### ISSUE TITLE
[Crash]: #9895 causes assertion failure in multiplayer

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#10016]
### Version of OpenTTD

Since #9895

### Steps to reproduce

Trigger functionality of #9895 by joining a multiplayer game when _company_manager_face is non-zero.

### Upload crash files

`[_company_manager_face](openttd: /home/jgr/openttd/trunk/src/script/api/../../command_func.h:378: static Tret CommandHelper<Tcmd, Tret (*)(DoCommandFlag, Targs ...), true>::Execute(StringID, void (*)(Commands, const CommandCost&, TileIndex), bool, bool, bool, TileIndex, std::tuple<_Tail ...>) [with Commands Tcmd = CMD_SET_COMPANY_MANAGER_FACE; Tret = CommandCost; Targs = {unsigned int}; StringID = unsigned int; CommandCallback = void(Commands, const CommandCost&, TileIndex)]: Assertion 'counter.IsTopLevel()' failed.)`

**Comment by 2TallTyler** [comment]
Sorry I didn't catch this in my PR testing. Not sure how this assert slipped through the cracks.

I'm not sure how to fix this, or why it's not working. ` Command<CMD_SET_COMPANY_MANAGER_FACE>::Post()` is used in the company GUI in the same manner. @JGR fixed it with `NetworkSendCommand()`, but I think that's depreciated in vanilla OpenTTD, correct?
