### ISSUE TITLE
Console: command autocompletion

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#1003]
**_bilbo_ opened the ticket and wrote:**

> I think it will be nice to have simple console command autocompletion (by using tab) as it is in quake console, bash, readline or basically most better consoles/shells
> .
> In some commands, using parameter autocompletion may be also useful.

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> See also #5904.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/1003#comment14604_

**Comment by TrueBrain** [comment]
Good idea! But not part of the current roadmap.

Of course we accept Pull Requests that implement this functionality.
