### ISSUE TITLE
[Bug]: Articulated Vehicles not showing correct capacity in buy menu

### ISSUE THREAD

**Issue by GarlicBread42** [OpenTTD/OpenTTD#10032]
### Version of OpenTTD

12.2

### Expected result

When a non-default cargo is chosen from the buy menu, vehicle should show the actual capacity of the whole vehicle.

### Actual result

If a non-default cargo is chosen from the buy menu, buy menu shows two lines of capacity.
One is displaying a wrong result for the default cargo the vehicle is coded in, the other line shows a different capacity.

![grafik](https://user-images.githubusercontent.com/96549054/190241297-48c304f3-5a65-4ca6-9d62-266f883f2668.png)
![grafik](https://user-images.githubusercontent.com/96549054/190241465-21dac2a4-f1a2-4118-af1c-606579584010.png)

When bought, the cargo capacity is as intended by the newgrf.
![grafik](https://user-images.githubusercontent.com/96549054/190241931-da59b358-676d-4b7e-ae12-eab27a1062bc.png)

### Steps to reproduce

1. Choose any articulated vehicle in the buy menu
2. Switch Cargo in buy menu to any refittable cargo.

**Comment by andythenorth** [comment]
One clarification to repro steps.  The bug doesn't manifest when the filtered cargo matches the default cargo for the units of the articulated vehicle.

**Comment by glx22** [comment]
Weight is wrong too.
#9954 is a related issue.
