### ISSUE TITLE
[Crash]: CTD and incorrect parameter value when adding GSInfo setting with certain int max values

### ISSUE THREAD

**Issue by Arastais** [OpenTTD/OpenTTD#10059]
### Version of OpenTTD

OpenTTD 12.2, Windows 10 64-bit

### Steps to reproduce

1. Create an info.nut file for a game script
2. Under the GSInfo derived class create a setting
3. Set the max value of this setting really high (as an example I did 4 billion, i dont know the exact range this happens at)
    - Note that setting this value too high (such as 4 trillion) will cause it to work normally. In this case, if you try to enter 4 billion as a value, it will stop typing at 400 million.
5. Set the other parameters of the setting to something random (It didn't matter in my testing)
6. Add a label for this setting for the value 0
7. Load the game into the "Configure Game Script Parameters" window
8. Click the dropdown (which is shown instead of a number picker)
9. Crash the game to desktop

See below for the screenshot at crash time. **I have attached a minimal game script setup to test this functionality:** [MinimalCTDTest.zip](https://github.com/OpenTTD/OpenTTD/files/9662175/MinimalCTDTest.zip)

**NOTE:** if you skip step 5 and do not put a label, the game will not crash but you will instead have incorrect parameters:
![image](https://user-images.githubusercontent.com/1361714/192705583-957250de-c773-4e61-bb88-2a3bf77c8e7d.png)
In this case, it does not show a drop down but the correct number picker, although it is grayed out. Inputting any number into the parameter will cause it to change from 0 to -29496729

### Upload crash files

The exception is "0xC0000094: The thread tried to divide an integer value by an integer divisor of zero."
[crash20220928063447.log](https://github.com/OpenTTD/OpenTTD/files/9662170/crash20220928063447.log)
![crash20220928063447](https://user-images.githubusercontent.com/1361714/192706368-d8be71ab-4c17-4d85-9361-cad4c2870004.png)

**Comment by James103** [comment]
Can reproduce in d843c8bd48 on Windows 10, 64-bit (via Steam) with the provided Game Script, triggering the following assertion in the process: https://github.com/OpenTTD/OpenTTD/blob/d843c8bd489082357f3f5a7e6a9fe77fbe5c18e1/src/widgets/dropdown.cpp#L146

Crash files: [crash20220928064727.zip](https://github.com/OpenTTD/OpenTTD/files/9662226/crash20220928064727.zip)

**Comment by glx22** [comment]
It's caused by implicit 64 bit to 32 bit conversions.
