### ISSUE TITLE
[Bug]: Can't remove railroad with drag and drop

### ISSUE THREAD

**Issue by condac** [OpenTTD/OpenTTD#10088]
### Version of OpenTTD

3b071f47e4b (master) Linux

### Expected result

Trying to remove railroad track using autobuild tool and remove function I get error that I can not remove track when using it in certain orientations and depending on where you start dragging.

### Actual result

Error dialog saying I can not remove track. 

### Steps to reproduce

Image showing some combinations that can not be removed using drag function. 
![removebug](https://user-images.githubusercontent.com/1023885/196178029-3050b2ff-5f58-4c4a-ba84-8b8ed1da7e64.png)

Using git bisect i have located the following:
db98cedb7e2a6028580fe9171542efb3422687c1 is the first bad commit
commit db98cedb7e2a6028580fe9171542efb3422687c1
Date:   Wed May 11 18:52:38 2022 -0600

    Fix #9883: Show cost/income float over end tile of rail or road construction

**Comment by James103** [comment]
Can reproduce in 3b071f47e4. It is only possible to remove diagonal track if the selection spans an odd number of pieces (1, 3, 5, 7, ...). If the selection spans an even number of pieces, the command fails. The actual number of pieces of track inside the selection does not matter. Straight track (aligned with the grid) can still be removed like before.

**Comment by 2TallTyler** [comment]
This was already fixed in dd26436. 🙂
