### ISSUE TITLE
[Bug]: Trains can continue unharmed even after destroying many road vehicles

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#10082]
### Version of OpenTTD

3e86f337a80 on Windows 10, 64-bit (this is an old problem)

### Expected result

When a train crashes into a road vehicle, the train should break down immediately or shortly after the accident, with a large penalty to its reliability rating. This encourages the player to get the train serviced ASAP so the damage can be repaired.

JGRPP implements this by forcing the train to break down (regardless of whether breakdowns are enabled), zeroing the train's reliability rating, and heavily reducing the train's max speed until it is serviced.

### Actual result

When the train crashes into a road vehicle, the train continues unharmed -- its reliability rating stays the same, continues dropping at the same rate, and the train would break down no sooner than if it didn't crash into a road vehicle.

### Steps to reproduce

1. Start a new game.
2. Build the setup shown below. 
![image](https://user-images.githubusercontent.com/37945304/196016954-8309a000-9138-4705-9b47-2690d6eb5cc5.png)
3. Buy a train and a road vehicle in the respective depots.
4. Make the train crash into a road vehicle.
5. The train continues unharmed.

Note: this is more difficult to reproduce in JGRPP or after https://github.com/OpenTTD/OpenTTD/pull/9931 due to new level crossing safety features.

**Comment by nielsmh** [comment]
This is by design, it's not a bug.
