### ISSUE TITLE
[Bug]: Reading Read Me/Changelog files is extremely tiring and probably harmful to the eyesight

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10091]
### Version of OpenTTD

All

### Expected result

The colors and the font used in the window allow you to easily read even long texts.
![Read me - x1 1](https://user-images.githubusercontent.com/67662046/197073087-54697b6e-a4ea-45ee-9e87-e649a6106b13.png)

### Actual result

The font, and especially the colors of the font and the background itself, make reading extremely tiring and probably also harmful to the eyesight.
![Read me - std](https://user-images.githubusercontent.com/67662046/197073301-a86f5704-cb9e-4158-9f3c-d5ec5c854754.PNG)

### Steps to reproduce

One example: Try reading the readme files of three selected game scripts (I recommend RWG, CB, ViV).

**Comment by LC-Zorg** [comment]
The simplest solution would be to change the font color from white to black. The effect is still far from good, but anyway much better.
![Read me - x0 1](https://user-images.githubusercontent.com/67662046/197075082-27ef8709-4b2a-4703-9f9f-2e3fd7abcaa3.png)

Changing the background color would also help. Gray seems like a reasonable and quite consistent choice here.
![Read me - x0 2](https://user-images.githubusercontent.com/67662046/197075140-8e06a6c6-2555-4f52-ab0c-7e90cdba5539.png)

For comparison, one more example with a lighter background color.
The font is the same as in the first example, is MS PGhotic (10) which for some reason is not available in the game.
![Read me - x1 2](https://user-images.githubusercontent.com/67662046/197075572-1a0f8789-c421-4d37-b30a-209412b4d2eb.png)

**Comment by LC-Zorg** [comment]
A few other examples, here with the Calibri (15) font that can be applied easily in the game. I checked a few others, but this one seems to be the most legible. Even without changing the colors it's pretty good. Smaller sizes have some glitch, 15 or 16 seem most suitable for FHD resolution.

![Licence, Readme, Changelog v2 1](https://user-images.githubusercontent.com/67662046/197259204-a5fc81b1-388f-494d-b177-59fea3f7650d.png)

![Licence, Readme, Changelog v2 1b](https://user-images.githubusercontent.com/67662046/197259230-2eb55392-e5ce-4567-9dfb-adc66a773156.png)

![Licence, Readme, Changelog v2 2](https://user-images.githubusercontent.com/67662046/197259251-e232b67e-cd4f-4cf8-a4ee-d4ca7e32d17c.png)

![Licence, Readme, Changelog v2 3b](https://user-images.githubusercontent.com/67662046/197259277-faec18bf-5093-461c-b16f-ad3370391f02.png)

And again the current form to emphasize the need to change. ;)
![Licence, Readme, Changelog v1 0](https://user-images.githubusercontent.com/67662046/197259407-f32ccdfd-7f04-4e84-8b3d-8e6102d9b42e.png)

**Comment by Arastais** [comment]
The readme part of this issue should be (at least mostly) fixed with what #7786 does, which adds highlighting to Internal anchor and web links. That's honestly even better than just changing the font, background, and text color of the readme.

**Comment by LC-Zorg** [comment]
Adding the option to create links will in no way improve the readability of these files, especially existing ones. Moreover, this whole help and manuals window will be just as cumbersome to use as the current readme / licence / changelog files. This is one of the reasons why it should be improved.
