### ISSUE TITLE
[Bug]: Windowed mode white screen issue with multiple monitors

### ISSUE THREAD

**Issue by ageekhere** [OpenTTD/OpenTTD#10099]
### Version of OpenTTD

OpenTTD 12.2 - Windows 11

### Expected result

Set OpenTTD to run as windowed mode and then stretch out the game window across multiple monitors, exit the game, start the game, the game should run.

### Actual result

If OpenTTD was closed while having the game window stretch across multiple monitors the next time OpenTTD starts it will hang and show a white screen.

### Steps to reproduce

1. Disable fullscreen
2. Stretch out game window across multiple monitors (in my case 3x 1920x1080 monitors).
3. Exit the game
4. Start the game, you now get a white screen and the game hangs

**Comment by PeterN** [comment]
Cannot reproduce here, at least across 2 monitors.

**Comment by ageekhere** [comment]
I am running windows 11, I do not remember having this issue with windows 10.

**Comment by krysclarke** [comment]
Unable to re-produce on Debian Sid with v12.2, running 2x 1920x1080 monitors.

Is this a Windows-only (Windows 11-only??) issue?

Did you stretch the OpenTTD window across some/all of your 3 monitors, or just across two of them?

**Comment by ageekhere** [comment]
Ah, did some more tests, the bug happens when the window passes a certain size.
So in my case 5760x1080, if i make the window 1920x1080 but across multi monitors it does not have the issue.

**Comment by James103** [comment]
What is the make and model of your GPU?

Full output from `dxdiag.exe` (run, wait for progress bar, then click Save All Information) if you can.

**Comment by ageekhere** [comment]
It is a GeForce RTX 3060 TI, come to think of it I had a 1060 the last time i played.

**Comment by nielsmh** [comment]
I'm not reproducing it either. Windows 10 with GeForce RTX 2060, OpenTTD 12.2 with hardware acceleration enabled.
I stretched the game out to about 5700 pixels wide across two monitors (3840x2160 and 1920x1080), quit the game, started again. The restored window after restarting the game was smaller than when I quit it.

**Comment by James103** [comment]
> I stretched the game out to about 5700 pixels wide across two monitors (3840x2160 and 1920x1080), quit the game, started again. The restored window after restarting the game was smaller than when I quit it.

1. What was the value of `resolution` in the `[misc]` section of `openttd.cfg` when you closed the game?
2. What is the approximate size of the window relative to the monitors when you restarted the game?

Since your monitors were of different resolutions, it's possible stretching the game window across both the 4K and HD monitors then restarting caused the size to be stored as if on the HD monitor, but the window opened on the 4K monitor.

**Comment by ageekhere** [comment]
I done some more tests, with 3 1920x1080 monitors, the max width resolution is 5743 before you get the white screen bug.
So for now I have just set my resolution to 5743x1103 (the height is set a bit higher to cut of the white bar at the top).

**Comment by krysclarke** [comment]
Setting my resolution to 5744x1000 in stock 12.2 on Debian Sid loaded fine.  FAR too wide for my 2x 1920x1080 screens, but I got through to the titlescreen.
Increasing the resolution to 6000x1200 didn't lock it up, either.

**Comment by ageekhere** [comment]
I am starting to think it could be a windows 11 issue.

**Comment by ageekhere** [comment]
This now seems to be fixed.
