### ISSUE TITLE
[Crash]: Crash trying to build objects on area

### ISSUE THREAD

**Issue by leonengel** [OpenTTD/OpenTTD#10135]
### Version of OpenTTD

13.0-beta1 (2022-10-31)

### Steps to reproduce

1. Selected an object
2. Tried drag-and-drop on an area
3. Game crash

### Upload crash files

[OpenTTD13BetaCrash.zip](https://github.com/OpenTTD/OpenTTD/files/9943623/OpenTTD13BetaCrash.zip)

**Comment by James103** [comment]
Can reproduce in d48a48b2cf using OpenGFX Landscape NewGRF.

The wind turbines have placement restrictions which means no two turbines can be on adjacent tiles.

The test run returns with an estimate of 9 turbines able to be constructed on a 3x3 area, but actually only 5 turbines can be constructed in the same area. This differences results in a cost difference between the test run and the exec run, which triggers an assert; therefore, the game crashes.
