### ISSUE TITLE
[Drawback]: Small font is unreadable at default size and most popular screen resolutions.

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10153]
### Version of OpenTTD

12.2 (the problem concerns the currently dominant resolutions (from HD to QHD), where the player still wants to use the original interface size)

### Expected result

The default small font is large and clear enough to be readable, but at the same time still small and doesn't increase the size of the interface unnecessarily.

![Arial 10 + leading improvement](https://user-images.githubusercontent.com/67662046/201241355-df08d3a0-18fb-4e61-980d-e0a046fb02f7.png)

### Actual result

The default small font is unreadable with the default size setting. The game allows you to change it, but it is an option hidden from most players. But even if it were readily available, I still think the default one should be fine for most players.

![Current default small font](https://user-images.githubusercontent.com/67662046/201241448-55242e98-0ebe-4a98-bd8e-2c09cb9aab66.png)

### Steps to reproduce

I suppose most of you have long ago changed this font or use a font size multiplier. So if you have access to a not very large monitor with average resolution, restore the default settings and feel what most players are still experiencing. ;)

**Comment by glx22** [comment]
It's a [known issue with workaround](https://wiki.openttd.org/en/Archive/Community/FAQ%20troubleshooting#my-user-interface-is-too-small-to-read-my-font-is-unreadable-or-faulty)

**Comment by Monkeycat-nl** [comment]
So... uhm my dad can play the game (he is learning)... 

He has no idea about editing config files... or workarounds. 
Font resolution should be adjusted to screen resolution... automatically...
Or at least be in the config menu...

For god sakes... he is using a real magnifying glass to see the profits of his trains... for the last week.

**Comment by glx22** [comment]
There is now the `font` console command to change fonts.
![image](https://user-images.githubusercontent.com/2952192/225485618-943ce224-d32e-4eef-9f19-e65ab4595a5e.png)
Still not ideal, but easier than editing config file.
