### ISSUE TITLE
[Bug]: Finance window: Category names are abbreviated in many languages (1/6)

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10159]
### Version of OpenTTD

13.0-beta1

### Expected result

The window adjusts the width to the length of the category names, never shortening them.

### Actual result

The window doesn't adjust to the length of category names, so in many languages they are truncated.
![76A](https://user-images.githubusercontent.com/67662046/201499135-08859790-f5a5-443b-b118-b0a9c4245ff1.png)

### Steps to reproduce

Open the finance window and change the language to for example:
- German
- Spanish
- Czech
- Polish
- Danish
...

**Comment by LordAro** [comment]
Cannot reproduce with the sprite font. Window resizes as you'd expect both with and without the finance window actually having numbers to display
(Win10) Possibly already fixed by #10114 ? Can you try the a newer nightly? (20221113+)

**Comment by PeterN** [comment]
Yes, this is fixed by #10114.
