### ISSUE TITLE
[Bug]: Names of cities on the map are shortened pointlessly after changing the font

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10150]
### Version of OpenTTD

12.2 (not new bug)

### Expected result

City names are only shortened if they are really long or they are never shortened.

### Actual result

After changing the font, the names of cities on the game map (zoom out) are shortened against any visible logic. Very often, short names are abbreviated while long names remain unchanged. Moreover, the abbreviated name of the city + ... also very often have the same or very similar length as not abbreviated. This is rare for original English names and quite common for Fictional Town Names. Not all fonts are affected.

![small Arial](https://user-images.githubusercontent.com/67662046/201233058-495bae0e-7449-4b34-8d8c-23df20290e30.png)

![small Verdana](https://user-images.githubusercontent.com/67662046/201233079-1d46e8ad-466f-4882-b610-3536c75db0c9.png)

![Better town names](https://user-images.githubusercontent.com/67662046/201233428-0fdc0ae7-fdd7-4979-a2e0-577360884eb3.png)

![Better town names 2](https://user-images.githubusercontent.com/67662046/201233692-a020bce8-c950-45a8-a08e-6eee45b2e7db.png)

### Steps to reproduce

1. Change small font to Arial, Calibri or Verdana.
2. Generate a map with multiple cities, preferably with some add-on that change the names of the cities.
3. More or less of the cities will have a shortened name in the zoom out view.

**Comment by PeterN** [comment]
I cannot reproduce this, please provide a save game.

**Comment by LC-Zorg** [comment]
After skimming the map quickly, I found some 30-40 abbreviated names. All of them pointless. 
Font: Arial Size: 10

![only few bugs](https://user-images.githubusercontent.com/67662046/201238217-b74d7db8-04de-4a42-9723-966451bb2753.png)

[City names bugs, 2054-03-25.zip](https://github.com/OpenTTD/OpenTTD/files/9985619/City.names.bugs.2054-03-25.zip)

**Comment by PeterN** [comment]
Still unable to reproduce...

![image](https://user-images.githubusercontent.com/639850/201239340-3ac60246-ed84-4eab-9795-1927ed0b5357.png)

![image](https://user-images.githubusercontent.com/639850/201239597-7e9ea657-2f9b-4a43-96d6-571cc927752d.png)

**Comment by PeterN** [comment]
Weird one, I've finally managed to replicate this. For ease of debug a single-town map, with the town renamed to 'X-Town' and small font set to Tahoma Bold.

The issue seems to be that calling the string Layouter with FS_SMALL produces a different result than calling with FS_NORMAL, even when the first thing the string does is switch to FS_SMALL.

So for me the sign is calculated as 86 pixels, but when it comes to drawing it's calculated as 88 pixels. I also don't know why this doesn't affect all small signs...
