### ISSUE TITLE
[Detail]: Finance window - Too large offset of the yellow text (3/6)

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10162]
### Version of OpenTTD

13.0-beta1

### Expected result

The layout of the window is aesthetic and consistent with other elements of the interface
![76C3](https://user-images.githubusercontent.com/67662046/201499585-4db8f89e-2e83-4c31-946e-cd14874239e8.png)

### Actual result

![76C](https://user-images.githubusercontent.com/67662046/201499502-117cce4c-674c-44e1-b657-0b691d168f90.png)
Maybe it's a matter of taste, maybe habit, but I don't like such a big shift. It's also a bit inconsistent. There is now one list window where offset has been applied, this is the Infrastructure window. There the indentation is 2 instead of 9 pixels and in my opinion it looks much better. The indentation is also used for the list of vehicle groups and it is much larger, but everything is in one color there. Also, in many other languages these yellow titles are much longer, so this indentation will increase the size of the window a bit.

I propose the same solution that is used in the case of the infrastructure window.

### Steps to reproduce

n/a

**Comment by PeterN** [comment]
It is now indented to the same level as other indented text. Perhaps it doesn't need to be indented at all as it is a different colour.

**Comment by michicc** [comment]
If anything is wrong here, I would vote for the infrastructure window, not the finance window.

**Comment by PeterN** [comment]
The colours are still inconsistent, but the indentation is the same since #10114 
![image](https://user-images.githubusercontent.com/639850/201517436-ca8ad860-120b-48f3-ad20-89d444920b2f.png)

**Comment by 2TallTyler** [comment]
Indeed, I'm working on a branch to make the Infrastructure window match the Finance window. The indentation amount was discussed in #9827 and increased by request of @TrueBrain who felt that 2px wasn't enough.
