### ISSUE TITLE
[Bug]: Finance window - The title "Net profit" is most probably wrong (2/6)

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10160]
### Version of OpenTTD

13.0-beta1

### Expected result

Titles in the finance window accurately refer to reality, but at the same time take into account the reality of this game and are not misleading.

### Actual result

I'm not fully convinced that "net profit" is the right title to summarize the company's annual financials. Depending on the country and tax system, these terms may have slightly different meanings. To me, this title seems confusing and not entirely appropriate in this game. First of all, the amount is not always positive, so the phrase "profit" will not always be accurate. Secondly, "net profit" is not a final summary of the annual finances. Dividends are deducted from the net profit. In the case of this game, all dividends go to the owner of the company, i.e. the player, or simply to the company's account. Dividends can also be extracted by script and in the future theoretically they may become an integral part of the game, but in the current form this cannot be done because you cannot subtract anything from the final amount. It seems to me that a more accurate term here  
would be "Financial result", which can be both positive and negative, can include dividends paid and is a de facto summary of all income and expenses.
![76B](https://user-images.githubusercontent.com/67662046/201499286-7fc450e4-2799-49f6-bf8f-0bac4f2f2965.png)
From wikipedia:
![Financial result wiki](https://user-images.githubusercontent.com/67662046/201499346-45a845ea-5c01-4ea2-bedd-fbb76dcccd43.svg)

### Steps to reproduce

An economist would be helpful here...

**Comment by LordAro** [comment]
"Net profit" could well be a bit dubious, however to my non-economist eyes, "Financial result" is overly vague and generic. OTTD is not an economy simulator, so I'm not too concerned regardless, but perhaps "Total profit" would suffice? Or even just "Profit" ?
