### ISSUE TITLE
[Detail]: Finance window - The location of total of revenues or expense seems not entirely legible and confusing (4/6)

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10163]
### Version of OpenTTD

13.0-beta1

### Expected result

The layout of the information is legible, not overloaded, easy to get used to.

### Actual result

The location of the revenues or expense summary can be confusing, especially when not all lines are filled in.
In this arrangement, it looks a bit like the value from the above part is assigned to the one below. In my proposal, that's why I put the summary at the top of the lists. This is not a rare solution, but well... If you keep the same layout as before, perhaps it would be better to use the existing solutions as well. Anyway, I see several solutions. Will post them in separate posts. Please rate what you think is better.

### Steps to reproduce

n/a

**Comment by LC-Zorg** [comment]
1. No changes
![76D](https://user-images.githubusercontent.com/67662046/201499696-1f4929de-0216-47aa-b851-c5525f4d596f.png)

**Comment by LC-Zorg** [comment]
2. Summaries not highlighted (A)
![76DA](https://user-images.githubusercontent.com/67662046/201499714-336dd30a-b3d3-498c-ad76-9cb61315d38f.png)

**Comment by LC-Zorg** [comment]
3. Adding a title for the summary
![76DB](https://user-images.githubusercontent.com/67662046/201499741-247c5d88-f7ea-464f-b83a-53264aaae736.png)

**Comment by LC-Zorg** [comment]
4. No highlighting of summaries + addition of a title for the summaries (A+B)
![76DBA](https://user-images.githubusercontent.com/67662046/201499761-4f7ff7d2-dffb-4a4a-afb0-fb5213338993.png)

**Comment by LC-Zorg** [comment]
5. Separating individual parts with lines (C)
![76DC](https://user-images.githubusercontent.com/67662046/201499793-16c27984-3c44-4deb-8d1b-3f2b43a0b976.png)

**Comment by LC-Zorg** [comment]
6. Separating individual parts with lines + moving the summary to the top and aligning it with the title (C+D)
![76DCD](https://user-images.githubusercontent.com/67662046/201499814-c80ffbdc-82d4-4013-b0bb-2cdfb93cac06.png)

**Comment by 2TallTyler** [comment]
For what it's worth, I prefer option 6 and had originally designed it this way in #9827, but that was rejected as confusing.

I also like option 5 but there's currently no precedence in other GUIs.

So I'm going with option 3, which is how it was prior to #9827.
