### ISSUE TITLE
[Bug]: In Arabic and Hebrew, the pointer on the interface scale slider is incorrect.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#10164]
### Version of OpenTTD

ced4258969 on Windows 10, 64-bit (via Steam)

### Expected result

The pointer on the interface scale slider is correct even in RTL languages.

### Actual result

The pointer on the interface scale slider is incorrectly positioned in RTL languages.

As shown, the interface scale is actually 1x albeit the widget shows it as 3x.
![image](https://user-images.githubusercontent.com/37945304/201499715-49f01e95-8a50-4448-8e35-79be883dd333.png)

Furthermore, attempting to change the interface by clicking and drag often leads to the incorrect value being set.

### Steps to reproduce

1. Start OpenTTD.
2. Switch language to Arabic or Hebrew.
3. Click on the pointer on the interface scale slider.
4. The interface scale is set to 3x.

**Comment by PeterN** [comment]
Weird, I did testing with RTL and never saw this... Hmmmmmmmmmmmmm
