### ISSUE TITLE
[Bug]: The texts are out of place with true type fonts

### ISSUE THREAD

**Issue by stormcone** [OpenTTD/OpenTTD#10161]
### Version of OpenTTD

OpenTTD 20221112-master-gced4258969

### Expected result

The text are readable like with the sprite fonts.

Something like this:
![sprite_font](https://user-images.githubusercontent.com/48624099/201499303-6bd04345-c29e-49be-a5be-0dad149b1b58.png)

### Actual result

The texts are unreadable with true type fonts.

![tt_font](https://user-images.githubusercontent.com/48624099/201499320-a616f6ae-dbc0-4cae-ac3d-9f2669ba1878.png)

### Steps to reproduce

- Set system fonts in openttd.cfg.
- Start OpenTTD

### Additional info

Os: Fedora 36

./openttd -d driver=3:
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Resolution for display: 1920x1057
dbg: [driver] SDL2: Mouse is at (684, 655), use display 0 (0, 0, 1920, 1080)
dbg: [driver] SDL2: using mode 1920x1057
dbg: [driver] SDL2: using driver 'x11'
dbg: [driver] OpenGL driver: NVIDIA Corporation - NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 (4.6.0 NVIDIA 520.56.06)
dbg: [driver] OpenGL: Using persistent buffer mapping
dbg: [driver] OpenGL shading language version: 4.60 NVIDIA, texture units = 192
dbg: [driver] Successfully probed video driver 'sdl-opengl'
dbg: [misc] String too long for destination buffer
dbg: [driver] Successfully probed sound driver 'sdl'
dbg: [driver] Successfully probed music driver 'extmidi'
dbg: [driver] using thread for game-loop
dbg: [driver] Switching blitter from '32bpp-anim' to '40bpp-anim'... 
dbg: [driver] Successfully loaded blitter '40bpp-anim'
dbg: [driver] Successfully switched to 40bpp-anim.
dbg: [driver] SDL2: using mode 1920x1057
dbg: [driver] extmidi: set volume not implemented

openttd.cfg snippet:
small_font = Liberation Sans
medium_font = DejaVu Sans
large_font = Liberation Serif
mono_font = Liberation Mono
small_size = 12
medium_size = 16
large_size = 26
mono_size = 14
small_aa = true
medium_aa = true
large_aa = true
mono_aa = true

**Comment by krysclarke** [comment]
Unable to replicate on Debian (sid) with OpenTTD 20221111-master-g59645c6733.
Replicated openttd.cfg configuration snippet and changed blitter and resolution values to match debug output.

./build/openttd -d driver=3
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Resolution for display: 1920x1057
dbg: [driver] SDL2: Mouse is at (1491, 626), use display 0 (0, 0, 1920, 1080)
dbg: [driver] SDL2: using mode 1920x1057
dbg: [driver] SDL2: using driver 'x11'
dbg: [driver] OpenGL driver: nouveau - NVA8 (3.3 (Compatibility Profile) Mesa 22.2.3)
dbg: [driver] OpenGL: Using persistent buffer mapping
dbg: [driver] OpenGL shading language version: 3.30, texture units = 64
dbg: [driver] Successfully loaded video driver 'sdl-opengl'
dbg: [driver] Successfully probed sound driver 'sdl'
dbg: [driver] allegro: no midi card found
dbg: [driver] Probing music driver 'allegro' failed with error: No sound card found
dbg: [driver] Fluidsynth: sf (null)
dbg: [driver] Fluidsynth: samplerate 44100
dbg: [driver] Successfully probed music driver 'fluidsynth'
dbg: [driver] using thread for game-loop

Also, when I changed to using the 40bpp-anim blitter, it made no change.

**Comment by PeterN** [comment]
Confirmed on my old Debian 10 laptop. Takes ages to compile so may be a while :-)

**Comment by PeterN** [comment]
Hmm, well, I've broken FallbackParagraphLayout -- it's used for both Freetype and Sprite fonts. On Windows and OS there are system-specific layouters that know the difference between truetype and sprite glyphs.
