### ISSUE TITLE
[Detail]: Finance window - Information about the interest rate is redundant now (6/6)

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10166]
### Version of OpenTTD

13.0-beta1

### Expected result

The interest rate information I included in my drafts was related to the variable rate idea. For example, it would grow significantly during a recessions. Then this information would be of significant importance to the player. It could also be significant if the upper interest rate limit were significantly raised.

### Actual result

I'm not sure if it makes sense to post this information now. The difference between 2% and 4% costs is almost imperceptible in most cases, and I doubt anyone cares, so there's little point in permanently putting this information on top. Unless you have any plans for what it is.
![76F](https://user-images.githubusercontent.com/67662046/201500137-935fe55b-8d66-4bc1-85e1-f84b61e8242c.png)

### Steps to reproduce

n/a

**Comment by 2TallTyler** [comment]
Future interest rate features can still be implemented, but we try to avoid mixing multiple features within a Pull Request. (I'm not currently planning to add these features, to be clear.)

I think it makes sense to include the interest rate with the maximum loan. In any case...this isn't a bug, just a matter of personal taste. 🙂
