### ISSUE TITLE
[Detail]: Finance Window - The financial summary can be confusing (5/6)

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10165]
### Version of OpenTTD

13.0-beta1

### Expected result

The design of the window takes into account the players habits of the layout where the number at the top was the most important.

### Actual result

It may be hypersensitivity, but it may be worth paying attention to. In my proposal, apart from naming the missing category and changing the order, it was important to use different colors of the text to mark what is less and what is more important. This is missing in its current form, and since the order has been changed, it's possible that this will at least initially confuse players. For me it is confusing now.

There are a bit of possibilities, some of which I will present below in separate posts.

### Steps to reproduce

Play a bit 13.0
When you want to buy a new vehicle to see if you can afford it, what amount are you looking at: own funds at the top or bank balance at the bottom?

**Comment by LC-Zorg** [comment]
1. Leave this unchanged
![76A](https://user-images.githubusercontent.com/67662046/201499906-14c4d3c1-1a41-41eb-9543-0ac04fd900c1.png)

**Comment by LC-Zorg** [comment]
2. "Own Funds" and "Loan" in grey
![76EA](https://user-images.githubusercontent.com/67662046/201499929-1eae15b3-79db-430d-b4bf-6b66f3cec46e.png)

**Comment by LC-Zorg** [comment]
3. Highlighting the main amount (the most important from the player's point of view) in white (B)
![76EB](https://user-images.githubusercontent.com/67662046/201499972-e6b04fdd-8ab5-4eb8-9ca4-67fdb5ce20cc.png)

**Comment by LC-Zorg** [comment]
4. Marking "Own funds" and "Loan" in gray and highlighting the principal amount in white (A+B)
![76EBA](https://user-images.githubusercontent.com/67662046/201499988-c342e24a-b0ed-4bd6-8bb1-223d441ec32c.png)

**Comment by LC-Zorg** [comment]
5. Restore the original order with the bank balance at the top above the line and own funds at the bottom (R)
![76ER](https://user-images.githubusercontent.com/67662046/201500005-730f434e-2558-46e2-88b2-91a8748526d2.png)

**Comment by LC-Zorg** [comment]
6. Restored to original order and marked "Own funds" and "Loan" in grey (R+A)
![76ERA](https://user-images.githubusercontent.com/67662046/201500014-835340df-1939-4443-8fc1-46b2f6a0467c.png)
Here with a similar layout also in the main part.

**Comment by LC-Zorg** [comment]
7. Restored to original order, marking "Own funds" and "Loan" in gray and highlighting the principal amount in white (R+A+B)
![76ERBA](https://user-images.githubusercontent.com/67662046/201500057-b3483e40-8504-416b-a9f4-7801eb0e0e0d.png)

**Comment by michicc** [comment]
In general, I'm not convinced that the finance window needs this many changes, but at least for this specific point here, option 3 is indeed more consistent with how the other partial sums are presented.
