### ISSUE TITLE
[Bug]: Error messages are bigger as of the recent UI changes

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#10174]
### Version of OpenTTD

cbb2d5303d on Windows 10, 64-bit

### Expected result

Error messages should be about the same size as before the recent UI changes / release 12.2 and older.

One line:
![image](https://user-images.githubusercontent.com/37945304/201778315-0492766e-fbf8-4743-82fa-5cc4430b8147.png)

Two lines:
![image](https://user-images.githubusercontent.com/37945304/201779312-8d2e829c-d655-49e4-af37-2d7ae9353c26.png)

### Actual result

Error messages are significantly bigger (wider and taller) compared to 12.2 and older.
This happens even on 1x interface scaling which all screenshots were taken at.

One line:
![image](https://user-images.githubusercontent.com/37945304/201778520-73bc4061-feb1-4dfe-8d4d-0fbfebaa6304.png)

Two lines:
![image](https://user-images.githubusercontent.com/37945304/201779363-5f21ef87-04a5-46b4-a572-61a18c72af62.png)

### Steps to reproduce

1. Start OpenTTD.
2. Trigger any error message.
3. Notice the message is significantly bigger compared to in older releases.

**Comment by PeterN** [comment]
Bug, or feature?

**Comment by ldpl** [comment]
Vertical feature horizontal bug xD

**Comment by PeterN** [comment]
If you want to play with and suggest a better size, it's the new `modalpopup` dimension, defined in `widget.cpp:152`.

**Comment by 2TallTyler** [comment]
I'd expect a two-line message to be taller than a one-line message, and the old message appears to have been lacking proper text padding.

Not a bug, although PRs are open if somebody wants to resize it. 🙂
