### ISSUE TITLE
[Detail]: Permissive Local Authorities - improper, confusing order of options in the settings window

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10182]
### Version of OpenTTD

13.0-beta1

### Expected result

The order of the settings is maintained on a scale from the mildest to the most severe.

![Local authority - order on the list](https://user-images.githubusercontent.com/67662046/202867269-a87bf3a7-3b07-48ba-9e77-e2398429adb9.png)

### Actual result

The order of settings is at least wrong in my opinion. Ever since I've known this game, the order of settings has been scalable: mildest at the top, most severe at the bottom. Option scaling is applied to all settings but not here (this issue also applies to tree growth settings). It is currently mixed and inconsistent. Swapped setting names, where the new setting has the old name and the old with the new one, don't help here.

![Local authority - wrong order](https://user-images.githubusercontent.com/67662046/202867333-e1f6c698-73d9-4e87-983c-4d56cfccad76.png)

### Steps to reproduce

n/a

**Comment by PeterN** [comment]
This is the internal order of the options. There is no abstraction between that and the displayed list.

Probably TMWFTLB.

**Comment by 2TallTyler** [comment]
Not a bug. PRs to change it accepted.
