### ISSUE TITLE
[Bug]: no message to player when industry prospecting fails

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/OpenTTD#10181]
### Version of OpenTTD

Any release up to 13.0 beta

### Expected result

When prospecting for industries, if the prospecting fails, it doesn't fail silently.

### Actual result

If prospecting fails, it fails silently, apart from deducting money from player's bank balance.

I'm not sure this qualifies as a bug, it's a UX issue / suggestion.

Not sure what the best implementation would be:

- news message is probably overkill, but doesn't need dismissed
- red modal message would have to be dismissed, which is annoying if prospecting repeatedly fails

Rolling-dice animated gif anyone?

### Steps to reproduce

1. set primary industry funding model to 'prospecting'
2. with an industry type where prospecting chance isn't 100% (most primaries), try and prospect a primary industry until the prospecting fails
3. observe that there's nothing to tell you it failed

**Comment by glx22** [comment]
Fixed with #10202
