### ISSUE TITLE
[Bug]: Road vehicles icon displaced on original_windows baseset

### ISSUE THREAD

**Issue by DefinitelyNotRau117** [OpenTTD/OpenTTD#10197]
### Version of OpenTTD

OpenTTD 13.0-beta2 Windows10

### Expected result

Correct icon layout as in previous versions
![изображение](https://user-images.githubusercontent.com/115672237/204277857-40564718-639a-454e-8892-84112bb6f7ca.png)

### Actual result

The road transport icon moved up in the menu bar
![изображение](https://user-images.githubusercontent.com/115672237/204278196-923e3e77-f04c-4733-b80b-48c0a338aa12.png)

### Steps to reproduce

1. Install original_windows baseset
2. Start the game

**Comment by PeterN** [comment]
This is intentional for now. This affects a few buttons, but this one and the landscape button in the mini-map window are most noticeable.

**Comment by DefinitelyNotRau117** [comment]
I remember there were new icons made specifically for openttd with original baseset (openttd.grf), maybe this can be repeated for all displaced icons?
