### ISSUE TITLE
[Bug]: NRT road tunnels lack custom overlays

### ISSUE THREAD

**Issue by PikkaBird** [OpenTTD/OpenTTD#10208]
### Version of OpenTTD

13.0 b2

### Expected result

Creating a good-looking NRT road tunnel is almost impossible, because the game always overlays a standard road tile on top of the tunnel underlay.

![Untitled](https://user-images.githubusercontent.com/39507755/205177236-93aa81b7-0af9-44f1-8df3-85e815e404bc.png)

Image shows a rail tunnel, a road tunnel as built (with the roadtile overlayed), and the road tunnel as drawn (mocked in). There is currently no way to change or hide the overlayed road tile.

### Actual result

Newgrf authors should be able to specify a custom overlay (as with Railtype action 3 cargo 03). This would not break compatibility with existing newgrfs (which will continue to work as before if the action 3 is not defined), nor would it cause conflicts between road + tram each providing graphics for the tile; a custom tram overlay will simply appear above a custom road overlay, as with the defaults.

see https://github.com/OpenTTD/nml/issues/79 for some further discussion.

### Steps to reproduce

Build a road tunnel with any NRT road grf.

**Comment by glx22** [comment]
Something similar to railtype action3 cargo 03 should be fine. I may look into implementing that.

**Comment by PikkaBird** [comment]
Thanks. :)

Here is a test grf, using cargo 03 for the overlay sprites - hopefully I put them in the right order!

[tunneltest.zip](https://github.com/OpenTTD/OpenTTD/files/10203691/tunneltest.zip)

**Comment by glx22** [comment]
I modified your test grf for it to work in my branch.
Only 2 sprites are needed for tunnels, Y and X, so I used bridge ones for the test.
[tunneltest_modified.zip](https://github.com/OpenTTD/OpenTTD/files/10204338/tunneltest_modified.zip)

**Comment by PikkaBird** [comment]
Thanks. :) FWIW here is the test grf again with only two overlay sprites.

[tunneltest.zip](https://github.com/OpenTTD/OpenTTD/files/10204501/tunneltest.zip)

I'm not sure whether the default behaviour if the action 3 is not should be no overlay sprite, or the default road overlay. The former is more consistent with how rail tunnels work, but the latter would keep the current behaviour for existing newgrfs.

**Comment by PikkaBird** [comment]
Actually, why are only two sprites needed? There is a little bit of road visible on the upper tunnel sprites, which could be more if the tunnels were drawn in a different style. The rail tunnel overlays have four sprites for this reason.

**Comment by glx22** [comment]
When drawing a tunnel only Y and X overlays are used, that's why I used bridge middle sprites as underlay in my test grf.
But indeed 4 sprites would probably be better. I'll try things.
![image](https://user-images.githubusercontent.com/2952192/206962740-2ca4996f-3b37-42ad-b389-d0bc46fe9638.png)

**Comment by PikkaBird** [comment]
For the test GRF, I used the whole tunnel sprite as the overlay (which should work perfectly fine, graphically speaking). Like I say it's possible/probable I have them in the wrong order though. :)

**Comment by glx22** [comment]
The order was still wrong :) (it's the same as in actionA)
Fixed test grf :[tunneltest.zip](https://github.com/OpenTTD/OpenTTD/files/10212234/tunneltest.zip)

![image](https://user-images.githubusercontent.com/2952192/207160321-9a4360a2-754c-4c02-b86d-dee4f2296a7e.png)

BTW the sprites in test grf seem to have alignment issues.

**Comment by PeterN** [comment]
> 



> BTW the sprites in test grf seem to have alignment issues. And of course it's only a test, a real grf should not redraw the tunnel entrance with underlay.

They're built for fixed offsets, the standard basesets are off-by-one (off-by-four at max zoom) :-)
