### ISSUE TITLE
[Bug]: Scriptable league table minor issues

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#10214]
### Version of OpenTTD

Since #10001

### Expected result

N/A

### Actual result

LeagueTable has fields title, header and footer, but the saveload code only saves the title.

CMD_CREATE_LEAGUE_TABLE/CmdCreateLeagueTable does not set CMD_STR_CTRL, unlike all the other similar commands.
This seems to result in strings passed via GSText (i.e. using SCC_ENCODED) being clobbered for network clients.

Edit:
The graphs and leagues buttons in the toolbar no longer have a default action.
Clicking them without holding to access the dropdown no longer does anything.
Clicking the graphs button should open the operating profit graph and clicking the league button should open the company league table.

### Steps to reproduce

N/A

**Comment by LordAro** [comment]
cc @ldpl
