### ISSUE TITLE
[Bug]: Banks of wide rivers on sloped terrain

### ISSUE THREAD

**Issue by chujo-chujo** [OpenTTD/OpenTTD#10218]
### Version of OpenTTD

OpenTTD 13.0-beta2, Windows 8

### Expected result

Normal banks of a river delta:

![river00](https://user-images.githubusercontent.com/91337649/205629181-036222d0-da01-4d77-a083-e0b07c57f484.PNG)

### Actual result

Banks that appear when there is a slope next to a river delta:

![river01](https://user-images.githubusercontent.com/91337649/205629893-8e64786c-cb3b-419c-b187-1db95b60d310.PNG)

![river02](https://user-images.githubusercontent.com/91337649/205629922-74bcaf09-d675-414e-8563-537223fc752c.PNG)

### Steps to reproduce

1. Random world generation with Terrain type: Mountainous, Variety distribution: Medium, Smoothness: Smooth or Rough

**Comment by PikkaBird** [comment]
This is just a graphical error with the sprite, isn't it? ie that river bank sprite should not have a coastline included.

**Comment by PikkaBird** [comment]
![Chundnor End Transport, 1902-12-23](https://user-images.githubusercontent.com/39507755/206976338-398fb73b-c82e-4353-9a3a-3bb181f38491.png)

Another example generated with different ground sprites - still not ideal, but without the extra water line created by the graphical error in the base set.

**Comment by zephyris** [comment]
@PikkaBird What base set is that? It's not clear to me how to code the base set to achieve that.

**Comment by Brickblock1** [comment]
it isn't a base set but a grf https://bananas.openttd.org/package/newgrf/44444401
