### ISSUE TITLE
[Bug]: Train speed vs. Aircraft speed

### ISSUE THREAD

**Issue by legitalk** [OpenTTD/OpenTTD#10226]
### Version of OpenTTD

13.0-beta2, nightly(20221205), probably for always bug

### Expected result

Aircraft speed is much lower than train speed compared to km/h.

Example:
1. Train machine Lev4 'Chimaera' max. speed 643 km/h
2. Aircraft Dinger 200 max. speed 952 km/h

So during the gameplay above aircraft should fly faster then train machine, but it is not, is flying probably 3x or even 4x slower.

For compare aircraft Dinger 1000 with max. speed 2 329 km/h is during the game play flying almost similar speed as Lev4 'Chimaera', which has 4x lower max. speed.

**_PS1: All aircrafts are flying in wrong speed based on the max. speed._**

**_PS2: Based on https://www.tt-forums.net/viewtopic.php?t=25272 the issue is there since 2006, where planes are 1/4 slower_**

### Actual result

1. Aircraft Dinger 200 should be approx. 1.5x faster than train machine Lev4 'Chimaera'
2. Aircraft Dinger 1000 should be approx. 4x faster than train machine Lev4 'Chimaera'

### Steps to reproduce

1. Build train machine Lev4 'Chimaera'
2. Build aircraft Dinger 200
3. Build aircraft Dinger 1000
4. Compare the speed during the game play

**Comment by PeterN** [comment]
![image](https://user-images.githubusercontent.com/639850/206474854-02dd8cd8-ac6b-4e2f-b43a-71d158f747d7.png)

Not a bug.

**Comment by glx22** [comment]
It's explained [here](https://wiki.openttd.org/en/Manual/Game%20Mechanics/#aircraft)
The setting is documented [here](https://wiki.openttd.org/en/Archive/Manual/Settings/Advanced%20Settings/Vehicles#plane-speed-factor)

**Comment by legitalk** [comment]
Thank you, did not know that. Closing.
