### ISSUE TITLE
[Crash]: Error: Assertion failed

### ISSUE THREAD

**Issue by legitalk** [OpenTTD/OpenTTD#10223]
### Version of OpenTTD

13.0-beta2, nightly(20221205)

### Steps to reproduce

1. Click on Clone train button and then on train which to clone
2. Crashed with screenshot below
![2022-12-07 15_39_43-Error!](https://user-images.githubusercontent.com/6940865/206208986-ed6f0ecc-af41-4c7d-914c-93fbe3fc67bb.png)

### Bug location

_/OpenTTD/blob/master/src/core/pool_type.hpp_
```
inline Titem *Get(size_t index)
{
  assert(index < this->first_unused);
  return this->data[index];
}
```

### How to solve it

1. After little bit testing I found out it is crashing when you are trying to clone a train, which has recently deleted station on the route list

### Upload crash files

1. Actually its showing the dialog box and when clicking Ok, its still showing again and it is not possible to go back to the game and no crash logs are created.

**Comment by PeterN** [comment]
Confirmed

**Comment by James103** [comment]
Also affects road vehicles and other vehicle types (confirmed in 985f487065). 
Crash files: [crash20221207152656.zip](https://github.com/OpenTTD/OpenTTD/files/10177402/crash20221207152656.zip)

**Comment by PeterN** [comment]
This is caused by https://github.com/OpenTTD/OpenTTD/blob/master/src/vehicle_cmd.cpp#L961 returning total_cost along with INVALID_VEHICLE, without flagging it as Failed.

Similar issue with https://github.com/OpenTTD/OpenTTD/blob/master/src/vehicle_cmd.cpp#L972 too.

**Comment by glx22** [comment]
Line 972 should be fine but line 961 was `return result;`
