### ISSUE TITLE
Roads built on foundations at the minimum snow level height have inconsistent snowiness

### ISSUE THREAD

**Issue by PikkaBird** [OpenTTD/OpenTTD#10239]
### Version of OpenTTD

13.0 b2

### Expected result

A road built on a foundation at the minimum snow level height should be snowy.

### Actual result

A road built on a foundation at the minimum snow level height is not snowy.

This bug affects both NRT roads using a var2 40 Terrain Type check, and the default roads with no newgrfs loaded.

![Flindingbury Transport, 1950-03-08](https://user-images.githubusercontent.com/39507755/207493356-3add0998-fef0-4eaa-8da6-fddd8ced3fe0.png)

### Steps to reproduce

Build a road on a foundation at the minimum snow level height.

**Comment by LC-Zorg** [comment]
> A road built on a foundation at the minimum snow level height should be snowy.

Wouldn't it be better if the road / rail graphics just always overlay the terrain as it is? Not only snowy or not snowy (desert or forest). For not one graphic sets, the proposed change with full snow can look similar not good.

![road background - z-base](https://user-images.githubusercontent.com/67662046/207738829-f05ab93f-ee9c-4903-925c-c4a1dcbe8ba7.png)

This bug applies to all graphics. Two other examples:
![road background - OpenGFX + U Ratt](https://user-images.githubusercontent.com/67662046/207738918-55eee0cc-0439-477a-93c3-d0c1585097e8.png)

![road background - BRIX + U Ratt](https://user-images.githubusercontent.com/67662046/207738956-4278bcda-2431-4713-88af-b1671dfba875.png)

**Comment by adamiaonr** [comment]
Hi @PikkaBird, @LC-Zorg and @2TallTyler : is this still eligible to be taken? 
I've come across this while looking for 'good first issues' to take on.
I used to play TTD quite a lot in my teens, so contributing to this project would be interesting to me.

**Comment by 2TallTyler** [comment]
It sure is. Go for it!

**Comment by adamiaonr** [comment]
@2TallTyler : Great!
It will take me a bit of time to get to know the project, so it won't be fast.

**Comment by daredem0** [comment]
I had a look into this lately. I don't really like the proposed solution. Snowy roads surrounded by partially snowy clear tiles looks just as bad as non snowy roads as @LC-Zorg  mentioned in his post previously. However, as far as I understand how the sprites for road and track tiles work, the background and the track/road is baked into a single sprite. Hence, overlaying the track/road over the partially snowy clear tile is not feasible as it is. 
Two solutions come to mind: 
* Track/Road sprites as single objects that can be overlayed similarly to tree tiles
* New partially snowy tiles for each possible track/road tile

The inconsistency described in this issue also include tunnel entries which could be handled in the same way. 
Both solutions however would need support of the available basesets.

**Comment by 2TallTyler** [comment]
Looks like this JGRPP commit would fix the issue, or at least make it match rail behavior. 

https://github.com/JGRennison/OpenTTD-patches/pull/384
