### ISSUE TITLE
One-way road arrows don't look good on slopes

### ISSUE THREAD

**Issue by PikkaBird** [OpenTTD/OpenTTD#10238]
### Version of OpenTTD

13.0 b2

### Expected result

Both the base graphics and newgrfs treat the one-way arrows as diegetic, ie as if they were in-game road markings rather a UI indicator. Action 5 type 09 should be extended with an additional 12 sprites to allow providing sloped versions of the one-way arrows.

### Actual result

The one-way arrows do not have sloped versions and thus look naff on slopes.
![Jollyburg Transport, 1976-09-30](https://user-images.githubusercontent.com/39507755/207490924-c45b56ec-0ae4-437c-85cb-bb1f88433bd5.png)

### Steps to reproduce

Build a one-way road on a slope.

**Comment by LC-Zorg** [comment]
When introducing changes, it would also be worth considering the possibility of assigning different direction signs to different roads.
![Zrzut ekranu 2021-03-13 162456](https://user-images.githubusercontent.com/67662046/207740899-6d4113b7-9399-420f-bf1a-b7afeeac24a1.png)

**Comment by michicc** [comment]
Support added in #10282
