### ISSUE TITLE
[Bug]: GRF vehicles < 8/8 long need special handling of action 1 realsprites when reversed (flipped)

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/OpenTTD#10231]
### Version of OpenTTD

13.0-beta2

### Expected result

Additional set of action 1 realsprites are not required for GRF vehicles that are both < 8/8 and reversed (flipped by player in depot).

Assumption is that OpenTTD would handle this case by adjusting offsets / origin as needed.

### Actual result

Sprites will be incorrectly positioned for < 8/8 long vehicles if reversed (flipped by player in depot).

This must be handled by GRF authors providing an additional set of realsprites for the flipped case.

Examples will make this clearer.

### Steps to reproduce

1. use Iron Horse grf attached in issue comments
2. build some < 8/8 vehicles 
3. flip vehicles in depot, observe incorrect offsets

**Comment by andythenorth** [comment]
Unreversed
<img width="312" alt="image" src="https://user-images.githubusercontent.com/1780327/206930058-6ac461e1-56ce-4178-8822-820704943bba.png">

Some vehicles reversed
<img width="330" alt="image" src="https://user-images.githubusercontent.com/1780327/206930049-4078ff6d-f9d2-46d4-9586-1f43d298eb6f.png">

All vehicles reversed
<img width="326" alt="image" src="https://user-images.githubusercontent.com/1780327/206930085-1bf96c6d-c0dd-4a66-ad50-c4810b04110d.png">

**Comment by andythenorth** [comment]
[iron-horse-2.63.1-2-g57df0be8.zip](https://github.com/OpenTTD/OpenTTD/files/10203341/iron-horse-2.63.1-2-g57df0be8.zip)

**Comment by andythenorth** [comment]
The Iron Horse handling is primarily just swapping offsets for first 4 and last 4 sprites, as can be seen at: https://github.com/andythenorth/iron-horse/blob/main/src/utils.py#L79

There's also some uninteresting templating of spritesets associated with that.

**Comment by PeterN** [comment]
Is this issue just in the depot, or does it affect vehicles in the viewport as well?

**Comment by andythenorth** [comment]
> 

<img width="270" alt="image" src="https://user-images.githubusercontent.com/1780327/206931774-60e37e0f-0bc9-45a7-8422-a2904c0190a8.png">

**Comment by andythenorth** [comment]
> Is this issue just in the depot, or does it affect vehicles in the viewport as well?

<img width="270" alt="image" src="https://user-images.githubusercontent.com/1780327/206931781-a33748f0-e994-4dc0-a469-ac3f593ab085.png">

**Comment by Eddi-z** [comment]
this is why reversing is disabled by default on shortened vehicles. GRFs are expected to work around this by providing separate reversed sprites with different offsets

**Comment by PikkaBird** [comment]
+1 Eddi. If this "bug" were to be fixed in isolation it would break almost every newgrf train set created to date. It *might* be worth considering as part of a rethink of how vehicle reversing works in general - also considering #10193, flipping of articulated vehicles, and reversing of entire trains - but that's a big project.

Stop trying to reduce IH compile time by breaking the game. :)

**Comment by andythenorth** [comment]
Can't remember where 'action 1s are a real problem ok?' originated 😛 

Think there were questions about both compile time and "why is Horse filesize so big for nml file, nfo file, and grf?"

A quick test of removing _most_ reversal support from Horse has the following results:

| Version | Approx duplicate realsprites | NML filesize | NFO filesize | GRF filesize | Typical compile time |
|---------|-----------------------------|---------------------------|-----------------------------------|
| Modified | 13k | 14.2 MB | 22.5 MB | 22 MB | ~24s |
| Release | 93k | 15.8 MB | 33.3 MB | 37.2 MB | ~28s |

Compile time is full build of grf, but with primed caches

**Comment by PeterN** [comment]
Closed by #10262
