### ISSUE TITLE
[Bug]: 12.2 is set to refuse to run in macOS 10.13

### ISSUE THREAD

**Issue by newbthenewbd** [OpenTTD/OpenTTD#10245]
### Version of OpenTTD

12.2, macOS High Sierra 10.13.6

### Expected result

This, but with OpenTTD 12.2:
![image](https://user-images.githubusercontent.com/1766353/208023404-2822dd7a-71dd-4460-a528-f4f2082498a8.png)
![image](https://user-images.githubusercontent.com/1766353/208023223-6c85deec-f01d-4478-82d1-1fbb05ca3282.png)

### Actual result

![image](https://user-images.githubusercontent.com/1766353/208023678-784d1015-ebd1-4cab-9715-2eeaa1218b24.png)

This would be #9689 at work... But if it's just `std::bad_variant_access`, [it should reportedly already exist in 10.13?](https://stackoverflow.com/a/53868971) Which is the last official version for many Macs, including mine.

I mean, it's kinda funny that out of all things, a remake of a 1995 game thinks the OS too old... Would a test build set to 10.13 be available to check it out? :)

Thank you so much!

### Steps to reproduce

1. Double click the game's icon.

**Comment by James103** [comment]
The system message in the second screenshot says (in Polish) that the app requires macOS 10.14 and that the system the app is being run on has macOS 10.13.6.

**Comment by orudge** [comment]
I don't know that we want to try introducing hacks to support functionality that is unsupported by Apple in 10.13, at least in official builds. It's unfortunate that Apple don't support newer versions of macOS on hardware that isn't all that old, but I don't know that that's our problem to solve.

**Comment by andythenorth** [comment]
Thanks for reporting.😉 

OpenTTD does try to provide backwards compatibility to older hardware and OS where we can, but we've had to make decisions to drop support for certain situations.  Older macOS / OS X is one case, as you found documented in #9689.

You might be able to self-compile with the workarounds described in the stackoverflow article, or you might be able to use an older OpenTTD binary. 

I'm going to close this one thanks.

**Comment by newbthenewbd** [comment]
I don't think that my point had been understood clearly; one of the workarounds discussed is simply _using the function outright_, and my request was to try a build set to 10.13, instead of 10.14 - it might just work!

![image](https://user-images.githubusercontent.com/1766353/208084513-81939dfc-03ee-408e-8017-b164874b8ab2.png)

Now just wondering if closed issues are being watched anyhow? Oh well :)
