### ISSUE TITLE
[Bug]: groundtiles on foundation should not be childsprites of foundation sprites

### ISSUE THREAD

**Issue by PikkaBird** [OpenTTD/OpenTTD#10248]
### Version of OpenTTD

13.0 b2

### Expected result

A groundsprite on a foundation should be positioned mathematically, rather than being parented to the foundation sprites.

### Actual result

With extra zoom grfs, some error in a calculation somewhere appears to attach the groundsprite to the foundation sprite two pixels to the left of where it ought to be. This error can be seen in my WIP grf, as well as the zbase baseset - both of which have used the workaround of clipping the foundation short to position the groundtile correctly.

![Untitled](https://user-images.githubusercontent.com/39507755/208226762-df8906c1-fe70-4c17-9349-08263d3cd3a0.png)
![zbase](https://user-images.githubusercontent.com/39507755/208226765-e3c03f80-9290-4e31-85fa-44f9e1864bad.png)

This calculation could be fixed, but that would cause errors for grfs (including base sets) which have previously worked around the error. Instead, the groundtile should be simply placed in the correct position (as building sprites on foundations are) instead of being parented to the foundation.

### Steps to reproduce

Look closely at the zbase graphics

**Comment by PeterN** [comment]
I see it, the issue is the sprites are drawn dependent on the *sprite offsets* of the foundation, which is clearly b...ad.

**Comment by PeterN** [comment]
Fix in #10256
