### ISSUE TITLE
[Bug]: Cargo flow legend line thickness becomes larger with UI scaling

### ISSUE THREAD

**Issue by merni-ns** [OpenTTD/OpenTTD#10255]
### Version of OpenTTD

13.0-beta2 on Windows 11

### Expected result

Either the thickness of the cargo flow legend's lines remains the same regardless of UI scaling, or there is a separate setting to control the thickness of those lines (as there is with graph lines). To me, the most important thing in scaling is to make UI elements (esp. text) readable since I have a small laptop screen with a high (1920x1080) resolution. I don't want non-text elements in the game world like the cargo flow lines to be enlarged.

### Actual result

The thickness of the cargo flow lines increases to a large extent when UI scaling is applied.
The below screenshot shows on the left JGRPP 0.47.2 (based on OpenTTD 12.x) and on the right JGRPP 0.50.0 (using the UI scaling feature of OpenTTD 13). In both windows, 2x scaling is applied (on the left it is 2x interface scaling + 2x font scaling).
![Screenshot 2022-12-18 135418](https://user-images.githubusercontent.com/66267867/208289238-dac690cd-ab34-4a07-abb5-364121412609.png)

### Steps to reproduce

1. Increase the UI scaling on OpenTTD 13.0-beta2 to 2x or any larger setting.
2. Open a save with some transport network, and enable the "Cargo Flow Legend"
3. Observe that the lines are much bigger than those in 12.x versions with 2x scaling.

**Comment by PeterN** [comment]
This is 'intentional', caused by #10064. I'm not sure that is correct though.

**Comment by merni-ns** [comment]
Perhaps then the best way is to have an option for the thickness of those lines -- just like for graph lines.

------- Original Message -------

**Comment by PeterN** [comment]
I think thinning them down from 3px to 2px (per colour, so 6px total) at 1x scale may be good enough. They are then 'only' 12px wide at 2x scale instead of 18px.

Saves yet more options.
