### ISSUE TITLE
[Bug]: List of available roads/tracks: Removing the scroll bar makes some road/track types unavailable if the player is using the enlarged GUI

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10268]
### Version of OpenTTD

13.0-beta2

### Expected result

It is possible to use all types of roads/tracks, regardless of the selected interface size

![Road list 12 2](https://user-images.githubusercontent.com/67662046/208788005-80d59123-c93d-4d31-86ba-7b1c9f79c241.png)

1. Restore the scroll bar
2. Limiting the possibility of enlarging - do not allow the GUI to be enlarged to sizes which will cause problems in use.
![limited interface magnification](https://user-images.githubusercontent.com/67662046/208788080-fd4d2edd-4f42-4eed-990e-00e956729fcb.png)

### Actual result

If someone has worse eyesight and needs an enlarged GUI, they cannot use all the features and possibilities of the game.
Using x2 magnification at FHD 1920x1080 resolution means that the player cannot select all available types of roads or tracks. Using even higher magnification intensifies this problem.
![Road list 13 0-beta2](https://user-images.githubusercontent.com/67662046/208788041-44012f1f-06b3-4108-a3b6-76b86599f41f.png)

### Steps to reproduce

1. Add to the NewGRF list: e.g. U&Ratt and Polroad (there may be many more add-ons with roads)
2. Make the interface large

**Comment by James103** [comment]
Try updating to the latest nightly build; this was fixed in https://github.com/OpenTTD/OpenTTD/pull/10264.

**Comment by PeterN** [comment]
Already fixed in #10264

**Comment by LC-Zorg** [comment]
I guess I'm typing these reports too slowly :D
Anyway, such limiting enlarging could still be useful. I don't want to repost this as a separate entry. I just leave it for you to consider. :)
