### ISSUE TITLE
[Crash]: crash closing dialogue box

### ISSUE THREAD

**Issue by superfloh247** [OpenTTD/OpenTTD#10275]
### Version of OpenTTD

12.2, MacOS 13.1 apple silicon

### Steps to reproduce

crash closing dialogue box

![crash20221222190208](https://user-images.githubusercontent.com/26180993/209209148-85141118-fd0f-45ba-9bc8-2bac66a02662.png)

### Upload crash files

[Archiv.zip](https://github.com/OpenTTD/OpenTTD/files/10289714/Archiv.zip)

**Comment by 2TallTyler** [comment]
Can you please try to reproduce with the nightly build instead of 12.2? It's available on the website and in the Betas menu on Steam.

**Comment by superfloh247** [comment]
I installed openTTD 12.2_1 today (from MacOS brew) and the crash still occurs.

I can reproduce it 100%: hover over the close X and wait for the tool tip, see screenshot above.

**Comment by 2TallTyler** [comment]
If it's fixed in 13.0-RC1, then the bug is fixed. Feel free to re-open if I misunderstand you. 🙂
