### ISSUE TITLE
[Bug]: poor UI options in latest patch, possibly due to irregular screen size

### ISSUE THREAD

**Issue by BL97** [OpenTTD/OpenTTD#10270]
### Version of OpenTTD

jgrpp 0,50,0 windows 10

### Expected result

prior to the current patch there was options for UI and text etc which allowed me to have a happy balance in ease of clicking things, reading things and also having many things on my screen at once, here i have provided 3 images of how things used to look for me
![006](https://user-images.githubusercontent.com/98127896/208812618-d194fb1c-b3cf-43b7-8416-6b94353953c8.png)
![005](https://user-images.githubusercontent.com/98127896/208812620-d2e28b5a-4bb3-4075-bd45-17d2ccc752b2.png)
![004](https://user-images.githubusercontent.com/98127896/208812622-3cacc785-37d4-42a0-a7fb-7af34b19eac4.png)

### Actual result

as you can see in screenshots the new method provides no middle ground for 2560x1440 screens, you can either have a nice text size, nice top bar size or nice sprite size but no balanced option
![003](https://user-images.githubusercontent.com/98127896/208812095-d053e024-fb66-4912-98dc-b8badea31487.png)
![002](https://user-images.githubusercontent.com/98127896/208812098-816e0587-1fea-4a0c-8d2d-1ea6943e0dd1.png)
![001](https://user-images.githubusercontent.com/98127896/208812101-dca69622-135a-401e-89d4-a390ee01eb41.png)

### Steps to reproduce

nothing needs to be done to reproduce this other than to load up any game, i apologise if i have posted this in the wrong place, i don't know if i am doing this right but i was directed here, thanks

**Comment by James103** [comment]
1. Can you please post your `openttd.cfg` including all the font settings?
2. Is this reproducible in master (13.0 beta or latest lightly)?

**Comment by BL97** [comment]
> 

i will get back to you on this after i download the latest nightly to see

**Comment by BL97** [comment]
hello! unfortunately i was unable to entirely comply as i use TTDLX graphics, however i found that deleting my config file would allow me to adjust the slider to a setting i am content with, what would i need to change in my own config file to make things look better? thanks!
[OpenTTD.zip](https://github.com/OpenTTD/OpenTTD/files/10274308/OpenTTD.zip)

**Comment by James103** [comment]
```ini
[misc]
small_size = 13
medium_size = 19
large_size = 30
mono_size = 13
```

Your font sizes are set very large. Try reducing them a fair bit, especially `medium_size` and `large_size`.

**Comment by BL97** [comment]
thanks! i messed with them a bit and a found something i am comfortable with))
