### ISSUE TITLE
[Crash]: Downloading a Game Script while having another Game Script selected may crash

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#10274]
### Version of OpenTTD

a857ed8240 on Windows 10, 64-bit (via Steam)

### Steps to reproduce

1. Download some Game Scripts, including one that has parameters.
2. From the main menu, click "Game Script Settings".
3. Select an installed Game Script with parameters.
4. From the console, run `rescangame`. The game may or may not crash right then.
5. Click "Check Online Content".
6. Download some more Game Scripts, then close the content downloading window which will run `rescangame` again to detect the newly downloaded Game Scripts.
7. The game may or may not crash then as well. If not, repeat from step 3 with a different Game Script selected.

### Upload crash files

[crash20221222153328.zip](https://github.com/OpenTTD/OpenTTD/files/10288122/crash20221222153328.zip)
[crash20221222153102.zip](https://github.com/OpenTTD/OpenTTD/files/10288123/crash20221222153102.zip)

Originally reported in https://github.com/JGRennison/OpenTTD-patches/issues/465, but I was able to reproduce in vanilla.

**Comment by glx22** [comment]
Seems to be a nasty one, crash.log are mentioning infinite loops.
