### ISSUE TITLE
[Crash]: opening City local authority window on macOS causes crash

### ISSUE THREAD

**Issue by davewthompson** [OpenTTD/OpenTTD#10288]
### Version of OpenTTD

12.2 macOS M1

### Steps to reproduce

Open the attached savegame.
Click the "Great Pedston" town name.
Click "local authority"
The game will then crash.

### Upload crash files

[crash20221229073405.zip](https://github.com/OpenTTD/OpenTTD/files/10318153/crash20221229073405.zip)

**Comment by davewthompson** [comment]
I have just pulled the latest OpenTTD code from Git, built it on my Mac, and opened the game in that version, and the crash doesn't happen, so perhaps it's been fixed?

**Comment by James103** [comment]
> I have just pulled the latest OpenTTD code from Git

Which commit exactly?

**Comment by davewthompson** [comment]
```
dave@dwt-MBP-max OpenTTD % git log
commit 918b2cb3ee741a0ed54900e7bed16eb5baa35cc7 (HEAD -> master, origin/master, origin/HEAD)
Author: translators <translators@openttd.org>
Date:   Wed Dec 28 18:44:23 2022 +0000

```

**Comment by 2TallTyler** [comment]
Sounds like it's been fixed at some point, so the report can be closed. If it happens again in the latest version, please feel free to re-open. 🙂
