### ISSUE TITLE
Setting timetable start dates for shared orders silently fails if not fully timetabled

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#10289]
### Version of OpenTTD

13.0-beta2

### Expected result

When setting timetable start dates for multiple vehicle with shared orders, Ctrl+clicking the Start Date button spaces out vehicles along the route. 

If the entire route is not timetabled, we don’t know the full duration and therefore can’t space our vehicles evenly. 

In this case I would expect it to either spread out vehicles using the known incomplete total, or throw an error message to the player. 

### Actual result

The command fails silently and only sets the start date of the selected vehicle, leading to misunderstandings like #8054. 

@nchappe explains in #8054:
> In the code the exact condition to set the timetable start date for all the vehicles with the same shared orders when the set start date button is pressed is v->orders->IsCompleteTimetable() && _ctrl_pressed, which means that if some orders are not explicitly timetabled, Ctrl+Click silently falls back to setting the timetable start date of a single vehicle, with no user feedback.
This is explained in the relevant tooltip ("Ctrl+Click distributes all vehicles sharing this order evenly from the given date based on their relative order, if the order is completely timetabled"), but I still find it a bit counter-intuitive, and I suspect this is the root of this issue.

### Steps to reproduce

1. Create more than one vehicle with shared orders
2. Timetable most but not all of their orders
3. Ctrl+click Start Date to space them out over the route
4. Notice that only the selected vehicle gets its start date changed

**Comment by LC-Zorg** [comment]
Setting start dates, making sure everything was done in the right order, receive error notifications when something goes wrong, and then when you change vehicles, repeating it all over all 74 lines... This whole feature is a nightmare. I don't know if there's any point in fixing it. I think it would be much better to focus on makeing / finishing the automatic vehicle separation feature that is available in the JGRPP. It should be a single button in the timetable window ON / OFF and nothing else. Not a whole complicated and time-consuming procedure. :/

**Comment by 2TallTyler** [comment]
No disagreement there, and I do plan to eventually implement autoseparate from JGRPP. (It's a big feature and a lot of work to merge.) But this is broken in the meantime.
