### ISSUE TITLE
[Bug]: Error message when performing town action with not enough cash does not say "not enough cash"

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#10280]
### Version of OpenTTD

a857ed8240 on Windows 10, 64-bit (via Steam)

### Expected result

The error message given when attempting to perform a town action while not having enough cash to do it should say that the company does not have enough cash to perform that action with the local authority.

Example: "Can't do this... Not enough cash, requires £102,539"

### Actual result

The error message given when attempting to perform a town action while not having enough cash to do it does not say that the company does not have enough cash to perform that action with the local authority.

Actual: "Can't do this..." without that second line saying "Not enough cash"

### Steps to reproduce

1. Start a new map.
2. Click on a town to open its town window.
3. Click "Local authority".
4. Double click on a greyed-out action to attempt to perform it.
5. The action fails (as expected), but the error message does not say that the company doesn't have enough cash to do it (as is typically the case if an action is greyed out).

**Comment by 2TallTyler** [comment]
Perhaps a better fix would be to actually disable the action, so double-clicking does nothing.

**Comment by redone9211** [comment]
i would like to contribute to this issue , can you let me know how i can solve it.
