### ISSUE TITLE
[Bug]: Compile warnings with release

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/OpenTTD#10293]
### Version of OpenTTD

master

### Expected result

No compile warnings :D

### Actual result

`OpenTTD/src/engine.cpp:541:7: warning: variable 'index' set but not used [-Wunused-but-set-variable]`
`OpenTTD/src/3rdparty/squirrel/squirrel/sqstate.cpp:453:20: warning: variable 'nfound' set but not used [-Wunused-but-set-variable]`

Both related to release builds, which build without `assert`. Both seem legit.

### Steps to reproduce

Build with `-DCMAKE_BUILD_TYPE=Release -DOPTION_USE_ASSERTS=OFF`

**Comment by glx22** [comment]
Only happens when using `clang`
