### ISSUE TITLE
[Bug]: The way of selecting the setting of the on-screen keyboard is wrong.

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10296]
### Version of OpenTTD

since 12.0, not present in 1.12.2

### Expected result

Selecting a setting from the list as it worked before 12.0
![Zrzut ekranu 2022-12-30 213451](https://user-images.githubusercontent.com/67662046/210109944-167fb02a-3771-4b90-8c36-e1b5ff6fcfb5.png)

### Actual result

The setting is selected by typing the value. There are no options at all to choose from. Regardless of the selection made, "disable" is always shown.
![Zrzut ekranu 2022-12-30 211845](https://user-images.githubusercontent.com/67662046/210109893-4f28ba00-8293-4686-90e7-920cc1dc3a3d.png)

### Steps to reproduce

Compare versions 12.0 and 1.11.2

**Comment by LC-Zorg** [comment]
Oops. I don't know when, but it has already been fixed. :)

**Comment by 2TallTyler** [comment]
Fixed by #9855
