### ISSUE TITLE
[Bug]: Font command input is scaled by interface scaling

### ISSUE THREAD

**Issue by heresyh** [OpenTTD/OpenTTD#10292]
### Version of OpenTTD

20221229-master-gf90156f74c

### Expected result

I don't know if this should be closed as working as intended, or considered a bug.
If you use the new font command, and try to change the font size to 10, it will be scaled by the current interface scaling also.

F.ex, writing "font medium 10" at 1.5 scaling, returns 15. At 2x scaling, it returns 20.
In the actual configuration file, it saves the actual written input, so in openttd.cfg, it will say medium_size=10 as expected.

However, if you want to try font size 10, at 2x scaling, you would have to write "font medium 5" to get the actual desired result of font size 10.

Example picture is result from testing with 2x Interface Scaling.
![image](https://user-images.githubusercontent.com/109810800/210003616-2cd06249-1a88-452f-95c4-d9d76ddcd265.png)

Another side effect of the interface scaling affecting the font input, is that some sizes become unavailable.
At 1.5 x scaling, size 7 returns 10, and size 8 returns 12. So actual size 11 is not possible to set at 1.5x scaling.

### Actual result

As mentioned, not sure if this should be classified as a bug or working as intended.
Since it does make certain font sizes unavailable and the command result might be misleading at scaled interface sizes, I would lean towards classifying it as a bug however.

So in that case, the expectation would be that writing "font medium 7" should result in the actual size 7, not 14, at 2x scaling f.ex.

### Steps to reproduce

Open OpenTTD version that includes the Font command.
Change interface scaling to higher than 1x.
Try to change font size using the font command.

**Comment by PeterN** [comment]
Actually the output should probably be `medium: "Tahoma" 10 false ["Tahoma" 10 false]`.

It is definitely intended that fonts are scaled by interface scaling.

**Comment by NyanGoat** [comment]
> Actually the output should probably be `medium: "Tahoma" 10 false ["Tahoma" 10 false]`.
> 
> It is definitely intended that fonts are scaled by interface scaling.

I did assume that fonts scaling was intended, but the output from the command should probably be massaged a bit then yes.

About the second side effect of certain font sizes being unavailable when interface is scaled, I think that will just have to be a causality of the implementation, unless there is some magic performed, or the font be uncoupled from the scaling.

For an eventual future font selection UI, it could become confusing if font size 11 (taking my example from above) is available in the dropdown, but clicking it just does nothing, or something unexpected.

**Comment by ldpl** [comment]
Scaling font might be intended but is extremely inconvenient. 
When I was setting up my OpenTTD I set up comfortable font size first and then when trying different UI sizes it kept messing up font so I had to fix it over and over again.

**Comment by PeterN** [comment]
Working as intended.

Text is part of the interface, therefore interface scaling is intentionally applied to text.

The output of the "font" console command shows the configured (unscaled) value and the current active value.
