### ISSUE TITLE
[Bug]: GitHub Actions Release workflow publishes too many files to the CDN

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/OpenTTD#10301]
The Windows Store part of the release workflow publishes two files to the CDN it really shouldn't:

- `output/OpenTTD.appxbundle`
- `cert.pfx`

This causes the CDN indexer to fail, as it doesn't know how to make those files available.

Please make sure those files are no longer published to the CDN, or, if we do want to publish them, please generate md5sum / sha1sum and sha256sum of those files before making an artifact out of them, like the other jobs do.

**Comment by TrueBrain** [comment]
The problem is a bit annoying to tackle:

https://github.com/OpenTTD/OpenTTD/blob/5e22788664b6d824bce1014f848e4a109d7c619d/.github/workflows/release.yml#L1024

causes the files to be uploaded.

https://github.com/OpenTTD/OpenTTD/blob/5e22788664b6d824bce1014f848e4a109d7c619d/.github/workflows/release.yml#L1053

Downloads all artifacts, and publishes them. Windows-store is always done before the Upload, as the Upload depends on MacOS, which is the slowest of them all.

---

I think these files are put in an artifact, as @orudge uploads those files manually on the Windows Store. But they do have a retention of just 5 days, so he always has to do that within 5 days, or they are lost.

So I wouldn't mind if we upload them to the CDN, for later retrieval (if we have to). But then the files should be put in a bundle like the other files are, and named `openttd-`, so they receive a proper checksum file.

Either way, I completely forgot what the intentions of @orudge were here. If he wanted to automate the upload process, and this was just an in-between? Is 5 days enough to always upload it on the Windows Store? Or should we publish this on the CDN?

We could also make a hidden folder for it, so we know where to find it, but it isn't indexed. Then we just need to blacklist those files from being indexed in the workflow/cdn scripts.

So yeah, let me know, and we take it from there :)

Our workflows really got too complicated :P

**Comment by orudge** [comment]
Sorry, I missed this issue - these were not intended to be uploaded to the CDN. The intention was that I would manually upload the final release to the Store just after release, by downloading the artifacts from the GitHub interface. (Automating the full release process looks to be technically possible, but requires setting up Active Directory infrastructure for OpenTTD and so on so is not very straightforward.)

We could make a hidden folder for them, or something similar, which I guess would allow us to download older Store builds if for whatever reason we wanted to. They shouldn't be on public display though, as it's not trivial how to install them without using the actual store, and there's no real need for anyone to want to.

**Comment by TrueBrain** [comment]
Cheers for the feedback.

In #10422 it now publishes the `appxbundle` and `pfx` in an `internal` folder, with the name `openttd-<version>-windows-store`. You can access those files directly from the CDN, but they won't be listed anywhere else. I think that should work fine for now :)

When the next release is done, I will let you know the exact URLs.

**Comment by TrueBrain** [comment]
@orudge : 13.0 release can be found here:

https://cdn.openttd.org/openttd-releases/13.0/internal/openttd-13.0-windows-store.appxbundle
https://cdn.openttd.org/openttd-releases/13.0/internal/openttd-13.0-windows-store.pfx

The same naming schema will be used for all other uploads from now on :)
