### ISSUE TITLE
[Bug]: The new grf settings button is moved

### ISSUE THREAD

**Issue by Brickblock1** [OpenTTD/OpenTTD#10308]
### Version of OpenTTD

13

### Expected result

Newgrf settings button should be in the same place as before.

It is prefered to keep the same placement as to not force people to relearn where the button is.

### Actual result

it is not

### Steps to reproduce

start the game

**Comment by andythenorth** [comment]
There are at least two views on change

- embrace change
- avoid change

I am sure there are many others.  But the nature of OpenTTD is that change happens. We do try to not make pointless changes. But change happens. Going against the nature of things doesn't work very well.

Sometimes the changes are even bad, but we learn something.  [NSFW link]: https://www.youtube.com/watch?v=46h7oP9eiBk

**Comment by 2TallTyler** [comment]
This change is intended, as https://github.com/OpenTTD/OpenTTD/pull/10203. Not a bug.
