### ISSUE TITLE
[Bug]: GS Story Book on start screen

### ISSUE THREAD

**Issue by arikover** [OpenTTD/OpenTTD#10304]
### Version of OpenTTD

20230101-master-g150f05dc15

### Expected result

Start screen contains the normal menu window

### Actual result

Start screen also displays the GameScript Story Book

![Screenshot from 2023-01-02 00-39-38](https://user-images.githubusercontent.com/53194907/210187745-20a45699-f283-4c44-a463-0de8aa8a79ac.png)

### Steps to reproduce

1. Select a GameScript that should display a story book on gamestart (Awards, Renewed Village Growth...)
2. Start a game
3. Abandon the game

**Comment by glx22** [comment]
Hmm but GS are supposed to be disabled
