### ISSUE TITLE
[Bug]: engine variants parent/children can't display different name strings depending on context

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/OpenTTD#10307]
### Version of OpenTTD

13 RC 1 or newer

### Expected result

Engine variants should display a name string depending on context.

In buy menu*, as parent of a variant tree: string 1
In buy menu*, as child of a parent tree: string 2
In vehicle information window: string 1 + string 2 

* also autoreplace

E.g. buy menu

- Freight Wagon
    - Red
    - Blue
    - Fancy
    - Special
    - Chunky

Vehicle information window

Freight wagon - Red

Ideally the string used in the buy menu would remain constant for the group, whereas currently it changes as the parent is shown as the last built vehicle from the group (which is good, but the string should not change).

Is this needed?  Dunno, might be worth testing though.

Callback?  New action 0 prop?  Don't know.

We might also look at splitting 'power type' suffixes out from the name string as a separate thing, but eh, scope creep?

### Actual result

The name string from the vehicle action 0 prop is always used in all contexts.

### Steps to reproduce

Try attached Horse grf in OpenTTD 13 RC 1 or newer.

[Uploading test-horse.zip…]()

**Comment by andythenorth** [comment]
Goes it better with example mockups probably.

**Comment by 2TallTyler** [comment]
Closed by #10399
