### ISSUE TITLE
[Feature request]: Add a setting to prevent crossing tracks with other players roads

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10311]
### Version of OpenTTD

13.0+

### Expected result

There is a setting that prohibits building tracks on someone else's roads and building a road on someone else's tracks. Useful especially for online games, but also for offline games with some AI.

### Actual result

This is a problem that has probably always existed. It existed even before the era of multiplayer games, although it mainly applies to such games.
Practically in every online game, there are cases where some players build tracks on someone else's roads. Often they do it out of ignorance or intellectual limitations (they can't predict the consequences), but just as often they do it fully consciously or even intentionally to destroy other players vehicles. Along with blocking ports and ships, this is the most common form of trolling in this game. In a game without add-ons, the player has no sensible way to protect himself against this. He can try to build one-way roads everywhere, but it just doesn't look good.

**1st example**
The purple player has entered into a conflict or just for fun destroys the green player's road vehicles for no reason.
Why? Because he can.
![purple vs  green](https://user-images.githubusercontent.com/67662046/210289286-c6fb545d-89d0-4121-8950-3ce851111b47.png)

**2nd example**
The red player, paying no attention to others, built his tracks on the road used by the orange player. As you can see, the blue player was able to build a bridge over the road. Even if he doesn't do it maliciously, paying attention to everyone, explaining what it leads to is simply tiring.
![red vs  orange vs  blue](https://user-images.githubusercontent.com/67662046/210289288-e011d396-0197-48d5-9f86-427afa6988e9.png)

The most sensible solution that would solve this problem seems to be adding an option that will prohibit crossing roads with tracks of different companies. Possibly also crossing tracks with public roads. A similar setting is available for the construction of through stops.
![settings for level crossing](https://user-images.githubusercontent.com/67662046/210289380-acdaa590-69b6-4f60-9c36-876cb0192fb7.png)
+Allow crossing of tracks with public roads
+Allow crossing of tracks with other players roads

Both could be enabled by default.

### Steps to reproduce

If you play on public servers, you are probably familiar with this problem and have seen situations similar to the above many times.
If not, it may take several hours to notice the situation. Seemingly rare, but given the gameplay characteristics, for someone who plays on public servers, such situations happen in practically every game.

**Comment by Homarton** [comment]
I would like to take a stab at implementing this. Would this still make for a desired PR?
