### ISSUE TITLE
[Crash]: Unsafe NewGRF use of date_of_last_service crashes after using date cheat

### ISSUE THREAD

**Issue by SimozzzAK** [OpenTTD/OpenTTD#10334]
### Version of OpenTTD

13 RC1 (Reported by other xUSSRset devs as well on 12.2)

### Steps to reproduce

Easy to set up but not 100% results in crash.

Happens with xUSSRset container wagons (any).

Steps:
Start new game in modern days (2020 for example).
Buy a train with container wagons - refit them to refrigirated or liquid cargo. In crashed game - oil was used.
Let it start loading. While it does - change date to earler years. In crashed game - 1960 was used.
Let time pass by.
...
Profit! (?)

As said - not guaranteed to crash. There is an error window when train start to move that capacity changed outside of depot.

In crashed game - train entered depot for service and left. Shortly after - crash.

### Upload crash files

[xUSSRset Crash.zip](https://github.com/OpenTTD/OpenTTD/files/10387861/xUSSRset.Crash.zip)

**Comment by SimozzzAK** [comment]
[xUSSRset Crash2.zip](https://github.com/OpenTTD/OpenTTD/files/10387913/xUSSRset.Crash2.zip)
Second crash with xUSSRset as only grf. This time crashed when train arrived to the statrion at oil refinery.

**Comment by PikkaBird** [comment]
While OpenTTD could probably handle it more elegantly, this sounds like a bug with the newgrf. Do not change the capacity of vehicles on the fly!

(also, I can tell you from experience that anything based on last service date will never been seen by players who play with breakdowns turned off, so it's not a good idea even for purely cosmetic changes).

**Comment by SimozzzAK** [comment]
"Changing the date using the date cheat also shifts the vehicle's last serviced date."
That wasn't like that before. Hence why was unnoticed until recently. 

As said on Discord - there is no crash on OpenTTD 10.3. I was asked to send a crash and here it is.

Crash shouldn't appear during regular gameplay, but it really hinders testing of set features ans those a heavly relied on dates. And last service was choosen before as one of most safe options as it changed in depot only. Not anymore though.

If there are other options for livery/available cargo/cargo capacity change controls depending on date - please let George know.

**Comment by PikkaBird** [comment]
If you're changing stats of a vehicle over time, make the later model a separate vehicle. The player can use autoreplace if they want to upgrade all their trains, and the new variants feature can be used to group vehicles and tidy the buy menu.

**Comment by JGRennison** [comment]
> Crash shouldn't appear during regular gameplay, but it really hinders testing of set features ans those a heavly relied on dates. And last service was choosen before as one of most safe options as it changed in depot only. Not anymore though.

#9694

Even if the changing the date doesn't shift the service date, sooner or later the vehicle will enter a depot and you'll encounter these problems anyway.
If you really must use date-dependent functionality, you need to ensure that your GRF works correctly for all possible dates.

**Comment by SimozzzAK** [comment]
> If you're changing stats of a vehicle over time, make the later model a separate vehicle. The player can use autoreplace if they want to upgrade all their trains, and the new variants feature can be used to group vehicles and tidy the buy menu.

That's how it's done in most cases. And those variants is something new, maybe used in some cases.

There are mandatory livery changes like safety stripes on locomotives in 1972 or total repaint in modern RZhD livery 2012 and on. That a global change that should be applied to all vehicles starting at date. Creating separate models for those is not an option.

And it's not an option for container wagons since it's not them who got "updated" but a container it carry. Before 90's there were no tank containers or refrigerator contaiers. But platforms for them were. So how else it should be handled? If there is a way to introduce new cargoes for exicting wagons at given date - let us know.

> Even if the changing the date doesn't shift the service date, sooner or later the vehicle will enter a depot and you'll encounter these problems anyway.

Well, game tells othervise. Only newer OpenTTD have crashes and seems to be tied to how "last service date" is handled there. Before everything was fine but somewhere between 10.3 and 13 RC1 was a change that caused crash.

I assure that everything works fine in 10.3 in all dates, well, at least without crashes, so it's something for you to care about in 13 RC1.

**Comment by JGRennison** [comment]
> I assure that everything works fine in 10.3 in all dates, well, at least without crashes, so it's something for you to care about in 13 RC1.
More likely this is because the RC builds have asserts enabled, but the final releases don't.

**Comment by George-VB** [comment]
> While OpenTTD could probably handle it more elegantly, this sounds like a bug with the newgrf. Do not change the capacity of vehicles on the fly!

date_of_last_service was not intended to be changed outside depot.
Anyway, we are interested to find any solution for our problem (for example, persistent storages for vehicles may solve the problem, because the wagon may store the information, that it is already suitable for new container types, and the capacity code will check this value instead of service date). 

The thing we need is the possibility to have different capacity for a vehicle over time. Mostly for containers.
The change happens 
1) when a new container type becomes available. in this case the capacity for new supported cargo changes from 0 to some new capacity
2) when an other container type should be used (like 40ft container instead of 2 20ft), based on random bits, specified by TRIGGER_VEHICLE_NEW_LOAD (currently we reduce the capacity to prevent crash)
Any suggestions are welcome
