### ISSUE TITLE
[Crash]: Loading old savegame with only an AI in it

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#10331]
### Version of OpenTTD

13.0-RC1, Windows 11 Pro

### Steps to reproduce

Load attached savegame.

### Upload crash files

[crash20230108142944.zip](https://github.com/OpenTTD/OpenTTD/files/10368645/crash20230108142944.zip)

The savegame I tried to load was this:
[Trans v130722, 1st Jan 2151.zip](https://github.com/OpenTTD/OpenTTD/files/10368648/Trans.v130722.1st.Jan.2151.zip)

Emergency save also crashes with:

Assertion failed at line 284 of D:\a\OpenTTD\OpenTTD\src\ai\ai_core.cpp: c != nullptr && c->ai_instance != nullptr

PS: It loads fine on 12.2

**Comment by James103** [comment]
Can reproduce in 7460fdb298.

**Comment by PeterN** [comment]
The game is starting up a new company during the loading process (I assume there is no human company, only AI?). This tries to send an AI/GS event, which probably isn't desirable during loading.
