### ISSUE TITLE
[Bug]: Towns attempt and fail to extend disallowed roadtypes

### ISSUE THREAD

**Issue by PikkaBird** [OpenTTD/OpenTTD#10343]
### Version of OpenTTD

nightly 20230112

### Expected result

The NewRoadType spec includes a property that disallows towns from building particular types of roads - so that a town does not inappropriately consist entirely of motorways or other non-urban roadtype. The town growth function does not appear to account for this, and will attempt to build off non-town roadtypes when expanding. This results in the town creating a lot of ugly T junctions on non-town roadtypes.

Instead, the town should not attempt to extend road from a non-town roadtype. It shouldn't *ignore* these roadtypes altogether, as if they were not roads, because that would mean it wouldn't find areas of town on the other side of the road...

### Actual result

![New Godfield Transport, 1950-01-28](https://user-images.githubusercontent.com/39507755/212214963-9816c49e-350e-40d6-a3da-085727617419.png)
Setup, with non-town roadtype around the edge of the town.

![New Godfield Transport, 1960-01-31](https://user-images.githubusercontent.com/39507755/212215054-e89a44b3-c0ca-45dc-91bb-b11398e1b702.png)
After 10 years, with spiky non-town road.

![New Godfield Transport, 1950-02-15](https://user-images.githubusercontent.com/39507755/212215088-b443f8aa-3da8-42e9-9ea0-00bb2dbf11a6.png)
Without roadtypes.

![New Godfield Transport, 1960-01-27](https://user-images.githubusercontent.com/39507755/212215111-389ede68-3ee3-4098-92a3-6734c2fad211.png)
After 10 years.

### Steps to reproduce

See above screenshots.

**Comment by PeterN** [comment]
Sample NewGRF/savegame to allow easy reproduction?

**Comment by PikkaBird** [comment]
[roadtypetest.zip](https://github.com/OpenTTD/OpenTTD/files/10410914/roadtypetest.zip)

May use the same grfid as previous test grfs, so hopefully you deleted them. :)

**Comment by PeterN** [comment]
After implementing a "can expand current road type" test... initial:
![image](https://user-images.githubusercontent.com/639850/212309435-3967cfbd-d1d3-4f11-b87f-68957dcaf5b2.png)
After 6 years:
![image](https://user-images.githubusercontent.com/639850/212309543-0c329c89-9fe7-4a9f-8f54-2b6dbdd976c1.png)

**Comment by PeterN** [comment]
Here is the same game in master after 6 years:
![image](https://user-images.githubusercontent.com/639850/212310672-780aec44-cee6-45d2-aa6d-ff93f5ef1cab.png)
Seems especially broken because it has built T-junctions on the tan roads, but not actually expanded beyond them.

With my patch, after manually crossing the tan road (I didn't build any grey roads), the town does expand out:
![image](https://user-images.githubusercontent.com/639850/212310861-806eb791-c95f-47e4-8954-927ad43288d2.png)

**Comment by LC-Zorg** [comment]
#8506 describes the same issue.

> EDIT: Needs more work though as currently it disables any growth (houses) around these tiles too.

Shouldn't that be the case? Highways have disabled house growth. The same applies to all other roads where this problem occurred, so everything seems to be working fine.
