### ISSUE TITLE
[Bug]: Bridges cannot not have a speed limit

### ISSUE THREAD

**Issue by PikkaBird** [OpenTTD/OpenTTD#10362]
### Version of OpenTTD

nightly 20230115

### Expected result

All infrastructure in the game with speed limits (road and rail types) can have that speed limit disabled by setting it to 0, except bridges.

### Actual result

Setting bridge speed limit to 0 in NewGRF results in a speed limit of 0 (which means vehicles cross at stall/crawl speed). Setting it to 0xFFFF results in a speed limit of 65,918 km/h.

Setting a bridge speed limit to either 0 or 0xFFFF in NewGRF should disable the speed limit for that bridge (even if that just means setting the speed limit to 0xFFFF and hiding the speed info text in the "select bridge" menu).

### Steps to reproduce

Build a bridge and get over it.

**Comment by 2TallTyler** [comment]
An example grf would make this easier to solve. 😉

**Comment by PikkaBird** [comment]
Oui

[bridgetest.zip](https://github.com/OpenTTD/OpenTTD/files/10425114/bridgetest.zip)
