### ISSUE TITLE
Climate selection icons don't resize at non-integer interface scales

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10367]
### Version of OpenTTD

13.0-RC1

### Expected result

The climate selection graphics in the main menu and the new game/scenario window maintain the proportions of the rest of the interface and they look good.
![Main menu window +](https://user-images.githubusercontent.com/67662046/212990659-1475f056-25fc-4fd3-9039-f51e93807646.png)

### Actual result

Climate selection graphics do not resize appropriately relative to the interface which looks a bit cheap.
![Main menu window](https://user-images.githubusercontent.com/67662046/212990907-a8d13bb0-407b-42f7-a796-a79d9818c7db.png)

### Steps to reproduce

n/a

**Comment by LC-Zorg** [comment]
I don't know if the game can resize files every 25%. I suppose not. I don't know if it would be worthwhile to create or import code to do this in such case. I think a template or templates could also be use. I was curious if it wouldn't be too big, so I made one with all the scales is needed. It is 104KB when compressed. It may not make sense, but it might come in handy. :)
![Climate selection graphics](https://user-images.githubusercontent.com/67662046/212994838-250f8ce3-3b73-460b-83eb-f89ea9bf35bf.png)

**Comment by TrueBrain** [comment]
Although we are constantly working on allowing non-power-of-2 scales for all parts of our interface, it is an ongoing progress. 
Sadly, it is not the easiest work, as a lot of code assumes power-of-2. But, we will get there eventually.

As this is an issue-tracker, and not a feature-request-forum, I am going to close up this issue.
