### ISSUE TITLE
[Crash]: Client chrashed with an error message (13.0RC1)

### ISSUE THREAD

**Issue by AdminChucky** [OpenTTD/OpenTTD#10368]
### Version of OpenTTD

13.0 RC1 - Windows 10

### Steps to reproduce

_The problem could be in previous versions also. I have never tried the following settings before:_

1. Setup a dedicated server with following settings at openttd.cfg: ending_year one year before restart_game_year ( e.g. restart_game_year = 2001  ending_year = 2000 )
2. Start the server and join. No need to play.
3. While throwing the daily news at the end year the client will crash. Server is restarting normally.
![error](https://user-images.githubusercontent.com/65466645/213003172-f0feb60d-635a-4417-823f-dbfad5d98008.jpg)

Further suggestion:
Add a little delay to the code of restart procedure. Is there a message box while restart process? Sometimes it´s been fast.

Regards Chucky

### Upload crash files

[Error.zip](https://github.com/OpenTTD/OpenTTD/files/10439086/Error.zip)

**Comment by glx22** [comment]
```
 	KERNELBASE.dll!00007ff976dccd29()	Inconnu
 	openttd.exe!raise(int signum) Ligne 547	C++
 	openttd.exe!abort() Ligne 71	C++
 	openttd.exe!error(const char * s, ...) Ligne 149	C++
>	openttd.exe!UnInitWindowSystem() Ligne 1863	C++
 	openttd.exe!ResetWindowSystem() Ligne 1872	C++
 	openttd.exe!LoadIntroGame(bool load_newgrfs) Ligne 350	C++
 	openttd.exe!SwitchToMode(SwitchMode new_mode) Ligne 1113	C++
 	openttd.exe!GameLoop() Ligne 1476	C++
 	openttd.exe!VideoDriver::GameLoop() Ligne 37	C++
 	openttd.exe!VideoDriver::GameThread() Ligne 46	C++
 	openttd.exe!StartNewThread::__l3::<lambda>(const char * name, void(*)(VideoDriver *) && F, VideoDriver * && <A_0>) Ligne 65	C++
 	[Code externe]	
 	openttd.exe!thread_start<unsigned int (__cdecl*)(void *),1>(void * const parameter) Ligne 97	C++
 	[Code externe]	
```
