### ISSUE TITLE
[Bug]: incorrect squared aircraft range multiplication

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#10372]
### Version of OpenTTD

13.0-RC1, Windows 11 Pro

### Expected result

65535 * 65535 = 4 294 836 225

### Actual result

65535 * 65535 = 1

### Steps to reproduce

https://github.com/OpenTTD/OpenTTD/blob/58014427800685a4fbaf7b7a242841a78e4ae70c/src/aircraft.h#L65-L69

cached_max_range_sqr is a uint32
cached_max_range is a uint16

When multiplying a uint16 with another uint16, the resulting value is still uint16

https://github.com/OpenTTD/OpenTTD/blob/58014427800685a4fbaf7b7a242841a78e4ae70c/src/aircraft_cmd.cpp#L608-L609

https://github.com/OpenTTD/OpenTTD/blob/58014427800685a4fbaf7b7a242841a78e4ae70c/src/script/api/script_engine.cpp#L272-L274

**Comment by SamuXarick** [comment]
Cannot reproduce this any longer.

**Comment by glx22** [comment]
Most likely fixed with #10533
