### ISSUE TITLE
[Bug]: Loading a pre-#9931 savegame bars all level crossings, even when no train nearby

### ISSUE THREAD

**Issue by vmicho** [OpenTTD/OpenTTD#10395]
### Version of OpenTTD

13.0-RC1 linux

### Expected result

Sometimes/some level crossings are blocked, without any train around, even when not connected to anything.
I did not see this in v12.

Example in the middle:
![Tennville Transport, 2157-07-27](https://user-images.githubusercontent.com/66125746/213920450-7cf8123f-1e4a-4fe0-9f25-fa0a66533bbe.png)

Another one:
![Tennville Transport, 2172-06-19-crop](https://user-images.githubusercontent.com/66125746/213920809-605ca5b7-8ca1-4900-a9ca-3998000d7427.png)

### Actual result

should not block

### Steps to reproduce

unknown :/

**Comment by 2TallTyler** [comment]
If I had to guess, I'd point at phantom path reservations. Can you provide savegames where this occurs, or try turning on "Show path reservations" to see if the tiles are reserved?

**Comment by LC-Zorg** [comment]
This is repeatable in every save. It seems that the level crossings remain closed after the game starts until the first train passes.
I thought this was intentional behavior. :)

**Comment by 2TallTyler** [comment]
That's not intended, but should be easy to fix.
