### ISSUE TITLE
[Crash]: Fatal application Failure on startup (graphics driver crash)

### ISSUE THREAD

**Issue by AccidentByDragon** [OpenTTD/OpenTTD#10394]
### Version of OpenTTD

12.2, windows 10

### Steps to reproduce

attempted to start the game from steam
have tested different versions of OTTD(Including nightly) and reinstalling same error and crash

### Upload crash files

[crash20230122121903.zip](https://github.com/OpenTTD/OpenTTD/files/10474394/crash20230122121903.zip)
[crash20230122122619.zip](https://github.com/OpenTTD/OpenTTD/files/10474418/crash20230122122619.zip)

**Comment by nielsmh** [comment]
This crash log is from version 12.2, but what's more important is it seems to happen in the graphics driver.
What GPU do you have?

**Comment by SuicideByDragon** [comment]
AMD Radeon R9 380

**Comment by nielsmh** [comment]
Both log files you have attached still appear to be from version 12.2. When you open the crashlog.txt file inside each ZIP, one of the first lines says the game version that wrote the file.

Try going into the Properties for the game on Steam and add `-v win32` in the Launch Options:
![image](https://user-images.githubusercontent.com/1062071/213920774-b0901467-c7ba-48bf-8787-47ce33b44a19.png)

That should force the game to start in software rendering mode, to rule out whether the issue is the graphics driver or something else.

**Comment by SuicideByDragon** [comment]
it runs with that change

**Comment by glx22** [comment]
```
 	0000000000000000()	Inconnu
 	atio6axx.dll!00007ffef7cfa50e()	Inconnu
 	atio6axx.dll!00007ffef7d0139d()	Inconnu
 	atio6axx.dll!00007ffef7cf66db()	Inconnu
 	atio6axx.dll!00007ffef7cf25bc()	Inconnu
 	atio6axx.dll!00007ffef7cf58f8()	Inconnu
 	opengl32.dll!pgldrvLoadAndAllocDriverInfo()	Inconnu
 	opengl32.dll!LoadAvailableDrivers()	Inconnu
 	opengl32.dll!__DescribePrimaryPixelFormat()	Inconnu
 	opengl32.dll!wglNumHardwareFormats()	Inconnu
 	opengl32.dll!wglDescribePixelFormat()	Inconnu
 	opengl32.dll!wglChoosePixelFormat()	Inconnu
 	gdi32full.dll!ChoosePixelFormat()	Inconnu
>	openttd.exe!SelectPixelFormat(HDC__ * dc, bool) Ligne 1236	C++
 	openttd.exe!LoadWGLExtensions() Ligne 1254	C++
 	openttd.exe!VideoDriver_Win32OpenGL::Start(const std::vector<std::string,std::allocator<std::string>> & param) Ligne 1302	C++
 	openttd.exe!DriverFactoryBase::SelectDriverImpl(const std::string & name, Driver::Type type) Ligne 122	C++
 	openttd.exe!DriverFactoryBase::SelectDriver(const std::string & name, Driver::Type type) Ligne 87	C++
 	openttd.exe!openttd_main(int argc, char * * argv) Ligne 742	C++
 	openttd.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Ligne 416	C++
 	[Code externe]	
```
