### ISSUE TITLE
[Bug]: Iron Ore Mine ignores transparent industries

### ISSUE THREAD

**Issue by gh658804** [OpenTTD/OpenTTD#10416]
### Version of OpenTTD

12.2

### Expected result

Ore mine should disappear when clicking on Transparency Options / Industries

### Actual result

All industries disappear. Iron Ore mine does not. Also, the coal from coal mines does not. All these using zBase as Base Graphics Set.

### Steps to reproduce

Click on Transparency Options / Industries.

**Comment by gh658804** [comment]
https://imgur.com/a/URssayd

**Comment by PeterN** [comment]
![image](https://user-images.githubusercontent.com/639850/214972881-f8243236-f2d6-454a-8ebc-ad678c4d91c0.png)

Unlike other industries, iron ore mines do not have building pieces places on top the ground, they are simply drawn as part of the ground tile. Transparent industries only hides the building pieces. It's not possible to not draw the ground tile.

**Comment by gh658804** [comment]
Ah, ok, i understand the logic behind it but to a user, it seems a little off. I'm guessing the same thing happens with the coal in coal mines (that's why it remained visible when transparency was On).

Anyway, i'm guessing this will remain as is, so please feel free to close it if you agree.

**Comment by 2TallTyler** [comment]
Yes, this is known behavior that is unlikely to be changed. 

I suppose it could be possible to draw a standard grass sprite as the ground tile and then draw the mine tile as the building piece, but there could be issues with NewGRFs that inherit graphics from vanilla industries. Probably too much work for little benefit.
