### ISSUE TITLE
[Bug]: Trains fail to pick free track

### ISSUE THREAD

**Issue by programmingstranger** [OpenTTD/OpenTTD#10428]
### Version of OpenTTD

13.0

### Expected result

After turning off 90° turns for trains, trains refuse to enter station onto free track and therefore do not follow the entry and exit signals that have been placed at the station. If a train gets lost or need to turn around by entering a terminal station, the train refuses to choose the free track in the station. The train tried to just go straight forward without attempting to switch to free track in station. This causes trains to back up endlessly.

### Actual result

After passing a free entry signal, the train should see that one of the platforms is occupied and choose the free platform in the station.

### Steps to reproduce

<img width="981" alt="Screenshot 2023-01-28 at 23 37 35" src="https://user-images.githubusercontent.com/123843035/215294741-b1edd294-ffa0-42de-b23a-1c5defbf2519.png">
<img width="1094" alt="Screenshot 2023-01-28 at 23 55 40" src="https://user-images.githubusercontent.com/123843035/215294827-3c81a864-9cbd-4fd6-86f9-2585a414fdc1.png">

**Comment by PikkaBird** [comment]
This appears to be an example of #1473, listed in known-bugs.txt as known but not planned to fix.

The solutions are a) use path signals in preference to presignals, and b) redesign your network so trains do not get lost.

**Comment by 2TallTyler** [comment]
Agreed, not a new bug. Path signals are the solution to this, and also allow for a train to arrive while another is departing from the parallel track.
