### ISSUE TITLE
[Bug]: some level crossings still barred

### ISSUE THREAD

**Issue by vmicho** [OpenTTD/OpenTTD#10434]
### Version of OpenTTD

13.0-RC2

### Expected result

After fixes in 
https://github.com/OpenTTD/OpenTTD/issues/10395
some level crossings are still barred for no obvious reason

### Actual result

should not be barred

### Steps to reproduce

[mito-crossing-bug.sav.zip](https://github.com/OpenTTD/OpenTTD/files/10539363/mito-crossing-bug.sav.zip)

Just open and the viewport should already contain the set of crossings. Some are barred, some not, same track.
Save was I think last saved in v13.rc1 or v12.x, created in v1.xxx long time ago, but the crossings were added during v12.

![Tennville Transport, 2172-06-19-crop](https://user-images.githubusercontent.com/66125746/215580979-c65c4e61-aad6-4e76-a67a-acae8ba22ecb.png)

**Comment by 2TallTyler** [comment]
Saving the game in 13.0-RC1 with the crossings barred may have locked them in that state. Can you try with a game that was last saved prior to 13.0-RC1?

**Comment by vmicho** [comment]
[saves2.zip](https://github.com/OpenTTD/OpenTTD/files/10562108/saves2.zip)

I found the old save.
Open the mito-crossing-v12.2.sav in v12.2: all OK.
Open the same save in v13rc2 -> all OK
Open the same save in v13rc1 -> all crossings barred
  save (as mito-crossing-v13.0rc1.sav) , open in rc1 or rc2 -> all crossings barred

**Comment by glx22** [comment]
Expected, the conversion was wrong in 13rc1, and there's no conversion between 13rc1 and 13rc2.

**Comment by 2TallTyler** [comment]
Yep, it was just broken in 13.0-RC1.

If you don't want to lose your progress in between saves, you can easily reset the crossings by running a train across them.

Thanks for the report.
