### ISSUE TITLE
[Bug]: Train suddenly started producing only cost instead of profit

### ISSUE THREAD

**Issue by gh658804** [OpenTTD/OpenTTD#10449]
### Version of OpenTTD

12.2 Win10

### Expected result

Train 86 should produce profit. It carries coal from a mine to a power station through a relatively easy and close path. It was producing profit for several years, but lately when it reaches the destination station and unloads all its cargo, it displays a cost instead of profit.

### Actual result

Problem described in "Expected result" field.

### Steps to reproduce

Just monitor the trip of Train 86 and the result when it unloads all cargo at destination station.
[Nick A. Transport, 2101-07-27.sav.zip](https://github.com/OpenTTD/OpenTTD/files/10611604/Nick.A.Transport.2101-07-27.sav.zip)

**Comment by PikkaBird** [comment]
The source station appears to be full of coal transferred from another mine (which is even closer to the destination power plant) by train 101. Train 86's profits are being eaten by this inefficient transfer.

**Comment by gh658804** [comment]
Great! What can happen with one mistake...

Thanks for finding it.
