### ISSUE TITLE
[Bug]: Translation issue

### ISSUE THREAD

**Issue by ZarTek-Creole** [OpenTTD/OpenTTD#10456]
### Version of OpenTTD

12.2

### Expected result

Hello, I am part of the French translator team. Values, the rest in English despite the modifications of several versions ago already.

I made screenshots in the following ticket: https://github.com/orgs/OpenTTD/teams/fr_fr/discussions/2

If a developer could check if there are real problems or tell us the exact strings to modify, it could be useful for the release of version 13. Thank you for your work and your free time

### Actual result

Read above, thank you.

### Steps to reproduce

Read above, thank you.

**Comment by 2TallTyler** [comment]
The user interface pictured in the linked screenshots is not vanilla OpenTTD. I think it's CityMania's "cmclient" by @ldpl, but could also be JGR's Patchpack.

**Comment by 2TallTyler** [comment]
@ldpl confirmed that this is cmclient. There is not a way to translate these strings in OpenTTD's Web Translator -- you would have to contact the author of that patchpack directly.
