### ISSUE TITLE
NewGRF-created error messages don't identify the NewGRF

### ISSUE THREAD

**Issue by GrzegorzDrozd** [OpenTTD/OpenTTD#10453]
### Version of OpenTTD

13.0, Windows 10

### Expected result

Hi,

After adding some NewGRF's I see an error when staring new game. It says: 
![image](https://user-images.githubusercontent.com/1885137/217231741-a6973bb8-37e6-4bbf-b1a5-ec2286a8ef2c.png)
Can you add name of that NewGRF? I can see only one side of the issue and it is very hard to track which module is reporting this issue.

### Actual result

Error message does not say which module is incompatible. 

### Steps to reproduce

1. Add multiple NewGRFs
2. Start new game
3. See warning from the screen.

**Comment by PikkaBird** [comment]
If you look in NewGRF Settings (under the 3rd icon on the toolbar), it should show an error icon next to the newgrf which has the problem, and repeat the error in the information panel.

**Comment by PikkaBird** [comment]
But I agree it might be nice for NewGRF error message windows to include the name of the grf which has thrown them.

**Comment by GrzegorzDrozd** [comment]
> If you look in NewGRF Settings (under the 3rd icon on the toolbar), it should show an error icon next to the newgrf which has the problem, and repeat the error in the information panel.

Thank you :) It is there :) 
Should I close this ticket or do we want devs to add that name there?

**Comment by 2TallTyler** [comment]
I agree, let's keep this open as something to fix.
