### ISSUE TITLE
[Bug]: docker latest points to 13.0-RC1 Version mismatch with 13.0 stable

### ISSUE THREAD

**Issue by cpt-n3mo** [OpenTTD/OpenTTD#10460]
### Version of OpenTTD

13.0-RC1 and 13.0 stable

### Expected result

docker latest should point to 13.0

### Actual result

docker latest points to 13.0-RC1

### Steps to reproduce

docker run -d -p 3979:3979/tcp -p 3979:3979/udp bateau/openttd:latest

**Comment by TrueBrain** [comment]
Tnx for your report.

Sadly, Docker images are not official supported and as such not maintained by us. You would have to ask the author of the image to update it, or wait and hope the author does so soon.

Hopefully it gets addressed soon!
