### ISSUE TITLE
[Bug]: Build bridge window truncates speed and cost

### ISSUE THREAD

**Issue by fmang** [OpenTTD/OpenTTD#10477]
### Version of OpenTTD

13.0, macOS 11.7.3

### Expected result

When building a bridge, the bridge type selection window should show the name for each item along with the max speed and the cost.

If the window were too narrow, I’d expect items to take more vertical space, or at least the ability to grow the window manually.

### Actual result

The opened window is too narrow and some data is truncated.

![スクリーンショット 2023-02-14 14 37 31](https://user-images.githubusercontent.com/1500359/218651364-dd3c7480-8eab-4a64-9063-a89885675db1.png)

### Steps to reproduce

I have the following custom settings in openttd.cfg:

```ini
[misc]
language = japanese.lng
small_font = IPAexゴシック
medium_font = IPAexゴシック
large_font = IPAexゴシック
mono_font = IPAexゴシック
small_size = 12
medium_size = 14
large_size = 16
mono_size = 12
small_aa = true
medium_aa = true
large_aa = true
mono_aa = true
```

The bug is produced regardless of the UI zoom level, though I typically use 125%.

The font is available at <https://moji.or.jp/ipafont/ipaex00401/>. Click [IPAexfont00401.zip(9.3MB)](https://moji.or.jp/wp-content/ipafont/IPAexfont/IPAexfont00401.zip) to download.

1. Start any vanilla game in temperate climate at year 2000.
2. Try building a bridge over 5 tiles long.

**Comment by fmang** [comment]
The build airport window has a similar issue: the maintenance costs are truncated. That too could be mitigated by letting the user resize the window.

![スクリーンショット 2023-02-14 20 41 35](https://user-images.githubusercontent.com/1500359/218728002-c974e540-61dc-4023-b242-82468d77d8ff.png)

**Comment by PikkaBird** [comment]
The bridge names should probably truncate if they're too long, rather than line wrapping.

Without prejudice to the general concept of widening windows for longer text lines, I wonder if those two specific lines can't be shortened - perhaps カンチレバー could be dropped from the bridge name, and there's surely a better translation for "maintenance cost" than spelling it out in kana.

**Comment by PeterN** [comment]
You could try reducing the font size but then increase the interface scale a bit more. That should provide a bit more space.

**Comment by fmang** [comment]
Though I’m not familiar with OpenTTD’s codebase, it feels like the window size is automatically calculated from the text bounding box, so there’s likely a bug in the computation somewhere. Shortening the translation might cause the bug on the next longest bridge name, but that’s worth a try. 

<https://github.com/OpenTTD/OpenTTD/blob/fe2c8a1240957d8569ae8bae7fe9499ba3bca666/src/bridge_gui.cpp#L200-L214>

I’ve tried setting the font size to 8 and adjusting the zoom, but the window gets resized proportionally so the issue remains.

I’ll experiment with the translations and see.

**Comment by PeterN** [comment]
Hmm, might be an issue with the text layouter on OSX, it works fine on Windows...
![image](https://user-images.githubusercontent.com/639850/218753047-ca5e360f-c1c8-4ef1-b6f0-461d5039fa2e.png)

**Comment by fmang** [comment]
Out of curiosity, I tried making the bridge name longer. The window grew longer too, but still cuts at the same place. There must be something off somewhere.

![スクリーンショット 2023-02-15 11 36 15](https://user-images.githubusercontent.com/1500359/218927018-87a3b178-2871-42e6-8a1f-c33c673bd72b.png)

To be honest I’m not too fond of the automatic window size calculation. One pixel off and the display breaks. A fixed width but better handling of long names would make the window more robust. Simplifying “Cantilever truss bridge” into “Truss bridge” is a nice workaround though:

![スクリーンショット 2023-02-15 12 00 04](https://user-images.githubusercontent.com/1500359/218928694-0354beb8-ed55-40b7-94fd-5c14805e2409.png)

Concerning airport selection, the window width is probably fixed regardless of the font size, so reducing the font size does solves the issue but that affects the whole UI. As PikkaBird pointed out, actually translating the string rather than using an phonetic transcription of English makes the text shorter. 維持費 already appears often in OpenTTD’s Japanese translation for both maintenance costs and running costs, though the meaning is closer to maintenance costs.

![スクリーンショット 2023-02-15 11 33 05](https://user-images.githubusercontent.com/1500359/218926127-c6986432-6f7f-4836-a7f4-eeb8c422ff2c.png)

Below is the patch I suggest. I also added spaces before the parentheses for aesthetics. I’d make a pull request but you seem to use Web Translator instead. Should I request access?

```diff
diff --git a/src/lang/japanese.txt b/src/lang/japanese.txt
index 446a818e7..9b9150967 100644
--- a/src/lang/japanese.txt
+++ b/src/lang/japanese.txt
@@ -2600,7 +2600,7 @@ STR_STATION_BUILD_COVERAGE_AREA_OFF_TOOLTIP                     :{BLACK}停留
 STR_STATION_BUILD_COVERAGE_AREA_ON_TOOLTIP                      :{BLACK}停留施設の旅客・貨物集荷範囲をハイライトします
 STR_STATION_BUILD_ACCEPTS_CARGO                                 :{BLACK}受入貨物: {GOLD}{CARGO_LIST}
 STR_STATION_BUILD_SUPPLIES_CARGO                                :{BLACK}供給貨物: {GOLD}{CARGO_LIST}
-STR_STATION_BUILD_INFRASTRUCTURE_COST                           :{BLACK}メンテナンスコスト: {GOLD}{CURRENCY_SHORT}/年
+STR_STATION_BUILD_INFRASTRUCTURE_COST                           :{BLACK}維持費: {GOLD}{CURRENCY_SHORT}/年
 
 # Join station window
 STR_JOIN_STATION_CAPTION                                        :{WHITE}停留施設を統合
@@ -2684,14 +2684,14 @@ STR_SELECT_RAIL_BRIDGE_CAPTION                                  :{WHITE}鉄道
 STR_SELECT_ROAD_BRIDGE_CAPTION                                  :{WHITE}道路橋建設
 STR_SELECT_BRIDGE_SELECTION_TOOLTIP                             :{BLACK}建設したい橋の種類をクリックしてください
 STR_SELECT_BRIDGE_INFO_NAME                                     :{GOLD}{STRING}
-STR_BRIDGE_NAME_SUSPENSION_STEEL                                :吊橋(S造)
-STR_BRIDGE_NAME_GIRDER_STEEL                                    :桁橋(S造)
-STR_BRIDGE_NAME_CANTILEVER_STEEL                                :カンチレバートラス橋(S造)
-STR_BRIDGE_NAME_SUSPENSION_CONCRETE                             :吊橋(RC造)
-STR_BRIDGE_NAME_WOODEN                                          :トラス橋(木造)
-STR_BRIDGE_NAME_CONCRETE                                        :桁橋(RC造)
-STR_BRIDGE_NAME_TUBULAR_STEEL                                   :管状橋(S造)
-STR_BRIDGE_TUBULAR_SILICON                                      :管状橋(シリコン造)
+STR_BRIDGE_NAME_SUSPENSION_STEEL                                :吊橋 (S造)
+STR_BRIDGE_NAME_GIRDER_STEEL                                    :桁橋 (S造)
+STR_BRIDGE_NAME_CANTILEVER_STEEL                                :トラス橋 (S造)
+STR_BRIDGE_NAME_SUSPENSION_CONCRETE                             :吊橋 (RC造)
+STR_BRIDGE_NAME_WOODEN                                          :トラス橋 (木造)
+STR_BRIDGE_NAME_CONCRETE                                        :桁橋 (RC造)
+STR_BRIDGE_NAME_TUBULAR_STEEL                                   :管状橋 (S造)
+STR_BRIDGE_TUBULAR_SILICON                                      :管状橋 (シリコン造)
 
 
 # Road construction toolbar
```

**Comment by PeterN** [comment]
> To be honest I’m not too fond of the automatic window size calculation. One pixel off and the display breaks. A fixed width but better handling of long names would make the window more robust. Simplifying “Cantilever truss bridge” into “Truss bridge” is a nice workaround though:

But it shouldn't ever be a pixel off -- the same layout code is used to determine the text width both when calculating the size and drawing the text. Fixed width relies on the guessed width to be sufficient to work.

**Comment by fmang** [comment]
There’s theory and there’s practice. As much as I hate quickfixes, I think adding a few extra pixels, or an extra hsep_normal at the end to allow room for error is a reasonable solution.

I made an experiment adding a single extra pixel to the window width, and that fixes it.

```diff
diff --git a/src/bridge_gui.cpp b/src/bridge_gui.cpp
index 62f4c96b9..bbcef13c4 100644
--- a/src/bridge_gui.cpp
+++ b/src/bridge_gui.cpp
@@ -209,7 +209,7 @@ public:
                                resize->height = std::max(sprite_dim.height, text_dim.height) + padding.height; // Max of both sizes + account for matrix edges.
 
                                this->bridgetext_offset = sprite_dim.width + WidgetDimensions::scaled.hsep_normal; // Left edge of text, 1 pixel distance from the sprite.
-                               size->width = this->bridgetext_offset + text_dim.width + padding.width;
+                               size->width = this->bridgetext_offset + text_dim.width + padding.width + 1;
                                size->height = 4 * resize->height; // Smallest bridge gui is 4 entries high in the matrix.
                                break;
                        }
```

![スクリーンショット 2023-02-17 13 49 49](https://user-images.githubusercontent.com/1500359/219552360-3d8b8a50-54e3-4001-b738-d1506249cac1.png)

I noticed gfx_layout.cpp mixes ints and floats, so a one-pixel error due to rounding is not that improbable.

Somewhat related, I found this line in the font renderer for macOS which acknowledges that everything does not always go as expected:

https://github.com/OpenTTD/OpenTTD/blob/27cbb81df5cf97f78ffbab9bd64f6daba6c21bc9/src/os/macosx/font_osx.cpp#L277

**Comment by PeterN** [comment]
Ah ha, that's why I can't reproduce. This seems likely to be the cause, in which case the solution is much deeper (but also more general) than adding 1 here and there to each widget width.

https://github.com/OpenTTD/OpenTTD/blob/27cbb81df5cf97f78ffbab9bd64f6daba6c21bc9/src/os/macosx/string_osx.cpp#L256

This line simply floors the float with the cast to int. It may be better to explicitly round or ceil this result?

**Comment by fmang** [comment]
Looks like you found the culprit indeed.

Concerning the airport maintenance cost, since it’s not a bug with the code but more like an excessively long translation string, where or whom to should I report it?
