### ISSUE TITLE
[Bug]: Noise control setting doesn't describe airport number limit well

### ISSUE THREAD

**Issue by EratoNysiad** [OpenTTD/OpenTTD#10478]
### Version of OpenTTD

13.0, Windows 10

### Expected result

![image](https://user-images.githubusercontent.com/10280358/218809290-f2eb4c59-2f42-4b75-888a-d5d38ded69a7.png)
When this setting is set to "Off", I expect to be able to place an unlimited amount of airports

### Actual result

![image](https://user-images.githubusercontent.com/10280358/218809264-45e93cda-c798-43e6-818a-7a4ec8f79f3b.png)
I am limited to only 2 airports, regardless of what this is set to

### Steps to reproduce

1. Set the "Allow town controlled noise level for airports" setting to "Off"
2. Attempt to place 3 airports near a single town.

**Comment by James103** [comment]
Workaround:
1. Install the NewGRF "OpenGFX+ Airports" with the disable airport noise limits parameter enabled.
2. Turn on "Allow town controlled noise level for airports"
3. You should now be able to build many more airports near a single town.

**Comment by PikkaBird** [comment]
With the noise limit setting off, the game reverts to the default TTD behaviour of allowing only two airports per town.

There are two ways to allow building unlimited airports: 

1) turn noise limits off, and set "Local authority attitude" to "Permissive".
2) turn noise limits on, and use a GRF that sets airport noise to 0, as James103 mentioned.

**Comment by PikkaBird** [comment]
The way it functions in 13.0 is correct according to the PR which added the functionality (#9833). It's interesting that it works differently in JGRPP, but doesn't necessarily make either implementation "wrong".

The tooltip is out-of-date and doesn't reflect the changes in #9833. That could definitely be considered a bug.

**Comment by 2TallTyler** [comment]
I don't quite understand this report. Which setting helptext isn't descriptive enough?

**Comment by PikkaBird** [comment]
The "bug" in the description text for 'Allow town controlled noise level for airports' is that "With this setting disabled, there can be two airports in each town" is no longer true if 'local authority attitude' is set to 'permissive'.

This functionality being affected by two independent settings, as well as potentially newgrf, is a bit of a mess. :) But the real confusion that resulted in this bug report stems from JGR implementing the interaction between the two settings differently from vanilla.
