### ISSUE TITLE
[Bug]: The area objects construction / land purchase feature is not available to the average player

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10473]
### Version of OpenTTD

13.0, Refers to #9709

### Expected result

It is possible to build objects / buy land by area.

### Actual result

It is not possible to build objects / buy land by area.
The reason is the default setting: build_object_frame_burst = 1
![area objects construction](https://user-images.githubusercontent.com/67662046/218346386-2f5740da-70f9-4b93-8508-9c8578a4a42f.gif)

If the player doesn't know about the existence of hidden settings in the configuration file, he will not know how to enable it. Unless the player reads the changelogs and stumbles across some information about this feature, he won't even know it exists.

### Steps to reproduce

n/a

**Comment by glx22** [comment]
The default value for build_object_frame_burst is 2048.

**Comment by 2TallTyler** [comment]
I agree with glx. The default value is 2048 and allows the advertise behavior, so if the setting value is different, it's because the player chose it. I suspect in your case it's left over from when you [tested](https://github.com/OpenTTD/OpenTTD/pull/9709#issuecomment-974489669) the original PR. 😉

**Comment by LC-Zorg** [comment]
I suspect it too. :) Most likely, I must have changed this setting and have long forgotten about it. After reset the settings, it works as described.
