### ISSUE TITLE
[Bug]: No display

### ISSUE THREAD

**Issue by JimmyNaidoo** [OpenTTD/OpenTTD#10482]
### Version of OpenTTD

13.0 KDE Neon(Flatpak)

### Expected result

Expected game to start with display.

### Actual result

Game runs in background, can hear audio but no display.

### Steps to reproduce

Tested on 2 different systems running the same OS(KDE Neon Stable). Game worked with initial version 13(Flatpak). Flatpak has since been updated, causing current issue.

**Comment by PeterN** [comment]
The Flatpak build is not created by us and has patches applied. Feel free to try with our generic binary instead.

**Comment by JimmyNaidoo** [comment]
> The Flatpak build is not created by us and has patches applied. Feel free to try with our generic binary instead.

Generic binary works just fine...

**Comment by wolfgang42** [comment]
Crosslinking https://github.com/flathub/org.openttd.OpenTTD/issues/103 since this issue came up first in a search
