### ISSUE TITLE
[Feature]: 1.5x scale for interface scaling

### ISSUE THREAD

**Issue by Limyx826** [OpenTTD/OpenTTD#10506]
### Version of OpenTTD

1.13.0

### Recommendation

The current UI scaling for OpenTTD is either too small at 1x or too big at 2x for screen resolution of 1920 x 1080. In order to remedy this 1.5x scale must be implement into the base game. Previously, a NewGRF called OpenGFX big GUI managed to do this but hasn't been update for years now with some icons missing.

**Comment by Limyx826** [comment]
Discussion at #10505

**Comment by TrueBrain** [comment]
Please don't use the issue tracker for feature-requests. Your discussion was the right call, no need to make more noise :) Let's close up this issue, in favour of the discussion!
