### ISSUE TITLE
[Bug]: GSGoal missing method for updating data like GSLeagueTable

### ISSUE THREAD

**Issue by npabisz** [OpenTTD/OpenTTD#10503]
### Version of OpenTTD

13.0

### Expected result

`GSGoal` should have method to update `type` and `destination` for existing goal instance. Similar to `GSLeagueTable.UpdateElementData`

### Actual result

There is no way to change eg. `companyId` if goal was rearranged. Right now only way to change it is to remove all goals and re-add which is slow and noticeable.

### Steps to reproduce

1. Add two or more goals
2. Rearrange goals changing their text
3. Still links to old company/town

**Comment by 2TallTyler** [comment]
Fixed by #10817 (I think).
