### ISSUE TITLE
[Bug]: Inconsistency in company ID

### ISSUE THREAD

**Issue by npabisz** [OpenTTD/OpenTTD#10501]
### Version of OpenTTD

13.0

### Expected result

Using company ID from GS in console for `reset_company` command should remove that company. Optionally we should have `GSCompany.ResetCompany` method.

### Actual result

`GSCompany` returns IDs with index starting at `0` while `reset_company` accepts index starting at `1`.

### Steps to reproduce

1. Use `GSCompany.ResolveCompanyID` to get the ID
2. Use this ID with `reset_company <company-id>` command

**Comment by glx22** [comment]
For humans, companies are numbered from 1, because it's more intuitive.

**Comment by 2TallTyler** [comment]
I'm inclined to close this as "not a bug." Adding a `GSCompany.ResetCompany` method might be a good addition, but doesn't justify keeping this issue open, IMHO. Feel free to open a PR or a separate issue specifically for that, if you feel it's important.
