### ISSUE TITLE
[Crash]: Game crashes when closing the window if it is narrower than the confirmation message

### ISSUE THREAD

**Issue by merni-ns** [OpenTTD/OpenTTD#10530]
### Version of OpenTTD

13.0, Windows 11

### Steps to reproduce

1. Start a game.
2. Resize the game window to be smaller than the confirmation popup that you get when closing the game window (with the X on the corner of the window, not ingame menu)
3. Close the window.
4. Crash occurs.

See https://github.com/JGRennison/OpenTTD-patches/issues/490 which was the initial report, and contains a probable fix.

### Upload crash files

[OpenTTD.zip](https://github.com/OpenTTD/OpenTTD/files/10869828/OpenTTD.zip)

**Comment by LordAro** [comment]
Related #8869
