### ISSUE TITLE
[Bug]: Default parameters in NewGRF not used when an active GRF is upgraded

### ISSUE THREAD

**Issue by cmcaine** [OpenTTD/OpenTTD#10549]
### Version of OpenTTD

13.0, Windows 10

### Expected result

A GRFs default values should be loaded if no value was specified by the user.

### Actual result

When parameters are added in a new version of a GRF, the new parameters take the value 0 rather than their default.

(at least in this case)

### Steps to reproduce

1. Get "Sailing Ships 0.62" from BaNaNaS and install it as an active GRF. This GRF has no parameters.
2. Activate it.
3. Close OpenTTD
4. Remove Sailing Ships from the content_download folder
5. Add ss.grf (a newer version of Sailing Ships GRF that has parameters) to your /newgrf/ folder
6. Start the game, click new game, newgrf settings, set parameters for "Sailing Ships (tweaked) 0.72" and observe that all parameters have value 0 (if you want to observe that the value really is 0, start a new game in 1705 and check if a ship called Schooner is available, if it is, then the "Ship introduction date" parameter is not at its default value (1: Historical)).
7. Click "reset". Observe that all parameters now have named values

[ss.zip](https://github.com/OpenTTD/OpenTTD/files/10909374/ss.zip)

The source for ss.zip can be found here: https://github.com/cmcaine/OpenTTD-Sailing-Ships commit bbaf839a613133ef7bdcd4522eb7b8749564a247

**Comment by James103** [comment]
See also https://github.com/OpenTTD/OpenTTD/issues/8846

**Comment by frosch123** [comment]
#8846 was fixed in #11348.
If a NewGRF is defined as "incompatible" it will now reset *all* parameters to defaults.

I am not sure whether there is a good method to only set new parameters to default. In the "load savegame/scenario with compatible NewGRF" case, there is definitely not.

But the "upgrade NewGRF preset" feature could be more confortable.

**Comment by 2TallTyler** [comment]
As discussed on Discord, I believe #11348 resolves this issue. When a NewGRF author adds or rearranges parameters, they will need to bump the compatible version. Then, a user upgrading the NewGRF will have all parameters set to the defaults. (Not just the new ones; existing choices will be lost and need to be re-selected by the player.)

**Comment by Andrew350** [comment]
Quote from #11348:

>If a NewGRF changes or adds parameters with non-zero defaults, this is (currently) always a savegame-incompatible change.

If indeed this is (has been?) the expected procedure (bumping compatibility) for this case, then it is not mentioned anywhere in the action 14 spec. If no further solution to this is desirable (or possible) then this fact needs to be explained to help others avoid this issue. Happy to add a note to the spec if true, but want to confirm first 🙂
