### ISSUE TITLE
[Bug]: Linkgraph hover tooltip "average travel time" is incorrect

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#10547]
### Version of OpenTTD

13.0, Windows 10

### Expected result

The linkgraph hover tooltip introduced in #9760 shows an `Average travel time` which roughly matches the timetable of vehicles using that link.

### Actual result

The number is incorrect.

![mismatch](https://user-images.githubusercontent.com/55058389/223229495-8a3b1f78-13f1-4c48-b9c3-7004ba5395bd.png)

I have not bisected to find the commit which broke this, but it worked as recently as February 1, [when I was checking my timetable unit conversions against it](https://github.com/OpenTTD/OpenTTD/pull/10322#issuecomment-1412644335).

### Steps to reproduce

1. Build a simple two-stop bus route in a town, with one bus on it
2. Enable the Cargo Flow Legend for the chosen company and cargo
3. Let the bus travel until the link is established
4. Observe that the average link travel time does not match the vehicle's timetabled time

**Comment by JGRennison** [comment]
The average travel time will vary, and is in any case not guaranteed to match what has been entered into the timetable. Timetable times must be larger than the minimum journey time to be useful.
It is unlikely that any regression has occurred since this measurement or tooltip was added.

**Comment by 2TallTyler** [comment]
Ah, I didn't realize that very short journeys could have a large enough discrepancy between timetables and the average time of the link to be noticeable. My previous tests used longer routes.
