### ISSUE TITLE
[Bug]: Train chain with inadequate vertical position in depot windows

### ISSUE THREAD

**Issue by J0anJosep** [OpenTTD/OpenTTD#10550]
### Version of OpenTTD

master at commit 87f4d37de379da391fc4478161fcec66824a48c8 linux

### Expected result

Train chain in vehicle depot should be vertically aligned, or at least not covering the bevel, as months ago:
![orig](https://user-images.githubusercontent.com/3152990/223433731-02cc810c-0256-4a36-9f7b-8cd04891d0b7.png)

The rectangle drawn when moving a vehicle train/chain should match vertically the vehicle sprite.

Commit reference of the version used for the screenshot:
c482f05616 ("Update: Translations from eints english (au): 7 changes by krysclarke", 2022-10-07)

### Actual result

Train chain is drawn at the top of the rectangle, ignoring the bevel.

![imatge](https://user-images.githubusercontent.com/3152990/223434767-966c2fe3-bdc8-416a-adb6-5dc989d462ac.png)
![imatge](https://user-images.githubusercontent.com/3152990/223434875-976fc1c7-c5c0-4a59-b72d-315cd574f6b1.png)

Commit reference of the version used:
87f4d37de3 ("Fix #10522: Link graph line tooltip test for vertical lines (#10524)", 2023-03-03)

### Steps to reproduce

Build a train depot.
Buy a rail vehicle.

**Comment by PeterN** [comment]
This is an issue with the OpenGFX baseset, not OpenTTD.

**Comment by J0anJosep** [comment]
@PeterN
> This is an issue with the OpenGFX baseset, not OpenTTD.

In October the vehicles weren't drawn over the bevel. Did the OpenGFX baseset change since October?

**Comment by PeterN** [comment]
OpenGFX has always been wrong. Here it is in 12.2:

![image](https://user-images.githubusercontent.com/639850/224315121-1c254573-b42d-4b0d-8f3d-c9fdce8ae909.png)

**Comment by J0anJosep** [comment]
@PeterN
> OpenGFX has always been wrong. Here it is in 12.2:
> 
> ![image](https://user-images.githubusercontent.com/639850/224315121-1c254573-b42d-4b0d-8f3d-c9fdce8ae909.png)

There is no open issue in OpenGFX about these offsets. Cannot they be fixed?

**Comment by PeterN** [comment]
Opened as OpenTTD/OpenGFX#83
