### ISSUE TITLE
[Bug]: Cannot open scenario from console

### ISSUE THREAD

**Issue by szczot3k** [OpenTTD/OpenTTD#10567]
### Version of OpenTTD

13.0, Debian 11.6

### Expected result

When downloading any content from the Dedicated Server's perspective (with `content` command), I should be able to use the content in question right away, without having to manually un-tar the archive, and put it into the respective folders, or at least be able to `load` the tar-ed scenario (in this case). `docs/directory_structure.md` states that it should be possible. On my Windows OpenTTD running as a client I can use the content just fine, even tho it's tar-ed.

### Actual result

1. The `content` (scenario in this case) is downloaded
1.1. The content is showing as "Installed"
1.2. The content is visible under `~/.local/share/openttd/content_download/scenario/`, as a tar archive
2. I can't load the content, either via `./openttd -D -g ~/.local/share/openttd/content_download/scenario/xyz.tar`
2.1. I can't load the content via traversing the directory layout, with the dedicated server console (either tho it's there, it just doesn't "want" to see the .tar archive)
```
pwd
/home/openttd/.local/share/openttd/content_download/scenario/
ls
0) .. (folder nadrzędny)
1) heightmap/ (folder)
```

### Steps to reproduce

1. Start the dedicated server via `./openttd -D`
2. Update the content cache (`content update`)
3. Select a scenario (`content select 3927155`)
4. Download the scenario (`content download`)
(you can even restart the game here, won't help)
You can then check the `content_download/scenario` folder, and you'll see the tar-ed archive.
You can try to load it via `./openttd -D -g (path)`, or just via load command, it won't work.

**Comment by glx22** [comment]
Ok, did some tests in debugger. The issue is `ls` only tries to list savegames.

**Comment by TrueBrain** [comment]
For `-g`, you have to list the path inside the tarball too. This might sound odd, but for OpenTTD tarballs are just a folder, like any other. For example, I downloaded a random scenario `South_Sweden.0.2_Beta`. I can start this with:

`./openttd -g 00000130-South_Sweden-0.2_Beta.tar/South_Sweden.0.2_Beta/South_Sweden_Beta_2.scn`

Or if you are not on the nightly / 14.0, you can use:

`./openttd -g 00000130-South_Sweden-0.2_Beta.tar/South_Sweden_Beta_2.scn`

As you can see, the tar is just considered a folder. (and before nightly / 14.0, the first folder in a tar was ignored).

I will change this issue to address that you cannot load a scenario via the console; that is a bug.
