### ISSUE TITLE
[Bug]: Windowed mode seems not be centered accurately

### ISSUE THREAD

**Issue by telk5093** [OpenTTD/OpenTTD#10569]
### Version of OpenTTD

13.0

### Expected result

Window mode would be centered perfectly

### Actual result

I'm using QHD monitors (2560x1440) and the window resolution of OpenTTD is 2400x1350, which are all 16:9 ratios.
When opens the game, game is opened with windowed-mode and it should be centered.
Mostly it is centered but there is a slight height that is hidden by task bar.

It seems that it is not considering the height of window's title

https://user-images.githubusercontent.com/10726524/224693406-0cc91ee7-c75c-45c6-a207-ff796af8fd4f.mp4
See the bridge that is on the right of the double yellow bridge in the left bottom side in the above video.

### Steps to reproduce

1. In QHD monitor
2. Set ``resolution = 2400,1350`` in ``openttd.cfg``
3. Opens the game

**Comment by LordAro** [comment]
Perhaps we should stop trying to position the window on Windows?

**Comment by nielsmh** [comment]
Radical thought: Attempt to centre the client area of the window within the desktop area of the primary display.
