### ISSUE TITLE
[Bug]: No way in GUI to select a previous version of AI or GS

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#10578]
### Version of OpenTTD

13.0 (old bug)

### Expected result

The creator or tester of AI/GS is free to enable different versions of them at the same time for comparison and further improvement.
The player can choose a particular earlier version of AI/GS that they liked more or that simply didn't have the bugs that were evident when using it.

### Actual result

To test a previous version of AI or GS, all newer versions must be removed from the folder. Once this is done, it is not possible to re-enable the newer version - again you have to restore the deleted versions. This is cumbersome and inconsistent with what you might expect by selecting a setting that allows you to view older versions of add-ons.

Personally, I recently tested AAAHogEx, I noticed differences in behavior after the last update, but I wasn't sure if it was a coincidence or a real effect. So I wanted to run the previous version... but that turned out to be impossible*.

Recently, I also created another alternative version of my RWD script and here, too, I used several versions at the same time for comparison. There was no problem here because each of them was renamed taking into account the version. If I wanted to publish it so that the player could choose, even though the changes are rather cosmetic, I would have to publish each version as a separate add-on, thus messing up the list of add-ons.

### Steps to reproduce

If you have multiple versions of one of AI or GS:
- try to run the latest version, then select the previous one, after that select the latest one again
- try running several games at once, each with a different AI/SI version

**Comment by LC-Zorg** [comment]
Several possibilities of what the AI/GS selection window could look like in practice
![AI,GS selection - variants](https://user-images.githubusercontent.com/67662046/227315784-48459bf7-f9a5-4ef5-b189-9d377f63fb8c.png)

**Comment by glx22** [comment]
It's mainly a GUI issue. You can use `start_ai ai.version` console command.
