### ISSUE TITLE
[Bug]: (Steam) Black screen on startup, can hear background noise.  Cannot get past.

### ISSUE THREAD

**Issue by Fingerthecat** [OpenTTD/OpenTTD#10571]
### Version of OpenTTD

13.0, Windows 10

### Expected result

I have uninstalled and reinstalled multiple times to no avail.  And google doesn't seem to be very helpful...

### Actual result

I hit play in steam.  
  
The game starts up and creates a black screen, though I can hear the vehicle noises that the background creates from the main menu.  
  
I can only hit windows key to get out of it and close the game from steam.

### Steps to reproduce

I don't know how to reproduce nor figure out how to get it to stop.

**Comment by glx22** [comment]
Add `-v win32` in launch properties.

**Comment by Fingerthecat** [comment]
> Add `-v win32` in launch properties.

Holy crap it worked.  I appreciate it man, tried for like 3 days searching and I couldn't find a solution.

**Comment by glx22** [comment]
It's a kinda known issue, but it's very hard for us to understand the root cause. What is your CPU/GPU ?
