### ISSUE TITLE
[Bug]: Server time out (netzwork traffic)

### ISSUE THREAD

**Issue by SpartaWarsec** [OpenTTD/OpenTTD#10588]
### Version of OpenTTD

13.0

### Expected result

so I have tested this on 2 different linux ("Debian") servers 

and the server has the problem that it has micro dropouts from a map size of 2000x2000 that can last up to 10 seconds both servers are completely new and clean installed 

it makes it seem as if he is calculating something 

the problem is worse when the server is running on a machine that has less singel core performance

SERVER 1
56 x Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz (2 Sockets)
256GB RAM
(VM)system Debian 11.1.0 amd64

SERVER 2
16 x Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (1 Socket) OC on 5.2GHZ
128GB RAM
(VM)system Debian 11.1.0 amd64

![openttd bug](https://user-images.githubusercontent.com/52891531/229181484-4bd0cea9-3fe2-4525-9f9a-1338831632d2.jpg)
BUG

![openttd normal](https://user-images.githubusercontent.com/52891531/229181496-d61308d6-e388-4d9f-9f01-59e4f40532f3.jpg)
ALL GOOD

### Actual result

and the server has the problem that it has micro dropouts from a map size of 2000x2000 that can last up to 10 seconds both servers are completely new and clean installed 

### Steps to reproduce

Connect on the server and wait no more

**Comment by PeterN** [comment]
Is this related to autosave? Saving a 2048x2048 map does take some time...

**Comment by SpartaWarsec** [comment]
yes auto save is on the error does not appear in the autosave itself

but it is only saved every year and the error does not occur on save but it occurs every 1-3 minutes

**Comment by 2TallTyler** [comment]
@SpartaWarsec Are you still experiencing this problem?
