### ISSUE TITLE
[Crash]: Flatpak version blinks a black screen and crashes

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [OpenTTD/OpenTTD#10599]
### Version of OpenTTD

13.0, Gentoo linux

### Steps to reproduce

1. Install openttd via flatpak
2. Start it via flatpak command or from application menu

### Upload crash files

[crazh.zip](https://github.com/OpenTTD/OpenTTD/files/11152585/crazh.zip)

**Comment by glx22** [comment]
Probable duplicate of #10232

**Comment by JohnTheCoolingFan** [comment]
Yes, it is, sorry.
