### ISSUE TITLE
[Bug]: Steam launches Intel variant instead of Apple Silicon variant

### ISSUE THREAD

**Issue by Mack-Mack** [OpenTTD/OpenTTD#10592]
### Version of OpenTTD

13.0 via steam, Apple Silicon(M2) OSX Ventura 13.2.1

### Expected result

When launching via steam on an apple silicon Mac the apple version should load.

### Actual result

Instead the intel version loads. When launching the app executable directly from finder the correct apple version does load.

### Steps to reproduce

1. On a apple silicon Mac download and launch via steam
2. Load activity monitor and under the kind window see it has loaded the intel version 
3. shut down and launch OpenTTD directly from the steam directory
4. Note it now loads the apple silicon version

**Comment by TrueBrain** [comment]
As mentioned, there is very little we can actually do about this. We ship our binary as an universal, which means it contains both the Intel and Apple Silicon variant.

When we launched on Steam, it was an issue that Steam was running as Intel binary, and as such, all games it launched are also Intel. By now I think they resolved that issue, which means you should see Steam running as a native app.

To make it explicit our binary is an universal, I updated the Steam metadata to mention this explicitly. Maybe that also triggers Steam to launch the app properly .. but honestly, there is not much more we can do.
This change was pushed with https://steamdb.info/changelist/18299812/, and a restart of the Steam client should cause it to load in the update. Let us know if that fixes the problem.

If not, please double-check Steam is actually running natively. And if that is the case ... I am out of ideas :D

**Comment by Mack-Mack** [comment]
Regarding steam it loads as an intel app, by googling it appears there is no apple silicon version just yet. I have retested loading OpenTTD from steam and unfortunately it still loads the intel version. On a side note thank you for this brilliant game.

**Comment by TrueBrain** [comment]
Then there is sadly little we can do to address this issue. Possibly it might help to raise the issue at Steam's side.

Going to close this issue for now, as there is nothing actionable for us here. Sorry about the non-solution :(

**Comment by twiedenbein** [comment]
If you add `/usr/bin/arch -64 %COMMAND%` to the launch options for OpenTTD, you can force it to use the native binary. Some other games use wrapper scripts to ensure the proper binary version gets launched.

**Comment by Mack-Mack** [comment]
Thanks, that fixes the issue

> If you add `/usr/bin/arch -64 %COMMAND%` to the launch options for OpenTTD, you can force it to use the native binary. Some other games use wrapper scripts to ensure the proper binary version gets launched.
> 
> <img alt="Screen Shot 2023-04-22 at 6 30 30 PM" width="888" src="https://user-images.githubusercontent.com/244838/233819918-2b0a5992-66b1-4e92-989c-8b21dc0d2e18.png">

**Comment by axu2** [comment]
Based on https://www.reddit.com/r/macgaming/comments/z5xlhx/can_steam_be_forced_to_open_the_apple_silicon/ a Steamworks update might fix it, if it's not already fixed.

**Comment by Mack-Mack** [comment]
Just tested on my MacBook Air M2 running Ventura 13.4.1 and the post UI update version of Steam.

Loading from steam will cause the Intel version to load however if the code below is added to OpenTTD's launch options it will open the Apple version. I can't get the steam overlay to work on either version, it does function on Crusader Kings 2. I hope this info is of some use.

/usr/bin/arch -64 %COMMAND%
