### ISSUE TITLE
[Bug]: "Replace vehicles" doesn't show number greater than 999

### ISSUE THREAD

**Issue by DefinitelyNotRau117** [OpenTTD/OpenTTD#10600]
### Version of OpenTTD

13.0 Windows 10

### Expected result

The number of vehicles is displayed with an accuracy of one
![изображение](https://user-images.githubusercontent.com/115672237/229955124-ca714f8d-ade5-4b1c-b7bb-1ed13479f523.png)

### Actual result

Only the first thousand digit is displayed, on some fonts – just « . . . »

Tahoma (and others not monospaced):
![изображение](https://user-images.githubusercontent.com/115672237/229951534-f35d6bb9-0271-4540-b41e-e87c88141dfc.png) 
![изображение](https://user-images.githubusercontent.com/115672237/229954588-62eeb5ef-de64-4b02-84c7-8273c47ddc60.png)

Consolas (and others monospaced):
![изображение](https://user-images.githubusercontent.com/115672237/229952792-d9f87db8-9909-42c4-bc5f-71136b7360dc.png) Consolas

Built-in openGFX sprite font:
![изображение](https://user-images.githubusercontent.com/115672237/229953782-dbb4dc7b-2cd8-430b-a86c-c721cb5622cb.png)

But the second digit does not appear on the original baseset sprite font:
![изображение](https://user-images.githubusercontent.com/115672237/229953899-d5f624bd-0472-49e5-bea5-7594122d75d8.png)

### Steps to reproduce

1. Create more than 999 vehicles/wagons of the same model
2. Open the corresponding replacement menu

1. Or open the wagon replacement menu in 10k.sav [999.zip](https://github.com/OpenTTD/OpenTTD/files/11154272/999.zip)

**Comment by glx22** [comment]
It's because https://github.com/OpenTTD/OpenTTD/blob/master/src/build_vehicle_gui.cpp#L1013
