### ISSUE TITLE
[Bug]: Flatpak OpenTTD hangs and never starts

### ISSUE THREAD

**Issue by KenSharp** [OpenTTD/OpenTTD#10615]
### Version of OpenTTD

OpenTTD 13.0, Ubuntu 22.04

### Expected result

Run OpenTTD.

### Actual result

Simply trying to run OpenTTD from the Flatpak appears to do nothing, but it actually sits in the background using 100% of one CPU.

```
$ flatpak run org.openttd.OpenTTD -d driver3
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Resolution for display: 1280x800
dbg: [driver] SDL2: Mouse is at (0, 0), use display 0 (0, 0, 1024, 768)
dbg: [driver] SDL2: using mode 1280x800
dbg: [driver] SDL2: using driver 'offscreen'
dbg: [driver] OpenGL driver: NVIDIA Corporation - Quadro K5000/PCIe/SSE2 (4.6.0 NVIDIA 470.161.03)
dbg: [driver] OpenGL: Using persistent buffer mapping
dbg: [driver] OpenGL shading language version: 4.60 NVIDIA, texture units = 192
dbg: [driver] Successfully probed video driver 'sdl-opengl'
dbg: [driver] Successfully probed sound driver 'sdl'
dbg: [driver] Fluidsynth: sf (null)
dbg: [driver] Fluidsynth: samplerate 44100
dbg: [driver] Successfully probed music driver 'fluidsynth'
dbg: [driver] using thread for game-loop
dbg: [driver] Switching blitter from '32bpp-anim' to '40bpp-anim'... 
dbg: [driver] Successfully loaded blitter '40bpp-anim'
dbg: [driver] Successfully switched to 40bpp-anim.
dbg: [driver] SDL2: using mode 1280x800
dbg: [driver] SDL2: using mode 1280x800
```
And that's it.

### Steps to reproduce

I've tried [another game](https://flathub.org/apps/details/io.github.endless_sky.endless_sky)  that uses the same runtime and it works fine.

I tried the various options for video drivers and resolutions but none of them make any difference, the result is the same.

I don't know what else to try.

**Comment by glx22** [comment]
Duplicate of #10232

**Comment by KenSharp** [comment]
There is no black screen and no crash (backtrace)!

**Comment by KenSharp** [comment]
Furthermore, `fc-list` does not cause a crash and runs fine.
`fc-cache` aborts with an assertion failure.

That's very different behaviour to the linked bug, assuming that information is correct.

**Comment by glx22** [comment]
So it's more like #9913.
Could be an opengl problem, try `flatpak run org.openttd.OpenTTD -v sdl`.

**Comment by KenSharp** [comment]
> So it's more like #9913.

Yeah that's what I thought but the bug is closed upstream, and other apps run fine with the current runtime.

>Could be an opengl problem, try `flatpak run org.openttd.OpenTTD -v sdl`

Like I said: I tried them all, makes no difference.

**Comment by TrueBrain** [comment]
From the logs above, there seems to be something odd about your setup. This is reported:
`dbg: [driver] SDL2: using driver 'offscreen'`

For some reason, SDL is selecting your `offscreen` SDL driver, which, as the name suggests, is not on screen. This is meant for headless rendering, and should be disabled by default. 

As we leave selecting the driver up to SDL, this is also not something we can control. You can however influence it with the environment variable `SDL_VIDEODRIVER`. I have no clue why SDL doesn't select the right driver for you, but again, also not really in our control.

If you wouldn't mind, I am curious if our official Linux binaries (see [here](https://www.openttd.org/downloads/openttd-releases/latest)) also shows the same behaviour. Flatpak is not build nor maintained by us, so I am also not sure which SDL version it is using. Of our own Linux binary, I am.

Tnx!

**Comment by KenSharp** [comment]
The downloaded binary works fine!

`dbg: [driver] SDL2: using driver 'x11'`

I tried using `SDL_VIDEODRIVER` but it couldn't find `x11`:

```
$ SDL_VIDEODRIVER=x11 flatpak run org.openttd.OpenTTD -d driver3
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Probing video driver 'sdl-opengl' failed with error: x11 not available
dbg: [driver] Probing video driver 'sdl' failed with error: x11 not available
```

An unnofficial Snap package also works fine. I'll open a bug report on Flatpak. Thanks!

**Comment by KenSharp** [comment]
Looks like this has [already been logged](https://github.com/flathub/org.openttd.OpenTTD/issues/103), albeit badly.

`$ sudo flatpak override --socket=fallback-x11 org.openttd.OpenTTD` allows OpenTTD to load.

**Comment by Eddi-z** [comment]
the "sudo" in there worries me...

**Comment by KenSharp** [comment]
Doesn't work without `sudo`

```
$ flatpak override --socket=fallback-x11 org.openttd.OpenTTD
error: Permission denied
```
