### ISSUE TITLE
[Crash]: When clicking on local authority button

### ISSUE THREAD

**Issue by Caber-nl** [OpenTTD/OpenTTD#10617]
### Version of OpenTTD

13.0 Windows 11

### Steps to reproduce

1. Click on a town/city
2. Click on the local authority button

### Upload crash files

[crash20230409134424.zip](https://github.com/OpenTTD/OpenTTD/files/11185593/crash20230409134424.zip)

**Comment by JGRennison** [comment]
This is probably the same as: https://github.com/OpenTTD/OpenTTD/issues/10461

**Comment by 2TallTyler** [comment]
Were you a spectator in a network game? Probably a duplicate of #10461.

**Comment by Caber-nl** [comment]
> Were you a spectator in a network game?

It was a network game. If memory serves me well I had been a spectator until half a minute before the crash. I joined my company to buy a statue (if memory serves me well).

**Comment by JGRennison** [comment]
The crash screenshot shows that the client was spectating when the error occurred.

**Comment by 2TallTyler** [comment]
Duplicate of #10461, then. 🙂 

It's fixed in nightlies, just needs a 13.1 release to bring it to everyone.
