### ISSUE TITLE
[Bug]: Using the date cheat can create vehicles with negative last service dates.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#10630]
### Version of OpenTTD

9e69556e2f on Windows 10, 64-bit (via Steam)

### Expected result

Vehicle service dates should be clamped below at 1st Jan 0 (internal value `0`), even after using the date cheat.

### Actual result

After using the date cheat to go back thousands of years, some never-serviced vehicles originally built in the 21st century AD (game time) can end up with service dates in e.g. the 6th century BC. Such dates are not displayed properly due to incorrect rounding of negative values.

### Steps to reproduce

1. Start a new 64x64 map in the year 2100 on the best CPU you have access to (by single threaded performance).
2. Build a road vehicle depot.
3. Build a vehicle inside that depot.
4. Start that vehicle. Orders don't matter.
5. Once the vehicle leaves the depot, demolish it so the vehicle does not service again.
6. Wait 3000 in-game years (should take a few minutes on a high-end computer).
7. In-game year should now be around 5000. Use the date cheat to set it back to the year 2300.
8. Check the vehicle last service date and notice it is negative.

**Comment by 2TallTyler** [comment]
You don't need to change dates by thousands of years. Just let one year elapse and then use the date cheat to go back to year 0. 🙂
