### ISSUE TITLE
[Bug]: Japanese characters are garbled.

### ISSUE THREAD

**Issue by salmonmikan** [OpenTTD/OpenTTD#10645]
### Version of OpenTTD

13.0、android13、Pixel 6a

### Expected result

Normal startup

### Actual result

![Screenshot_20230413-122339](https://user-images.githubusercontent.com/94634410/231641087-f4803150-dfc1-4284-9a6f-88a84d32f21e.png)

### Steps to reproduce

Error on title screen after starting as normal.

**Comment by MiguelHorta** [comment]
Hi,
that is an Android issue, that is not an officially supported platform. I copied your issue to where development for Android is currently taking place. At first glance it seems is not fallbacking correctly to a font that supports Japanese.

**Comment by TrueBrain** [comment]
Tnx! Will close the issue here, as that is not something within our control :)
