### ISSUE TITLE
[Bug]: (Not really a bug) Playstyle incompatibility with #10596

### ISSUE THREAD

**Issue by TheMowgliMan** [OpenTTD/OpenTTD#10656]
### Version of OpenTTD

Any OpenTTD version with PR #10596

### Expected result

People can play with any playstyle, building long train routes, short train routes, or anything in between. Or they use ships, I can't make judgements on other people's playstyles.

### Actual result

Some playstyles are hobbled by #10596, or made completely unplayable. This especially makes ships useless and airplanes "overpowered."

Basically, long or slow routes no longer make money---or at least as much as they used to. This hobbles gameplay in these styles and makes games that start with very slow vehicles (E.g. a mostly trains game with NARS that starts in 1860) extremely difficult to get going. It also might impact existing long-running servers and any remaining OpenTTDCoop games. It would also be confusing to players who don't keep track of the codebase and overall makes a very drastic change in a 20-year-old game that tries to remain true to it's roots.

However, the PR does have merit in some cases.

A possible solution would be to add settings for cargo decay time and time factor to adjust cargo decay. Unfortunately, I do not have the C++ knowledge to be able to institute a fix, so the best I can do is create an issue (Which doesn't really work either, unfortunately).

### Steps to reproduce

N/A

**Comment by Andrew350** [comment]
> Some playstyles are hobbled by https://github.com/OpenTTD/OpenTTD/pull/10596, or made completely unplayable. This especially makes ships useless and airplanes "overpowered."

Ships have always been useless and planes have always been overpowered. #10596 does nothing to change this fact. And this is coming from someone who has experience working with ships and wishing they would have some way to have more impact 😢 

> Basically, long or slow routes no longer make money---or at least as much as they used to. This hobbles gameplay in these styles and makes games that start with very slow vehicles (E.g. a mostly trains game with NARS that starts in 1860) extremely difficult to get going.

I have (so far) not observed this. The only case where #10596 makes any noticeable change is in the most extreme case where exceptionally slow vehicles are placed on exceptionally long routes. I have saves where ships travel over 500 tiles - an already quite long distance - and have observed very little change in overall profitability. If you are relying on even more ridiculous routes to serve as the backbone of profitability for your company then you have been relying on bad behavior IMHO.

As long as you start with sensible routes which are at least modestly profitable (i.e. just as you should have before #10596), I see no change in the overall playability in the game except in the most extreme playstyles, which themselves have no excuse for being unplayable given the fact that the money cheat and other "workarounds" already exist in order to facilitate them. 

If you want a sailing ship or horse-drawn-carriage which takes 2 years to make it's route to be profitable than ultimately you should ask a NewGRF author to make it so by setting running costs to basically zero. Although I suspect that most authors of such NewGRFs never intended their NewGRFs to be used in such an extreme way, and instead it was a result of the limited cargo aging effect which resulted in this behavior even being possible, which #10596 actually solves.

Again though, this is just my opinion, maybe others think differently.

**Comment by michicc** [comment]
As the title already says, "Not really a bug", and as such not something for issues anyway.

If you have comments specifically regarding #10596, make the comments there please. For general game play balance comments, you may start a GitHub discussion if you want.

**Comment by LordAro** [comment]
(Ideally with some actual data of before and after, with justifications)

**Comment by TheMowgliMan** [comment]
> As the title already says, "Not really a bug", and as such not something for issues anyway.
> 
> If you have comments specifically regarding #10596, make the comments there please. For general game play balance comments, you may start a GitHub discussion if you want.

I did make a comment there (Along with several other people), but @ldpl  wasn't interested in a compromise. It was almost a flame war.

> (Ideally with some actual data of before and after, with justifications)
See comments in #10596.


> Ships have always been useless and planes have always been overpowered. #10596 does nothing to change this fact. And this is coming from someone who has experience working with ships and wishing they would have some way to have more impact 😢
> 
> I have (so far) not observed this. The only case where #10596 makes any noticeable change is in the most extreme case where exceptionally slow vehicles are placed on exceptionally long routes. I have saves where ships travel over 500 tiles - an already quite long distance - and have observed very little change in overall profitability. If you are relying on even more ridiculous routes to serve as the backbone of profitability for your company then you have been relying on bad behavior IMHO.
> 
> If you want a sailing ship or horse-drawn-carriage which takes 2 years to make it's route to be profitable than ultimately you should ask a NewGRF author to make it so by setting running costs to basically zero. Although I suspect that most authors of such NewGRFs never intended their NewGRFs to be used in such an extreme way, and instead it was a result of the limited cargo aging effect which resulted in this behavior even being possible, which #10596 actually solves.
> 
> Again though, this is just my opinion, maybe others think differently.

Yeah, I also wish ships were more playable.

For information on how routes are affected, see this comment in #10596:
> Ok, so now I did the tests myself...
> 
> The same map, I changed the details, because indeed that graph and these "230" led me astray.
> 
>     * changed the set of trains - cars for red and yellow are much more capacious and although they have a small negative multiplier for cargo aging, in 13.1 the effect is much higher income (2-3 times more)
> 
>     * changed the route of green - now it travels a much longer, natural-looking route through the land of mountains and lakes
> 
>     * added a company (blue) that creates a network of connections using slow sailing ships
>       ![Long Dist Cargo Payment TEST v2](https://user-images.githubusercontent.com/67662046/231607517-63793613-55cf-4a3c-9ddb-32429d91bae5.png)
>       [LDCPT v2.zip](https://github.com/OpenTTD/OpenTTD/files/11216854/LDCPT.v2.zip)
>       In all cases, decreases in income are noticeable. In the case of red and yellow, they are acceptable and the change is not a problem in my opinion. In the case of green and blue, the drop in income is very large and devastating.
> 
> 
> Do you think such building and playing styles should be excluded from this game? This is still a medium sized map. What about the bigger ones?
> 
> One more example... ![Slow vehicles in 19th century](https://user-images.githubusercontent.com/67662046/231607536-1e592688-3d12-4f2f-9794-912c4e77e476.png) Do you think that the current slow vehicle add-ons should only be loss making or that it was impossible to build longer routes with them?

I do wish old games would be playable though, especially for people who like to play realistic games. Where is this going to leave the people who play realistic games on large maps and start with slow steam engines?

A possible workaround for them might be to use #10606 to increase cargo production, but that's _really_ ugly.

Sorry for the long posts ;)

**Comment by TheMowgliMan** [comment]
> As the title already says, "Not really a bug", and as such not something for issues anyway.
> 
> If you have comments specifically regarding #10596, make the comments there please. For general game play balance comments, you may start a GitHub discussion if you want.

Afterthought: also, #10596 is already merged, so it makes more sense to raise an issue. I don't really have a forum account, so this left the only place left for me.

**Comment by TrueBrain** [comment]
As a FYI: discussions are available [here](https://github.com/OpenTTD/OpenTTD/discussions). It is part of GitHub. This is what @michicc is referring to.

**Comment by TheMowgliMan** [comment]
Ah yes. Thank you.
