### ISSUE TITLE
[Bug]: Wonky scaling of company window at non-integer interface scale

### ISSUE THREAD

**Issue by LordAro** [OpenTTD/OpenTTD#10661]
### Version of OpenTTD

master ( 730687080a )

### Expected result

Company window should scale nicely at all interface scale levels. Here's 2x:

![](https://i.imgur.com/ZOrAFgJ.png)

### Actual result

1.25x
![](https://i.imgur.com/23AMw6b.png)

1.75x
![](https://i.imgur.com/hOQghxF.png)

### Steps to reproduce

1. Open the company window
2. Set scaling to something like 1.75x

**Comment by PeterN** [comment]
Scaling is perfect, just the image can't be scaled. I could centre it, or carry on working on the non-powers of two sprite scaler...

**Comment by 2TallTyler** [comment]
Horizontal centering might be a good stop-gap solution. I'd still keep it top-aligned within its space, though.

**Comment by LordAro** [comment]
That's all I was expecting. Though the manager name/title should sit just under the portrait regardless - not with the big vertical gap that's there currently
