### ISSUE TITLE
[Bug]: NO_VEHICLES_AVAILABLE_YET calculation does not consider climate

### ISSUE THREAD

**Issue by greg-kennedy** [OpenTTD/OpenTTD#10665]
### Version of OpenTTD

1.13.1, Windows 10

### Expected result

"No Vehicles Are Available Yet" message should appear when a new game is started before 1935 in Toyland.  Introduction date of MightyMover trucks should be fixed (not randomized).

### Actual result

"No Vehicles Are Available Yet" message appears when a new game is started before 1925 in Toyland.  Starting a game after 1925 but before 1935 creates a game with no available vehicles, until 1935 when MightyMover trucks become available.  No warning message is displayed in this case.

### Steps to reproduce

1. Start a new game Jan. 1, 1925 in Toyland.
2. "No vehicles available yet" message does not appear.
3. No vehicles are available.
4. Fast-forward to 1935, trucks are introduced.

**Comment by greg-kennedy** [comment]
I think the issue is that the filter on climate occurs on line 711 of src/engine.cpp: https://github.com/OpenTTD/OpenTTD/blob/b19f42ecd92226bb7959c5f5bc1c9676fe8b980b/src/engine.cpp#L711

but this is after the check for intro_date and setting of flag ENGINE_AVAILABLE, line 677:
https://github.com/OpenTTD/OpenTTD/blob/b19f42ecd92226bb7959c5f5bc1c9676fe8b980b/src/engine.cpp#L677

...therefore the Temperate engines are causing the game to think engines are available in 1925, but then disabling those temperate engines for being the wrong climate.

**Comment by 2TallTyler** [comment]
Since it looks like you've already identified the problem, if you feel like learning to [compile OpenTTD](https://github.com/OpenTTD/OpenTTD/blob/master/COMPILING.md), this might be a good first PR to contribute a fix! 😃
