### ISSUE TITLE
[Bug]: Interface including fonts and viewports doesn’t scale properly on Mac OS with retina display

### ISSUE THREAD

**Issue by dpk** [OpenTTD/OpenTTD#10660]
### Version of OpenTTD

OpenTTD 13.1, also current nightly (20230415-master), Mac OS 13.3 (ARM)

### Expected result

Opening OpenTTD on a Mac with a retina display and setting interface scaling to 2x should cause everything, including fonts, to scale. Only the margins around the fonts changes. The scale of the actual game is also too small, including in the startup screen.

### Actual result

1x scaling, everything ‘correct’ in terms of proportions but too small to be seen on a high-resolution screen:
<img width="1136" alt="Screenshot 2023-04-16 at 11 51 20" src="https://user-images.githubusercontent.com/378375/232292780-7f0e0ce7-4caa-41b5-aa49-c1d1e2b4e2c5.png">

2x scaling, margins around interface elements increased but nothing else, and everything still too small to comfortably read:
<img width="1136" alt="Screenshot 2023-04-16 at 11 51 16" src="https://user-images.githubusercontent.com/378375/232293184-cee1f799-ea7d-45b0-a114-233bb7244c22.png">

If I enable ‘Auto-detect size’, it just changes to 2x scaling and looks exactly the same as when I select that manually.

### Steps to reproduce

Open OpenTTD 13.1 on Mac OS. Fiddle with the Interface scale option in Game Options.

I’m using the original_windows graphics set, if that might make a difference. @LordAro suggested this might also be helpful info:

<img width="126" alt="Screenshot 2023-04-16 at 11 59 19" src="https://user-images.githubusercontent.com/378375/232292543-56776248-e46d-441f-a5ea-2d6998afbf30.png">

**Comment by glx22** [comment]
Sprite font is not resizable, but you can set a TrueType font with the `font` command.

**Comment by LordAro** [comment]
That's not true, it resizes for me on Linux

![](https://i.imgur.com/owz27vb.png)

**Comment by PeterN** [comment]
This happens if you've changed the max sprite zoom setting to be 1x instead of 4x

**Comment by 2TallTyler** [comment]
Related issue of that setting changing things it probably shouldn't: #8873

**Comment by PeterN** [comment]
Hmm, that one is even worse as those gui sprites are handled in the same way as viewport sprites, and some sprites are drawn in both viewport and gui. At least fonts is an easier case to deal with :)

**Comment by PeterN** [comment]
Ah, not that one, "Maximum zoom in level".

**Comment by PeterN** [comment]
Change it to 4x. 4x is the default value, normal means 1x. The context is a bit wrong for how it ends up being used here...

**Comment by PeterN** [comment]
You are right, this setting didn't previously affect font sprites before 13.0.
