### ISSUE TITLE
[Crash]: Segmentation fault on house loop (game has removed house GRF)

### ISSUE THREAD

**Issue by maaaaaaaaaad** [OpenTTD/OpenTTD#10681]
### Version of OpenTTD

13.1 - OS 13.2.1

### Steps to reproduce

1. No specific action was taken at the moment of the crash

### Upload crash files

File too large to upload - use this link.
https://www.dropbox.com/s/3giiz7y0jqt9nm9/Archive.zip?dl=0

**Comment by PeterN** [comment]
Do you also have the last good copy of the savegame before the crash?

**Comment by maaaaaaaaaad** [comment]
Sure:
https://www.dropbox.com/s/r6in26v2goetykn/JR%2C%20Feb%2020th%2C%201974.sav%202.zip?dl=0

**Comment by PeterN** [comment]
Oops, didn't see this, and it's deleted now.

**Comment by TrueBrain** [comment]
@maaaaaaaaaad sadly, the files are no longer available on Dropbox. Would it be possible for you to upload at least the `crash.log` (in a zip or not) to this ticket? As how it stands, we have no information at all about what happened :)

Tnx!

**Comment by maaaaaaaaaad** [comment]
Hi,
I believe this is the last save game:
https://www.dropbox.com/s/w9uk5q5750pvv29/JR%2C%20Feb%2020th%2C%201974.sav%202.zip?dl=0

**Comment by glx22** [comment]
This savegame seems to run fine for me. And without `crash.log` we are in the dark.

**Comment by maaaaaaaaaad** [comment]
The same issue occurred again, this time .log, .sav .png is included 

https://www.dropbox.com/scl/fo/sjstfs0vv5x9xnhkyvh22/h?dl=0&rlkey=dgjfqdpjy4i33qf7986e3lwae

**Comment by glx22** [comment]
Log seems to indicate the crash happens during house loop, but it also shows you removed newgrf, one of them being a house grf.

**Comment by TrueBrain** [comment]
I am really sorry, but I am going to close this issue.

As @glx22 mentioned, this is most likely to you removing a House GRF. This is notorious for causing problems, and the reason why you can only modify GRFs when in developer-mode, and why you get this warning when making changes:

![image](https://github.com/OpenTTD/OpenTTD/assets/1663690/904afc50-4187-46c5-ace2-f855ea101572)

We are not kidding about that, sadly :(

One of the most common causes is that there is somewhere a 2x2 house on your map, which used to be managed by the GRF you removed. As this GRF is now gone, the game no longer knows it is a 2x2 house, but sees 4 1x1 houses. When a town starts to modify these houses individually, for example by removing one of them, it will not remove all 4 tiles (as the game doesn't know they belong to each other). This leaves the game in a very tricky state, as .. is it gone? Isn't it? This also causes graphical glitches, etc. and in the end more often than not, crashes. But, as you have noticed, often years and years after the removal of the GRF.

So sadly, I am going to close this issue, as this really isn't something we can prevent or avoid .. other than telling people to not modify GRFs on a running game. And I know how annoying this is, especially for a map you have been running for so long .. so I do apologize. But there is very little I can do for your here :(

**Comment by maaaaaaaaaad** [comment]
No worries, thanks for letting me know. I’m aware that I was playing with fire when I started to add newGrF.I’ll wait until there’s a fix with the RealHouses Grf to start a new scenario.Thanks for all the hard work you and the team put into this project - I’ve been a avid TTD player since 1995 and really impressed by the way you guys managed to transform the game while keeping the experience intact!Well done/MartinSent from my iPhoneOn Jun 11, 2023, at 4:45 AM, Patric Stout ***@***.***> wrote:﻿
Closed #10681 as not planned.
