### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Happpytrains** [OpenTTD/OpenTTD#10698]
### Version of OpenTTD

openttd 13.1

### Expected result

trains  service setting of

### Actual result

i got trains going to the deport to be service when i got the setings of

### Steps to reproduce

[happy.zip](https://github.com/OpenTTD/OpenTTD/files/11304134/happy.zip)

**Comment by PeterN** [comment]
![image](https://user-images.githubusercontent.com/639850/233850529-c9455279-8df4-4855-9543-cc24b9607e7e.png)

You have autoreplace enabled on some wagons, so the trains are going to depot to be autoreplaced.
