### ISSUE TITLE
[Bug]: Server does not apply the changes of openttd.cfg.

### ISSUE THREAD

**Issue by troilus** [OpenTTD/OpenTTD#10704]
### Version of OpenTTD

13.1 Centos7

### Expected result

1. Modifying the relevant content of openttd.cfg, such as mapsize or server name.
2. ./openttd -D -c ./openttd.cfg to strat the server
3. Go to servers.openttd.org, check the server information, the server name or mapsize should change.

### Actual result

The server name or mapsize dose not change.

### Steps to reproduce

1. Modifying the relevant content of openttd.cfg, such as mapsize or server name.
2. ./openttd -D -c ./openttd.cfg to strat the server
3. Go to servers.openttd.org, check the server information, the server name or mapsize should change.

**Comment by PeterN** [comment]
If you check the configuration are the changes still there?

When you exit the game it will overwrite the config, so may be replacing it back again.

**Comment by troilus** [comment]
> If you check the configuration are the changes still there?
> 
> When you exit the game it will overwrite the config, so may be replacing it back again.
> 
> EDIT: I assume running "./openttd.cfg" to start is a typo...?

Sorry it is ./openttd-D -c ./openttd.cfg

I tried again and yes the game will overwrite the config when I exit the game after editing the cfg file.

But I exit the game first, the edit the cfg and start the server, the server info still not change , and changes in cfg file still there, I exit and restart server, nothing change.

**Comment by PeterN** [comment]
If you join the server are the changes applied? It could just be that updating the server list takes a little time -- it is cached information.

**Comment by PeterN** [comment]
Those settings are no longer stored in openttd.cfg, they are in private.cfg instead.

**Comment by troilus** [comment]
> Those settings are no longer stored in openttd.cfg, they are in private.cfg instead.

Is there and information about private.cfg? Can I use settings by moving cfgs from openttd.cfg to private.cfg?

**Comment by TrueBrain** [comment]
If you start the game with for example `-c newfolder/openttd.cfg`, and close the game graceful (by exiting or typing `exit` in console), you will also see a `private.cfg` in `newfolder`. When you open that up, you can see what settings are stored there.

Does that give you enough information?
