### ISSUE TITLE
[Bug]: Android App Blackscreen

### ISSUE THREAD

**Issue by ClemontX** [OpenTTD/OpenTTD#10760]
### Version of OpenTTD

13.0.rev114 Android

### Expected result

App starts

### Actual result

Blackscreen on app lauch

### Steps to reproduce

1. Download App (not installed before, fresh)
2. Launch App

**Comment by PeterN** [comment]
Android version of OpenTTD is separate and not maintained by us. Please use their own tracker.

**Comment by 2TallTyler** [comment]
For reference, I believe this is the tracker for the current maintainers of the unofficial Android version: https://github.com/n-ice-community/openttd-android
