### ISSUE TITLE
[Bug]: Cannot clone a train

### ISSUE THREAD

**Issue by ottdfevr** [OpenTTD/OpenTTD#10819]
### Version of OpenTTD

20230513-master-ge1b653137f, Windows 10 (x64)

### Expected result

I wanted to clone a train.

### Actual result

Nothing happens.

### Steps to reproduce

1. Build a Train Depot.
2. Buy a train. (no specific composition)
3. (Try to) Clone a train. (with or without CTRL)
4. Nothing happens. (like if the clone button was imaginary)

**Comment by TrueBrain** [comment]
Thank you for this report! And yes, this is broken :)

To be a bit more exact, it is off-by-one. If you click on the "second" (imaginary) train, it will clone the first.

Similar problems exist when deleting a train. It deletes the wrong train :) (and selects the wrong on even).

**Comment by glx22** [comment]
Yup it clones the line before the clicked one
