### ISSUE TITLE
[Bug]: Cannot click on vehicles in depot window 

### ISSUE THREAD

**Issue by fmang** [OpenTTD/OpenTTD#10824]
### Version of OpenTTD

20230513-master-ge1b653137f, macOS 11.7.6

### Expected result

Clicking on a vehicle should open its viewport window.

### Actual result

Nothing. The click is ignored.

### Steps to reproduce

1. Start a new game.
2. Buy a road vehicle depot.
3. Open the depot window and buy a vehicle.
4. Close the vehicle window that automatically opens.
5. Click on the vehicle from the depot window.

**Comment by glx22** [comment]
Fixed in #10820.
