### ISSUE TITLE
[Bug]: Terrain raise/lower/level selection point is not drawn at 4x or 8x zoom out.

### ISSUE THREAD

**Issue by zephyris** [OpenTTD/OpenTTD#10838]
### Version of OpenTTD

openttd-20230515-master-g389b66bd16-windows-win64

### Expected result

The terrain raise/lower/level selection point (ie. sprite number 774) visible on the corner of the tiles to be modified should always be visible, irrespective of zoom level.

### Actual result

This sprite is drawn at normal zoom, 2x or 4x zoom in and 2x zoom out, but not at 4x or 8x zoom out. This is not base graphics set-dependent - the same behaviour happens with original windows, OpenGFX. Also occurs with custom GRF which provides a ZOOM_LEVEL_OUT_4X alternate sprite for sprite number 774.
![openttd_pointselectbug](https://github.com/OpenTTD/OpenTTD/assets/2762690/b76c8216-ffa3-4c06-9dba-3f38b6b960e1)

### Steps to reproduce

In any game or in the scenario editor just select a terrain edit tool and try zooming out.

**Comment by PeterN** [comment]
In terms of hysterical raisins, this is a carry-over from original TTD, but it should probably go.

**Comment by zephyris** [comment]
Looking at the code and fiddling with the sprite aligner it looks like it switches to drawing sprite number 4078 when zoomed out... But that sprite is so small that when downsampled it never appears. In the current code, it is the the only hard-coded zoom out-specific sprite, and the only place sprite 4078 is used. Perhaps a holdover from when zoom out was first implemented, if the selector didn't scale? Weird!

**Comment by zephyris** [comment]
The plot thickens... While the sprite is called `SPR_DOT_SMALL`:

sprites.h:
```c++
    static const SpriteID SPR_DOT_SMALL    = 4078;
```
... it's actually an 8x8px blank sprite. It's right next to a small dot sprite (number 4079) which might be a cause of confusion.

And, I missed that it is used in one additional place: The 'not button' in the small map.

smallmap_gui.cpp:
```c++
    NWidget(WWT_IMGBTN, COLOUR_BROWN, WID_SM_BLANK),
        SetDataTip(SPR_DOT_SMALL, STR_NULL), SetFill(1, 1),
```
![terraformbug](https://github.com/OpenTTD/OpenTTD/assets/2762690/60467f97-cd7a-4d1f-ad3a-3eb96838643b)

So, what's the bug? Should the smallmap not be using this sprite? Or should the terraforming indicator not use this sprite?
