### ISSUE TITLE
Licensing issue - GPL violation on Apple Store

### ISSUE THREAD

**Issue by profTwinglings** [OpenTTD/OpenTTD#10832]
### Version of OpenTTD

all

### Expected result

This code is stolen by " Yung-Chiang Tu"

https://apps.apple.com/us/app/openttd/id1585549844
and he puts ads on the app, while not providing the latest source or attribution.

GPLv2 clearly states that attribution and sharing code is mandatory.

### Actual result

x

### Steps to reproduce

x

**Comment by James103** [comment]
Did you report the offending app to Apple's app store moderation?

**Comment by andythenorth** [comment]
I have looked twice for a way to report this app, but didn't find an appropriate abuse email address.

**Comment by TrueBrain** [comment]
@orudge do you mind giving this a look? If there is nothing we can do about it, so be it. But if someone can do anything about it, it would be you :D Tnx!

**Comment by Notts90** [comment]
1. I’ve played the iOS version and there are no adverts.

2. Did you look or ask for the source code? You can request it from the author, I found their email on Reddit after a very quick Google.

**Comment by orudge** [comment]
"Reporting not available" when I try to report a problem with it, at least for "quality issue". Would need to look into how best to report this. They have a link to a web site with a "Source" description, but no actual links/downloads.

**Comment by pemensik** [comment]
Haven't tried the iOS version. But unless they disabled online chat in online games, the game is not really suitable for ages 4+ as is written on store page. You may want to report at least that to Apple.

**Comment by 2TallTyler** [comment]
It sounds like we don't have a way to resolve this right now, but we are aware of it -- and this is not a bug. 😉
