### ISSUE TITLE
[Bug]: Opening the town directory does not focus on the search box

### ISSUE THREAD

**Issue by btzy** [OpenTTD/OpenTTD#10886]
### Version of OpenTTD

13.1

### Expected result

The text box should get focus when the town directory window is opened.

### Actual result

The text box does not get focus.

### Steps to reproduce

1. Start a new game.
2. Click on the "Display town directory" button.
3. Start typing, and observe that it doesn't type into the textbox until you click on it.

________

So I'm not actually sure this would be considered a "bug", but it's more of a minor UI improvement that does not seem to be large enough to warrant its own thread on the forums.  With focus on the search box, you can still interact with all the buttons on the window.  However, the town directory is often used with the search box, since there is usually too many towns to easily find the town you are looking for.

**Comment by 2TallTyler** [comment]
#8908 added `f` as a hotkey to focus on the text filter edit box. It wasn't consistently added to new filters, though, and is missing from:

- Waypoints
- Industry directory
- Town directory

These should probably support the hotkey.

Whether or not the directory-type windows should get focus by default is another question. Maybe providing a hotkey and leaving it up to the player is best.
