### ISSUE TITLE
[Bug]: Multiplayer server listing missing servers

### ISSUE THREAD

**Issue by npabisz** [OpenTTD/OpenTTD#10887]
### Version of OpenTTD

13.1

### Expected result

The listing from https://servers.openttd.org/listing should be the same as in game listing.

### Actual result

There are many servers missing from the in game listing. Why?

![Screenshot_1257](https://github.com/OpenTTD/OpenTTD/assets/13676368/a43d73ab-90ae-4872-b241-ffe5815acd1f)
![Screenshot_1258](https://github.com/OpenTTD/OpenTTD/assets/13676368/8c71f87d-2675-4aca-93e4-98c30417bd17)

### Steps to reproduce

1. Go to https://servers.openttd.org/listing
2. Compare with in game multiplayer server list

**Comment by TrueBrain** [comment]
Both the in-game listing and the online server-listing shows all servers. Where they differ, is their sorting.

Online, we have no clue what GRFs your client has installed, so all servers are considered equal in those regards. In-game how-ever we know exactly what GRFs your client has, and whether you can join a server or not. So network servers that run the same versions as you and have the same GRFs, are marked with a green dot. You can easily join them without any further effort.

If you do not have the required GRFs however, they are marked with a yellow dot. Indicating you need to download some files, which might or might not be available via the online content service. And we also have a red dot, indicating your client is running another OpenTTD version all together.

In-game listing is sorted based on those dots first. And this of course is impossible to do online. So what you are seeing are not missing servers .. they are there, just a bit lower in the listing.

As for the other differences between the two screenshots, they seem to list servers on different moments in time. Which is clear by the difference in amount of players online.
If I look at the here and now, I see that both listings are identical .. just with a different sorting :)

Hope this clears things up for you a bit!

**Comment by npabisz** [comment]
@TrueBrain sure I did screen with different sorting, but there was few missing 100%. Even my dedicated server which was online whole time and hosted few different which were visible. I restarted the one which wasn't visible and guess what it appeared on the list. Weird and definitely there is something wrong.

**Comment by TrueBrain** [comment]
I am not sure I really follow what you say here, you are going a bit too quick with too little detail. So let's see if I get all the pieces of information right (and correct me if I am wrong, ofc):

What I forgot to mention in my earlier reply, that the server-listing online is cached for 5 minutes. So it is always a bit out-of-date compared to the in-game listing. But do you see any server in-game now that isn't listed? Or with the information above you agree with me that they are in fact in sync?

The other thing I think you are trying to say, is that one of your own servers wasn't showing up in either list, but was after a restart? As that would be another bug than your originally described; fine ofc, but it is important that we understand what you are running into :)

If I understood this all correctly, I suggest we close this ticket with "work as expected", and please open another ticket that one of your servers wasn't showing up. Ideally with logs with `-dnet=6` around the time it happens/happened, as that gives us a bit of an idea what the server thought the state was, and we can cross-reference that with the backend.

If I did not understand it correctly, please explain a bit more what you see and what you expect. Tnx a bunch!

**Comment by npabisz** [comment]
@TrueBrain yes, one of my games which are hosted on dedicated server wasn't showing up on in-game listing, but was showing up on website. Unfortunately I don't have logs anymore.

**Comment by TrueBrain** [comment]
Sadly, without logs or having a server in a perceived broken state, there is very little we can do. Code-wise, I can find no reason why the website would report anything else than in-game, except for the caching on the website. We are aware of a bug where if a server quickly disconnects/reconnects (due to network issues) it can be invisible, but that will always be invisible both in-game and on the website.

For now, I will close up this ticket. If it ever happens again, please reopen the ticket without fixing your server, or make sure to capture logs from the server. Then we can investigate further. But as it stands, there is nothing we can do. Sorry!

**Comment by npabisz** [comment]
@TrueBrain I have some server running on 12.1 for few weeks and it's not visible on listing nor in game

```ini
[network]
server_name=TEST GAME #1
server_bind_ip=188.116.40.254
server_port=3979
```

Some logs

```
dbg: [net] [admin] Rcon command from 'YorkBot' (1): say "Restarting server due to inactivity"
dbg: [net] [admin] Rcon command from 'YorkBot' (1): say "Next game starts in 30s"
dbg: [net] [admin] Rcon command from 'YorkBot' (1): say "Next game starts in 20s"
dbg: [net] [admin] Rcon command from 'YorkBot' (1): say "Next game starts in 10s"
dbg: [net] Sending server update to Game Coordinator
dbg: [net] [admin] Rcon command from 'YorkBot' (1): set generation_seed 1054146836
dbg: [net] [admin] Rcon command from 'YorkBot' (1): newgame 1054146836
dbg: [net] [server] Closed listeners
dbg: [net] [admin] Closed listeners
dbg: [net] Closed UDP listeners
dbg: [net] Initializing UDP listeners
dbg: [net] Closed UDP listeners
dbg: [net] Initializing UDP listeners
dbg: [net] Starting listeners for clients
dbg: [net] Listening on 188.116.40.254:3979 (IPv4)
dbg: [net] Starting listeners for admins
dbg: [net] Listening on 188.116.40.254:3977 (IPv4)
dbg: [net] Starting listeners for incoming server queries
dbg: [net] Listening on 188.116.40.254:3979 (IPv4)
dbg: [net] Generating map, please wait...
dbg: [net] Map generation percentage complete: 5
dbg: [net] Map generation percentage complete: 10
dbg: [net] Map generation percentage complete: 15
dbg: [net] Map generation percentage complete: 20
dbg: [net] Map generation percentage complete: 25
dbg: [net] Map generation percentage complete: 30
dbg: [net] Map generation percentage complete: 35
dbg: [net] Map generation percentage complete: 40
dbg: [net] Map generation percentage complete: 45
dbg: [net] Map generation percentage complete: 50
dbg: [net] Map generation percentage complete: 55
dbg: [net] Map generation percentage complete: 60
dbg: [net] Map generation percentage complete: 80
dbg: [net] Map generation percentage complete: 85
dbg: [net] Map generation percentage complete: 90
dbg: [script] english:533: error: Undefined command 'CARGO'
dbg: [script] english:533: error: Undefined command 'CARGO'
dbg: [script] english:123: error: Undefined command 'CARGO'
dbg: [script] english:123: error: Undefined command 'CARGO'
dbg: [net] Map generation percentage complete: 95
dbg: [net] Map generated, starting game
dbg: [net] coordinator.openttd.org:3976 resolved in:
dbg: [net] - 54.217.16.91:3976 (IPv4)
dbg: [net] - 34.248.138.28:3976 (IPv4)
dbg: [net] - [2a05:d018:5fd:4604:75b9::1]:3976 (IPv6)
dbg: [net] - [2a05:d018:5fd:4605:5ba::1]:3976 (IPv6)
dbg: [net] Attempting to connect to 54.217.16.91:3976 (IPv4)
dbg: [net] Connected to coordinator.openttd.org:3976
dbg: [net] - using 54.217.16.91:3976 (IPv4)
dbg: [net] stun.openttd.org:3975 resolved in:
dbg: [net] stun.openttd.org:3975 resolved in:
dbg: [net] - 54.217.16.91:3975 (IPv4)
dbg: [net] - 34.248.138.28:3975 (IPv4)
dbg: [net] - [2a05:d018:5fd:4605:5ba::1]:3975 (IPv6)
dbg: [net] - [2a05:d018:5fd:4604:75b9::1]:3975 (IPv6)
dbg: [net] Attempting to connect to [2a05:d018:5fd:4605:5ba::1]:3975 (IPv6)
dbg: [net] Could not connect to [2a05:d018:5fd:4605:5ba::1]:3975 (IPv6): Network is unreachable
dbg: [net] Attempting to connect to 54.217.16.91:3975 (IPv4)
dbg: [net] Attempting to connect to [2a05:d018:5fd:4604:75b9::1]:3975 (IPv6)
dbg: [net] Could not connect to [2a05:d018:5fd:4604:75b9::1]:3975 (IPv6): Network is unreachable
dbg: [net] Connected to stun.openttd.org:3975
dbg: [net] - using 54.217.16.91:3975 (IPv4)
dbg: [net] [server] Client connected from 34.248.138.28 on frame 30
dbg: [net] ----------------------------------------
dbg: [net] Your server is now registered with the Game Coordinator:
dbg: [net]   Game type:       Public
dbg: [net]   Connection type: Public
dbg: [net]   Invite code:     +NJMMdVM
dbg: [net] ----------------------------------------
dbg: [net] [server] Client #7577 closed connection
dbg: [net] Sending server update to Game Coordinator
```

there is another, but this time cannot see the game coordinator log

```
dbg: [net] [admin] Rcon command from 'YorkBot' (1): say "Restarting server due to inactivity"
dbg: [net] [admin] Rcon command from 'YorkBot' (1): say "Next game starts in 30s"
dbg: [net] [admin] Rcon command from 'YorkBot' (1): say "Next game starts in 20s"
dbg: [net] [admin] Rcon command from 'YorkBot' (1): say "Next game starts in 10s"
dbg: [net] [admin] Rcon command from 'YorkBot' (1): set generation_seed 238935094
dbg: [net] [admin] Rcon command from 'YorkBot' (1): newgame 238935094
dbg: [net] [server] Closed listeners
dbg: [net] [admin] Closed listeners
dbg: [net] Closed UDP listeners
dbg: [net] Initializing UDP listeners
dbg: [net] Closed UDP listeners
dbg: [net] Initializing UDP listeners
dbg: [net] Starting listeners for clients
dbg: [net] Listening on 188.116.40.254:3979 (IPv4)
dbg: [net] Starting listeners for admins
dbg: [net] Listening on 188.116.40.254:3977 (IPv4)
dbg: [net] Starting listeners for incoming server queries
dbg: [net] Listening on 188.116.40.254:3979 (IPv4)
dbg: [net] Generating map, please wait...
dbg: [net] Map generation percentage complete: 5
dbg: [net] Map generation percentage complete: 10
dbg: [net] Map generation percentage complete: 15
dbg: [net] Map generation percentage complete: 20
dbg: [net] Map generation percentage complete: 25
dbg: [net] Map generation percentage complete: 30
dbg: [net] Map generation percentage complete: 35
dbg: [net] Map generation percentage complete: 40
dbg: [net] Map generation percentage complete: 45
dbg: [net] Map generation percentage complete: 50
dbg: [net] Map generation percentage complete: 55
dbg: [net] Map generation percentage complete: 60
dbg: [net] Map generation percentage complete: 80
dbg: [net] Map generation percentage complete: 85
dbg: [net] Map generation percentage complete: 90
dbg: [script] english:533: error: Undefined command 'CARGO'
dbg: [script] english:533: error: Undefined command 'CARGO'
dbg: [script] english:123: error: Undefined command 'CARGO'
dbg: [script] english:123: error: Undefined command 'CARGO'
dbg: [net] Map generation percentage complete: 95
dbg: [net] Map generated, starting game
dbg: [net] [admin] Rcon command from 'YorkBot' (1): say "Restarting server due to inactivity"
```

and here something about the invitation code

```
dbg: [net] Sending server update to Game Coordinator
dbg: [net] Sending server update to Game Coordinator
dbg: [net] Connection with Game Coordinator lost; reconnecting...
dbg: [net] coordinator.openttd.org:3976 resolved in:
dbg: [net] - 54.217.16.91:3976 (IPv4)
dbg: [net] - 34.248.138.28:3976 (IPv4)
dbg: [net] - [2a05:d018:5fd:4604:75b9::1]:3976 (IPv6)
dbg: [net] - [2a05:d018:5fd:4605:5ba::1]:3976 (IPv6)
dbg: [net] Attempting to connect to 54.217.16.91:3976 (IPv4)
dbg: [net] Connected to coordinator.openttd.org:3976
dbg: [net] - using 54.217.16.91:3976 (IPv4)
dbg: [net] stun.openttd.org:3975 resolved in:
dbg: [net] stun.openttd.org:3975 resolved in:
dbg: [net] - 34.248.138.28:3975 (IPv4)
dbg: [net] - 54.217.16.91:3975 (IPv4)
dbg: [net] - [2a05:d018:5fd:4604:75b9::1]:3975 (IPv6)
dbg: [net] - [2a05:d018:5fd:4605:5ba::1]:3975 (IPv6)
dbg: [net] Attempting to connect to [2a05:d018:5fd:4604:75b9::1]:3975 (IPv6)
dbg: [net] Could not connect to [2a05:d018:5fd:4604:75b9::1]:3975 (IPv6): Network is unreachable
dbg: [net] Attempting to connect to 34.248.138.28:3975 (IPv4)
dbg: [net] Attempting to connect to [2a05:d018:5fd:4605:5ba::1]:3975 (IPv6)
dbg: [net] Could not connect to [2a05:d018:5fd:4605:5ba::1]:3975 (IPv6): Network is unreachable
dbg: [net] Connected to stun.openttd.org:3975
dbg: [net] - using 34.248.138.28:3975 (IPv4)
dbg: [net] [server] Client connected from 34.248.138.28 on frame 26201
dbg: [net] ----------------------------------------
dbg: [net] Your server is now registered with the Game Coordinator:
dbg: [net]   Game type:       Public
dbg: [net]   Connection type: Public
dbg: [net]   Invite code:     +NJMMdVM
dbg: [net] ----------------------------------------
dbg: [net] [server] Client #7715 closed connection
dbg: [net] Sending server update to Game Coordinator
Another server with the same invite-code registered itself. Switching to "local" game-type.
```
