### ISSUE TITLE
[Bug]: Cannot destroy train building station

### ISSUE THREAD

**Issue by askondro** [OpenTTD/OpenTTD#10882]
### Version of OpenTTD

13.1

### Expected result

Trying to destroy a railway train depot.

### Actual result

Does not work. Nothing happens.

### Steps to reproduce

Build a train depot. Try to delete. But it does not work.
![image](https://github.com/OpenTTD/OpenTTD/assets/670935/a878e548-d7de-4bf7-9ca9-7733120fe64e)

**Comment by glx22** [comment]
Please attach the savegame.

**Comment by askondro** [comment]
Sorry, there was a train in the station. that is why i could not delete the station.
Closing it now.
