### ISSUE TITLE
[Bug]: Strings for extended station objects not showing in-game

### ISSUE THREAD

**Issue by trolleytrev** [OpenTTD/OpenTTD#10885]
### Version of OpenTTD

20230527-master-g90fdf17e39, Win 8.1

### Expected result

Class names and station object names appearing as normal for extended station objects in single GRF

### Actual result

For all station objects beyond the old limit of 255 per GRF, the description string reverts to "Default Station" and class strings defined by a station object with ID > 255 are blank.

Not 100% sure if this is an OpenTTD issue or an issue with the updated nml compiler (v0.7.3) that can do > 255 station objects.

![Unnamed, 7th Jan 1950](https://github.com/OpenTTD/OpenTTD/assets/19632038/4ee3067c-b7d8-42e8-aa36-7b464ccbd301)
![Unnamed, 14th Jan 1950](https://github.com/OpenTTD/OpenTTD/assets/19632038/793facbd-aefb-4de4-97e9-6886c755b835)
![Unnamed, 19th Jan 1950](https://github.com/OpenTTD/OpenTTD/assets/19632038/66671e4d-3b86-4b05-ab75-8fb44ec93682)

### Steps to reproduce

Start a game with a newGRF that makes use of the extended station object limits. I am currently making one, which is how I discovered the problem!

**Comment by glx22** [comment]
OpenTTD introduced a mechanism for station names (prop 1C) and station class names (prop 1D) to handle more than 256 (in https://github.com/OpenTTD/OpenTTD/commit/bc7dfd7b46c0184dc4b2cc376556702ac0ac1019) but it's not yet mentioned in the specs, nor implemented in nml.

**Comment by trolleytrev** [comment]
Ok. So the latest nml (0.7.3) will allow >255 stations objects now, but hasn't implemented the extra strings yet, is that what you're saying? If so, I will wait until the next nml release which will hopefully implement this, thus solving the issue. Thank you!

**Comment by LordAro** [comment]
This was completed in https://github.com/OpenTTD/nml/pull/293 and released with nml 0.7.4

**Comment by glx22** [comment]
Actually it's in nml 0.7.4, but it's broken, the fix will be in next nml release.
