### ISSUE TITLE
[Crash]: Building a NewGRF object causes a crash

### ISSUE THREAD

**Issue by FilmBoy84** [OpenTTD/OpenTTD#10880]
### Version of OpenTTD

20230525-master-gdb3b086a52 , Windows 10

### Steps to reproduce

Load the crash save
Attempt to build a NewGRF Object (I selected something from the Sawmill category with this crash)
Game will crash on select and/or placement

### Upload crash files

[OpenTTD.zip](https://github.com/OpenTTD/OpenTTD/files/11579683/OpenTTD.zip)

Config File also included for GRF parameters

![crash20230526201206](https://github.com/OpenTTD/OpenTTD/assets/33913088/e487f9c7-a957-45bc-bcd0-fa3e51e08a0a)

**Comment by PeterN** [comment]
This is... duh duh duhhhh, scrollbar related... looking at it!

**Comment by FilmBoy84** [comment]
Thanks for quick response
Sorry for throwing two issues at you today (the Bananas one via discord and this one)
Let me know if you need any more data :beers:
