### ISSUE TITLE
[Bug]: Placing factories by Game Script

### ISSUE THREAD

**Issue by npabisz** [OpenTTD/OpenTTD#10897]
### Version of OpenTTD

13.1

### Expected result

I'm able to place factory through GS wherever I want (as long as it is one per town).

### Actual result

Climates like sub-tropical or arctic has limitation on some factories which cannot be placed in specific areas, eg. snow, desert or Oil Factory which cannot be placed if not close to map edge. 

I think this should be not applicable to Game Scripts which should have free hand on such things. Right now any climate, but temperate is useless for City Builder game modes which would require different types of cargo delivered to town.

### Steps to reproduce

1. Pick sub-tropical climate
2. Fund Factory by GS on desert

**Comment by Eddi-z** [comment]
These placement restrictions are traditionally controlled by NewGRFs, it would be a bit weird to interfere in their territory like this.
