### ISSUE TITLE
[Bug]: Train name wrongly marked as non-unique

### ISSUE THREAD

**Issue by merni-ns** [OpenTTD/OpenTTD#10975]
### Version of OpenTTD

13.1, Windows 11

### Expected result

"Name must be unique" error only occurs when there is a train existing with the same name.

### Actual result

"Name must be unique" error occurs even when the train with the same name does not exist anymore. This seemingly continues even when fast-forwarded for a long time.

### Steps to reproduce

1. Buy two trains and name them say "A" and "B"
2. Drag the train "A" and couple it on train "B". Now there is only one train, "B".
3. Buy another train.
4. Try to set the name of this new train as "A".
5. The message "Can't name train... Name must be unique" is displayed.

**Comment by krysclarke** [comment]
Confirmed with 13.0 on Debian Linux.
