### ISSUE TITLE
[Bug]: Openttd's admin port sends Update event first after creation of the company if it posses the same ID as deleted company

### ISSUE THREAD

**Issue by shoter** [OpenTTD/OpenTTD#10983]
### Version of OpenTTD

13.2 (also happened in previous version but I do not remember my previous version :( )

### Expected result

I expect that after creating company OpenTTD AdminPort's is going to send `ADMIN_PACKET_SERVER_COMPANY_INFO` first and `ADMIN_PACKET_SERVER_COMPANY_UPDATE` afterwards to inform AdminPort's client about updates.

### Actual result

Openttd is sending `ADMIN_PACKET_SERVER_COMPANY_UPDATE` before `ADMIN_PACKET_SERVER_COMPANY_INFO` if you create company with Id that was already used in the past by removed company. 

If I create company which Id was not used before then `ADMIN_PACKET_SERVER_COMPANY_INFO` is send first.

I have a feeling that not all information about company are removed from memory after company removal.

### Steps to reproduce
1. Send a ADMIN_PACKET_ADMIN_UPDATE_FREQUENCY message with `ADMIN_UPDATE_COMPANY_INFO` having value `ADMIN_FREQUENCY_AUTOMATIC`
2. Create a Company. Let's assume it's id is `1`
3. Execute `reset_company 1`
4. Create a company again
5. `ADMIN_PACKET_SERVER_COMPANY_UPDATE` is send first

**Comment by shoter** [comment]
The reason is within `src\network\network_server.cpp` on line `2088`. While creating new company a password is cleared for this company and update is being sent because of that. It happens before informing clients about new company:
```
	NetworkServerUpdateCompanyPassworded(c->index, false); // <--- culprit
	
	// (some code here ...)
	
	/* Announce new company on network. */
	NetworkAdminCompanyInfo(c, true);
```

**Comment by TrueBrain** [comment]
As you found the location of the issue and everything, do you feel up for making a Pull Request to address this issue? :)

**Comment by shoter** [comment]
I can try to do that. I did not compile OpenTTD in a long time though, therefore I will need to check it out :-). Probably tomorrow I will start process of figuring out how to compile it :P
