### ISSUE TITLE
[Bug]: Clicking the land info button in the main toolbar no longer activates the land info tool without using the drop down

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#10987]
### Version of OpenTTD

master

### Expected result

Clicking the land info button in the main toolbar activates the land info tool without using the drop down

### Actual result

Clicking the land info button in the main toolbar no longer activates the land info tool without using the drop down

### Steps to reproduce

Clicking the land info button in the main toolbar

**Comment by glx22** [comment]
Seems to happen in 13.3 too (it's fine in 13.1)

**Comment by PeterN** [comment]
Hmm, it calls SetObjectToPlace, and then ResetObjectToPlace straight after.
