### ISSUE TITLE
[Bug]: Fullscreen window is broken since 13.2

### ISSUE THREAD

**Issue by margoulin54** [OpenTTD/OpenTTD#10989]
### Version of OpenTTD

13.2 - W11 & W10

### Expected result

The game works as intended.

### Actual result

Enabling fullscreen will prevent the mouse from going too high (mouse blocked before the edge of the screen). Putting the mouse at the bottom of the screen will make reappear the standard windows mouse and clicking will take the user back to desktop.

Screenshot : from my perspective, the game is in fullscreen but when I press prntscrn it shows that the game isn't
![fullscreen](https://github.com/OpenTTD/OpenTTD/assets/136242659/6dd5dee8-7c27-4d6a-9c6e-f5d6aa2341d2)

### Steps to reproduce

1. Set the game in fullscreen
2. Works on the main menu as well as in-game

**Comment by TrueBrain** [comment]
Fixed in #10985 and 13.2.1 :)
