### ISSUE TITLE
[Bug]: Canals and rivers can be built in the sea

### ISSUE THREAD

**Issue by Kuhnovic** [OpenTTD/OpenTTD#10997]
### Version of OpenTTD

13.1

### Expected result

IMO building a canal in the sea makes no sense and should not be possible. Same for rivers in the scenario editor.

I know ships can have different canal/river vs sea speeds, though I can imagine that most of the times the canal speed will be lower than the sea speed. And if it's the other way, then I would consider building canals in the sea cheating.

### Actual result

You can just build canals in the sea, and you don't get an error message.

![image](https://github.com/OpenTTD/OpenTTD/assets/68320206/d1032b19-352a-45b7-bce5-2f6fa93f7461)

It's a bit hard to see, so I've selected the tiles with the Flatten Land tool here

### Steps to reproduce

1. Generate a map with some water
2. Build a canal somewhere in the sea
-------------------
1. Open the scenario editor
2. Open a scenario with a sea
3. Build a river somewhere in the sea

**Comment by andythenorth** [comment]
This one is use for a range of classic hacks, including airports on water, and other stupid tricks. 😉

**Comment by PeterN** [comment]
Yes, building canals at sea level is commonly used to prevent flooding of land at height level 0.

**Comment by 2TallTyler** [comment]
Also to claim ocean tiles so a competitor can't terraform it into land and block your ships. 

Intended, not a bug, but thanks for the report! 😄
