### ISSUE TITLE
[Crash]: Crash after sorting trains by "Profit last year"

### ISSUE THREAD

**Issue by Leithirn** [OpenTTD/OpenTTD#11064]
### Version of OpenTTD

13.3

### Steps to reproduce

Loaded a saved game, sorted trains by "Profit last year", clicked on first train, then tried to open Maglev Construction.
I am running OpenTTD on HP Omen Laptop, program itself is displayed on secondary monitor (Dell, connected via HDMI) running in window mode (not full screen).

### Upload crash files

[OpenTTD.zip](https://github.com/OpenTTD/OpenTTD/files/11856146/OpenTTD.zip)

**Comment by glx22** [comment]
From the screenshot it's most likely a duplicate of #11043

**Comment by 2TallTyler** [comment]
Closing this as a duplicate of #11043, which is fixed in 13.4. If you upgrade to 13.4 and continue to experience crashes, please open a new ticket for them. Thanks! 😃
