### ISSUE TITLE
[Bug]: Starting new game with 0 minutes between competitor starts causes some inconsistencies.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#11067]
### Version of OpenTTD

78c9446aef on Windows 10, 64-bit

### Expected result

When "Interval between starting of competitors" is greater than 0,
* Starting a new game puts the first human company in slot 0 (`(Company 1)`), as should always be case.
* When AIs start, they start in order according to the AI configuration. The first competitor should use the first AI slot below "Human player", the second competitor should use the second AI slot below the first, etc.

Both of these should still hold when "Interval between starting of competitors" is 0.

The following screenshots were taken from a scenario where 2 AIs by the name of "IdleMoreMore" are scheduled to start.

Expected behavior (currently occurs when interval > 0):
![image](https://github.com/OpenTTD/OpenTTD/assets/37945304/6913f9db-c25f-495d-87df-a538511e24fe)

### Actual result

When "Interval between starting of competitors" is 0,
* Starting a new game puts the first human company in slot N (`(Company N+1)`), where N is the maximum number of AI competitors to automatically start. For example, with 0 interval and 2 "Maximum no. competitors", the human company is in slot 2 (`(Company 3)`).
* The first AI is started as a random AI.
* The second AI uses the AI config normally used for the first AI to start in a regular game.
* The third AI uses the AI config normally used for the second AI in a regular game, etc.

Actual behavior (when interval = 0) - notice the first AI is randomly selected:
![image](https://github.com/OpenTTD/OpenTTD/assets/37945304/556395ba-7b70-499b-b1a8-d4e3692bbabb)

### Steps to reproduce

1. In the AI config window, set "Maximum no. competitors" greater than 0 and "Interval between starting of competitors" equal to 0.
2. Start a new game.
3. Open the company dropdown (or company info, finances window for your company).
4. Notice the first human company is put in a slot other than the slot labelled "Company 1".

**Comment by krysclarke** [comment]
Unable to replicate on 13.0 on Debian.

Tried with 2, as well as 4, random AI's (only have AAAHogEx downloaded).

**Comment by TrueBrain** [comment]
Yeah, this is a bug in the nighlty. I wanted to spice up how AIs worked a bit :P

(Joking ofc, this behavior is not intentional :) )
