### ISSUE TITLE
[Bug]: Raw string in game script

### ISSUE THREAD

**Issue by npabisz** [OpenTTD/OpenTTD#11062]
### Version of OpenTTD

13.3

### Expected result

Raw string is printed.

### Actual result

Not sure what I'm missing here, let's say in my game script I have something like this:

```
GSGoal.QuestionClient(0, clientId, GSText(GSText.STR_WELCOME, "Johnny"), GSGoal.QT_WARNING, GSGoal.BUTTON_START);
```

and in `lang/english.txt`:

```
STR_WELCOME: Welcome {RAW_STRING}
```

I'm only getting "Welcome" instead of "Welcome Johnny". What I'm missing here?

### Steps to reproduce

1. Add translation with RAW_STRING
2. Translate with string variable

**Comment by glx22** [comment]
`{RAW_STRING}` is explicitly disabled because incorrect use can crash OpenTTD.
But this issue is fixed in nightlies with the introduction of strict string parameter validation for GSText.

**Comment by npabisz** [comment]
@glx22 thought this was released already?

**Comment by glx22** [comment]
It will be in openttd 14
