### ISSUE TITLE
[Bug]: Base sound selection disabled

### ISSUE THREAD

**Issue by fkopp81** [OpenTTD/OpenTTD#11087]
### Version of OpenTTD

1.13.0, Windows 11

### Expected result

I can select an installed base sound set from the game menu

### Actual result

All base sound sets except for "NoSound" are disabled.

![image](https://github.com/OpenTTD/OpenTTD/assets/33949825/1f9a187a-96a6-43b6-988b-e688e8b8f80f)

### Steps to reproduce

1. Install from installer `openttd-13.3-windows-win64` on Windows 11
2. Download OpenSFX through "Check Online Content" in the main menu
3. Start a new game
4. Click on the gear in the top bar
5. Open the drop down under "Base sound sets"

**Comment by PeterN** [comment]
You can only change the base sound set from the main menu, not when in game.

**Comment by LordAro** [comment]
One could argue that the whole drop-down should be disabled, with an appropriate tooltip

**Comment by fkopp81** [comment]
That resolves my issue. How about removing the section from the in-game options then? It doesn't appear to be useful there.
