### ISSUE TITLE
[Bug]: In the high score table pressing the window X to exit does not work

### ISSUE THREAD

**Issue by zephyris** [OpenTTD/OpenTTD#11096]
### Version of OpenTTD

20230630-master-f082c47a4f9

### Expected result

When you click the window close/`X` button OpenTTD should _always_ show the "Exit / Are you sure you want to exit OpenTTD?" dialog. This should include the endgame news articles and high score views.

### Actual result

Clicking the window close/`X` button when in the endgame full screen special views - ie. the newspaper/magazine and highscore views - does nothing.  The same happens with `Alt+F4`.

On exiting the highscore view the "Exit / Are you sure you want to exit OpenTTD?" window is visible, so presumably just not being drawn over the newspaper/magazine and highscore special sprites.

### Steps to reproduce

Start a new game in 2051 and fast forward for a minute or so. Wait for the endgame newspaper to be displayed and try exiting the game through window controls...

**Comment by glx22** [comment]
Probably something to do with `GetWindowZPriority()`
