### ISSUE TITLE
[Bug]: There is no way to autofill signals, even with a straight section of track, in the AI API

### ISSUE THREAD

**Issue by btzy** [OpenTTD/OpenTTD#11099]
### Version of OpenTTD

13.1, Win 10

### Expected result

Human players can drag the signal tool over a straight section of track to place signals on the entire section (with pre-chosen spacing).  They can also hold down Ctrl to place signals until the next junction.

Both humans and AIs can build a straight section of track in a single command.  For AIs this is the [AIRail::BuildRail](https://docs.openttd.org/ai-api/classAIRail.html#a4553fc21ff34a7e6ffda9998301bcebf) command.

As building signals are almost as important as building tracks, and we already have a way to build a straight section of track in the AI API, it is expected that we should have something similar for building signals too.

### Actual result

There is no such function in the AI API, so AIs need to build signals individually, despite being able to build arbitrarily-long straight sections of track in a single command.

### Steps to reproduce

Look at the [AIRail](https://docs.openttd.org/ai-api/classAIRail.html) API reference and observe that no such function exists.

**Comment by 2TallTyler** [comment]
I don't think this is a bug, but a feature request. An AI can use its own algorithm to place signals on a segment of track. I'd be happy to review a PR giving AIs access to this command, but I don't think the feature request belongs in the issue tracker.

**Comment by nielsmh** [comment]
The actual issue here might be that it's an instance where a player can perform a large-area action in a single command, while an AI would need to perform multiple commands, of which it can only perform a single command per tick.
