### ISSUE TITLE
Land info build date is also renovation date.

### ISSUE THREAD

**Issue by Gadg8eer** [OpenTTD/OpenTTD#11123]
## Motivation / Problem
_Originally posted by @DorpsGek in https://github.com/OpenTTD/OpenTTD/issues/4415#issuecomment-379443968_

> We could ofcourse opt to be obnoxiously specific about what the date means: "Date at which the last construction or rebuilt at this station took place". But that bloats the interface for no good reason.
> 
> We actually need to update the build date as it's used by NewGRFs and TTDPatch/OpenTTD have behaved for a decade like this, thus changing it would break quite a few NewGRFs. Even then it would be wrong given the former example.
> 

_Originally posted by me here_
> Suggestion for "unfixable" station date "issue"

>How about "Last build/renovation date" or even "Build/renovation date"? Shorter, just as accurate and not that hard to implement, unless I'm mistaken?
> I get this is an old and unjustified "issue", feel free to close this immediately if the suggestion isn't useful.

_**When a station layout is modified in any way, the "Built: YYYY" section of the station's land info is also the renovation date. While fixing it properly would not be trivial, I propose a simpler short-term solution.**_

## Description
Just change the basic string from "Built" to "Built/last renovated" or possibly "Most recent construction". 2TallTyler suggested "Built/renovated" to be as short as possible.

I added a minor change to the language file. Apparently I forgot to submit it.

## Limitations
A more long-term solution is to record the original construction date and then also record the most recent renovation, but nothing in-between (it doesn't seem like anyone needs a history of the whole station).

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

**Comment by 2TallTyler** [comment]
Sure, feel free to make a PR with your suggested change. It would be this line in `english.txt`: https://github.com/OpenTTD/OpenTTD/blob/master/src/lang/english.txt#L2970

I am going to close this issue, as the bug tracker isn't really the place for suggestions; it gets cluttered way too quickly if we do that. 😄 

Side note: I saw your translator request for en_US. I don't have the permissions to handle your request, but please don't try to fix this issue by changing a single translation — it needs to be done in `english.txt` and then propagated down to translations. 😃

**Comment by ldpl** [comment]
Part of the problem also is that station build date is sometimes more useful than modification date.
