### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by ghost** [OpenTTD/OpenTTD#11146]
### Version of OpenTTD

1.13.3, Windows 11

### Steps to reproduce

Just Playing Till May 31st, 2034. Then when auto saving the game crash. I have some NewGRF installed

### Upload crash files

*** OpenTTD Crash Report ***

Crash at: 2023-07-18 04:57:11 (UTC)
In game date: 2034-06-01 (0)

Crash reason:
 Exception: C0000005
 Location:  00007FF79FEAFAA4
 Message:   <none>

OpenTTD version:
 Version:    13.3 (0)
 NewGRF ver: 1d386d64
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: Jun 11 2023 16:45:39

Registers:
 RAX: 0000017437C6FD10 RBX: 00000174262F4220 RCX: 61645F7472617473 RDX: 0000000000000004
 RSI: 0000000000000002 RDI: 0000000000000002 RBP: 0000000000000000 RSP: 00000024655FF298
 R8:  0000000000000002 R9:  0000000000000025 R10: 00007FF7A023C9F8 R11: 000000000000008F
 R12: 0000000000000010 R13: 00007FF7A03F6960 R14: 0000000000000000 R15: 0000000000000001
 RIP: 00007FF79FEAFAA4 EFLAGS: 00010246

 Bytes at instruction pointer:
 48 85 91 78 1E 00 00 74 03 B0 01 C3 32 C0 C3 CC CC CC CC CC CC CC CC CC

Stack trace:
 9FEAFB08 00007FF7 00000000 00000000 A0026700 00007FF7 02838870 00000174
 02838820 00000174 00000001 00000024 9FEBF2B0 00007FF7 000002F7 00000174
 9FFBCC3F 00007FF7 00000000 00000000 00000000 00000000 02839D80 00000174
 00000013 00000018 00000015 00000000 9FFBBB0F 00007FF7 262F4220 00000174
 00000000 00000000 0000055A 00000000 00000000 00000000 00000015 00000000
 9FFBD1C7 00007FF7 262F4220 00000174 00000002 00000000 00000000 00000174
 00000000 00007FF7 000002FD 00000024 A002AF69 00007FF7 00000000 00000000
 A002C76A 00007FF7 26AE1BA0 00000174 A0026700 00007FF7 000000EB 00000000
 49BC9040 00000174 26433450 00000174 9FCF54E7 00007FF7 26AE1BA0 00000174
 00000000 00000000 49BC9000 00000174 02839820 00000174 02839801 00000174
 A00263FC 00007FF7 26433450 00000174 A002B386 00007FF7 0000055A 00000025
 00000010 00000000 26433450 00000174 00000000 00000000 26433450 00000174
 A002CE70 00007FF7 02839870 00000174 26433450 00000174 00000000 00000000
 00000000 00000174 000002FD 00000000 000000EB 00007FF7 49BC9000 00000174
 3AB91750 00000174 473A2DE0 00000174 A002D9A4 00007FF7 26433450 00000174
 00000000 00000000 0000000A 00000000 473A2DE0 00000174 A1CD1D20 00007FF7
 00000000 00000000 A1C97DD0 00007FF7 9FE8A3C2 00007FF7 26433450 00000174
 26433450 00000174 000002BA 00000000 A0116FBF 00007FF7 00000000 00000000
 000000D8 00000000 A039B860 00007FF7 0000000A 00000000 000002BA 00000000
 9FE8B0AE 00007FF7 26433450 00000174 00000010 00000000 473A2DE0 00000174
 00000012 00000000 473A2DE0 00000174 9FE8B475 00007FF7 26433450 00000174
 00000006 00000000 473A17E0 00000174 75600000 00000174 00000006 00000000
 9FE8B50C 00007FF7 473A1490 00000174 00000000 00000000 00000006 00000000
 A01173FC 00007FF7 00000004 00000000 9FE8B6BC 00007FF7 00000004 00000000

Operating system:
 Name:     Windows
 Release:  10.0.22000 ()
 Compiler: MSVC 1935

Configuration:
 Blitter:      40bpp-anim
 Graphics set: zBase (5588)
 Language:     C:\Program Files (x86)\Steam2\steamapps\common\OpenTTD\lang\english_US.lng
 Music driver: dmusic
 Music set:    OpenMSX (7761)
 Network:      no
 Sound driver: xaudio2
 Sound set:    OpenSFX (7974)
 Video driver: win32-opengl (Intel(R) UHD Graphics, 4.5.0 - Build 30.0.101.1371)

Fonts:
 Small:  sprite
 Medium: sprite
 Large:  sprite
 Mono:   sprite

AI Configuration (local: 0) (current: 16):
  0: Human
  1: CityLifeAI (v1)

Libraries:
 LZMA:       5.4.1
 LZO:        2.10
 PNG:        1.6.39
 Zlib:       1.2.13

Module information:
 C:\Program Files (x86)\Steam2\steamapps\common\OpenTTD\openttd.exe handle: 00007FF79F860000 size: 12496336 crc: 4D5CD869 date: 2023-07-04 02:32:32
 C:\WINDOWS\SYSTEM32\ntdll.dll handle: 00007FFA66A40000 size: 2129392 crc: 5613E61C date: 2023-06-24 05:00:38
 C:\WINDOWS\System32\KERNEL32.DLL handle: 00007FFA65710000 size: 790624 crc: 3A341BDA date: 2023-06-24 05:00:25
 C:\WINDOWS\System32\KERNELBASE.dll handle: 00007FFA641A0000 size: 3716128 crc: 0D3A1B6C date: 2023-06-24 05:00:41
 C:\WINDOWS\System32\WS2_32.dll handle: 00007FFA652E0000 size: 467296 crc: 714A995B date: 2021-06-05 12:05:25
 C:\WINDOWS\System32\RPCRT4.dll handle: 00007FFA65410000 size: 1199720 crc: 5FF7B7F2 date: 2023-06-24 05:00:40
 C:\WINDOWS\SYSTEM32\OPENGL32.dll handle: 00007FFA3CB80000 size: 937984 crc: 6DBC1AF1 date: 2022-10-30 05:55:39
 C:\WINDOWS\System32\msvcrt.dll handle: 00007FFA648A0000 size: 673896 crc: 11D3F579 date: 2021-06-05 12:05:25
 C:\WINDOWS\System32\IMM32.dll handle: 00007FFA66790000 size: 214904 crc: 33223948 date: 2023-04-01 01:19:48
 C:\WINDOWS\System32\ADVAPI32.dll handle: 00007FFA657D0000 size: 724472 crc: 46A77847 date: 2023-06-24 04:59:53
 C:\WINDOWS\System32\win32u.dll handle: 00007FFA64640000 size: 166696 crc: BE757DDC date: 2023-06-24 05:00:23
 C:\WINDOWS\System32\PSAPI.DLL handle: 00007FFA66780000 size: 41664 crc: 14228118 date: 2021-06-05 12:05:23
 C:\WINDOWS\System32\sechost.dll handle: 00007FFA64A40000 size: 658384 crc: 3069B60C date: 2023-06-24 05:00:40
 C:\WINDOWS\System32\USER32.dll handle: 00007FFA65540000 size: 1778136 crc: 646B1EAB date: 2023-06-24 05:00:23
 C:\WINDOWS\SYSTEM32\WINMM.dll handle: 00007FFA5A410000 size: 211096 crc: 7116E50C date: 2021-06-05 12:04:54
 C:\WINDOWS\System32\combase.dll handle: 00007FFA64BE0000 size: 3660992 crc: EC24D3DC date: 2023-04-01 01:19:42
 C:\WINDOWS\System32\GDI32.dll handle: 00007FFA65350000 size: 183240 crc: F72B9246 date: 2023-06-24 05:00:09
 C:\WINDOWS\System32\ucrtbase.dll handle: 00007FFA64080000 size: 1132544 crc: F3DDB40F date: 2021-06-05 12:05:23
 C:\WINDOWS\System32\gdi32full.dll handle: 00007FFA63F60000 size: 1178992 crc: FC0FEF72 date: 2023-06-24 05:00:50
 C:\WINDOWS\System32\msvcp_win.dll handle: 00007FFA64530000 size: 649104 crc: 33D056E0 date: 2021-06-05 12:05:23
 C:\WINDOWS\SYSTEM32\USP10.dll handle: 00007FFA60FE0000 size: 102400 crc: BF045E3F date: 2021-06-05 12:05:27
 C:\WINDOWS\System32\SHELL32.dll handle: 00007FFA659A0000 size: 8199296 crc: 8F24DAEE date: 2023-06-24 05:00:52
 C:\WINDOWS\System32\ole32.dll handle: 00007FFA665E0000 size: 1695536 crc: BAF50B45 date: 2023-06-24 05:00:34
 C:\WINDOWS\SYSTEM32\GLU32.dll handle: 00007FFA42F10000 size: 180224 crc: 2F6BA491 date: 2022-10-30 05:55:39
 C:\WINDOWS\SYSTEM32\dxcore.dll handle: 00007FFA61300000 size: 232792 crc: 9D92F799 date: 2022-07-13 14:45:08
 C:\Program Files (x86)\Steam2\gameoverlayrenderer64.dll handle: 00007FFA20AB0000 size: 1416040 crc: 01E1246A date: 2023-07-11 01:04:54
 C:\WINDOWS\System32\OLEAUT32.dll handle: 00007FFA64B00000 size: 884600 crc: DB2A5BE3 date: 2021-06-05 12:05:25
 C:\WINDOWS\SYSTEM32\windows.storage.dll handle: 00007FFA61FB0000 size: 8864608 crc: 0190CC2A date: 2023-06-24 05:00:18
 C:\WINDOWS\SYSTEM32\wintypes.dll handle: 00007FFA61E40000 size: 1488936 crc: 14AD3ED6 date: 2023-06-24 05:00:36
 C:\WINDOWS\System32\SHCORE.dll handle: 00007FFA64950000 size: 972432 crc: 0E624C87 date: 2022-07-13 14:45:17
 C:\WINDOWS\System32\shlwapi.dll handle: 00007FFA65190000 size: 388744 crc: BF10454F date: 2021-06-05 12:05:33
 C:\WINDOWS\system32\uxtheme.dll handle: 00007FFA611F0000 size: 696320 crc: 9314217B date: 2022-09-02 09:09:02
 C:\WINDOWS\System32\MSCTF.dll handle: 00007FFA667F0000 size: 1181792 crc: 00FD724B date: 2023-04-01 01:19:32
 C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll handle: 00007FFA5F290000 size: 286512 crc: DFC8C66A date: 2022-07-13 14:45:08
 C:\WINDOWS\SYSTEM32\ntmarta.dll handle: 00007FFA62F70000 size: 219352 crc: 1A189826 date: 2021-06-05 12:05:25
 C:\WINDOWS\SYSTEM32\kernel.appcore.dll handle: 00007FFA62F50000 size: 107784 crc: D480B782 date: 2022-07-13 14:45:11
 C:\WINDOWS\System32\bcryptPrimitives.dll handle: 0000017478840000 size: 534440 crc: 26FDF61F date: 2023-02-02 08:32:12
 C:\WINDOWS\System32\clbcatq.dll handle: 00007FFA658F0000 size: 716272 crc: AB9441BC date: 2023-04-01 01:19:40
 C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_639dc0cca54f85f3\ig11icd64.dll handle: 00007FFA06B00000 size: 17255832 crc: 687F5669 date: 2022-02-28 20:20:48
 C:\WINDOWS\system32\dwmapi.dll handle: 00007FFA61560000 size: 186304 crc: 67499569 date: 2022-07-13 14:45:24
 C:\WINDOWS\system32\dxgi.dll handle: 00007FFA61340000 size: 1001336 crc: E36D466F date: 2023-06-24 05:00:09
 C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_639dc0cca54f85f3\igdml64.dll handle: 00007FFA0ECD0000 size: 3113824 crc: 6BE20C85 date: 2022-02-28 20:21:58
 C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_639dc0cca54f85f3\igdgmm64.dll handle: 00007FFA5B120000 size: 4072848 crc: D047AB62 date: 2022-02-28 20:21:46
 C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_639dc0cca54f85f3\igc64.dll handle: 00007FFA547A0000 size: 57683944 crc: 76E8C313 date: 2022-02-28 20:20:58
 C:\WINDOWS\SYSTEM32\powrprof.dll handle: 00007FFA63DB0000 size: 326784 crc: 4FA0289C date: 2021-06-05 12:05:25
 C:\WINDOWS\SYSTEM32\UMPDC.dll handle: 00007FFA63D90000 size: 87128 crc: EFBDF558 date: 2021-06-05 12:04:57
 C:\WINDOWS\SYSTEM32\textinputframework.dll handle: 00007FFA3C460000 size: 1245104 crc: D02C696D date: 2023-06-24 05:00:11
 C:\WINDOWS\SYSTEM32\CoreMessaging.dll handle: 00007FFA60C50000 size: 1265784 crc: 867E93B3 date: 2022-10-30 05:55:19
 C:\WINDOWS\SYSTEM32\CoreUIComponents.dll handle: 00007FFA5EA70000 size: 3603632 crc: 73109799 date: 2022-07-13 14:45:07
 C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL handle: 00007FFA63670000 size: 58224 crc: 01FD7442 date: 2021-06-05 12:05:25
 C:\WINDOWS\System32\MMDevApi.dll handle: 00007FFA5AD60000 size: 641864 crc: 80B83DB1 date: 2022-10-30 05:55:02
 C:\WINDOWS\System32\DEVOBJ.dll handle: 00007FFA63AC0000 size: 190424 crc: 15617D83 date: 2021-06-05 12:05:25
 C:\WINDOWS\SYSTEM32\cfgmgr32.dll handle: 00007FFA63AF0000 size: 318520 crc: 084BF0F1 date: 2021-06-05 12:05:25
 C:\WINDOWS\SYSTEM32\AUDIOSES.DLL handle: 00007FFA59DE0000 size: 1931032 crc: 1DFDD7ED date: 2022-07-13 14:12:37
 C:\WINDOWS\system32\mswsock.dll handle: 00007FFA63400000 size: 430080 crc: 02FFC4B3 date: 2021-06-05 12:05:23
 C:\WINDOWS\SYSTEM32\xaudio2_8.dll handle: 00000174003D0000 size: 12288 crc: 00A13FC9 date: 2021-06-05 12:04:54
 C:\WINDOWS\SYSTEM32\xaudio2_9.DLL handle: 00007FFA2B850000 size: 667648 crc: 17581F60 date: 2023-06-24 04:59:50
 C:\WINDOWS\SYSTEM32\AVRT.dll handle: 00007FFA5F270000 size: 55112 crc: 2504B8D9 date: 2022-07-13 14:44:56
 C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll handle: 00007FFA61460000 size: 95392 crc: 6BDC9966 date: 2021-06-05 12:05:03
 C:\WINDOWS\System32\dmusic.dll handle: 00007FFA4FE30000 size: 180224 crc: BB784371 date: 2023-06-24 05:01:23
 C:\WINDOWS\SYSTEM32\winmmbase.dll handle: 00007FFA5A6F0000 size: 173880 crc: DE915E87 date: 2021-06-05 12:04:54
 C:\WINDOWS\System32\ksuser.dll handle: 00007FFA5EA60000 size: 45792 crc: 4298F33E date: 2021-06-05 12:04:54
 C:\WINDOWS\System32\DSOUND.dll handle: 00007FFA206C0000 size: 655360 crc: 7A5B3366 date: 2023-04-01 01:19:06
 C:\WINDOWS\System32\MSACM32.dll handle: 00007FFA5C470000 size: 132576 crc: 5B9A077F date: 2021-06-05 12:04:54
 C:\WINDOWS\System32\ResampleDmo.DLL handle: 00007FFA20600000 size: 735848 crc: 6D1A4DAD date: 2021-06-05 13:17:10
 C:\WINDOWS\System32\msdmo.dll handle: 00007FFA5A2D0000 size: 54072 crc: 601B8185 date: 2021-06-05 12:04:54
 C:\WINDOWS\SYSTEM32\wdmaud.drv handle: 00007FFA4FB40000 size: 278528 crc: F97FFF3E date: 2021-06-05 12:04:54
 C:\WINDOWS\SYSTEM32\msacm32.drv handle: 00007FFA5D270000 size: 53248 crc: E5AB6EE9 date: 2022-07-13 14:44:56
 C:\WINDOWS\SYSTEM32\midimap.dll handle: 00007FFA5D260000 size: 45056 crc: 19481042 date: 2021-06-05 12:04:54
 C:\WINDOWS\System32\dmsynth.dll handle: 00007FFA4E330000 size: 143360 crc: CC345BC9 date: 2023-06-24 05:01:23
 C:\Windows\System32\Windows.UI.dll handle: 00007FFA3C590000 size: 1624232 crc: 96F765DF date: 2021-06-05 12:05:27
 C:\WINDOWS\SYSTEM32\DNSAPI.dll handle: 00007FFA62AA0000 size: 960016 crc: 88052DC7 date: 2023-06-24 05:00:35
 C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL handle: 00007FFA62A70000 size: 194560 crc: F9AC787A date: 2022-07-13 14:45:24
 C:\WINDOWS\System32\NSI.dll handle: 00007FFA656F0000 size: 45824 crc: 0B41D24A date: 2021-06-05 12:05:25
 C:\Windows\System32\rasadhlp.dll handle: 00007FFA5A2C0000 size: 40960 crc: 31BF9F63 date: 2021-06-05 12:05:40
 C:\WINDOWS\System32\fwpuclnt.dll handle: 00007FFA5A910000 size: 532480 crc: 06148E8D date: 2023-06-24 05:00:20

---- gamelog start ----
Tick 0: new game started
Revision text changed to 13.3, savegame version 302, not modified, _openttd_newgrf_version = 0x1d386d64
New game mode: 1 landscape: 0
Added NewGRF: GRF ID 4A448850, checksum 378D96DB977F01C0ADB8CBC455B89226, filename: housing_as_industries-0.1.1\housingind_0.1.1.grf (md5sum matches)
Added NewGRF: GRF ID 454E2001, checksum 342B064182A42854EF830BC11BE86E4E, filename: real_international_maglev_set-1.6\rims.grf (md5sum matches)
Tick 1355: settings changed
Setting changed: construction.command_pause_level : 1 -> 3
---- gamelog end ----

Recent news messages:
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 4405, Ref2: 0, 4294967295
(2034-06-01) StringID: 695, Type: 10, Ref1: 4, 4360, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 4336, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 4276, Ref2: 0, 4294967295
(2034-06-01) StringID: 695, Type: 10, Ref1: 4, 4209, Ref2: 0, 4294967295
(2034-06-01) StringID: 695, Type: 10, Ref1: 4, 4130, Ref2: 0, 4294967295
(2034-06-01) StringID: 695, Type: 10, Ref1: 4, 4072, Ref2: 0, 4294967295
(2034-06-01) StringID: 695, Type: 10, Ref1: 4, 4060, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 4058, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 4050, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 4032, Ref2: 0, 4294967295
(2034-06-01) StringID: 695, Type: 10, Ref1: 4, 4029, Ref2: 0, 4294967295
(2034-06-01) StringID: 686, Type: 6, Ref1: 1, 9916697, Ref2: 0, 65535
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 3991, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 3958, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 3954, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 3952, Ref2: 0, 4294967295
(2034-06-01) StringID: 695, Type: 10, Ref1: 4, 3946, Ref2: 0, 4294967295
(2034-06-01) StringID: 695, Type: 10, Ref1: 4, 3937, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 3917, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 3911, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 3832, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 3783, Ref2: 0, 4294967295
(2034-06-01) StringID: 686, Type: 6, Ref1: 1, 10741691, Ref2: 0, 65535
(2034-06-01) StringID: 695, Type: 10, Ref1: 4, 3543, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 3536, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 3492, Ref2: 0, 4294967295
(2034-06-01) StringID: 695, Type: 10, Ref1: 4, 3459, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 3447, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 3431, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 3414, Ref2: 0, 4294967295
(2034-06-01) StringID: 698, Type: 10, Ref1: 4, 3412, Ref2: 0, 4294967295

*** End of OpenTTD Crash Report ***

Decoded stack trace:
[00] openttd              0x00007FF79FEAFAA4
[01] openttd              0x00007FF79FEAFB08
[02] openttd              0x00007FF79FEBF2B0
[03] openttd              0x00007FF79FFBBB0F
[04] openttd              0x00007FF79FFBD1C7
[05] openttd              0x00007FF7A002AF69
[06] openttd              0x00007FF79FCF54E7
[07] openttd              0x00007FF7A002B386
[08] openttd              0x00007FF7A002CE70
[09] openttd              0x00007FF7A002D9A4
[10] openttd              0x00007FF79FE8A3C2
[11] openttd              0x00007FF79FE8B0AE
[12] openttd              0x00007FF79FE8B475
[13] openttd              0x00007FF79FE8B50C
[14] openttd              0x00007FF79FE8B6BC
[15] openttd              0x00007FF79FDE1385
[16] openttd              0x00007FF79FDE17FA
[17] openttd              0x00007FF79FDE1E30
[18] openttd              0x00007FF79FD62F16
[19] openttd              0x00007FF79FD63039
[20] openttd              0x00007FF79FE9A530
[21] openttd              0x00007FF79FE9A90B
[22] openttd              0x00007FF79FCF3A53
[23] openttd              0x00007FF79FCF3AB8
[24] openttd              0x00007FF79FCF439A
[25] openttd              0x00007FF79FCF4859
[26] openttd              0x00007FF7A00F0E76
[27] KERNEL32             0x00007FFA657255A0 BaseThreadInitThunk + 16
[28] ntdll                0x00007FFA66A4485B RtlUserThreadStart + 43

*** End of additional info ***

**Comment by James103** [comment]
Do you have the crash dump (and save, screenshot)? If so, can you please zip them first and post the resulting zip file here?

**Comment by TrueBrain** [comment]
Without a `crash.dmp` there is nothing we can do here, sorry :( If you have it, please attach and reopen the ticket. Tnx :)
