### ISSUE TITLE
[Bug]: Refit at stations is not available for motorized dumpcar

### ISSUE THREAD

**Issue by George-VB** [OpenTTD/OpenTTD#11159]
### Version of OpenTTD

n20230729

### Expected result

A consist of PE2+powered dumpcar can be refitted on station

### Actual result

Refitting on station is not available, only refitting in depot is avalable

### Steps to reproduce

1) create a new game with [xussr-electric.zip](https://github.com/OpenTTD/OpenTTD/files/12209972/xussr-electric.zip) in temperate climate (iron ore and coal are available for refit) 
2) build a train of PE2 and motorized dumpcar (any order of vehicles). Default cargo is iron ore
3) add an order to the station for loading coal. try to make the order to refit a train to coal. Refit at station button is disabled
![image](https://github.com/OpenTTD/OpenTTD/assets/43310520/e72469e4-f795-40fe-bd56-c4e5dda73b05)

Note
If you add a wagon set with a regular wagons and add a regular wagon to a train, a train can be refitted, but at station only regular wagons become refitted, motorised dumpcar stays unrefitted.

**Comment by James103** [comment]
Is the "motorized dumpcar" specified in the GRF code as being capable of refit in station?

**Comment by George-VB** [comment]
refit_cost: return 0 | CB_RESULT_AUTOREFIT;

**Comment by glx22** [comment]
You also need to set `TRAIN_FLAG_AUTOREFIT` in `misc_flags` property as `refit_cost` callback documentation says "To allow autorefitting, the corresponding bit in the misc_flags must be set as well. "

**Comment by George-VB** [comment]
Thank you, I've missed it in this template
