### ISSUE TITLE
[Bug]: 2CC isn't consistent for articulated vehicles

### ISSUE THREAD

**Issue by Brickblock1** [OpenTTD/OpenTTD#11162]
### Version of OpenTTD

jgrpp 0.54.4 windows 10

### Expected result

2CC should not be applied in train info window

### Actual result

It is 
![image](https://github.com/OpenTTD/OpenTTD/assets/100433052/9963e0f8-a654-4f43-9bcd-6c562667df1d)

The vehicle has the flag on the first part but not the one with the graphics

### Steps to reproduce

1) Load this grf
[kst_scandi_train.grf.txt](https://github.com/OpenTTD/OpenTTD/files/12227411/kst_scandi_train.grf.txt)
2) buy the ME with the red and black livery
3) refit it to "2cc"
open the train info window

**Comment by PeterN** [comment]
> 2CC should not be applied in train info window

Why?

**Comment by Brickblock1** [comment]
> > 2CC should not be applied in train info window
> 
> Why?

because that part of the vehicle doesn't have the 2cc flag
