### ISSUE TITLE
[Bug]: performance regression between 13.4 and nightly

### ISSUE THREAD

**Issue by Bouke** [OpenTTD/OpenTTD#11194]
### Version of OpenTTD

g8ea01c0bfb vs 13.4

### Expected result

Same performance.

### Actual result

While rebasing at #10584, I was confused by the resulting simulation rate in wentbourne: I saw a decrease. Then to confirm against the nightly (to have a better benchmark), I found the same decrease.

|Version|Simulation rate|FPS|
|-|-|-|
|13.4|0.37x|<img src="https://github.com/OpenTTD/OpenTTD/assets/235882/a39c323c-3f0d-4c43-a28e-5adf1bd13929" width="215" />|
|g8ea01c0bfb|0.27x (25% slower)|<img src="https://github.com/OpenTTD/OpenTTD/assets/235882/6aed2f04-24c6-4281-aac4-176dcb96e2b6" width="215" />|

### Steps to reproduce

1. For 13.4 and nightly:
    a. Load a heavy savegame
    b. Note the simulation rate
2. Compare them

**Comment by LordAro** [comment]
Some difference is to be expected, as releases are built without asserts, whereas nightlies still have them (they're both built in release mode)

**Comment by Bouke** [comment]
What CMake target can I compile locally to have an apples-to-apples comparison (e.g. Release/MinSizeRel/RelWithDebInfo)?

**Comment by PeterN** [comment]
Also the target rate since 13.x is ~10% higher, do the multiplier will be lower even if it was running at the same rate.
