### ISSUE TITLE
Stations are backwards/ sidewards[Bug]: 

### ISSUE THREAD

**Issue by eKeja** [OpenTTD/OpenTTD#11216]
### Version of OpenTTD

13.4 Windows 10

### Expected result

Station placement

### Actual result

The Game placed the Station backwards/ sidewards

### Steps to reproduce

Used the Function once to drag the Size of the Station. Then Didnt wanted to use the Function and switched back to just fill in the SIte of the Station. After that, the Bug appeared. 
2. Klicked a Station in the Station pop-up-screen.
3. Chose the Way the Station should be placed.
4. Klicked somewhere on the Map to place Station.

![](https://www.kejamedia.nl/openttd/BUG-station-wrong-way1.png)

![](https://www.kejamedia.nl/openttd/BUG-station-wrong-way2.png)

Tried to:
> Uninstall and reinstall - NO RESULTS

**Comment by PeterN** [comment]
It's filled in (in 2) with the direction you have selected (in 1), so... where's the issue?

**Comment by glx22** [comment]
yeah 5 platforms of length 2 in the selected direction, works fine to me

**Comment by eKeja** [comment]
Hahahahaha, so i got that backwards my self :-D
Thanks guys
