### ISSUE TITLE
[Bug]: Sort by button is misaligned with OpenGFX2.

### ISSUE THREAD

**Issue by zephyris** [OpenTTD/OpenTTD#11230]
### Version of OpenTTD

20230630-master-f082c47a4f9

### Expected result

The vehicle list shouldn't have a hole in it! But with OpenGFX2 under the "sort by" button there's a hole....

### Actual result

![opengfx2_listbug](https://github.com/OpenTTD/OpenTTD/assets/2762690/32a1f5a3-2182-472c-b857-1415db006864)

When using OpenGFX2 a hole appears... Related to the size of sprite 4942? Because the "Sort by" button is too small vertically. But that doesn't quite make sense, because the "Group by" button seems too small vertically too.

Not sure if this should count as a base set or OpenTTD bug, but I suspect assumptions about sprite sizes shouldn't give holes in windows.

### Steps to reproduce

Just download OpenGFX2 via BaNaNaS and set as the base set... Open any vehicle list and you'll see the gap.

**Comment by glx22** [comment]
My guess is a weird widget layout, and your baseset happens to trigger an edge case.

**Comment by frosch123** [comment]
The default spritefont assumes a line height of 10px (+2px for the bevel).
In this case the dropdown arrow (right to "None"/"Number") forces a row height of 14px.

We could fix the alignment of the "Group by"/"Sort by" widgets to take the same height:
![image](https://github.com/OpenTTD/OpenTTD/assets/23150643/d156c9e8-92d8-475a-96fc-64150cce2121)
But the group names list on the left will always use the font height.

I think it is better to fix the dropdown sprite size in OpenGFX2.

**Comment by zephyris** [comment]
Ah, so a too big sprite 4941?

**Comment by LordAro** [comment]
I disagree. A baseset should not be able to break the window layout, regardless of how "broken" it is

**Comment by zephyris** [comment]
I went to try to fix this in OpenGFX2 and got confused. Sprite 4941 (the dropdown down arrow) is from OTTD_GUI offset 46. In OpenGFX2 it is an 8 x 8 px sprite... So unless I'm totally mixed up, an overlarge dropdown menu arrow sprite can't be the issue here.

**Comment by zephyris** [comment]
Is it possible to pad intelligently? ie. only pad up to the 10px sprite height? It makes it quite inflexible when trying to design GUI elements if they have an enforced padding.
