### ISSUE TITLE
[Bug]: Wiki may have incorrectly-named links. 

### ISSUE THREAD

**Issue by kevinfields777** [OpenTTD/OpenTTD#11257]
### Version of OpenTTD

0

### Expected result

Links on the wiki should have descriptive text

### Actual result

Some links, however, show up with a description of "None". I am guessing that this happened when moving the wiki over to the current format and raw links were given the name of "None" as a placeholder. 

For example, the article on Steel Mills (https://wiki.openttd.org/en/Manual/Base%20Set/Industries/Steel%20Mill) has a link to Wikipedia for more information about ironworks. The link is labeled as "None" when it should be more descriptive.  

It might be worth checking all of the pages to ensure that links have proper names, and if they don't start making a list so they can be edited by hand with porper context. 

### Steps to reproduce

n/a

**Comment by TrueBrain** [comment]
Well, first of all, this is not the repository for these things :D But as this is a problem on the wiki, you can just fix this on the wiki. Login, edit the page, fix the link. I am sure you will find more odd things when you actually look at it :)

Not sure what you expect us to do here .. I assume and hope you already fixed the current page at least :D

Let us know if we can help with anything!
