### ISSUE TITLE
[Bug]: Train does not pick up any passengers or mails

### ISSUE THREAD

**Issue by Pubiwhy** [OpenTTD/OpenTTD#11254]
### Version of OpenTTD

13.4

### Expected result

Train A and train B on a double line station pick up passengers and mails.

### Actual result

There is a double station with passengers and mail. Train A pick up passengers and mails on line 1 but the train B just unload the passengers on line 2, does not pick up any passengers. After unload it departs to the next station with empty carriage. If I click full load then the train just stands in the station and do nothing. Could not figure out why. Tried everything. The station were destroyed and rebuilt even trains were sold and replaced with new ones...the same bug.

### Steps to reproduce

Every time I rebuild the station the same bug. One train does not pick up only unlod.

**Comment by glx22** [comment]
Please attach a savegame.

**Comment by LordAro** [comment]
3 months is long enough, closing to help keep issues clear
