### ISSUE TITLE
[Bug]: Windows IME: Length unit mismatch using result of ImmGetCompositionString for GCS_CURSORPOS

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#11291]
### Version of OpenTTD

master

### Expected result

ImmGetCompositionString always returns a value in bytes, the other call sites for ImmGetCompositionString have a comment about this.

### Actual result

At https://github.com/OpenTTD/OpenTTD/blob/master/src/video/win32_v.cpp#L366
`LONG caret_bytes = ImmGetCompositionString(hIMC, GCS_CURSORPOS, nullptr, 0);`

However `caret_bytes` appears to be used as a length in sizeof(wchar_t).
At https://github.com/OpenTTD/OpenTTD/blob/master/src/video/win32_v.cpp#L368
`for (const wchar_t *c = str.c_str(); *c != '\0' && *caret != '\0' && caret_bytes > 0; c++, caret_bytes--) {`

This appears to be a possible cause for this crash: https://github.com/JGRennison/OpenTTD-patches/issues/596

At https://github.com/OpenTTD/OpenTTD/blob/master/src/video/win32_v.cpp#L356-L357
`str` also appears to be unnecessarily large

### Steps to reproduce

I don't have a working IME setup on Windows for reproduction steps

**Comment by glx22** [comment]
It's very easy to reproduce:
* Start a newgame
* Switch keyboard to japanese IME
* Try to rename a town with non latin characters

**Comment by michicc** [comment]
The code in win32_v.cpp seems to be fine, expect that the comment on line 365 is simply misleading. `GCS_CURSORPOS` is one if  the oddball things that are in fact not bytes but chars, see for example https://github.com/microsoft/VCSamples/blob/9e1d4475555b76a17a3568369867f1d7b6cc6126/VC2008Samples/International/IME/IMEEdit.cpp#L386 in combination with https://github.com/microsoft/VCSamples/blob/9e1d4475555b76a17a3568369867f1d7b6cc6126/VC2008Samples/International/IME/IMEEdit.cpp#L826

As Japanese input definitely worked in the past (it was my go to test-IME when writing all this), it very much looks like some oversight in some query string changes or `std::string` conversion.

**Comment by JGRennison** [comment]
As far as I can see the direct issue in the title (ImmGetCompositionString) is not an issue after all, and the original problem is fixed by https://github.com/OpenTTD/OpenTTD/pull/11831
