### ISSUE TITLE
[Bug]: Game fails to load with "road vehicle on invalid road type"

### ISSUE THREAD

**Issue by SammieBiscuits** [OpenTTD/OpenTTD#11319]
### Version of OpenTTD

13.4, Windows 10

### Expected result

The savegame should load with several benign errors (mostly changes to passenger capacity-related errors), but game is otherwise playable. 

### Actual result

The game freezes before producing the error. 

### Steps to reproduce

1. After opening the game, open the included save. The game will most likely freeze before producing the error in version 13.4.
[Yekaterske Zheleznice Map Saves.zip](https://github.com/OpenTTD/OpenTTD/files/12660420/Yekaterske.Zheleznice.Map.Saves.zip)

**Comment by SammieBiscuits** [comment]
> You might still be able to play the savegame on 13.0 or 13.1, and you might get lucky, but 13.2 specifically includes a check that your savegame is falling foul on, due to GRF config being changed.
> 
> > Fix: Abort loading savegame if road vehicle is on invalid road type (#10622)

Is it possible to get PC version 13.0 or 13.1? I can't seem to find older versions on the OpenTTD website.

**Comment by SammieBiscuits** [comment]
> > Is it possible to get PC version 13.0 or 13.1? I can't seem to find older versions on the OpenTTD website.
> 
> You can download older versions directly from https://cdn.openttd.org/openttd-releases/ . You can also roll back to earlier versions on Steam via the "betas" tab in the game properties.

Thank you so much! I won't be able to play newer versions of the game with this save, but it should be alright for me.

**Comment by James103** [comment]
> I won't be able to play newer versions of the game with this save

You might be able to update the save to a new version, but only after selling all road vehicles or carefully checking that every tram is on a road tile with tram and every non-tram is on a road tile with compatible road.
