### ISSUE TITLE
[Crash]: NOT_REACHED triggered at line 1942 of vehicle_gui.cpp

### ISSUE THREAD

**Issue by TaxiService** [OpenTTD/OpenTTD#11329]
### Version of OpenTTD

OpenTTD 20230920-master-g72323ae9e6 | Windows 10 22H2 19045.3324

### Steps to reproduce

- load this save [autosave2(crash20230921095051).zip](https://github.com/OpenTTD/OpenTTD/files/12683210/autosave2.crash20230921095051.zip)
- select Ship#2, open its orders window and click on this tiny button.
(i couldnt get the tooltip to show in the screenshot, but it says "Show all vehicles that share this schedule")
![image](https://github.com/OpenTTD/OpenTTD/assets/5853667/e9ff22b8-358f-4a6f-beb3-942b8a43c95e)
- this crashes the game with the following error dialog
![image](https://github.com/OpenTTD/OpenTTD/assets/5853667/4da5a127-1ce4-4278-868b-b7bc518b42f8)

### Upload crash files

[crash20230921095051.zip](https://github.com/OpenTTD/OpenTTD/files/12683156/crash20230921095051.zip)

**Comment by PeterN** [comment]
Confirmed with a fresh game with two aircraft sharing orders (so not just ship-related).

**Comment by PeterN** [comment]
Caused by #11321. Creation of the vehicle list is deferred til after the window is initialized, but there's a check that vehicle list length is non-zero during initialization (via widget sizing routines.)
