### ISSUE TITLE
[Bug]: Cannot expand towns in Scenario Editor when town road construction disallowed

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#11374]
### Version of OpenTTD

13.4

### Expected result

In Scenario Editor, when I open a town window and press Expand, the town gets bigger, building more roads if needed.

If I have disabled the setting `Towns are allowed to build roads`, the town expands anyway, because according to the documentation of the setting, it is `always allowed when generating world / in SE`: https://github.com/OpenTTD/OpenTTD/blob/master/src/settings_type.h#L546

### Actual result

If I have disabled town road construction, the town does not get larger and instead gives a warning popup: `The town will not build roads. You can enable building of roads via Settings->Environment->Towns`.

I guess there might be a use case for expanding a town without building roads, so the resolution for this issue might be to fix the setting documentation.

### Steps to reproduce

1. Open Scenario Editor
2. Open Settings menu and disable `Towns are allowed to build roads`
3. Build a town
4. Click on the town name to open the town window
5. Click Expand
6. Note that the town does not grow and you get an error message

**Comment by glx22** [comment]
Missing check in https://github.com/OpenTTD/OpenTTD/blob/master/src/town_gui.cpp#L506

**Comment by 2TallTyler** [comment]
That whole case indicates that the error is intentional. It's really more of a "behavior does not match documentation" than a bug.

**Comment by glx22** [comment]
I just think documentation is correct, but the check should also test `_game_mode != GM_EDITOR`

**Comment by 2TallTyler** [comment]
That's my preferred resolution too, but the Expand button is only present in Scenario Editor, so the entire error needs to be deleted.

**Comment by glx22** [comment]
It should still check for GM_EDITOR (like build river)

**Comment by glx22** [comment]
Hmm `CmdExpandTown` enforces GM_EDITOR https://github.com/OpenTTD/OpenTTD/blob/master/src/town_cmd.cpp#L2953
But `GrowTown` will still build no road https://github.com/OpenTTD/OpenTTD/blob/master/src/town_cmd.cpp#L1776
So enabling the GUI won't be enough.

**Comment by LordActive** [comment]
The message was displayed only once, after that, the town would expand normally until it would run out of space (prompting the player to either allow road construction or build the road themselves). This way a person could build a town in a way they wanted and have full control over the build. Which is no longer the case after forcing the road expansion on, effectively killing the eye candy scenario building style.
