### ISSUE TITLE
[Bug]: roadtypes with speed limits show undefined string in scenario editor

### ISSUE THREAD

**Issue by PikkaBird** [OpenTTD/OpenTTD#11375]
### Version of OpenTTD

20231015-master

### Expected result

Newgrf roadtypes show a string in the title bar of the construction menu.
![screenshot#1](https://github.com/OpenTTD/OpenTTD/assets/39507755/264acf91-e811-4f4a-8e90-3e1d9dc42edc)

### Actual result

Newgrf roadtypes with a set speed limit show "undefined string (0 km/h)" in the scenario editor only - they work correctly in normal gameplay. I tested this with multiple newgrfs including timberwolf's roads and RATT roads.
![screenshot#2](https://github.com/OpenTTD/OpenTTD/assets/39507755/2f8e4045-03f9-462c-ae41-2887042a19fa)

### Steps to reproduce

Load a newgrf with speed-limited roadtypes in the scenario editor.

I assume this is a similar string issue to #11367.

**Comment by glx22** [comment]
`_nested_build_road_widgets` uses `STR_JUST_STRING2`
`_nested_build_tramway_widgets` uses `STR_JUST_STRING`
`_nested_build_road_scen_widgets` uses `STR_JUST_STRING`
`_nested_build_tramway_scen_widgets`uses `STR_JUST_STRING`
And they are mostly all wrong https://github.com/OpenTTD/OpenTTD/blob/master/src/road_gui.cpp#L406-L417
