### ISSUE TITLE
Message log shows all news items, even those disabled in settings

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#11409]
### Version of OpenTTD

13.4

### Expected result

If I don’t want to see a type of news item, like production changes of industries my company does not serve, I can change its notification type to None.

This means it doesn’t generate a newspaper or appear in the news ticker. 

I would expect that it is also hidden from the message log. 

### Actual result

The message log gets cluttered with every single news item, even those which I’ve disabled. 

### Steps to reproduce

1. Set a news type to “none”
2. Fast-forward the game for a minute or so
3. Check the message log for unwanted news items

**Comment by TrueBrain** [comment]
And so history forms:

- News popup is annoying, we need a summary!
- The summary (ticker) is annoying, it takes too long! I want to disable it!

And now we are at the step:

- I disabled the news, it shouldn't be in the history!

:D I love how context is lost, refound, put in a different context, and processed again :) (I am not even being sarcastic; it is really fun to see happen, being with this project for this long).

Anyway, most context can be found here:
https://github.com/OpenTTD/OpenTTD/commit/febae668fec6ebb3fffc9ff038e9cfab0f3f0a39

Basically, the idea of the setting is to influence the news dropout / ticker, not the actual news history. As the commit message states, even if you hide the news message, it still shows you a red dot that there was news. So you can use in the history what it was about.

Actually completely hiding news is a new request. And when you don't know the background, I can fully understand why it is a surprise that "none" doesn't mean: don't add in the history. That said, I am not sure actually fully hiding news is a good idea.

What might be another solution, is to add a filter in the news history window, so you can filter yourself. And maybe word the setting a bit better that this is about the news popup/ticker, not about the history.

Anyway, just an old man speaking here :)

**Comment by 2TallTyler** [comment]
So this is a feature request, not a bug. I don't intend to fulfill said feature request, so I will close this. 🙂
