### ISSUE TITLE
[Bug]: Something bad happened (JRG 55.3)

### ISSUE THREAD

**Issue by Ross999123** [OpenTTD/OpenTTD#11415]
### Version of OpenTTD

55.3 JRG. win10 64

### Expected result

For the JRG to work as normal, see next field for further info. 

### Actual result

I've been playing the update for the past week with no issues. I've taken a break from the game this afternoon and came back to find an error message advising something like "big a_a" missing, but I can't remember the exact red message on the title screen. 

Here are some of the issues I've found so far:

- No "new GRF" option to download and add/remove grfs. 
- Trains no longer go from far end to middle/near end of platforms, they just stay where ever they first arrived. Not a big issue, but would be something I'd like for future shunt moves.
- A lot of settings have been reset to default, such as the routing lines reappearing, news popping up, sign transparancy settings, vehicle warnings. I've turned most off, but it was annoying. 
- Even when I start a new game to test, the "newgrf settings" doesn't have the option to add/remove newgrfs (which I had no issue with/fixing any issues before). I also don't think I can update anything with any upgrades. :(

This is my back-up file for when it worked normally: https://www.dropbox.com/scl/fi/8fqocs0j57edi02sus4lp/AUG2022V1BUILDINGCITIES.sav?rlkey=7g5ybcw1ssciq4oylrekedh5t&dl=0

This was my progress when the issue occurred, I was just building towns and landmarks in London: https://www.dropbox.com/scl/fi/tnb58gh5ecmmq2ycs4lgg/New-issue-National-Rail-Junction-Map-3729-10-12.sav?rlkey=1g4wszcxn2chwhnpf689gm3uw&dl=0

Is this a feature or a fault? I can't even go back to vanilla OpenTTD as I started this with JRG. I can't even go back to a previous JRG version (if that would even work). 

### Steps to reproduce

1. Loaded game
2. Red warning message about "large a_a" missing , didn't continue, restarted PC.
3. Nothing seems right, lots of setting reset/lost/changed. 
4. See drop-box share of current progress.

**Comment by James103** [comment]
This may be caused by starting OpenTTD with a corrupt or missing `openttd.cfg` file, which causes the game to reset all its settings as if started for the first time.

**Comment by Ross999123** [comment]
Sorry, just checked my search history before I restarted the machine. The red message advised: error with the configuration file invalid value " for 'large_aa'
Is there any way I could put this back in and where would I put it?

**Comment by Ross999123** [comment]
https://github.com/JGRennison/OpenTTD-patches/issues/606
