### ISSUE TITLE
[Bug]: Trains not loading cargo 

### ISSUE THREAD

**Issue by martinezjr231** [OpenTTD/OpenTTD#11421]
### Version of OpenTTD

OpenTTD 12.2; Win10 22H2

### Expected result

Vehicles pick up cargo as assigned.
![Hardswijk Transport, 2055-01-09](https://github.com/OpenTTD/OpenTTD/assets/28929286/78e08092-6f86-46ce-82a6-4022e8fabf6b)

### Actual result

Vehicles not picking up cargo as a result.

### Steps to reproduce

1. Pick engine
2. Pick cars
3. Select cargo type
4. Set train orders to "Full load any cargo" at station with goods
5. Set train orders to "Transfer and leave empty" as station to receive goods

Note:
1. I have interchanged trains and cars to test if maybe that is the issue, but same result, trains not picking up cargo.  
2. Also happens with road vehicles.
3. Added image of GRF for info

![HardswijkTransport2055-01-09scene2](https://github.com/OpenTTD/OpenTTD/assets/28929286/bcaf344b-f4cb-4799-9d1f-e7eca78907b1)
![HardswijkTransport2055-01-09scene3](https://github.com/OpenTTD/OpenTTD/assets/28929286/8f3f1360-0e5e-42ed-a4cf-11df86c12ade)

**Comment by 2TallTyler** [comment]
It appears that you have Cargo Distribution enabled, and the cargo waiting at the station wants to go to a different destination than the vehicles which are not loading.

**Comment by martinezjr231** [comment]
How do I change that?  I do not see any settings for that.

**Comment by 2TallTyler** [comment]
![cargodist](https://github.com/OpenTTD/OpenTTD/assets/55058389/43d8e271-59a0-4116-bafc-a8eb6d654969)

You probably want most cargos set to manual distribution, so they will go anywhere you wish to take them.

**Comment by martinezjr231** [comment]
That did it.  Thanks!
