### ISSUE TITLE
[Bug]: Flipped train of lenght 3 not being drawn correctly

### ISSUE THREAD

**Issue by Brickblock1** [OpenTTD/OpenTTD#11437]
### Version of OpenTTD

jgrpp 0.55.3 windows 10

### Expected result

Train is properly shown in depot.

### Actual result

it is not vissible even when it works outside the depot
![image](https://github.com/OpenTTD/OpenTTD/assets/100433052/ecbbc859-0264-4118-b69d-c73deca3269c)

### Steps to reproduce

1) Start a new game with the grf below 
2) Open the depot and buy the Z4p 
3) flip it by ctrl pressing
4) Notice how it disappears 
[openttd_bugs.zip](https://github.com/OpenTTD/OpenTTD/files/13257543/openttd_bugs.zip)

**Comment by PikkaBird** [comment]
I can confirm this bug exists in 20231104-master - a locomotive shortened to 3/8 and reversed is invisible in the depot and vehicle lists, while appearing correctly on the track.

This appears to affect only vehicles of 3/8 length (and possibly shorter), using #10262's automatic offset feature. If the EF_RAIL_FLIPS flag is set, the graphics display correctly.

Attached is a test grf with two test locomotives, one without EF_RAIL_FLIPS set ("autoflip") and one with the flag set ("manuflip"). The manuflip locomotive has had its sprite offsets corrected in the horizontal views only, for demonstration purposes.

[sunshine_test.zip](https://github.com/OpenTTD/OpenTTD/files/13258696/sunshine_test.zip)

**Comment by PeterN** [comment]
Thanks Pikka for the additional information that was missing in the report.
