### ISSUE TITLE
[Bug]: Changing interface size can have weird effects on current zoom

### ISSUE THREAD

**Issue by zephyris** [OpenTTD/OpenTTD#11515]
### Version of OpenTTD

Latest nightly, Windows 10 & 11

### Expected result

When changing the interface size in game, it should change the game zoom consistently. Doubling the interface size should double the game zoom, unless you're already fully zoomed in.

### Actual result

If you increase interface size by a factor of two or more when the game is at maximum zoom in then the zoom 'wraps around' to a large zoom out. This also confuses the toolbar zoom buttons, the zoom in remains grayed out, even though the game is now zoomed out, but scroll to zoom still works. 

(The inverse doesn't happen, if you decrease interface size by at least a factor of two while the game is at maximum zoom out then the zoom stays at maximum zoom out). 

### Steps to reproduce

1. Start a new game with the interface size to 1x. 
2. Zoom all the way in, to 4x zoom in.
3. Set the interface size to 2x using the Game Options > Graphics menu.
4. The game will maximally zoom out, and the zoom in toolbar button will be the grayed out. 

Similar results happen when 4x zoomed in and you change the interface size from 2x to 4x, or when 2x zoomed in and you change the interface size from 1x to 4x.

**Comment by PeterN** [comment]
IIRC this also happens in 13.x, I just never got around to dealing with it.
