### ISSUE TITLE
[Bug]: Ctrl + left click Centre view on ship depot opens a viewport centered on a power station

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#11577]
### Version of OpenTTD

20231211-master-g0a8bcdd344

### Expected result

Open a viewport centered on ship depot.

### Actual result

Opens a viewport centered on a power station.

### Steps to reproduce

1. Start a new game
2. Build a ship depot
3. Click on it
4. Ctrl-click on Centre view button

**Comment by glx22** [comment]
I can confirm it on windows, but it's fine with wsl.
