### ISSUE TITLE
[Bug]: Goods cars and trucks have very low capacity when refitted

### ISSUE THREAD

**Issue by DonaldDuck313** [OpenTTD/OpenTTD#11575]
### Version of OpenTTD

13.4, Windows 11

### Expected result

It should be possible to transport a reasonable amount of cargo in goods cars and goods trucks, even when refitted.

### Actual result

Goods cars can only take 13 units of cargo each when refitted, and goods trucks can only take 9 units of cargo each. I don't know if this is considered a bug, but it makes it very difficult to transport cargo types that can only be transported in refitted goods cars or goods trucks.

Especially for the goods truck, it's almost impossible to make it go with profit at all. And even for trains with goods cars, even if I have a 4 tile (7 car) long train it's often very difficult to transport everything produced by an industry, so I've often ended up with thousands of units of cargo waiting because the train can't transport everything.

Interestingly, this doesn't happen when transporting goods, only other cargo types. I would expect the goods cars and goods trucks to have the same capacity no matter what cargo type they transport.

### Steps to reproduce

1. Download a NewGRF that adds new cargo types, for example FIRS.
2. Build a depot for trains or road vehicles, and click on New Vehicle.
3. Filter by a cargo type other than goods that can only be transported in goods cars, for example engineering supplies.
4. Buy a vehicle, and you will see that its capacity is ridiculously low.

**Comment by PeterN** [comment]
Provide a savegame set up showing the problem.

Cargo multipliers for refit capacity are set by the industry/cargo NewGRF.

**Comment by PeterN** [comment]
ImprovedGenericTramSet.grf is not available to download.

**Comment by PeterN** [comment]
This is technically by design, as the the multiplier for goods is 512, 256 for the other types. FIRS could change that but doesn't.

**Comment by DonaldDuck313** [comment]
> This is technically by design, as the the multiplier for goods is 512, 256 for the other types. FIRS could change that but doesn't.

Should it be changed then? Because if it's the default behavior, it's likely that most other NewGRFs that introduce new cargo types have the same problem.

**Comment by 2TallTyler** [comment]
It's up to the industry set (multiplier) or the vehicle GRF (capacity), not OpenTTD itself.
