### ISSUE TITLE
[Bug]: Wrong liveries list for trains

### ISSUE THREAD

**Issue by George-VB** [OpenTTD/OpenTTD#11613]
### Version of OpenTTD

n20231218

### Expected result

Common liveries are available

### Actual result

Liveries list is empty
![image](https://github.com/OpenTTD/OpenTTD/assets/43310520/6d0af56f-d055-44a4-a360-180311d780c6)
![image](https://github.com/OpenTTD/OpenTTD/assets/43310520/05d32faf-9aee-4ced-83f6-2c85332e091f)
![image](https://github.com/OpenTTD/OpenTTD/assets/43310520/87757b1f-baa2-4219-8642-4397a48ca216)

I expect that it may happen because these a different files (while the use the same livery ID and livery name), but it is not expected restriction

### Steps to reproduce

[xussr-cars.zip](https://github.com/OpenTTD/OpenTTD/files/13751670/xussr-cars.zip)
[xussr-electric.zip](https://github.com/OpenTTD/OpenTTD/files/13751682/xussr-electric.zip)

1. Start a game after 2000 with vehicles never expire option.
2. Build ChS2/53E locomotive and 61-817 wagon
3. Try refitting

**Comment by PeterN** [comment]
Cargo subtype name is compared by string ID, because they are different NewGRFs the string ID is not the same.

IMHO this is won't-fix

**Comment by 2TallTyler** [comment]
I agree. We don't really support cross-GRF communication like this, and cargo subtype liveries are somewhat depreciated now that we have variants.
