### ISSUE TITLE
[Bug]: Errors during build process that i dont know how to resolve

### ISSUE THREAD

**Issue by mahoff140** [OpenTTD/OpenTTD#11620]
### Version of OpenTTD

Windows 11, VS Community 2022, master commit c1afbc9

### Expected result

CMake builds and links the strings.h

As was recommended to me [here](https://www.tt-forums.net/viewtopic.php?t=91376) im making a ticket and since none of the other issue templates fits my problem im making a bug report.

### Actual result

CMake builds the game and i can start it but the strings.h is always missing which leads to build errors.

[error.txt](https://github.com/OpenTTD/OpenTTD/files/13759212/error.txt)

Ive followed the COMPILING.md.

I dont understand why the strings.h isnt being generated since i havent modified the source yet and (at least in my mind) followed proper procedure.

### Steps to reproduce

1. git pull master at c1afbc9
2. open the project in vs 2022 on windows 11
3. build the project

**Comment by glx22** [comment]
`strings.h` is autogenerated during build, and this step automatically happens before openttd compilation (CMake manages the build order to ensure that).

**Comment by gammarayb** [comment]
defining VCPKG_TARGET_TRIPLET and CMAKE_TOOLCHAIN_FILE correctly in the cmakesettings.json and running "vcpkg integrate install" solved the problem
