### ISSUE TITLE
[Bug]: Fix Romanian translation of some strings/words

### ISSUE THREAD

**Issue by georgeabr** [OpenTTD/OpenTTD#11666]
### Version of OpenTTD

13.4, linux

### Expected result

Romanian words should use comma instead of cedilla for ș/ț, and correct form of verb înnoi. 
I've created PR #11665 to merge.

### Actual result

The above is not true and should be corrected.

### Steps to reproduce

Load game and change language accordingly.

**Comment by nielsmh** [comment]
Please use the web translator to update the translations.
https://translator.openttd.org/
