### ISSUE TITLE
[Bug]: Vehicle lists went missing in the AI/GS documentation

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#11689]
### Version of OpenTTD

20240104-master-gc44faf4eea

### Expected result

https://docs.openttd.org/ai-api/hierarchy
https://docs.openttd.org/gs-api/hierarchy

Every "Creates a list of vehicles..." show up.

### Actual result

https://docs.openttd.org/ai-api/hierarchy
https://docs.openttd.org/gs-api/hierarchy

Every "Creates a list of vehicles..." disappeared.

### Steps to reproduce

I suspect it was https://github.com/OpenTTD/OpenTTD/pull/11663 which caused it.

**Comment by glx22** [comment]
Yeah it's hard to test doxygen on windows, I'll debug with WSL.
