### ISSUE TITLE
[Bug]: Decreasing service interval when it's 5%, jumps to 90%

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#11748]
### Version of OpenTTD

20240109-master-gc86d918921

### Expected result

Percentage stays at 5% when decreasing servicing interval from 5%.

### Actual result

Percentage jumps to 90% when decreasing servicing interval from 5%.

### Steps to reproduce

1. Start a new game
2. Build a ship
3. View details
4. Change interval type to percentage
5. Click the left arrows to decrease percentage below 5%

**Comment by glx22** [comment]
https://github.com/OpenTTD/OpenTTD/blob/86b046cd26a67c1a216e5487ff72c91f80d8e4d0/src/vehicle_gui.cpp#L2616
`mod` is -10, `v->GetServiceInterval()` is 5 so -5 is passed to `GetServiceIntervalClamped()`
https://github.com/OpenTTD/OpenTTD/blob/86b046cd26a67c1a216e5487ff72c91f80d8e4d0/src/order_cmd.cpp#L1852-L1855
`GetServiceIntervalClamped()` takes an uint so the -5 is actually a huge positive number and it's clamped to 90.
