### ISSUE TITLE
[Bug]: Nightly builds are failing since January 10

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#11756]
### Version of OpenTTD

Since f7bd70baec83b97e8b4e91f1425b2b105d3ac9f6

### Expected result

Nightly builds should build and publish for all platforms at the expected time.

### Actual result

Since January 10, the nightly builds are failing in the Linux (Generic) category, causing no builds to be published.
The error is different, however, as the build is failing on the "Enable Rust cache" step with the following error:
```
/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /__e/node20/bin/node)
```

### Steps to reproduce

Wait for the nightly build via GitHub Actions, then check the logs.
Most recent failing run: https://github.com/OpenTTD/OpenTTD/actions/runs/7493388614/job/20399019407

**Comment by glx22** [comment]
Yeah the `rust-cache` action received an update and it seems it's now incompatible with the very old linux we use to build "Linux (Generic)".
