### ISSUE TITLE
[Bug]: Charactors in NewGRF menu being displayed incorrectly while using zh_CN and zh_TW

### ISSUE THREAD

**Issue by wensimehrp** [OpenTTD/OpenTTD#11752]
### Version of OpenTTD

Master

### Expected result

Charactors being displayed correctly, i.e.
```
文件名：
```

### Actual result

In the "NewGRF Details" column, the charactor "名" at the filename part has been displayed twice with a werid change of lines, making it
```
文件名
名：
```
and
```
檔名
名：
```

<img width="501" alt="image" src="https://github.com/OpenTTD/OpenTTD/assets/145064583/167344c0-9d90-4d73-b358-19e1fe26d2b7">

*zh_CN*

<img width="476" alt="image" src="https://github.com/OpenTTD/OpenTTD/assets/145064583/50d65f1d-eba7-472b-8e4d-4f77d92918a9">

*zh_TW*

MD5sum is also displayed incorrectly in the zh_TW screenshot, with a strange line change and a duplicated charactor, while zh_CN only has a line change, which also shouldn't be there.

Other languages (languages I've checked so far) does not have this problem.

I've checked the language files of both zh_TW and zh_CN but I couldn't find any problems in the strings.

### Steps to reproduce

1. Open OpenTTD
2. change language to Chinese (simplified) or Chinese (traditional)
3. open newgrf settings and select a NewGRF.

**Comment by JGRennison** [comment]
#11485 may be related to this

**Comment by glx22** [comment]
Yeah I think it's the same issue.

**Comment by WenSimEHRP** [comment]
In #11485 the problem occurs when the window is resized to a size, but for this issue I tried resizing the window and the duplicated charters still exsists.

**Comment by rubidium42** [comment]
@WenSimEHRP, looking at the zh_CN translation I'm seeing that for the NewGRF settings window there are some strings that use a wider colon (：) without space, whereas others use the ASCII colon (:) and a space. So there is some inconsistency in there.

I'm not sure what's the real difference between these options, but with the ASCII colon and space the layouter will break the string at the space after the colon, instead of before the character before it. I think that will look better overall.

**Comment by WenSimEHRP** [comment]
> @WenSimEHRP, looking at the zh_CN translation I'm seeing that for the NewGRF settings window there are some strings that use a wider colon (：) without space, whereas others use the ASCII colon (:) and a space. So there is some inconsistency in there.

@rubidium42 Yes, and that is another problem. There are too many punctuation mistakes in the translation and I might make a PR for that, in which it replaces all ascii :,." thingy to the ones used in standard Chinese.

**Comment by WenSimEHRP** [comment]
This issue should not be closed as *completed* as the line problem still exsists. Nonetheless, there is one way that I can think of to fix this problem, which is replacing all Chinese styled punctuations to ascii ones + " ". But as I said earlier, ascii punctuations are not used in standard Chinese and should be replaced by formal ones.
