### ISSUE TITLE
[Bug]: Font rendering is ugly on linux

### ISSUE THREAD

**Issue by man-of-eel** [OpenTTD/OpenTTD#11765]
### Version of OpenTTD

Latest git, Arch Linux

### Expected result

I like to use OpenTTD with these settings:
```
small_font = Tahoma
medium_font = Tahoma, Bold
large_font = Times New Roman
mono_font = 
small_size = 0
medium_size = 13
large_size = 0
mono_size = 0
```
On stable 13.4 it looks nice:
![image](https://github.com/OpenTTD/OpenTTD/assets/86927456/c0d0e55b-ba70-4337-95d2-480ff9aea198)

### Actual result

But somewhere between then and now the spacing between glyphs has been broken:
![image](https://github.com/OpenTTD/OpenTTD/assets/86927456/4859f45c-803f-4b8c-9594-7f01b48ebc99)

### Steps to reproduce

1. Install Microsoft Tahoma font (Tahomabd.ttf) (using Windows 11 version here but the Windows 7 one should look the same)
2. Set openttd.cfg as above

**Comment by PeterN** [comment]
This change is probably caused by the switch to ICU/Harfbuzz.

**Comment by man-of-eel** [comment]
[Ah.](https://github.com/harfbuzz/harfbuzz/issues/2394)

Yeah not sure what can be done about this. Why the change?

**Comment by glx22** [comment]
Because #6922
