### ISSUE TITLE
[Crash]: when loading a TTD savegame with vehicles and then unpausing

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#11785]
### Version of OpenTTD

a6873ef7dd1da93f0d954817d7b68a1621b4a04c on Windows 10, 64-bit

### Steps to reproduce

1. Load any TTD savegame with vehicles inside.
2. Unpause the game.
3. The game asserts here after a few ticks: https://github.com/OpenTTD/OpenTTD/blob/a6873ef7dd1da93f0d954817d7b68a1621b4a04c/src/economy.cpp#L1633

### Upload crash files

The following ZIP file contains the TTD savegame that was loaded when reproducing the issue, and the resulting crash logs: [crash20240115180153.zip](https://github.com/OpenTTD/OpenTTD/files/13941802/crash20240115180153.zip)

However, the issue is not specific to that TTD savegame; many other TTD savegames crash OpenTTD when unpaused with the same assertion error.

**Comment by PeterN** [comment]
This is a TTDPatch savegame (#4398) so if it ever worked it was just luck.

**Comment by rubidium42** [comment]
With #11783 most of the TTO savegames are also running into the same assertion when unpausing. So I'm not sure it's a TTDPatch only issue.

**Comment by rubidium42** [comment]
Reverting #9680 solves this crash (and the crashes I'm seeing for #11783).
