### ISSUE TITLE
[Bug]: Toggling whether to use traditional sprite font overrides font changes due to language

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#11791]
### Version of OpenTTD

a1690d5b7b33a3ba60e55a261a128e1a17fca8c2 on Windows 10, 64-bit

### Expected result

Toggling whether to use the sprite font or not should not override font changes from other sources, including changing the language.

Ideally, if the option to use the traditional sprite font is toggled off, and the OpenTTD font series support all characters used in the current language, the font is changed to that.

### Actual result

When the language is changed to one that isn't supported by the sprite font or the OpenTTD font series, the font is changed to one that supports the language being used, as expected.

However, when the option to use the traditional sprite font is then toggled, the font is changed back to the sprite font or the OpenTTD font series, even if the font being changed to does not support the language. This results in lots of question marks in place of non-Latin characters.

### Steps to reproduce

1. Make sure the game is using the default fonts, by setting `mono_font`, `small_font`, `medium_font`, and `large_font` to blank values.
2. Change the language to Korean.
3. Toggle whether to use the traditional sprite font.
4. Notice question marks in place of Hangul characters.

**Comment by telk5093** [comment]
I can reproduce this if font settings such as ``small_font``, ``medium_font`` and etc. has default value(i.e. blank), while it is not if I use custom font settings.
