### ISSUE TITLE
[Bug]: Fullscreen Disables HDR

### ISSUE THREAD

**Issue by TheMowgliMan** [OpenTTD/OpenTTD#11809]
### Version of OpenTTD

13.4 Windows x86-64

### Expected result

I enter fullscreen, my monitor remains in HDR.

### Actual result

When I go fullscreen, HDR is disabled. When I leave fullscreen, HDR comes back on.

### Steps to reproduce

1. Launch OpenTTD
2. Open Game Options and enable HDR

**Comment by PeterN** [comment]
We don't support HDR at all, so this is a Windows system/driver bug.

It could probably be worked around if OpenTTD implemented non-exclusive fullscreen mode though.

**Comment by TheMowgliMan** [comment]
Hmm, interesting. I've noticed some other games cause issues with HDR, such
as Stardew Valley. What I don't understand is why fullscreen disables HDR
in the first place; as I'm on Windows, it shouldn't be true exclusive
fullscreen in the first place (If I understand how Windows works
correctly). Next time I play, I should check if I can turn HDR back on
after it's shut off.

**Comment by glx22** [comment]
It is exclusive full screen, it can even mess the desktop icons if you use a lower resolution

**Comment by TrueBrain** [comment]
There are more than one report on the interwebz about this problem, and all related to driver issues. Maybe they can be helpful.

Anyway, as said, we don't do anything in relation to HDR, so it dropping out of HDR is not something in our control :( Sorry, but we can't help here!

Going to close this ticket for now; but please do post an update if you have any, so others might learn from it :) Tnx!
