### ISSUE TITLE
[Bug]: Incorrect water region connectivity check with aqueduct on an edge

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#11802]
### Version of OpenTTD

20240116-master-g2efd897691

### Expected result

No connectivity!

Something like this should do the check the right way:
https://github.com/OpenTTD/OpenTTD/blob/2efd8976914d0a669656143a2cd20426df0b9901/src/script/api/script_marine.cpp#L59-L77

### Actual result

![Captura de ecrã 2024-01-16 173937](https://github.com/OpenTTD/OpenTTD/assets/43006711/de7c583b-161e-4d06-9576-bf405476342e)

### Steps to reproduce

https://github.com/OpenTTD/OpenTTD/blob/2efd8976914d0a669656143a2cd20426df0b9901/src/pathfinder/water_regions.cpp#L294-L297

**Comment by 2TallTyler** [comment]
What is the `Actual result` showing? What's your proof that this is broken? (Not saying you're wrong, but I don't understand your diagnosis.)

**Comment by SamuXarick** [comment]
> What is the `Actual result` showing? What's your proof that this is broken? (Not saying you're wrong, but I don't understand your diagnosis.)

The picture is showing 2 tiles sharing the same edge. During ForceUpdate, these two tiles can have a ship exit their respective edges, making traversability bits marked to indicate that.

On the bottom side, the tracks are on the ocean, on the top side, the tracks are on the ramp. Ships can't go from the sea to the ramp in that manner.

**Comment by Kuhnovic** [comment]
Looks like you've found a nice edge case indeed. And _of course_ it involves aqueducts. The bane of my existence.

**Comment by Kuhnovic** [comment]
![image](https://github.com/OpenTTD/OpenTTD/assets/68320206/22956427-3e05-492b-80a1-5baabd8ee71a)
I think a much easier solution would be to mark the ramp of the bridge on the left as non-traversible (red line). It is treated as a cross-region-bridge, essentially "teleporting into another region". 

The ramp of the bridge on the right does provide an regular entry into the region, so there the bit should be set (indicated by the yellow line).
