### ISSUE TITLE
[Crash]: Crash after hitting the "show all" button in the cargoflow menu

### ISSUE THREAD

**Issue by wensimehrp** [OpenTTD/OpenTTD#11819]
### Version of OpenTTD

Master, Windows 11

### Steps to reproduce

1. Load crash20240117195049.sav (or start a new game)
2. Hit this button
<img width="214" alt="image" src="https://github.com/OpenTTD/OpenTTD/assets/145064583/1cf5ae7e-8a97-433d-a63c-4b30afe55ae2">

3. Crash

### Upload crash files

[crash20240117.zip](https://github.com/OpenTTD/OpenTTD/files/13968116/crash20240117.zip)

**Comment by frosch123** [comment]
Broken in aa5ba5b: linkgraph_gui.cpp:
``` diff
-	for (uint c = 0; c < num_cargo; c++) {
-		if (!this->IsWidgetLowered(c + WID_LGL_CARGO_FIRST)) continue;
+	for (CompanyID c = COMPANY_FIRST; c < MAX_COMPANIES; c++) {
+		if (!this->IsWidgetLowered(WID_LGL_CARGO_FIRST + c)) continue;
```
