### ISSUE TITLE
[Bug]: GetCharPosition does not work with ligatures

### ISSUE THREAD

**Issue by PeterN** [OpenTTD/OpenTTD#11827]
### Version of OpenTTD

master

### Expected result

Editing text and moving the text cursor should not crash ;)

### Actual result

Layouter::GetCharPosition() does not consider ligatures, which replaces (at least) a pair of characters with a single glyph.

These are used mostly by non-Latin script, but some Latin fonts also use them (e.g. Tahoma Bold has an 'fi' ligature)

### Steps to reproduce

1. Set medium font to "Tahoma, Bold" 12.
2. Open the console and enter "refit".
3. Use arrow keys to move cursor.

**Comment by glx22** [comment]
It's probably OS specific, no issue for me on windows.

**Comment by PeterN** [comment]
Probably. FreeType and harfbuzz make use of ligatures for Latin text.

Non-Latin text might have an issue on other OSes, but it's slightly harder to test:

1. Set language to Arabic.
2. Build a station.
3. Edit the station name and move the text cursor.

**Comment by zephyris** [comment]
In my (breif) tests ligatures aren't used under windows, so a different behaviour is expected. But, that's tested using my own fonts, so I'm not certain if it's a font problem or a display problem.

It'd be nice if they were used, but that's a different issue ;)

**Comment by glx22** [comment]
Tried Arabic, and the station rename. I can move cursor with cursor keys without crashing.
