### ISSUE TITLE
[Bug]: Music is still playing while volume is set to 0

### ISSUE THREAD

**Issue by wensimehrp** [OpenTTD/OpenTTD#11822]
### Version of OpenTTD

Master, Windows 11

### Expected result

No music playing when volume is set to 0.

### Actual result

While using *Touhou* as base music set, the title music is still playing while music volume is set to 0.
However, *original_windows* and *OpenMSX* won't occur the problem though.

This issue might be a duplication of #9640.

### Steps to reproduce

~~Since I'm not sure whether the original author of *Touhou* would allow me to share the baseset online or not, the files will not be included before I get premission from the author. Thus this bug might be unreproducible.~~

**Comment by glx22** [comment]
Can you test with `-m win32` and `-m dmusic` ? (IIRC dmusic is the default)

**Comment by WenSimEHRP** [comment]
> Can you test with `-m win32` and `-m dmusic` ? (IIRC dmusic is the default)

@glx22 I tried with both of them and the problem still exsisits.

**Comment by WenSimEHRP** [comment]
[touhou_67+.zip](https://github.com/OpenTTD/OpenTTD/files/13973953/touhou_67%2B.zip)

**Comment by 2TallTyler** [comment]
I can confirm this on the 17 January nightly, Windows 10, using the attached music set. Like with the original report, it does not happen with other music sets.

It doesn't happen when launching the game, but when changing modes back to the menu from another mode (in-game or Scenario Editor) the main menu volume seems to initialize at 100%, no matter what the volume slider is set to (not just zero, it does the same if set to a very low volume).

**Comment by PeterN** [comment]
Okay, the MIDI file is very basic and does not have a channel volume message at all (nor does it select an instrument, so pot-luck there!)

I suspect we only insert a channel volume message when the value is changed or when we modify the MIDI file's own channel volume messages as they are processed.

They are at the start of each track in the normal base set, that would hide a missing volume change.

So I think we just need to also send channel volume messages when starting playback after the MIDI reset done in `TransmitNotesOff()`.
