### ISSUE TITLE
[Bug]: Ship is stuck

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#11840]
### Version of OpenTTD

20240119-master-g6a2c37b4ed

### Expected result

Ship 1763 finds the way. The path is valid, unobstructed.

### Actual result

Ship 1763 is stuck. The path is valid, unobstructed.

https://github.com/OpenTTD/OpenTTD/assets/43006711/4638bd43-15d2-45ae-8252-35390dc94031

### Steps to reproduce

[Unnamed, 1941-04-02.zip](https://github.com/OpenTTD/OpenTTD/files/13989947/Unnamed.1941-04-02.zip)

**Comment by PeterN** [comment]
[Wartston Transport, 1980-07-31.zip](https://github.com/OpenTTD/OpenTTD/files/13990414/Wartston.Transport.1980-07-31.zip)

Smaller save with just one ship and only 64x64 tiles. Easier to debug. I could not get the ship to get stuck by itself, only by clearing tiles as it was moving.

**Comment by Kuhnovic** [comment]
![image](https://github.com/OpenTTD/OpenTTD/assets/68320206/d8333a71-8ed7-4460-ba9f-b6936defa801)

I was able to produce a situation similar to the savegame provided by @PeterN , this time in OpenTTD 13.4
[OTTD_13.4.zip](https://github.com/OpenTTD/OpenTTD/files/14171739/OTTD_13.4.zip). 

I had to wait for the ship to be where it is in the screenshot, stop it, and then I changed the order to go to the depot on the right. In 13.4 the ship gets lost as well, but moves around enough so it find a new path eventually.
![17ltj9kSBQ](https://github.com/OpenTTD/OpenTTD/assets/68320206/e6a9a9f0-9981-448c-8d4b-5ae6bd65d272)

I haven't been able to figure out what causes the change in behavior, still looking into that.
