### ISSUE TITLE
[Bug]: something's wrong with center view on tiles

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#11873]
### Version of OpenTTD

20240122-master-g76499b96fb

### Expected result

Center view on tiles correctly.

### Actual result

going from c to first h is bugged, going from second h to first h is fine
https://github.com/OpenTTD/OpenTTD/assets/43006711/1ad380e3-13cf-4b90-8d15-b2d483d5695f

### Steps to reproduce

I created a scenario replicating the coordinates of the two tiles involved.
[scroll between towns.zip](https://github.com/OpenTTD/OpenTTD/files/14024942/scroll.between.towns.zip)
1. Load the attached scenario.
2. Open the town list.
3. Click on the towns to scroll center on them.

**Comment by glx22** [comment]
It's caused by 1985e7415b, but I don't know why.

**Comment by TrueBrain** [comment]
> It's caused by [1985e74](https://github.com/OpenTTD/OpenTTD/commit/1985e7415b5c6c5341f87c49fbc1f7f043bec28a), but I don't know why.

Test with https://github.com/OpenTTD/OpenTTD/pull/11865 applied first, before delving into it. There are some rounding issues when close to borders before that PR.

**Comment by glx22** [comment]
Ok with #11865 it feels weird, but it ends up on the right place.
