### ISSUE TITLE
[Bug]: In wallclock mode, `GSDate.GetYear` always returns the current economic period.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#11890]
### Version of OpenTTD

80ebcc72fb415fc73f80cb8afbf0d927ade639e4 on Windows 10, 64-bit

### Expected result

`GSDate.GetYear` should always return the year corresponding to the date passed in, regardless of if it is in calendar mode or economy mode.

### Actual result

In wallclock mode when `GSTimeMode` is economy (the default), `GSDate.GetYear` always returns the economic period corresponding to the current economic date, not the date passed in.

### Steps to reproduce

Create a Game Script with the following in `main.nut`'s `Start()` function:
```squirrel
function Main::Start() {
	local cal = GSTimeMode(true)
	GSLog.Info("Calendar: " + GSDate.GetYear(GSDate.GetDate(1234, 5, 6)))
	cal = null
	GSLog.Info("Economy: " + GSDate.GetYear(GSDate.GetDate(1234, 5, 6)))
}
```
Then set Timekeeping units to Wallclock, start a new game with that Game Script, and observe the log output.

**Comment by TrueBrain** [comment]
Don't be teasing, also please actually attach referenced output :) Helps with the understanding ;)

**Comment by James103** [comment]
Sorry for the incomplete example. I have attached the full Game Script and updated the example.
[TestGS #11890.zip](https://github.com/OpenTTD/OpenTTD/files/14073073/TestGS.11890.zip)
