### ISSUE TITLE
[Bug]: Cannot fund towns while using infinate money

### ISSUE THREAD

**Issue by wensimehrp** [OpenTTD/OpenTTD#11938]
### Version of OpenTTD

Master

### Expected result

Player can fund towns when bank balances is negative.

### Actual result

Player cannot.

<img width="751" alt="image" src="https://github.com/OpenTTD/OpenTTD/assets/145064583/4342b27a-44af-41df-a926-e15e90598165">

### Steps to reproduce

1. make bank balance negative (or do nothing)
2. try to fund a town

**Comment by 2TallTyler** [comment]
Ah, looks like the code that checks if town actions should be shown in the UI hasn't been adapted. Paging @merni-ns... 😉

**Comment by DefinitelyNotRau117** [comment]
A similar thing with loan repayment. 
![изображение](https://github.com/OpenTTD/OpenTTD/assets/115672237/5814521c-ede0-40cd-b113-046368f66d34)
_Another question is whether loans are needed in infi money mode._
