### ISSUE TITLE
[Bug]: Crashed AI data not deleted until AI goes bankrupt

### ISSUE THREAD

**Issue by TheMowgliMan** [OpenTTD/OpenTTD#11960]
### Version of OpenTTD

1.13.4 Stable

### Expected result

Extra data about AI is deleted immediately.

### Actual result

When an AI crashes, the AI's data in memory isn't deleted until the AI's company goes bankrupt and is shut down. Occasionally this only takes a short time, but other times this can take quite a while or effectively forever, especially if the AI already had profitable routes.

### Steps to reproduce

1. Start a game with an AI (DictatorAI seems pretty buggy, it should crash easily enough)
2. Open FPS counter
3. Wait for the AI to crash (Again, this seems to be what DictatorAI was built for)
4. Notice in the FPS Counter how the AI's data isn't deleted until the bankruptcy news message appears.

**Comment by TrueBrain** [comment]
This is fully by design.

When an AI crashes, it stays in this crashed state till the company it is controlling is deleted (for example, by bankruptcy). Till then, it is there, just in a halted state.

It is mostly meant to allow the ability for developers to either see or request what is in the crash log of the AI; if we would delete it instantly, there won't be room for this.

What you don't really explain in your ticket, is why you would expect it to be deleted instantly? Is it preventing you to do something in some way?

**Comment by TheMowgliMan** [comment]
No, it just seems to be the habit of you devs to save as much memory and
CPU cycles as possible, after watching this repo for a while :) If that's
the case, then, why don't you just save the crash log in a file and
terminate it immediately, like most programs do? That might even be more
useful, as an AI developer could just let it run without themselves being
around and grab the crash log later, no matter what. Going further, when
the AI is a bit more robust, they could set up "testing farms" by just
starting a bunch of the AIs (Say, all 14/15 allowed in the game) and
walking away for a while, and iron out crashes that way. Given that, for
most AIs, crashes are rare, it seems the most logical solution to me, as a
person without OpenTTD dev experience.

**Comment by TrueBrain** [comment]
Absolutely good ideas. Script logs can already be written to disk, but to always do it seems not so nice for most users :) as for AI testing, that is up to the authors.

Either way, if nothing prevents you from playing the game, I will close this up. We are always looking to improve and suggestions are always welcome, but as said, this is currently intended behaviour and as such not a bug :) Nevertheless, I appreciate you raising this point!

**Comment by TheMowgliMan** [comment]
No problem! I debated whether to send it as a bug: didn't seem appropriate
for the forums in any way, might have been a higher priority to y'all than
deserved to be opened in Discuss, and didn't quite seem a bug. Just no
really good place to put this.
