### ISSUE TITLE
[Crash]: signal on bridge / tunnel / station crashes the game

### ISSUE THREAD

**Issue by Jacobus-Mr-Cool** [OpenTTD/OpenTTD#11985]
### Version of OpenTTD

ex 14.0 bata-1 windos 7

### Steps to reproduce

When clicking a signal on the first or end tile of a bridge or tunnel. error happen

![cr](https://github.com/OpenTTD/OpenTTD/assets/29341296/ffa891c5-e49d-4344-bb26-eaaa1b3bc896)
![cr 2](https://github.com/OpenTTD/OpenTTD/assets/29341296/8415c431-987c-47ee-b34d-90c258d58061)

### Upload crash files

[openttd.txt](https://github.com/OpenTTD/OpenTTD/files/14156664/openttd.txt)

**Comment by TrueBrain** [comment]
Thanks for the report!

This is in fact a duplicated of #11982 (but triggered by bridges instead of stations), and fixed by #11977. We hope to ship an update soon! For now: please only place signals on rails :)
