### ISSUE TITLE
[Crash]: When clicking to insert orders for a specific vehicle

### ISSUE THREAD

**Issue by Bekofz** [OpenTTD/OpenTTD#11987]
### Version of OpenTTD

14.0-beta1, Win11

### Steps to reproduce

1. Bought the vehicle Tama Tanker Road Train, automagically refitted for Water.
2. Click the Orders button on the vehicle -> Crash

![2024-02-04_161359](https://github.com/OpenTTD/OpenTTD/assets/158836489/6d4758b5-9f76-4ba1-9eff-ed3e5872e685)
![2024-02-04_161837](https://github.com/OpenTTD/OpenTTD/assets/158836489/e1f23309-791e-45d4-bcdb-4f2e57e90336)

### Upload crash files

[crash20240204151757.zip](https://github.com/OpenTTD/OpenTTD/files/14157382/crash20240204151757.zip)

**Comment by Bekofz** [comment]
Tried with another vehicle from the same depot, did not cause the crash. Tried again with above vehicle, crash reproduced.

**Comment by TrueBrain** [comment]
Thank you for the report!

This is in fact a duplicated of https://github.com/OpenTTD/OpenTTD/issues/11978, and fixed by https://github.com/OpenTTD/OpenTTD/pull/11973. We hope to ship an update soon!
