### ISSUE TITLE
[Crash]: Cannot start route on 14.0-beta1 multiplayer

### ISSUE THREAD

**Issue by MASACR99** [OpenTTD/OpenTTD#11989]
### Version of OpenTTD

14.0-beta1

### Steps to reproduce

1. Start multiplayer server
2. Wait for friends to join
3. Try to create route
4. On click of the bus game crashes

### Upload crash files

[crash20240204192904.json.zip](https://github.com/OpenTTD/OpenTTD/files/14158032/crash20240204192904.json.zip)

**Comment by michicc** [comment]
Thank your for the report.

This particular problem was already reported and is fixed in #11973. The next release of OpenTTD will contain the fix.
