### ISSUE TITLE
[Bug]: Game crashes when attempting to place Semaphore on Train Station

### ISSUE THREAD

**Issue by Ivan-Cristian** [OpenTTD/OpenTTD#11982]
### Version of OpenTTD

14.0-Beta1 Windows 10

### Expected result

Error popup displayed informing user that Train Station is not a valid placement for Signal On Railway tool

### Actual result

Game crashes.
![Screenshot 2024-02-04 120150](https://github.com/OpenTTD/OpenTTD/assets/24207785/893e106f-9109-4dcd-8b41-d8fa5d894f0d)

### Steps to reproduce

1. Create a 5-length Train Station
2. Select Signal on Railway tool
3. Select Path Signal (semaphore)
4. Click anywhere on the Train station created in Step 1

**Comment by michicc** [comment]
Thanks for the report.

Already fixed by #11977 which will be in the next release.
