### ISSUE TITLE
[Bug]: Sub-Arctic Food Plants

### ISSUE THREAD

**Issue by Lut3s** [OpenTTD/OpenTTD#11999]
### Version of OpenTTD

14.0-beta2

### Expected result

Delivering livestock to a processing plant to manufacture food

### Actual result

No food is produced. Also, only livestock is produced by farms, but this might be intentional. Only affects new games.

### Steps to reproduce

[Food Production Bug.zip](https://github.com/OpenTTD/OpenTTD/files/14162540/Food.Production.Bug.zip)

**Comment by LordAro** [comment]
Duplicate of #11995
