### ISSUE TITLE
[Crash]: Placing signal on a train station and then crashed

### ISSUE THREAD

**Issue by joaojesus81** [OpenTTD/OpenTTD#11990]
### Version of OpenTTD

14.0-beta1, Windows 10

### Steps to reproduce

1. Select a railway signal
2. Click on a station instead of a line

### Upload crash files

[OpenTTD.zip](https://github.com/OpenTTD/OpenTTD/files/14158373/OpenTTD.zip)

**Comment by LordAro** [comment]
Duplicate of #11982 , fixed by #11977
