### ISSUE TITLE
[Bug]: Some industries in tropical and arctic climates not producing cargo

### ISSUE THREAD

**Issue by Bonehead-101** [OpenTTD/OpenTTD#11995]
### Version of OpenTTD

14.0-beta2

### Expected result

Expected the Bank to accept Diamonds since that's it's good. 

### Actual result

I spent a good chunk of change to build a maglev path, to find out there were no diamond cars, I then downgraded to monorail to use the one engine with cargo capacity to find out the bank wasn't accepting the goods.

### Steps to reproduce

![image](https://github.com/OpenTTD/OpenTTD/assets/158988224/b3e7113d-5b8c-4260-9b8e-0ce96b9aa7cd)

**Comment by PeterN** [comment]
Fixed by #12000
