### ISSUE TITLE
[Bug]: No Corn (desert) Train Cars, Fruit not being accepted to Food Processing Plant (desert)

### ISSUE THREAD

**Issue by Bonehead-101** [OpenTTD/OpenTTD#11996]
### Version of OpenTTD

14.0 beta2

### Expected result

Expected Corn Train Cars. Expected Fruit to be delivered via train cars.

### Actual result

I built a run from a Corn Farm to a Food Processing Plant (desert), only to find no food train cars available (after 2025, perhaps sooner as well). Also, the Food Processing Plant (desert) is not accepting Fruit.

### Steps to reproduce

![image](https://github.com/OpenTTD/OpenTTD/assets/158988224/38860ff0-6070-4ce5-a1b6-678418c53eeb)

**Comment by LordAro** [comment]
Same bug as #11995, several cargo things are broken in beta2
