### ISSUE TITLE
[Bug]: Loading TTD and TTO savegames causes financial statements to be blank for 1,920 years.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#11997]
### Version of OpenTTD

14.0-beta2 and 9cc17230e864b84e60fa96e0bfcf1ed969d7345a on Windows 10, 64-bit

### Expected result

Loading TTD and TTO savegames allow financial statements to be viewed immediately for all companies.

### Actual result

Loading TTD and TTO savegames cause all financial statements to be blank for 1,920 years or until the date cheat is used.
This is caused by the economy date being set to the number of years elapsed since 1920, as that is how the date was stored in TTO and TTD.

### Steps to reproduce

1. Load any TTD or TTO savegame.
2. View financial statements for any company.
3. Notice they are all blank.

**Comment by 2TallTyler** [comment]
@James103 Are you able to test if #12007 fixes this issue?
