### ISSUE TITLE
[Crash]: While creating train route

### ISSUE THREAD

**Issue by lexuslatvia** [OpenTTD/OpenTTD#11991]
### Version of OpenTTD

14.0-beta1, Windows 10

### Steps to reproduce

1. Brought new train and cars
2. Tried to establish new route, game crashed

### Upload crash files

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/14158564/crash.zip)

**Comment by LordAro** [comment]
Duplicate of #11968, fixed in #11973
