### ISSUE TITLE
Click on Train Order [Crash]: 

### ISSUE THREAD

**Issue by Taterspud** [OpenTTD/OpenTTD#12002]
### Version of OpenTTD

OpenTTD 14.0.0.55115

### Steps to reproduce

Deleted station two electric tracks and 2 monorail tracks
Redbild with 5 monorail tracks
Station changed name
Trains have invalid station/destination
Opened station edit, changed name to previous station name
clicked on a train that did not stop at station
Clicked on yellow "Order" button, the Game crashed.

### Upload crash files

 
[crash20231209150152.log](https://github.com/OpenTTD/OpenTTD/files/14168352/crash20231209150152.log)
[crash20240205155812.json.log](https://github.com/OpenTTD/OpenTTD/files/14168355/crash20240205155812.json.log)
[crash20240205155812.dmp](https://github.com/OpenTTD/OpenTTD/files/14168374/crash20240205155812.dmp)
[crash20231209150152.zip](https://github.com/OpenTTD/OpenTTD/files/14168437/crash20231209150152.zip)

**Comment by glx22** [comment]
Please update to 14.0-beta2, it should be fixed.

**Comment by Taterspud** [comment]
Thank you!!



________________________________
