### ISSUE TITLE
[Crash]: cargotype???

### ISSUE THREAD

**Issue by Ufiby** [OpenTTD/OpenTTD#12001]
### Version of OpenTTD

20240204-master-g9cc17230e8

### Steps to reproduce

/

### Upload crash files

![GIF 05 02 2024 17-31-44](https://github.com/OpenTTD/OpenTTD/assets/46504018/967840a1-d1a3-4166-b9e2-1902040b8976)

**Comment by LordAro** [comment]
Thanks for the report! Seems related, but actually distinct to the missing cargoes in #11995.

But still, in future could you please use your words - a gif is informative but words are a lot more concrete, and mean you can read them without having to watch a gif over and over (not usually any controls for a gif, remember)
