### ISSUE TITLE
[Bug]: Sandbox options available in multiplayer which causes desync

### ISSUE THREAD

**Issue by MontyMontana** [OpenTTD/OpenTTD#12029]
### Version of OpenTTD

14.0-beta3 Linux Generic

### Expected result

Sandbox options deactivated in multiplayer.

### Actual result

Sandbox options are available to be used, and it seems to modify the map (magic bulldozer). However, those actions finally cause a desync and client is autokicked from the servers. For some actions (e.g. Fix station rating), desync is caused immediatly.

### Steps to reproduce

1. Connect to a server.
2. Use sandbox options.

**Comment by TrueBrain** [comment]
Cheers, tnx for the report!
