### ISSUE TITLE
[Bug]: Default font rendering looks bad on macOS external display

### ISSUE THREAD

**Issue by Bouke** [OpenTTD/OpenTTD#12037]
### Version of OpenTTD

14.0-beta3, macOS

### Expected result

Text to be legible like in pre v14:

![image](https://github.com/OpenTTD/OpenTTD/assets/235882/f0f6bb71-65af-422c-a74b-290ca4a891a5)

### Actual result

Text looks bad on an external (normal dpi) display:

![image](https://github.com/OpenTTD/OpenTTD/assets/235882/4ed2bd9f-8449-451c-879d-f70b1ab1c9a6)

Turning off anti aliasing resolves the problem. Should AA be the default in such situations?

### Steps to reproduce

Run 14.0-beta3 on macOS with an external display (or move to external display) with default settings.

**Comment by PeterN** [comment]
Could you try 14.0-beta2 to see if it's any different? The font was updated between beta2 and beta3. Not expecting any change but would be good to confirm.

**Comment by Bouke** [comment]
In 14.0-beta2 I get the same result:

![image](https://github.com/OpenTTD/OpenTTD/assets/235882/0a53f199-ff88-446a-bda3-41b8a06811d7)

**Comment by zephyris** [comment]
Just to clarify, this is almost certainly a TrueType font rendering problem. In 14.0 the rendering of the windows, icon sprites and viewport sprites look perfect, it's just the font that's problematic. In 13.4, the default font was a sprite font.

(@Bouke It'd be useful if you could confirm that in 13.4 you're using the sprite font, ie. that you haven't manually edited your openttd.cfg file to use the OpenTTD TrueType fonts. If you have no idea what I'm talking about then that means you were using the sprite font in 13.4.).

The workaround is to switch back to the sprite font (`Game Options > Graphics > Use traditional sprite font`).

Looking at letters with clear vertical and horizontal strokes (eg. `E`) it looks like the X and Y position of the font are shifted by exactly 0.5 pixels. The horizontal strokes should be 1px wide, but are being rendered 2px wide at exactly half opacity. The vertical strokes should be 2px wide, but are being rendered 3px wide with the centre pixel full opacity, but the flanking ones half opacity.

**Comment by zephyris** [comment]
The initial thought from Discord discussion was that the following is to blame:
https://github.com/OpenTTD/OpenTTD/blob/9b323b4ef9f1f12d629c4f42d6641e37be541cba/src/os/macosx/font_osx.cpp#L266

However, no developers have a MacOSX system to test/debug it.

**Comment by Bouke** [comment]
I'd say right on the money. Having `float offset = 0.0f;` yields the following results:

AA on:
![image](https://github.com/OpenTTD/OpenTTD/assets/235882/2f073c1b-b58f-4be0-a1c5-2a33fad024c4)

AA off:
![image](https://github.com/OpenTTD/OpenTTD/assets/235882/803ee604-1890-424c-ada4-72fbff981aec)

This seems to fix the blurry text issue. There is still some blurriness on some letters, take for example the "x" in "Exit", but that is probably to be expected with AA.

**Comment by zephyris** [comment]
Looks like a pixel-perfect fix to me.

**Comment by PeterN** [comment]
I wonder why this is there... and does changing this fix other fonts or make them worse?

**Comment by michicc** [comment]
I'm quite sure I didn't have an offset there at first, and at least on whatever macOS version I test it back then, 0.0 look bad with the regular fonts shipped with the OS.

It's entirely possible that there was some kind of API/function change since then or that it is some retina/non-retina nonsense.

**Comment by Bouke** [comment]
Without the offset it also looks better on a retina display (MacBook Pro built-in display). On the left is 14.0-beta3, on the right master with the offset set to 0. The text is less blurry without the offset.

<img width="172" alt="image" src="https://github.com/OpenTTD/OpenTTD/assets/235882/95f7004e-0678-49e2-9497-e3a7ac6ab06e"> 
<img width="174" alt="image" src="https://github.com/OpenTTD/OpenTTD/assets/235882/5d2e7d21-a509-41b2-b8d2-d7586a5f4b1d">

(Note that the images will be downscaled on non-high-dpi displays, or open them in full resolution.)

**Comment by zephyris** [comment]
Again, zero offset looks pixel perfect.

**Comment by PeterN** [comment]
@Bouke would you be able to do a comparison of offset 0.5 vs offset 0.0 with the language set to a CJK language (which will automatically switch font), and/or with the fonts set to a system-installed font? It would be useful to see if it improves that or makes it worse.

**Comment by zephyris** [comment]
Looks like a clear consensus that `float offset = 0.0f;` is the correct fix.

Presumably this could be macOS version-dependent, but works for recent versions. So reasonable to take as the solution?

**Comment by Bouke** [comment]
On macOS Catalina (10.15, 2019) the text is blurry in beta3 and is fixed without the offset:

![Screenshot 2024-02-10 at 08 16 28](https://github.com/OpenTTD/OpenTTD/assets/235882/623b45a2-e105-43b2-9403-cef5ab2dca59)
