### ISSUE TITLE
[Bug]: Music not installing

### ISSUE THREAD

**Issue by WilmerSchouten** [OpenTTD/OpenTTD#12041]
### Version of OpenTTD

Windows 11; OpenTTD 14.0-beta3

### Expected result

Downloading music tracks for using them in-game. see images
<img width="639" alt="musictracks" src="https://github.com/OpenTTD/OpenTTD/assets/113888427/38dc079a-5298-4e2b-af99-39fb01448d7d">
<img width="646" alt="downloadedmusictracks" src="https://github.com/OpenTTD/OpenTTD/assets/113888427/c7102b1c-ed7f-456e-8f86-4555ea91f8cf">

### Actual result

I downloaded music via download extra content in start menu, but when I go to game options, no soundtracks were displayed. see image 
<img width="500" alt="nomusic" src="https://github.com/OpenTTD/OpenTTD/assets/113888427/5640ef42-ab04-41f0-9986-8870ea503b9e">

### Steps to reproduce

1. start game
2. go to search online content
3. search for basic music
4. download it
5. go to game options -> sound
6. try to apply other music track
7. not possible with me

**Comment by glx22** [comment]
Tested 2 basesets, they both extracted empty (which feels wrong)
![image](https://github.com/OpenTTD/OpenTTD/assets/2952192/006c7930-fbff-4c65-adde-35003f59da7b)
![image](https://github.com/OpenTTD/OpenTTD/assets/2952192/fb9c3fc2-c74b-4f56-8fd6-650eb50e1811)

**Comment by WilmerSchouten** [comment]
@glx22 Okay, so it really is something, right?
Please say if I need to do something, 'cause I don't know how this whole bug reporting works.

**Comment by glx22** [comment]
Your report is fine, it's really a bug :)

**Comment by JDawsonT** [comment]
Was gonna come say something about this. Thanks for keepin up the work guys!
