### ISSUE TITLE
[Bug]: The fast forward button on the touch bar works in multiplayer

### ISSUE THREAD

**Issue by ghost** [OpenTTD/OpenTTD#12069]
### Version of OpenTTD

13.4, macOS 14.3

### Expected result

It doesn't work, just like the one on the toolbar.

### Actual result

It actually fast forwards, and for everyone too.

### Steps to reproduce

Set up a multiplayer game from a Mac with a touch bar.
Fast forward with the touch bar button.

**Comment by TrueBrain** [comment]
Already fixed in #11206 and part of 14.0-beta3 if you like to try it out!
