### ISSUE TITLE
[Bug]: It is possible for dedicated server process to stop being a server.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#12074]
### Version of OpenTTD

13.4 and 8d9fa0ea89 on Windows 10, 64-bit

### Expected result

A dedicated server should always be a server.

### Actual result

It is possible for a dedicated server process to stop being a server, through the `part` command.

### Steps to reproduce

1. Start a dedicated server with `openttd -D`.
2. Run the console command `clients`.
3. Notice the command outputs the list of clients.
4. Run the console command `part`.
5. Notice the command succeeds and returns the dedicated server process to the main menu.
6. Run the console command `clients` again.
7. Notice this time the command errors with `Not connected. This command is only available in multiplayer.`

**Comment by glx22** [comment]
When running `part` it just returns to main menu I think.
