### ISSUE TITLE
[Crash]: game suddenly crashes when opening Object List

### ISSUE THREAD

**Issue by MontyMontana** [OpenTTD/OpenTTD#12086]
### Version of OpenTTD

openttd-20240211-master-g8d9fa0ea89-linux-generic-amd64

### Steps to reproduce

Create new game with the NewGRF list attached.
When opening the Object List (from Terrain Menu), game crashes.
(Maybe caused by the high number of objects (or subcategories) because of many NewGRF's used.)
Message of json.log: 
    "crash": {
        "reason": "Assertion failed at line 762 of /__w/OpenTTD/OpenTTD/src/widget_type.h: num <= MAX_UVALUE(uint16_t)"
    },
Note: does not happen in 13.4 (screenshot)
### Upload crash files

[crash20240213231158.dmp](https://github.com/OpenTTD/OpenTTD/files/14273173/crash20240213231158.dmp)
[crash20240213231158.json.log](https://github.com/OpenTTD/OpenTTD/files/14273175/crash20240213231158.json.log)
[newgrfs.txt](https://github.com/OpenTTD/OpenTTD/files/14273179/newgrfs.txt)
![image](https://github.com/OpenTTD/OpenTTD/assets/62640458/d17a38a9-fec4-44cf-b078-4ef2e9a2d307)

**Comment by PeterN** [comment]
Congrats on reaching the 64K pixel limit of the matrix widget :)
