### ISSUE TITLE
[Bug]: No longer possible to add tram to road bridges/tunnels or vice versa since #11606

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#12102]
### Version of OpenTTD

Since #11606

### Expected result

It is possible to add tram to road bridges/tunnels or vice versa

### Actual result

It is no longer possible since #11606

### Steps to reproduce

Try to add a tram type to an existing road bridge/tunnel

**Comment by rubidium42** [comment]
Not the same bug, but associated with the same PR:
If there is a tunnel head under a bridge (or a bridge head above a tunnel) then it will start building where it is not supposed to and it will not build beyond the original tunnel/bridge. Contrary to the initial bug, this also affects rail.
![Lisieux Transport, 2035-01-19](https://github.com/OpenTTD/OpenTTD/assets/13785744/f2c69584-5839-4ed0-89a5-e7192f42c5c4)
