### ISSUE TITLE
[Bug]: option "-l" does not work

### ISSUE THREAD

**Issue by rei-artist** [OpenTTD/OpenTTD#12109]
### Version of OpenTTD

14.0 beta3 windows11

### Expected result

Network forwarding of debug logs when the -l option is added.
https://wiki.openttd.org/en/Manual/Command%20line

Since this was the only way to get debug logs in windows until now, I would like to see this functionality restored or another means provided. As it is, it is difficult to debug scripts.

### Actual result

When started with the "-l" option, openttd fails to start.

### Steps to reproduce

1. set up tcp/ip server at 127.0.0.1:8001
2. start "openttd.exe -d script=5 -l 127.0.0.1:8001"

**Comment by rubidium42** [comment]
That functionality was removed as it does not work in many situations, as documented in the changelog. For example when passing `-D` or `-g`.

Am I right to assume that you set this up this way so you can dump the debug output to some file? In that case, there is a small tool called "[convert](https://github.com/OpenTTD/OpenTTD/discussions/10648#discussioncomment-5642457)" that changes a GUI executable to a console executable. After doing this you, you should be able to just do `openttd -d script=5 > script.log`.

**Comment by rei-artist** [comment]
convert.exe solved exactly this problem! I thought this useful tool could be put on the official distribution page. Anyway, thank you very much for sharing the information.

**Comment by rei-artist** [comment]
convert.exe solved exactly this problem! I thought this useful tool could be put on the official distribution page. Anyway, thank you very much for sharing the information.
