### ISSUE TITLE
[Bug]: Most "unbunching" compatibility checks are done only on GUI side

### ISSUE THREAD

**Issue by glx22** [OpenTTD/OpenTTD#12118]
### Version of OpenTTD

master

### Expected result

`Ctrl+Click on roadstop, then Ctrl+Click on depot` should fail like `Ctrl+Click on depot, then Ctrl+Click on roadstop` does.

### Actual result

`Ctrl+Click on roadstop, then Ctrl+Click on depot` doesn't fail
![image](https://github.com/OpenTTD/OpenTTD/assets/2952192/be46b9c1-495d-45c5-ac33-4f34712dea79)

### Steps to reproduce

* Build a depot and a roadstop
* Build a vehicle
* Click on order button (it opens in "Go-To" mode)
* Ctrl+Click on the roadstop
* Ctrl+Click on the depot

**Comment by glx22** [comment]
The main issue is CmdInsertOrder uses `Vehicle::HasUnbunchingOrder()` (which works), but it should also use some kind of `Vehicle::HasConditionalOrder()` and `Vehicle::HasFullLoadOrder()`.

**Comment by 2TallTyler** [comment]
Ah, the checks in #11945 are only in `CmdModifyOrder` because at the time, players could only add an unbunching instruction to an existing order. This changed in #12023, although AIs could always create orders that already have flags. Thus the need to add these checks in `CmdInsertOrder`.
