### ISSUE TITLE
[Bug]: PR#11993 is not properly display CJK currency

### ISSUE THREAD

**Issue by telk5093** [OpenTTD/OpenTTD#12123]
### Version of OpenTTD

14.0-RC1

### Expected result

1. For £10,002,003,405,670,089, it should be ``(₩) 1경 2조 34억 567만 89`` in Korean
2. For £185,000,000, it should be ``(₩) 1억 8500만`` in Korean (for ``{CURRENCY_LONG}`` maybe)

### Actual result

1. It is displayed as ``(₩) 1경 0002조 0034억 0567만 0089``
2. ``(₩) 1억 8500만 0000`` (for ``{CURRENCY_LONG}`` maybe)

### Steps to reproduce

PR #11993 have introduced the non-western number formats which is very thankful for CJK languages.
As I wrote above, however, the implemented shown number format (maybe for ``{CURRENCY_LONG}``) in my language, Korean, is somehow akward.

1. It would be great to bind something like ``0경{NBSP}0조{NBSP}0억{NBSP}0만`` for ``##numberabbreviations`` to omit the leading zeros for each units.
2. It would be great to be able to omit last zeros (as for example 2) for ``{CURRENCY_LONG}``

For now, Korean translation will be going to use western number format until these requested things would be improved.

**Comment by rubidium42** [comment]
Is the following what you are looking for?
![이름 없음의 게임, 2035-01-01](https://github.com/OpenTTD/OpenTTD/assets/13785744/cf98fab6-5b2e-4c94-897d-e858311d5a07)

This is the same screenshot in English, just so you know which numbers were formatted:
![Unnamed, 2035-01-01#1](https://github.com/OpenTTD/OpenTTD/assets/13785744/935e99ed-86e9-4697-969a-e14077368ad7)

I know there's a "problem" with a trailing `{NBSP}` in the string, for which I still need to figure out some solution. Though that might be one of the lesser issues we could work around by just always adding a trailing `{NBSP}` if there's no elegant solution.

**Comment by rubidium42** [comment]
> Yes. Can I check how about £100,001,000? It should be `₩1억 1천`, which omits `만`(10 thousand) units

It's not doing that, and it looks like yet another intricacy of CJK number formatting that I am blissfully unaware of.

I've come to the point that handling this is too much whack-a-mole for trying to get right without an actual understanding what is going on with CJK number formatting. So, I guess the only solution is to just abandon support of CJK numbers implemented by my/someone who has no clue, and revert to the status quo as it was before I attempted this.
