### ISSUE TITLE
[Crash]: CargoDist assertion, date >= edge.LastUpdate()

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#12145]
### Version of OpenTTD

14.0-RC1

### Steps to reproduce

Just playing a vanilla map, when suddenly this assertion triggered in `station_cmd.cpp`, in `DeleteStaleLinks()`:
`assert(TimerGameEconomy::date >= edge.LastUpdate());`

### Upload crash files

[crash20240220222810.json.zip](https://github.com/OpenTTD/OpenTTD/files/14351850/crash20240220222810.json.zip)

**Comment by JGRennison** [comment]
`ClickChangeDateCheat` is shifting the economy dates of various things even when it should be doing nothing in wall clock mode.

**Comment by glx22** [comment]
#12027 might be related (same area)
