### ISSUE TITLE
[Bug]: trees and builds became transparant

### ISSUE THREAD

**Issue by chenjintang-shrimp** [OpenTTD/OpenTTD#12171]
### Version of OpenTTD

13.4 windows 11 22h2

### Expected result

trees and buildings are clear

### Actual result

![image](https://github.com/OpenTTD/OpenTTD/assets/110657724/3b038d08-f990-4384-ae21-5f0de31b611a)
![image](https://github.com/OpenTTD/OpenTTD/assets/110657724/7c4b3ae9-0ff6-4c86-a8c3-85dcaf443325)

### Steps to reproduce

hang the game until the computer sleep
re-logon windows, you will see it

**Comment by PeterN** [comment]
Press 'X' to toggle transparency, or find it under the settings menu.

**Comment by 2TallTyler** [comment]
Did you try toggling transparency? (Menu in the gear drop-down, or press the hotkey X).
