### ISSUE TITLE
[Bug]: Ships are circling in one place.

### ISSUE THREAD

**Issue by rei-artist** [OpenTTD/OpenTTD#12176]
### Version of OpenTTD

14.0 RC1 windows11

### Expected result

Ships reach its destination.

### Actual result

Ships are circling in one place.
![ss2024-02-25 221815](https://github.com/OpenTTD/OpenTTD/assets/74841537/32518d9b-f865-43f9-b97b-ddb7759e5ff5)

### Steps to reproduce

load the attached savegame and go to 880x2449
[Unnamed, 1991-12-04.zip](https://github.com/OpenTTD/OpenTTD/files/14396475/Unnamed.1991-12-04.zip)

**Comment by SamuXarick** [comment]
![Captura de ecrã 2024-02-25 145513](https://github.com/OpenTTD/OpenTTD/assets/43006711/b406f066-98f5-4571-b81d-0feed59577ea)
When the ship enters the region at 54, 153, follow the yellow numbers. The intermediate region given by the high level pf is number 5, it tells the the low level pf to pathfind to the center tile of region 54, 151, forcing the ship to turn back to 55, 153, but...

... when the ship enters the region at 55, 153, follow the cyan numbers. The intermediate region given by the high level pf is number 5, it tells the the low level pf to pathfind to the center tile of region 53, 151, forcing the ship to turn back to 54, 153, repeat...

perhaps a solution would be.... restrict path right off the bat? considering the high level pathfinder gives the exact same path, this would solve the problem

**Comment by Kuhnovic** [comment]
Forcing the low level pathfinder to only use the path provided by the high level pathfinder would indeed fix this problem. But doing so often results in less optimal paths that look a little forced / funny. I went for a different solution in #12181 which keeps some of the freedom to deviate from the high level path. If this still gives issues then path restriction is plan B.
