### ISSUE TITLE
[Crash]: After building a landmark

### ISSUE THREAD

**Issue by Cuddle-sheep** [OpenTTD/OpenTTD#12195]
### Version of OpenTTD

1.13.4

### Steps to reproduce

bought a dutch landmarks:Utrecht landmark then the game crashed

object is 0x0 tile

### Upload crash files

[OpenTTD.zip](https://github.com/OpenTTD/OpenTTD/files/14453375/OpenTTD.zip)

**Comment by James103** [comment]
I was able to reproduce the crash on 667adf7df9738fc9adb388f8be659007d01d1b7d.
[crash20240301200714.zip](https://github.com/OpenTTD/OpenTTD/files/14465485/crash20240301200714.zip)

To reproduce, open the build object window, then select any object class for which objects are available. Then select any object class for which all objects are unavailable (not introduced yet or expired), and try to place an object. For the Dutch Landmarks object set, a starting year of 1950 is required to reproduce the crash.

**Comment by TrueBrain** [comment]
```
 	openttd.exe!BuildObjectWindow::OnPlaceObject(Point pt={...}, StrongType::Typedef<unsigned int,TileIndexTag,StrongType::Compare,StrongType::Integer,StrongType::Compatible<int>,StrongType::Compatible<__int64>> tile={...}) Line 530	C++
 	openttd.exe!PlaceObject() Line 2408	C++
 	openttd.exe!HandleViewportClicked(const Viewport * vp=0x000002aaac4efb60, int x=934, int y=252) Line 2423	C++
 	openttd.exe!MouseLoop(MouseClick click=MC_LEFT, int mousewheel=0) Line 2816	C++
 	openttd.exe!HandleMouseEvents() Line 2947	C++
 	openttd.exe!WndProcGdi(HWND__ * hwnd=0x000000000009042a, unsigned int msg=513, unsigned __int64 wParam=1, __int64 lParam=16516006) Line 445	C++
```
