### ISSUE TITLE
[Bug]: Content Downloading window buttons are inconsistent when using filter

### ISSUE THREAD

**Issue by DefinitelyNotRau117** [OpenTTD/OpenTTD#12196]
### Version of OpenTTD

OpenTTD 20240229 Windows 10

### Expected result

If a query is entered into the search bar in online-content, by clicking on “select uploaded” only those resources that are currently visible are marked. Loading occurs only for selected resources
![изображение](https://github.com/OpenTTD/OpenTTD/assets/115672237/2636ea5b-3825-4f79-a9ce-e1a9db7c2f82)
![изображение](https://github.com/OpenTTD/OpenTTD/assets/115672237/463e5681-0f06-441f-9777-b1cbfd27be6f)

### Actual result

The selection in the window is displayed correctly, the amount of content to download is also displayed correctly
![изображение](https://github.com/OpenTTD/OpenTTD/assets/115672237/2636ea5b-3825-4f79-a9ce-e1a9db7c2f82)
But after clicking on “download selected”, all possible updates are downloaded, even those that are not listed in a specific search window.
![изображение](https://github.com/OpenTTD/OpenTTD/assets/115672237/0f332369-71d2-480c-accd-dfbdd5a4a743)

https://github.com/OpenTTD/OpenTTD/assets/115672237/a387684d-6456-4e5c-a97d-c125f53b0367

it will work correctly only if you manually select all new versions

https://github.com/OpenTTD/OpenTTD/assets/115672237/2a7ccce9-1abd-414b-8719-32c5f3f5767b

### Steps to reproduce

1. Have several non-updated sets from online-content
2. Open online-content, click on “select updated”, remember the size of the downloaded content, then unselect all
3. Enter the name of one of the non-updated sets into the search box
5. Click “select updated”, remember the size of the downloaded content, click "download selected"
7. The download of »» all available updates will begin, the download size will be equal to point 2

**Comment by TrueBrain** [comment]
"Select upgrades" selects all content, no matter if you filtered. So that part is working as intended (whether it is wanted is a different story, but at least it is not a bug).

What is a bug however, is that the "total download size" only counts that what is being filtered. That is a bit odd. Makes me wonder if that happens in general, or if that only happens when using "select upgrades".

**Comment by TrueBrain** [comment]
Yeah, had to check myself, but indeed: "Total download size" is only showing the "total" download size of the current filter; not the actual total download size, and that is the bug you are observing.
