### ISSUE TITLE
[Bug]: Issue in NewGRFs

### ISSUE THREAD

**Issue by 17yiuk** [OpenTTD/OpenTTD#12215]
### Version of OpenTTD

1.12, iPadOS 17.3.1

### Expected result

Able to see a list of NewGRFs available when clicking “search online content”.

### Actual result

No NewGRFs can be seen when clicking on the check online content.

### Steps to reproduce

1. Click on NewGRFs settings.
2. Click on check online content.
3. No NewGRFs can be seen.

**Comment by PeterN** [comment]
OpenTTD on Apple devices which don't run macOS is nothing to do with us.
