### ISSUE TITLE
[Bug]: Not able to see the tutorial

### ISSUE THREAD

**Issue by 17yiuk** [OpenTTD/OpenTTD#12216]
### Version of OpenTTD

1.12, iPadOS 17.3.1

### Expected result

Open a new page when clicking on the details of tutorial.

### Actual result

When clicking on tutorial and then a tab, nothing pops up.

### Steps to reproduce

1. Click on Tutorial.
2. Click any of the buttons shown, eg Cargo types.
3. No new pages or tabs pops up.

**Comment by PeterN** [comment]
OpenTTD on Apple devices which don't run macOS is nothing to do with us.

**Comment by 17yiuk** [comment]
Dear Peter,

Thank you for your email.

Where can I report the bugs/crashes for iPadOS? Thank you for your help.

Kind regards,
Kenelm

**Comment by 2TallTyler** [comment]
Unfortunately, we don't know how to contact the person who put it on the App Store, and it may be in violation of Apple's terms of service to be there. See #10832.
