### ISSUE TITLE
[Bug]: Inconsistent string build-up depot orders

### ISSUE THREAD

**Issue by Transportman** [OpenTTD/OpenTTD#12268]
### Version of OpenTTD

14.0-RC1 Windows 10

### Expected result

The various strings for depot orders are consistent with each other (same formatting, same lowercase/uppercase) and other order modifiers. Quick look, I would say between brackets at the end of the order string, with first letter uppercase.

### Actual result

The strings for depot orders are inconsistent:
- 'Service' is set at the start of the order string
- 'Stop' is set as '(Stop)' with capital S at the end of the order string
- 'Unbunch' is set as '(wait to unbunch)' with lowercase w at the end of the order String

### Steps to reproduce
Screenshot taken with English (US), but same for UK.
![image](https://github.com/OpenTTD/OpenTTD/assets/47077527/76f87e37-dcab-41be-9ca7-0d07f368cfd8)

**Comment by 2TallTyler** [comment]
In my view, `Service` is at the beginning of the string because it takes the place of `Go to` or `Go non-stop to`. If the vehicle does not need service, it doesn't go to the depot. 🙂 

I've opened #12375 to fix the capitalization of `(wait to unbunch)`.
