### ISSUE TITLE
[Bug]: Inconsistent default action in vehicle group dropdown

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#12283]
### Version of OpenTTD

14.0-RC1

### Expected result

Some dropdowns in OpenTTD have a selected value which is selected when the dropdown is opened. This contains the current value of the selection.

### Actual result

The group action dropdown has `Replace vehicles` highlighted. This is not a value, but an action, and as @PeterN points out in the comments below, should not be highlighted at all.

![highlight-real](https://github.com/OpenTTD/OpenTTD/assets/55058389/fa5433cf-b34d-4108-bf2b-f6e85f397dd7)

### Steps to reproduce

1. Create a group of vehicles.
2. Open the group's action dropdown and notice that an action is selected as the current value.

**Comment by PeterN** [comment]
A default value should only be set if

1) that's the current value
or
2) that's the action that will be performed if you don't select an option.

So I think you have this backwards, and the dropdown in the first screenshot is wrong.

**Comment by DefinitelyNotRau117** [comment]
Hmm, on the other hand, why not add the ability to replace vehicles for a specific group of shared orders? This can help with "quickly changing a couple of trains" without having to create a new group.

**Comment by 2TallTyler** [comment]
Shared order groups are not real groups. I'm not sure how much work is required to make them act like full groups, but that suggestion is definitely not in-scope for this bug report which relates only to dropdown menus.
