### ISSUE TITLE
[Bug]: #11719 changes the availablity of some vehicles for some GRFs

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#12302]
### Version of OpenTTD

Since #11719 / 2fd9096

### Expected result

Availability of NewGRF vehicles is the same as before

### Actual result

In DACH 0.3.2 (on Bananas), some locomotives which do not carry cargo are now marked as unavailable via the `ei->climates = 0` path in `CalculateRefitMasks`.
It appears that this is due to the vehicle definition not explicitly overriding the cargo type for locomotives which do not carry cargo. (I cannot comment on whether this makes the GRF correct or incorrect).
An example of this is "DB BR 143", engine ID 40.

### Steps to reproduce

See available vehicles for DACH 0.3.2 from bananas before and after #11719.

**Comment by PeterN** [comment]
I guess if capacity is 0 then we could be lenient and try picking the first available cargo (normally passengers) instead of just disabling it.
