### ISSUE TITLE
[Bug]: Main menu does not appear in fullscreen with multiple monitors

### ISSUE THREAD

**Issue by MrC08** [OpenTTD/OpenTTD#12311]
### Version of OpenTTD

1.13.4, Ubuntu 20.04

### Expected result

When opening the game, a video of gameplay is shown in the background and a menu appears allowing you to start a game, modify settings, etc.

### Actual result

![image](https://github.com/OpenTTD/OpenTTD/assets/88736768/468d9f12-17d9-408a-891c-719091707676)
The background video plays (and sound works) however no actual menu can be found. If fullscreen is exited, however, the menu will show up as expected. It should also be noted that the game window always appears in my rightmost display, and if I move the fullscreen window to other displays it does not fix the issue.

### Steps to reproduce

1. Have your primary display be between two non-primary displays
![image](https://github.com/OpenTTD/OpenTTD/assets/88736768/8dfc00b3-5e22-42a7-ac46-a4eea250e086)
(The orange highlighted display is my primary display)

2. Open the game in fullscreen. The game window should appear in the rightmost monitor, but without any main menu window.

**Comment by TrueBrain** [comment]
Please try 14.0-RC2, and let us know if that changes anything.
