### ISSUE TITLE
[Bug]: 32bpp-sse2 blitter is broken in debug build

### ISSUE THREAD

**Issue by ldpl** [OpenTTD/OpenTTD#12319]
### Version of OpenTTD

master(0cff40dd19a52ebd1b2435991dab9ebfdacbcec1), Ubuntu 22.04.4 LTS
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Only affects debug build

### Expected result

Correct rendering.

### Actual result

![Screenshot from 2024-03-17 02-49-55](https://github.com/OpenTTD/OpenTTD/assets/413570/3ce31e68-7c12-4059-b937-33810aea5bff)

### Steps to reproduce

Run `./openttd -b 32bpp-sse2`

**Comment by frosch123** [comment]
This was broken by #11695:
* ``32bpp_sse_func.hpp`` is not a real header, but an inline file.
* It is compiled multiple times with different defines for ``SSE_VERSION``.
* #11695 removes some ``static``, so the function definitions conflict during linking.
