### ISSUE TITLE
[Bug]: Beginner Tutorial scenario crashes in v14

### ISSUE THREAD

**Issue by MrSkinny** [OpenTTD/OpenTTD#12316]
### Version of OpenTTD

14 RC2

### Expected result

Expect: Completion of tutorial without incident.

### Actual result

See attached. 
![openttd-bug](https://github.com/OpenTTD/OpenTTD/assets/3757471/c161c39d-cd14-42ef-85b8-86302d777b36)

### Steps to reproduce

1. Load Scenario
2. Beginner Tutorial (included in vanilla)
3. Hit "Continue" on info screens until start of Chapter 1

**Comment by glx22** [comment]
Windows changed, a game script using window highlighting is only guaranteed to work in a given version.

It's author needs to update it.

**Comment by MrSkinny** [comment]
> It's author needs to update it.

Got it... I don't know if the script author still contributes. Just wanted to warn as I assume the tutorial scenario is an introduction to the game for many players. It is referenced in the [official manual](https://wiki.openttd.org/en/Manual/Tutorial/In-game%20tutorial) as well.

**Comment by glx22** [comment]
Oh it's 11 years old, not bad it still worked in 13.4 :)

**Comment by glx22** [comment]
Actually after some more checking, it seems we have a bug in our build scripts.
