### ISSUE TITLE
[Bug]: House cargo acceptnance changes when loading the game in newer OpenTTD version

### ISSUE THREAD

**Issue by ldpl** [OpenTTD/OpenTTD#12327]
### Version of OpenTTD

14.0-RC2, master(af1bd43b3048f925e1c82ce11c050920ab9b06c5)

### Expected result

Cargo acceptance of houses stays the same when loading the save from 13.4

### Actual result

Houses lose Vehicle acceptance.
![Screenshot from 2024-03-17 17-02-43](https://github.com/OpenTTD/OpenTTD/assets/413570/252a4e65-6b4b-4a95-8a49-4be770e132e7)

### Steps to reproduce

1. Load the attached save game
2. Check house acceptance with ? tool.

Save file: [McBorer_Development_1957-06-01v13.zip](https://github.com/OpenTTD/OpenTTD/files/14627070/McBorer_Development_1957-06-01v13.zip) (provided by McBorer on Master Hellish discord)

**Comment by PeterN** [comment]
TTRS's cargo translation table contains only PASS, PETR, MAIL, TOUR, FOOD and GOOD, so I think it was a bug that it accepted Vehicles before.

**Comment by PeterN** [comment]
That particular building is grf-local house type 1B. It overrides default house type 0E, and does not set any cargo types.

The cargo types of house type 0E are PASS, MAIL and GOOD.

FIRS does not have GOOD so that cargo type is invalid. Older versions ignore that is it invalid and would use whatever was in the same slot that GOOD normally occupies.

**Comment by ldpl** [comment]
Makes sense. It kind of sucks that it means acceptance gets changed in a confusing way but I don't see any better solution than just leaving it be. At least in the case of MH challenge it's not that big of a deal, just means players will need to fund vehicle distributors next to old stations.

**Comment by 2TallTyler** [comment]
I agree with Peter. Inheriting cargo acceptance using the cargo slot and not the label was technically allowed but something of an undefined behavior.

I don't see a nice way to support the old bug, and like you say FIRS doesn't expect houses to accept vehicles so it provides its own destination industry.
