### ISSUE TITLE
[Bug]: Default custom currency not translatable

### ISSUE THREAD

**Issue by eriksorngard** [OpenTTD/OpenTTD#12324]
### Version of OpenTTD

14.0-RC1

### Expected result

When changing currency units to "Custom..." while using a different language than English (UK) I expect to get a default suffix translated from "credits".

### Actual result

The "credits" string does not appear in the Web Translator, and instead the custom default currency presented in the UI appears to be hard coded, possibly in the file "currency_settings.ini"

### Steps to reproduce

1. In Game Options select a different language than English (UK)
2. Select the currency unit equivalent of "Custom..."
3. Notice the suffix string is "credits" regardless of the selected language; verified with Danish, German, Norwegian Bokmål and Swedish
4. Search for the string "credits in Web Translator, and get no matches

**Comment by TrueBrain** [comment]
The default "credits" is stored in the settings file on first start. This is not changed when changing languages, and is meant as placeholder for: if you want a custom currency, this is the place to fill in what you want there. It is not so much meant to actually use, or to translate.

Fixing this would be .. tricky. As it would mean we can't store the default in the ini-file, would need to figure out a way to set a default when a game is started, based on a translation. A huge hassle.

**Comment by 2TallTyler** [comment]
In my opinion, this is a "won't fix" problem for the reasons explained by TrueBrain. If someone disagrees, feel free to re-open. 🙂
