### ISSUE TITLE
[Bug]: Fix inconsistent punctuation in English

### ISSUE THREAD

**Issue by pasantoro** [OpenTTD/OpenTTD#12342]
### Version of OpenTTD

nightly (20240320), Linux Mint 21.3

### Expected result

Inconsistent missing ellipsis (punctuation) at the end of the string beginning with
:{WHITE}Can't
of some variable names that begin with
STR_ERROR_

### Actual result

Should be made consistent by taking the majority 'choice', i.e. with ellipsis at the end.

### Steps to reproduce

Update the strings (2 out of 122) appropriately:
STR_ERROR_CAN_T_GENERATE_TOWN
STR_ERROR_CAN_T_START_AND_END_ON

I am only a translator and don't know how to do a PR.

**Comment by frosch123** [comment]
I confirm ``STR_ERROR_CAN_T_GENERATE_TOWN``: It is the first part of a two-part error-message, so it should end in ``...``.

``STR_ERROR_CAN_T_START_AND_END_ON`` on the other hand is not, it should not start or end with ``...``.

**Comment by pasantoro** [comment]
Thank you very much for your time and kind help.

**Comment by 2TallTyler** [comment]
Thanks for the report!
