### ISSUE TITLE
[Bug]: Industry Chain Window - Decreased responsiveness/area of buttons (cargo names)

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#12368]
### Version of OpenTTD

14.0-RC1/RC2

### Expected result

It should work as in version 13, where the surface of the buttons is the same as the surface of the cargo names.
![Industry Chains window - 13 4](https://github.com/OpenTTD/OpenTTD/assets/67662046/c92435f2-1e5b-40d1-a89b-fdcc446d1391)

### Actual result

The surface of the buttons is almost half the size of the cargo names, which means that when you press the inscription, there is often no appropriate response, i.e. opening the diagram for the selected cargo. The lack of reaction concerns the lower part of the inscription marked with a red frame.
The problem affects every font scale.
![Industry Chains window - 14 0-RC2](https://github.com/OpenTTD/OpenTTD/assets/67662046/37d3ca8d-a881-4b00-abb6-95a252728c15)

### Steps to reproduce

Open the window, press the buttons

**Comment by PeterN** [comment]
I remember looking at this, there's some offset that is or isn't applied, as you can click above the text and it still registers.
