### ISSUE TITLE
[Bug]: Company inauguration date should use calendar year in wallclock mode

### ISSUE THREAD

**Issue by zephyris** [OpenTTD/OpenTTD#12365]
### Version of OpenTTD

14.0-RC3

### Expected result

Company inauguration date, similar to eg. vehicle design dates, should probably always be displayed as calendar year.

### Actual result

![image](https://github.com/OpenTTD/OpenTTD/assets/2762690/e1a2a28e-637e-450b-a4b3-4a5616114829)

In wallclock mode, inauguration time is in minutes(?) with no units, and looks quite weird.

### Steps to reproduce

1. Set the time setting to wallclock mode
2. Start a new game and look at the company information window

**Comment by frosch123** [comment]
Calendar year is of little use, if calendar time is stopped.
I think it would make sense to display both:
> 1955 (period 1)

**Comment by 2TallTyler** [comment]
Both would probably be the best player experience, yes. The calendar year of inauguration is not stored in the company (it was converted to economy year, which in calendar timekeeping mode is kept synced with the calendar), so it will need to be added, similar to what we did with #11124.

**Comment by MaderDash** [comment]
Bump, is this issue now closed?

**Comment by 2TallTyler** [comment]
No, it is waiting on #12798 to be completed and merged.
