### ISSUE TITLE
[Bug]: Building station on slopes is not posible.

### ISSUE THREAD

**Issue by McBorer** [OpenTTD/OpenTTD#12387]
### Version of OpenTTD

v 14RC3, Windows

### Expected result

Station supposed to be build on slope only because it got underground entry.

### Actual result

With 'New Stations' grf there isn't possible to build Bamberg station on slope as it supposed to be and it worked in v13. Instead of that is possible to build on flat surface.

### Steps to reproduce

[Temp.zip](https://github.com/OpenTTD/OpenTTD/files/14773167/Temp.zip)

**Comment by PeterN** [comment]
Sounds like this is should be resolved by #12369?

**Comment by michicc** [comment]
Yes, this is one of the issues that that PR would solve.
