### ISSUE TITLE
[Bug]: Sign list - strange behavior, half of the links are unavailable

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#12393]
### Version of OpenTTD

14.0-RC1

### Expected result

It should work as in version 13 - clicking on an inscription on the list, the main view changes its position to the place of this inscription

### Actual result

I noticed strange behavior in one of the save in the Title Screen 14 competition.
Once you click on an item in the list, nothing happens.
Other times, by clicking on the same sign (after selecting another one), the main view is moved to the adjacent sign above or below in the list.
Ca. half of the links are unavailable.

I didn't see this problem in other saves.

### Steps to reproduce

Download and open the geme created by ErorrTNT in the competition theme ([here](https://github.com/OpenTTD/OpenTTD/discussions/12282#discussioncomment-8760656)).
Open the list of signs and try to move to each of them in turn, from the first to the last and back.

**Comment by JGRennison** [comment]
Some tiles have more than one sign on them, therefore the sign underneath is only partially visible.
