### ISSUE TITLE
[Bug]: Passengers are not accepted by all industrial factories

### ISSUE THREAD

**Issue by wett1988** [OpenTTD/OpenTTD#12553]
### Version of OpenTTD

14.0, Windows 10

### Expected result

I've noticed that since some version of the game it's been possible to take passengers to industrialized factories, but for some reason it only works for the steel mill.

### Actual result

If you try to place a bus stop near other industries - factory, refinery, power plants, mines, etc., it won't accept passagers. 

![scr3](https://github.com/OpenTTD/OpenTTD/assets/12225673/0293b567-b17a-40a1-85ec-6c3b68197cfe)

![scr4](https://github.com/OpenTTD/OpenTTD/assets/12225673/df4ed781-d50e-4ded-b899-6f5f10a41907)

But if you place it near a steel mill, it does.

![scr1](https://github.com/OpenTTD/OpenTTD/assets/12225673/076b661c-eb7b-4b2d-9729-4280aae7aad5)

![scr2](https://github.com/OpenTTD/OpenTTD/assets/12225673/a146aeb1-60e6-4c91-858c-d378be494374)

![scr5](https://github.com/OpenTTD/OpenTTD/assets/12225673/a15d27f6-bcd8-4c4e-ba84-f440f40d8aab)

It seems logical to me that all industries should be able to take passengers from the city.

Is this some kind of mistake or was it intended for some balance reasons? 

If you add such an opportunity to all production it would give the players and new game opportunities and would give to realism, because it is unclear how people from the cities now get to their jobs :)

### Steps to reproduce

If you try to place a bus stop near other industries - factory, refinery, power plants, mines, etc., it won't accept passengers. But if you place it near a steel mill, it does.

**Comment by PeterN** [comment]
![image](https://github.com/OpenTTD/OpenTTD/assets/639850/0ce4adb3-fb68-4c74-9999-dc6ddd8f3b03)

This is nothing new at all, it's a how industries behaved in original TTD.

**Comment by glx22** [comment]
Vanilla industries don't accept passengers (oil rigs being an exception), see https://wiki.openttd.org/en/Manual/Industries.
But some industry tiles may have an 1/8 acceptance for passengers, and when a station has a total of at least 8/8 acceptance for passengers it will accept them.

**Comment by TheMowgliMan** [comment]
Are you playing with a NewGRF? The default industry set should not accept
passengers at any industries except for the Oil Rig.

**Comment by wett1988** [comment]
> Vanilla industries don't accept passengers (oil rigs being an exception), see https://wiki.openttd.org/en/Manual/Industries.
> But some industry tiles may have an 1/8 acceptance for passengers, and when a station has a total of at least 8/8 acceptance for passengers it will accept them.

Stock version from Steam, without any modes

**Comment by PeterN** [comment]
@TheMowgliMan Also wrong. Industry *tiles* can accept, fully or partially, passengers, or any other cargo. This is separate from the input and output cargo types of the industry as a whole.

**Comment by TheMowgliMan** [comment]
> @TheMowgliMan Also wrong. Industry _tiles_ can accept, fully or partially, passengers, or any other cargo. This is separate from the input and output cargo types of the industry as a whole.

Interesting. I've known that some tiles may not accept/produce the industry's cargo(s), as it can be seen in gameplay with some default industries (I seem to recall Coal Mines having this effect), but I did not know this.

**Comment by wett1988** [comment]
> This is nothing new at all, no changes to acceptance of default industries have been made, it's how industries behaved in original TTD.

Yes, you are right. I don't now [that](https://wiki.openttd.org/en/Manual/Base%20Set/Cargos/Passengers)

> They are accepted in towns, oil rigs, Steel Mills, and at Company Headquarters.
