### ISSUE TITLE
[Crash]: Assertion failed at line 114 of D:\\a\\OpenTTD\\OpenTTD\\src\\core\\pool_type.hpp: index < this->first_unused

### ISSUE THREAD

**Issue by fldlqu** [OpenTTD/OpenTTD#12551]
### Version of OpenTTD

Nightly build 20240421,Windows

### Steps to reproduce

I don't know WHAT HAPPENED

### Upload crash files

[OpenTTD.zip](https://github.com/OpenTTD/OpenTTD/files/15050886/OpenTTD.zip)

**Comment by PeterN** [comment]
Do you have the normal savegame from before the crash too?

**Comment by JGRennison** [comment]
[Issue 12551, 1990-04-22.sav.zip](https://github.com/OpenTTD/OpenTTD/files/15051638/Issue.12551.1990-04-22.sav.zip)
Removing the road stop at tile 41 x 28 can be used to reproduce the issue.

The use of GetOrderStationLocation in RemoveRoadStop clears last_station_visited which must remain valid for a vehicle which is loading.

**Comment by 12306ylg** [comment]
> Do you have the normal savegame from before the crash too?

no

**Comment by PeterN** [comment]
Fixed by #12552 , but I messed up the tagging...
