### ISSUE TITLE
[Bug]: Unbunch breaks CargoDist

### ISSUE THREAD

**Issue by TheMowgliMan** [OpenTTD/OpenTTD#12562]
### Version of OpenTTD

14.0

### Expected result

Cargodist works with unbunching.

### Actual result

Cargodist passengers at stations are "via any station, to any station," using Asymmetric routing.

### Steps to reproduce

1. Play a game with cargodist and unbunching vehicles
2. Observe CargoDist failing

**Comment by TheMowgliMan** [comment]
As usual, OpenTTD fixes itself after I report a bug 🙄 It had gotten to over 5,000 passengers at the station reporting that before it did, however. it seems to be broken at first and fix itself over time, so I will leave the ticket open.

**Comment by 2TallTyler** [comment]
Can you provide a savegame where you can reproduce this?

**Comment by 2TallTyler** [comment]
Closing this since the author has not responded and this is likely a misunderstanding. If anyone can provide a savegame reproducing the problem, I'd be happy to reopen and investigate further. 🙂
