### ISSUE TITLE
[Crash]: Unhandled exception in ottd:game thread: invalid stoul argument

### ISSUE THREAD

**Issue by KamikaziF** [OpenTTD/OpenTTD#12584]
### Version of OpenTTD

1.14.0, Windows 11

### Steps to reproduce

This always happens when on startup

![image](https://github.com/OpenTTD/OpenTTD/assets/38037802/41849b41-88c6-4dc0-baf5-12346469f4d2)

### Upload crash files

[crash20240427170211.json.log](https://github.com/OpenTTD/OpenTTD/files/15139070/crash20240427170211.json.log)
[crash20240427170211.dmp](https://github.com/OpenTTD/OpenTTD/files/15139074/crash20240427170211.dmp)

**Comment by glx22** [comment]
The only place it could happen is when scanning the tar files.

**Comment by PeterN** [comment]
The modern way is `std::from_chars`, which has any error in the return value instead of an exception.
