### ISSUE TITLE
[Bug]: No descriptive error when hostile takeover fails due to vehicle limit

### ISSUE THREAD

**Issue by davewthompson** [OpenTTD/OpenTTD#12594]
### Version of OpenTTD

14.0

### Expected result

You can execute a hostile takeover of the company

### Actual result

A message saying "Can't buy company..." appears, with no additional information.

### Steps to reproduce

1. Load attached savegame.
2. Try and execute a hostile takeover of the "AAAHogEx" AI
3. You will see a message saying the cost will be around £12m but on attempting to execute the takeover you just see a message labelled "Can't buy company..."
[Wutborough Market Transport, 1963-05-28.sav.zip](https://github.com/OpenTTD/OpenTTD/files/15153940/Wutborough.Market.Transport.1963-05-28.sav.zip)

**Comment by James103** [comment]
Can reproduce on b852a3f4 on Windows 10, 64-bit.

This appears to be related to vehicle limits; increasing the maximum number of vehicles per company for each of the four vehicle types allows the hostile takeover to succeed.

As far as I know, the full error message before this regression started was "Can't buy company... Too many vehicles in game"

**Comment by davewthompson** [comment]
Thank you for looking, @James103 ! You're correct - if I increase the vehicle count in the Settings dialog then the takeover works.

Gotta love that comment, too: `/* Disable taking over when not allowed. */ `!
