### ISSUE TITLE
[Crash]: Out of Memory

### ISSUE THREAD

**Issue by Oberdorfer0** [OpenTTD/OpenTTD#12601]
### Version of OpenTTD

OpenTTD 14, Windows 11 Steam

### Steps to reproduce

I had a DVD burner running at the time and it may have caused the crash.  DVD crashed too.  Never had a crash before.  I've been testing NewGrf groups, had not played this game very long.
I've been playing since it first came out, back in the 80's?  Love what has been done to make it so much better!

### Upload crash files

[New Compressed (zipped) Folder.zip](https://github.com/OpenTTD/OpenTTD/files/15171793/New.Compressed.zipped.Folder.zip)

**Comment by TrueBrain** [comment]
Thank you for your report!

Sadly, there is not much we can do about these cases. Your computer literally ran out of memory, while trying to allocate 4 MiB of memory. This is an unrecoverable event, and the only solution is to crash.
As you noticed, your DVD burner software did too, most likely for the same reason. Most likely they were contesting each other for memory, and both draw the short stick.

OpenTTD normally uses a very low amount of memory, but the more NewGRFs you add, especially 32bpp sets, the more memory is requires. Something to keep in mind.
Another common reason for these kind of errors is a browser with many active tabs. These can be very memory hungry.

Either way, nothing we can fix on our end, except to give you a bit of context. Hope it helps!

> I've been playing since it first came out, back in the 80's? Love what has been done to make it so much better!

Thank you! Happy you enjoy the game :)

**Comment by PeterN** [comment]
If this happens regularly, you can try limiting the zoom in level from the default 4x down to 2x (or even "normal") via Settings which may help (but might not):

![image](https://github.com/OpenTTD/OpenTTD/assets/639850/b61e9b81-a613-4228-b5db-2e4a1ed3dc78)

**Comment by Oberdorfer0** [comment]
I only had the game, and the DVD burner going.  I closed both, restarted
the game, loaded the last autosave and resumed the game without a hitch.
Many years ago, I bought the game.  I played one game for almost two
years.  Everything took longer, it was a very small computer compared to
today.  I really appreciate all the improvements!
Thanks again!
