### ISSUE TITLE
[Bug]: No sound content installed

### ISSUE THREAD

**Issue by ghost** [OpenTTD/OpenTTD#12626]
### Version of OpenTTD

Windows 10

### Expected result

I don't have the sound from the original game, how do I install the sound?

### Actual result

I don't have the sound from the original game, how do I install the sound?

### Steps to reproduce

![image](https://github.com/OpenTTD/OpenTTD/assets/168972670/33cb967d-9a01-4004-a685-7a4be5a34c28)

**Comment by telk5093** [comment]
Download ``OpenSFX`` from [Online Contents Download] menu

**Comment by 2TallTyler** [comment]
@santisuper Were you able to download new sounds? If so, please close this ticket, otherwise let us know if you need more help. 🙂

**Comment by santisuper** [comment]
> e

yes thanks

**Comment by santisuper** [comment]
> Baixar `OpenSFX` no menu [Download de Conteúdo Online]

Thanks bro
