### ISSUE TITLE
[Bug]: 14.1 release is not marked as 14.1 in CMakeLists.txt

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/OpenTTD#12633]
### Version of OpenTTD

All

### Expected result

To bump the version upon release (and not just the changelog ;) ).

### Actual result

The version wasn't bumped.

### Steps to reproduce

https://github.com/OpenTTD/OpenTTD/blob/release/14/CMakeLists.txt#L8

That should read 14.1, and should be bumped just before release. Possibly this requires updating the docs, to reflect that requirement.

Nothing is actually broken as such, it just means the client identifies as a 14.0 to the content service. Means nobody can make GRFs that are "14.1 or higher".

**Comment by 2TallTyler** [comment]
#12634 clarifies the docs so this shouldn't happen again. 🙂

**Comment by TrueBrain** [comment]
Documentation is always a good mitigation of any problem ;) closing, as we are not going to release 14.2 to address just this :P

**Comment by orudge** [comment]
For information, this is important for the Windows Store build (as the Windows Store won't allow you to upload a package that has the same major.minor.revision version number as an existing package, somewhat unhelpfully). I'll fix the Windows Store package manually and get it uploaded shortly.
