### ISSUE TITLE
[Crash]: Crash after kicking spectator

### ISSUE THREAD

**Issue by wensimehrp** [OpenTTD/OpenTTD#12655]
### Version of OpenTTD

20240510-master-ga5c2543efc, Windows 11

### Steps to reproduce

1. Start a new server
2. let another client join the server and then join or found a new company
3. kick the player
![image](https://github.com/OpenTTD/OpenTTD/assets/145064583/8a15b119-fdf9-409d-a118-ac0bb25b144c)
4. notice "spectators" is kickable and kick spectators
![image](https://github.com/OpenTTD/OpenTTD/assets/145064583/803f816a-0613-458a-b53b-e709be4edd57)
5. Crash!

### Upload crash files

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/15281704/crash.zip)

**Comment by rubidium42** [comment]
Also reproducible in 14.1.
