### ISSUE TITLE
Paper mill set to accept wrong cargo[Bug]: 

### ISSUE THREAD

**Issue by Budgie2021** [OpenTTD/OpenTTD#12706]
### Version of OpenTTD

14

### Expected result

Paper mill cargo is set to accept "wood" where as it should be set to accept "Wood Products"

### Actual result

no production

### Steps to reproduce

Play the game!

**Comment by andythenorth** [comment]
Thanks for the report.

However the cargo in OpenTTD is "Wood".  

"Wood Products" is not an OpenTTD cargo 😃 

[Is there ](https://wiki.openttd.org/en/Manual/Base%20Set/Cargos/Wood)

**Comment by Budgie2021** [comment]
My error .....this must be a ECS mod error ? Although the error ONLY started with version 14.

**Comment by Budgie2021** [comment]
True this must be a ECS mod error that only started with release 14.

**Comment by PeterN** [comment]
You should be using 14.1 instead of 14.0

The industry accepts Wood Products and one industry tile accepts Wood Products, which is the same as in 13.x

In 14.0 there is indeed a bug, the industry accepts Wood Products and one industry tile accepts Wood Products, but the other tiles accept Wood.

**Comment by Budgie2021** [comment]
Thank You Peter.   I've been playing OpenTTD for decades and owned the
Original TTD.

Shares
If you have any pull with the development team. Ask them to PLEASE re-
allow the option to buy shares in AI firms.

The reason is young people may view this as a competition game which they
must win , however I am sure many of us are much more interested in casual
play, crafting vast transportation empires for the pure joy of creation and
the AI is nothing but a nuisance and it is also fun to take control of an
AI firm and spend an hour or so cleaning up their mess.

I actually use version 13 due to this change.

Shutdown

Also having an  industry shutdown just when you have spent an hour setting
up a route to it is  a major pain in the butt.

ANY industry on this planet in the real world would have a new lease on
life if a firm was rushing to provide needed transport.

Shutdown should be an option although I am aware that this stupid industry
timed shutdown  may be beyond the teams ability to change.

Anyway
Regards Jim

**Comment by Eddi-z** [comment]
None of that belongs into this issue, but since we're already here

> the AI is nothing but a nuisance and it is also fun to take control of an AI firm and spend an hour or so cleaning up their mess.

You can still do this, we introduced a "hostile takeover" feature as a replacement for exactly this purpose.

> Also having an industry shutdown just when you have spent an hour setting up a route to it is a major pain in the butt.

Industry shutdown is in full control of the NewGRF. So if you don't want it, you can switch to a NewGRF which has this option, or you can edit the NewGRF yourself.
