### ISSUE TITLE
[Bug]: Chinese, Japanese, Korean language display is incorrect.

### ISSUE THREAD

**Issue by fldlqu** [OpenTTD/OpenTTD#12738]
### Version of OpenTTD

Nightly build 20240531,Windows

### Expected result

Correct display Chinese, Japanese, Korean

### Actual result

Chinese(Simplified)
![image](https://github.com/OpenTTD/OpenTTD/assets/89052130/03733247-a62d-4238-bfb4-3703d6b8e6ea)

### Steps to reproduce

GameOpitons->General->Language->Switch to Chinese or Japanese or Korean

**Comment by James103** [comment]
Can confirm. On my end, this also affects (at least) Arabic, Hebrew, Thai, Tamil, and Vietnamese.
The "Use traditional sprite font" setting affects reproducibility, with some languages having this issue with it on, some only having this issue with the setting off, and some languages having this issue regardless of the setting value.

**Comment by WenSimEHRP** [comment]
@12306ylg 
你需要自己设置字体，用~键打开控制台然后输入
```
font 大小 某字体 0 aa
```
大小可以是 small medium large mono，最好都设置一遍；字体可以选用“微软雅黑”

This could be fixed if you set your own font. Open the console via the ~ key and type:
```
font <size> <fontname> 0 aa
```
Where size could be medium, small, large, or mono, and fontname could be any font you prefer e.g. Microsoft YaHei.
