### ISSUE TITLE
[Bug]: Default font size has increased by 2px since #12641

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#12735]
### Version of OpenTTD

Since https://github.com/OpenTTD/OpenTTD/pull/12641 on Windows 10, 64-bit (via Steam)

### Expected result

The default font size for the OpenTTD font series when "Use traditional sprite font" is off should match the default font size for the different sprite fonts.
```
medium font:
Currently active: "OpenTTD Sans", size 10
Requested: "", size 0
small font:
Currently active: "OpenTTD Small", size 6
Requested: "", size 0
large font:
Currently active: "OpenTTD Serif", size 18
Requested: "", size 0
mono font:
Currently active: "sprite", size 10
Requested: "", size 0
```

### Actual result

The default font size for the OpenTTD font series when "Use traditional sprite font" is 2 points greater than what it was in 14.1, where it was the same size as the sprite font.

This can cause readability issues with anti-aliasing off, despite the larger print and especially at 1x interface scale.

<details>

<summary> <code>font</code> output and screenshots on different versions </summary>

"Use traditional sprite font" on as of nightly 2024-05-29:
```
medium font:
Currently active: "sprite", size 10
Requested: "", size 0
small font:
Currently active: "sprite", size 6
Requested: "", size 0
large font:
Currently active: "sprite", size 18
Requested: "", size 0
mono font:
Currently active: "sprite", size 10
Requested: "", size 0
```
![image](https://github.com/OpenTTD/OpenTTD/assets/37945304/b8a80668-35b8-4043-a8b5-22c011f336af)

"Use traditional sprite font" off as of nightly 2024-05-29:
```
medium font:
Currently active: "OpenTTD Sans", size 12
Requested: "", size 0
small font:
Currently active: "OpenTTD Small", size 8
Requested: "", size 0
large font:
Currently active: "OpenTTD Serif", size 20
Requested: "", size 0
mono font:
Currently active: "sprite", size 10
Requested: "", size 0
```
![image](https://github.com/OpenTTD/OpenTTD/assets/37945304/947cbbb2-1568-4c09-94c2-2882967dbb42)

"Use traditional sprite font" off as of release 14.1:
```
medium: "OpenTTD Sans" 10 noaa ["" 0 noaa]
small: "OpenTTD Small" 6 noaa ["" 0 noaa]
large: "OpenTTD Serif" 18 noaa ["" 0 noaa]
mono: "sprite" 10 noaa ["" 0 noaa]
```
![image](https://github.com/OpenTTD/OpenTTD/assets/37945304/66e93642-7af3-45ba-9d07-3af87275905f)

</details>

### Steps to reproduce

1. Start OpenTTD with nightly 2024-05-27 or later.
2. Reset any custom font configurations, change the language to one using a Latin alphabet, uncheck "Use traditional sprite font," set interface scale to 1x, and disable anti-aliasing.
3. Notice the text looks bigger yet less readable (through my eyes) compared to 14.1 or earlier.

**Comment by PeterN** [comment]
Since #12641 actually.
