### ISSUE TITLE
[Bug]: #12030 causes incorrect accounting of water infrastructure totals when removing objects on water

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#12747]
### Version of OpenTTD

Since #12030

### Expected result

Water infrastructure totals are correct

### Actual result

#12030 sets the DC_FORCE_CLEAR_TILE flag when clearing more than one tile at once.
This causes water infrastructure totals to not be correctly updated when removing objects on water.

### Steps to reproduce

* Build a canal tile
* Build an object on it using your preferred object GRF
* Demolish an area larger than 1x1 including the above tile

**Comment by 2TallTyler** [comment]
Is this a separate issue than what you fixed in #12757?

**Comment by JGRennison** [comment]
No, it is the same one, I seem to have got my 5 digit numbers a tad muddled up.
