### ISSUE TITLE
[Bug]: In-game mouse stuck in top left corner of the screen

### ISSUE THREAD

**Issue by SCTA9** [OpenTTD/OpenTTD#12762]
### Version of OpenTTD

14.0 Chromebook OS

### Expected result

I updated the game thinking it would fix the issue.

### Actual result

But instead it was still keeping my mouse stuck on the top left of the screen.

### Steps to reproduce

1. Open OpenTTD on ChromeOS
2. Wait for it to load to the main menu
3. When in the main menu try to move the mouse

**Comment by krysclarke** [comment]
Am I correct in assuming that you're "SCTA" from tt-forums.net

These two forum threads were created recently and appear to be relevant:
- [Thread started by "SCTA"](https://www.tt-forums.net/viewtopic.php?t=91730)
- [Thread started by "yanguw"](https://www.tt-forums.net/viewtopic.php?t=91732)

## Summary of forum threads
Both users are experiencing the issue noted in the title of this bug report when using OpenTTD on Chromebook devices.
Both are using the Android-port obtained through the Google Play Store.

**Comment by PeterN** [comment]
OpenTTD on Android is developed separately, see https://github.com/n-ice-community/openttd-android
