### ISSUE TITLE
[Bug]: Long/truncated class names in picker windows missing first letter

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#12775]
### Version of OpenTTD

Nightly (18bce69), Windows 10

### Expected result

The new picker window is fantastic, but some class names do not fit and are truncated with an `...` elipsis.

The first part of the class name should be drawn normally.

### Actual result

![picker](https://github.com/OpenTTD/OpenTTD/assets/55058389/54bb629b-6e53-4b1e-9592-c49f59b11095)

Class names which are long enough to be truncated partway through are missing their first letter.

### Steps to reproduce

1. Start a game with a NewGRF station set with long names, like `Japan Set 3: Stations`.
2. Open the station picker and find a class name that is long enough to be truncated.
3. Observe that the class name is missing its first letter.

**Comment by WenSimEHRP** [comment]
Also reproducible in NewGRF parameter menu; tested with https://github.com/OpenTTD/OpenTTD/commit/81b5a7c7c6a7db9a90dbcc762023f6d5accbba19

![image](https://github.com/OpenTTD/OpenTTD/assets/145064583/27d574da-57cc-43cf-969c-54281e65e92c)

Won't occur in OpenTTD 14.1.

![image](https://github.com/OpenTTD/OpenTTD/assets/145064583/129e6606-7fc8-4226-8b9e-41d49acfc2ac)

**Comment by PeterN** [comment]
So nothing to do with the picker window.

Most likely something not quite right with my text layouter changes, maybe an off-by-one.

Doesn't seem to be reproducible with ICU/HarfBuzz/Freetype.
