### ISSUE TITLE
[Bug]: can't get server_name or client_name to work (docker on rapsi)

### ISSUE THREAD

**Issue by murphy83** [OpenTTD/OpenTTD#12784]
### Version of OpenTTD

13.4

### Expected result

Setting a server_name or client_name in openttd.cfg is respected when starting a dedicated server with the config file.

### Actual result

I compiled OpenTTD via cross-compile for Raspi to have a local server at hand.
I used the scripts / entrypoint from bateau / reddit and finally got the server to use the right config file.
Most of the settings in the config file work out as expected (such as min_active_clients). However I did not yet succeed in setting either client or server name by the config-parameters in the openttd.cfg

```
[network]
commands_per_frame = 2
max_commands_in_queue = 16
bytes_per_frame = 8
bytes_per_frame_burst = 256
max_init_time = 100
max_join_time = 500
max_download_time = 1000
max_password_time = 2000
max_lag_time = 500
pause_on_join = true
server_port = 3979
server_admin_port = 3977
server_admin_chat = true
server_game_type = local
server_name = My_Local_Server_Name
autoclean_companies = false
autoclean_unprotected = 12
autoclean_protected = 36
autoclean_novehicles = 0
max_companies = 15
max_clients = 25
client_name = my_funny_client_name
min_active_clients = 2
restart_game_year = 0
min_active_clients = 0
reload_cfg = false
no_http_content_downloads = false
use_relay_service = ask
```
Still every time I try to start the server I see the following logs:
```
openttd  | [2024-06-14 13:36:22] 
openttd  | [2024-06-14 13:36:22] dbg: [net] No "client_name" has been set, using "Unnamed Client" instead. Please set this now using the "name <new name>" command
openttd  | [2024-06-14 13:36:22] dbg: [net] No "server_name" has been set, using "Unnamed Server" instead. Please set this now using the "server_name <new name>" command
openttd  | [2024-06-14 13:36:22] dbg: [net] Initializing UDP listeners
openttd  | [2024-06-14 13:36:22] dbg: [net] Initializing UDP listeners
openttd  | [2024-06-14 13:36:22] dbg: [net] Listening on 0.0.0.0:3979 (IPv4)
openttd  | [2024-06-14 13:36:22] dbg: [net] Listening on [::]:3979 (IPv6)
openttd  | [2024-06-14 13:36:22] dbg: [net] Listening on 0.0.0.0:3979 (IPv4)
openttd  | [2024-06-14 13:36:22] dbg: [net] Listening on [::]:3979 (IPv6)
openttd  | [2024-06-14 13:36:22] dbg: [net] Network revision name: 13.4
```
The server name on the network is also displayed as Unnamed Server. Setting the server name via the console will not have any effect because the startup script uses "-x" indicating that changes to the config will never be written.

### Steps to reproduce

- Create a openttd.cfg with either server_name or client_name set to something
- mount it to the /config/ directory
- start the container / server (eg. using docker run or via a docker-compose file)
- See the error-message in the log

**Comment by PeterN** [comment]
These settings live in the `private.cfg` config file, alongside `openttd.cfg`

**Comment by murphy83** [comment]
Thanks a lot - this indeed resolved the issue!
