### ISSUE TITLE
Mouse Cursor Breaks when a physical mouse is being used on Android [Bug]: 

### ISSUE THREAD

**Issue by John2Baird** [OpenTTD/OpenTTD#12795]
### Version of OpenTTD

OpenTTD 14.1, Android 14 

### Expected result

I connected a physical mouse to my phone and tried to play OpenTTD with it. When it didn't work I also tried playing OpenTTD windowed with the Samsung DeX feature with an external monitor, that also didn't work.

### Actual result

In all cases, be it in regular phone mode, tablet mode or windowed on a second screen via Samsung DeX the mouse Cursor in OpenTTD would be stuck and unusable in the top left corner of the app or the app window. Using a physical mouse is therefore impossible on Android and only touch inputs work.

### Steps to reproduce

1. Connect a Bluetooth or USB mouse to your android device 
2. Open OpenTTD
3. Congratulations! Your mouse Cursor will be stuck in the top left corner.

**Comment by PeterN** [comment]
OpenTTD on Android is developed separately, see https://github.com/n-ice-community/openttd-android
