### ISSUE TITLE
[Bug]: catching exception from `array(1e12)` still crashes the script.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#12802]
### Version of OpenTTD

49d47b3b74 on Windows 10, 64-bit

### Expected result

When catching the exception thrown from an `array(x)` or array `resize(x)` call with a very large `x`, the script should be able to catch the exception, just like when dividing by zero or referencing a variable that does not exist.

Working example:
```squirrel
AILog.Info(1)
try { 1/0 } catch (e) { AILog.Info(e) }
AILog.Info(2)
```
Output:
```
1
division by zero
2
```

### Actual result

When catching the exception thrown from an `array(x)` or array `resize(x)` call with a very large `x`, the script still crashes and the code inside the catch block is not executed.

Not working example:
```squirrel
AILog.Info(1)
try { array(1e12) } catch (e) { AILog.Info(e) }
AILog.Info(2)
```
Output:
```
1
```
and the script crashes.

### Steps to reproduce

1. Create an AI with the following inside `main.nut`'s `Start()` method:
```squirrel
AILog.Info(1)
try { 1/0 } catch (e) { AILog.Info(e) }
AILog.Info(2)
try { array(1e12) } catch (e) { AILog.Info(e) }
AILog.Info(3)
```
2. Start the script.
3. The script crashes.
4. Check the logs from the script. Notice only `1`, `division by zero`, and `2` are output; the second exception message and `3` are both not printed.

[TestAI #12802.zip](https://github.com/user-attachments/files/15937261/TestAI.12802.zip)

**Comment by glx22** [comment]
Memory errors are fatal, they are triggered outside of squirrel and that's why you can't catch them.

So it's working as intended.

**Comment by James103** [comment]
> Memory errors are fatal, they are triggered outside of squirrel and that's why you can't catch them.
> 
> So it's working as intended.

Does the same reasoning apply for attempting to call `Sleep` or a DoCommand in a valuator or deleting a non-latest `AsyncMode`/`ExecMode`/`TestMode` object? As far as I know, these are the only other places a `Script_FatalError` can be triggered based on the code in the script.
