### ISSUE TITLE
[Bug]: With "Use traditional sprite font" on, no fallback font detection is performed even if the sprite font doesn't support the current language.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#12815]
### Version of OpenTTD

a1e94ccddb on Windows 10, 64-bit (via Steam)

### Expected result

Enabling "Use traditional sprite font" then changing the language to one not supported by the traditional sprite font should run the fallback font detection, just like in old versions.

### Actual result

Enabling "Use traditional sprite font" then changing the language to one not supported by the traditional sprite font does not run the fallback font detection, leaving the game displaying lots of ? in place of non-ASCII characters.

### Steps to reproduce

1. Reset any custom font configurations.
2. Enable "Use traditional sprite font"
3. Change the language to one not supported by the sprite font, such as Arabic, Ukrainian, or Vietnamese.
4. Notice lots of strings of ??? instead of regular text.

This is a sub-case of https://github.com/OpenTTD/OpenTTD/issues/11791, which was fixed but that fix has since broke.

**Comment by PeterN** [comment]
Oh, of course, the sprite font still falls back to the `?` glyph.
