### ISSUE TITLE
[Bug]: Windows: can't be compiled with llvm-rc

### ISSUE THREAD

**Issue by ognevny** [OpenTTD/OpenTTD#12820]
### Version of OpenTTD

14.1, Windows 11

### Expected result

successful rc file compilation

### Actual result

```
llvm-rc: Error in VERSIONINFO statement (ID 1):
FILEVERSION fields (20240503) does not fit in 16 bits.
```

### Steps to reproduce

1. download [msys2](https://msys2.org)
2. use the [recipe](https://github.com/ognevny/MINGW-packages/blob/b08f6981ae869d3c6a40d769931c03737069693c/mingw-w64-openttd/PKGBUILD) for build with `makepkg-mingw -s` from CLANG64 shell

**Comment by ognevny** [comment]
the same error for `PRODUCTVERSION`

**Comment by glx22** [comment]
Yeah it's not compliant but any other `rc` happily accept it.

**Comment by ognevny** [comment]
> Yeah it's not compliant but any other `rc` happily accept it.

I see. I also want to provide openttd not only for GCC environments
