### ISSUE TITLE
macOS sandbox

### ISSUE THREAD

**Issue by appleisshit** [OpenTTD/OpenTTD#12829]
### Version of OpenTTD

Any

### Expected result

Enabling the [macOS sandbox](https://developer.apple.com/documentation/security/app_sandbox) will reduce harm from vulnerabilities and malicious code

### Actual result

Game is not sandboxed

### Steps to reproduce

1. Run the game

**Comment by TrueBrain** [comment]
Totally off-topic, but I would never have expected someone with such a username to make such a ticket. That is just irony, which I truly appreciate :)

More on-topic, sounds excellent to enable sandbox. If you feel up for it, we would appreciate a PR which enables it, locally tested and everything. We currently don't actually have a developer with a MacOS, so for us these changes are rather hard. So if you are able / willing, we would welcome such PR :)

**Comment by yeah-its-gloria** [comment]
Since the App Sandbox would necessitate breaking social plugin (it does not support the needed `com.apple.security.cs.disable-library-validation` entitlement) and [Steam support](https://partner.steamgames.com/doc/store/application/platforms), I don't entirely see the point of enabling it.

**Comment by TrueBrain** [comment]
How I read your reply, is that we can close this ticket. Tnx for looking into this!
