### ISSUE TITLE
[Bug]: Windows help dialog box truncates help text due to too small statically sized conversion buffers

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#12839]
### Version of OpenTTD

master, Windows

### Expected result

Running `openttd.exe -h` shows the help text in a dialog box

### Actual result

The statically sized buffers for line ending conversion and char to wchar_t conversion in HelpDialogFunc are too small (when a modest number of AIs and GSs are installed).
![Screenshot_2024-07-03_00-46-51](https://github.com/OpenTTD/OpenTTD/assets/3910080/b778464d-d335-4409-9e2b-c8b2d5395e90)

(The GS section of the output is missing entirely in the above screenshot).

### Steps to reproduce

Run  `openttd.exe -h` on Windows

**Comment by glx22** [comment]
It's already two 8K buffers.
