### ISSUE TITLE
[Bug]: "Show industry names" blank panel not initialized properly

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#12840]
### Version of OpenTTD

ff3be45

### Expected result

#12770 added a button in the bottom row of the smallmap, which is only visible in the industry view.

When the smallmap is first opened, it defaults to the land contours mode, which has no buttons and works fine. Changing modes once the smallmap is open works fine: if I select a mode that has some but not all buttons (e.g. land owners, which has three), the missing industry name button space is filled by a blank panel. No problems yet.

If you change modes and close the smallmap, it remembers this choice and opens again in the same mode. If I choose a three-button mode and then close the smallmap, when I re-open the smallmap the buttons should appear properly.

### Actual result

Closing the smallmap in a mode with three buttons and then re-opening it does not draw the blank panel properly.

![hole](https://github.com/OpenTTD/OpenTTD/assets/55058389/7d99e470-6601-40b4-b207-b3f9098a1c13)

### Steps to reproduce

1. Open the smallmap (hotkey M)
2. Switch to "land owners" mode
3. Close the smallmap
4. Open the smallmap
5. Notice the hole in the GUI

**Comment by 2TallTyler** [comment]
I reviewed/approved #12770 and missed this, so I am fully to blame. That said, @EdmondChuiHW, any interest in fixing this? If not, we'll take care of it. 🙂

**Comment by EdmondChuiHW** [comment]
@2TallTyler oof sorry I missed this! I added `ReInit()` for this exact bug for switching between map types, but missed the reopening-map case. I've submitted #12842 to fix. Thanks for flagging this!  https://github.com/OpenTTD/OpenTTD/pull/12770#discussion_r1650212639
