### ISSUE TITLE
[Bug]: New Company button missing while server is full and Max Companies setting changes

### ISSUE THREAD

**Issue by efess** [OpenTTD/OpenTTD#12856]
### Version of OpenTTD

OpenTTD 14.1

### Expected result

When server is full of companies, Online Players Window updates with correct New Company button when `network.max_companies` increases 

### Actual result

When server is full of companies, Online Players Window will not add "New Company" button when `network.max_companies` increases - and retains "Join Company" - and it's out of sync with the company name list.

### Steps to reproduce

1. Create a dedicated server, set max companies to 1
2. Join game from a client, and create a company.  The server should have "max companies" and there is no longer a "New Company" button in `Online Players`. 
3. Join Spectators. THere should be just one empty company.
4. Keep open the Online Players window
5. Change the Max Companies setting to 2
6. See that there is no "New Company " button.   Closing the window and re-opening it will fix the issue.
![image](https://github.com/OpenTTD/OpenTTD/assets/772580/981b3a08-7ca5-49ca-a643-5e8d24b59225)

**Comment by 2TallTyler** [comment]
Sounds like changing the setting should re-init the window.
