### ISSUE TITLE
[Bug]: Fails to compile.  FATAL: Unwanted UTF-8 character U+200B in sequence

### ISSUE THREAD

**Issue by xiota** [OpenTTD/OpenTTD#12881]
### Version of OpenTTD

22e525dafef6273fad35c4358b942eb19ee94034

### Expected result

Should compile without error.

### Actual result

Error during compile:
```
[354/845] Compiling language traditional_chinese
FAILED: lang/traditional_chinese.lng /home/builder/build/src/build/lang/traditional_chinese.lng 
cd /home/builder/build/src/build/src/lang && /usr/bin/cmake -E make_directory /home/builder/build/src/build/lang && /home/builder/build/src/build/src/strgen/strgen -s /home/builder/build/src/openttd-git/src/lang -d /home/builder/build/src/build/lang /home/builder/build/src/openttd-git/src/lang/traditional_chinese.txt
/home/builder/build/src/openttd-git/src/lang/traditional_chinese.txt:3311: FATAL: Unwanted UTF-8 character U+200B in sequence '{BLACK}選擇遊戲版圖內最高峰的海拔，​​以海平面為基準計算'
[375/845] Generating table/strings.h
ninja: build stopped: subcommand failed.
```

### Steps to reproduce

Try to compile.

**Comment by krysclarke** [comment]
This is also happening in my fork of OpenTTD within GitHub.
The image below is the string, copied from the above error message and pasted in to LibreOffice - the highlighting is from LibreOffice.
![image](https://github.com/user-attachments/assets/ec7a0c0f-9d35-443f-a741-31dcd2272991)

Line 3311 of traditional_chinese.txt is for STR_MAPGEN_HEIGHTMAP_HEIGHT_TOOLTIP
My guess at the fix will be one of: roll back the translation of this string, or kindly ask the translator to amend the translation.

**Comment by WenSimEHRP** [comment]
@KogentaSan I believe that string is from you. Can you fix that please?

**Comment by xiota** [comment]
Search online indicates problem character is a zero-width separator.  Removal with following allows compilation to continue normally.
```
sed 's/\xe2\x80\x8b//g' -i src/lang/*.txt
```

**Comment by James103** [comment]
See also https://github.com/OpenTTD/OpenTTD/issues/9109 (same error path triggered).

**Comment by krysclarke** [comment]
> Search online indicates problem character is a zero-width separator. Removal with following allows compilation to continue normally.
> 
> ```
> sed 's/\xe2\x80\x8b//g' -i src/lang/*.txt
> ```

Unfortunately, that is only a work-around - the Web Translator service (eints) pushes updated translation files for ALL translations into src/lang/ each time ANY translation has been updated, except for english.txt as that's the 'base' that every other language is translated from.  Even english_AU.txt & english_US.txt (for en_AU & en_US, respectively)  are 'translations' as there are some words in each of them which have different spelling from en_GB.

**Comment by xiota** [comment]
Could the `sed` command be applied to the translation sources?  Seems "zero-width" could be hard for translators to find manually.
