### ISSUE TITLE
[Bug]: Purchase menu can show unpurchaseable vehicles 

### ISSUE THREAD

**Issue by Brickblock1** [OpenTTD/OpenTTD#12892]
### Version of OpenTTD

14.1 windows 10

### Expected result

All vehicles in the purchase list should be avaliable to purchase

This would mean that the first avaliable vehicle in a group is the one shown at the header of a the group

### Actual result

Some vehicles aren't avaliable as they either have no climate set, haven't reached their intro date or are of a different railtype.
![image](https://github.com/user-attachments/assets/e98db9ab-1b74-4a57-ae90-9a2c937f39c6)
clicking on it currently does nothing which could be confusing for players

### Steps to reproduce

[kst_scandi_train.zip](https://github.com/user-attachments/files/16500222/kst_scandi_train.zip)

1. download the zip file
2. extract it and putit in your newgrf folder
3. open a unelectrified depot and try to build the SL X10p 
4. notice that you first have to open the NKlJ AEG first since you can't buy the SL X10p by double clicking on the header

**Comment by audigex** [comment]
This is used deliberately by some newGRFs to create dummy "headers" in the purchase list (eg where there are doubly-nested items, or where the newGRF developer does not want a "default" purchase option for that variant group), and should probably not be "fixed" without the creation of an alternate solution to that goal

I would personally argue that this isn't a bug, but rather should be made explicitly-allowed behaviour (not greying out the item at all, but deliberately allowing it to be used as a non-purchasable header), although this should maybe be differentiated graphically

**Comment by Brickblock1** [comment]
Could the parent not be replaced by the avaliable items beneath it?

**Comment by audigex** [comment]
> Could the parent not be replaced by the avaliable items beneath it?

Again, ruins some use cases like that described above

**Comment by Brickblock1** [comment]
sure but that is a different issue
