### ISSUE TITLE
[Crash]: CTD opening Game Options

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#12952]
### Version of OpenTTD

Nightly df0233f, Windows 10

### Steps to reproduce

1. Start OpenTTD
2. From the main menu, click Game Options
3. Crash to desktop

This also occurs when trying to open Game Options in a running game.

### Upload crash files

[crash20240919163844.zip](https://github.com/user-attachments/files/17063015/crash20240919163844.zip)

**Comment by PeterN** [comment]
Any chance of a better stack trace than that?

**Comment by PeterN** [comment]
Never mind, got it :-)
