### ISSUE TITLE
[Bug]: "Proportion of towns that will become cities" is unnecessarily random

### ISSUE THREAD

**Issue by PikkaBird** [OpenTTD/OpenTTD#12957]
### Version of OpenTTD

20240922

### Expected result

By default, OpenTTD generates "1 in 4" towns as cities; towns which have an initial size boost and faster growth. It also sets a flag on the town, and It is not unusual for NewGRF authors to use that flag to differentiate between "cities" and "towns" for house and industry newgrf behaviour. 

Ideally, the proportion in the setting should be strictly adhered to; eg,  at 1 in 4, every fourth town generated is given the city flag.

### Actual result

However, rather than being strictly "1 in 4", a random probability of "city"hood is applied to each town. On large maps, with hundreds of towns, this randomness is hardly significant; but on smaller maps, with only a few towns, it becomes impossible for either GRF authors or players to anticipate the availability and proportion of cities on a randomly generated map.

### Steps to reproduce

On a map with 16 towns (an appropriate number for a 256x256 or 256x512 map) and the city setting at the default 1 in 4, a few generations produced results as varied as 9/16 - more than double the expected ratio - and 2/16 cities. With 8 towns, it only took a few generations to produce a map with zero cities, rather than the expected two.

![Unnamed, 7th Jan 1950](https://github.com/user-attachments/assets/2a6b2c39-ee10-4867-b590-4a1110d1ccda)

**Comment by PeterN** [comment]
Yeah, it's implemented `1 in X chance` rather than `1 every X`.
