### ISSUE TITLE
[Bug]: Score excluded from highscore when using sandbox

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#12973]
### Version of OpenTTD

from 14.0

### Expected result

Since these are no longer cheating options, using any of the sandbox options by the player should not cause any consequences for them - the final score should not be excluded from the highscore table.

### Actual result

After using a sandbox setting, the players score no longer ends up in the highscore.

### Steps to reproduce

Use the sandbox option and try to save your company to the highscore table.

**Comment by TrueBrain** [comment]
I removed a lot of your text. It was either not relevant to the bug, or just a rant. Both are not useful to include in a bug report. Edited the bug to be much more to the point and removed the ranting parts.

**Comment by Da-W1nn3r** [comment]
Can I take this issue?
