### ISSUE TITLE
[Bug]: Vehicle windows opening as 'sticky' by default.

### ISSUE THREAD

**Issue by AndyLandy** [OpenTTD/OpenTTD#12972]
### Version of OpenTTD

14.1, macOS 12.4, Apple Silicon

### Expected result

When opening a vehicle window by clicking on a vehicle either on the map or in a depot, the vehicle window should open with the sticky bit off.

### Actual result

When opening road vehicles, ships, or aircraft, the sticky bit is on by default. Train windows open as expected, without the sticky bit.

### Steps to reproduce

1. Start new game
2. Place a ship/road depot, or airport
3. Create a new vehicle
4. The vehicle window is opened, with the sticky pin set.

**Comment by PeterN** [comment]
To answer the last part, trains use a different window configuration, `view_vehicle_train`.

**Comment by AndyLandy** [comment]
In which case, no bug here, just user error!
