### ISSUE TITLE
[Bug]: Mac Cursor is not moving

### ISSUE THREAD

**Issue by rendomnet** [OpenTTD/OpenTTD#12971]
### Version of OpenTTD

Mac 14.6.1

### Expected result

Moving cursor reacting to my clicks.

### Actual result

When starting the game cursor is not moving. I see my Mac cursor and the Game cursor in the top left corner. Game cursor is not reacting to my Mac cursor movements and clicks.

### Steps to reproduce

1. Installed the game using Steam.
2. Started the game.

**Comment by yeah-its-gloria** [comment]
The cursor works just fine on macOS 15.0 (OpenTTD 14.1, Steam, MBA M2), could you describe your situation further? Like:
- Which Mac are you using?
- If you're using a Mac laptop, are you using the internal keyboard and trackpad or external peripherals?
- Are you using fullscreen mode?

**Comment by rendomnet** [comment]
> The cursor works just fine on macOS 15.0 (OpenTTD 14.1, Steam, MBA M2), could you describe your situation further? Like:
> 
> * Which Mac are you using?
> * If you're using a Mac laptop, are you using the internal keyboard and trackpad or external peripherals?
> * Are you using fullscreen mode?

The issue resolved itself when I relaunched the game.
Mac Mini M2 Desktop
Thank you.
