### ISSUE TITLE
[Bug]: Cities can't build roads / game can't generate new cities (concerns U&Ratt set)

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#12991]
### Version of OpenTTD

14.1 / JGRPP 0.62.0

### Expected result

Using one of the earlier versions of U&Ratt cities can build roads and the map generator is able to create a new map.

### Actual result

I don't know if it's only, but the problem concerns the very popular U&Ratt set. In the non-default setting "Time era used: Sequence", where city roads have a speed limit of 50 km/h, cities can't build these roads. Founded cities have 0 inhabitants and the map generator is unable to generate cities.
The new version of the add-on is not affected by this problem, but if someone started the game with one of the previous versions of the add-on before 14.0, they currently have a broken game.
The solution could be to update the set or change the "Time era used" setting to default, but firstly, most players will not know that this could be a solution, secondly, they will not know how to do it, and thirdly, the new version of the add-on is much less interesting for many players than the previous one, and changing the setting will disable the speed limit in cities to the real 50 km/h. The problem appeared, among others, on the Map of Poland server, where this add-on is used and where players currently have to build their own roads to develop cities, which becomes a limitation for other players. This can be fixed by changing the setting, but the aforementioned significant limitation will be removed, and the appearance of the roads will be changed, which will have a mixed form instead of homogeneous.

### Steps to reproduce

1. Try to start a new game with U&Ratt version 0.8 or earlier with the "Time era used: Sequence" setting - you will not generate a new map and will not start the game
2. Start the game with the above add-on and setting in version 13.4 and try to continue playing in 14.X - cities cannot build new roads, and funded cities always have 0 inhabitants.

**Comment by WenSimEHRP** [comment]
Solution: update to U&Ratt 1.1\
IMO should be a NewGRF problem rather than a game problem

> the new version of the add-on is much less interesting for many players than the previous one

you always have interesting points of view, but you don't have to write it down.

**Comment by WenSimEHRP** [comment]
@LC-Zorg
- You don't have to include that many citations; besides, focus on the topic - what is the bug?
- No need to argue "this add-on is popular" etc etc
- The NewGRF is unreachable, and outdated.
- Talk to the author of the NewGRF first. Have you talked yet?

**Comment by PeterN** [comment]
I just wanted to close this again.
