### ISSUE TITLE
[Bug]: Tabs not getting closed using cursor in Android device

### ISSUE THREAD

**Issue by critical1997** [OpenTTD/OpenTTD#12990]
### Version of OpenTTD

14.1 rev128

### Expected result

Opened tabs should be able to close using cursor or touch drag to the bottom to close. 

### Actual result

Unable to close the tabs using cursor or touch drag to the bottom to close

### Steps to reproduce

1. Open the app
2. Open any tab or multiple tab
3. Try to close the tabs using cursor drag to bottom 
4. Observe that unable to close tab
5. If multiple tabs are opened in screen only able close using X botton on top left corner.

**Comment by JohnFranklin523** [comment]
Android versions are not released and officially supported here.

**Comment by PeterN** [comment]
See either https://github.com/n-ice-community/openttd-android or https://github.com/pelya/openttd-android
