### ISSUE TITLE
[Bug]: OpenTTD Wiki link leading to wrong Website

### ISSUE THREAD

**Issue by Sedrowow** [OpenTTD/OpenTTD#13041]
### Version of OpenTTD

Website wiki.openttd.org

### Expected result

Clicking on the link [At the portable device section](https://wiki.openttd.org/en/Archive/Compilation%20and%20Ports/Portable%20device%20version) at Pocket Pc Download at [eSoft Interactive website](http://esoftinteractive.com/openttd.html) should lead to the download for PocketPc

### Actual result

It leads to a totally different webiste not containing the download:
[Kuyi Mobile](https://kuyimobile.com/)

### Steps to reproduce

1. Open wiki.openttd.org
2. Go to [this section in the wiki](https://wiki.openttd.org/en/Archive/Compilation%20and%20Ports/Portable%20device%20version)
3. Click on any eSoft interactive link
4. See the issue

**Comment by LordAro** [comment]
Luckily, it's a wiki, so you can fix it yourself. If a link still exists, I suspect it does not, as the version referenced is 0.6.0, which is over 16 years old.
