### ISSUE TITLE
[Bug]: landscape_grid.html objects data are misaligned by 2 columns

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#13052]
### Version of OpenTTD

OpenTTD 20241102-master-ga1233ee8a1, Windows 11 Pro 23H2

### Expected result

Aligned objects in the grid.

### Actual result

objects data are misaligned by 2 columns

### Steps to reproduce

![Captura de ecrã 2024-11-02 165702](https://github.com/user-attachments/assets/d272d9f1-dc4a-4ba7-81d4-d25cc140474e)

**Comment by rubidium42** [comment]
Fixed by #13185.
