### ISSUE TITLE
[Bug]: Transfer credits calculated for wrong CargoID

### ISSUE THREAD

**Issue by jostephd** [OpenTTD/OpenTTD#13053]
### Version of OpenTTD

master (3a76af090)

### Expected result

IotC case: I expected the truck to show positive transfer credits, since coffee is a profitable cargo and it was being transported towards an industry that accepts it.

Base game case: The valuables train should credit per unit of cargo more than the passengers train, because valuables are more profitable than passengers, all else being equal.

### Actual result

IotC case: The truck showed negative transfer credits.

Base game case: The passengers train and the valuables train report transfer credits £54 and £222 respectively. That's about £13 per unit of cargo in both cases.

### Steps to reproduce

With NewGRFs (the bug is easier to see this way):

1. Start a new game in the sub-tropical climate, with NewGRFs "ITL Houses" and "Industries of the Caribbean". The latter should have static payments enabled in NewGRF parameters. (IotC with static payments is what makes the bug noticeable. Sub-tropical climate and ITL Houses are required by IotC.)
2. Buy a coffee truck.
3. Have the truck full load, go to some other station, and transfer. The other station needn't be near an industry or anything.
4. Observe the transfer credits (the yellow text the truck emits after dropping off the coffee).

Without NewGRFs:

1. Start a game in the temperate climate.
2. Wait for a bank to appear. (Just the one bank is enough, you don't need two.)
3. Transfer valuables from the bank to some other station, doesn't matter which. I used a train comprising a single SH125 and nothing else (capacity 4).
4. Transfer passengers from the bank's station to the same other station. I used the same model, refitted (capacity 16).
5. Compare the transfer credits for the two cases.

**Comment by jostephd** [comment]
Turns out that in `CargoPayment::PayTransfer`, `this->ct` is zero rather than the correct CargoID value, so the wrong cargo's `cs->initial_payment` is used. In IotC, `cs->initial_payment` of CargoID zero happens to be negative. (IotC has several of these.)

So, basically, it seems to me that every transfer order everywhere calculates its transfer credits as though it is carrying passengers, regardless of what it's actually carrying...

It seems to be all down to a missing initialization:

```diff
diff --git a/src/economy.cpp b/src/economy.cpp
index 8ab98f9944..aab34df048 100644
--- a/src/economy.cpp
+++ b/src/economy.cpp
@@ -1429,6 +1429,7 @@ static void TriggerIndustryProduction(Industry *i)
  */
 CargoPayment::CargoPayment(Vehicle *front) :
 	current_station(front->last_station_visited),
+	ct(front->cargo_type),
 	front(front)
 {
 }
```

With this change:

- the IotC truck does get positive transfer credits (and the ship's income crediting drops accordingly)
- the temperate passengers case credits the same as above, £13 per unit
- the temperate valuables case credits £132, which is £34 per unit, that's x2.5 what it did before

However, I wasn't able to test the use of this constructor overload in `AfterLoadGame` in `src/saveload/afterload.cpp`.

**Comment by JGRennison** [comment]
Setting `ct` to `front->cargo_type` like this will only work for single-vehicle consists. In particular it won't work for trains, this also creates saveload problems as you mentioned.

`ct` is set via `CargoPayment::SetCargo`, in `LoadUnloadVehicle`, in preparation for `VehicleCargoList::Unload` -> `CargoPayment::PayFinalDelivery`.

The issue seems to me that it is not set for the `PrepareUnload` -> `VehicleCargoList::Stage` -> `CargoPayment::PayTransfer` path.
I'd suggest that `ct` should be set using `CargoPayment::SetCargo` there.
