### ISSUE TITLE
[Bug]: Traditional Chinese language does not display characters correctly in the stable version

### ISSUE THREAD

**Issue by KogentaSan** [OpenTTD/OpenTTD#13064]
### Version of OpenTTD

Windows 10

### Expected result

I want to see Traditional Chinese fonts displayed correctly in the stable version.

### Actual result

I translated it on the web translation website and the Traditional Chinese characters can be displayed correctly in the nightly version. But the stable version needs someone to help updating the language files.

### Steps to reproduce

Update to nightly version of Traditional Chinese language document will be fix it.

**Comment by 2TallTyler** [comment]
Yep, translations are only updated when there's a new release. We usually release a new stable version around April 1st, but make no promises as to the exact date.
