### ISSUE TITLE
[Crash]: RoadStop::Entry::CheckIntegrity always fails since #13029

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#13070]
### Version of OpenTTD

Since dfb74e25 / #13029

### Steps to reproduce

Set the desync debug level to >= 2 or otherwise enable cache checks

### Upload crash files

The NOT_REACHED in RoadStop::Entry::CheckIntegrity is always reached when the road stop is occupied.

At first glance, the transformation in #13029 is not correct because the various `this` values are not interchangeable.

**Comment by James103** [comment]
I was able to reproduce the crash while loading a performance testing savegame titled `wentbourne.sav`: 
[crash20241110153633.zip](https://github.com/user-attachments/files/17692008/crash20241110153633.zip)
