### ISSUE TITLE
Vehicle Groups: create group from vehicles in station list.

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#1308]
**_vc-labs_ opened the ticket and wrote:**

> With too many vehicles in game it's practically impossible to group vehicles for Autoreplace dealing with whole list.
> It would be much easier to do it on per-station basis, dealing with the only vehicles binded to that station; especially due the fact, that the vehicles binded to same station usually logically grupped by user to share same route and cargo.
> 
> I would consider a little more automation:
> \- Automatically group vehicles with same orders (route), model and refiting.

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_sulai_ wrote:**

> "same station" groups already exist: click on a station and then on the little train in the lower right of the window.
> 
> Anyway, "same station" vehicle lists and "shared orders" vehicle lists should be treated as groups. I developed some details about how to do this: http://wiki.openttd.org/index.php/User:Sulai/new_feature_concepts/FlexibleVehicleList
> 
> model- and vehicle based groups are already implemented by this patch: http://www.tt-forums.net/viewtopic.php?f=33&t=36648

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/1308#comment3969_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> There is currently no way to create a group based on same-station.  That would be a useful improvement imho.  It's non-trivial to design, because it needs to consider how/if vehicles are moved from their existing groups.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/1308#comment14532_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> I've retitled this, as I think it's really about how groups are created.  I think creating groups from station lists (1) would be a very useful feature when playing (2) has to consider a lot of awkward behaviour as it must move vehicles from other groups, which not be what players want.  
> 
> The current groups implementation is based on a vehicle being in one-and-only-one group. which is the only sustainable way (to avoid, e.g. autoreplace circular replacements).  Being in multiple groups would perhaps make more sense when creating station groups, but does't look viable to me.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/1308#comment14695_

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
