### ISSUE TITLE
[Bug]: Train does not find way into "Zugdepot"

### ISSUE THREAD

**Issue by GeneralxTaktikus** [OpenTTD/OpenTTD#13080]
### Version of OpenTTD

14.4

### Expected result

Im german and do not know the word for Zugdepot in english. Its the place where creation or maintenance is done. I have made a game where only the tracks are build where the problem occurs and two additional track parts below.

The tracks in this configuration are my standard place to let 2 trains drive safely on one track. If one train comes from the right and i send them to the zugdepot, then they normally drive past the zugdepot, drive through the signal, turn back and then drive into it. Sometimes the train/game tells me, that it cant find the zugdepot.

If i force the train to drive into the zugdepot by deleting 2 tracks in front of the zugdepot (i build the ones i delete south of the construction for example), then a new path is "found" at the moment i delete the thracks, and then the Zugdepot is found every time and the train drives directly into it.

For me this is a bug. Its totally annoying to send a train to his zugdepot, that is obiously reachable, and the train ignores it. Second there is a mechanism, that works ingame, that finds the way. The moment i delete the tracks it works and suddenly finds the way.

It would be fine if the game is changed, that the mechanism, that works the moment i delete the tracks, is started the moment i send the train to the zugdepot. Deleting tracks to force trains to find a way that is already there is (dunno, not good).

I play this game (im 60 and a gamer since Civ1 on Amiga) for many many years. I invented (for me) this track-configuration when i started the game at all and im sure sending a train to a zugdepot just worked in some older versions.

There are 2 ways of pathfinding, this problem occurs in both, i tried. My former version of the game was 12.(?)2 or 4. Im now playing 14.4. The Problem occurs in both versions. Actually i updated because of this "bug", i hoped it would be fixed in 14.4.

I dont have my older version to test it (i think).

Thank you for your effort

### Actual result

see above

### Steps to reproduce

[Test.zip](https://github.com/user-attachments/files/17775454/Test.zip)

**Comment by Kuhnovic** [comment]
I looked at your savegame, it only contains the layout but doesn't demonstrate the problem. Can you provide a savegame with a running train?

P.S. Zugdepot translates to train depot.

**Comment by GeneralxTaktikus** [comment]
[Test2.zip](https://github.com/user-attachments/files/17775771/Test2.zip)

**Comment by GeneralxTaktikus** [comment]
Thx for the translation ;)

**Comment by Kuhnovic** [comment]
Thanks, that savegame is much more useful. This does indeed look strange. The problem seems to go away when a signal is placed between the train and the intersection that connects the depot:
![image](https://github.com/user-attachments/assets/5baf2145-538f-424c-a572-118b6da238d1)

This might be the same issue as #9817

**Comment by GeneralxTaktikus** [comment]
I think the problem is, that the way, the train will drive, only is updated, if the track is changed. When the train starts it sets its way and does not change it, when i send it to the depot, but keeps his way no matter what. When the train passes a signal it sets his way new and then it finds the way to the depot.

But i change its way by ordering it to the depot, and at that moment it should set its way new and find it at once on a direct way.

Imho

Sicher versendet mit [Proton Mail](https://proton.me/mail/home).

Kuhnovic ***@***.***> schrieb am Freitag, 15. November 2024 um 15:05:

**Comment by 2TallTyler** [comment]
I am closing this issue to avoid duplicate issues in the bug tracker, since we already have this reported as #9817.

To sum up my understanding of the problem: A moving train can only change its path at a signal. Once the train has passed the last signal before the depot, it is committed to its path and cannot change its mind until the next signal. To avoid this, tell the train before it passes the signal before the depot. You can also add depots to the train's orders if you are having trouble; this is much easier for the train to figure out.

As discussed in #9817, we would like to fix this, but it is a hard problem to solve. 🙂

**Comment by GeneralxTaktikus** [comment]
Its ok to close my issue, but a train can change its path if a piece of its path is deleted, it does not stop at the point where the track-part is deleted, it continues its way if there is a possible track.

If i place a depot on the track and delete the one piece, where it connects, then there are two pieces left where the train can enter the depot and the train finds this way. So its possible to take a new path without a signal.

Sicher versendet mit [Proton Mail](https://proton.me/mail/home).

Tyler Trahan ***@***.***> schrieb am Freitag, 22. November 2024 um 18:29:
