### ISSUE TITLE
[Crash]: Crash on exiting to menu

### ISSUE THREAD

**Issue by joehtosis** [OpenTTD/OpenTTD#13158]
### Version of OpenTTD

Version: jgrpp-0.63.1 Windows 10

### Steps to reproduce

Saved the game and was exiting to the main menu.
Can provide mod list if it helps.

### Upload crash files

[crash.zip](https://github.com/user-attachments/files/18050204/crash.zip)

*** OpenTTD Crash Report ***

Crash at: 2024-12-07 23:22:04 (UTC)
In game date: 2051-05-09 (27, 0) (DL: 1)
Calendar date: 2051-05-09 (27, 0)

Crash reason:
 Exception:  C0000005
 Location:   7FF7F9596673
 Fault type: 0 (read)
 Fault addr: 0000021DB6BFE1C0
 Message:    <none>

Non-main thread (ottd:game)

OpenTTD version:
 Version:     jgrpp-0.63.1 (0)
 Release ver: 0.63.1
 NewGRF ver:  1f006d64
 Bits:        64
 Endian:      little
 Dedicated:   no
 Build date:  Nov 11 2024 00:54:04
 Defines:     WITH_BITMATH_BUILT
INS WITH_OVERFLOW_BUILTINS WITH_DEMANGLE WITH_BFD1 WITH_DBGHELP TTD_ENDIAN=TTD_LITTLE_ENDIAN WITH_PNG WITH_ZLIB WITH_LIBLZMA WITH_LZO WITH_ZSTD WITH_OPENGL WITH_PERSONAL_DIR WITH_SSE WITH_ASSERT UNICODE _UNICODE WITH_UNISCRIBE PSAPI_VERSION=1 POINTER_IS_64BIT

Decoded stack trace:
[00] openttd              0x00007FF7F9596673 FlushDeferredAspectUpdates() + 83 (/src/tile_map.h:105)
[inlined]                                    FlushDeferredAspectUpdates (/src/signal.cpp:1612)
[01] openttd              0x00007FF7F986C520 UpdateExtraAspectsVariable (/src/signal.cpp:2051)
[02] openttd              0x00007FF7F99818A8 AfterLoadGame (/src/saveload/afterload.cpp:4526)
[03] openttd              0x00007FF7F9983EA3 DoLoad (/src/sl/saveload.cpp:4254)
[04] openttd              0x00007FF7F9985D82 SaveOrLoad (/src/sl/saveload.cpp:4383)
[05] openttd              0x00007FF7F9A004AB LoadIntroGame (/src/openttd.cpp:481)
[06] openttd              0x00007FF7F99F8A12 SwitchToMode (/src/openttd.cpp:1435)
[07] openttd              0x00007FF7F99FA978 GameLoop (/src/openttd.cpp:1788)
[08] openttd              0x00007FF7F99FC54F GameLoop (/src/video/video_driver.cpp:41)
[09] openttd              0x00007FF7F99FC5E3 VideoDriver::GameThreadThunk(VideoDriver*) + 51 (/src/video/video_driver.cpp:48)
[inlined]                                    GameThreadThunk (/src/video/video_driver.cpp:100)
[10] openttd              0x00007FF7F959B5D7 unsigned int mingw_stdthread::thread::threadfunc<mingw_stdthread::detail::ThreadFuncCall<StartNewThread<void (*)(VideoDriver*), VideoDriver*>(mingw_stdthread::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&)(VideoDriver*), VideoDriver*&&)#1}, mingw_stdthread::detail::IntSeq<0ull, 1ull, 2ull>, char const*, void (*)(VideoDriver*), VideoDriver*> >(void*) + 167 (/src/video/../thread.h:110)
[inlined]                                    (/usr/lib/gcc/x86_64-w64-mingw32/10-win32/include/c++/bits/invoke.h:60)
[inlined]                                    (/usr/lib/gcc/x86_64-w64-mingw32/10-win32/include/c++/bits/invoke.h:95)
[inlined]                                    (/usr/lib/gcc/x86_64-w64-mingw32/10-win32/include/c++/functional:88)
[inlined]                                    (/src/3rdparty/mingw-std-threads/mingw.thread.h:100)
[inlined]                                    threadfunc (/src/3rdparty/mingw-std-threads/mingw.thread.h:151)
[11] msvcrt               0x00007FFB43BDAF5A beginthreadex + 298
[12] msvcrt               0x00007FFB43BDB02C endthreadex + 172
[13] KERNEL32             0x00007FFB43327374 BaseThreadInitThunk + 20
[14] ntdll                0x00007FFB4421CC91 RtlUserThreadStart + 33

Registers:
 RAX: 000000000000000B RBX: 0000021DAF7E7D30 RCX: 0000000000022EA8 RDX: 0000021DB6BFE1C0
 RSI: 0000000000117540 RDI: 0000000000000001 RBP: 00007FF7F9D8BF40 RSP: 00000062D8BFD720
 R8:  0000021DAF7E7C10 R9:  0000000000000000 R10: 0000000000000008 R11: 0000000000000008
 R12: 0000000000022EA8 R13: 00007FF7F9D8BEE0 R14: 0000000000000007 R15: 000000009DFC5814
 RIP: 00007FF7F9596673 EFLAGS: 00010206

 Bytes at instruction pointer:
 0F B6 02 C1 F8 04 83 F8 01 74 52 83 F8 09 75 1E 0F B6 52 07 89 D0 A8 20

Operating system:
 Name:     Windows
 Release:  10.0.19045 ()
 Compiler: GCC 10.0.0 "10-win32 20220113"

Configuration:
 Blitter:      40bpp-anim
 Graphics set: OpenGFX2  High Def (0)
 Language:     english_US.lng
 Music driver: dmusic
 Music set:    Rise of the Triad OST (No Short Tracks) (1)
 Network:      no
 Sound driver: xaudio2
 Sound set:    OpenSFX (7974)
 Video driver: win32-opengl (Intel(R) Iris(R) Plus Graphics 655, 4.5.0 - Build 26.20.100.6999)
 Game mode:    MENU, SM: 6

Fonts:
 Small:  OpenTTD Small
 Medium: OpenTTD Sans
 Large:  OpenTTD Serif
 Mono:   sprite

Map size: 0x10000 (256 x 256)

AI Configuration (local: 0) (current: 0):
  0: Human

Libraries:
 LZMA:       5.2.12
 ZSTD:       1.4.8
 LZO:        2.10
 PNG:        1.5.23
 Zlib:       1.2.8

Non-default settings:
  soundsset: "OpenSFX"
  musicset: "Rise of the Triad OST (No Short Tracks)"
  language: english_US.lng
  resolution: 2560,1346
  player_face: 3511826072
  invisibility_options: 4
  last_newgrf_count: 122
  gui_scale: 200
  window_maximize: true
  difficulty.competitors_interval: 0
  difficulty.number_towns: 1
  difficulty.industry_density: 0
  economy.town_layout: 1
  economy.allow_town_roads: false
  economy.town_cargogen_mode: 0
  economy.inflation_fixed_dates: false
  economy.payment_algorithm: 0
  station.modified_catchment: false
  vehicle.road_side: left
  vehicle.train_acceleration_model: 0
  vehicle.roadveh_acceleration_model: 0
  vehicle.max_train_length: 50
  vehicle.dynamic_engines: false
  vehicle.adjacent_crossings: false
  gui.right_click_wnd_close: yes
  gui.industry_tooltip_show_required: true
  gui.industry_tooltip_show_stockpiled: true
  gui.link_terraform_toolbar: true
  gui.starting_colour: 15
  gui.starting_colour_secondary: 2
  gui.auto_remove_signals: true
  gui.use_owner_colour_for_tunnelbridge: true
  gui.pause_on_newgame: true
  gui.drag_signals_density: 6
  gui.semaphore_build_before: 1850
  gui.station_platlength: 1
  gui.station_dragdrop: false
  gui.station_show_coverage: true
  gui.graph_line_thickness: 4
  gui.show_adv_tracerestrict_features: true
  gui.show_progsig_ui: true
  gui.show_noentrysig_ui: true
  gui.adv_sig_bridge_tun_modes: true
  gui.sort_track_types_by_speed: true
  gui.show_newgrf_name: true
  gui.show_cargo_in_vehicle_lists: true
  gui.settings_restriction_mode: 2
  linkgraph.recalc_interval: 16
  linkgraph.recalc_time: 64
  locale.currency: EUR
  music.playlist: 4
  music.music_vol: 30
  music.effect_vol: 89
  music.custom_1: 1,4,6,7,8,9,10,11,12,13,15,15,16,17,18,19,22,22,23,24,25,26,27,28,2,0,0,0,0,0,0,0,0
  music.custom_2: 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
  pf.forbid_90_deg: false
  pf.reverse_at_signals: true
  game_creation.landscape: arctic
  game_creation.snow_line_height: 7
  game_creation.generation_unique_id: 2316009271
  game_creation.map_x: 10
  game_creation.map_y: 9
  construction.map_height_limit: 15
  construction.freeform_edges: false
  construction.flood_from_edges: false
  vehicle.servint_ispercent: true
  vehicle.servint_trains: 25
  vehicle.servint_roadveh: 25
  vehicle.servint_ships: 25
  vehicle.servint_aircraft: 25
  infra_others_buy_in_depot[0]: true
  infra_others_buy_in_depot[1]: true
  infra_others_buy_in_depot[2]: true
  infra_others_buy_in_depot[3]: true
  advance_order_on_clone: true

Command Log:
 Showing most recent 0 of 0 commands

Special Events Log:
 Showing most recent 0 of 0 events

---- gamelog start ----
Tick 62675: game loaded
Conversion from OTTD savegame without gamelog: version 4, 1
Revision text changed to jgrpp-0.63.1, savegame version 292, not modified, _openttd_newgrf_version = 0x1f006d64
New game mode: 0 landscape: 1
Added NewGRF: GRF ID 4E434944, checksum AECA8E46F76F2A3EEFB8A7D6B8238894, filename: 4e434944-nml_cat_industry-1.tar\nml_cat__industry-1\nmlcat-industry.grf (md5sum matches)
Added NewGRF: GRF ID 4E445903, checksum EA3772BB12318C0CB851AB92769BD913, filename: 4e445903-age_of_industry_replacement_set-1.3.2.tar\age_of_industry_replacement_set-1.3.2\airs.grf (md5sum matches)
Added NewGRF: GRF ID 4E434C53, checksum 6BF46833AFBC46548FFEFAB03FBDD83B, filename: 4e434c53-nml_cat_landscape-1.tar\nml_cat__landscape-1\nmlcat-landscape.grf (md5sum matches)
Added NewGRF: GRF ID 33325A43, checksum 8767596EEC0C25A41B060D834C356402, filename: 32bpp_ez-0.1.grf (md5sum matches)
Added NewGRF: GRF ID 4F475A02, checksum 47855626B32396692E09753A71DA1710, filename: ogfx2_landscape.grf (md5sum matches)
Added NewGRF: GRF ID 4F475A04, checksum 6613F70A7E02B90910EE8270248DF165, filename: ogfx2_trees.grf (md5sum matches)
Added NewGRF: GRF ID 424E0101, checksum 611058D499297493B47062078F12A988, filename: 424e0101-opengfx_landscape_minus-v7140_minus.tar\opengfx_landscape_minus-v7140_minus\ogfx-landscape-minus.grf (md5sum matches)
Added NewGRF: GRF ID 4D490302, checksum 938BC78CAAC2E69DBBC919FC869C0767, filename: 4d490302-cztr_tree_set-2.0.1.tar\cztr_tree_set-2.0.1\cztr_tree_set.grf (md5sum matches)
Added NewGRF: GRF ID 4D490401, checksum 22B2D1D195FC972E3C3439DE72E6D80A, filename: 4d490401-cztr_effects-1.0.0.tar\cztr_effects-1.0.0\cztr_efects.grf (md5sum matches)
Added NewGRF: GRF ID 56420505, checksum 9A5B0E32FEBCE29282C1091BE79579C8, filename: 56420505-brix_realism_is_xxxx-0.0.3.tar\brix_realism_is_xxxx-0.0.3\brix.grf (md5sum matches)
Added NewGRF: GRF ID 4B460301, checksum 9E3EF9AB972B459F5BA33850A1F6520F, filename: rock_replacement_for_transmitter.tar\transrock.grf (md5sum matches)
Added NewGRF: GRF ID 4E434F42, checksum 8744E4664EC16E52A225F5BABC048E5F, filename: 4e434f42-nml_cat_newobjects-1.tar\nml_cat__newobjects-1\nmlcat-newobjects.grf (md5sum matches)
Added NewGRF: GRF ID 54454D33, checksum A94F2D3B5B9B22B53FF43F3C82C7F09C, filename: 54454d33-real_parks_gardens_in_32bpp-beta_1.0.tar\real_parks_gardens_in_32bpp-beta_1.0\realgardens.grf (md5sum matches)
Added NewGRF: GRF ID 54454D32, checksum A3FD770D4DCF34214307E42A97C435E3, filename: 54454d32-temporal8_real_houses_eyecandy-1.tar\temporal8_real_houses_eyecandy-1\real_houses_eyecandy_objects_1.grf (md5sum matches)
Added NewGRF: GRF ID 4652AD09, checksum 9189601C50787BE7A9D53F8F8231A790, filename: 4652ad09-swedish_houses_as_objects-1.1.tar\swedish_houses_as_objects-1.1\swedishobjects.grf (md5sum matches)
Added NewGRF: GRF ID 4E434244, checksum 62BDEE2136DEEFBC3ED0D172466E99E9, filename: 4e434244-nml_cat_buildings-1.tar\nml_cat__buildings-1\nmlcat-buildings.grf (md5sum matches)
Added NewGRF: GRF ID 5A554B21, checksum D057A92507467167857C4E9FDCF6B9EB, filename: 5a554b21-full_english_uk_townset-1.tar\full_english_uk_townset-1\full-english_uk-townset.grf (md5sum matches)
Added NewGRF: GRF ID 54540301, checksum 8DEBFD0FFAEF09875DC1E214D969FF24, filename: 54540301-itl_houses-2.2.tar\itl_houses-2.2\itl_houses.grf (md5sum matches)
Added NewGRF: GRF ID 2D480107, checksum D12D0DF9F96AFFB4122E32D0C5D12D63, filename: 2d480107-main_hq_ttdur-1.0.tar\main_hq_ttdur-1.0\mainhqw.grf (md5sum matches)
Added NewGRF: GRF ID 4E435354, checksum 49774C8EEB675A83170CA1090A9A7C03, filename: 4e435354-nml_cat_stations-1.tar\nml_cat__stations-1\nmlcat-stations.grf (md5sum matches)
Added NewGRF: GRF ID 4B480C00, checksum 0C8A72A55E5CD0FE95A9A4CC15E4E9E3, filename: 4b480c00-highspeed_farm_stations-1.tar\highspeed_farm_stations-1\highspeed-station-f.grf (md5sum matches)
Added NewGRF: GRF ID 4B480B00, checksum 9EA166668B7C8DAEE78975D78710DDEA, filename: 4b480b00-highspeed_industry_stations-1.tar\highspeed_industry_stations-1\highspeed-station-i.grf (md5sum matches)
Added NewGRF: GRF ID 4B480A00, checksum 54F1897170BE410B9D1FBEBEB22BE3B5, filename: 4b480a00-highspeed_passenger_stations-1.tar\highspeed_passenger_stations-1\highspeed-station-p.grf (md5sum matches)
Added NewGRF: GRF ID 54574608, checksum 8B455DF3597874F8640A5B25A98FED64, filename: 54574608-timberwolf_s_stations-1.2.4.tar\timberwolf_s_stations-1.2.4\timberwolfs_stations.grf (md5sum matches)
Added NewGRF: GRF ID 54454D06, checksum 55FC970E8847AB06AE0FDFC0149A1DE6, filename: 54454d06-temporal8_real_stations_32bpp-beta_1.0.tar\temporal8_real_stations_32bpp-beta_1.0\real_stations_beta1.grf (md5sum matches)
Added NewGRF: GRF ID 56480002, checksum A073ECD0799F9E4E1B974F2DAE3665BD, filename: 56480002-cztr_stations-1.0.0.tar\cztr_stations-1.0.0\cztr_stations.grf (md5sum matches)
Added NewGRF: GRF ID 5F5F0301, checksum 98FB9C95AA0E49DFB451E15DA88B02D2, filename: 5f5f0301-china_set_stations-0.2.0.tar\china_set_stations-0.2.0\cns.grf (md5sum matches)
Added NewGRF: GRF ID E5BC8B73, checksum EE2735F7D49FC8AFD7C7F250F774CC0B, filename: e5bc8b73-china_set_stations_wuhu-0.3.1.tar\china_set_stations_wuhu-0.3.1\station.grf (md5sum matches)
Added NewGRF: GRF ID 53410A0A, checksum FAE9F12A642095FA0B88A467F836B49E, filename: 53410a0a-gets_waypoints-0.1.tar\gets_waypoints-0.1\gets_wp_0.1.grf (md5sum matches)
Added NewGRF: GRF ID 4E434953, checksum 3C332D7F6F6F54D8228DB5B0C1B5DA31, filename: 4e434953-nml_cat_infrastructure-1.tar\nml_cat__infrastructure-1\nmlcat-infrastructure.grf (md5sum matches)
Added NewGRF: GRF ID 54574609, checksum 7A2A3048AD4A39CA68AC5DD9D227C152, filename: 54574609-timberwolf_s_roads-1.0.10.tar\timberwolf_s_roads-1.0.10\timberwolfs_roads.grf (md5sum matches)
Added NewGRF: GRF ID 4D490104, checksum 81F0F3929F0C1356F8AE81016C337F77, filename: 4d490104-cztr_rails-2.1.2.tar\cztr_rails-2.1.2\cztr_rails.grf (md5sum matches)
Added NewGRF: GRF ID 4D490307, checksum 87502FC3C789199B270E4E2882261F69, filename: 4d490307-cztr_rail_addons-1.0.2.tar\cztr_rail_addons-1.0.2\cztr_rail_addons.grf (md5sum matches)
Added NewGRF: GRF ID 4D490101, checksum 81384BE0D4F65C5810B0486DCB230A99, filename: 4d490101-cztr_road_set-2.2.1.tar\cztr_road_set-2.2.1\cztr_road_set.grf (md5sum matches)
Added NewGRF: GRF ID 43530103, checksum 5E452F207A8C6C791698E67B9A671953, filename: 43530103-country_roads-1.0.2.tar\country_roads-1.0.2\countryroads.grf (md5sum matches)
Added NewGRF: GRF ID 4E435452, checksum 6E75DD4ED53B314EC374BEB80EC81E9F, filename: 4e435452-nml_cat_trains-1.tar\nml_cat__trains-1\nmlcat-trains.grf (md5sum matches)
Added NewGRF: GRF ID 54574607, checksum BFF461D29B7885CDEEDCBBD225EF598A, filename: 54574607-timberwolf_s_uk_trains-1.6.0.tar\timberwolf_s_uk_trains-1.6.0\timberwolfs_trains.grf (md5sum matches)
Added NewGRF: GRF ID 5457460C, checksum BB61C0B447F8649F7F2381704118FD63, filename: 5457460c-timberwolf_s_uk_trains_addon-1.1.0.tar\timberwolf_s_uk_trains_addon-1.1.0\timberwolfs_community_addon.grf (md5sum matches)
Added NewGRF: GRF ID 48558787, checksum FB9D70D26EA87F5D52260BA831C01EBE, filename: 48558787-hungarian_urban_train_set-1.tar\hungarian_urban_train_set-1\hvwurban.grf (md5sum matches)
Added NewGRF: GRF ID 52548330, checksum 2CF65F24DC2D87570378E6656BAA186A, filename: 52548330-rubber_tyred_metro_set-1.tar\rubber_tyred_metro_set-1\rtms.grf (md5sum matches)
Added NewGRF: GRF ID 5F5F0300, checksum 50A6010572E2C4341837B052B047E7B2, filename: 5f5f0300-china_set_trains-0.3.3.176.tar\china_set_trains-0.3.3.176\chinasettrains.grf (md5sum matches)
Added NewGRF: GRF ID 05080304, checksum 2E1D04E09F52048E3BA8E2B25C8B51A9, filename: 05080304-hangzhou_metro_lines-1.1.tar\hangzhou_metro_lines-1.1\hangzhoumetro2.grf (md5sum matches)
Added NewGRF: GRF ID A0005353, checksum 7C2F62D44712EC3D6839E88AB5CC0778, filename: rutrains32fz.grf (md5sum matches)
Added NewGRF: GRF ID 54454D31, checksum 418AB7E6139F82BEBC08773A023E261C, filename: 54454d31-temporal8_real_trains_32bpp_4x-1.0.2.tar\temporal8_real_trains_32bpp_4x-1.0.2\temporal8_real_trains_hs_32bpp_4x_extrazoom_1.0.2.grf (md5sum matches)
Added NewGRF: GRF ID 4C453038, checksum BB8E8BE07AB25EC163C0978045602CA8, filename: 4c453038-8_32bpp_chinese_maglev_trains-1.0beta.tar\8_32bpp_chinese_maglev_trains-1.0beta\832bpp_chinese_maglev_trainsv1.grf (md5sum matches)
Added NewGRF: GRF ID 4E435244, checksum E5D978305832EB67434B9AD1332094EB, filename: 4e435244-nml_cat_road-1.tar\nml_cat__road-1\nmlcat-road.grf (md5sum matches)
Added NewGRF: GRF ID 5457460A, checksum A56EB17426B6D481B2BCF433922F6A14, filename: 5457460a-timberwolf_s_uk_road_vehicles_3-3.3.0.tar\timberwolf_s_uk_road_vehicles_3-3.3.0\timberwolf_uk.grf (md5sum matches)
Added NewGRF: GRF ID 43530702, checksum F035A31AE4A67EA2B522D284B20785D5, filename: 43530702-suv-0.6.1.tar\suv-0.6.1\suv_0_6_1.grf (md5sum matches)
Added NewGRF: GRF ID 43531001, checksum 93740B81A19501142AA1BF8C0C5DC54E, filename: aatvset_0.1_prerelease3.grf (md5sum matches)
Added NewGRF: GRF ID 43530902, checksum 99AC3E5DA038937948061040CC6B524D, filename: 43530902-water_way_road-0.4.5.tar\water_way_road-0.4.5\waterway_0_4_5.grf (md5sum matches)
Added NewGRF: GRF ID 48531620, checksum 3F36A8F5572E24ECF8037762DF7BD256, filename: 48531620-hvw_tram_set-1.0b.tar\hvw_tram_set-1.0b\hvwts.grf (md5sum matches)
Added NewGRF: GRF ID 48531701, checksum 38086D35A592856600035C3BB995B115, filename: 48531701-hvw_bus_set-0.1b.tar\hvw_bus_set-0.1b\hvwbs.grf (md5sum matches)
Added NewGRF: GRF ID 48531999, checksum 618514F259A829C9C5D3BBE1C0FECACF, filename: 48531999-hvw_modular_truck_set-r130.tar\hvw_modular_truck_set-r130\hvw-mts.grf (md5sum matches)
Added NewGRF: GRF ID 54454D07, checksum CDC3E1EA3EE9F674539A002CECEB4761, filename: 54454d07-temporal8_real_bus_32_bpp_4x-1.1.tar\temporal8_real_bus_32_bpp-1.1\real_bus_1_1.grf (md5sum matches)
Added NewGRF: GRF ID 54454D01, checksum BF7BDE06EF57E027DA3F397F857A0447, filename: 54454d01-temporal8_s_real_cars_32bpp-1.5.tar\temporal8_s_real_cars_32bpp-1.5\real_cars_1_5.grf (md5sum matches)
Added NewGRF: GRF ID 54454D08, checksum DCE528DBD4A3EA2A58EE870D7EF6C340, filename: 54454d08-temporal8_real_vehicles_32bpp-1.0.tar\temporal8_real_vehicles_32bpp-1.0\real_vehicle_1_0.grf (md5sum matches)
Added NewGRF: GRF ID 5742530A, checksum 9E274994BA16294ED115A8C1853B90D2, filename: susmon-reldred-edits\susmon-reldred-edits.grf (md5sum matches)
Added NewGRF: GRF ID 4E434D41, checksum 128E3AE7F3661C1D955BBD639E3D1D91, filename: 4e434d41-nml_cat_marine-1.tar\nml_cat__marine-1\nmlcat-marine.grf (md5sum matches)
Added NewGRF: GRF ID 54454D20, checksum 14B89E03446091A1F78BECA806139DC9, filename: 54454d20-temporal8_s_real_ships_32bpp-1.3.1.tar\temporal8_s_real_ships_32bpp-1.3.1\real_ships_1_3_1.grf (md5sum matches)
Added NewGRF: GRF ID 434D4301, checksum 9F51BA9B50B5F99AD31BD3A13E66ADA8, filename: 434d4301-sailing_ships_community-0.73.tar\sailing_ships_community-0.73\ss_community.grf (md5sum matches)
Added NewGRF: GRF ID 4E434143, checksum B4BB5854278F4707E36509EA905C2F54, filename: 4e434143-nml_cat_aircraft-1.tar\nml_cat__aircraft-1\nmlcat-aircraft.grf (md5sum matches)
Added NewGRF: GRF ID 535A2330, checksum BEDFEED918FED648579C1A1245BFDA1E, filename: 535a2330-use_able_default_aircraft-v2.tar\useable_default_aircraft-v2\use_airc.grf (md5sum matches)
Added NewGRF: GRF ID 4C450016, checksum 7C8578504DF40725012301010C80067C, filename: 4c450016-china_aircraft_comac_c919-2.0.tar\china_aircraft_comac_c919-2.0\c919v2.grf (md5sum matches)
Added NewGRF: GRF ID 44440A80, checksum 2F7F4BC7FBAD4544CA241DFE6D5A6F39, filename: 44440a80-av9.8-0.97.tar\av9.8-0.97\av9point8.grf (md5sum matches)
Added NewGRF: GRF ID 4B530125, checksum C19F10AC3F819A81A24EEDEAA9E33AA8, filename: 4b530125-atov_helicopters-1.0.tar\atov_helicopters-1.0\atov_helicopters.grf (md5sum matches)
Added NewGRF: GRF ID 4B460401, checksum 0246AF841FDD0F0856B52E8CFBCA2C70, filename: airmast.grf (md5sum matches)
Added NewGRF: GRF ID 4E434755, checksum 1531C814F50B09061CC2599559C7F200, filename: 4e434755-nml_cat_gui-1.tar\nml_cat__gui-1\nmlcat-gui.grf (md5sum matches)
Added NewGRF: GRF ID 55464970, checksum C586AD3601A028A3FD8968CEAAA31A1D, filename: 55464970-u_gui-2.1.tar\u_gui-2.1\ugui.grf (md5sum matches)
Added NewGRF: GRF ID 4A44FAB1, checksum 3F98860E64AC3D7671A6A0F0715930F1, filename: 4a44fab1-newcc_set-0.3.tar\newcc_set-0.3\newcc.grf (md5sum matches)
Added NewGRF: GRF ID 4E434D43, checksum C1B36A9B6AD2634ABA03BC68C262E8DB, filename: 4e434d43-nml_cat_misc-1.tar\nml_cat__misc-1\nmlcat-misc.grf (md5sum matches)
Added NewGRF: GRF ID 4D470305, checksum 2E96B9AB2BEA686BFF94961AD433A701, filename: 4d470305-basecosts-5.0.tar\basecosts-5.0\basecosts.grf (md5sum matches)
Added NewGRF: GRF ID 53536302, checksum 094296153E827DFD6991E5DDA447C316, filename: 53536302-ultimate_cargo_payment_override-2.tar\ultimate_cargo_payment_override-2\ultimatecargopaymentoverride.grf (md5sum matches)
---- gamelog end ----

Recent news messages (0 of 0):

*** End of OpenTTD Crash Report ***

**Comment by glx22** [comment]
It's a JGRPP build, reports should go to https://github.com/JGRennison/OpenTTD-patches/issues.

**Comment by joehtosis** [comment]
Gotcha, sorry about that.
