### ISSUE TITLE
[Bug]: Scrolling map with scrollwheel/touchpad does not work

### ISSUE THREAD

**Issue by v1993** [OpenTTD/OpenTTD#13167]
### Version of OpenTTD

14.1, EndeavourOS (KDE Wayland)

### Expected result

Setting "Interface -> Viewports -> Function of scrollwheel" to "Scroll map" makes two-finger scroll on touchpad move the map around.

### Actual result

Setting "Interface -> Viewports -> Function of scrollwheel" to "Scroll map" has no effect, i.e. two-finger scroll only zooms in/out.

### Steps to reproduce

1. Open settings menu
2. Set "Interface -> Viewports -> Function of scrollwheel" to "Scroll map"
3. Launch a game session and try scrolling in main viewport only for map to zoom in/out
4. Open an extra viewport and confirm that it zooms there as well
5. Restart the game and repeat steps 3-4 just to make sure it's still broken

Bonus: run with `SDL_EVENT_LOGGING=2` set to confirm that SDL sees horizontal scrolling.

**Comment by PeterN** [comment]
Strange, this setting was meant to only be available to Mac OS, as there's the only place where 2D scrolling was implemented.
