### ISSUE TITLE
[Bug]: Changelog missing on website

### ISSUE THREAD

**Issue by TheMowgliMan** [OpenTTD/OpenTTD#13194]
### Version of OpenTTD

Current Openttd.org website version

### Expected result

Clicking 'Changelog' opens 15.0-beta1 changelog.

### Actual result

Clicking 'Changelog' returns 404 error.

### Steps to reproduce

1. Go to Openttd.org
2. Click 'Changelog' for 15.0-beta1 news message
3. Observe 404 error

**Comment by glx22** [comment]
Yeah we know, also see https://github.com/OpenTTD/website/issues/330 :)

**Comment by TheMowgliMan** [comment]
Ahh, I see. I hadn't known there was a website GitHub. I actually thought I was the first to catch bug for once  ;)  Closing!
