### ISSUE TITLE
Allow industry tiles to be water tiles

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#1423]
**_George_ opened the ticket and wrote:**

> Would it be possible to make industry tiles be water tiles? 
> It is required for industries on shores, because rivers have river border inside river tile, that makes the industry's tile to have grassed land graphics, while on sea level the sea does not have border, that makes the industry's tile to have watered land graphics (the right way from my point of view). 
> You can check Neu Schwanstein Castle from ECS Town vector. Build it on water level and on the water of the lake and see the difference. 
> I'd like to see the same behaviour (to remove height check)
> So, there are two possible solutions.
> 1) rivers would have shore graphics like seas (land sprites of nearby tiles are drawn as shores) on any level.
> 2) specify industry tile as water, so river would not draw the shore. Additionally, it requires the possibility for industry tiles to access shore sprites to draw them on industry tiles.

**Reported version**: _0.5.3_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> The report was misunderstood.
> https://yadi.sk/i/RLNVFih23MLfJR
> The aim is make river think, that it is not land nearby, but a water, and not draw a river shore

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/1423#comment14649_

**Comment by andythenorth** [comment]
Converting arbitrary tiles to water when the industry is built won't be implemented.

Proposed solution.  Include water tiles in the hotel layout, so it has to be built over the river.  Then set custom sprites for those water tiles.
