### ISSUE TITLE
Scenario Editor: wipe out all player-owned objects (and also other categories)

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#1731]
**_electricmonk_ opened the ticket and wrote:**

> In the scenario editor, there should be an option to remove all player-owned objects (vehicles, railway-infrastructure, docks, airports, road-vehicle-stops, company statues, depots, owned land, etc.). Roads' ownership would be transfered to the town. Not sure if industries built by the player should be cleared or not, but I think that all player-built industries should become town-owned industries (like the industries that were on the map at the start of the game) instead of being deleted.
> 
> Likewise, there should also be an option to remove all industries from the map (I believe this is similar to TTDPatch's cht:resetindustries). Also, there could be an option to remove all towns from the map (although I suspect that in order to work, it would also have to remove all player objects and industries).
> 
> These options could either be accessed from the user-interface, or entered as a command in the console-window.
> 

**Reported version**: _0.6.0-beta3_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_SmatZ_ wrote:**

> Start Scenario editor, press F4, click on Reset landscape. Removes all player owned stuff. (it should, see #1703 for problems)
> Maybe "Reset landscape" isn't the best label there though...

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/1731#comment3413_

**Comment by DorpsGek** [comment]
**_electricmonk_ wrote:**

> I agree. It's not the best label. "Reset landscape" should be renamed to "Remove all companies and company-owned infrastructure". Also, is there a way of removing just the industries but leaving the player-owned stuff? To do this, there should also be a "Remove all industries" button in the "Land Generation" menu. This is useful if using a set of NewIndustries GRFs and updating to more recent versions cause glitches with some of the industries.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/1731#comment3414_

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> Reset landscape dos not fix problem FS1735
> I think SE should provide tools to replace Industry, house and other sets. It will allow to create scenarios on one land with different industry/house sets.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/1731#comment3444_

**Comment by DorpsGek** [comment]
**_SmatZ_ wrote:**

> George,
> "Likewise, there should also be an option to remove all industries from the map (I believe this is similar to TTDPatch's cht:resetindustries). Also, there could be an option to remove all towns from the map (although I suspect that in order to work, it would also have to remove all player objects and industries)."
> 
> This isn't what you are talking about?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/1731#comment3445_

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> Not exactly.
> 
> Remove industry is purge industries cheat. This is what I meant for industries.
> 
> As for houses, removing towns is not what I mean. I'd suggest the bottom "remove town houses" in the town window. This way the town name and industries would stay, and you need to place new houses only.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/1731#comment3450_

**Comment by andythenorth** [comment]
No progress for 10 years.  Let's say that this one isn't happening.  Closing it, thanks :)
