### ISSUE TITLE
Scenario Editor: two types of land tool

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#1738]
**_George_ opened the ticket and wrote:**

> R12035
> In TTDP I can open the land tool and road construction tool, that allows me to have 2 cursors for rise/lower land. I can configure them that way, that land cursor provides large area, while road cursor provides small area, and I can switch fast.
> In OTTD land cursor is removed from road tool and I have to resize the area size every second :(  that takes lots of time. I'd like to have 2 cursor for rise/lower land in land tool bar. One with small size and one with customisable size (or even two with customisable size). Alternatively, I may like to have many icons, one for every possible size :)

**Reported version**: _trunk_
**Operating system**: _Windows_

---

**Comment by andythenorth** [comment]
Closing

* This is 10 years old
* Land raise/lower is draggable, multiple fixed sizes is not adding much

We'll pass on this, thanks :)
