### ISSUE TITLE
Stations: coverage area button

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#2683]
**_collinburnell_ opened the ticket and wrote:**

> I would love to see a button on the station (interface) that, when clicked, showed the (effective) coverage area for that station... maybe using blue boxes (for each 1x1).

**Reported version**: _0.7.0-beta1_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
This is not a current priority for core OpenTTD.  A version of it is implemented as part of 'zones' in JGR's Patchpack https://www.tt-forums.net/viewtopic.php?t=73469
