### ISSUE TITLE
Scenario Editor: deleting town in editor deletes associated industries

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#2751]
**_bilbo_ opened the ticket and wrote:**

> If I build some industries, they get internally "assigned" to some town (the nearest one in build time I think).
> But if I build some industries in editor and then I decide to delete the town to which the industries belong, the industries are deleted as well. I think more intelligent would be not to delete the industries, but reassign it to another city. This makes it painful if you are placing industries - you want to remove town to make way for additional industries and those currently built (in vicinity of removed city) will disapear.

**Reported version**: _0.7.0-RC1_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_SmatZ_ wrote:**

> This won't for example work when "multiple industries of the same type per town" is not enabled. I don't know if there wouldn't be any side effects, like bank "in the middle of nothing" (+further broken newgrf restrictions - they are often broken when you build new town though). I vote for changing to Feature request and closing as "Won't implement".

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/2751#comment5817_

**Comment by DorpsGek** [comment]
**_bilbo_ wrote:**

> If you build new industry and then somehow change surroundings, you can always create "incompatible" conditions around it. Or you can turn on "multiple industries", plant gazillion of coal mines in small spot and then turn it back off.
> 
> As for the "bank in the middle of nothing" - if this is what you want to create in editor, then let it be the result. If not, you can delete the bank and keep other industries intact.
> 
> This won't affect any random games, just if someone uses the editor to create some custom land.
> 
> Not autodeleting industries is more user friendly - you can always delete them later if you really think they are not appropriate in the editor :)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/2751#comment5819_

**Comment by andythenorth** [comment]
Let's pass on this :)
* 9 years old with no progress
* reassignment is TMWFTLB 
* would need to re-name all industries also
* could conflict with newgrf industry location rules (which aren't resolvable)
