### ISSUE TITLE
AI Goto Nearest Depot / Change Servicing Interval

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#2853]
**_lhrios_ opened the ticket and wrote:**

> I like to suggest these two things:
> \* goto nearest depot order;
> \* some function that will able change the vehicle servicing interval.
> 
> Thanks.
> 

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Yexo_ wrote:**

> Goto nearest depot order has been implemented in r18518.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/2853#comment7064_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> I checked, couldn't see any way in 1.7.1 that AI can set servicing interval.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/2853#comment14686_

**Comment by TrueBrain** [comment]
Please don't add two request in one ticket.

One has been done, the other seems to be no demand for. Sorry, going to pass. Tnx though!
