### ISSUE TITLE
Resize windows when main window gets smaller than window size

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#3417]
**_planetmaker_ opened the ticket and wrote:**

> The server list window doesn't get re-sized to the main window size

**Attachments**
- [Bildschirmfoto 2009-12-24 um 10.25.48.png](https://bugs.openttd.org/task/3417/getfile/5067/Bildschirmfoto+2009-12-24+um+10.25.48.png) (158.33 KiB)

**Reported version**: _1.0.0-beta1_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> This is the behaviour for eons and technically not a bug.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3417#comment7117_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> [8:26pm] andythenorth: Alberth: does the UI have methods to resize windows when viewport changes size? https://bugs.openttd.org/task/3417
> [8:26pm] Alberth: I think so
> [8:26pm] Alberth: or at least move them back into view
> [8:26pm] andythenorth: so valid task?
> [8:27pm] Alberth: not sure, Rb claims it's not
> [8:27pm] mescalito left the chat room. (Quit: )
> [8:28pm] Alberth: maybe the window is not very resizable or so
> [8:28pm] Alberth: don't understand why Rb says that
> [8:29pm] andythenorth: he was just adjusting status
> [8:30pm] Alberth: yes, because he doesn't see it as a bug
> [8:30pm] andythenorth: industry windows are moved when I resize viewport
> [8:30pm] Alberth: I don't know why
> [8:30pm] andythenorth: so the methods exist
> [8:31pm] andythenorth: newgrf window neither
> [8:31pm] Alberth: it's just a function that walks through the window-stack 
> [8:31pm] Alberth: not all windows resize very well
> [8:32pm] Alberth: maybe they stay centered?
> [8:32pm] andythenorth: think they do
> [8:33pm] Alberth: if they do, then that technically indeed counts as not a bug
> [8:33pm] Alberth: since they are properly centered
> [8:33pm] Alberth: just not in a useful way 
> [8:33pm] Alberth: from UX pov, it counts as bug 
> [8:34pm] andythenorth: can’t fix 
> [8:34pm] Alberth: not easily, likely
> [8:34pm] andythenorth: not convinced that supporting resize-to-smaller is a big thing
> [8:34pm] andythenorth: especially at game start
> [8:35pm] Alberth: I sometimes do resize the window while playing, to make room for another window
> [8:36pm] Alberth: but in general, I agree

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3417#comment14738_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Leaving this open for now.  But very unlikely to get fixed, candidate for closure for pragmatic 'not going to happen' reason.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3417#comment14739_

**Comment by andythenorth** [comment]
Not happening.
