### ISSUE TITLE
Houses: allow sloped land under houses

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#3466]
**_George_ opened the ticket and wrote:**

> r18545
> 
> Special house "Praha hotel" intends to be build on the sloped land, where the NE tile is sloped, while the SW tile is flat.
> I use the following code
> // FF specifies the SW tile, F0 the NE tile
>   357 * 15	 02 07 FF 81 62 00 00 1F 01 F0 00 00 00 00 80
>   358 * 23	 02 07 F0 81 62 00 00 1F 03
>                  F0 00 04 04
>                  F0 00 0C 0C
>                  F0 00 00 00
>                  00 80
> 
> For CB 17, but OTTD puts a house on the tile that does not fit this rule. At the example, the SW tile is located on the 0E slope
> Is it a bug in my code or in OTTD?
> 

**Attachments**
- [ECSHousew.grf](https://bugs.openttd.org/task/3466/getfile/5172/ECSHousew.grf) (476.32 KiB)
- [Unnamed, 1st Jan 1920.png](https://bugs.openttd.org/task/3466/getfile/5173/Unnamed%2C+1st+Jan+1920.png) (46.37 KiB)
- [-to-del.sav](https://bugs.openttd.org/task/3466/getfile/5174/-to-del.sav) (616.81 KiB)

**Reported version**: _trunk_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> BTW, if I do not allow NE tile to be build on 00 slope, it does not appear at all

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3466#comment7192_

**Comment by DorpsGek** [comment]
**_Yexo_ wrote:**

> From http://wiki.ttdpatch.net/tiki-index.php?page=Callbacks# House_construction_check_17_
> "For multi-tile buildings, this callback is always called for the north tile type .... in OTTD r13489, the callback is now called for the final position of the north tile."
> 
> The callback is only called once, and only for the north tile. Your check for the southwest tile is never executed.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3466#comment7211_

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> Would it be hard to call it for every tile?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3466#comment7222_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> The callback is also supposed to check lots of other stuff (like population etc.) which you only want to call once.
> Isn't checking the adjacent tiles in the north-tile callback enough?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3466#comment7227_

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> Well, I changed the code for hotel praha as you suggest, and now I get no instance on the map. Why?
> // Slope check
>   358 * 15	 02 07 F0 81 62 10 00 1F 01 F0 00 00 00 00 80
>   359 * 19	 02 07 F0 81 62 00 00 1F 02
>                  F0 00 04 04
>                  F0 00 0C 0C
>                  00 80
> 

**Attachments**
- [ECSHousew.grf](https://bugs.openttd.org/task/3466/getfile/5201/ECSHousew.grf) (486.14 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3466#comment7228_

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> Also, when I allow northern tile to be flat, I get the house located on land with non-flat southern tile
> // Slope check
>   359 * 15	 02 07 F0 81 62 10 00 1F 01 F0 00 00 00 00 80
>   360 * 23	 02 07 F0 81 62 00 00 1F 03
>                  F0 00 04 04
>                  F0 00 0C 0C
>                  F0 00 00 00
>                  00 80
> 

**Attachments**
- [-to-del.sav](https://bugs.openttd.org/task/3466/getfile/5202/-to-del.sav) (617.02 KiB)
- [Sudhall Transport, 13th Jan 1960.png](https://bugs.openttd.org/task/3466/getfile/5203/Sudhall+Transport%2C+13th+Jan+1960.png) (55.92 KiB)
- [ECSHousew.grf](https://bugs.openttd.org/task/3466/getfile/5204/ECSHousew.grf) (486.13 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3466#comment7229_

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> Sorry, looks my fault here, should be 01, not 10

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3466#comment7230_

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> Changed 10 to 01, but it does not apppear

**Attachments**
- [ECSHousew.grf](https://bugs.openttd.org/task/3466/getfile/5205/ECSHousew.grf) (486.07 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3466#comment7231_

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> and appears if flat northern tile is allowed 
> // Slope check
>   359 * 15	 02 07 F0 81 62 01 00 1F 01 F0 00 00 00 00 80
>   360 * 23	 02 07 F0 81 62 00 00 1F 03
>                  F0 00 04 04
>                  F0 00 0C 0C
>                  F0 00 00 00
>                  00 80
> 

**Attachments**
- [ECSHousew.grf](https://bugs.openttd.org/task/3466/getfile/5206/ECSHousew.grf) (486.07 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3466#comment7232_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Ok, the grf defines the following house:
> House 0xA1 in NE, house 0xA2 in SW.
> It requires the SW tile to be flat, and the NE tile to be sloped with either East corner raised or North&East corner raised.
> So far so good.
> 
> The problem is:
> Callback 17 can only restrict the possible house locations and not allow "more".
> A normal 2x1 house is build on two adjacent tiles which get a leveled platform. For that OTTD checks that the platforms have equal heights. But with above slope combination the tiles do not have equal heights.
> 
> So maybe we need a new flag in property 19 to disable any default slope checks.
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3466#comment7249_

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> Yes

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3466#comment7250_

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> BTW, what does the status "Waiting on reporter" mean?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3466#comment7262_

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> It means that at some moment "we" needed a reply from you.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3466#comment8381_

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> And why didn't contacted me then? ;)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3466#comment8382_

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> It was changed to that just after one of the developers asked you a question. If you email address was correct at that point you would have gotten an email with the question (which is now over half a year old though). Same way that you should receive an email about this comment.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3466#comment8385_

**Comment by andythenorth** [comment]
8 years old.  Not currently a goal.  We'll pass on this thanks :)
