### ISSUE TITLE
Timetable: skip order should not change time table start date

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#3581]
**_kvtb_ opened the ticket and wrote:**

> I've a set up a system where trains drive according to a specific schedule.
> For each train I've set the start date for that train.
> 
> If a train has a delay, I'd like to be able to let the train skip one order, but then without affecting the scheduled arrival/departure dates.
> 
> What currently happens is that when skipping an order, all scheduled arrival/departure dates are changed, and the delay of the train is not minimized at all.
> This feature request is to change the behaviour as follows; 
> \- skipping an order should not affect the scheduled arrival/departure dates
> \- at the next station, the train will arrive a bit early, causing the delay to be shortened or even disappear.
> 
> 
> This way, the train will always drive according to the start dates I've set in the past (after carefully calculating the most optimal start date for each train)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
8 years old, also TMWFTLB.  Closing as we're clarifying priorities.  Thanks.
