### ISSUE TITLE
Scenario Editor: Loading *.sav

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#3596]
**_Ammler_ opened the ticket and wrote:**

> As it is already possible to load a renamed save to the Editor. It could save some hassle if you make it possible to load also usual saves.
> 
> Of course, saving to *.sav isn't needed and would be a overwrite protection as the Editor "cleans up" some stuff there.
> 
> Greets
> Ammler

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
Sounds too simple not to support.

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
