### ISSUE TITLE
Clip vehicles at border of tunnel tile

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#3606]
**_arie__ opened the ticket and wrote:**

> Problem with the ordering of sprites I guess. Tried latest windows cargodist, beta 4 and latest trunk builds. Tried with and without grphs. Did not supply a save game as it is easily reproducible and the screenshots are clear enough as well. It's all about the trains entering and leaving a tunnel, the trains sometimes partly visible.
> 
> used versions: 
> openttd-trunk-r19061-windows-win32
> openttd-1.0.0-beta4-windows-win32
> g920ffd74-cargodist_win32
> 
> OS:
> Win XP

**Attachments**
- [Grenington Transport, 1945-03-22.png](https://bugs.openttd.org/task/3606/getfile/5560/Grenington+Transport%2C+1945-03-22.png) (125.44 KiB)
- [Sarfingbridge Transport, 1945-02-25.png](https://bugs.openttd.org/task/3606/getfile/5561/Sarfingbridge+Transport%2C+1945-02-25.png) (72.61 KiB)
- [Sarfingbridge Transport, 1945-04-29.png](https://bugs.openttd.org/task/3606/getfile/5562/Sarfingbridge+Transport%2C+1945-04-29.png) (118.68 KiB)
- [Sarnley Transport, 1945-01-23.png](https://bugs.openttd.org/task/3606/getfile/5563/Sarnley+Transport%2C+1945-01-23.png) (115.31 KiB)
- [Sarnley Transport, 1945-01-28.png](https://bugs.openttd.org/task/3606/getfile/5564/Sarnley+Transport%2C+1945-01-28.png) (118.07 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_arie__ wrote:**

> My bad, uploaded a wrong screenshot, nothing to see on the second pic I think.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3606#comment7568_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> The sorting of the sprites is correct: The tunnel is drawn in front of the vehicle. Just the vehicle is bigger than the tunnel covers.
> 
> As this has been reported multiple times, I changed it into a feature request for clipping vehicle sprites at the border of tunneltiles (which might somewhat work with existing "SubSprite"-mechanism), so the tunnels would not rely on vehicles being not too big.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3606#comment7569_

**Comment by DorpsGek** [comment]
**_arie__ wrote:**

> I'm terribly sorry for reporting this then, I had searched but hadn't found relevant topics (do not remember the search phrases).

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3606#comment7570_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Candidate for closure IMHO, think this is unlikely to be changed.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3606#comment14742_

**Comment by andythenorth** [comment]
Still no more likely 6 months later.  Let's pass on this one, thanks :)
