### ISSUE TITLE
Make it possible to make RTL aware vehicle purchase graphics

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#3608]
**_dnd_man_ opened the ticket and wrote:**

> in train depot, when creating a train in RTL mode, and graphics of the locomotive is the opposite then usual.
> attached a screen-capture showing this.

**Attachments**
- [1959-05-28 ,Cardstone Transport.png](https://bugs.openttd.org/task/3608/getfile/5567/1959-05-28+%2CCardstone+Transport.png) (354.56 KiB)

**Reported version**: _trunk_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> That's because it's designed (or coded) to do it like that.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3608#comment7574_

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> By the way, the 'ok' and 'backwards' engines look exactly the same. Furthermore the 'build engine' window can't turn the engines around in the window as those images are (for at least a number of NewGRFs) not the same as the actually build engines. You can see this especially well with the 2cc train set.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3608#comment7575_

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> Once NewGRFs have support for it too we can flip the graphics

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3608#comment7584_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Probably just flip the buy menu sprite no?  Lighting will be wrong, but eh, life is short, perfection is attained one step at a time, other greetings card lines are available etc. 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3608#comment14547_

**Comment by andythenorth** [comment]
8 years old.  Not currently a goal.  Would be 'broken' with sets that have text or flags directly in the purchase sprite pixels.  Closing, thanks.
