### ISSUE TITLE
Orders: different STR_ORDER_GO_TO for each transport type

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#3848]
**_perk11_ opened the ticket and wrote:**

> In Russian there is no good translation of "Go To" which will mean "Go To" for train, road vehicle, aircraft and ship at the same time. The current translation is quite irregular. And in English it may be replaced with "Fly to", "Sail to", "Drive to" for non-train transport types too to be more exact.

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> Doing so means duplicating a lot of strings because it arguably isn't just STR_ORDER_GO_TO, but also STR_ORDER_GO_NON_STOP_TO, STR_ORDER_GO_VIA, STR_ORDER_GO_NON_STOP_VIA, STR_ORDERS_GO_TO_NEAREST_DEPOT, STR_ORDERS_GO_TO_BUTTON (after all, the button should say the same, right?), STR_ORDERS_GO_TO_WAYPOINT, STR_ORDERS_GO_NON_STOP_TO_WAYPOINT. Then probably the STR_ORDER_SERVICE_AT and STR_ORDER_SERVICE_NON_STOP_AT strings as well.
> 
> You make it seem like there is no translation for "Go to Paris" if you do not know the means of transportation. That's something I can't quite believe.
> 
> I'm quite hesistant to adding 30 strings that are a copy of some other string. It only adds to the translator's burden.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3848#comment8368_

**Comment by DorpsGek** [comment]
**_perk11_ wrote:**

> People always know the means of transportation when they refer to transport, not a person (you can say "Go to Paris" about the person in Russian). There are some translations, but none of them are applied both good for land, sea and air ways of transportation. Just see a number of translations for a word "go" http://lingvo.yandex.ru/go/с%20английского/ . (it BTW doesn't include those which I think the most suitable)  Adding those strings could also make an English and other variants of game richer as well.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3848#comment8372_

**Comment by DorpsGek** [comment]
**_lain_ wrote:**

> As i remember, order texts look like that:
> Go to $somewhere
> Go non-stop to $somewhere
> Go [non-stop] via $somewhere
> 
> Maybe easier will be to add strings like:
> STR_ORDERS_GO_TRAIN = "Go"
> STR_ORDERS_NON_STOP = "non-stop"
> STR_ORDERS_VIA = "via"
> STR_ORDERS_TO = "to"
> 
> and combine them in orders menu?
> And if there will be a separate order text for each vehicle type, translation in the language like Russian, where:
> >>There are some translations, but none of them are applied both good for land, sea and air ways of transportation.
> As perk11 said, will look better.
> 
> P.S. sorry for any mistakes, English is not my native language.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3848#comment9237_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Persuaded to reopen by Perk and Eddi.  I don't see splitting translations as bad, it's copy-paste for translators in some languages, and provides a better result in other languages where the context changes the required word(s).

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3848#comment14551_

**Comment by TrueBrain** [comment]
Fully agree with Eddit and Perk, and disagree with Rubidium (sorry). We did often a few things so translations fit. And I agree, 30 copies is annoying .. but we either support other languages or we don't :D (we also have this insane system for numbers and their plural form).

What I do wonder, if this can be done smart with sub-strings or something? Or some other clever solution to make it a bit easier?

**Comment by nielsmh** [comment]
Outside of making 3x, 4x, or 5x the number of every "Go (non-stop) to/via" string, which will be pointless in most translations, perhaps a new string formatting feature for optional case-parameterised strings would be relevant.

Idea: `{0:CASE:"train"}Run to{0:CASE:"road"}Drive to{0:CASE:"ship"}Sail to{0:CASE:"air"}Fly to{0:CASEELSE}Go to{ENDCASE} {STATION}`
