### ISSUE TITLE
Railtypes: support for variable or callback "station has_roof"

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#3914]
**_planetmaker_ opened the ticket and wrote:**

> When using railtypes and station newgrfs together, one will end up with snowy tracks in stations above the snow line - even though the stations feature a nice snow-proof roof.
> 
> In order to allow drawing the correct track sprites it'd be nice to have a variable available which returns "has_roof" for a given track tile which can be set by a station set which supports this feature.
> 
> A bit open question is as to what to report back in cases where this bit is not set; most probably 'no roof' should be the default as then the result is obtained which a simple terrain check yields.
> 
> Or, optionally, one could build on this and define a variable which is not a boolean one but a three or more values variable: no_station, station, and station_with_roof. Then the newgrf authors could decide themselves what to do, IF they also know the newgrf which supplies this station tile.

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> If there would be such a variable, it should also tell about station-supplied groundtype. E.g. concrete or plain earth.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3914#comment8213_

**Comment by DorpsGek** [comment]
**_mb_ wrote:**

> > When using railtypes and station newgrfs together, one will end up with snowy tracks in stations
> > above the snow line - even though the stations feature a nice snow-proof roof.
> 
> This is a non-existent problem.
> 
> The real problem with railtypes and snow is #6407 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3914#comment14707_

**Comment by andythenorth** [comment]
https://wiki.openttd.org/Frosch/ButGroundTypes :P

**Comment by andythenorth** [comment]
Let's close, it's not a current priority :)
