### ISSUE TITLE
Hotkey configuration - display of pressed key combination

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#3943]
**_Zuu_ opened the ticket and wrote:**

> Since OpenTTD uses a semi-US-qwerty keyboard layout it can be fairly hard to figure out what a desired keyboard combination translates to in the hotkeys.cfg file. 
> 
> Therefore, it would be highly usefull if something similar to the keyboard logger part of the xev tool could be added to OpenTTD. It would eg. display CTRL+MOD+T or whatever a key combination corresponds to in the semi-US-qwerty layout that OpenTTD uses.
> 
> 
> A more complete solution would be to allow in-gui changes of the hotkeys. But just having a tool that supply the text strings to enter the hotkeys file would help a lot in more complicated cases. 

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
Would be nice.  But pragmatically, not happening.  8 years old, so closing :)
