### ISSUE TITLE
Location History in Mainwindow

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#3977]
**_chu_ opened the ticket and wrote:**

> There would be a great improvement in usability if the main window could store a list of recently seen locations.
> 
> Using hotkeys, this list could be browsed backward (and even forwards).
> 
> Why?
> Imagine you play on a lare map, with hundereds of industries and vehicles.
> You are building somewhere a larger infrastructure. And then a message appears about a train being lost, a industry being closed or started.
> You want to have a look at that situation. So you click on the appropriate object to move the main window to that place.
> After examining that situation, you want to go back where you were builduing your new station. But where is it?
> If you are lucky, you can see some brown underground-texture, when you made a lot of terraforming. But if not?
> 
> Using that hotkey, you would simply press the hotkey until you are back at your building-site.
> 
> ok. thats all :-)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Krille_ wrote:**

> When I need to go back to a position I open a window of some building in that area and stick it to the corner of the screen. When I want to go back I do so by clicking the Location button. You could also open another viewport to quickly look somewhere.
> 
> However your suggestion sounds interesting. One question you didn't exactly define is when to make an entry in the list. It could be done automatically when clicking on a Location button (didn't look if this is possible without touching every window that has one) or manually with a hotkey. Are there more options? Sounds somewhat like a question that belongs into the forums and not here.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3977#comment8415_

**Comment by DorpsGek** [comment]
**_Krille_ wrote:**

> I just noticed there's already work on this idea:
> http://www.tt-forums.net/viewtopic.php?f=33&t=42556
> 
> Didn't check if the patch still works with recent versions.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3977#comment8434_

**Comment by DorpsGek** [comment]
**_Terkhen_ wrote:**

> That patch won't work with recent versions: it is too ancient and probably conflicts with the new hotkeys feature. Besides, I think that the idea of just storing points without any GUI is flawed. I have been toying with the idea of allowing to store positions in the map or even (maybe?) vehicles into a list. These positions could then be copied to a viewport or the main window (expanding the current viewport copy paste feature). Using configurable (global) hotkeys, it would allow quick store and restore of locations. I need to think more about this concept, any suggestions are welcome.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3977#comment8457_

**Comment by TrueBrain** [comment]
Not currently part of the Roadmap. We welcome any Pull Request that implements this (properly).
