### ISSUE TITLE
Audio: cycle through music sets

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#3997]
**_LordAro_ opened the ticket and wrote:**

> what it says on the tin.
> 
> add some variety to the music playing

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> From irc:
> 
> LordAro: #6090 is about changing the selected music set
> LordAro: (when in game)
> LordAro: #3997 is playing all of them

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3997#comment14643_

**Comment by TrueBrain** [comment]
Cool idea! A Pull Request would be even better :) Low priority, so sorry, closing issue.
