### ISSUE TITLE
Lag counter

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4065]
**_TruePikachu_ opened the ticket and wrote:**

> Some 3D games have the option to display the current framerate. A possible feature (as in it can be turned on or off) for OpenTTD would, in the status bar thing, display two more numbers:
> a) Draw framerate - A value in FPS conforming to how fast screen data changes are being made
> b) Execution rate - A value which tells you how long each 'tick' is divided by 30ms, in percent. This would tell you the current rate of which the game itself is running, so you can tell if it is lagging (<100%), or how fast it's going if you have Fast Forward turned ON (>100%)

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_TruePikachu_ wrote:**

> Yes, I know Ottd is not 3-d, but my computer is sluggish, and I want to know how sluggish

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4065#comment8604_

**Comment by DorpsGek** [comment]
**_dihedral_ wrote:**

> Have a look at 3dmark and compare your results on the web.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4065#comment8874_

**Comment by TrueBrain** [comment]
I think this is an awesome idea, to have an FPS counter and UPS counter. But given in 8 years nobody else asked for it .. low priority I guess. As such, closing the ticket.

Always feel free to make a Pull Request that implements this!
