### ISSUE TITLE
Default company color setting

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4115]
**_ABCRic_ opened the ticket and wrote:**

> 99% of the time, I use Green as my company color, which means that I have to change it to Green nearly every game I start.
> It would be much more convenient to have a 'Default Company Color' setting, maybe under Advanced Settings > Interface, telling the game the color that should be used as the color for Company 1.
> 
> Could this be implemented?

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_TruePikachu_ wrote:**

> Yes, it could, and quite easily too, without advancing savegame version. I can't write a patch for it right now, however, as I don't know how to set up new options. I think that, in Advanced OPtions\Interface, there could be 'Default Color' which cah have values for the names of the 15(?) colors and 'Random'
> 
> EDIT: Only skimmed your post, sorry for restating idea

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4115#comment8767_

**Comment by TrueBrain** [comment]
Love the idea!

**Comment by andythenorth** [comment]
It's done.  Nice feature.

Thanks for the suggestion, thanks for the implementation!

**Comment by ABCRic** [comment]
A happy surprise to see this added even eight years after my original suggestion 😄
Thank you for keeping this great game going!

**Comment by andythenorth** [comment]
@ABCRic nice that you found us on GitHub too :)  Thanks for suggesting!
