### ISSUE TITLE
Console: copiable text in console & clickable hyperlinks in chat/console

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4122]
**_Mek_ opened the ticket and wrote:**

> Copiable text in console & clickable hyperlinks in chat/console - would be very useful, especially for server admins.

**Reported version**: _1.0.3_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
This would be useful, but currently it's not a priority, so closing, thanks :)
