### ISSUE TITLE
Stations: changes to building 'too close to another station'  

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4185]
**_Moriarty_ opened the ticket and wrote:**

> Following on from # 4183, it seems that it is possible for the player to build a station next to another station if they know the magic key (Control).
> This "Bug" (which could be considered a feature request, your choice), is basically to point out that this is inconsistent with what happens when the user simply clicks to place a station next to an existing station belonging to another player. If you do that it says you're too close to another station. As noted this is inconsistent and thus doesn't really bode well for the player, especially not ones who haven't discovered the magic Control key.
> 
> I would suggest removing the "too close to another station" message when building next to an enemy company station if the magic key isn't pressed.

**Attachments**
- [Clipboard02.png](https://bugs.openttd.org/task/4185/getfile/6769/Clipboard02.png) (576.79 KiB)

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Krille_ wrote:**

> Since a while I intend to make a patch which opens the selection window in this case without having to press Ctrl, but didn't get around to it yet. It could also be done when the location adjoins more than one existing station. Or don't consider foreign stations in these decisions at all.
> 
> BTW: There's also an option which modifies this behaviour.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4185#comment8987_

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> Having that window pop up every time you try to build a station (part) is probably way more annoying than not knowing you can do something because you didn't read the manual.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4185#comment8997_

**Comment by DorpsGek** [comment]
**_Moriarty_ wrote:**

> Rubidium - That's a logical fallacy: many players are old players, myself included. Such people don't re-read the manual every couple of months. Frankly you shouldn't be requiring or expecting the manual to be read either except for advanced/complicated features (i.e., signal setups).
> 
> My own suggestion was as follows (but to clarify):
>     1) If Building immediately next to an enemy another station: Just build there. Presently requires magic-key.
>     2) If building outside of the "maximum size" of another of your own stations: Just build there. Exact same as present.
>     3) If building within the "maximum size" or whatever the variable is called, of another of your own stations, pop up a window that gives the player a choice of what to do.
> 
> It could get annoying as Rubidium noted, but otherwise you've got hidden functionality.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4185#comment9002_

**Comment by DorpsGek** [comment]
**_planetmaker_ wrote:**

> I don't see 3) happening. Given a possible station size of 64 tiles (subject to adv. settings), it'd mean to have this window pop up virtually at every station being build. Granted, 1) would be nice and current behaviour seems a bit inconsistent, the same is true when building adjacent to two stations which you own yourself.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4185#comment9003_

**Comment by DorpsGek** [comment]
**_Kogut_ wrote:**

> I suggest to implement as
> If Building immediately next to an enemy another station (if there is no more than one your station next to placed station): Just build there. Presently requires magic-key.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4185#comment9199_

**Comment by andythenorth** [comment]
8 years old, no clear outcome.  Let's move on :)
