### ISSUE TITLE
Signals: path signals for tunnels and bridges

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4196]
**_palzkillm_ opened the ticket and wrote:**

> Hi,
> 
> to go along with the other cheat functions or maybe as a general enhancement, I would suggest to add path signals for tunnels and bridges. This would allow for larger constructions to be used more efficiently.
> 
> From an interface perspective, the best way to handle this would surely be to be able and use the normal signal interface on tunnels and bridges.
> An easier way to solve this could be to add a context menu to tunnels and bridges where the path signal could be set or unset, but only for the entire construction.
> 
> Marco

**Reported version**: _1.0.4_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_private_paula_ wrote:**

> HackaLittleBit allready has a patch including this feature.
> Maybe the devs can have a look at it for easy and fast implementation ;)
> 
> http://www.tt-forums.net/viewtopic.php?f=33&t=41260&start=0# p754200

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4196#comment10304_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Flyspray clean up: possibly a long term goal for OpenTTD, but difficult to implement cleanly.  Not a current goal for OpenTTD, so reducing priority.
> 
> Eddi has looked at the HackaLittleBit patch and believes that it's not a viable solution, and would create a development dead end for other related features.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4196#comment14559_

**Comment by andythenorth** [comment]
Classic big pony.  It's known that the feature is wanted, but it has serious implementation challenges, and nobody wants to push it through.

So let's pass on this one :)
