### ISSUE TITLE
Console: start_all_ais console command

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4216]
**_Kogut_ opened the ticket and wrote:**

> start_all_ais console command
> 
> to avoid typing start_ai + enter 
> \+ up arrow + enter
> \+ up arrow + enter
> \+ up arrow + enter
> \+ up arrow + enter
> \+ up arrow + enter
> \+ up arrow + enter
> \+ up arrow + enter
> \+ up arrow + enter
> \+ up arrow + enter
> \+ up arrow + enter
> \+ up arrow + enter
> \+ up arrow + enter
> \+ up arrow + enter
> \+ up arrow + enter
> 

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_MagicBuzz_ wrote:**

> \-- Ignore this patch, there is a bug in it --

**Attachments**
- [cmd_all_ais_r21200.patch](https://bugs.openttd.org/task/4216/getfile/6834/cmd_all_ais_r21200.patch) (3.66 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4216#comment9089_

**Comment by DorpsGek** [comment]
**_MagicBuzz_ wrote:**

> Here is a patch that contains 3 new console commands :
> 
> start_all_ais : No arguments. Starts all non-running AIs (take care : number of AI that will start is egual to the parameter "_settings_game.difficulty.max_no_competitors".
> stop_all_ais : No arguments. Stops any running AI.
> reload_all_ais : No arguments. Stops then restarts any running AI.

**Attachments**
- [cmd_all_ais_r21200.patch](https://bugs.openttd.org/task/4216/getfile/6835/cmd_all_ais_r21200.patch) (3.65 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4216#comment9090_

**Comment by DorpsGek** [comment]
**_MagicBuzz_ wrote:**

> Fixed a compilation warning when comparing int and uint

**Attachments**
- [cmd_all_ais_r21200.patch](https://bugs.openttd.org/task/4216/getfile/6836/cmd_all_ais_r21200.patch) (3.65 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4216#comment9091_

**Comment by DorpsGek** [comment]
**_MagicBuzz_ wrote:**

> Change:
> \- Renamed start_all_ais by start_all_ai
> \- Renamed stop_all_ais by stop_all_ai
> \- Renamed reload_all_ais by reload_all_ai
> => AIs in lower case doesn't look natural
> 
> Added Feature:
> \- start_all_ai now supports an argument <AI count>. It's the desired total AI count.
> 
> Fix:
> \- start_all_ai now doesn't start more AIs than desired. IE when already running AIs, it will start <AI count> - <Already running AIs> new AIs.

**Attachments**
- [cmd_all_ai_r21218.patch](https://bugs.openttd.org/task/4216/getfile/6842/cmd_all_ai_r21218.patch) (4.85 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4216#comment9107_

**Comment by andythenorth** [comment]
Nothing for 8 years, let's move on :)  Happy to re-open if needed.
