### ISSUE TITLE
Scenario Editor: build rough land

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4305]
**_alocritani_ opened the ticket and wrote:**

> Is it possible to add the possibility to build rough land in scenario editor? At the moment the only way to create it is using the delete tool on a normal grass tile and it will randomly "reborn" as rough land.
> 

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Belugas_ wrote:**

> You have to understand that this rough land would not stay rough for long.
> The tile process would change it to grass (or else)  quite fast.
> Any reason for that request?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4305#comment9255_

**Comment by DorpsGek** [comment]
**_alocritani_ wrote:**

> No special reason, but if we can create rock we should be able to create rough land
> Just to be clearer, I'm talking about rough land (dark green one) not bare land (brown one - that came when you delete a tile and came back to normal grass in few days)
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4305#comment9257_

**Comment by DorpsGek** [comment]
**_Belugas_ wrote:**

> Oh... right... silly me, sorry.  I understand your point

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4305#comment9258_

**Comment by andythenorth** [comment]
8 years no change.  I have no objection to this idea, but nobody's pushing it through, let's prioritise it out :)
