### ISSUE TITLE
Industries: more information during CB 3B effect 1

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4310]
**_George_ opened the ticket and wrote:**

> R21503 
> 
> Control special industry effects (3B) effect 1 (cut nearby trees periodically)
> Would it be possible to know the distance to the nearest tree before cutting it? (To have sawmills with different to tree range, and also to allow some industries to keep some free space around (planned for oil refinery for example for better support of some tiles, which overlap nearby land tiles).

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> P.S. please fix the typo in the task

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4310#comment9263_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Note that every cut tree produces 45 items of output cargo.
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4310#comment9264_

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> Would be nice to control that too. At least specify multipliers for cargo 1 and 2. 2 words, lets call them M,N, meaning prod cargo 1 = 45*M/256, prod cargo 2 = 45*N/256. So setting M and N = 0 would produce 45*0=0 tons of cargo

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4310#comment9271_

**Comment by andythenorth** [comment]
Nice, but being pragmatic, won't be done.  8 years old, so closing, thanks.
