### ISSUE TITLE
Mapgen: option to preview heightmap of new game random map

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4322]
**_ukobach_ opened the ticket and wrote:**

> Summary: Request for option checkbox on Newgame menu that shows heightmap preview of randomized map.
> 
> Explanation: The purpose of this option is to speed up new game setup, allowing bad maps to be discovered immediately and a new one regenerated before industries are placed and map started.
> 
> 
> 
> PS: An additional comment on random map games, more advanced options in the menu for tweaking map generation parameters is greatly desired. (example: [ ] create lateral mountain range, or [ ] large inland sea, or [ ] group small cities radially from large ones, [ ] no lakes just rivers, [ ] cities follow rivers, anything like this or even more generic)
> 
> 

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> Instead of coding this in OpenTTD, wouldn't it be more useful to have this functionality in a separate program?
> 
> As a first step, one could code an algortihm that behaves like you suggested, delivering a height map.
> A next step could be to encode the additional information in some way (eg an INI file), and give it to the OpenTTD program.
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4322#comment9305_

**Comment by DorpsGek** [comment]
**_Krille_ wrote:**

> If doing an external landscape generator I see to options:
> 
> Have the program create a heightmap file to be imported by the existing heigthmap support in OpenTTD.
> 
> Or move the functions to write a savegame into a library or allow to compile them either into the main game or a library. Do the same for needed terraforming algorithms. Then the program could create savegame files to load into the scenario editor.
> 
> The latter approach would allow more detailed control over the created map but requires more effort also.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4322#comment9315_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Discussion with frosch indicates this is _probably_ a goal for OpenTTD.  'Maptopia'. :P . 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4322#comment14703_

**Comment by TrueBrain** [comment]
Although the idea is great, we are going to pass for now :)
