### ISSUE TITLE
Provide CC for sprite 3097

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4336]
**_George_ opened the ticket and wrote:**

> R21646
> OTTD uses sprite 3097 in the company window to represent colour scheme. It would be nice to apply 2CC to it, so it would be possible to see not only the primary, but also the secondary colour of the company. 

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
This would need to be done in all basesets.  Pragmatically, it won't happen.  I do think it would be good to see the 2CC in the company window though.
