### ISSUE TITLE
Choose layout number while building the industry

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4365]
**_George_ opened the ticket and wrote:**

> R21646
> 
> It would be nice when building the industry with several possible layouts to specify layout number to build. When building, it would be nice to mark not only one tile with white border (under cursor), but all tiles of the industry. Because the layout is selected, all tiles location is known, so it should be no questions where to display the industry tiles. Also, it would be also nice to mark the tiles with red, which would not become industry tiles, but are checked to be free (like for oil rig for example).

**Reported version**: _trunk_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> George - there's a similar need to control layouts in FIRS.
> 
> If fs # 4131 was implemented, you would be able to 'specify' layout by checking it during cb28 and rejecting if not correct (the game would then try another layout).
> 
> This might require a new return value 'try a different layout' (haven't checked).  
> 
> This could be a source of deadlocks (game locks up trying to find correct layout at random).
> 
> Frosch had some thoughts on this some while ago.
> 
>  http://bugs.openttd.org/task/4131

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4365#comment9408_

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> It is possible to restrict specified layout during CB 28 (already used it in ECS)
> My question was to allow the user select the layout to build from the allowed list.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4365#comment9409_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> UI for this would be hard, as it would likely need to preview the entire layout, similar to airports.  I am not sure this one is a goal for OpenTTD, but I am leaving it open for now.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4365#comment14580_

**Comment by andythenorth** [comment]
Building specific layout numbers won't be implemented.  Industry layout choice is random by design.
