### ISSUE TITLE
Industries do the terraforming before construction 

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4366]
**_George_ opened the ticket and wrote:**

> R21683
> 
> Everybody knows :) how hard to prepare the ground to build the ECS Tourists centre. 
> The high map landscape generator transforms the image to the landscape. 
> So, it would be nice to allow the industry to return a real sprite (image) via CB (or define it with some other way) to make land terraforming before building the industry, based on this real sprite.

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Considered hard.  IMHO it's a valid goal though, just not currently.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4366#comment14579_

**Comment by andythenorth** [comment]
Pragmatically, there isn't anybody who's going to push this one through.  It's a nice feature that I could make use of in FIRS.  But it's not going to happen and we need to clarify priorities, so closing.
