### ISSUE TITLE
List AI-Libraries in console

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4372]
**_fanioz_ opened the ticket and wrote:**

> Request:
> \-a console command, something like : list_ailibraries (as complement of "list_ai")
> 
> Purpose:
> \-List any AI libraries (with their version) that is recognized by OpenTTD
> 
> thanks.

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Yexo_ closed the ticket.**

**Reason for closing: _Implemented_**

> In r21703

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4372_

**Comment by minchinweb** [comment]
The command is `list_ai_libs`
