### ISSUE TITLE
Houses can check classes of other sets houses

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4389]
**_George_ opened the ticket and wrote:**

> R21699
> [19:14:16] <George> Hi. When a house check for other houses of the specified class, does it check houses of the current set, or houses of every house set loaded?
> [19:21:35] <frosch123> classes are shared accross all houses independent of the grf
> [19:22:29] <frosch123> hmm, no
> [19:23:04] <frosch123> every grf has its own classes
> 
> Would it be possible to have a check for houses classes of the other GRFs too, so house GRF could cooperate?

**Reported version**: _trunk_
**Operating system**: _Windows_

---

**Comment by andythenorth** [comment]
7 years, no progress.  I think that k by default we've passed on this feature.  Closing, thanks :)
