### ISSUE TITLE
Trains: var4A in purchase list (current railtype)

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4410]
**_mb_ opened the ticket and wrote:**

> It would be nice to get var4A (current rail type for trains) available in the purchase list. I´m using different values for net load depending on rail type, and it would be beneficial for the player to see it in advance in the purchase list.
> 

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> The current railtype would be the railtype of the depot, right? But what when there is no depot, e.g. the available engines list that you can open from the vehicle list's window.
> 
> I assume you want to get the railtype's label, right?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4410#comment9485_

**Comment by DorpsGek** [comment]
**_mb_ wrote:**

> > The current railtype would be the railtype of the depot, right? 
> 
> In this case, yes. (Because the vehicle is not yet built.)
> 
> > But what when there is no depot, e.g. the available engines list that you can open from the vehicle list's window.
> 
> Mmh? Ah yes, there´s another scroll down menu ... never realised it. Well, this list seems to include *all* vehicles. So, it lacks the "filter functionality" of a depot, so to say. Well, that´d be OK, as a list of vehicles from every depot type, it´d simply display the max value for a particular vehicle. 
> 
> > I assume you want to get the railtype's label, right?
> 
> Yes: "the lower byte (rr) contains the (translated) rail type the train vehicle is currently driving on."

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4410#comment9488_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> I guess the variable would need to return some special value like 0xFFFFFFFF for the "available vehicles"-list, autoreplace-gui, newspaper and vehicle-preview.
> 
> However, there are way too many places where the depot-railtype would need passing to various callbacks and similiar though. Making it very hard to implement unless maybe using some treacherous global variables set and reset by the purchase list.
> 
> Would it be enough, if this was only available for callback 23 (additional text)?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4410#comment9500_

**Comment by DorpsGek** [comment]
**_mb_ wrote:**

> > However, there are way too many places where the depot-railtype would need passing to various > callbacks and similiar though. Making it very hard to implement unless maybe using some 
> > treacherous global variables set and reset by the purchase list.
> 
> I was under the impression that the depot already "knows" about the current railtype (hence its selection of vehicles), and thus it should be "manageable". :)
> 
> > Would it be enough, if this was only available for callback 23 (additional text)?
> 
> It would be helpful, at least.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4410#comment9501_

**Comment by andythenorth** [comment]
No progress on this in 7 years, let's assume we've passed on it.  Can re-open in future if someone is prepared to push this through.

**Comment by andythenorth** [comment]
The issue is closed, and it's fiddly to implement.

That said, for vehicles that vary stats by railtype (e.g. power etc), it would be a better UI if the purchase menu could show the stats for current depot.  

I don't know how the 'available trains' non-depot case would be handled at all though.
