### ISSUE TITLE
Scenario Editor: relocate centre-of-a-town-tile

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4459]
**_arie__ opened the ticket and wrote:**

> This is a feature request with a very low severity: the possibility to relocate the centre-of-a-town-tile while in scenario editor.
> Why? I'm currently working on a scenario/game for the start screen and I'm well on the way of finishing it, however, now I run into an issue where I want to relocate a town, but because of roads and industries being linked to the town I would rather not delete it and build a new one.

**Reported version**: _1.1.0-beta4_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
Nice, but TMWFTLB.  Cleaning issues to clarify priorities, closing this one thanks.
