### ISSUE TITLE
Railtypes: improve snow transition 

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4573]
**_dandan_ opened the ticket and wrote:**

> This is related to #2071.
> 
> The snow transition (especially with a variable snowline) has never really looked so great around rails and roads because, unlike ground tiles, rails and roads have only two stages: snow or no snow (see screenshot).
> 
> I think for rails coming from new railtypes, this could be improved without the need for more sprites: Since the new rail sprites typically only cover part of the tile, the tile underneath should not be restricted to only two stages. It would also look better to use the snowy rail sprites only on tiles that are completely covered in snow. 
> 
> Technically this would require two changes:
> 
> 1) The ground sprite under a new rail type should behave in the same way as an empty ground tile.
> 2) Variable 40 for railtypes should only report 4 (=on or above snowline) when in the completely snowy region.
> 
> These two suggestions are kind of independent. If 1) cannot easily be done because of the way information is stored in the map array (I have no clue), then 2) would still be an improvement IMO. It is also possible that 1) without 2) would work better. Any thoughts?

**Attachments**
- [snowtransition.png](https://bugs.openttd.org/task/4573/getfile/7440/snowtransition.png) (21.67 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_planetmaker_ wrote:**

> In principle 1) is possible, but it might want to be embedded in the bigger context of FS # 2071. IIRC SmatZ had an interesting patch on this topic, but I don't know anymore the details of the discussion around it.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4573#comment9827_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Railtypes have var 40, but lack any equivalent to industry var 60, which includes tile height.
> 
> https://newgrf-specs.tt-wiki.net/wiki/VariationalAction2/Railtypes# Terrain_type_.2840.29
> https://newgrf-specs.tt-wiki.net/wiki/VariationalAction2/Industry_Tiles# Land_info_of_nearby_tiles_.2860.29
> 
> If tile height is known, partial snowing can be calculated by subtracting from global snowline var.  This mechanic is proven for industries in FIRS and other places.
> 
> This does look worth solving, IMHO, but I don't know whether it has performance or MP implications.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4573#comment14696_

**Comment by andythenorth** [comment]
See also #6407 - fixing one might entail fixing the other.  Or not.

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
