### ISSUE TITLE
"Official" Dual Monitor  support

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4637]
**_wobs_ opened the ticket and wrote:**

> I know about patches which support dual monitor unofficially and the workarond to connect 2 clients in multiplayer to generate a dual monitor setup.
> 
> But I think it would be very useful to all "offical" dual monitor support.
> 
> In my experience the number of dual monitor setups increase and wil continue to increase te next several years. It is nog longer a high-end gaming rig privilege.
> 
> I think the best setup would be the second monitor being an extend of the first, where you can put several windows which need to monitored, or several vieuwpoints.
> 
> This way you can monitor your entire company, without clogging your main screen.

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_adf88_ wrote:**

> Why don't you just stretch the window over booth monitors?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4637#comment9993_

**Comment by DorpsGek** [comment]
**_wobs_ wrote:**

> True.
> 
> But the whole idea of an extend is that the menu sticks on the left screen.
> When I stretch the screen some parts of the menu and windows fall "in between" the monitors.
> 
> Stretching the screen only works in windowed mode. 
> I was hoping for a feature where I can use full screen mode spanning both monitors.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4637#comment9995_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> You can already configure the position of the main menubar and the statusbar in advanced settings. Configure them to be on the left/right as you like.
> 
> The fullscreen-only-extends-to-one-screen-issue seems to be OS specific. On my Debian machine with the SDL backend, fullscreen uses all monitors.
> 
> So, I guess the only issue are windows which pop up centered and thus between screens, right?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4637#comment9996_

**Comment by DorpsGek** [comment]
**_wobs_ wrote:**

> I was already expected that one :-).
> 
> I never had the pleasure of installing my openttd on debian.
> But if the fullscreen issue is OS specific, doesn't mean it isn't an issue at all.
> 
> As far as I know, a majority of the community still uses windows to play openttd.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4637#comment9998_

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> But the Debian machine demonstrates that the capability exists within OpenTTD. The program can do it, but the video library underneath it doesn't.
> As such it is not an OpenTTD problem but a video library problem.
> 
> OpenTTD can only do as much as the video library it uses. When this issue is fixed there, OpenTTD can switch to the new version, and give you full dual screen experience.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4637#comment9999_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> [mistake]

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4637#comment12852_

**Comment by DorpsGek** [comment]
**_lodewijkadlp_ wrote:**

> Alberth, Windows does not treat multiple monitors as if it's one big drawing surface. As monitors usually do not align perfectly, and some offset is used, this is nearly always the truth. I therefore think it is a totally valid (real/accurate/true) model of reality, no better or worse than Unix usually has.
> 
> Futhermore Unix does not have any specific video library at all, the diversity is stupendous and almost always requires specific adjustments to support all the little diversities.
> 
> Now either you can take a very good request seriously or you can continue pretending that a specific OS is superior for all users. Also, why not just detect how many monitors there are, and place taskbars on N of them? I don't really like swiping halfway across the room for a specific dialog.
> 
> I think it would be best to have seperate viewports, as Supreme Commander, and let windows be dragged all over the place. I'd also add support for free floating or multiple (one on every screen) menu bars.
> 
> Sorry to be agitated. It's just that I have to turn off my second screen to play OpenTTD because it doesn't understand my setup at all and draws in the middle of the portrait screen and halfway onto the other screen >:[ 
> 
> (ALSO F*# & SDL/X's TACTIC OF JUST EXPANDING S# !@. THEY'RE DIFFERENT SCREENS! NOT ONE BIG SCREEN! -->DIFFERENT<-- SCREENS)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4637#comment13251_

**Comment by TrueBrain** [comment]
Multiple monitor support is currently not on the roadmap.
