### ISSUE TITLE
Ping time for multiplayer

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4669]
**_kalten_ opened the ticket and wrote:**

> Feature: A new column in the multiplayer server list for 'ping' time?
> 
> To get a better idea of whether servers will be playable or not from your location.
> 
> 

**Reported version**: _1.0_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_TrueBrain_ wrote:**

> Moved from 'website' project to 'openttd', as this is useless on the website.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4669#comment10508_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> IRC discussion Augst 2017
> [11:26am] LordAro: andythenorth: many other game lobbys have the feature, it can't be that difficult to achieve
> [11:26am] LordAro: ¯\_(ツ)_/¯
> [11:28am] Eddi|zuHause: andythenorth: wrt ping time, only use the timing of the initial response packet, don't constantly update it?
> [11:28am] Eddi|zuHause: would put no additional stress on the servers, because that packet is sent anyways
> [11:31am]_dp_: nice and relatively easy feature imo but hardly useful
> [11:31am] _dp_: but I may be too spoiled by a good internet 
> 
> Conclusion: fair request, not a current OpenTTD goal.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4669#comment14577_

**Comment by andythenorth** [comment]
Not a current goal.  We need to clarify priorities, so closing.
