### ISSUE TITLE
Water: allow rivers (slopes) for navigation

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4711]
**_George_ opened the ticket and wrote:**

> It would be nice if rivers could be used for ship navigation. Currently they are not useful, because river requires locks to be build on slopes, that costs too much for the beginning of the game. 
> It disallows to make real-map based scenarios of the regions, where ship navigation is the main transportation way of cargo transportation.
> This would also improve placing of water based ECS industries, because it would allow wider range of placing them on the map, especially on hilly maps. Currently there are too many industries near water and a lot of free place on the hills.
> 

**Reported version**: _1.1.1_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_rini17_ wrote:**

> This problem can be solved by much cheaper building of canals/locks on river tiles than on land. Currently it is the same price which is nonsense. And it seems quite easy to implement. 
> 
> Maybe it is also possible to do easily that building canals on tiles *next to* river is cheaper. Overall, it would make rivers much more useful.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4711#comment10345_

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> That is not a solution. Locks requires at least 2 flat tiles between 2 height levels, that fits only for very smooth landscape, while rivers can be located in mountains and change level even without flat tiles.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4711#comment10346_

**Comment by DorpsGek** [comment]
**_rini17_ wrote:**

> This is why I propose to enable lower price also for neighboring tiles to rivers, is increases probability that there is suitable terrain for lock. Despite I like to play alpine terrain, still majority of rivers were 100% usable as canals. But the building price pissed me off.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4711#comment10347_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> FISH / Squid grf 'fixes' building costs for canals and locks.  Still the locks are too big, they take up too much space.  Rivers should be more fun + useful in game.
> 
> I am +1 to navigable rapids, with a speed penalty and a ship property for 'can navigate rapids'.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4711#comment12844_

**Comment by TrueBrain** [comment]
I can only agree to this if going upstream slows a ship down :D (just kidding). Cool idea :)

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
