### ISSUE TITLE
Industries: (tiles) provide additional information during CB 3C

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4715]
**_George_ opened the ticket and wrote:**

> It would be nice to know in var 10 or 18 which corner is being lowed. 
> Currently there are only 2 variants - disallow any terraforming under a tile, and allow any terraforming.
> With additional information being provided, it would be possible to protect inner tiles of the industry, but allow terraforming on the perimeter.

**Reported version**: _1.1.2-RC2_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> I've done the opposite of this in FIRS, forbidding outer tiles from terraforming, and allowing inner tile on slopes, as long as the height matches the industry N tile.  
> 
> http://dev.openttdcoop.org/projects/firs/repository/entry/src/industries/quarry.py# L19
> 
> My goal was to increase the number of locations large industries can build, by allowing them to locate on uneven ground, whilst appearing to be flat.  What goal do you have here George? :)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4715#comment14705_

**Comment by andythenorth** [comment]
No progress for 7 years, let's pass on this.  Happy to re-open if needed.
