### ISSUE TITLE
Scenario Editor: rivers with desert

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4754]
**_planetmaker_ opened the ticket and wrote:**

> In the scenario the interaction between rivers and desert tool are not optimal:
> 
> a) drawing a river on desert creates grass tiles around it (ok)
> b) drawing desert over a river kills removes the river and makes the tile desert (this is IMHO a real bug and should not work this way. Houses etc. aren't removed either)
> c) drawing desert next to a river removes the transition (this is somewhat inconsistent, but can be argued ok)
> 
> Expected behaviour could be:
> ad b) drawing desert over a river tile could sets the tile to full desert, too, thus creating rivers which show desert shores. Alternatively putting a river tile to desert could simply have no effect / not be allowed.
> ad c) Apply the usual transition rule. Assuming river tiles are always grass tiles, drawing desert next to a river should make the tile a grass-desert transition tile. If rivers can be deserts, it should depend on what type the river tile is.
> 

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_planetmaker_ wrote:**

> illustration

**Attachments**
- [screenshot#23.png](https://bugs.openttd.org/task/4754/getfile/7739/screenshot%2323.png) (16.40 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4754#comment10279_

**Comment by DorpsGek** [comment]
**_planetmaker_ wrote:**

> as visible in the screenshot: a similar argument could apply to coasts, too which are always grass, thus a transition tile could follow towards desert. Or one could allow desert shores

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4754#comment10280_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Half-desert tiles are technically non-desert tiles next to desert tiles.
> As such c) makes no sense to me. Just do not put desert next to rivers.
> Same applies to coasts.
> 
> Wrt. d): Converting coast to non-desert when being flooded would thus also reqruite to convert neighboured tiles to non-desert.
> 
> e) Converting desert to non-desert in game when flooding the desert would be irreversible. So likely not a good idea.
> 
> f) It might be possible to make tile also show half-desert when they are next to water/coast. This would also react to flooding in game. However it will likely look weird during flooding, when tiles change to half-desert shortly before being flooded. :p

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4754#comment10281_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Attached diff changes the behaviour of half desert: Desert tiles are now half-desert if a neighboured tile is non-desert or sea/coast.
> That is, flooding changes neighboured tiles to half-desert.
> Rivers do not do the same, that is up to the scenario editor user.
> 
> Somewhat important change: Half-desert tiles are now in the DESERT zone, not in the NORMAL zone.
> 1) This might break NewGRFs doing the computation themelf.
> 2) This might slow the game as there are usually a lot more DESERT tiles than NORMAL tiles.
> 3) This might actually look better as stuff that tests for non-DESERT is now not in half-desert. (Stuff checking for DESERT is rare.)

**Attachments**
- [fs4754.diff](https://bugs.openttd.org/task/4754/getfile/7744/fs4754.diff) (1.52 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4754#comment10296_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> FWIW, houses are removed with the desert tool (in 1.7.1) it seems to act as 'clear area' for the things I tried.
> 
> Patch applied ok and works as expected in SE.  Can't comment on potential performance issues.
> 
> This would likely break at least FIRS assumptions about desert.  Not in a serious way, but likely to affect location checks and maybe some graphics; I would be prepared to resolve those issues.  Can't comment on other NewGRFs.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4754#comment14597_

**Comment by andythenorth** [comment]
Needs turning into a pull request next IMHO :)

**Comment by andythenorth** [comment]
It's done \o/
