### ISSUE TITLE
Water: enhanced buoys

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4792]
**_PaulC_ opened the ticket and wrote:**

> OK, I believe this has already been rejected before in the past, but before anyone directs this request straight to the bin I'd like to make a renewed plea for the inclusion of enhanced buoys (i.e. buoys as stations) in OTTD. This is one of the features I miss most from TTDP, and I firmly believe it would be of value here as well for the following reasons:
> 
> 1) Docks can only be built on canals and rivers buy raising the adjacent land, which isn't ideal. Enhanced buoys would offer a better alternative, IMO.
> 
> 2) Likewise, docks cannot be built on canals or rivers that are only one tile wide, which is an unnecessary and unrealistic restriction. Enhanced buoys would offer a way around this.
> 
> 3) Enhanced buoys would allow cargo to be transfered from one ship to another while at sea. This is done in real life and would be useful in terms of gameplay, i.e. transfering cargo from a smaller ship to a larger ship.
> 
> 4) With regards to industries I've heard it said that enhanced bouys simply aren't necessary as sea-based industries can be coded with a built-in dock, but I don't believe that's true! AFAIK a sea-based industry with build-in dock must also have a built-in heliport, which isn't ideal for something like fishing grounds (as in FIRS). Use of enhaced buoys would arguably be more realistic anyway.
> 
> 5) It would allow OTTD to be compatible with older grfs like Michael Blunck's New Cargo. Sure, you can build a dock next to those fishing grounds by raising land in the middle of the sea, but that's expensive, ugly and unrealistic.

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> I am +1 to this.  The built-in dock/heliport has multiple problems, as per #5682 and related tasks.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4792#comment14638_

**Comment by andythenorth** [comment]
Further discussion happened.   IMHO not buoy stations, but some kind of better docks instead.

**Comment by TrueBrain** [comment]
Sounds like a good idea! But realistic, not going to happen anytime soon (hasn't happened in 7 years). So sorry, going to pass on this. Tnx though!
