### ISSUE TITLE
TTD Inflation model is crap

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4799]
**_Pikka_ opened the ticket and wrote:**

> As I'm sure you are aware, the TTD inflation model makes the game "harder" as years go by by increasing costs by 1% more than incomes.
> 
> The recent proliferation of 19th century GRFs is starting to highlight the problems with this system; games started in early years have massive discrepancies between costs and incomes by the mid 20th century, often making the game unplayable.  This 1% discrepancy is impossible for GRFs to balance for, as the level of divergence between costs and income is dependent on how long the game has been running.  We are starting to see an increase of threads on the forums from players who can no longer make a profit in their game because they started in too early a year.
> 
> I suggest an additional inflation model be added, where there is no 1% divergence, and that this new model be the default.
> 
> Inflation: Off
> Inflation: On (cost and income increase at same rate).
> Inflation: Original TTD (costs increase faster than income).

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> What about just stopping the inflation after say, 170 game years? That's the time the original game had inflation for.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4799#comment10434_

**Comment by DorpsGek** [comment]
**_Pikka_ wrote:**

> That doesn't help; you still have a dramatically different economy in the year 2000 if you started that year vs if you started in 1850, even with "only" 150 years of inflation.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4799#comment10460_

**Comment by DorpsGek** [comment]
**_mfb_ wrote:**

> Maybe it is possible to calculate inflation based on a fixed year: Let inflation run as if every game would start in 1900. That way, costs are reduced for earlier years (or income/cost is fixed to the 1900 value), from 1900 to 2050 everything is like in the original TTD and afterwards cost and income increase at the same rate.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4799#comment10591_

**Comment by DorpsGek** [comment]
**_PaulC_ wrote:**

> What if inflation only kicked in from 1950?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4799#comment11029_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Just delete inflation, it offers nothing fun for gameplay.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4799#comment14512_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> NoInflation - delegate it to an economy script.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4799#comment14573_

**Comment by andythenorth** [comment]
I agree that inflation is daft.  

Inflation is hard to solve, because it requires a decision about whether to keep the old inflation model around
* preserve savegame compatibility?
* or get rid of  dead code that causes failure demand and adds complexity?
 
That argument is not appealing, so it's unlikely anyone is going to pick this up and push it through.  There is no win in keeping open tickets around 'just to remind us of a problem'.  Tickets should be about addressable issues, not unsolvable tarpits.

This ticket isn't winning us anything, so I'm closing it. :)
