### ISSUE TITLE
Orders: convert implicit orders to explicit

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4811]
**_alocritani_ opened the ticket and wrote:**

> I think would be nice having possibility to convert from implicit orders to explicit.
> It can be useful, for example, if you have a line with lot of intermediate stops: A - B - C - D - E - F - G
> In this case the vehicle can be set with a
> 
> goto A
> goto G
> 
> and all intermediate stops will be added as implicit orders.
> 
> If the line is then changed, the intermediate stops may change. In this case will be nice to promote them to explicit one.
> 
> My proposal is something like CTRL+SHIFT+CLICK on a implicit order to convert it to explicit.

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
No progress in 7 years.  Maybe nice to have, but let's pass for now, thanks :)
