### ISSUE TITLE
AI Debug Variable Watch Support

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4843]
**_11Runner_ opened the ticket and wrote:**

> As an AI developer,  I have been wondering if it is possible to include more advanced debugging mechanisms for AI development.  It would be nice to have line-by-line code debugging ingame.  Along with that, variable watches to verify and edit variables.
> 
> This should be possible to implement because Squirrel has a debugging interface.
> 
> You could just put most of it in the AI debug window.

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
I think a debugger for AIs would be very cool, but it is also a very big project. So I am going to close this issue, as it is not part of the current roadmap.
