### ISSUE TITLE
Sort object and station purchase list

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4961]
**_foobar_ opened the ticket and wrote:**

> Vehicles have a property to define a custom sort order for the purchase list. This allows to maintain grf compatibility when you add a vehicle later on but don't want it to appear at the end of the list.
> 
> I would like to use a similar property for objects (and stations), for the same reason.
> 
> I'm aware that object and station sets can have their items distributed over multiple classes, but this fact can be largely ignored. If there's one overall sorting order, it's also possible to get any sort order you want in the classes itself.
> 
> Thank you for your time :)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
Thanks.  I think it's TMWFTLB, so closing as we clean up issues.
