### ISSUE TITLE
Objects: draggable items

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4998]
**_KasperVld_ opened the ticket and wrote:**

> L.S.,
> 
> I've been playing OpenTTD for a few years now with great enjoyment and I really like the implementation of NewObject, which I use for the Dutch Road Furniture Set, however, I think that these objects need to be 'draggable' as I have to click hundreds and hundreds of times to create a highway as in the picture below. Maybe a system much like the one used by station sets in NewGRF's could be used, where some tiles can be dragged and some cannot.
> 
> The highway: http://i.imgur.com/UmOh3.png
> 
> As you can see, after laying down the road (which I can drag), I have to put a hard shoulder on each side of the road and also add a central divider. Being able to drag objects like this would cut construction time significantly.

**Reported version**: _1.2.0-beta2_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_foobar_ wrote:**

> I think an additional flag/property is in order for this, allowing the NewGRF author to set if an object should be draggable or not. Possibly with a callback that can disallow dragging depending on selected object view.
> 
> I think it's fine to have this only for 1x1 tile objects, at least for starters.
> 
> But yes, +1 for this feature request, as I'm getting RSI from building motorways :P

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4998#comment10776_

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
