### ISSUE TITLE
Railtypes: 'hide railtype' flag

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5006]
**_George_ opened the ticket and wrote:**

> To create trains, that can run on several electrified railway types, it is required to create the new "combo" rail type, that is available in menu. 
> It is required to have a flag to have "hidden" rail type for combo rail type.
> 
> [16:09:24] <George> RailTypes querstion. Is it possible to create a 2 electrified rail types and 3 types of trains, that can run on first, second and both rail types?
> [16:10:19] <George> If I carte a new 3-d rail type, that has trains that can use first and second rail types, I also get it in the list.
> [16:10:37] <George> But there should be only 2 rail types for trains
> [16:11:17] <George> How to solve it?
> [16:19:46] <George> For example, Eurostar can run on electrified and 3-d rail rayl types. How to code it?
> [16:21:03] <andythenorth> compatibility with other labels?
> [16:21:15] andythenorth hasn't tested
> [16:21:28] <andythenorth> pikka has done it afaik in UKRS 2
> [16:21:53] <George> Because a train can have only one rail type, there should be provided some new rail type "combo". It has to specify compatibility with both  electrified rails and 3-d rail types
> [16:22:46] <George> But in this case there would be a new rail type "combo", that is not intended
> [16:23:17] <George> andythenorth: pikka has done it afaik in UKRS 2> How did he do it?
> [16:28:35] <Eddi|zuHause> George: when the problem appeared for the voltage systems in the ToE set, the discussed solution was to allow a "combo" railtype, because especially on some platforms, the voltage systems might be switchable
> [16:28:56] <Eddi|zuHause> George: just make it overly expensive
> [16:30:53] <George> Eddi|zuHause: I came to the same, but this sounds not a good solution. Would it be possible to hide this combo type?
> [16:31:26] <Eddi|zuHause> George: no, as soon as a vehicle uses it, it becomes available

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_planetmaker_ wrote:**

> What's missing when using railtype properties 17 and 18?
> 
> As for vehicles, you need to make use of a railtype translation table. Use an action7 chain, testing availability of railtypes in sequence of your preference. NML offers a nice shorthand: http://newgrf-specs.tt-wiki.net/wiki/NML:Railtypetable

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5006#comment10783_

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> How can it help?
> 
> Introduction date (17)
> Introduction required rail type list (18)
> 
> electrified rails and 3-d rail are available at the same time. The question is how to make a Eurostar train, that can run both on electrified rail and on 3-d rail. But other trains can only run on electrified rails or on 3-d rail. 
> As  it was discussed, in this case we need a "combo" rail type, specify Eurostar as combo rails type, and make combo rail compatible with electrified and 3-d rail. Eurostar is coded as combo. The problem is that there is a combo rail type appears, and combo type depot has one vehicle - Eurostar, that is not intended. this combo rail type should be hidden.
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5006#comment10784_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Similar issue for NotRoadTypes.  Not sure if it should be fixed though, maybe it's a useful constraint.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5006#comment14340_

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> Attached patch adds a flag to hide a railtype from construction. Untested.

**Attachments**
- [fs5006.diff](https://bugs.openttd.org/task/5006/getfile/10689/fs5006.diff) (1.53 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5006#comment14409_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> It would be nice if the non-buildable types would not count towards the max-railtypes limit.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5006#comment14410_

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> Aww that sounds hard

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5006#comment14419_

**Comment by DorpsGek** [comment]
**_Snail__ wrote:**

> Frosch has a fair point, the non-buildable types shouldn't count towards the max-railypes limit.
> This is why I requested the maximum railtype number be raised from 16 to 32: this would address the issue raised by Frosch. Disgraciously, my request got shot down...

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5006#comment14654_

**Comment by DorpsGek** [comment]
**_Snail__ wrote:**

> Frosch has a fair point, the non-buildable types shouldn't count towards the max-railypes limit.
> This is why I requested the maximum railtype number be raised from 16 to 32: this would address the issue raised by Frosch. Disgraciously, my request got shot down...

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5006#comment14655_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Comment from George via forums pm: "required, but may be the problem should be solved in some other way. It is a pity to loose railtype just for 2type trains. It would be better to have just 2 railtypes, while a train has a code, that specifies it can use both."

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5006#comment14692_

**Comment by PeterN** [comment]
Proto-plan in my head is to raise the in-game limit on the number of rail types, add some mapping, and then only allow 16 different types of rail type on the map at one time. Hidden rail types would be trivial in this scheme.

This scheme would work the same for road/tram types as well, probably.

 Or just shuffle the map around and add more space. You all have 32GB ram these days, right?

**Comment by andythenorth** [comment]
Well, railtypes are 64 now... :) https://github.com/OpenTTD/OpenTTD/pull/6805

Room to hide some?

**Comment by PeterN** [comment]
Probably room now, yes. Shouldn't be too hard to implement either.

**Comment by PeterN** [comment]
@George-VB are you able to provide a test case for this feature?

Set bit 2 of rail type flags to hide the rail type from selection.

**Comment by George-VB** [comment]
As far as I can see the xUSSRset code, every rail type has bits 2 and 3 on
railtype_flags: bitmask(2, 3);
https://dev.openttdcoop.org/projects/xussrset/repository/entry/src/railtype/railtrack.pnml
In 20190204-master-g33e3f49161 all the tracks are available
![image](https://user-images.githubusercontent.com/43310520/52234181-1c9ff900-28d2-11e9-89d1-736837f82e9b.png)
what am I doing wrong?

**Comment by michicc** [comment]
It's only a PR for now and not merged into master yet.

**Comment by George-VB** [comment]
xUSSRset is available here http://bundles.openttdcoop.org/xussrset/push/LATEST/

**Comment by PeterN** [comment]
By setting the bit to hide railtypes on all railtypes, you've of course made it so that NO railtypes appear. This makes it somewhat tricky to test...

**Comment by PeterN** [comment]
@George-VB Thanks for that test, however are you able to provide a realistic test with out all rail types hidden? I would also need to know which vehicles to test with.

**Comment by George-VB** [comment]
I can hide all ACDC-electrified railways for example (the last one in the list), so you could test with ACDC engines (should be available in AC and DC depots). Would it be suitable?

**Comment by George-VB** [comment]
If so, you can get a new version at http://bundles.openttdcoop.org/xussrset/push/LATEST/
List of ACDC engines is at https://wiki.openttd.org/XUSSR_Set/Electric_locomotive/EN

**Comment by PeterN** [comment]
This is implemented by #7118.

**Comment by George-VB** [comment]
Works fine with master 20190207
![image](https://user-images.githubusercontent.com/43310520/52518560-39835600-2c5d-11e9-90f0-109fc06cbd85.png)
![image](https://user-images.githubusercontent.com/43310520/52518582-95e67580-2c5d-11e9-9322-a8b5bb353136.png)
