### ISSUE TITLE
Also allow overbuilding of depots

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5092]
**_kwm_ opened the ticket and wrote:**

> With 1.2.0-RC2 it is possible to build trains stations on top of already excisting stations. This goes also for bus stations and lorry loading bays. Road/rail deports and airports don't allow this.

**Reported version**: _Version?_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_planetmaker_ wrote:**

> Overbuilding is allowed by design; it allows you to adjust the looks (using other station tiles) after you built it for efficiency.
> 
> Airports don't allow overbuilding as they each have a complicated state machine which is basically a fixed movement pattern for planes.
> It would be feasible to allow depots being overbuilt, if they're empty.
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5092#comment10966_

**Comment by DorpsGek** [comment]
**_PaulC_ wrote:**

> Allowing depots to be overbuilt would certainly be useful.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5092#comment11022_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> See #6617 for one possible solution to over-building depots.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5092#comment14704_

**Comment by andythenorth** [comment]
I think we can pass on this.  Overbuilding stations is necessary because newgrf stations offer multiple tile types.

But:
* Depots always have only one tile type.   
* Overbuilding them on same railtype wouldn't change anything.
* Changing depots between railtypes can be done with the convert tool.

So closing, thanks :)
