### ISSUE TITLE
Railtypes: variable L5 of map array

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5132]
**_Pikka_ opened the ticket and wrote:**

> A variable exposing the lower byte of L5 to newgrf would allow railtype sets to provide custom intersection sprites for every possible intersection, instead of just the cross.  This would allow nice-looking switches - TTD-style layering of elements doesn't work very well for more solid tracktypes, or complicated messes like 3rd rail.  
> 
> Extra bonus; this var would also allow detecting signal tiles, for AWS ramps or other greebles, and custom depot groundtiles!

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
Nah, TMWFTLB, closing.  Cheers :)

**Comment by andythenorth** [comment]
"I was wrong" 🐱
