### ISSUE TITLE
Orders: ping-pong orders

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5140]
**_xahodo_ opened the ticket and wrote:**

> Regularly I find myself building trains with about 29 orders, because they attend 15 stations. It would be really helpful if I can just forget about the 14 for the route back.
> 
> Implicit orders aren't helpful for me as I, in nearly all cases, need to use pass-through tracks and my trains and platforms are of varying lengths. This makes implicit orders useless in such cases. That's why I am asking for this feature.

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> One of the problems I see here is that just the position of the current order is not sufficient any more.
> This can lead to confusion of what a train is doing.
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5140#comment11072_

**Comment by DorpsGek** [comment]
**_xahodo_ wrote:**

> Are you talking about possible bugs or user confusion?
> 
> Well, user confusion might be solved by a) making it optional (like shared orders it isn't needed in all cases) and b) by showing the current traversal direction in the order list.
> 
> Some possible solutions to this are:
> \- Make the arrow which points at the current order point 45 degrees up or down.
> \- add another arrow in front of the current order showing the current traversal direction (then it could be clickable to change the traversal direction).
> \- Show the traversal direction in the window title of the order window.
> \- The traversal direction through the order list could be shown in various other places where such information is relevant.
> 
> And for the case of the engine suffering from bugs. Well, adding an additional traversal direction to a simple list (even considering (conditional) jumps) shouldn't be that hard.
> 
> I would have done this myself, but... erm... openttd still resembles a plate of spaghetti to me. :'(

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5140#comment11074_

**Comment by DorpsGek** [comment]
**_ntoskrnl_ wrote:**

> Maybe a press of a button could add the current orders to the end of the list in reverse order? The added orders could be visually similar to implicit orders to differentiate between normal orders and them. They could possibly be updated automatically as well, again similarly to implicit orders.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5140#comment11214_

**Comment by DorpsGek** [comment]
**_pavzav_ wrote:**

> >>a press of a button could add the current orders to the end...
> This would be confusing because the order list would be too long. If you have an order list with non-stop orders, you have to specify each station explicitly. Therefore, you usually have a long list of stations. If you need to specify stations for reverse direction, it is even longer because you need to add each station twice (except the first one and the last one).
> 
> The solution is to have two systems: ABCD-ABCD and ABCD-DCBA as I described in http://bugs.openttd.org/task/5196
> Allow the player to set the system for each order list and add a global option about the default one
> To indicate the used system, you can have  "-- End of orders --"  and "-- Go back --"
> 
> There is a problem with non-stop orders - see http://bugs.openttd.org/task/5196

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5140#comment11268_

**Comment by TrueBrain** [comment]
I don't see this happening. It is both very complex (and possibly confusing) for the user to have different settings/types/etc, and I am not sure either party would like it.

Of course feel free to rebuttal or create a Pull Request resolving this issue :) Or drop by on IRC to talk it over!

For now, closing the issue. Tnx for the thoughts and feedback!
