### ISSUE TITLE
Objects: animation triggers for multiple tiles

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5144]
**_mb_ opened the ticket and wrote:**

> ATM, there´s no possibility to start synchronized multi-tile animations in a random way. 
> 
> [quote="frosch"]
> Personally I am in favour of changing the animation callbacks of objects and airport tiles to have 16 shared bits for animation triggers that trigger on multiple tiles.
> [/quote]
> 
> (See discussion http://www.tt-forums.net/viewtopic.php?f=68&t=59167) 

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
Sounds like a good idea! But I don't think this is going to happen any time soon .. so going to pass for now. Tnx though!
