### ISSUE TITLE
Timetable: set timetable start date - add days

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5198]
**_pavzav_ opened the ticket and wrote:**

> a vehicle/Orders/Timetable/Start date:
> 
> Add a button 'add n days to the start date' (and possibly 'subtract n days from the start date' as well).
> Allow the player to set n, the default value will be timetable_duration / number_of_vehicles_with_shared_orders
> This will be very practical if you need to set intervals between vehicles with shared orders (it is not easy to add e.g. 54 days to some date)
> 

**Reported version**: _1.2.0_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
Timetables should be revamp'd in general. So sorry, going to pass on this specific request. Tnx though!
