### ISSUE TITLE
[Windows] fullscreen_bpp = 32 causing visible skipping due to enforced vsync

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5202]
**_squall_leonhart_ opened the ticket and wrote:**

> When the fullscreen_bpp is set to 32, visible skipping/hitching is present while scrolling the world map, moving the mouse and watching vehicles go about their business.
> 
> This appears to be caused by the fact vsync is forced on in 32bpp mode while not in 8bpp and the game animation expects to update whenever it pleases.
> 
> This was also recognised in Starcraft using ddhack with vsync enabled so I assume this and other ddraw titles expect a variable framerate and not being locked at 59.94 (vsync)

**Reported version**: _1.2.1_
**Operating system**: _Windows_

---

**Comment by TrueBrain** [comment]
Many things wrong with how OpenTTD handles resolution and fullscreen (very old-fashioned), I am unable to reproduce this issue on the latest version. Given this ticket is 6 years old, maybe not surprising.

Please open a new ticket if this is still the case for you in the latest version. Thank you!
