### ISSUE TITLE
Bananas: confusing "find missing content online" - especially removing savegame selection

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5210]
**_Kogut_ opened the ticket and wrote:**

> downloading missing newgrf from bananas requires
> 1) clicking on "find missing content online" (BTW, this button may be bigger and easier to notice for savegames with missing newgrfs)
> 2) hitting download (also, it may be a good idea to make this button bigger)
> 3) hitting OK (why it is needed?)
> 4) and now the biggest problem happens - savegame is no longer selected
> 
> I returned after 5 month of break and this was extremely confusing and I think that it should not be hard to fix this.
> 
> Expected: OpenTTD downloads all available newgrfs after clicking on "find missing content online", skipping points 2, 3 and 4

**Reported version**: _1.2.1_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
That indeed sounds like a bad UI. Fix should be a good way to learn the code!

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
