### ISSUE TITLE
Cloning vehicle with impossible orders silently fails to copy orders

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5213]
**_Kogut_ opened the ticket and wrote:**

> \*Create vehicle (in my example bus)
> \*give it orders (go to bus station A, bus station B)
> \*make orders impossible (bus station B contains now only truck part, without bus stop)
> \*clone vehicle (no error message)
> \*check orders (orders of cloned vehicle are now empty)

**Reported version**: _1.2.1_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_frosch_ closed the ticket.**

**Reason for closing: _Fixed_**

> in r24390

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5213_

**Comment by James103** [comment]
* Main issue still occurs in d7a928a, with the same reproduction steps as in initial commit. Suggested fix: Still let the vehicle clone go through, but issue a warning noting that the vehicle's orders were not copied.
* Additionally, if vehicles share impossible orders, then it is not possible to undo the order sharing.

**Comment by LordAro** [comment]
Can you create a new issue for this? I don't really want to reopen such an old issue
