### ISSUE TITLE
Multiplayer: allow favorite and not favorite servers

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5277]
**_Lazl_ opened the ticket and wrote:**

> In a multiplayer game there are constantly filled servers and servers with unacceptable rules. At the same time, there are servers, rules which allow interesting to play them. Propose allow the user to tag such servers in server list with key + or - , in order to at the beginning of the list of available servers user have positive marked servers, then not marked and in the end servers, marked negatively. Thanks!

**Reported version**: _1.2.2_
**Operating system**: _Windows_

---

**Comment by TrueBrain** [comment]
If you manually add a server, it will always be there and on top. Currently there is no other way to do something like this. I really do like the idea (especially if we push it further to some "voting" system or what-ever), but it is not part of the current roadmap.
