### ISSUE TITLE
Ctrl+Click on a sign in the sign list window to edit it

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5284]
**_sbr_ opened the ticket and wrote:**

> This patch allow to edit a sign by Ctrl+Clicking it on the sign list window.
> This permit to rename/delete a sign if it's not visible on the main viewport or if signs aren't displayed at all.
> 
> Please find attached a patch against r24502.

**Attachments**
- [ctrl-click-sign-list-to-edit-sign_r24502.patch](https://bugs.openttd.org/task/5284/getfile/8537/ctrl-click-sign-list-to-edit-sign_r24502.patch) (1.87 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_planetmaker_ wrote:**

> I very much like the idea of being able to edit and delete signs from the sign list.
> 
> Comparing with other lists, a ctrl+click will open an extra viewport centred on the object though. Thus what about this:
> ctrl+click opens the viewport
> double click opens the edit capability

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5284#comment11481_

**Comment by DorpsGek** [comment]
**_sbr_ wrote:**

> Opening an extra viewport on Ctrl+click is consistent with the rest of the UI and should be the way to go. At first, I also found the use of double click to edit sign as a good idea.
> 
> However when double clicking, two events are send to the window: an OnClick(pt, widget, click_count = 1) for the first click of the double click and another OnClick(pt, widget, click_count = 2) when the second click of the double click occurs. Thus when double clicking on a sign, the main viewport is moved to the sign location before the opening of the edit window.
> 
> I've then split the patch in two parts, one for the Ctrl+click part and the other for the double click part.
> I'll also try to find a way to launch the edit window without moving the main viewport.
> 
> Please find attached these two patches against r24508.

**Attachments**
- [sign-list-00ctrl-click-open-extra-viewport_r24508.patch](https://bugs.openttd.org/task/5284/getfile/8542/sign-list-00ctrl-click-open-extra-viewport_r24508.patch) (2.14 KiB)
- [sign-list-01double-click-edit-sign_r24508.patch](https://bugs.openttd.org/task/5284/getfile/8543/sign-list-01double-click-edit-sign_r24508.patch) (1.68 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5284#comment11488_

**Comment by DorpsGek** [comment]
**_sbr_ wrote:**

> Another proposition to edit signs from the sign list window :
> \- Click the company icon to edit the sign;
> \- Click the sign name center the main viewport on the sign position;
> 
> Please find attached these two patches against r24510.

**Attachments**
- [sign-list_00ctrl-click-open-extra-viewport_r24510.patch](https://bugs.openttd.org/task/5284/getfile/8548/sign-list_00ctrl-click-open-extra-viewport_r24510.patch) (2.14 KiB)
- [sign-list_01click-company-icon-edit-sign_r24510.patch](https://bugs.openttd.org/task/5284/getfile/8549/sign-list_01click-company-icon-edit-sign_r24510.patch) (1.84 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5284#comment11494_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Patch 00 fails to apply on r27908, .rej attached
> 
> openttd-trunk(master)$ curl https://bugs.openttd.org/task/5284/getfile/8548/sign-list_00ctrl-click-open-extra-viewport_r24510.patch | patch -p1
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  2194  100  2194    0     0  14279      0 --:--:-- --:--:-- --:--:-- 14339
> patching file src/lang/english.txt
> Hunk # 1 FAILED at 2749.
> 1 out of 1 hunk FAILED -- saving rejects to file src/lang/english.txt.rej
> patching file src/signs_gui.cpp
> Hunk # 2 succeeded at 238 with fuzz 1 (offset -15 lines).
> Hunk # 3 succeeded at 374 (offset -25 lines).

**Attachments**
- [english.txt.rej](https://bugs.openttd.org/task/5284/getfile/10844/english.txt.rej) (1.09 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5284#comment14720_

**Comment by andythenorth** [comment]
No change for > 5 years.  Prioritising to get some clarity, so let's pass on this one, thanks :)
