### ISSUE TITLE
Savegames Failing to Load

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5306]
**_Pingaware_ opened the ticket and wrote:**

> Some old savegames are causing crashes for me when I try and load them in trunk. This includes OpenTTD and TTD savegames. Attached are examples of TTD and OpenTTD saves which cause the crash, each with respective crash files. The OpenTTD save crashes immediately on trying to load, the TTD save loads the map for a brief moment, then crashes.

**Attachments**
- [TRT01.SV1](https://bugs.openttd.org/task/5306/getfile/8607/TRT01.SV1) (269.29 KiB)
- [crash (TTD Save).dmp](https://bugs.openttd.org/task/5306/getfile/8608/crash+%28TTD+Save%29.dmp) (2095.76 KiB)
- [crash (TTD Save).log](https://bugs.openttd.org/task/5306/getfile/8609/crash+%28TTD+Save%29.log) (9.92 KiB)
- [crash (TTD Save).png](https://bugs.openttd.org/task/5306/getfile/8610/crash+%28TTD+Save%29.png) (509.01 KiB)
- [Turksetti Transport Original.sav](https://bugs.openttd.org/task/5306/getfile/8611/Turksetti+Transport+Original.sav) (125.58 KiB)
- [crash.dmp](https://bugs.openttd.org/task/5306/getfile/8612/crash.dmp) (2111.55 KiB)
- [crash.log](https://bugs.openttd.org/task/5306/getfile/8613/crash.log) (9.50 KiB)
- [crash.png](https://bugs.openttd.org/task/5306/getfile/8614/crash.png) (628.73 KiB)

**Reported version**: _trunk_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_Yexo_ wrote:**

> @Pingaware: I can confirm the crashes, we'll do our best to fix them. What follows below are some technical details, feel free to ignore those.
> 
> Turksetti savegame crashes because house tile 24472 has m2 set to 62 and there exists no town with that id.
> TRT01.SV1 crashes because a water tile has different bits set then OpenTTD expects. This seems to be a duplicate of #5207

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5306#comment11552_

**Comment by DorpsGek** [comment]
**_Rubidium_ closed the ticket.**

**Reason for closing: _Won't fix_**

> Both savegames are corrupted and checking the complete validity of a savegame after/during loading would require too much effort to be worth it.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5306_

**Comment by DorpsGek** [comment]
**_Pingaware_ wrote:**

> Fair enough Rubidium. Thanks for looking into it though!

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5306#comment11962_

**Comment by James103** [comment]
The TRT01.SV1 save game [crashes on load with this log](https://github.com/OpenTTD/OpenTTD/files/3200135/OpenTTD.-.2.zip)
 on 20190516-master-g24493548da with `Assertion failed at line 4036 of d:\a\1\s\src\station_cmd.cpp: st->facilities == (FACIL_AIRPORT | FACIL_DOCK) && st->airport.type == AT_OILRIG`.
The Turksetti Transport Original.sav save game does not crash in a few months.
