### ISSUE TITLE
Advanced Fences: (with test case)

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5309]
**_George_ opened the ticket and wrote:**

> R24556
> 
> currently the same graphics is used for fences in front and behind railway (it was that way in TTD and stayed unchanged)
> It causes holes and overlapping on corners. It would be nice, if a GRF could provide different fence graphics to fix this problem.
> 
> 

**Attachments**
- [Test Bas+chem, 01.09.2008.png](https://bugs.openttd.org/task/5309/getfile/8620/Test+Bas%2Bchem%2C+01.09.2008.png) (75.12 KiB)
- [xussr.grf](https://bugs.openttd.org/task/5309/getfile/8621/xussr.grf) (6718.38 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> This should maybe be closed, as #6315 has a more complete discussion about advanced fences (including what's now implemented and what isn't, and why).
> 
> I left it open only because it has the png and grf attached, and they show the case requested to be fixed.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5309#comment14632_

**Comment by andythenorth** [comment]
Closing, see #6315 instead.
