### ISSUE TITLE
GameScript function for CmdClearArea

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5313]
**_xOR_ opened the ticket and wrote:**

> Right now there is only GSTile.DemolishTile(tile) which invokes the DoCommand CmdLandscapeClear. However, there is no function to invoke the DoCommand CmdClearArea, so if the GS needs to clear a bigger area it has to call GSTile.DemolishTile() lots of times from a loop, causing lots of unnecessary DoCommands.
> Therefore a new function should be added, e.g. GSTile.DemolishTiles(start, end), which internally uses the CmdClearArea DoCommand to clear an area of tiles.

**Reported version**: _1.2.2_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
This was always done deliberately. It means a GS can not do all too crazy stuff in a short time. I am a bit reluctant to add it. GS is limited in amount of commands it can execute per tick, so doing lots of commands at least slows down destructive behavior.

Please rebuttal if you disagree!
