### ISSUE TITLE
Disaster aircraft speed revamp

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5414]
**_Pikka_ opened the ticket and wrote:**

> It's a bit odd seeing a fighter jet traveling across the map at a fraction of the speed of other aircraft, and it's a bit tedious waiting for the Skyranger to crawl down and blow up a large UFO.
> 
> Disaster aircraft could do with both making their speed scale with the planespeed setting, and giving them "realistic" speeds to begin with.
> 
> Suggested speeds (with decimal grf speed (mph/8)):
> 
> Small UFO: 600mph ( 75 )
> Zeppelin: 80mph ( 10 )
> Helicopter: 183mph ( 23 )
> Fighter Jet: 583mph ( 73 )
> Large UFO: 400mph ( 50 )
> Skyranger: 600mph ( 75 )

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_surferconor425_ wrote:**

> The speeds are very odd, that's worth looking into and maybe making a patch (which I will post here) for it until it is fixed

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5414#comment11947_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> NoDisaster framework! :P . Hi Pikka Bob.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5414#comment14571_

**Comment by TrueBrain** [comment]
Although I agree disasters do need some love, this is a very local fix for a broader issue. We welcome any patch addressing this issue, but sorry, going to close this ticket for now.
