### ISSUE TITLE
Vehicles: take refitted capacity into account in buy menu

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5437]
**_George_ opened the ticket and wrote:**

> R24865
> 
> In buy vehicle window when vehicles are sorted by capacity and filtered by cargo type, value of capacity for default cargo is used.
> for example:
> 84 crates of goods
> 60 tons of food (wagon # 2)
> 52 crates of goods
> But when the wagon # 2 is refited to goods, it gets capacity equal to 120 crates of goods, which is more than 84 crates of goods.
> It would be nice to display refited capacity in this case (when a filter by cargo is applied), like this
> 120 crates of goods (wagon # 2)
> 84 crates of goods
> 52 crates of goods
> 

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_krinn_ wrote:**

> I could answer that one as i've been told why :)
> 
> openttd cannot know some vehicle properties by the newGRF until the vehicle is created. So to fill up the value you are seeking, openttd would need to create one vehicle of each type, and record all properties once built to keep track of them.
> Not something undoable, but until one create a caching properties system, you will never seen it happen.
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5437#comment11870_

**Comment by TrueBrain** [comment]
Very complex because of NewGRFs (as explained, and more). I understand the roadmap, but I see no room for this currently.

Of course we welcome a patch that implements this properly.
