### ISSUE TITLE
Towns: Message/Overview needed for exclusive transport rights

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5443]
**_onimoschta_ opened the ticket and wrote:**

> In multiplayer games it is essential to keep track of who owns exclusive transport rights in which town. Now i have to open and pin many town windows and always have an eye on them if something changes. This would be alot easier when i could setup a message that is displayed when something changes. There could be also an overview who owns exclusive rights in which town. When playing with human players it is a major task because they can easily take damage to your coorporation by purchasing exclsuive rights without your attention.

**Reported version**: _1.2.3_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_surferconor425_ wrote:**

> I could make a NewGRF for this if you like

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5443#comment11950_

**Comment by DorpsGek** [comment]
**_onimoschta_ wrote:**

> I would appreciate that very much! Thank you for your offer

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5443#comment11996_

**Comment by DorpsGek** [comment]
**_trainqa_ wrote:**

> A useful extension would be to display ALL "Local Authorities" on the screen.  Change the color of the overlay for the color of the company that has transport rights.
> 
> Other options within the GUI:
> \- Icons in Station List to show a "DO NOT ENTER" sign next to the station, indicating it is blocked.
> \- Text in the Station Detail window to show "XXX Transport has Exclusive Transport Rights".

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5443#comment12268_

**Comment by andythenorth** [comment]
Could this be done with gamescript?  Maybe putting it in the goals window?

https://nogo.openttd.org/api/1.4.3/classGSEventExclusiveTransportRights.html

Otherwise, I see the issue, but I don't think it's a current goal, and there's nobody currently who wants to push it through.
