### ISSUE TITLE
Ship controller can only move one position per tick

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5454]
**_peter1138_ opened the ticket and wrote:**

> The ship controller needs to be updated to handle moving a ship more than once per tick for speeds above 80mph, as the other vehicle controllers do.

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> First attempt: http://git.fuzzle.org/openttd.git/log/?h=fs5454
> 
> Some of this stuff is in inherited classes for road vehicles and trains. Perhaps a ship is also a ground vehicle?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5454#comment11919_

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> Or limit ships to just below 80mph? :D

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5454#comment11921_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> The idea of ground vehicles was to work towards RV consists with trailers, much like train wagons.
> 
> I don't think tug boats are reason enough to consider ships as ground vehicle :)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5454#comment11923_

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> Articulated ships!
> 
> http://www.seabreezes.co.im/index.php?option=com_content&view=article&id=964:ss-connector&catid=6:letters-to-the-editor&Itemid=154

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5454#comment11928_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> From irc:
> 
> peter1138: andythenorth, the patch to make ships faster worked, iirc
> peter1138: it was just... pointless 
> peter1138: instant stopping was a problem
> peter1138: that's even worse for ships

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5454#comment14614_

**Comment by TrueBrain** [comment]
Original author indicated he now considers this request (not a bug btw) pointless. Closing!
