### ISSUE TITLE
Vehicles: access the user-defined bits of a specific vehicle only (in a train consist)

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5460]
**_Snail__ opened the ticket and wrote:**

> Hi all!
> 
> I would like to request a new way to access the user-defined bits of a vehicle inside of a train consist.
> So far we have a function that allows us to do "ORing" across the userbits of a certain vehicle + all the vehicles in the consist after that one.
> How about a function that only allows us to check a certain vehicle's userbit pattern, ignoring the bits of the following vehicles?
> 
> It would be very useful to check for info about a specific vehicle in the consist, without having it "blurred" by the other wagons' info.
> 
> Of course, this shouldn't replace the current way we go through userbits (at least for compatibility's sake), but it could be a very useful added feature.
> 
> Thanks in advance!

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Hi Snail, it would be useful to discuss this in irc to find out (a) what the intended use is (b) if it's still valid 4 years later.
> 
> Flyspray is being cleaned, so I'd like to close any feature requests which are no longer useful, or not likely to be implemented :) In some newgrf cases, an alternative way has been found since the original feature request was opened.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5460#comment14683_

**Comment by DorpsGek** [comment]
**_Snail__ wrote:**

> Yes it's still needed. I tried a few workarounds, but they didn't really work.
> It's needed mostly for my push-pull implementation. Although some people might think push-pull is a BAD FEATURE altogether, it's a core part of my set; being able to access a specific vehicle's userbit pattern (without ORing) will be able to add new functionality, and also to make my code cleaner.
> I'll try to get on irc in the next few weeks if you need to talk more about this

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5460#comment14689_

**Comment by andythenorth** [comment]
There is very little that can't be done by checking specific vehicle IDs in the chain.  I am closing this. If you want to discuss in irc we'll see if we can get your problem solved :)
