### ISSUE TITLE
Vehicles: callback to populate vehicle purchase list 

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5471]
**_Pikka_ opened the ticket and wrote:**

> It would be nice to have a callback to add/remove vehicles from the purchase list, so that different players could have different vehicles available (similar to the way, at the moment, one player can have access a prototype vehicle that other players do not).
> 
> The only use of this callback I can think of is:
> 
> c) giving players exclusive vehicles in multiplayer games (for example, player 1 gets German trains and player 2 gets French trains).
> 
> Callback returns 0 to allow and 1 to hide vehicle from buy list. Perhaps 2 to display vehicle but not allow construction?  This callback (or some other callback) should also have the ability to auto-reject new vehicle prototypes. Otherwise players will be offered prototypes of vehicles they're not going to be able to build.
> 
> New variables which would be nice, but not essential, for this callback are:
> 
> a) availability of other vehicle (x). This would allow, for example, specialist wagons to be hidden before the locomotive which hauls them appears.
> b) count of vehicle (this/x) (owned by this player/everyone). This would allow authors to limit the number of a particular vehicle, if they wanted to do that for some reason.

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> Second attempt at the description, previous attempt was in #5467

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5471#comment11999_

**Comment by DorpsGek** [comment]
**_Eddi_ wrote:**

> Implementation details:
> src/engine_base.h:Engine already has this member:
> 	CompanyMask company_avail;  ///< Bit for each company whether the engine is available for that company.
> 
> 
> it just needs a NewGRF-y way to set the value.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5471#comment12000_

**Comment by DorpsGek** [comment]
**_Eddi_ wrote:**

> A possible use-case for this callback would be to force availability of vehicles circumventing the builtin randomisation.
> E.g for EMU-Wagons to become available immediately when the matching EMU gets offered as a prototype/general availability.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5471#comment12002_

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> http://irclogs.qmsk.net/channels/openttd/link/1360588209# 1360588209  some random conversation in # openttd about this issue.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5471#comment12003_

**Comment by DorpsGek** [comment]
**_Pikka_ wrote:**

> http://www.tt-forums.net/viewtopic.php?f=68&t=59630&p=1065767# p1065767

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5471#comment12004_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Not convinced that this is super-useful, but eh.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5471#comment14682_

**Comment by andythenorth** [comment]
Not any more convinced that this is a (good) BAD FEATURE.  Let's close it.
