### ISSUE TITLE
Vehicles: change vehicle life via CB 36

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5474]
**_George_ opened the ticket and wrote:**

> R25004
> 
> It would be nice to have different vehicle life during model life (required for new vehicles only, already built vehicles should not change their vehicle life), selected with CB 36.
> It would allow shorter vehicle life during the testing phase (for example 10 years), while in the later years it would be 30 years or even more

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Snail__ wrote:**

> I think it could work for already-bought vehicles as well. Think refurbishing...

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5474#comment12020_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> I think this is TMWFTLB, but I have left it open.  There are probably more valuable things that could be worked on.  Let me know if it's no longer needed.  Thanks.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5474#comment14694_

**Comment by andythenorth** [comment]
We're cleaning again to make priorities clearer and get some progress on core OpenTTD :)

This one isn't a high enough priority, so I'm closing it, thanks.
