### ISSUE TITLE
Provide the global random seed to NewGRFs

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5487]
**_Eddi_ opened the ticket and wrote:**

> This patch introduces NewGRF global var 26, offering the world generation seed to NewGRFs, to potentially randomize parameters of the NewGRF.
> 
> What remains to be checked is that the value _settings_game.game_creation.generation_seed is already initialized during GRF activation and will not be changed afterwards.

**Attachments**
- [newgrf_random_seed.diff](https://bugs.openttd.org/task/5487/getfile/8940/newgrf_random_seed.diff) (0.36 KiB)

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> I guess in theory this would belong to Action D Patch Vars.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5487#comment12048_

**Comment by DorpsGek** [comment]
**_Eddi_ wrote:**

> judging from the comment:
>  \* Returns VarAction2 variable 'param' resp. Action7/9/D variable '0x80 + param'.
> 
> i assume they use the same code.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5487#comment12052_

**Comment by DorpsGek** [comment]
**_Eddi_ wrote:**

> I have an update here, that also adds a variable 27 which has different random bits for each GRF. in theory (tm) this should provide the same random bits on reload and on reapply GRFs, unless you change the number or order of GRFs.

**Attachments**
- [newgrf_random_seed2.diff](https://bugs.openttd.org/task/5487/getfile/8944/newgrf_random_seed2.diff) (2.26 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5487#comment12053_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> I think you should better store those in the save instead of making them depend on the GRF loading order. That should be more fail-safe wrt. changes to the way base graphics work or similar.
> 
> Also, what is then intention of this feature wrt. scenarios? Shall they have the same value everytime, or shall it be rerandomised on scenario start like vehicle reliabilities?
> 
> My earlier comment refers to using GetPatchVariable() instead of GetGlobalVariable(). The former is more suitable for stuff which does not change during a game.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5487#comment12054_

**Comment by DorpsGek** [comment]
**_Eddi_ wrote:**

> this attempt features a completely different method, instead of providing variables, the action 14 is amended with a "random" type, where the parameter will be filled with random bits. needs additional magic to make sure the chosen random value is within the given limits of the parameter.

**Attachments**
- [newgrf_random_seed3.diff](https://bugs.openttd.org/task/5487/getfile/8947/newgrf_random_seed3.diff) (1.77 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5487#comment12057_

**Comment by DorpsGek** [comment]
**_Eddi_ wrote:**

> improved version now with support for min/max ranges
> 
> next task would be some test grfs for functionality tests. and when does/should rerandomisation happen? (upon starting the grf scan, upon adding the grf to the list, upon scenario/savegame creation?)

**Attachments**
- [newgrf_random_seed4.diff](https://bugs.openttd.org/task/5487/getfile/8949/newgrf_random_seed4.diff) (3.20 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5487#comment12074_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> I guess it should no rerandomise when starting a prepared scenario.
> 
> So I guess randomisation should happen when adding a GRF to a game, that is when starting a game, or when adding in mid-game. Though I am not sure how the editing of GRFs in-game compares to adding GRFS when starting a new game.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5487#comment12075_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> How should the NewGRF parameter GUI handle this? Hide parameter completely?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5487#comment12490_

**Comment by DorpsGek** [comment]
**_Eddi_ wrote:**

> Yes, doesn't make a lot of sense to display it, i think.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5487#comment12492_

**Comment by DorpsGek** [comment]
**_Eddi_ wrote:**

> the currently best idea to handle randomization is to have the generator for the parameter values be initialized iwth (map_seed XOR grfid). this means there is no correlation between random bits for different NewGRFs, but the same NewGRF will retain values even when reordering NewGRFs or updating versions.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5487#comment13481_

**Comment by andythenorth** [comment]
andythenorth: Eddi|zuHause had a patch for this https://github.com/OpenTTD/OpenTTD/issues/5487
[8:53pm] andythenorth: still want it open? 
[8:54pm] andythenorth: can it be a PR?
[8:54pm] Eddi|zuHause: i can't comment on how finished that was
[8:55pm] Eddi|zuHause: the comments sound like there were a bunch of open philosophy questions
[8:55pm] TrueBrain: I guess andythenorth is asking: do you want to make a PR out of it and see it through, or shall we close it? 
[8:55pm] andythenorth: what TrueBrain said
[8:55pm] andythenorth: PR, or move on
[8:55pm] andythenorth: all of us 
[8:56pm] Eddi|zuHause: i'd have to dig a little deeper to decide that

**Comment by andythenorth** [comment]
Re-open if you think it's still valid ;)
