### ISSUE TITLE
Audio: music volume control for the extmidi driver

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5499]
**_sfriebe_ opened the ticket and wrote:**

> This patch enables the volume control for the extmidi driver.
> It gives the selected volume as parameter to timidity when a new song is started.
> 
> Even when it works, it has a few problems:
> \- It probably only works with timidity.
> \- The volume only changes when a new song is started, but that is better than no volume control at all.

**Reported version**: _trunk_
**Operating system**: _Linux_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> I guess you also had planned to attach a patch file :)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5499#comment12080_

**Comment by DorpsGek** [comment]
**_sfriebe_ wrote:**

> Okay, next try. Is there another button except for "browse"?
> Edit: Ha, this time it worked. Strange...
> Edit2: Or not strange at all. I forgot the summary and after it send me back to add it, the file was forgotten.

**Attachments**
- [extmidi_patch.diff](https://bugs.openttd.org/task/5499/getfile/8955/extmidi_patch.diff) (1.26 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5499#comment12081_

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> It doesn't just only work for timidity, it also prevents other players from working.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5499#comment12084_

**Comment by DorpsGek** [comment]
**_sfriebe_ wrote:**

> Okay, thats a point i haven't thougth about.
> It could be solved with defines, but the code does look a bit messy now.
> Doing this for all players is not possible, however since timidity is
> the default player this construct might be okay.

**Attachments**
- [extmidi_patch.diff](https://bugs.openttd.org/task/5499/getfile/8957/extmidi_patch.diff) (1.81 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5499#comment12085_

**Comment by DorpsGek** [comment]
**_s0r00t_ wrote:**

> [redacted, did not read the date correctly]

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5499#comment14404_

**Comment by andythenorth** [comment]
No progress for 5 years, let's say this one's time has passed :)  Happy to re-open if needed.
