### ISSUE TITLE
Improved readability in company finances window

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5551]
**_kvee_ opened the ticket and wrote:**

> This patch improves readability in the company finances window by regrouping some values and introducing a separator value in the ExpensesType enum.

**Attachments**
- [finances_gui_r25249.diff](https://bugs.openttd.org/task/5551/getfile/9031/finances_gui_r25249.diff) (2.04 KiB)
- [new_finances_window.png](https://bugs.openttd.org/task/5551/getfile/9032/new_finances_window.png) (11.17 KiB)

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> Changing the default layout is not an option, in my opinion.
> Instead, you should look into adding something so your layout becomes a 3rd way of showing finances.
> 
> My second main problem with your patch is that you add yet another permutation of displaying the same numbers. How many of these do we need before we have "enough"?
> Personally, I never look at these numbers, the "vehicle has negative income" warning provides sufficient information (and much quicker too) to steer my empires.
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5551#comment12223_

**Comment by DorpsGek** [comment]
**_kvee_ wrote:**

> Well, I use this window from time to time and it seems unnecessarily cluttered to me.
> The point of this patch is to simply rearrange the values, so that relevant values are next to each other. Seeing as many other windows underwent slight cosmetic changes (always for the better) in the past, while this one never did, I thought this would be a nice, clean way to improve it. Especially given the relatively small code change necessary.
> 
> And I agree, no point in adding anything new. This really is precisely about changing the default layout for a better one. If that's not an option, well, there's not much else I can do.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5551#comment12224_

**Comment by DorpsGek** [comment]
**_NG_ wrote:**

> > Changing the default layout is not an option, in my opinion.
> 
> > Personally, I never look at these numbers
> If you really don't, why even care? That being said, the optimal solution would probably be switching between a group-by-item view as in this patch and an income-above-expenses view. The standard window is just an awkward mix of both, and could certainly do with some spacing no matter what.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5551#comment12225_

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> Because I know users will get very upset when you change their windows.
> But if you don't want my feedback or time to add it, that's ok too.
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5551#comment12227_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Oh well, there is already a setting to choose between two window layouts... and last time people wanted a "formally correct" balance sheet which grouped expenses and income. So, I guess this would need a third value, or other people will complain.
> 
> Personally I do not see much use in grouping it per vehicle type. There is no bigger difference between vehicle types than between vehicle groups. And likely profit per group is a lot more interesting, than per vehicle type.
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5551#comment12228_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> This would actually be my preferred layout.  The balance sheet view is 'correct' but kind of tedious, just like a balance sheet in the real world.  I prefer to know if each vehicle type is actually making money.  But then transfers....or maybe I have 10 vehicles losing money, and 1 making a lot of money?  Basically finances window is mostly useless eh?
> 
> So dunno if this is worth including.   Yet Another Way To Display Finances.  Do we have enough fragmented UI options already? :|

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5551#comment14529_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Tested this, compiles on r27910
> 
> Finances window opens far too wide for my viewport, with no option to resize.
> 
> Will close if no further commentary on this.

**Attachments**
- [FS5551.png](https://bugs.openttd.org/task/5551/getfile/10845/FS5551.png) (454.16 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5551#comment14726_

**Comment by TrueBrain** [comment]
I think this has been talked about enough to close it up. Sorry.
