### ISSUE TITLE
Vehicle Command to Sell Vehicle at Depot

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5573]
**_trainqa_ opened the ticket and wrote:**

> The purpose of this enhancement is for better management of large number of vehicles.
> 
> Add the ability to "Sell Vehicle".  This would obey the option in my previous feature request regarding immediacy of commands, and would then proceed to the depot and be sold.  While not a huge issue, it would "solve" the issue of where an old vehicle is sent to a depot, replaced at cost, and then the user turns around and sells it. 
> 
> Useful for under-performing vehicles.

**Reported version**: _1.3.0_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Profa_ wrote:**

> \+1 vote

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5573#comment13473_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Rondje style play, eh :x

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5573#comment14681_

**Comment by TrueBrain** [comment]
I don't see how this fits in OpenTTD. I understand your use-case, but it sounds like a very limited use-case, for an invasive UI change. Going to say "no" for now. Feel free to rebuttal.
