### ISSUE TITLE
[Windows] Switching tracks quickly in jukebox

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5585]
**_Brumi_ opened the ticket and wrote:**

> If I switch tracks in the jukebox quickly by pressing 'next/previous track' multiple times in a quick succession, the wrong track will start playing. For example, if track 1 is playing, and then I press 'next' two times to play track 3, track 2 will play instead. The bug is present for me with all music sets.

**Reported version**: _1.3.1_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_Phrossi_TTD_ wrote:**

> Confirmed, happens to me too.
> Proably cause is the game not updating the music quick enough?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5585#comment12310_

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> I cannot reproduce this on Linux, and there seems to be quite a lot of magic w.r.t. waiting in the Windows music driver, so I suspect it to be Windows only.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5585#comment12403_

**Comment by DorpsGek** [comment]
**_Jaap_ wrote:**

> I could reproduce it on Windows 7 64bit, also with the newest r25939.
> 
> It seems that the command to open the song takes too much time. When skipping some songs within a couple of seconds, the action to load the latest song will not be taken while the old song is loading.
> I made a patch which compares the current song against the requested song to make sure that the correct song will be loaded finally.
> 

**Attachments**
- [Music.patch](https://bugs.openttd.org/task/5585/getfile/9458/Music.patch) (1.82 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5585#comment12745_

**Comment by nielsmh** [comment]
The above patch is obsolete with the new music drivers on Windows, and the issue needs to be tested again. It should also be tested on non-Windows systems with various drivers.

**Comment by nielsmh** [comment]
Looking at the description of this again, it's seems to have been an artifact of the old MCI-based Win32 music driver, which had the exact issue on newer Windows versions of taking multiple seconds to load each song. The new drivers typically load a song in less than 100 ms so I think the issue can be considered fixed.
