### ISSUE TITLE
NewGRF Vehicles: special flag for cargo subtype text (hidden text)

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5588]
**_George_ opened the ticket and wrote:**

> R25306
> 
> Currently it is impossible to safely remove entries from liveries list (cargo subtype texts)
> In case var F2 holds a value, that points to undefined string in cargo subtype callback, no name would be should in the information window.
> In case the string is defined, this cargo subtype is also available for refit.
> 
> The idea is to have a flag (for example a special character in the beginning of the string) to disallow the refit, but allow a text in the vehicle information window.
> 
> What is it required for: during vehicle life (especially when it is very long) you can apply, for example, special recolouring for the vehicle. When time passes this recolouring becomes unavailable, but previously refitted vehicles should hold their colours. At the same time they can be repainted to the new colours, while newly repainted vehicles (new or old) can't be repainted into the old colours.

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_mb_ wrote:**

> > Currently it is impossible to safely remove entries from liveries list (cargo subtype texts) [...]
> 
> I´m using an empty string for things like this. And you could probably re-arrange the values of varF2 according to vehicle age or current era, to reflect that.
> 
> regards
> Michael

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5588#comment12283_

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> I suppose that means that in the information window you get no text instead of old text. 
> So, that would not fix my problem

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5588#comment12287_

**Comment by andythenorth** [comment]
TMWFTLB - more complexity in cargo subtypes isn't going to be implemented.  Closing thanks.
