### ISSUE TITLE
Game Script: StoryPageElementType SPET_EVENT

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5616]
**_idioty_ opened the ticket and wrote:**

> When someone click on one element in the story book, call new GSEvent with reference ID. Like GSEventGoalQuestionAnswer.

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Zuu_ wrote:**

> I was thinking about adding some type of answer option element that will allow you to ask questions in the Story Book. However I have left it out of the initial Story Book implementation that is now in trunk. 
> 
> The Story Book wiki contains a section for possible future extensions: https://secure.openttd.org/wiki/Story_book# Possible_future_extensions
> 
> I haven't yet figured out how I want to implement this. I don't think that there should be an event for items used to refer to tiles/goals. These elements allow the GS to refer to things without there being a delay between the click of a button and the GS responding.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5616#comment12348_

**Comment by DorpsGek** [comment]
**_Zuu_ wrote:**

> To allow for some discussion, I can see multiple ways to do this:
> 
> \- radio + check buttons that submit upon the click of either some submit/ok-button inside the page view or upon click of next
> \- buttons/elements that send an event when the user clicks on them (like your suggestion)
> 
> 
> With radio buttons, can there be multiple radio groups on one page?
> 
> To follow TTD style, the radio buttons possible should be implemented as a drop-down or using push buttons.
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5616#comment12349_

**Comment by DorpsGek** [comment]
**_idioty_ wrote:**

> I like both of these solutions.
> The drop-down list is more transparent than the radio buttons.
> I think you should submit button and also linkable components may be.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5616#comment12353_

**Comment by DorpsGek** [comment]
**_idioty_ wrote:**

> Any news on this?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5616#comment12481_

**Comment by DorpsGek** [comment]
**_Zuu_ wrote:**

> I haven't started on any implementation yet. There are still things like #5617 to fix. Also I have planned to hide the story/goal buttons in the main menu when no pages/goals exist.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5616#comment12482_

**Comment by DorpsGek** [comment]
**_idioty_ wrote:**

> thanks!

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5616#comment12484_

**Comment by DorpsGek** [comment]
**_idioty_ wrote:**

> I need to clickable elements also in StoryPage element with GSText:
> {TOWN}: show the town,
> {COMPANY}: show the companys info window, etc...

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5616#comment12634_

**Comment by DorpsGek** [comment]
**_Zuu_ wrote:**

> For {TOWN} you can use SPET_LOCATION and feed it with the location of your town.
> 
> Yes it would be pretty with a town icon, a station icon etc. but I chosen to only use a generic SPET_LOCATION to simplify things.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5616#comment12635_

**Comment by DorpsGek** [comment]
**_idioty_ wrote:**

> Thanks, you're right with SPET_LOCATION! :)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5616#comment12639_

**Comment by TrueBrain** [comment]
I fully agree this can be useful, but a list of wishes already exist! So I don't think keeping this issue around is helping; closing!
