### ISSUE TITLE
Symbol search if symbol missing in the current font

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5628]
**_George_ opened the ticket and wrote:**

> R25522
> 
> GRFs define strings in UTF-8, that allows using a lot of symbols of different languages, special chars and so on. Unfortunately, when OTTD finds a missing symbol in the selected font, it displays ⃞ symbol. It would be much better if OTTD would look for the symbol in the other fonts, because the GRF can't store font file with all the symbols inside the GRF.

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> May be it would be also possible to include font files into bananas packages, so the OTTD knew where to search these missing symbols?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5628#comment12413_

**Comment by TrueBrain** [comment]
I see and understand what you are saying, but I don't see this happening any time soon. In general, OpenTTD needs a bit of work to properly support UTF-8 in all kinds of places. So sorry, going to pass for now.
