### ISSUE TITLE
Refitting doesn't display all available liveries for group of wagons

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5631]
**_George_ opened the ticket and wrote:**

> r25522
> 
> I've found the following problem while coding and playing xUSSR EMUs
> The even wagons have one list of liveries, while  non-even wagons have the other list. When selecting the whole train for refit, no livery is available. 
> This makes the player to refit wagons one by one that is very hard.
> It would be much better to have a list of all the liveries available for even and non-even wagons displayed for the whole train being refitted, and choosing the livery to refit would apply only to the wagons, which support chosen livery (even or non-even in my case). 
> This would allow to refit the train only with 2 refit commands.

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Is this behaviour due to the same cause as #3764?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5631#comment14693_

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
