### ISSUE TITLE
AI: "error: wrong number of parameters" - show number used and number of expected?

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5652]
**_Kogut_ opened the ticket and wrote:**

> "error: wrong number of parameters" - is it possible to show number of used and number of expected?
> 
> I am currently debugging weird situation where I am certain that I use 0 parameters for function that wants 0 and additional info would show me where I am wrong. I remember previous situations where this would be helpful.

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
