### ISSUE TITLE
fix VS 2012 FACILITY_DIRECTMUSIC warning

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5663]
**_adf88_ opened the ticket and wrote:**

> Since some new SDK (not sure which version, VS 2012 installer use it) <winerror.h> contains FACILITY_DIRECTMUSIC macro definition. This macro is also present inside <dmerror.h> (the one from the "handy zip file containing direct music headers") causing a warning. The patch fixes it by undefining FACILITY_DIRECTMUSIC befor including dmusic headers.

**Attachments**
- [fix-vs2012-dmerror-warning.diff](https://bugs.openttd.org/task/5663/getfile/9195/fix-vs2012-dmerror-warning.diff) (0.45 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_adf88_ wrote:**

> Also see my comment here http://bugs.openttd.org/task/5375 (Fix __forceinline in Visual Studio 2012)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5663#comment12431_

**Comment by nielsmh** [comment]
Either #6787 or #6774 will probably obsolete this.

**Comment by michicc** [comment]
Fixed by #6787.
