### ISSUE TITLE
Better multuiple screens support

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5664]
**_arny73_ opened the ticket and wrote:**

> I am using two screens. Left one is the main screen with taskbar. Right is additional. 
> 
> I extended OTTD window to both screens. However it doesn't remember its location (top-left coords) when exits and always starts centered related to the first of my screens. Thus, OTTD left corner is outside of my screens.
> 
> Suggestion - keep/restore not only screen size, but its location as well.

**Reported version**: _1.3.2-RC2_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_dude17172009_ wrote:**

> Is Bug # 5714 something you are looking for?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5664#comment12538_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Possibly related http://bugs.openttd.org/task/4637

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5664#comment12851_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Possibly OS-specific, and not solvable by OpenTTD.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5664#comment14557_

**Comment by TrueBrain** [comment]
Currently it is not on the roadmap to support two screens in OpenTTD, nor is remembering window location.

Borderless Window play might be worth considering.
