### ISSUE TITLE
'Default sort order' to defines different sort orders depending of the used criteria

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5678]
**_sbr_ opened the ticket and wrote:**

> In r25096, TownPopulationSorter() was reversed to put most populated towns at the top of the list.
> While it's desirable, it was inconsistent with the selected sort order.
> 
> 
> The '00feature-default-sort-order' patch modify 'sortlist_type.h' to introduce the notion of default sort order.
> It permits to define a preferred sort order per criteria instead of reusing the last used sort order.
> 
> SetDefaultSortOrders() defines the default sort orders to use per sort criteria.
> If a default sort order is defined for the current sort criteria, UseDefaultSortOrder() set the current sort order to it.
> Three default sort order types are defined:
>   \- DSO_NONE: don't alter the current sort order;
>   \- DSO_ASCENDING: switch the current sort order to descending;
>   \- DSO_DESCENDING: switch the current sort order to descending.
> UseDefaultSortOrder() returns a boolean indicating if the current sort order has been changed or not.
> 
> 
> The '10change-town-directory-default-sort-orders' patch sets default sort orders to the town directory as follow:
>   \- sort by name: ascending;
>   \- sort by population: descending;
>   \- sort by rating: no default order.
> 
> 
> The '11change-industry-directory-default-sort-orders' patch sets default sort orders to the industry directory as follow:
>   \- sort by name: ascending;
>   \- sort by type: ascending;
>   \- sort by production: descending;
>   \- sort by transported: descending;
> 
> 
> Please find attached theses three patches against r25628.
> 

**Attachments**
- [00feature-default-sort-order_1ae4021b468b.patch](https://bugs.openttd.org/task/5678/getfile/9200/00feature-default-sort-order_1ae4021b468b.patch) (2.85 KiB)
- [10change-town-directory-default-sort-orders_1ae4021b468b.patch](https://bugs.openttd.org/task/5678/getfile/9201/10change-town-directory-default-sort-orders_1ae4021b468b.patch) (1.84 KiB)
- [11change-industry-directory-default-sort-orders_1ae4021b468b.patch](https://bugs.openttd.org/task/5678/getfile/9202/11change-industry-directory-default-sort-orders_1ae4021b468b.patch) (1.98 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
Thanks for this, but we'll pass :)  Changing the default sort orders is not a current priority.
