### ISSUE TITLE
NewGRF viewer in game

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5689]
**_Milsa_ opened the ticket and wrote:**

> Please add NewGRF viewer directly to "NewGRF Settings" for better selecting NewGRFs.

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> What's a NewGRF viewer?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5689#comment12472_

**Comment by DorpsGek** [comment]
**_Milsa_ wrote:**

> It would include:
> 
> List of vehicles:
> \- image of object
> \- date of produce
> \- speed
> \- capacity
> \- etc...
> 
> List of buildings:
> \- image
> 
> List of industry:
> \- cargo in
> \- cargo out
> \- etc...
> 
> Etc...

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5689#comment12473_

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> This is not generally possible, NewGRFs are not simple lists of stuff that it contains, they are piece of program code, which get executed and combined together hopefully give a good result. OpenTTD doesn't actually know the information you want, it just repeatedly asks "can I do this?", and the NewGRF says yes/no. It does however never give the rule that it uses to make the decisions.
> 
> Also, OpenTTD is a simulator. Things happen at the time they happen, not before, not after. You don't get announcements when existing objects will disappear nor when new objects can be expected.
> 
> If we would provide such lists, all fun of discovering new items of a NewGRF would be gone, as well as the desperation of needing a better aircraft, and anxiously awaiting the announcements to see whether one becomes available.
> 
> 
> I do see your point however, but to me, it feels like the NewGRF author(s) should provide that information. They made the NewGRF, they know what's in it, and could "sell" it to you by means of explaining how great it is, and what features it has. (Something like an A4 poster with the highlights.)
> 
> Some authors make a nice web-page for this, others don't do anything, it seems.
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5689#comment12477_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> I guess overall this request heads towards: http://wiki.openttd.org/Frosch/NewGRF_Configuration_in_Utopia
> 
> I don't think "exploring a set" is valid reason against a feature like this. You will hardly explore a set by looking at a list of all available stuff. After all every set would be a one-time experience in that case, since you obviously can see the whole list in game when playing a game till 2050, or even starting it at that point.
> 
> NewGRF authors providing a readme imposes a work on NewGRF authors, generically generated information in game would be better for everyone: Less work for authors, always complete and up-to-date for players.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5689#comment12486_

**Comment by DorpsGek** [comment]
**_Milsa_ wrote:**

> Example:
> 
> I didn't know that trams is only in downloaded NewGRF. If I want trams in game, I must download NewGRF with trams. I didn't know it.
> 
> If NewGRF viewer will be in game I find trams in list and I will use that NewGRF.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5689#comment12489_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> I think the aims are nice, and I am +1 to grftopia, but this looks not-implementable as written by Milsa.  NewGRF just doesn't work this way.  Look at the multiple FS requests just for trains to see all the dynamic behaviour that newgrf authors can and do implement in newgrfs.  This behaviour cannot be reliably determined anywhere outside of a running game.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5689#comment14680_

**Comment by DorpsGek** [comment]
**_Milsa_ wrote:**

> Only base informations is enough (image of vehicle, limits (velocity, cargo, capacity), year of production).

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5689#comment14712_

**Comment by TrueBrain** [comment]
Eyecandy! Nice idea, but a large project. Currently not on the roadmap.
