### ISSUE TITLE
Patch to make filter_funcs members of BuildVehicleWindow

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5695]
**_Vaulter_ opened the ticket and wrote:**

> Subj.
> I see that this one filter func dont use anything window class specific, but... it is just 

**Attachments**
- [bvw_ff.patch](https://bugs.openttd.org/task/5695/getfile/9248/bvw_ff.patch) (1.94 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> Just moving a single static function into a class in the same file doesn't help much, given that static functions are common in OpenTTD (and perhaps even in C++, as not everything has to be a method or part of a class in that language).
> 
> The patch also breaks the general pattern of all the other filter functions, which makes it less easy to find and re-use if the need arises.
> 
> 
> In other words, while the thought is alright, the scale is too small.
> 
> If you want to move these functions, it needs a new general pattern of handling these filter functions (or handling filtered lists, or something else, where the filter functions are apart of).
> From such a new pattern you can then change all filter functions, and improve the general structure.
> 
> 
> 
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5695#comment14722_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Close if no reply by end of 2017.  Thanks.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5695#comment14761_

**Comment by andythenorth** [comment]
Ok it's 2018
