### ISSUE TITLE
News history filtering

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5709]
**_Wormnest_ opened the ticket and wrote:**

> This patch, consisting of 5 hg patches, provides filtering of the news history window based on the way the stations window filters vehicles and cargo.
> A new dropdown list is added showing all available types of news and a all news category. The all news category contains all news unfiltered, the other categories will only show the news that is of the selected type.
> For news about vehicles and engines there is an additional vehicle type filter to be able to only show vehicles of the types you are interested in.
> The same for industries, you can select the producing cargos you want to be shown.
> 
> This patch is based on trunk r25721.
> 
> Problems/shortcomings:
> For industries that produce more than 1 cargo it is currently not possible to only filter on the cargo type that is mentioned in the news item. e.g. when you get a message about livestock production increasing it will both be shown when filtering on livestock and on grain.
> Closing industries can't be filtered on cargo type, since they are closing the industry data isn't sent with the news message.
> 
> Possible improvements:
> An all news types category but with filters for vehicle and cargo types active.
> Combine some news type categories since several of them have a very low amount of news.
> Combining the industry production news types might make sense to, however then there would have to be another filter added for opening/closing, own industry/ competitor/ unserviced.

**Attachments**
- [OpenTTD trunk_20707.patch](https://bugs.openttd.org/task/5709/getfile/9274/OpenTTD+trunk_20707.patch) (2.43 KiB)
- [OpenTTD trunk_20708.patch](https://bugs.openttd.org/task/5709/getfile/9275/OpenTTD+trunk_20708.patch) (1.67 KiB)
- [OpenTTD trunk_20709.patch](https://bugs.openttd.org/task/5709/getfile/9276/OpenTTD+trunk_20709.patch) (1.14 KiB)
- [OpenTTD trunk_20710.patch](https://bugs.openttd.org/task/5709/getfile/9277/OpenTTD+trunk_20710.patch) (8.95 KiB)
- [OpenTTD trunk_20711.patch](https://bugs.openttd.org/task/5709/getfile/9278/OpenTTD+trunk_20711.patch) (10.37 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
News isn't so important, it's events in the past eh. :)

Filtering meanwhile always has complications (UI, preserving / clearing state, bug reports of missing items due to filters being applied).   All resolvable, but takes work to catch it all.

Let's pass on this one.  Feel free to re-open if someone is prepared to push this through.
