### ISSUE TITLE
Boats sent to unreachable depots

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5713]
**_Leftie_ opened the ticket and wrote:**

> Hiya.
> 
> Boats sometimes attempt to go to places they are simply unable to reach. I first saw this on the TT-F forum, here http://www.tt-forums.net/viewtopic.php?f=29&t=68364&p=1093057#p1093055
> 
> I then tried to replicate it to see if it was still possible in the current version (1.3.2). Using YAPF, i managed to recreate this. Boats attempted to go to a depot that was nearer, but was completely inaccessible through any valid means, and totally ignored a boat yard further away, but in clear open waters.
> 
> My attempt at replication is in the below screenshot, using OpenTTD 1.3.2 and YAPF as the pathfinder in advanced settings.

**Reported version**: _1.3.2_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Leftie_ wrote:**

> Whoops, screenshot attached, it seems it wasn't done in the original post, possibly due to my forgetting to add the title and being prompted to re-enter ;)
> 
> edit: also if its of value, this is a vanilla game, there are no GRFs involved, at all, although i did cheat (ctrl+alt+c) to get the money needed to mess with terrain.

**Attachments**
- [Prennston Transport, 2001-04-19.png](https://bugs.openttd.org/task/5713/getfile/9283/Prennston+Transport%2C+2001-04-19.png) (204.87 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5713#comment12530_

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> Could you please provide a save game before the problem happens, and a (preferably) short sequence of steps to do, to replicate the issue?
> That gives us the certainty we talk about the exact same problem, gives an easy means to examine the issue closer, and also verify afterwards that it is fixed.
> 
> A vanilla game without newgrf would be preferable, cheating for money is no problem. In general using trunk or a recent nightly is best, but latest stable will work too.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5713#comment12532_

**Comment by DorpsGek** [comment]
**_LordAro_ wrote:**

> I got bored and decided to reproduce this
> 
> r25725
> 
> 

**Attachments**
- [Muir & Co., 1970-01-22.sav](https://bugs.openttd.org/task/5713/getfile/9284/Muir+%26+Co.%2C+1970-01-22.sav) (6.32 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5713#comment12533_

**Comment by DorpsGek** [comment]
**_LordAro_ wrote:**

> far as i can tell, the unreachable depot must be closer to the ship than the 'reachable' depot

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5713#comment12534_

**Comment by DorpsGek** [comment]
**_krinn_ wrote:**

> Have a look at http://bugs.openttd.org/task/5656
> i have a savegame there, it is not limited to boats or limited to the YAPF (but i'm unsure if road vehicle use it or not)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5713#comment12535_

**Comment by DorpsGek** [comment]
**_Leftie_ wrote:**

> LordAros save is accurate. You basically just need a boat and two depots, one of them (the nearest) being impossible to go to due to land. The boat will always choose the nearest depot. My best guess is that clicking on the depot button is missing a check, and it doesn't actually see if its possible to go to the depot, it just chooses the nearest instead of trying to plot routes to see.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5713#comment12539_

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> Ships are stupid... they find the closest depot by finding the one with the shorted manhattan distance, instead of the distance it would need to travel. Probably as optimisation for finding the closest one, which can be extremely expensive when there isn't a reachable depot but it still has to search a vast amount of the map.
> 
> I'm not quite sure whether we actually want this 'optimisation' fixed or not.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5713#comment12747_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> I guess it needs both:
> \* First check whether there is a depot near-by using the bird-distance heuristic.
> \* Then run the pathfinder to check the actual distance/reachability.
> 
> As mentioned by juanjo in #6410, YAPF only supports limited search distances for trains. Road- and ship pathfinder always search to the destination, without limit.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5713#comment14198_

**Comment by 2TallTyler** [comment]
Note from Discord conversations: #10543 does not fix this issue, because boats still try to find the closest depot based on Manhattan distance, without using the pathfinder to see if they can actually reach that depot.
