### ISSUE TITLE
Add news messages to crashlog

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5722]
**_LordAro_ opened the ticket and wrote:**

> As per the Todo list, i have added pending news messages to the crashlog
> 
> hg patch queue, based on r25739
> patch 02_ isn't strictly necessary, but is nice to have :)
> 
> However, i would like some feedback regarding patch 03 - 
> Alberth pointed out to me that converting StringIDs to text after a crash probably isn't very safe.
> So, should i store a char* of the message in the NewsItem object, or just list the relevant numbers from the NewsItem? Or something else altogether?

**Attachments**
- [01_refactor_news.diff](https://bugs.openttd.org/task/5722/getfile/9305/01_refactor_news.diff) (56.71 KiB)
- [02_doxyment_fixes.diff](https://bugs.openttd.org/task/5722/getfile/9306/02_doxyment_fixes.diff) (24.22 KiB)
- [03_crashlog_newsitems.diff](https://bugs.openttd.org/task/5722/getfile/9307/03_crashlog_newsitems.diff) (4.34 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Does 01 change anything, or does it only move functions?
> While a function name "GetReferenceTile" is fine when it is static to a file, it's not exactly suitable for a globally accessible thing.
> 
> Wrt. 03: 
> WriteNewsString definitely needs a "last" parameter to denote the end of the buffer.
> "(%i-%i-%i) %s\n" could be "(%i-%02i-%02i) %s\n"
> But I agree with Albert. The text message might be troublesome, since news serveral times caused crashes in the past, when they referenced invalid entities from the past. So, maybe print NewsItem members: type, references, stringid, stringparams

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5722#comment12658_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> frosch123: andythenorth: it's on the offical todo list 
> LordAro: andythenorth: i think it could probably be finished relatively easily

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5722#comment14630_

**Comment by TrueBrain** [comment]
@LordAro : sorry for the 5 year delay, but could you make a PR out of this? :D
