### ISSUE TITLE
Autoreplace - remove wagon is global not local

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5730]
**_Milsa_ opened the ticket and wrote:**

> I Set remove wagon on in replace group X and I set remove wagon off in replace group Y. Setting was changed global. It's not good. This must be change local for actual group.

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Milsa_ wrote:**

> And please remove cargo type wagon, not brake wagon. Savegame is in http://bugs.openttd.org/task/5734. if you set remove wagon then game will remove brake wagon and show error message and it will cancel the autoreplace of that vehicle.
> 
> I will create new task for brake van. This is it: http://bugs.openttd.org/task/5736

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5730#comment12584_

See #5736 for this (issue is closed).

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Confirmed.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5730#comment14679_

**Comment by andythenorth** [comment]
Resolved by #7441
