### ISSUE TITLE
Game Script: GSText in info.nut's GetSettings() method

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5753]
**_idioty_ opened the ticket and wrote:**

> Simple I want read the setting description texts form language text files. :)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
I assume you mean that you want Setting Descriptions to be translatable? Sounds fair :)

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
