### ISSUE TITLE
Autoreplace: better feedback for failed force-upgrade in depot 

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5776]
**_jvlomax_ opened the ticket and wrote:**

> A window will try to snap to a window that is not visible. 
> 
> To reproduce: Set a wagon or train to autoreplace with another. Send trains to depot and press "Autoreplace all trains in depot" without having enough money to do so. No error is thrown, nothing happens
> If I hold shift while pressing the button, it will give me an estimated cost
> 
> Expected behaviour: The game should tell me I don't have Enough Money
> 
> Actual behaviour: The action fails and the game does not tell me why
> 
> System info:
> Windows 7
> Openttd r25797 (downloaded precompiled binary)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> Enable the vehicle news
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5776#comment12654_

**Comment by DorpsGek** [comment]
**_jvlomax_ wrote:**

> I know it shows in the news section, it's also in the news log. But I still think a red error message window should pop up explaining why it doesn't work.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5776#comment12655_

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> Yeah nice, every time an autoreplace fails throw an error message at the user.
> Ever wondered what would happen if you do that when attempting (and failing) with 500+ trains running around?
> 
> I agree it could be more visible, but simply throwing an error message on failure is not the solution, I think.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5776#comment12656_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> The OP is suggesting this only triggers a message when the depot 'force upgrade' button is used.  It took me literally years to learn what that button does, as most of the time, pressing it causes nothing to happen.  A message specific to pressing that button does seem like a fair improvement to me. :)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5776#comment14533_

**Comment by andythenorth** [comment]
See also #6207 which is a different cause, but needs similar message.

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
