### ISSUE TITLE
When i connect server/company. can use default password?

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5799]
**_munhyunsu_ opened the ticket and wrote:**

> we connect server, company in multiplayer game.
> 
> if that's protected (password) password dialog is up.
> then we type password and press ok.
> 
> 
> in openttd.cfg. there's 'default_company_pass' and 'server_password'
> 
> it can use when we connect server/company. (use default password).

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_munhyunsu_ wrote:**

> I coding it

**Attachments**
- [mypatch.diff](https://bugs.openttd.org/task/5799/getfile/9444/mypatch.diff) (18.09 KiB)
- [Screenshot from 2013-11-06 18:19:30.png](https://bugs.openttd.org/task/5799/getfile/9445/Screenshot+from+2013-11-06+18%3A19%3A30.png) (686.81 KiB)
- [Screenshot from 2013-11-06 18:19:48.png](https://bugs.openttd.org/task/5799/getfile/9446/Screenshot+from+2013-11-06+18%3A19%3A48.png) (424.66 KiB)
- [FS#5799.diff](https://bugs.openttd.org/task/5799/getfile/9447/FS%235799.diff) (18.09 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5799#comment12719_

**Comment by DorpsGek** [comment]
**_planetmaker_ wrote:**

> The idea is good. The patch can be improved, though:
> 
> NetworkNeedCompanyPasswordWindow, NetworkNeedGamePasswordWindow and NetworkNeedMovePasswordWindow are nearly identical in everything. They could and probably should be unified into one by means of a parameter.
> The newly-introduced functions need to get doxygen comments as well. All of them :-)
> 
> Mind the coding style. You add or remove in a lot of places whitespace:
> \* Use tabs only for indentation
> \* Align stuff only with spaces
> \* Don't add trailing white spaces anywhere
> \* Don't add or remove lines or insert or remove spaces without reason. If there's reason, better do that in a separate patch.
> 
> See http://wiki.openttd.org/Coding_style Ignoring whitespace changes would cut the amount of changed lines into half size and remove a number of hunks.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5799#comment12720_

**Comment by DorpsGek** [comment]
**_munhyunsu_ wrote:**

> oh, sorry. i read your comment lately. 
> 
> Ok, i got it. i will modify & add doxygen comments. 
> and re-upload.
> 
> thank you for interest.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5799#comment12743_

**Comment by DorpsGek** [comment]
**_munhyunsu_ wrote:**

> @Ingo von Borstel (planetmaker)
> Hello, I have some question.
> 
> NetworkNeed[Game/Company/Move]PasswordWindow looks similar. but it's GUI text is different.
> ex) Query Window Label.
> NWidget(WWT_TEXT, COLOUR_GREY, WID_NNP_LABEL), SetDataTip(STR_NETWORK_NEED_GAME_PASSWORD, STR_NULL) -->> Server Password
> NWidget(WWT_TEXT, COLOUR_GREY, WID_NNP_LABEL), SetDataTip(STR_NETWORK_NEED_COMPANY_PASSWORD, STR_NULL) -->> Company Password
> 
> so, how can i unified into one?
> i think use 'Parameter' for functionally switch.
> and use 'Global variable' for GUI Text.
> but i hesitant to use global variable. 
> 
> i need some idea. :D

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5799#comment12751_

**Comment by DorpsGek** [comment]
**_munhyunsu_ wrote:**

> @Ingo von Borstel (planetmaker)
> Hello, I have some question.
> 
> NetworkNeed[Game/Company/Move]PasswordWindow looks similar. but it's GUI text is different.
> ex) Query Window Label.
> NWidget(WWT_TEXT, COLOUR_GREY, WID_NNP_LABEL), SetDataTip(STR_NETWORK_NEED_GAME_PASSWORD, STR_NULL) -->> Server Password
> NWidget(WWT_TEXT, COLOUR_GREY, WID_NNP_LABEL), SetDataTip(STR_NETWORK_NEED_COMPANY_PASSWORD, STR_NULL) -->> Company Password
> 
> so, how can i unified into one?
> i think use 'Parameter' for functionally switch.
> and use 'Global variable' for GUI Text.
> but i hesitant to use global variable. 
> 
> i need some idea. :D

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5799#comment12752_

**Comment by DorpsGek** [comment]
**_munhyunsu_ wrote:**

> I complete coding thanks to planetmaker :D
> 
> three widget is unified one.
> and also unified password set window.
> 
> result this.
> 

**Attachments**
- [01-server_password_query.jpeg](https://bugs.openttd.org/task/5799/getfile/9472/01-server_password_query.jpeg) (205.10 KiB)
- [02-company_password_query.jpeg](https://bugs.openttd.org/task/5799/getfile/9473/02-company_password_query.jpeg) (208.64 KiB)
- [03-join_move_company_password_query.jpeg](https://bugs.openttd.org/task/5799/getfile/9474/03-join_move_company_password_query.jpeg) (183.97 KiB)
- [04-new_company_password_query.jpeg](https://bugs.openttd.org/task/5799/getfile/9475/04-new_company_password_query.jpeg) (181.04 KiB)
- [FS#5799.diff](https://bugs.openttd.org/task/5799/getfile/9476/FS%235799.diff) (20.89 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5799#comment12795_

**Comment by DorpsGek** [comment]
**_munhyunsu_ wrote:**

> I modify GUI
> 

**Attachments**
- [05-modify_GUI.jpeg](https://bugs.openttd.org/task/5799/getfile/9478/05-modify_GUI.jpeg) (207.51 KiB)
- [FS#5799.diff](https://bugs.openttd.org/task/5799/getfile/9479/FS%235799.diff) (20.91 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5799#comment12799_

**Comment by TrueBrain** [comment]
I am not a fan of storing passwords in plain text, and I would hate if we continue adding to that. I rather first see we overhaul how we store passwords, before we add more usages.

So sorry, for now, lets now implement this.
