### ISSUE TITLE
Mass-deleting of map signs

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5837]
**_airbus_sai_ opened the ticket and wrote:**

> Hello!
> 
> It would be nice to have cleaning tool for signs. Preferably mass-cleaning. I ended up with <attached> after two years with broken AI, and now this part of map has very poor performance. The only way to clean them by now is to click on every one and delete them one by one.
> 
> Thanks!

**Attachments**
- [Togglebridge Transport, 1948-10-27.png](https://bugs.openttd.org/task/5837/getfile/9539/Togglebridge+Transport%2C+1948-10-27.png) (102.74 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> Write an AI to remove them?
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5837#comment12862_

**Comment by DorpsGek** [comment]
**_airbus_sai_ wrote:**

> How should I do it?
> 
> I haven't wrote an AI before, but I have some programming knowledge, so could you just give some directions?
> I'll look into wiki for basics.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5837#comment12874_

**Comment by DorpsGek** [comment]
**_krinn_ wrote:**

> Actually you cannot write any AI or GS that will do that for you.
> 
> an AI can remove its active signs, and a GS can remove active signs for itself, or active signs from any other AI.
> 
> But "dead" signs (dunno how you call them) signs : ones left by players or ai that has been restart are not own by anyone and cannot be refind by both API.
> As you cannot find them, you cannot handle them : no handling == no deletion.
> 
> I'm afraid the only way to solve your issue is avoiding it : look for the problematic AI, and disable debug sign or sign outputing... (you generally have an option to disable them).
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5837#comment12898_

**Comment by DorpsGek** [comment]
**_LordAro_ wrote:**

> There should be a way of removing mass amounts of signs, be it with a tile selection from some interface, or just culling "dead" signs from the map (especially since GS cannot interact with them anyway)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5837#comment14550_

**Comment by andythenorth** [comment]
Don't use AI that builds a lot of signs.  Closing, thanks :)
