### ISSUE TITLE
Town name starvation leads to slow industry generation (landscape creation)

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5864]
**_MJP_ opened the ticket and wrote:**

> If the selected "town_name" has not enough names, the time spent to generate industry increases a lot.
> 
> On a 2048*2048 map, _GenerateWorld() takes much longer with "french" or "swiss" than "english" or "danish" (more than 150 sec vs less than 10).
> 
> This patch implements the use of an alternative town name generator when the first can't supply anymore.

**Attachments**
- [town_name_fallback.patch](https://bugs.openttd.org/task/5864/getfile/9585/town_name_fallback.patch) (3.68 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_MJP_ wrote:**

> I realized lately it breaks savegame compatibility :(
> So I replaced "guiflags = SGF_NO_NETWORK" by "flags = SLF_NOT_IN_SAVE | SLF_NO_NETWORK_SYNC".
> 
> Now, a patched binary can load old savegames.
> In the other way, I created a new game with the patch so there is mixed town names.
> Then I checked this savegame is loadable by a version of OpenTTD without the patch.

**Attachments**
- [town_name_fallback_r2.patch](https://bugs.openttd.org/task/5864/getfile/9586/town_name_fallback_r2.patch) (3.69 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5864#comment12920_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Haven't tested the patch, but in principle this would fix https://bugs.openttd.org/task/5840

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5864#comment14530_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Patch fails to apply on r27910
> 
> openttd-trunk(master)$ git reset --hard
> HEAD is now at f1e54b437 (svn r27910) -Update from Eints:
> openttd-trunk(master)$ curl https://bugs.openttd.org/task/5864/getfile/9586/town_name_fallback_r2.patch | patch -p1
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  3777  100  3777    0     0  16695      0 --:--:-- --:--:-- --:--:-- 16712
> patching file src/settings_type.h
> Hunk # 1 succeeded at 285 (offset 1 line).
> patching file src/table/settings.ini
> Hunk # 1 succeeded at 342 (offset 6 lines).
> patching file src/town_cmd.cpp
> Hunk # 1 FAILED at 1881.
> Hunk # 2 succeeded at 1975 with fuzz 2 (offset 75 lines).
> 1 out of 2 hunks FAILED -- saving rejects to file src/town_cmd.cpp.rej

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5864#comment14727_

**Comment by TrueBrain** [comment]
I don't like this solution, as it works around the real issue. It also adds complexity. I also wonder if this really is a problem.

For now I do not consider this a problem. If you disagree, please rebuttal!
