### ISSUE TITLE
Replace _screen_disable_anim

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5873]
**_MJP_ opened the ticket and wrote:**

> I hesitated to post that since it is a change of almost no importance (say the one who posted #5871 and #5872...).
> But I find 32bpp_anim.cpp easier to read this way.
> 
> Pros:
> \- simplified animated blitter code
> \- 1 global variable less
> 
> Cons:
> \- giant screenshot may take a bit more time
> \- giant screenshot may use more memory (size of anim_buf)

**Attachments**
- [1-add-backup-restore-animbuf.patch](https://bugs.openttd.org/task/5873/getfile/9606/1-add-backup-restore-animbuf.patch) (2.82 KiB)
- [2-replace-screendisableanim-global.patch](https://bugs.openttd.org/task/5873/getfile/9607/2-replace-screendisableanim-global.patch) (5.58 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
Although I am not against a patch like this, the cons make me a bit reluctant. Going to close this for now; please create a Pull Request if you feel this still adds to the readability!
