### ISSUE TITLE
Bananas: online content doesn't stop downloading when canceled

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5875]
**_Samu_ opened the ticket and wrote:**

> OpenTTD 1.4.0-beta3
> Windows 7 64-bit SP1
> 
> 
> I clicked Check Online Content from the main menu, waited a bit for the data to fill in, then click Select upgrades. It picked zBase (version r251), sized 273 MiB. I click Download, but since I'm on a slow internet, I decided to cancel before it finished.
> 
> While the game shows no indication of a download in progress, I noticed there was still a download activity on my connection. I went to check out what was happening and there was a connection maintaned to gd.binaries.openttd.org by openttd.exe.
> 
> Only by exiting and restarting OpenTTD, did this download stop.

**Reported version**: _other_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Reproduced on r27910 (on OS X).  Following steps Samu describes:
> \- zBase continues to be download after cancelling in game
> \- the tar is unpacked from the .gz on conclusion of the download
> 
> As expected, OpenTTD then won't see the unpacked tar until the game is restarted.  Until restarted, zBase remains available for download, even though a local copy is now present (conventional behaviour, base sets are only rescanned on launch afaik).

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5875#comment14744_

**Comment by andythenorth** [comment]
Thanks for this.  At the time of writing this appears to be an isolated bug, and not frequently reported.  We do try to address bugs where they occur frequently and/or are easy to reproduce, but this one doesn't look like we can any go further, so I'm closing it.  Thanks for contributing!
