### ISSUE TITLE
Allow separate compilation (objdir != srcdir)

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5881]
**_dylex_ opened the ticket and wrote:**

> The configure/build system as it stands mostly allows separate compliation, when you run configure from a different directory, but fails in subtle ways.  In particular, cpu-type detection and bundling fail.  This small patch fixes the various issues.  It also removes some related excess quoting that ended up un-quoting paths instead of quoting them (""/path/"").
> 
> Obviously it is up to you whether you actually want to support this, but if you don't, it would be nice if it did a check during configure and complained if $PWD != $ROOT_DIR.

**Attachments**
- [0001-Allow-separate-compilation.patch](https://bugs.openttd.org/task/5881/getfile/9618/0001-Allow-separate-compilation.patch) (4.64 KiB)

**Reported version**: _trunk_
**Operating system**: _UNIX_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Hmm, it's not that easy with these four:
> \+	$(Q)cp "$(ROOT_DIR)/bin/baseset/"*.grf    "$(BASESET_DIR)/"
> \+	$(Q)cp "$(ROOT_DIR)/bin/baseset/"*.obg    "$(BASESET_DIR)/"
> \+	$(Q)cp "$(ROOT_DIR)/bin/baseset/"*.obs    "$(BASESET_DIR)/"
> \+	$(Q)cp "$(ROOT_DIR)/bin/baseset/"*.obm    "$(BASESET_DIR)/"
> 
> Depending on whether GRFcodec is installed or not, they are build from (real) sources or taken as it from the repository.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5881#comment12971_

**Comment by DorpsGek** [comment]
**_dylex_ wrote:**

> The readme claims that using grfcodec will "leave the repository in a modified state" and "modify the base file set."  One solution then would be to update Makefile.grf.in to make this actually true, and put the files in $ROOT_DIR/bin rather than $BIN_DIR.  Alternatively, bundle could copy from $ROOT_DIR and then copy any addition files from $BIN_DIR if they exist, overwriting the originals.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5881#comment12978_

**Comment by TrueBrain** [comment]
I do not think it is useful to try to fix the current configuration system with small things like that. It can have unexpected consequences which are hard to oversee.

I think we can better put the effort in switch to CMake, which solves most of this stuff already.

Tnx anyway (5 years late) for the contribution :)
