### ISSUE TITLE
Objects: loop through random variants deterministically on construction

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5887]
**_Simons_Mith_ opened the ticket and wrote:**

> When you have multiple items from e.g. the NewObject menu, which one you get is determined randomly. I'm thinking of ISR/DWE particularly here. Could Ctrl-click be added to step through the variations in order? Particularly useful for the many ISR tiles, which have probably only been compressed into one tile for space reasons. A way to get a logical sequence would be particularly handy for these, especially as some of the graphical variants are really visually confusing if you get the wrong tile when you're trying to build something complex. Similarly for the modular depot tiles NewGRFs.
> 
> The same feature could also usefully be expanded to the station UI and even depots. Perhaps even allow the ability to do step through the variants for the current tile, then all the variants for the next and so on, in an endless loop, so you can view them all, and /access them consistently and reliably/ which is the main thing I'm after.

**Reported version**: _1.4.0-beta3_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> I've retitled this to reflect what I think is sought here.
> 
> Sometimes I find current behaviour of random tiles is irritating for stations (I don't use objects, but would probably be same).  Not sure anyone will be convinced to change it though ;)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5887#comment14702_

**Comment by andythenorth** [comment]
I think making this deterministic is TMWFTLB.  

* If predictable building is wanted, then authors shouldn't provide random variants.  
* Random variants should be random.
* Adding a deterministic order for variants inside a tile is really tiles-in-tiles; i.e. it's nested.  That's not wise.  We already have one layer of nesting via groups of tiles.  Let's not turtles all the way down.
