### ISSUE TITLE
Crash: [OSX] opening company window

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5949]
**_vinnie_nl_ opened the ticket and wrote:**

> 1.4.0-RC1 OSX 10.7.5,
> 
> Game slowed down drastically when i tried to zoom in to improve frame rate, Tried to open company window to teleport main view to a remote HQ when crash to desktop occurred. 
> 
> Probably my PC is to slow but the assertion line failed in screenshot is unknown to me.
> 
> Love this game, thanks for your dedication.

**Attachments**
- [crash.log](https://bugs.openttd.org/task/5949/getfile/9735/crash.log) (4.20 KiB)
- [crash.png](https://bugs.openttd.org/task/5949/getfile/9736/crash.png) (69.47 KiB)
- [crash.sav](https://bugs.openttd.org/task/5949/getfile/9737/crash.sav) (1196.13 KiB)
- [Schermafbeelding 2014-03-20 om 17.29.43.png](https://bugs.openttd.org/task/5949/getfile/9738/Schermafbeelding+2014-03-20+om+17.29.43.png) (697.66 KiB)

**Reported version**: _other_
**Operating system**: _Mac OS X_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Can't repro on 1.7.1 (mac OS 10.12.5).  However I am testing in SP.  Looks like it was an MP game?
> 
> "Assertion failed at line 843 of /bamboo/src/company_cmd.cpp: _local_company == COMPANY_SPECTATOR"

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5949#comment14518_

**Comment by andythenorth** [comment]
Can't repro.  De-facto Mac OS version support is n-2, and this is 10.7 when n is 10.13.  So closing, thanks.
