### ISSUE TITLE
[OSX] Trackpad pinch gesture support broken (r25666)

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5958]
**_xmirakulix_ opened the ticket and wrote:**

> There is a commit to trunk, that includes support for the pinching gesture on Trackpads in e.g. a Macbook:
> (svn r25666) -Feature [#4760]: [OSX] Pinch gesture support for zooming. (Based on patch by leecbaker)
> 
> Unfortunately, the functionality, as it is implemented has a flaw that renders it unusable for me:
> Trackpads act as a two-way mouse wheel too, so the best setting for the mouse wheel when playing is to "scroll map", not "zoom map".
> The implementation as far as I understand it though just "turns" the mouse wheel when pinching, not actually zoom.
> Thus the map doesn't get zoomed then.
> 
> The commit is said to be based on FS task # 4760 "pinch to zoom support" (http://bugs.openttd.org/task/4760).
> That patch in contrast to the implementation in trunk seems to define two new hotkeys that are then used to actually zoom the map, regardless of the mouse wheel setting.
> 
> This seems to be a better way to implement that feature, as the "mousewheel" (two parallel fingers) and the "pinch" gesture are two different things on the trackpad and should not be mixed.
> 
> My Setup: Macbook Air, OS X 10.9.2

**Reported version**: _trunk_
**Operating system**: _Mac OS X_

---

**Comment by andythenorth** [comment]
See also #6558 for related broken with OS X mouse zoom.

We'll pass on fixing this one, thanks.
