### ISSUE TITLE
Cargodist: Too many passengers on stations

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5975]
**_Milsa_ opened the ticket and wrote:**

> Please remake generating count of passengers and mail on stations.
> 
> Example:
> 1. I have station with 7 pieces and 2 lines but 4500 passengers. Set max. limit of passengers on one piece of station (like Simutrans).
> 2. Please add passengers inteligence. They going from A to B around all map (C, D, E)
> 3. Do not enlarge cities if passengers stays on station (few trains)
> 4. Let the CD generating more passengers if station have more lines to other cities.
> 

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_fonsinchen_ wrote:**

> About 2: Can you please upload a savegame showing the problem? That is not a feature request but a bug. Shorter routes should be preferred to longer ones, as long as there is free capacity.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5975#comment13226_

**Comment by DorpsGek** [comment]
**_Milsa_ wrote:**

> Please look at the image. Kremnica is in left bottom corner. Poprad is in the left middle. Nova Bana is in right middle.
> 
> The shortest way is via Rimavska Sobota, Gelnica, Zlate Moravce. No via Poprad.
> 
> This problem is not overcrowded the shortest line (station in Rimavska Sobota (on the shortest line) is nearly empty.
> 

**Attachments**
- [M-Trans, 1967-08-13.sav](https://bugs.openttd.org/task/5975/getfile/9788/M-Trans%2C+1967-08-13.sav) (1867.30 KiB)
- [M-Trans, 1967-08-13#2.png](https://bugs.openttd.org/task/5975/getfile/9789/M-Trans%2C+1967-08-13%232.png) (166.59 KiB)
- [openttd.cfg](https://bugs.openttd.org/task/5975/getfile/9790/openttd.cfg) (11.78 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5975#comment13227_

**Comment by DorpsGek** [comment]
**_fonsinchen_ wrote:**

> The link between Rimavska Sobota and Gelnica seems to be new. The link graph is recalculated on August 28th. At that point the new link becomes active. You can reduce the delay between adding new links and passengers being routed along them by reducing the link graph calculation time and interval in the settings. If you have very complicated link graphs that may lead to noticable lag, though.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5975#comment13233_

**Comment by DorpsGek** [comment]
**_smurfix_ wrote:**

> Also, 5. (see #6103): a small town with 100 inhabitants, without external connections, cannot have 3000+ passengers waiting at one single bus stop.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5975#comment13499_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Flyspray clean up: possibly should close this as it's two issues in one:
> 
> 1. cdist performance question - answer provided by fonsinchen
> 2. recurring issue of how pax are generated in cdist networks, where the ability to actually deliver pax to destinations plummets as new links are connected to an existing network.
> 
> Leaving it open because (2) is valid, although it would be better to consolidate these recurring pax generation issues to one place.  It's low priority, because multiple solutions have been proposed and none have been viable, therefore it's a possible tar pit, with high chance of sucking in time and making things worse not better. :)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5975#comment14558_

**Comment by andythenorth** [comment]
This ticket has achieved all it can achieve.  Closing for clean up.
