### ISSUE TITLE
Autoreplace window isn't updated after group hierarchy changes

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5978]
**_juanjo_ opened the ticket and wrote:**

> The autoreplace window lists are not updated after making a group hierarchy change.
> 
> Group 1: Has no maglevs.
> Group 2: Has maglevs.
> 
> Open autoreplace window for G1. It doesn't list maglevs.
> Add G2 as a subgroup of G1. Autoreplace window for G1 should list maglevs, but it doesn't.
> 
> Showing diesel engines and then going back to maglev ones makes window up-to-date.
> 
> Maybe group hierarchy code should call InvalidateAutoreplaceWindow somewhere.

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_juanjo_ wrote:**

> Title should be "Autoreplace window isn't *updated* after group hierarchy changes."

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5978#comment13228_

**Comment by DorpsGek** [comment]
**_alex6_ wrote:**

> I was not able to reproduce the problem following the steps.
> Do you have a savegame ?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5978#comment13577_

**Comment by DorpsGek** [comment]
**_juanjo_ wrote:**

> Here is a savegame (r27037) and some images.
> It happens if you open a replacement window for vehicles of GROUP 1.

**Attachments**
- [FS5978.sav](https://bugs.openttd.org/task/5978/getfile/9998/FS5978.sav) (15.22 KiB)
- [FS5978-1.png](https://bugs.openttd.org/task/5978/getfile/9999/FS5978-1.png) (119.49 KiB)
- [FS5978-2.png](https://bugs.openttd.org/task/5978/getfile/10000/FS5978-2.png) (138.15 KiB)
- [FS5978-2-OK.png](https://bugs.openttd.org/task/5978/getfile/10001/FS5978-2-OK.png) (164.34 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5978#comment13578_

**Comment by DorpsGek** [comment]
**_3298_ wrote:**

> It was indeed a simple fix, a call to GroupStatistics::UpdateAutoreplace was missing. While I was testing I also found two other equally small issues between autoreplace and groups: the group window doesn't refresh when starting or stopping a replacement (i.e. the autoreplace icon didn't (dis-)appear when it should, but after another redraw trigger like selecting a group it did), and in addition the color of the autoreplace icon in the group window doesn't accurately reflect the status of autoreplace when the only remaining vehicles to replace are in subgroups (it is drawn like when the autoreplace has finished, even though that is not yet true).
> The attached patch fixes all three issues. The first two hunks refresh the group window when starting/stopping autoreplace; the third hunk fixes the issue with incorrect display of autoreplace's "finished" status; and the fourth hunk is the fix for the original issue, refreshing the autoreplace window on group hierarchy changes.
> I aggregated them into a single patch because they are closely related, tiny, and easy to separate if needed.

**Attachments**
- [fs5978.diff](https://bugs.openttd.org/task/5978/getfile/10826/fs5978.diff) (1.58 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5978#comment14645_

**Comment by andythenorth** [comment]
@J0anJosep is this one yours? :)

**Comment by J0anJosep** [comment]
I didn't wrote the patch, just created the ticket on FS. I'll check it. In case 3298 doesn't create a PR soon, I'll do it and credit him if I find the patch to be correct.

**Comment by andythenorth** [comment]
Thanks for doing that @J0anJosep  

3298 can't use GitHub for ethical reasons, so won't be creating any PRs.   See https://www.tt-forums.net/viewtopic.php?f=33&t=83025
