### ISSUE TITLE
Vehicles: var for "Tiles traveled since last station/depot visit"

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5982]
**_Snail__ opened the ticket and wrote:**

> I'm proposing a new feature for trains (but it could also be extended to road vehicles): a variable that counts the tiles that have been traveled since the last stop at a station or at a depot.
> 
> This could be quite useful to differentiate trains, especially steamers; indeed, one of my ideas for my set is tpo add the "range" to each locomotive's specs. A small tank steamer would be able to carry a very limited amount of coal and water, requiring frequent refill stops and making it more difficult to travel for long stints. A larger tender steamer would have a larger range, and an electric would have an unlimited range.
> The way I'd envision this to work is, whenever this "tiles traveled" variable is greater than X, I'd cripple its max speed, because the engine is about to run out of fuel and needs to save the little that's left. Of course, X would be different for each locomotive.
> 
> Mind you, this variable should count the tiles traveled since the last station or depot visit, not since the last stop (which could have been at a signal).
> 
> In the early years, this would give an advantage to tender steamers, allowing me to lower the price of small tank steamers. Could this be implemented?
> 
> Thanks in advance.

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> I gave this a bit of thought (it's come up a few times over the years).  Seems like a variation of aircraft range, and I think it would lead to similar reporting of problems, e.g. #6312.  
> 
> Failure demand is boring.  We can avoid the most obvious failure demand whilst still providing a fun game.  So I would avoid this feature.  :)
> 
> It was probably Pikka who said about newgrf "just because we can doesn't mean we should".  Wise words imho.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5982#comment14755_

**Comment by TrueBrain** [comment]
I like the idea; But too big to keep around in an issue tracker, so sorry, but going to close it. Of course feel free to come with a (proper) patch that implements this :)
