### ISSUE TITLE
Store company passwords for network servers

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#599]
**_Smoovious_ opened the ticket and wrote:**

> When saving a network game, and reloading it later, none of the company passwords are saved|reloaded...
> 

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Brokkoli_ wrote:**

> when this is implemented there should also be an option for the server admin, to remove the password of any company.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/599#comment2042_

**Comment by DorpsGek** [comment]
**_sforget_ wrote:**

> I have actually written a patch that saves Multiplayer company passwords. It works quite well and is so far bug free.
> 
> 

**Attachments**
- [SavePasswords.diff](https://bugs.openttd.org/task/599/getfile/1999/SavePasswords.diff) (2.59 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/599#comment2814_

**Comment by DorpsGek** [comment]
**_zothar_ wrote:**

> Related forum topic: http://www.tt-forums.net/viewtopic.php?f=33&t=34997

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/599#comment3006_

**Comment by DorpsGek** [comment]
**_zothar_ wrote:**

> I've updated the patch for the 0.6.2 r13972 release, making the password file save to the same path as the saved game file.

**Attachments**
- [SavePasswords-zothar-r13972.diff](https://bugs.openttd.org/task/599/getfile/3141/SavePasswords-zothar-r13972.diff) (5.14 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/599#comment4523_

**Comment by DorpsGek** [comment]
**_Hazzard_ wrote:**

> It's probably best to hash & salt the passwords for storage, I'm sure some people use their "good" passwords in openttd, thinking they are stored (somewhat) securely. I think this is a feature worth having.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/599#comment13656_

**Comment by DorpsGek** [comment]
**_planetmaker_ wrote:**

> Yeah, probably. Obviously it's wanted. My suggestion (just my personal one), but an acceptable patch (series) would need to provide all of it:
> 
> \- store it as a company property
> \- store the salted + hashed password only
> \- transmit the salted + hashed password only, thus make that operation client-side
> \- only restore the password sin the savegame, when run as server
> \- add an rcon command to clear passwords
> \- add an admin port command to clear passwords
> 
> EDIT: this likely will need to make use of an additional cryptography library. This should be guarded in the code with # ifdef and in config.lib treated similar as the configure options like freetype, icu etc.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/599#comment13657_

**Comment by TrueBrain** [comment]
~~In these modern days it is a big no-no to transmit in plain text passwords. So indeed, it needs client-side hashing of some sorts, which the server needs to store. This also means the server needs to send a salt or something ..~~ I was misinformed, passwords are never sent clear-text.

**Comment by TrueBrain** [comment]
I like the idea, I think it can be very valuable, but it is a low priority. Closing issue.
