### ISSUE TITLE
Console: when using console set <variable> <value>, reply with new value upon success

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5996]
**_Taede_ opened the ticket and wrote:**

> Currently there is no confirmation of a setting's new value upon changing it, there is merely a lack of response. It would make sense to display that the setting has a new value. This would be especially helpful for adminport clients.
> 
> Current situation:
> > set yapf.rail_firstred_twoway_eol
> Current value for 'yapf.rail_firstred_twoway_eol' is: 'off' (min: 0, max: 1)
> > set yapf.rail_firstred_twoway_eol 1
> > set yapf.rail_firstred_twoway_eol
> Current value for 'yapf.rail_firstred_twoway_eol' is: 'on' (min: 0, max: 1)
> > _
> 
> 
> 
> Example desired output:
> > set yapf.rail_firstred_twoway_eol
> Current value for 'yapf.rail_firstred_twoway_eol' is: 'off' (min: 0, max: 1)
> > set yapf.rail_firstred_twoway_eol 1
> New value for 'yapf.rail_firstred_twoway_eol' is now: 'on'
> > set yapf.rail_firstred_twoway_eol
> Current value for 'yapf.rail_firstred_twoway_eol' is: 'on' (min: 0, max: 1)
> > _
> 

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
andythenorth: ^ I kind of agree with that, but eh, unix shell doesn't provide confirmation of changes
[09:32am] andythenorth: 'worse is better'
[09:33am] andythenorth: 'reload_newgrfs' -> "15 newgrfs have been reloaded"
[09:33am] andythenorth: seems redundant really
[09:38am] peter1138: Should reply with failure if not successful
[09:39am] peter1138: set without a parameter should be invalid
[09:39am] peter1138: should be get parameter for that
[09:39am] peter1138: mind you it's not an api is it
[09:40am] andythenorth: keep or close?

**Comment by TrueBrain** [comment]
The main reason why I wonder about this, is that you set '1', which means 'on'. Having that feedback can be very valuable. I am tempted to say it is better to give feedback, but it needs more thought.

In general, these days there are better UX designs for consoles. So possibly this should just be part of a bigger overhaul.

**Comment by TrueBrain** [comment]
Despite the coin toss, going to pass on this ticket. A lot of effort for something that is essential already broken. Not worth the effort at this moment in my opinion.

Please feel free to rebuttal!
