### ISSUE TITLE
Towns: allow town info window to display different cargo names

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5998]
**_Andrew350_ opened the ticket and wrote:**

> NewGRFs are allowed to change the names of the default cargoes "PASS" and "MAIL", however the town information window currently won't reflect this change, and always just shows "passengers" and "mail". If possible, it would be nice if this window could be updated to not just use the hard-coded cargo names, but also reflect any changes made by NewGRFs.

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Would need a discussion about the mechanic.  Is it driven by cargo labels?  Or some misc flags?  (I have no idea) :) . Discuss in irc if you want to move it on, cheers ;)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5998#comment14676_

**Comment by TrueBrain** [comment]
Guess that answers your question (6 months later). I don't see this currently happening, so passing. Tnx though!

**Comment by andythenorth** [comment]
https://www.tt-forums.net/viewtopic.php?p=1207680#p1207680

**Comment by nielsmh** [comment]
Resolved by #6801
