### ISSUE TITLE
Signals: train gets stuck while entering a depot and path re-reservation occurs

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6039]
**_adf88_ opened the ticket and wrote:**

> 1. Send a train to a depot
> 2. While the train is entering the depot, initiate path re-reservation e.g. put a PBS on a near track
> 3. The train gets sucked
> 
> The problem seems to be inside TryPathReserve function, especially the fragment starting at this line:
> 
> https://vcs.openttd.org/svn/browser/trunk/src/train_cmd.cpp?rev=26635# L2683
> 
> Reservation fails because the depot is already reserved for a train. But it's the same train :) Looks like someone made wrong assumption that "v->track == TRACK_BIT_DEPOT" means that whole train is inside and wants to exit.

**Attachments**
- [a.png](https://bugs.openttd.org/task/6039/getfile/9854/a.png) (60.62 KiB)
- [b.png](https://bugs.openttd.org/task/6039/getfile/9855/b.png) (63.89 KiB)

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_adf88_ wrote:**

> I'm not sure about origins of the bug but maybe the depot reservation status should have been already cleared while inside TryPathReserve? Just a thought...

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6039#comment13374_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> I confirmed this in #6046

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6039#comment14667_

**Comment by andythenorth** [comment]
Let's live dangerously sometimes. I can't see this getting fixed. Thanks for contributing!
