### ISSUE TITLE
Signals: train gets stuck when placing multiple signals over it

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6046]
**_adf88_ opened the ticket and wrote:**

> 1. Run a train on a track
> 2. By performing a single mouse drag-drop, build many one-way signals in a way that:
> \- signals are faced against the train
> \- at least two signals are placed over the train
> 3. The train gets stuck
> 
> Kind of signals doesn't matter, the only requirement is that they are non-passable by the train from the side it is coming.
> 
> Could be related to #6039.

**Attachments**
- [a.png](https://bugs.openttd.org/task/6046/getfile/9865/a.png) (51.66 KiB)
- [b.png](https://bugs.openttd.org/task/6046/getfile/9866/b.png) (56.72 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_krinn_ wrote:**

> did you check?
> grep reverse_at openttd.cfg
> reverse_at_signals = false
> 
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6046#comment13385_

**Comment by DorpsGek** [comment]
**_adf88_ wrote:**

> 'reverse_at_signals' doesn't have any impact on the problem. When 'reverse_at_signals' is on then yes, trains will reverse after some time. But the problem is that they shouldn't stop in the first place.
> 
> This problem is really annoying and destructive sometimes. It happens quite frequently when you are placing signals on occupied tracks. Short stretches are not a problem, but with longer stretches (ctrl+drag) it is easy to miss that some train stopped. You are finding this out when it's too late (a traffic jam).
> 
> Changing 'reverse_at_signals' is not always an option (multiplayer). Besides, current behaviour is not "elegant" ('reverse_at_signals' is just a workaround).
> 
> Also 'reverse_at_signals' has other side effects that you may not want to have (reversing it's optional for a reason).

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6046#comment13471_

**Comment by DorpsGek** [comment]
**_adf88_ wrote:**

> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6046#comment13472_

**Comment by DorpsGek** [comment]
**_Marctraider_ wrote:**

> just curious, is this the bug where a train simply doesnt move at all for no apparent reason? If so I probably encountered the same isssue.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6046#comment13479_

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> Unless you fiddled with signals at a 'live' track, no.
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6046#comment13480_

**Comment by andythenorth** [comment]
I can repro this by dragging one-way signals on density 1 or 2 against the direction of the train.  It stops, and doesn't appear to reverse when I run the game on FFWD.

**Comment by TrueBrain** [comment]
Behavior is bit wonky indeed. When train is already on track, and you put it far in front of him, he just reverses. Otherwise it stops dead in its track. This needs a closer look :)

**Comment by andythenorth** [comment]
Let's live dangerously sometimes.  I can't see this getting fixed. Thanks for contributing!
