### ISSUE TITLE
No music playback with timidity++ and OpenTTD 1.4.1

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6051]
**_Ascanius_ opened the ticket and wrote:**

> On a Debian 7 system, timidity++ does not play OpenMSX, Modern Motion or other in-game music with the latest OpenTTD 1.4.1 .deb package from the official site. The version in Debian's stable repository (1.2.1) works fine with the same music sets.
> 
> The issue is the same with OpenTTD 1.4.1 on an Arch Linux system, with Arch's openttd and timidity++ packages, and OpenMSX (both via content download and via the AUR).

**Reported version**: _1.4.1_
**Operating system**: _Linux_

---

**Comment by DorpsGek** [comment]
**_ZirconiumX_ wrote:**

> Have you installed (on Arch) timidity-freepats?
> 
> Matthew:out

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6051#comment13406_

**Comment by DorpsGek** [comment]
**_Ascanius_ wrote:**

> timidity-freepats is installed, and playing openMSX music files via timidity++ works. Same on Ubuntu.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6051#comment13407_

**Comment by DorpsGek** [comment]
**_ZirconiumX_ wrote:**

> I remember the workaround now.
> 
> Install portmidi. Run timidity as a daemon. Create a shell script that contains the one liner "pmidi -p128:0 $1" (without quotes). Start openttd like this: "openttd -m extmidi:<path>" replacing <path> with the path to your shell script one liner.
> 
> Matthew:out

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6051#comment13408_

**Comment by DorpsGek** [comment]
**_ZirconiumX_ wrote:**

> I made a typo.
> 
> "openttd -m extmidi:cmd=<path>"
> 
> Matthew:out

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6051#comment13409_

**Comment by TrueBrain** [comment]
Midi on linux is always ugly. 4 years later. I see no point keeping this issue around.

Please feel free to open a new ticket if this is still a thing.
