### ISSUE TITLE
Towns: preview border town

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6052]
**_polaque_ opened the ticket and wrote:**

> Add to menu with Map option which marks border towns because the high concentration of towns sometime make station in other city than we want

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Milsa_ wrote:**

> Related but not the same: http://bugs.openttd.org/task/5710

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6052#comment13482_

**Comment by andythenorth** [comment]
Nice idea, but unlikely to be implemented (nobody to push it through).  I think JGR patchpack has something similar to this though.  Closing as we need to prioritise issues, thanks :)
