### ISSUE TITLE
Allow use cursor keys to move in lists

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6074]
**_Milsa_ opened the ticket and wrote:**

> Please allow use cursor arrows to move between items of list in windows (list of vehicles, airplanes, groups, etc.)

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> You mean like in the signs list window?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6074#comment13427_

**Comment by DorpsGek** [comment]
**_Milsa_ wrote:**

> I mean all windows with list but primarily this:
> \- vehicle groups list (moving between groups), this is ideal for check profit (ADDED: moving groups with cursor and scrolling vehicles with mouse (scrolling working already now))
> \- new/replace engine/wagon list (faster is pushing cursor down than click with mouse and scroll), this is ideal for comparing engine parameters 
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6074#comment13428_

**Comment by DorpsGek** [comment]
**_alex6_ wrote:**

> I also tried to quickly compare different vehicles or trains with the up and down arrow keys.
> It's just a habit to use the arrow keys because it's available in many applications.
> 
> I made a patch to manage trains/vehicles/ships/aircrafts lists.
> As well as the build of these engines.
> 
> The window must have the focus to work well.
> The scrolling of the main map area works if the focused window is NOT trains/vehicles/... list or build list.
> 
> The news/tooltips windows are not considered for this focus.

**Attachments**
- [patch_FS#6074_alex6.diff](https://bugs.openttd.org/task/6074/getfile/9988/patch_FS%236074_alex6.diff) (3.43 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6074#comment13568_

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> I like the idea but I don't like the implementation. I think this should be handled at the matrix or scrollbar level, some how.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6074#comment13609_

**Comment by andythenorth** [comment]
How does one know the window has focus?  There is no concept of UI feedback about currently focussed window. 

Hasn't moved since 2014.  We can pass on this.  Closing, thanks.
