### ISSUE TITLE
Timetable: removing all times from timetable and change all "stay" time

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6075]
**_Milsa_ opened the ticket and wrote:**

> Please add this functionality:
> \- Ctrl+Click on Clear time removes all times from timetable.
> \- Ctrl+Click on Change time sets all "stay" time for stations
> 

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
When implementing, please think if the suggestion solution is the correct one. It describes a solution, not a problem. But sounds sane to implement.

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
