### ISSUE TITLE
Audio: change music list in game

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6090]
**_Milsa_ opened the ticket and wrote:**

> Please allow change music during game playing (OpenMSX to other).

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> From irc:
> 
> LordAro: #6090 is about changing the selected music set
> LordAro: (when in game)
> LordAro: #3997 is playing all of them

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6090#comment14642_

**Comment by TrueBrain** [comment]
Cool idea! A Pull Request would be even better :) Low priority, so sorry, closing issue.
