### ISSUE TITLE
File failed to decompress - Error window not on top

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6095]
**_Transportman_ opened the ticket and wrote:**

> I downloaded Qu@rks savegame from http://www.tt-forums.net/viewtopic.php?f=29&t=71077&view=unread# p1129307 and needed to download some additional content, but for some reason it failed to decompress one of the following files:
> Total Town Replacement Set 3.02a
> German Town Names 0.2.0
> CS Rail Set v1.4-1.05
> 
> This blocked the complete download of all three files, with a failed to decompress error. But the error window was not shown on top, but was hidden behind other windows.
> 
> Also, the error window was opened twice instead of only once.
> 
> Downloading again did not trigger the error and the file was decompressed successfully.
> 
> Using Win 8.1 64 bits with OpenTTD r26752 64 bits.

**Reported version**: _trunk_
**Operating system**: _Windows_

---

**Comment by andythenorth** [comment]
Thanks for this.  At the time of writing this appears to be an isolated bug, and not frequently reported.  We do try to address bugs where they occur frequently and/or are easy to reproduce, but this one doesn't look like we can any go further, so I'm closing it.  Thanks for contributing!
