### ISSUE TITLE
Hotkeys: using 2 byte language's letter in Hotkeys.cfg

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6101]
**_telk5093_ opened the ticket and wrote:**

> Since I am Korean player, I write all texts in Korean in the game.
> But in Korean writing mode, I cannot use global hotkeys such as GLOBAL+A, GLOBAL+D.
> It works in English writing mode.
> (Note: there is 'Kor/Eng' key in Korean keyboard to change writing mode between korean and english.)
> 
> For example, there is 'ㄱ'(giyeok; the first letter of korean alphabet) in the place of R in Korean keyboard.
> In openttd, since R is a hotkey for remove, I tried to modify hotkeys.cfg like this:
> (...)
> tunnel = T
> remove = ㅊ,R
> convert = C
> (...)
> 
> However, 'ㅊ' disappears when I run the game.
> I think it seems that openttd treats korean letter as an invalid key, remove it from hotkeys.cfg.
> 
> 
> I think it could be very conveinient to play game for Korean or other two-byte-language users.

**Reported version**: _1.4.2_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_telk5093_ wrote:**

> Additional:
> Sorry for my mistakes in the task, not ㅊ but ㄱ.
> And I cannot use hotkeys not only global hotkeys but also others.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6101#comment13492_

**Comment by andythenorth** [comment]
See also #6301

**Comment by TrueBrain** [comment]
I fully agree that UTF-8 support in the config/hotkeys would be a welcome change. I just don't think enough people who can make it are interested .. and it is a pretty big job. So passing on this for now.

**Comment by James103** [comment]
See #8138 for a more recent instance of this issue.
