### ISSUE TITLE
Global hotkeys in game menu

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6104]
**_juanjo_ opened the ticket and wrote:**

> It is more a question than a feature request.
> 
> Why the global hotkeys GHK_DELETE_WINDOWS, GHK_DELETE_NONVITAL_WINDOWS, GHK_REFRESH_SCREEN and GHK_CRASH don't work while in the game menu? Is there a reason for that?

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> I don't think there is a reason.
> The global hotkeys for menu, scenario editor and in-game are just in three different code places, and there has been no unification or refactoring.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6104#comment13502_

**Comment by DorpsGek** [comment]
**_juanjo_ wrote:**

> It seems strange you can toggle bounding boxes and dirty blocks in game menu using hotkeys, while refreshing screen and the others are not available.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6104#comment13503_

**Comment by TrueBrain** [comment]
Strange it might be, but a fact it is :) Not currently planned to take action on this.
