### ISSUE TITLE
Involuntary cargo exchange with cargodist via neutral station

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6114]
**_planetmaker_ opened the ticket and wrote:**

> When two players serve a neutral station at an industry, a cross-company chain for cargo flow can and will be established which can only be interrupted if one of the players stops competing for the ressources of that industry.
> 
> It's a fun thing, but as it's unvoluntary sharing, it would at least need some way the players can control whether they want to share or not.
> 
> See the attached screenshot and savegame where fish is carried from all fishing grounds of yellow company via the Koudenhoek Fish Market, the neutral fishing ground De Falom Sandbank to the blue player's Den Haag Fish Market fishing harbour (and also vice versa).

**Attachments**
- [cross_company_cargodist.png](https://bugs.openttd.org/task/6114/getfile/9947/cross_company_cargodist.png) (1386.24 KiB)
- [cargodist_cross_company.sav](https://bugs.openttd.org/task/6114/getfile/9948/cargodist_cross_company.sav) (804.78 KiB)

**Reported version**: _1.4.3-RC1_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_fonsinchen_ wrote:**

> There is an easy fix for this: If you are loading at the shared station make the order "no unload" and if you're unloading make it "no load". Cargodist will then figure out that it should not create such a route. Is that sufficient?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6114#comment13559_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Discussed with planetmaker & frosch - can be moved to known_bugs.txt and closed.  Patch attached.

**Attachments**
- [known_bugs_6114.diff](https://bugs.openttd.org/task/6114/getfile/10808/known_bugs_6114.diff) (0.88 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6114#comment14596_

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> Not sure documenting a known bug counts as closing a bug...

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6114#comment14669_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Well it's feature eh? :) 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6114#comment14671_

**Comment by TrueBrain** [comment]
@andythenorth I expect a Pull Request from you addressing this soon :) (fully agree that known-bugs is sufficient)
