### ISSUE TITLE
Vehicles: allow 'livery override' for wagons  

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6136]
**_mb_ opened the ticket and wrote:**

> The livery override feature comes in handy especially when building articulated locomotives. It allows easy reuse of already defined veh-IDs as part of new articulated locomotives (e.g. steam locomotive tenders). 
> 
> However, this works only for 'engines' (locomotives), not for wagons, i.e. when building articulated wagons, you cannot reuse already defined veh-IDs as part of new articulated wagons, since there´s no 'livery override' (i.e. adoption of graphics), but the reused veh-ID keeps the graphics from its constituent action3. 
> 
> This is especially annoying when using lots of articulated vehicles, since one has to define a new veh-ID for each new articulated vehicle. It is also impossible to use articulated vehicles constructed in such a way in 'push-pull service' (by simple exchange of correlating graphic sprites).
> 
> However, that would be very easy if only the 'livery override' feature would work as well for wagons.
> 
> 
> 
>   

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Transportman_ wrote:**

> Can't you use var61 for that in combination with varC6 for that?
> 
> In the 2cc Trains In NML NewGRF I use it to check if a vehicle can be attached to the consist, but I imagine something like you want can also be done with it.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6136#comment13556_

**Comment by DorpsGek** [comment]
**_mb_ wrote:**

> > Can't you use var61 for that in combination with varC6 for that? [...]
> 
> No, it can´t. What I´m proposing here is simply "livery override for wagons", not only for engines.
> 
> This has nothing to do with vars 61, C6, or callback 1D. The orignal problem can´t be worked around by any of these.
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6136#comment13564_

**Comment by andythenorth** [comment]
If I've understood the issue correctly, this can be done by checking position in consist with varact2 in graphics chain.  https://newgrf-specs.tt-wiki.net/wiki/VariationalAction2/Vehicles#Position_within_articulated_vehicle_.284B.29

Co-incidentally there is also no shortage of IDs (16k are available for articulated vehicles), so multiple IDs can be safely consumed.

If I've misunderstood, apologies.  However:
* I am betting there is a way to achieve this within current spec.
* I know that there is no support for extending spec for livery over-rides
...so I'm closing this, thanks.
