### ISSUE TITLE
Orders: replace order for all vehicles

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6151]
**_Rollmaterial_ opened the ticket and wrote:**

> A feature that would allow to replace an order for all vehicles that have it at once. It would be useful when relocating highly used stations, waypoints or depots, so one doesn't have to change the order list of every vehicle/order sharing group separately. This feature could be accessible i. e. from the vehicle lists or the station/waypoint/depot GUI.

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
I fully agree this would be useful, but a GUI for this is very difficult. I do not see this happening on the short term, so going to close the issue. Sorry, and thank you.
