### ISSUE TITLE
Add support for SDL2

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6173]
**_ignatenkobrain_ opened the ticket and wrote:**

> https://wiki.libsdl.org/MigrationGuide

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> So far, SDL2 seems slower

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6173#comment13638_

**Comment by DorpsGek** [comment]
**_Marctraider_ wrote:**

> lol, nvm that :p

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6173#comment13640_

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.

**Comment by nikolas** [comment]
I'm going to look into what kinds of changes this will require and see if I can get something working. Should be fun! Relevant docs:
* https://wiki.libsdl.org/MigrationGuide
* [ASGP's Android Port Part II: from SDL 1.2 to SDL 2](http://blog.stuff-o-matic.com/post/2013/09/15/ASGP-s-Android-Port-Part-II%3A-from-SDL-1.2-to-SDL-2.) (Video code update commit: https://github.com/j-jorge/bear/commit/8ab09228c00c59c21f5283db09d955c5e93ee453) Though this example is using OpenGL, so OpenTTD's conversion to SDL 2 will be more challenging than this.

**Comment by nikolas** [comment]
I've gotten OpenTTD's SDL video driver working with SDL 2 on this branch. https://github.com/nikolas/OpenTTD/tree/sdl2 A work in progress: unicode/compose key input isn't working yet.

I'm also not sure if it makes sense to make a new video driver: `sdl2_v.cpp` to leave the option of using SDL 1.2, or just update the current `sdl_v.cpp` to 2.0.

**Comment by LordAro** [comment]
I wouldn't expect to need to support both versions of SDL, they're quite different and supporting both will just make things difficult.

**Comment by LordAro** [comment]
You *might* find https://github.com/FreeRCT/FreeRCT/blob/master/src/video.cpp interesting to look at - it uses SDL2 and there are some similarities to OTTD's codebase (I think it was converted from 1.2 to 2 at some point in the history as well)

**Comment by orudge** [comment]
I've had a play with your code, @nikolas, and it seems to be working well for me (although I must stress I haven't tested it extensively!). I was also able to combine it with my (currently very experimental and incomplete) UWP port of OpenTTD, and it works there too. :)

**Comment by nikolas** [comment]
Cool, good to hear. Currently there are problems with text input on my `sdl2` branch: when typing in a text box, certain keys are interpreted as key shortcuts, and random windows like the road builder pop up when they shouldn't. Once I fix that I think I'll open a pull request.
