### ISSUE TITLE
Railtypes: specify conversion cost

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6177]
**_George_ opened the ticket and wrote:**

> R27064
> 
> It is very bad, that convertation of non-electrified rails to electrified rails cost as removing normal rails and building new rails and with wires. It should cost as providing wires only (convertation should be much cheaper than it is in such cases). So it is required to have a way to specify such cases.
> 
> Please provide new rail-type properties, that specify list of rail-types with cheap convertation and|or convertation cost factor.

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
Eddi proposed a spec for this in #openttd irc 12th April 2018, but has no github login to add it to the ticket :P

**Comment by TrueBrain** [comment]
I do agree it is a bit weird that the costs are this high. But I think we are going to pass on this for now, as I don't see it changing any time soon. Tnx though!
