### ISSUE TITLE
Vehicles: auto-refit on purchase if vehicle list filtered by cargo

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6191]
**_SirXavius_ opened the ticket and wrote:**

> I've often wished that vehicles when created are automatically refitted after determining which vehicles can be refitted to your needs. So here's my proposal...
> 
> After opening the New Vehicles dialog and filtering the vehicle list according to cargo type, pressing New will create a vehicle already fitted to that cargo type. So for example if I open the RV list looking for a truck to carry grain, I filter the listings to show only those vehicles that can be refitted to carry grain, then click on New and the vehicle is built in that depot already refitted, able to carry grain. If there is a cost to be incurred, it's automatically added to the price.
> 
> Since everyone may not want this feature when clicking on New after filtering the list, perhaps this should be made an option.

**Reported version**: _1.4.4_
**Operating system**: _Windows_

---

**Comment by andythenorth** [comment]
I think this is TMWFTLB.  It's better IMHO to use station refit orders for all vehicles in an order group.
