### ISSUE TITLE
Autorenew fails for articulated vehicles with mixed cargo

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6207]
**Summary of this topic** 

Current situation:
* Exotic articulated vehicle (like in PKP set) can be refitted to carry different cargos at once (in different articualted parts).
* Autorenew for these vehicles fails, since autorenew relies on build+refit, and there is no easy strategy for refitting this kind of vehicle.
* Cloning uses a different strategy for adjusting cargos and works.

Task:
* Change autorenew to do refits like cloning does.

Note:
* This only applies to autorenew. Autoreplace with different vehicle is not possible.

**_TadeuszD_ opened the ticket and wrote:**

> The autorenew mechanism doesn't work correctly for articulated train vehicles, which can transport more than one cargo type.
> 
> Those vehicles can be defined via NewGRF addons. For example, the EMU contained 2 or more articulated parts, where:
> \- one part can be rebuilt to passengers/mail.
> \- rest of parts can transport only passengers,
> Example train is properly supported in the Train refit window and the Train information window. All available cargoes are displayed. Player can refit mentioned train for transport only passengers or passengers+mail.
> 
> But autorenew mechanism works partially. When the train is refitted for transport only passengers, everything is OK. However, when the train is refitted for transport passengers+mail, autorenew process fails without any warning. The train is going very old and may lead to the collapse of the company.
> 
> It would be nice to add full support for multi-cargo vehicles in autorenew process.

**Attachments**
- [EN57.png](https://bugs.openttd.org/task/6207/getfile/10081/EN57.png) (60.88 KiB)

**Reported version**: _1.4.4_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> Silent autorenew failure sounds more like a bug than a feature request. It can be a bug in the newgrf though.
> Can you provide instructions how to reproduce it, and what you result you find wrong?
> 
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6207#comment13712_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> It's implemented like that.
> Autoreplace refuses to replace articulated vehicles which carry multiple cargos, because it is non-obvious what replacements should be allowed, and how they should be refitted.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6207#comment13714_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Ah, I guess one can make it work for autorenew, by adding a special case that uses clone instead of build+refit.
> Autoreplace won't work in any case though.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6207#comment13715_

**Comment by DorpsGek** [comment]
**_TadeuszD_ wrote:**

> Frosch is right. It's not a bug. It's implemented like that.
> 
> To reproduce described 'bug', you can use test version of my NewGRF. You can download it from https://dev.openttdcoop.org/attachments/download/6997/pkp-set-2.0.11.grf
> NewGRF NML source is available in project repository:
> https://dev.openttdcoop.org/projects/pkpset/repository/changes/src/engines/enxx-common.pnml
> https://dev.openttdcoop.org/projects/pkpset/repository/changes/src/engines/en57.pnml
> 
> The EMU EN57 (available since 1957) can be refitted to carry passengers and mail.
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6207#comment13716_

**Comment by DorpsGek** [comment]
**_TadeuszD_ wrote:**

> Small update. Polish PKP Set 2.0.11 is now available on BaNaNaS.
> You can test mentioned bug using EMUs: EN57 (available since 1957) and EN71 (available since 1976).

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6207#comment13774_

**Comment by andythenorth** [comment]
Newgrfs shouldn't include articulated vehicles with mixed cargos, it's not supported.  Thanks :)

I'm closing this as we try to keep the issue count low for OpenTTD, it helps us focus on things that are important and fun.  Feel free to discuss in irc or request re-opening if you disagree.  Thanks for contributing!

**Comment by andythenorth** [comment]
I disagree! :)

I confirmed that autoreplace does not work for the specific case of mixed mail + pax engines, which also do _not_ offer player cargo refits.  

That limited case seems reasonable to support? 

Accepting that that the actual implementation might be TMWFTLB.

Or alternately to supporting this, the autoreplace GUI could not offer the articulated vehicle as a valid replacement option?  

GRF attached.  Test situation is
* set game date to 1933 or so
* articulated mixed vehicle 1 (autocoach 1900), pax + mail, no player refits
* articulated mixed vehicle 2 (autocoach 1930), pax + mail, no player refits
* vehicle 2 can be selected as replacement for vehicle 1 in autoreplace GUI
* replacement _will fail silently_ in depot when train visits
* replacement _will fail silently_ in depot if player uses 'force autoreplace' button

[iron-horse-2.8.0-5-g1926053b.zip](https://github.com/OpenTTD/OpenTTD/files/5360722/iron-horse-2.8.0-5-g1926053b.zip)

Relevant LOC seems to be https://github.com/OpenTTD/OpenTTD/blob/master/src/autoreplace_cmd.cpp#L212

**Comment by Eddi-z** [comment]
i think the only way to reasonably solve this would be with template replacement.

**Comment by 2TallTyler** [comment]
@JGRennison Did you fix this in #11253?

**Comment by JGRennison** [comment]
> @JGRennison Did you fix this in #11253?

Yes this should be fixed
