### ISSUE TITLE
UDP query of game script

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6211]
**_The_Dude_ opened the ticket and wrote:**

> Patch adds a possibility to query OpenTTD server for running game scripts and returns its name and version if any present.
> 
> This could be used to show GS info in server details of http://www.openttd.org/en/servers, in network lobby of server detail, so player could seek for a GS which he likes.
> 
> 
> I am also preparing a overall statistics of public servers, where it could be used to see what GS are currently available to play.
> 
> Overview of NewGRFs used on public servers:
> http://www.novapolis.net/newgrfsAservers.php

**Attachments**
- [UPD_query_gamescript.patch](https://bugs.openttd.org/task/6211/getfile/10096/UPD_query_gamescript.patch) (6.16 KiB)

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_ST2_ wrote:**

> some servers/communities use several gamescripts, packed together and controlled by openttd.cfg settings that say to main.nut what files to load. Since the main gamescript (that gives the info to your query) is global (only a controller, lets say like this), won't show the real gamescript used. Wich makes the query useless, imho.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6211#comment13726_

**Comment by DorpsGek** [comment]
**_The_Dude_ wrote:**

> You do not understand. 
> Game can have only one game script loaded, if someone merges more GS into one, it is still one GS from the view of the game.
> 
> The GS query is mainly informal, but still it can provide information whether the server has or has not a GS controlled game and whether it is the GS you'd like to play no matter if it is the original one or some modded version.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6211#comment13728_

**Comment by andythenorth** [comment]
Pull request? o_O

**Comment by TrueBrain** [comment]
What am I missing: your patch adds functions, but I do not see where they are called?

That said, it is not a bad idea; I mostly wonder if you also would like to see which AIs are loaded ..

Either way, if you are still interested in bringing this forward, please create a Pull Request. Closing ticket (as I think the patch is only a partial).

**Comment by TrueBrain** [comment]
Ah, I only now understand you; you only wants this for websites etc.

In general, we don't do that. I would really like to see an ingame interface change for this too, where you can see the same info.
