### ISSUE TITLE
Commuter - Helicopter is in flight bug

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6219]
**_Samu_ opened the ticket and wrote:**

> Quick way to reproduce the bug is by having no means to have cargo waiting at the commuter
> 1) Build a commuter near nothing.
> 2) Build 3 helicopters and full load at the commuter.
> 3) Start all 3 helicopters.
> 
> The 3rd helicopter will be bugged inside hangar and cannot be stopped. It says it is in flight. For this to happen, the 2 helipads must be busy.
> 
> Another bug, continuing the steps.
> 4) Send the first helicopter to hangar.
> 
> The 3rd helicopter is not heading to the free helipad.
> 
> Yet another bug, continuing.
> 5) Send the second helicopter to hangar.
> 
> The 2nd helicopter and 3rd helicopter will go through each other head on.

**Attachments**
- [Aircraft in flight error.png](https://bugs.openttd.org/task/6219/getfile/10107/Aircraft+in+flight+error.png) (198.41 KiB)

**Reported version**: _1.5.0-beta1_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_Samu_ wrote:**

> Savegame

**Attachments**
- [Fanwell City Transport, 2053-07-23.sav](https://bugs.openttd.org/task/6219/getfile/10108/Fanwell+City+Transport%2C+2053-07-23.sav) (11.58 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6219#comment13740_

**Comment by DorpsGek** [comment]
**_Samu_ wrote:**

> Sorry, that savegame shows nothing, and the steps are missing something.
> 
> Trying again:
> 
> 1) Build 2 airports, one is commuter, the other is a random one
> 2) Build 3 helicopters at the commuter
> 3) Order the 3 helicopters to full load at the commuter as order 1
> 4) Order the 3 helicopters to go to the random airport as order 2
> 5) Order Helicopter 3 to skip to order 2
> 6) Start Helicopter 1 and 2 first, then start 3 shortly after.
> 
> The 3rd helicopter will be bugged inside hangar and cannot be stopped. It says it is in flight. For this to happen, the 2 helipads must be busy.
> 
> Another bug, continuing the steps.
> 7) Send the first helicopter to hangar.
> 
> The 3rd helicopter is not heading to the free helipad.
> 
> Yet another bug, continuing.
> 8) Send the second helicopter to hangar.
> 
> The 2nd helicopter and 3rd helicopter will go through each other head on.
> 
> I've attached another savegame.

**Attachments**
- [Fanwell City Transport, 2055-08-10.sav](https://bugs.openttd.org/task/6219/getfile/10109/Fanwell+City+Transport%2C+2055-08-10.sav) (12.88 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6219#comment13741_

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> Save game shows commuter airport with 2 helicopters loading, and the 3rd helicopter in the hangar "heading to foo airport".
> 
> 6) While 3rd helicopter is still in the hangar, it's considered to be "en route", stopping is not possible.
> 
> At the other airport, one can stop helicopter while taxiing or on the runway. It looks like stopping was omitted at the commuter. Aircraft can be stopped as well at the commuter.
> 
> 
> 7) Click the rightmost helicopter, and let it return to the hangar. Helicopter 3 in the hangar does not pick up this change, and stays in the hangar.
> This also happens when the rightmost helicopter leaves the airport.
> 
> 8) Click the leftmost helicopter, and let it return to the hangar. Helicopter 3 is released too early, and both helicopters cross each other in front of the hangar.
> 
> If you let one helicopter from the hangar return to the leftmost loading spot, and then release the second one, the rightmost empty position is noticed.
> 
> Conclusions about the commuter airport:
> \- Stopping of helicopters seems broken or not implemented.
> \- Selection of free helipads from the hangar does not notice the right-most pad getting empty if it is initially claimed.
> \- Block in front of the hangar is released too early by helicopter returning to the hangar from the leftmost position (and perhaps also the rightmost position).
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6219#comment13750_

**Comment by nielsmh** [comment]
Possibly aircraft control logic should be entirely changed to use a separate "is_airborne" flag rather than the current state checks, similar to what I'm doing in #6962. The flag should then be set when an aircraft begins take-off, and be cleared when it finishes landing.
