### ISSUE TITLE
Stations: using property 1A sometimes shows incorrect railtype ground tile

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6222]
**_mart3p_ opened the ticket and wrote:**

> I found this problem when a station is built with one particular railtype from NuTracks 2. The railtype is NuTracks' combined monorail/maglev. Other railtypes work as expected.
> 
> I have written a test GRF which is attached, along with a zip file with the source NFO and a sprite sheet. The GRF contains 2 stations. Both are coded using property 1A and are identical, except that the second station has bit 1 set (add offset to sprite) for its platform sprite. The register for this offset is always set to 0. In both cases the ground sprite has no flags set.
> 
> In the case of station 1 everything works as expected. Station 2 shows incorrect ground sprites when used with NuTracks combined monorail/maglev.
> 
> To reproduce:
> 1. Load NuTracks 2 (available from online content download).
> 2. Set NuTracks parameter "Force narrow gauge tracks" On. This also makes the combined monorail/maglev railtype available.
> 3. Load the test grf supplied "Station property 1A test".
> 4. Start a new game in 2020.
> 5. Select "Maglev/monorail track construction".
> 6. Open the station build menu and select "Station property 1A test".
> 7. Build Station 1 - it works correctly and shows the correct ground sprite track graphics.
> 8. Build Station 2 - it shows the wrong ground sprite track graphics.
> 
> At first, I thought this must be a bug in NuTracks, but I can't see what could cause this problem. And as I said, the ground sprites are coded identically. It is only the platform sprite coding that differs, yet it is effecting the ground sprites.
> 
> Using:
> OpenTTD 1.5.0-beta1 (also occurs in 1.4.4)
> NuTracks 2 r247
> 

**Attachments**
- [prop1A_test.grf](https://bugs.openttd.org/task/6222/getfile/10112/prop1A_test.grf) (1.21 KiB)
- [Prop_1A_test_GRF.zip](https://bugs.openttd.org/task/6222/getfile/10113/Prop_1A_test_GRF.zip) (3.07 KiB)
- [Station_prop_1A_bug.png](https://bugs.openttd.org/task/6222/getfile/10114/Station_prop_1A_bug.png) (10.94 KiB)

**Reported version**: _1.5.0-beta1_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Test savegame

**Attachments**
- [fs6222.sav](https://bugs.openttd.org/task/6222/getfile/10157/fs6222.sav) (23.01 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6222#comment13809_

**Comment by LordAro** [comment]
arbitrary bump
