### ISSUE TITLE
Crash when no baseset en invalid font in configuration

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6226]
**_roidal_ opened the ticket and wrote:**

> Version:
>     Linux 1.4.4 64 bit
> 
> What happens:
>     Segfault if there is no graphic-set available (first start)
> 
> How to bypass:
>     Manually copy opengfx-0.5.0.tar into the ~/.openttd/baseset directory
> 
> Additional to the attached crash.log there are few error-lines at STDOUT:
> 
> ./openttd 
> Unable to use '/usr/share/fonts/adobe-source-han-sans-twhk/SourceHanSansTW-Heavy.otf' for medium font, FreeType reported error 0x1, using sprite font instead
> Unable to use '/usr/share/fonts/adobe-source-han-sans-twhk/SourceHanSansTW-Heavy.otf' for small font, FreeType reported error 0x1, using sprite font instead
> Unable to use '/usr/share/fonts/adobe-source-han-sans-twhk/SourceHanSansTW-Heavy.otf' for large font, FreeType reported error 0x1, using sprite font instead

**Attachments**
- [crash.log](https://bugs.openttd.org/task/6226/getfile/10123/crash.log) (1.92 KiB)

**Reported version**: _1.4.4_
**Operating system**: _Linux_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> There are two features in conflict here:
> \* If no baseset is installed, OTTD tries to not use the sprite font, but a system supplied font instead.
> \* If the system font set via openttd.cfg (SourceHanSansTW-Heavy) is invalid, it falls back to the sprite font.
> 
> Likely these two fallbacks need to be reversed, or iterated twice.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6226#comment13758_

**Comment by andythenorth** [comment]
Thanks for this.  At the time of writing this appears to be an isolated bug, and not frequently reported.  We do try to address bugs where they occur frequently and/or are easy to reproduce, but this one doesn't look like we can any go further, so I'm closing it.  Thanks for contributing!
