### ISSUE TITLE
Remember the game save/load location even when closing the app

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6253]
**_yura_gr_ opened the ticket and wrote:**

> If you load a game, which is a very common scenario, the "save" folder (OpenTTD save folder) is the current folder.
> 
> I usually save my games in my Dropbox folder, because I play on different computers, and I get redundancy as a bonus.
> Each time I want to play, I open OpenTTD and choose "Load Game", and I have to locate my Dropbox folder, and then locate the game within it. Every time.
> 
> It would be nice that when I choose "Load Game", the current directory will be the one that was current before I closed the game.
> 

**Reported version**: _1.4.4_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> Perhaps replace the default savegame folder by a link to your dropbox folder?
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6253#comment13820_

**Comment by DorpsGek** [comment]
**_yura_gr_ wrote:**

> Replacing the default savegame folder by a link didn't worked. It is windows. The game recreated the "save" folder in the same location.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6253#comment13821_

**Comment by TrueBrain** [comment]
You can also store OpenTTD completely on DropBox. The save folder is read relative from OpenTTD, so that could help you out here.

I understand your use case, but I do not think the solution is practical. What would be more useful in my opinion is one of these:

- Recent savegames (top 5 recent games in Load Game window?)
- Bind extension so you can double click it to open OpenTTD (bit tricky, as OpenTTD doesn't need to be installed to work)

**Comment by andythenorth** [comment]
I think we can close this.  If someone wants to implement one of TrueBrain's suggestions they're free to do so and make a PR instead.  Thanks.

**Comment by TrueBrain** [comment]
I really think this needs some resolution, as it annoys most people who use a cloud-service to store their savegames :)

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
