### ISSUE TITLE
UI Zoom: ugly lists in network windows on double/quad interface sizes with custom fonts

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6266]
**__dp__ opened the ticket and wrote:**

> Patch changes:
> Server Lobby:
> \- List width (not sure if that's the proper way to do it though)
> \- Lines height
> \- Icons and text vertical centering
> Network servers window:
> \- Icons vertical centering 

**Attachments**
- [openttd150rc1-bug-network-windows-quad-size.png](https://bugs.openttd.org/task/6266/getfile/10184/openttd150rc1-bug-network-windows-quad-size.png) (302.08 KiB)
- [network-windows-better-scaling.diff](https://bugs.openttd.org/task/6266/getfile/10185/network-windows-better-scaling.diff) (4.53 KiB)

**Reported version**: _1.5.0-beta1_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> See also #6212 - not same but related.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6266#comment14618_

**Comment by LordAro** [comment]
@ldpl Care to make a PR out of this? Patch still applies cleanly

**Comment by nielsmh** [comment]
This is an actual bug that needs to be fixed.
