### ISSUE TITLE
Crash when creating company in MP from Spectator

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6269]
**_burninghey_ opened the ticket and wrote:**

> Got a crash when starting a new company (multiplayer, btpro.nl # 99 testserver busybeepro with multiple goals)
> 
> I joined game as spectator, then tried to fund a new company - openttd crashed.
> Tried again, this time no problem.
> 
> OpenTTD 1.5.0-RC1
> Windows 10 Pro Technical Preview # 10041
> 
> Note: had to zip the 12MB crash.dmp to be able to attach it

**Attachments**
- [crash.zip](https://bugs.openttd.org/task/6269/getfile/10187/crash.zip) (289.23 KiB)
- [crash.log](https://bugs.openttd.org/task/6269/getfile/10188/crash.log) (10.42 KiB)
- [crash.png](https://bugs.openttd.org/task/6269/getfile/10189/crash.png) (97.45 KiB)
- [crash.sav](https://bugs.openttd.org/task/6269/getfile/10190/crash.sav) (299.44 KiB)

**Reported version**: _1.5.0-RC1_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_burninghey_ wrote:**

> I'm sorry didnt put os/version in summary. chrome crashed twice, because i tried to attach a file greater than 8 MiB.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6269#comment13842_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> upload limit increased

**Attachments**
- [crash.dmp](https://bugs.openttd.org/task/6269/getfile/10192/crash.dmp) (11242.73 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6269#comment13844_

**Comment by andythenorth** [comment]
Thanks for this.  At the time of writing this appears to be an isolated bug, and hard to reproduce.  We do try to address bugs where they occur frequently and/or are easy to reproduce, but this one doesn't look like we can any go further, so I'm closing it.  Thanks for contributing!
