### ISSUE TITLE
Vehicles: lifetime profit

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6275]
**_burty_ opened the ticket and wrote:**

> This is a quick patch that enables lifetime profit display on vehicles.
> 
> Forum link: http://www.tt-forums.net/viewtopic.php?f=33&t=72844

**Attachments**
- [Lifetime profit V2.patch](https://bugs.openttd.org/task/6275/getfile/10200/Lifetime+profit+V2.patch) (5.42 KiB)
- [openttd.zip](https://bugs.openttd.org/task/6275/getfile/10201/openttd.zip) (8184.48 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> And some quick comments on the patch.
> 
> For the next time, there is no need to provide a binary, we are quite capable of building our own versions :)
> 

**Attachments**
- [profit_V2_comments.txt](https://bugs.openttd.org/task/6275/getfile/10202/profit_V2_comments.txt) (3.99 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6275#comment13855_

**Comment by DorpsGek** [comment]
**_burty_ wrote:**

> Thank you Alberth for your time in looking at my patch and providing feedback. 
> 
> I have taken the feedback on board (for future as well) and have addressed all of the comments in this latest patch.
> 
> Many Thanks,
> Ben

**Attachments**
- [Lifetime profit V2.1.patch](https://bugs.openttd.org/task/6275/getfile/10203/Lifetime+profit+V2.1.patch) (4.93 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6275#comment13856_

**Comment by DorpsGek** [comment]
**_burty_ wrote:**

> Attaching latest version.
> 
> Change log:
> Added new setting for news item advisory to use lifetime instead of last year profit.
> Added sort by option on vehicle list windows

**Attachments**
- [Lifetime profit V4.patch](https://bugs.openttd.org/task/6275/getfile/10434/Lifetime+profit+V4.patch) (11.66 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6275#comment14106_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Patch fails to apply on r27910
> 
> HEAD is now at f1e54b437 (svn r27910) -Update from Eints:
> openttd-trunk(master)$ curl https://bugs.openttd.org/task/6275/getfile/10434/Lifetime%20profit%20V4.patch | patch -p0
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 11940  100 11940    0     0  73518      0 --:--:-- --:--:-- --:--:-- 73703
> (Stripping trailing CRs from patch.)
> patching file src/lang/english.txt
> Hunk # 4 succeeded at 3675 (offset 14 lines).
> (Stripping trailing CRs from patch.)
> patching file src/saveload/afterload.cpp
> Hunk # 1 succeeded at 2977 (offset 2 lines).
> (Stripping trailing CRs from patch.)
> patching file src/saveload/saveload.cpp
> Hunk # 1 FAILED at 263.
> 1 out of 1 hunk FAILED -- saving rejects to file src/saveload/saveload.cpp.rej
> (Stripping trailing CRs from patch.)
> patching file src/saveload/vehicle_sl.cpp
> Hunk # 1 succeeded at 685 (offset 2 lines).
> (Stripping trailing CRs from patch.)
> patching file src/settings_gui.cpp
> Hunk # 1 succeeded at 1561 (offset 2 lines).
> (Stripping trailing CRs from patch.)
> patching file src/settings_type.h
> (Stripping trailing CRs from patch.)
> patching file src/table/settings.ini
> Hunk # 1 succeeded at 2929 (offset 8 lines).
> (Stripping trailing CRs from patch.)
> patching file src/vehicle.cpp
> Hunk # 1 succeeded at 2693 (offset 48 lines).
> (Stripping trailing CRs from patch.)
> patching file src/vehicle_base.h
> Hunk # 1 succeeded at 238 (offset 58 lines).
> Hunk # 2 succeeded at 573 (offset 59 lines).
> (Stripping trailing CRs from patch.)
> patching file src/vehicle_gui.cpp
> Hunk # 5 succeeded at 2097 (offset 5 lines).
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6275#comment14730_

**Comment by andythenorth** [comment]
Thanks for this.  Lifetime profit is not a current goal for core.  But JGR patch-pack has implemented this (as far as I know), so it can be used there.
