### ISSUE TITLE
GSNews.Create makes game script failed on Linux, 1.5.0

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6276]
**_Gavin_ opened the ticket and wrote:**

> Env:
> 
> Ubuntu 12.04, OpenTTD 1.5.0, Simple_City_Builder-2015.01.07
> 
> It seems Windows version works fine.
> 
> Description:
> 
> On 1.5.0, GSNews.Create has two more params:
> NewsReferenceType
> ref_type
> 
> http://nogo.openttd.org/api/1.5.0/classGSNews.html# 97c8abe72c217c2b34795c5b6b37fe0a
> 
> And a GSNews.Create call of old version will crash the script:
> 
> dbg: [script] [18] [S] Your script made an error: wrong number of parameters
> dbg: [script] [18] [S] 
> dbg: [script] [18] [S] *FUNCTION [HQClaimTown()] content_download/game/Simple_City_Builder-2015.01.07/main.nut line [358]
> dbg: [script] [18] [S] *FUNCTION [DailyLoop()] content_download/game/Simple_City_Builder-2015.01.07/main.nut line [245]
> dbg: [script] [18] [S] *FUNCTION [Process()] content_download/game/Simple_City_Builder-2015.01.07/main.nut line [174]
> dbg: [script] [18] [S] *FUNCTION [Start()] content_download/game/Simple_City_Builder-2015.01.07/main.nut line [153]

**Reported version**: _1.5.0_
**Operating system**: _Linux_

---

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> Made a trivial test game script that displays a news message (and then crashes as its Start function then terminates).
> This works for me in trunk, with 1.4 compatibility, just like your script.
> 
> I would expect this as well, as the script lives completely in the Squirrel domain, and Windows and Unix are the same there (modulo used compilers).
> If you run the debug level at 6 ( ./openttd -d script=6 ), do you get the "dbg: [script] [18] [I] 1.4 API compatibility in effect." line ?
> 
> The file that fixes 1.4 -> 1.5 compatibility of news is (copied the line from the 1.5 source download):
> 
> \-rw-r--r-- root/root       644 2015-04-01 20:35 openttd-1.5.0/bin/game/compat_1.5.nut
> 
> Do you have this file?
> 

**Attachments**
- [news_test.tgz](https://bugs.openttd.org/task/6276/getfile/10205/news_test.tgz) (0.64 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6276#comment13857_

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> Oops, that file is actually
> 
> \-rw-r--r-- root/root       899 2015-04-01 20:35 openttd-1.5.0/bin/game/compat_1.4.nut
> 
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6276#comment13858_

**Comment by TrueBrain** [comment]
No response after 3 years. Closing ticket.
