### ISSUE TITLE
Canal on River

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6277]
**_Samu_ opened the ticket and wrote:**

> This patch restores rivers when demolishing canals that have been built on river tiles. Demolishing them again will actually clear the river tiles.
> 
> \- A behaviour was changed: Leveling land with rivers or lakes will not immediately demolish them, they must be cleared first.
> \- A better error message was added to complement the behaviour change.
> \- Store canal on river bit flag on m1 bit 7 for convenience.
> \- Moved completed industry flag from m1 bit 7 to m1 bit 4, and added a conversion for old savegames.
> \- Updated the documentation regarding these changes.

**Attachments**
- [Canal on River v5 r27220.patch](https://bugs.openttd.org/task/6277/getfile/10204/Canal+on+River+v5+r27220.patch) (21.52 KiB)

**Reported version**: _trunk_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_Samu_ wrote:**

> There was a problem with v5, I was setting canal on river too early for industries, and that was causing assertion. This fixes it.

**Attachments**
- [Canal on River v7 r27221.patch](https://bugs.openttd.org/task/6277/getfile/10206/Canal+on+River+v7+r27221.patch) (21.58 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6277#comment13860_

**Comment by andythenorth** [comment]
I think we'll pass on this one, thanks.
