### ISSUE TITLE
compile and linker warnings (gcc 4.9, arch linux)

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6279]
**_planetmaker_ opened the ticket and wrote:**

> see https://paste.openttdcoop.org/pydkk11vt

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_LordAro_ wrote:**

> CFLAGS='-O3 -march=native -freorder-blocks-and-partition -pipe' ./configure --with-ccache --with-freetype --with-liblzma --with-sdl --with-makedepend --enable-debug=0 --enable-lto
> 
> With gcc7, most of the compiler warnings have gone away with those configure options. Still quite a few linker warnings, however

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6279#comment14553_

**Comment by TrueBrain** [comment]
I think a developer should just pick this up; having this as an issue is a nicer reminder, but in the end doesn't really result in action.

So sorry, but closing issue :)
