### ISSUE TITLE
Console: support for non-ascii character in console of dedicated server

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6301]
**_telk5093_ opened the ticket and wrote:**

> Hi, I'm Korean Translator and now operating dedicated server.
> But its console does not support non-ascii character such as korean as you can see the image that I attached.
> It is hard to manage my server's clients. I can't see and write korean in the dedicated server console.
> It will be very glad to be able to see and write non-english language in there.
> 
> ps. In addition, it will be very convenient if there is a console command that shows real date or time.

**Attachments**
- [1.png](https://bugs.openttd.org/task/6301/getfile/10256/1.png) (22.56 KiB)

**Reported version**: _1.5.0_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
I fully agree that UTF-8 support in the Console would be a welcome change. I just don't think enough people who can make it are interested .. and it is a pretty big job. So passing on this for now.
