### ISSUE TITLE
Window position jumps after being moved if "timetable" or "orders" is clicked

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6302]
**_oneshot_ opened the ticket and wrote:**

> OSX 10.10.3
> 
> If a vehicle's order window is moved from the position where it was spawned then clicking on the toggle between "Orders" and "Timetable" causes the entire window to jump back to the place where the window was first spawned.
> 
> To reproduce:
> 
> Click any vehicle (train, road, plane, [ships?])
> In the viewport that appears click the arrow "Show Vehicle Orders"
> MOVE THE RESULTING WINDOW
> Click "Timetable"
> The window jumps back to the initial spawn position
> Move it again
> Click "Orders"
> The Window jumps back again to the inital spawn position
> 
> It's pretty annoying. Other windows don't exhibit this behavior.

**Reported version**: _1.5.0_
**Operating system**: _Mac OS X_

---

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> It's not the same window, the timetable window and the order window are two different windows, and they both spawn (mostly?) at the same place relative to the vehicle window they belong to.
> 
> So while it may look like the same window jumping back to you, in fact the 'old' window is closed, and a new (different one) opens at a similar position as the previous one was opened.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6302#comment13920_

**Comment by DorpsGek** [comment]
**_oneshot_ wrote:**

> I see. The effect, however, is that of a transformation from one window to the next even though under the covers it is one window closing and another opening.
> 
> From a UI perspective, it seems that the window refuses to stay where I take the time to specifically place it.
> 
> If I move that window elsewhere why is that explicit order disregarded and a new window respawned on top of the vehicle viewport window? I instantly have to track down the new window to continue my work, followed by repositioning it all over again. This quickly becomes tiresome.
> 
> I imagine, if this is not a bug that there is a good reason for this behavior but it is opaque to me. And given the deep customizability of this game it seems like the imposition of an arbitrary UI quirk.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6302#comment13921_

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> Here's a nasty patch that pretends it is the same window and repositions and resizes based on the 'other' window if it's open. It's a horrible hack!

**Attachments**
- [fs6302.diff](https://bugs.openttd.org/task/6302/getfile/10670/fs6302.diff) (2.77 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6302#comment14381_

**Comment by andythenorth** [comment]
I can repro the behaviour.  However I don't think this is a valid issue currently.  

* there are other similar unexpected behaviours with window opening in OpenTTD
* fixing them one at a time in isolation is likely to cause a fragmentation of approach and solutions, UI consistency will get worse not better
* fixing one at a time, _against a consistent rule_ would be a good way to get it done, but no consistent approach has been suggested

If someone wanted to pick this up, a list of windows that don't open/re-open where expected would be a good starting point.  Then common causes can be figured out. 

Meanwhile, closing this as we cleanup and clarify priorities, thanks
