### ISSUE TITLE
Bug with usage of varAction2 var10 (Pick sprites for different GUI windows)

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6318]
**_mb_ opened the ticket and wrote:**

> When using that var10, e.g. when supplying special graphics for the depot view for an articulated vehicle, composed from different veh-IDs and using Action3 "livery override" for one of those veh-IDs, not only that special "depot view graphics" are displayed, but also the original graphics associated with that particular veh-ID having been overridden, in case this vehicle supplies a "depot view" for itself.
> 
> IMO, this is not only a misconception because it could be worked around, but rather a bug, simply because var10 had been announced to "display different sprites in the GUI and on the map".
> 
> Example:
> 
> \- pic1 shows both a depot view (top) and a normal view (bottom). You can see that e.g. the very first coach behind the engine head in the depot view is superimposed by some other graphics.
> 
> \- pic2 shows that those graphics can be picked and are superfluous graphics for the coaches (sprites # 19556). The sprite to be displayed in the depot view is # 25502.
> 
> In fact, # 19554 would be the overriden sprite for that coach, but # 19556 is its "depot view" sprite.
> 
> regards
> Michael

**Attachments**
- [display_mode.png](https://bugs.openttd.org/task/6318/getfile/10293/display_mode.png) (8.72 KiB)
- [display_mode2.png](https://bugs.openttd.org/task/6318/getfile/10294/display_mode2.png) (8.78 KiB)

**Reported version**: _trunk_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> I would rather see this closed as "won't implement" in favour of fixing at root cause in #6357.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6318#comment14665_

**Comment by TrueBrain** [comment]
Proper solutions go first :)
