### ISSUE TITLE
Cursor: mousepointer flickers when moving the mouse

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6319]
**_3dmaxb00n_ opened the ticket and wrote:**

> Hi,
> 
> I noticed the following Problem since V1.4.2. Do not know, if it existet in earlier versions. I do not know, if it affects other OS.
> 
> When moving the mouse around, the cursor flickers. The strength varies from barely visible to invisible. This effect is heavier, when the game is paused. When unpaused, the cursor flickers but remains visible enough. I explained the problem in the forum here: https://www.tt-forums.net/viewtopic.php?t=71149# p1129732.
> 
> I have a Logitech g500 mouse with 4400dpi and 500 signals per second. If I lower the values, the flicker is less heavy. With standard office mouse types, the problem is gone. If I connect my G500 to my Laptop and play the game there, the flicker effect appears. I do not have other mice to test.
> 
> Hope this gets fixed.

**Attachments**
- [cursor1.jpg](https://bugs.openttd.org/task/6319/getfile/10295/cursor1.jpg) (92.58 KiB)
- [cursor2.jpg](https://bugs.openttd.org/task/6319/getfile/10296/cursor2.jpg) (93.25 KiB)
- [cursor3.jpg](https://bugs.openttd.org/task/6319/getfile/10297/cursor3.jpg) (109.69 KiB)
- [cursor4.jpg](https://bugs.openttd.org/task/6319/getfile/10298/cursor4.jpg) (108.94 KiB)
- [DxDiag.txt](https://bugs.openttd.org/task/6319/getfile/10299/DxDiag.txt) (41.35 KiB)

**Reported version**: _1.5.1_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_3dmaxb00n_ wrote:**

> Sorry for confusing you but I have to correct a fact I gave you.
> 
> I retried lowering the values for the g500 but the mouse still flickers very heavily when moving. Even on 200dpi and 125 signals per second (lowest values for g500).

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6319#comment13976_

**Comment by TrueBrain** [comment]
3 years later. No other reports. Sorry, going to close the ticket. Feel free to reopen if you feel it is just.
