### ISSUE TITLE
Mapgen: no tropical trees and no snow with default world generation settings

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6337]
**_canaaerus_ opened the ticket and wrote:**

> The current default world generation settings are a maximal map height of 30 and a snow line height of 15, while tropical tree line height is calculated automatically based on the maximal map height and can not be set, afaik.
> In effect in sub-arctic there is no snow and in sub-tropic there are no tropical trees except at the coast-line, when using the default settings.
> 
> For sub-arctic setting the snow line height to 5 provides sufficient snow and
> for sub-tropic setting the maximal map height to the historic value 15 gives tropical forests.

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> In r27334, changes to the terrain generator were reverted.
> Does that fix your problem?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6337#comment14025_

**Comment by DorpsGek** [comment]
**_canaaerus_ wrote:**

> I tested the current trunk r27346 and the issue was still there. I think this is not related to the noise generation, but only to the height limits.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6337#comment14026_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Confirmed, if I remove openttd.cfg and start OpenTTD 1.7.1, using default world gen settings
> \- no snow in sub-arctic
> \- no trees in sub-tropic

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6337#comment14598_

**Comment by LordAro** [comment]
Confirmed with master as of this date

**Comment by LordAro** [comment]
Still an issue, though can largely be summed up as "Terragenesis generates really flat maps"
