### ISSUE TITLE
Stations: difficult to locate parts of spread stations

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6339]
**_kolcon_ opened the ticket and wrote:**

> When you build a "spread" station (with Ctrl, meaning individual parts of the station are not adjacent, but further apart),
> 
> it is difficult to locate all the parts on the map.
> 
> The problem is that the parts can be up to 64 squares apart, "somewhere", and the game does not allow their easy finding.
> 
> Suggestion: Multiple clicks on the "Location" button should cause the map to jump around all parts of the station.

**Reported version**: _1.5.1_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
Very good idea!

That said, in terms of priority it is very low, so I am going to close this issue for now.

If anyone makes a Pull Request for this, we are more than happy to accept it.
