### ISSUE TITLE
positioning of train vehicle sprites

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6357]
**_mb_ opened the ticket and wrote:**

> Positioning of train vehicle sprites is all a mess in the diverse windows/lists.
> 
> Granted, since varAction2 var10 (display different sprites in GUI), this can be worked around, changing it from a bug into an inconvenience. However, why should a newGRF provide 4 identical sprites (only differing in y-position) to compensate for the different base y-coordinate in the diverse windows/lists?
> 
> E.g., to position a simple rail car with repect to the same y-position it needs 3 (or even 4, incl the purchase menu) identical sprites, only different in y:
> 
> [code]
> // test all those different offsets in the various windows/lists
> spriteblock(
> // Depot
>   set(
>     sprite(db# vt95.pcx 226 8 01 11 28 -14 -7)
>   )
> // Details/refit
>   set(
>     sprite(db# vt95.pcx 226 8 01 11 28 -14 -9)
>   )
> // Liste
>   set(
>     sprite(db# vt95.pcx 226 8 01 11 28 -14 -8)
>   )
> )
> [/code] 
> 
> In addition, some windows show silly assumptions with regards to vehicle sprite placement. E.g. the train details window reserves 4 rows of empty pixels above the text (see pic), unnecessarily (in a rather low-ceilinged box), only to clip the sprite on its bottom when being shifted downwards. Etc, pp.
> 

**Attachments**
- [position.png](https://bugs.openttd.org/task/6357/getfile/10345/position.png) (6.40 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> I am +0.5 to this, having to chase down these different views is inconvenient yak-shaving.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6357#comment14057_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> #6318 is related; I would rather see the need to use var 10 removed by fixing the issue at root cause, then #6318 closed as "won't fix".
> 
> However fixing the issue at root cause might be a nest of snakes w.r.t backwards compatibility.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6357#comment14664_

**Comment by TrueBrain** [comment]
I was about to ask .. doesn't fixing this cause all current NewGRFs to break? But if it is about removing something, backwards compatibility is easier.

This ticket will be far from easy, but it sounds really silly, so solving it should be on some list.

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
