### ISSUE TITLE
Orders: 'max reliability' order filter

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6360]
**_Simons_Mith_ opened the ticket and wrote:**

> I set up orders to make vehicles go to depot and stop when they passed their maximum age.
> But what I really wanted to do was to send vehicles to depot when their /maximum reliability
> after servicing/ dropped too low.
> 
> So in the interests of 'do what you mean'*, instead of
> 
> 'Jump to order 7 when Remaining lifetime (years) is less than 0'
> 
> I would like to use
> 
> 'Jump to order 7 when Maximum reliability is less than 50'
> 
> But maximum reliability/reliability after servicing doesn't exist as an order filter. Could it be
> added?
> 
> 
> \* 'Do what you mean' - in programming, when you want a computer to do x, always try to tell
> it directly to do x, rather than telling it to do something else that indirectly causes it to do x.
> Helps with debugging and improves code clarity.

**Reported version**: _1.5.1_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_chindit_ wrote:**

> I've created a patch.
> Tested and functional with road vehicles.
> I'm testing it with train and planes but it normally works fine.

**Attachments**
- [max_reliability.diff](https://bugs.openttd.org/task/6360/getfile/10355/max_reliability.diff) (6.12 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6360#comment14046_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Patch compiles on r27910.
> 
> Appears to work as expected, in my brief testing.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6360#comment14731_

**Comment by andythenorth** [comment]
Now that we're on github, this would be better handled as a pull request :)  

(Assuming it meets code standards) :)

**Comment by andythenorth** [comment]
Closing as done, thanks all :)
