### ISSUE TITLE
Bananas: name is truncated in in-game content downloader

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6389]
**_dpk_ opened the ticket and wrote:**

> The name of my scenario is "dpk’s UK and Ireland Map (1900)". On the website this is displayed fine, but in game it's truncated to "dpk’s UK and Ireland Map (190".

**Attachments**
- [NesflWn.png](https://bugs.openttd.org/task/6389/getfile/10401/NesflWn.png) (74.38 KiB)

**Reported version**: _1.5.2_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Zuu_ wrote:**

> The reason for this is that ContentInfo::name is limited to 32 characters. This is also the number of characters OpenTTD receives from the content server.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6389#comment14082_

**Comment by DorpsGek** [comment]
**_dpk_ wrote:**

> Then the limit should be made larger, or the content service upload system should warn you about this, or (even better) forbid you from uploading things with names longer than that.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6389#comment14083_

**Comment by DorpsGek** [comment]
**_Eearslya_ wrote:**

> The problem is actually a little more complex; your scenario's name is only 31 characters long, but the apostrophe used is a special UTF-8 character that takes up 3 bytes instead of 1. The web frontend accepted it as one character, but the actual server and game code still use the UTF-8 apostrophe, causing it to be 33 characters, and thus truncated.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6389#comment14084_

**Comment by DorpsGek** [comment]
**_dpk_ wrote:**

> Then the server and game code should count Unicode codepoints for the limit, not bytes. (Incidentally, what happens if a UTF-8 codepoint is split in the middle by the truncator?)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6389#comment14086_

**Comment by DorpsGek** [comment]
**_Eearslya_ wrote:**

> Unfortunately, that's just not how C++ works. Not without throwing the string through a UTF-8 -> ASCII parser, at least. The strings are all stored as null-terminated byte arrays. And if it did happen to truncate in the middle of a UTF-8 character, it would probably either render a garbage character, or nothing at all for that byte.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6389#comment14089_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Confirmed OP's report in r27903

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6389#comment14662_

**Comment by TrueBrain** [comment]
How C++ should be irrelevant for the user. It is weird that we limit on UTF8 on the website, and on ANSII ingame. One of the two has to give, to make a consistent experience.

That said, there is not a simple solution for this problem.
- Changing the network protocol is far from an easy task; especially if we talk about making a single instance bigger.
- Changing BaNaNaS is not something anyone would like to touch in its current state.

I think this should be tackled when-ever BaNaNaS is replaced; so I am tempted to pass on this. @andythenorth what do you think?

**Comment by andythenorth** [comment]
Pass on this.  In a better Bananas, it should be relatively easier I hope.
