### ISSUE TITLE
Keep town growth rate in sync with house count

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6397]
**__dp__ opened the ticket and wrote:**

> I had this thing on my mind for quite a while, but separation of growth rate from growth flag I did for #6378 makes it a lot easier.
> 
> Right now town growth rate is normally updated only once a month. This have a nasty side-effect of town growth speed being influenced by game date. It's especially troublesome in citybuilder. For example, imagine two cities that are very close on growth, just one is a day behind the other. At some point they switch from growing 1 house in 2 days to 1 house every day. But first city does it on 31 dec and second would've done it on 1 jan but because of monthly update it only gets it on 1 feb. So, suddenly, on 1 feb first city is 15 houses larger than second one only because it was lucky to get its growth changed before the new month.
> 
> So instead of monthly updates this patch keeps town growth rate in sync with house count. It is supposed to be applied on top of my patch for #6378.
> 

**Attachments**
- [town-house-count-sync-growth-rate.diff](https://bugs.openttd.org/task/6397/getfile/10419/town-house-count-sync-growth-rate.diff) (1.84 KiB)

**Reported version**: _1.5.3-RC1_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
I missed that this was merged already, cleaning labels and closing.  Thanks for contributing!
