### ISSUE TITLE
Fails to download online content when ~/.local/share does not exist

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6399]
**_matthijs_ opened the ticket and wrote:**

> It seems that when downloading things through the online content user interface, and ~/.local/share does not exist, the download fails with a "file not writable" error.
> 
> strace shows that it tries to open up the final filename right away, which obviously fails:
> 
> open("/root/.local/share/openttd/content_download/baseset/OpenSFX-0.2.3.tar.gz", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 ENOENT (No such file or directory)
> 
> No mkdir calls happen at all (not even inside ~/.local/share, interestingly). When ~/.local/share *does* exist, mkdir calls do happen, but only inside ~/local.share. In this case, there is also a failed mkdir for ~/.config/openttd, so there is presumably also a problem for a non-existing ~/.config directory.
> 
> This problem was observed on version 1.5.3 and 1.4.4, on a Debian Sid and Jessie system respectively.
> 
> In addition, the automatic OpenGFX download (when no gfx are available) fails when ~/.local/share does not exist, though an additional problem is that no error (just a download dialog that gets shown for a fraction of a second, then disappears leaving an empty window).

**Reported version**: _1.5.3_
**Operating system**: _Linux_

---

**Comment by Wirdal** [comment]
I'd like to tackle this.

I haven't looked through the code much, so I will ask, where is the  online content user interface defined?

**Comment by nielsmh** [comment]
I'd start with [src/network/network_content.cpp](https://github.com/OpenTTD/OpenTTD/blob/master/src/network/network_content.cpp), there is also a network_content_gui.cpp, and matching .h files.

**Comment by Wirdal** [comment]
OK, thanks. I'll poke around.

Might take a while, I am on the home stretch of finals. So if anyone else wants to work on this, go for it.

**Comment by sdcloudt** [comment]
I could not reproduce this issue in the current upstream version of openttd (1.9.+ something) on my Arch Linux system.

First of all, downloaded content is stored in `~/.openttd` not in `~/.local/share/openttd` on my system. Secondly, deleting this `~/.openttd` directory also does not trigger any errors, the directory is just created as expected.

I am not aware of the policy around fixing bugs in old versions.
