### ISSUE TITLE
Crash: ctrl-clicking a factory type in map

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6400]
**_TiozinNub_ opened the ticket and wrote:**

> Operating system: Windows 7 Ultimate (Service Pack 1)
> NewGRFs:
>   Brazilian Names 2.0
>   FIRS Industry Replacement Set 1.4.4M
>   Original vehicles cargo set
> 
> Obs.: I play in Portuguese(Brazil)
> 
> I Ctrl-Clicked the "Quarry" button in the map and the game simply crashed.

**Attachments**
- [TiozinNub Co., Jun 4th, 2012.sav](https://bugs.openttd.org/task/6400/getfile/10423/TiozinNub+Co.%2C+Jun+4th%2C+2012.sav) (894.64 KiB)
- [crash.sav](https://bugs.openttd.org/task/6400/getfile/10424/crash.sav) (895.62 KiB)
- [crash.log](https://bugs.openttd.org/task/6400/getfile/10425/crash.log) (8.84 KiB)
- [crash.dmp](https://bugs.openttd.org/task/6400/getfile/10426/crash.dmp) (6769.86 KiB)
- [crash.png](https://bugs.openttd.org/task/6400/getfile/10427/crash.png) (171.17 KiB)

**Reported version**: _1.5.2_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Information from crash.dmp:
> 00000000\`0016e1a0 00000001\`3f49714a : 00000000\`00000001 00000000\`0016e5d0 00000000\`2838b4e0 00000000\`00000000 : openttd!icu_51::ParagraphLayout::previousBreak+0x10a
> 00000000\`0016e390 00000001\`3f17fc18 : 00000000\`2a7f4ca0 00000000\`76fb1a7a 00000000\`05111310 00000000\`00000000 : openttd!icu_51::ParagraphLayout::nextLine+0x9a
> 00000000\`0016e3c0 00000001\`3f180ec6 : 00000000\`0016e5e3 00000000\`00000010 00000000\`2751a5e0 00000000\`00000000 : openttd!ICUParagraphLayout::NextLine+0x24 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\gfx_layout.cpp @ 182]
> 00000000\`0016e400 00000001\`3f17c3d1 : 00000000\`0016e588 00000000\`0016e5e4 00000000\`7fffffff 00000001\`00000010 : openttd!Layouter::Layouter+0x8fe [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\gfx_layout.cpp @ 680]
> 00000000\`0016e550 00000001\`3f17c45f : 00000000\`0000025e 00000000\`2527b800 0000000a\`00000000 00000000\`00000000 : openttd!GetStringBoundingBox+0x31 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\gfx.cpp @ 700]
> 00000000\`0016e5b0 00000001\`3f1d6beb : 00000000\`00000086 00000000\`0016ee48 00000000\`2751a5e0 00000000\`27519ee0 : openttd!GetStringBoundingBox+0x27 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\gfx.cpp @ 716]
> 00000000\`0016ede0 00000001\`3f1d3fa3 : 00000000\`2751a5e0 00000000\`2527b8c0 00000000\`00000000 00000000\`0016ef08 : openttd!NWidgetLeaf::Draw+0x137 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\widget.cpp @ 2445]
> 00000000\`0016ee90 00000001\`3f1d3f38 : 00000000\`27c944c0 00000000\`00000016 00000000\`00000539 00000000\`00000000 : openttd!NWidgetPIPContainer::Draw+0x1f [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\widget.cpp @ 1112]
> 00000000\`0016eec0 00000001\`3f1d3fa3 : 00000000\`00000249 00000000\`2a7f6240 00000000\`2527b8c0 00000000\`2527b8c0 : openttd!NWidgetStacked::Draw+0x48 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\widget.cpp @ 1063]
> 00000000\`0016eef0 00000001\`3f1d3fa3 : 00000000\`27c91dd0 00000000\`2527b8c0 00000000\`2527b8c0 00000000\`27519e60 : openttd!NWidgetPIPContainer::Draw+0x1f [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\widget.cpp @ 1112]
> 00000000\`0016ef20 00000001\`3f1d3f38 : 00000000\`27c97080 00000000\`2527b8c0 00000000\`2761fa50 00000000\`285208e0 : openttd!NWidgetPIPContainer::Draw+0x1f [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\widget.cpp @ 1112]
> 00000000\`0016ef50 00000001\`3f1d3fa3 : 00000000\`27c91820 00000001\`3f1d3f38 00000000\`2761b680 00000000\`285208e0 : openttd!NWidgetStacked::Draw+0x48 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\widget.cpp @ 1063]
> 00000000\`0016ef80 00000001\`3f1d37d0 : 00000000\`0016f0c0 00000001\`3f1d3fa3 00000000\`2761b4c0 00000001\`3f1eff1e : openttd!NWidgetPIPContainer::Draw+0x1f [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\widget.cpp @ 1112]
> 00000000\`0016efb0 00000001\`3f1d9cee : 00000000\`0000000b 00000000\`0016f0c0 00000000\`2527b8c0 00000000\`00000000 : openttd!Window::DrawWidgets+0x2c [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\widget.cpp @ 607]
> 00000000\`0016f010 00000001\`3f1d9c59 : 00000000\`0000026c 00000000\`2527b8c0 00000000\`00000000 00000000\`0000026c : openttd!DrawOverlappedWindow+0x136 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\window.cpp @ 922]
> 00000000\`0016f050 00000001\`3f17d2a4 : 00000000\`2527b8c0 00000000\`000000a8 00000000\`000001e8 00000000\`00000280 : openttd!DrawOverlappedWindow+0xa1 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\window.cpp @ 886]
> 00000000\`0016f090 00000001\`3f17d46f : 00000000\`00000580 00000000\`000000a8 00000000\`000002c8 00000000\`259bcbae : openttd!RedrawScreenRect+0xd8 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\gfx.cpp @ 1292]
> 00000000\`0016f0f0 00000001\`3f1dcec5 : 00000000\`00000016 00000000\`00000000 00000000\`0016f301 00000000\`00479241 : openttd!DrawDirtyBlocks+0x183 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\gfx.cpp @ 1384]
> 00000000\`0016f140 00000001\`3f3b041a : 00000000\`00479200 00000000\`00479241 00000000\`00000000 00000001\`3f3af2cc : openttd!UpdateWindows+0x179 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\window.cpp @ 3053]
> 00000000\`0016f170 00000001\`3f1a69a1 : 00000000\`00000000 00000000\`0016f300 00000000\`00000000 00000000\`00000000 : openttd!VideoDriver_Win32::MainLoop+0x402 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\video\win32_v.cpp @ 1298]
> 00000000\`0016f200 00000001\`3f3b2a3d : 00000000\`00000000 00000000\`0016f530 00000000\`00000001 00000000\`00000000 : openttd!openttd_main+0xec1 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\openttd.cpp @ 865]
> 00000000\`0016f510 00000001\`3f49edc0 : 00000000\`00000000 00000000\`00000000 00000000\`00000000 00000000\`00000000 : openttd!WinMain+0x141 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\os\windows\win32.cpp @ 457]
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6400#comment14103_

**Comment by andythenorth** [comment]
Thanks. ICU has known issues, and there is a project underway to replace it. We're not keeping the reports relating to it open, but they can still be found here as and when they are needed. Thanks for the report and diagnosis efforts.
