### ISSUE TITLE
railtype - depot - snow

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6407]
**_mb_ opened the ticket and wrote:**

> The railtype feature doesn´t allow for depots showing snowy ground sprites. Although, in snowy terrain, a snowy ground sprite (4550) is in use, there is always also a non-snowy ground sprite (3891) being placed upon the former. 

**Attachments**
- [depot_snow.png](https://bugs.openttd.org/task/6407/getfile/10435/depot_snow.png) (20.09 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> To confirm - railtype var 40 is being checked for the example in your screenshot?
> 
> I can try and repro this, but I will have to patch Termite (railtype grf I maintain) first.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6407#comment14708_

**Comment by DorpsGek** [comment]
**_mb_ wrote:**

> Yeah, that´s why it shows a snowy roof.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6407#comment14715_

**Comment by andythenorth** [comment]
See also #6222 - may or may not have a similar cause.

**Comment by jcoletto77** [comment]
I'm adding snowy depots on my trackset (French narrow gauge) and this issue is really getting in the way. The final effect of having snow on the roofs, but not on the ground, is quite weird.
Could you please see if it's possible to fix?
