### ISSUE TITLE
Signals: confusing concept (wording): "Signal density"

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6408]
**_juanjo_ opened the ticket and wrote:**

> This is not a bug report. It is a suggestion in order to revise the wording of some strings.
> 
> STR_BUILD_SIGNAL_DRAG_SIGNALS_DENSITY_TOOLTIP:          {BLACK}Dragging signal density
> STR_BUILD_SIGNAL_DRAG_SIGNALS_DENSITY_DECREASE_TOOLTIP: {BLACK}Decrease dragging signal density
> STR_BUILD_SIGNAL_DRAG_SIGNALS_DENSITY_INCREASE_TOOLTIP: {BLACK}Increase dragging signal density
> 
> While translating those, I found the concept "density" difficult and confusing. "Decrease density" means decreasing the space between signals, and thus increase the amount (and density) of signals in the involved tiles.
> 
> I understand that they mean something like:
> "Distance between signals{}When placing rail signals while dragging the mouse or holding Ctrl pressed, they will be separated at this distance"
> "Decrease/Increase the distance between two consecutive signals"
> 
> This way, the strings are easier to understand in Catalan. Changing them in the base language is not so easy, as it may involve changing some other lines of the source code of OpenTTD.
> 
> 
> 

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
Fully agree the wording is weird.
