### ISSUE TITLE
Auto-pan window minor issue

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6412]
**_Jubilee_ opened the ticket and wrote:**

> Game settings / Interface / Viewports. The "Pan window..." setting is set to "Main viewport". When the mousepointer reaches the edge of the window, the viewport automatically scrolls to that direction EXCEPT... when it is at the toolbar at the top of the screen, it does not scroll (which is logical since all the buttons that control the game are there - if scrolling occurred while over there, let's say it would not be good). This however also happens at the bottom where the status bar exists. When the mousepointer is at the bottom of the screen and over the statusbar, no scroll happens. If the pointer however is placed at a distance between 1 and 3 pixels above the statusbar, autoscrolling occurs. Buttons in the statusbar are clickable, so i guess autoscroll would not be a good idea when over there but this area of 2-3 pixels above it should not autoscroll either. It's a little confusing. Also, perhaps a modifier (i.e. shift down) could force-enable auto-scroll even above the status/button bars at bottom and top of screen.

**Reported version**: _1.5.3_
**Operating system**: _Windows_

---

**Comment by TrueBrain** [comment]
I agree that "pan window" can be a bit confusing, but there are also limited means of doing it right. But I do not see a bug here. At best a feature request to overhaul it completely (there are better modern solutions for this; but something like shift etc would also really help).

I don't see a priority in this request, so closing the issue for now. Tnx for the report!
