### ISSUE TITLE
Add option to ignore local authorities opinion

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6416]
**_Milek7_ opened the ticket and wrote:**

> Patch for trunk in attachment

**Attachments**
- [ignore_local_authorities.patch](https://bugs.openttd.org/task/6416/getfile/10441/ignore_local_authorities.patch) (4.82 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Milek7_ wrote:**

> fixed indentation and added some comments

**Attachments**
- [ignore_local_authorities.patch](https://bugs.openttd.org/task/6416/getfile/10442/ignore_local_authorities.patch) (5.25 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6416#comment14116_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Why are you adding a new setting instead of using the existing "town council attitude" one? 
> (Current values: permissive, tolerant, hostile; new value: submissive/cheating)
> 
> What is the meaning of the existing one, when disabling via the new setting?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6416#comment14117_

**Comment by DorpsGek** [comment]
**_Milek7_ wrote:**

> It was just easier to add this, and I do not want to mess with other code. With this setting the rating calculation stays working, but it is not checked when destroying/building station. When adding an extra option to "town council attitude" it should completlely remove rating calculation, visiblity in "Local authorities" window and bribing function.
> 
> If it is important to not add new setting, i can submit new patch.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6416#comment14118_

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> It's not just important, it's a hard requirement. New code must be fully integrated into the code base.
> 
> You don't want to have multiple settings to achieve one thing (eventually leading to set this option to "yes", that one to "ignore other one", and the the third one to "yes").

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6416#comment14125_

**Comment by DorpsGek** [comment]
**_Milek7_ wrote:**

> No, this patch don't make multiple settings to achieve one thing. It disables blocking capabilities of local authority, but no whole rating calculation.
> Copy-paste from irc:
> <Milek7> while disabling rating calculation, what value use in GSTown.GetRating?
> <Milek7> ignoring don't breaks anything, disabling can broke something relying on that
> <Milek7> and it even shouldn't be disabled, because gamescript using town rating to calculate growth is very good
> <Milek7> but this patch is for that local authority can't block building/destroying
> <Milek7> not disabling rating completly

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6416#comment14127_

**Comment by DorpsGek** [comment]
**__dp__ wrote:**

> I think main source of confusion here is that town_council_tolerance affects multiple things:
> 1) Max town noise level
> 2) Speed of noise level reduction with distance
> 3) Min rating required for demolishing stuff in town
> Also, notably, it does NOT affect
> 4) Town rating calculation (and thus cb scripts)
> 5) Min rating for placing stations (that's always RATING_VERYPOOR)
> 
> And main issue with authority rating is it's blocking behavior (3 and 5).
> So I'd suggest splitting airport noise in separate setting and making tolerance affect station placement.
> That way adding ignorant/cheating attitude will allow to disable blocking aspect without breaking anything else.
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6416#comment14128_

**Comment by DorpsGek** [comment]
**__dp__ wrote:**

> Oh, and also ignoring 3 should be removed from magic bulldozer effects imo if this is implemented.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6416#comment14129_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> This is IMHO a boring thing to add to the core game.  
> 
> The local authority mechanic is a core mechanic of the original gameplay.  
> 
> Completely nerfing it is really dull.  
> 
> Does that matter?  
> 
> Yes.
> 
> Patches need reviewed and tested before they can be committed.
> 
> That's work.
> 
> Working on dull things is...dull.
> 
> So dull things have very low chance of getting done.
> 
> Even if there were 50 people with commit rights, this wouldn't change.  
> 
> Nobody wants to be the one adding dull stuff.
> 
> Nobody wants 49 other people asking 'wtf did you do that for?'
> 
> So eh.
> 
> Town ratings have long been a problem. 
> 
> Is there a better way? :)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6416#comment14743_

**Comment by TrueBrain** [comment]
This sounds more like a cheat than anything else. I do not see a need for this in the core game currently. Sorry, but thank you for the patch!
