### ISSUE TITLE
GSTile.GetTownAuthority not accounts town growth

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6417]
**_Milek7_ opened the ticket and wrote:**

> GSTile.GetTownAuthority returns not the town which has authority for the tile, but closest town with maximum distance _settings_game.economy.dist_local_authority. It should use instead cache.squared_town_zone_radius[0] for each town.
> 
> Propably related with that terrain information tool shows "Local authority" field wrong in grown up towns.

**Reported version**: _1.5.3_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
Reverse lookups are always a bit tricky.

**Comment by Milek7** [comment]
It actually works correctly, I was confused by influence of stations on local authority ratings (which are assigned just by distance, ignoring any town sizes and authority ranges)
To close.

**Comment by andythenorth** [comment]
Thanks @Milek7 for checking :)
