### ISSUE TITLE
Game Script: Expose cache.squared_town_zone_radius[0] in GSTown

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6420]
**_Milek7_ opened the ticket and wrote:**

> Currently there is no way to check city radius after growth.

**Reported version**: _1.5.3_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
Please start your issue with why you would like this (besides for the fact of having it). I am a bit puzzled what this would help.

Going to close this issue for now (given it is 2 years old); please (re)open if you feel this is still needed and give us a use case of how you would use it. Tnx!
