### ISSUE TITLE
[patch] GS function to scroll viewport for all players in company

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6422]
**__dp__ opened the ticket and wrote:**

> Basically, a multiplayer analogue of GSVewport.ScrollTo, useful when gs want players to focus on some important event or place.
> I would use it in CB script to scroll players to claimed town when they join or start company.
> 
> 

**Attachments**
- [gs-scroll-company-clients-to.diff](https://bugs.openttd.org/task/6422/getfile/10443/gs-scroll-company-clients-to.diff) (4.68 KiB)
- [testscroll.tar.gz](https://bugs.openttd.org/task/6422/getfile/10444/testscroll.tar.gz) (0.77 KiB)

**Reported version**: _1.5.3_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
Done?

**Comment by andythenorth** [comment]
My understanding is that this issue is now closed by https://github.com/OpenTTD/OpenTTD/pull/6745 Good news :)
