### ISSUE TITLE
re-cache vehicle properties in depot

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6423]
**_George_ opened the ticket and wrote:**

> R27507
> 
> In xUSSR set I use code like this
> 
> switch (FEAT_TRAINS, SELF, e_e_power, date_of_last_service >= date(1920,1,1))
> {
>   0: return get_power_in_cb(1100);  
>      return get_power_in_cb(1306);
> }
> 
> It is intended, that when a train visits a depot after specified day, it changes the power to the new value (got automatically upgraded).
> Unfortunately, the game changes the power not in depot, but several days later. I suppose, it caches the value and updates the cache while the train is outside depot.
> It would be nice, if visiting the depot would force properties recache, guaranteeing that a change happens in depot. 

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_George_ wrote:**

> related task
> https://bugs.openttd.org/task/6249 - the same for leaving the station

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6423#comment14120_

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> I guess this can cause a desync currently. Is it sane to refresh when leaving depots?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6423#comment14386_

**Comment by TrueBrain** [comment]
That is a pretty big jump, thinking it might cause a desync? (it changes priority of these tickets). Could you please supply more context if you make this claim?
