### ISSUE TITLE
[Windows] Touch support on windows tablets

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6425]
**_c933103_ opened the ticket and wrote:**

> I downloaded openttd onto my windows 8 tablet, but can't use touch screen to move around in the map like the android version, and it can be expected to have many similar problems in further gameplay. Since android version already have touch support can windows version have these support too?

**Reported version**: _1.5.3_
**Operating system**: _Windows_

---

**Comment by TrueBrain** [comment]
Android is not officially supported by OpenTTD. You most likely found a fork which added support for this.

**Comment by TrueBrain** [comment]
Not on the current roadmap for OpenTTD.
