### ISSUE TITLE
[Windows] RTL bug OpenTTD 1.6.0-RC1

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6427]
**_Yoseflm13_ opened the ticket and wrote:**

> How it look in 1.5.3 (this how it shold work)
> and how in look in 1.6.0-RC1(work like LTR lang like english)
> 

**Attachments**
- [OpenTTD_1_6_0_RC1-LTR-NEED-TO-BE-RTL2.PNG](https://bugs.openttd.org/task/6427/getfile/10447/OpenTTD_1_6_0_RC1-LTR-NEED-TO-BE-RTL2.PNG) (633.35 KiB)

**Reported version**: _Version?_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_dnd_man_ wrote:**

> Yes, same is happening here.
> text alignment is LTR istead of RTL, resulting in a flipped text.

**Attachments**
- [capture.PNG](https://bugs.openttd.org/task/6427/getfile/10479/capture.PNG) (3.05 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6427#comment14154_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> It looks correct on linux.
> 
> Likely causes by compiling OpenTTD with a new libICU.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6427#comment14158_

**Comment by DorpsGek** [comment]
**_frosch_ closed the ticket.**

**Reason for closing: _Fixed_**

> in r27542

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6427_

**Comment by MosheL** [comment]
I see this bug on 1.8 @ windows.

![image](https://user-images.githubusercontent.com/2265043/45484726-cdf49580-b75d-11e8-9196-2341cf07b39f.png)

**Comment by LordAro** [comment]
Likely a ICU issue, which is no longer used on Windows after 1.8 - it's been switched out with Uniscribe

If you're able to (because we've not got nightlies running again yet), are you able to test with the latest trunk/master, to see if it's still an issue?

**Comment by MosheL** [comment]
Hi, I can't compile it. waiting for nightlies.

**Comment by nielsmh** [comment]
I posted a recent build here, that should use ICU, try this one: https://www.tt-forums.net/viewtopic.php?f=33&t=83554#p1214289

**Comment by MosheL** [comment]
working. thanks

**Comment by nielsmh** [comment]
Solved by #6798
