### ISSUE TITLE
Allow overriding default-generated compiler flags.

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6433]
**_adf88_ opened the ticket and wrote:**

> The 'configure' script generates some flags for the compiler (CFLAGS, CXXFLGAS etc.). Also users can add their own flags by passing them to the script. However, user flags have lower priority because automatic flags are added behind them. It means that it is not possible to override the auto-generated flags e.g. it is not possible to turn off some '-Wxxx' if 'configure' script decides to use it.
> 
> If auto-generated flags were put before user flags this would not be a problem anymore. While users have full control on what flags they pass to the script, they have limited control on what flags will be generated automatically.
> 
> Patch attached (-p0).
> 

**Attachments**
- [allow-overriding-default-generated-build-flags-r27523.diff](https://bugs.openttd.org/task/6433/getfile/10459/allow-overriding-default-generated-build-flags-r27523.diff) (1.46 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
Now that we're on github, this would be good to handle via a pull request.
