### ISSUE TITLE
Localization of company and president name

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6434]
**_juanjo_ opened the ticket and wrote:**

> OpenTTD automatically generates names such as:
> "K. K. Jones" and "Wenway Transport"
> It would be great if they could be generated depending on the selection of "Town Names".

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_dnd_man_ wrote:**

> Also, if it's possible, can you provide source of optional names (one for each language) so the names will be created from that file?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6434#comment14155_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Seems fair, my assumption here is this would need an extension to newgrf spec.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6434#comment14564_

**Comment by nielsmh** [comment]
Generating a company name from a town name can possibly give grammatical issues in some languages, I think certain town names can have varying grammatical genders, and then there's outliers like _den Haag_.

Additionally, should this be entirely a NewGRF feature, or should it have some default tables for the built-in town name tables? I think the latter would be more appropriate.

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
