### ISSUE TITLE
raising/lowering 'Maximum no. competitors' setting in multiplayer

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6438]
**_Samu_ opened the ticket and wrote:**

> The bug happens when the AI/Game script Configuration window is brought up this way:
> 
> 1 - Launch OpenTTD
> 2 - Click multiplayer
> 3 - Start server
> 4 - Click new game
> 5 - Click Options > AI/Game script Configuration
> 
> Bugs:
> \- if the value is 14: when clicking '<' to lower it to 13, the '>' can't be clicked to raise it to 14, unless lowered to 12
> \- if the value is 13: when clicking '>' to raise it to 14, the '>' can be clicked, but it shouldn't. Clicking it fixes itself
> \- if the value is 0: when clicking '>' to raise it to 1, the '<' can't be clicked to lower it to 0, unless raised to 2
> \- if the value is 1: when clicking '<' to lower it to 0, the '<' can be clicked, but it shouldn't. Clicking it fixes itself 

**Reported version**: _1.6.0_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_Samu_ wrote:**

> you sure? I just reproduced it in 1.7.2

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6438#comment14844_

**Comment by DorpsGek** [comment]
**_Samu_ wrote:**

> proof

**Attachments**
- [Unnamed, 1935-02-15.png](https://bugs.openttd.org/task/6438/getfile/10975/Unnamed%2C+1935-02-15.png) (54.47 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6438#comment14845_

**Comment by DorpsGek** [comment]
**_Wolf01_ wrote:**

> Reopened: reproduced in r27967

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6438#comment14846_

**Comment by GabdaZM** [comment]
I found that when you click on the '<' or '>' buttons to change the number of the competitors, the value won't get updated on the client, but sent to the server. The server registers the update and sends the new number back to the client, but it only updates the text on the screen, but it won't call a button invalidations, so only a part of the window gets updated. (If you click on other functioning parts of the window, the arrow button validation will be updated.)
While it would be easy to store the modification of the number on the client as well, I think it would only be a workaround, as in case another client modifies this number while this window is open in our client as well (and the number gets 0 or 14) only the number will be updated and not the button invalidation.
