### ISSUE TITLE
Aircraft will not move if company is bought while displaying "too far to next destination"

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6439]
**_donchatryit_ opened the ticket and wrote:**

> Hi there,
> 
> During one recent game, I bought over an AI so I could get their airports. What I didn't realise was they they still had two aircraft on the ground, displaying the "Too far to next destination" message. As they had no airports within range, I send both aircraft to their depots. They still displayed the same flag and didn't move.
> 
> I think deleted all their orders, replacing them with orders to go to their nearest depot and stop. They didn't move and displayed the same flag. Is this a known bug? Save file and screen cap attached.

**Attachments**
- [Greatwood.sav](https://bugs.openttd.org/task/6439/getfile/10466/Greatwood.sav) (521.93 KiB)
- [Dunby Transport, 3rd Dec 2017.png](https://bugs.openttd.org/task/6439/getfile/10467/Dunby+Transport%2C+3rd+Dec+2017.png) (512.85 KiB)

**Reported version**: _1.5.3_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_hackalittlebit_ wrote:**

> This patch will solve the problem
> Problem is Pikka's airplane patch that use distance limits.

**Attachments**
- [r27530 release stuck airplanes.patch](https://bugs.openttd.org/task/6439/getfile/10482/r27530+release+stuck+airplanes.patch) (8.33 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6439#comment14159_

**Comment by DorpsGek** [comment]
**_hackalittlebit_ wrote:**

> I did not really have time to look at it.
> I got it out of my waypoint air patch
> I will have a look at it to improve it for trunk.
> 
> It happened to me also when loading Pikka's airplane newgrf.
> He uses distance limits and all planes got stuck.
> This plane will release airplanes stuck on the platform.
> Duno if this is what you want.
> 
> You don't allow me to delete files, so it is the last patch.
> Don't ask me what happened????
> regards ;-)
> 

**Attachments**
- [r27530 release stuck airplanes.patch](https://bugs.openttd.org/task/6439/getfile/10483/r27530+release+stuck+airplanes.patch) (8.33 KiB)
- [r27530 release stuck airplanes.patch](https://bugs.openttd.org/task/6439/getfile/10484/r27530+release+stuck+airplanes.patch) (8.33 KiB)
- [Release stuck airplane_this one.patch](https://bugs.openttd.org/task/6439/getfile/10485/Release+stuck+airplane_this+one.patch) (0.58 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6439#comment14160_

**Comment by DorpsGek** [comment]
**_hackalittlebit_ wrote:**

> If you click 'send to hangar' plane starts moving. (unpause game)
> With clean trunk!

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6439#comment14161_

**Comment by DorpsGek** [comment]
**_hackalittlebit_ wrote:**

> Here a savegame that I made after big clean.
> Delete openttd.cfg before starting game -d0 mode.
> 25 march plane 1 (dunby transport) from still stuck.
> on 1 of april plane suddenly starts moving. (after autosave)
> Trunk 27539
> Hope this helps

**Attachments**
- [Dunby Transport, 25 Mar 2018.sav](https://bugs.openttd.org/task/6439/getfile/10486/Dunby+Transport%2C+25+Mar+2018.sav) (92.09 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6439#comment14162_

**Comment by andythenorth** [comment]
Thanks for this.  

Based on comments from hackalittlebit 18 Apr 2016, this issue can be worked around. 

So at the time of writing this appears to be an isolated bug, and hard to reproduce.  We do try to address bugs where they occur frequently and/or are easy to reproduce, but this one doesn't look like we can any go further, so I'm closing it.  Thanks for contributing!
