### ISSUE TITLE
Crash: MP game (with emergency save)

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6440]
**_Samu_ opened the ticket and wrote:**

> Windows 10 Pro 64-bit
> 
> I am hosting 8 servers. Each server instance are set up on different folders. Each openttd.exe file has been converted with an utility glx provided: convert.exe
> 
> I am also spectating all my servers, but for this, I am using the same openttd.exe to run all the 8 spectating instances. This Openttd.exe was not converted.
> 
> All these servers are running AIs.
> 
> 
> The crashes:
> 
> I got 2 crashes happening almost at the same time. I don't know which one crashed first, both crash files from the 2 occurences have the exact date of creation.
> 
> \-Spectator 1 instance crashes, and asked for an emergency save.
> \- Server 3 crash went unnoticed, the console just disappeared, but I found the crash logs in there
> 
> Some other few things:
> \- Spectator 3 instance went back to main menu with "Network - Game connection lost"
> \- Server 1 did not crash
> \- Server 8 logged a Player desyncing. This player was not me, as I first thought. It wasn't a recent event either. I counted 36 messages of "advertising to master server" after the desync (at 01:00 my time, Lisbon). If you know how often that advertising occurs, I could better precise when that desync happened.
> 

**Attachments**
- [Spectator crash.zip](https://bugs.openttd.org/task/6440/getfile/10468/Spectator+crash.zip) (229.59 KiB)
- [Server 3 crash.zip](https://bugs.openttd.org/task/6440/getfile/10469/Server+3+crash.zip) (142.66 KiB)
- [openttdCore8 - Cópia.log](https://bugs.openttd.org/task/6440/getfile/10470/openttdCore8+-+C%C3%B3pia.log) (5.97 KiB)

**Reported version**: _1.6.0_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_Samu_ wrote:**

> two more logs, from server 1 and 3.

**Attachments**
- [openttdCore1 - Cópia.log](https://bugs.openttd.org/task/6440/getfile/10471/openttdCore1+-+C%C3%B3pia.log) (5.70 KiB)
- [openttdCore3 - Cópia.log](https://bugs.openttd.org/task/6440/getfile/10472/openttdCore3+-+C%C3%B3pia.log) (5.76 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6440#comment14146_

**Comment by DorpsGek** [comment]
**_glx_ wrote:**

> Spectator crash
> >	openttd.exe!SlList(void * list, SLRefType conv) Ligne 1378	C++
>  	openttd.exe!SlObjectMember(void * ptr, const SaveLoad * sld) Ligne 1562	C++
>  	openttd.exe!SlObject(void * object, const SaveLoad * sld) Ligne 1612	C++
>  	openttd.exe!SlObjectMember(void * ptr, const SaveLoad * sld) Ligne 1586	C++
>  	openttd.exe!SlObject(void * object, const SaveLoad * sld) Ligne 1612	C++
>  	openttd.exe!Save_VEHS() Ligne 876	C++
>  	openttd.exe!DoSave(SaveFilter * writer, bool threaded) Ligne 2583	C++
>  	openttd.exe!SaveOrLoad(const char * filename, int mode, Subdirectory sb, bool threaded) Ligne 2834	C++
>  	openttd.exe!DoAutosave() Ligne 1427	C++
>  	openttd.exe!GameLoop() Ligne 1449	C++
>  	openttd.exe!VideoDriver_Win32::MainLoop() Ligne 1278	C++
>  	openttd.exe!openttd_main(int argc, char * * argv) Ligne 865	C++
>  	openttd.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Ligne 467	C++
>  	openttd.exe!__tmainCRTStartup() Ligne 275	C
>  	[Code externe]	
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6440#comment14147_

**Comment by DorpsGek** [comment]
**_glx_ wrote:**

> Server 3 crash
> >	openttd.exe!Vehicle::UpdateRealOrderIndex() Ligne 782	C++
>  	openttd.exe!ProcessOrders(Vehicle * v) Ligne 2202	C++
>  	openttd.exe!RoadVehController(RoadVehicle * v) Ligne 1536	C++
>  	openttd.exe!CallVehicleTicks() Ligne 889	C++
>  	openttd.exe!StateGameLoop() Ligne 1384	C++
>  	openttd.exe!NetworkGameLoop() Ligne 1003	C++
>  	openttd.exe!GameLoop() Ligne 1472	C++
>  	openttd.exe!VideoDriver_Dedicated::MainLoop() Ligne 318	C++
>  	openttd.exe!openttd_main(int argc, char * * argv) Ligne 865	C++
>  	openttd.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Ligne 467	C++
>  	openttd.exe!__tmainCRTStartup() Ligne 275	C
>  	[Code externe]	
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6440#comment14148_

**Comment by andythenorth** [comment]
Thanks for this.  At the time of writing this appears to be an bug but not frequently reported.  We do try to address bugs where they occur frequently and/or are easy to reproduce, but this one doesn't look like we can any go further, so I'm closing it.  Thanks for contributing!
