### ISSUE TITLE
Spinlock when saving game on server while client is joining

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6445]
**_Samu_ opened the ticket and wrote:**

> Non-dedicated server gets stuck when selecting a savegame file to load while a client is joining and the server is encoding the save to the client.
> 
> This bug is a bit hard to reproduce. It requires 3 things and exact timing:
> 1 - a savegame file already available to load, preferibly large (4096x4096 map)
> 2 - a non-dedicated server running, preferibly large (4096x4096 map) 
> 3 - a client joining the server.
> 
> Steps:
> 1+2. Have the savegame file ready for the server:
> \- launch openttd
> \- click multiplayer
> \- click start server
> \- click new game
> \- generate a large map (4096x4096 map)
> \- once it generates, save this game
> \- have the load game window already open, but before clicking the savegame, a client has to join first
> 
> 3. A client joins the server:
> \- launch openttd
> \- click multiplayer
> \- join the server, and then...
> 
> ... the bug:
> \- the server will display SAVING GAME when the client joins.
> \- with the load game window open, time to click the savegame to happen exactly when SAVING GAME message is being displayed.
> 
> Result:
> \- Server gets stuck.
> \- Client gets a 20 seconds message without an answer from the server, then network-connection lost
> 

**Reported version**: _1.6.0_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> 'Stuck' = crashes, with crashlog? Or 'stuck' = hangs, spinning?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6445#comment14623_

**Comment by DorpsGek** [comment]
**_Samu_ wrote:**

> hangs

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6445#comment14842_

**Comment by andythenorth** [comment]
Thanks for this.  At the time of writing this appears to be an isolated bug, and not frequently reported.  We do try to address bugs where they occur frequently and/or are easy to reproduce, but this one doesn't look like we can any go further, so I'm closing it.  Thanks for contributing!
