### ISSUE TITLE
Locked GS parameter value can be reseted to default value

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6452]
**_Samu_ opened the ticket and wrote:**

> I need a script with locked values in-game to reproduce this bug, I used Villages Is Villages v2 from download content.
> 
> 1) Launch OpenTTD
> 2) Click AI/Game Script Settings, Click Game Script slot and select Villages Is Villages.
> 3) Click Configure and change Maximum size of largest non-city from default value to anything you want.
> (This parameter is locked while in a game, at least on version v2)
> 4) Click Close, Close, New Game, Generate
> 5) Open AI/Game Script Debug Window, select the Game Script and click Settings.
> 6) Click Reset...
> ... bug: Locked value reverts to default value.

**Reported version**: _1.6.0_
**Operating system**: _Windows_

---

**Comment by andythenorth** [comment]
Thanks for this.  At the time of writing this appears to be an isolated bug, and not frequently reported.  We do try to address bugs where they occur frequently and/or are easy to reproduce, but this one doesn't look like we can any go further, so I'm closing it.  Thanks for contributing!
