### ISSUE TITLE
Crash: scrolling down list of (none) GS parameters

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6453]
**_Samu_ opened the ticket and wrote:**

> To reproduce this bug, I used GS Villages Is Villages v2 which contains many parameter items in its configuration, forcing a vertical scrollbar to be active.
> 
> Steps:
> 
> \- launch OpenTTD
> \- click AI/Game Script Settings
> \- click GS slot, click Select Game Script and select Villages is Villages, click Accept.
> \- click Configure and let this window open.
> \- click Select Game Script and select (none), click Accept.
> 
> bug 1: Configure window didn't close.
> bug 2: Vertical scrollbar is still reflecting the amount of parameter items of Villages Is Villages
> 
> \- click on the scrollbar to scroll down...
> ... OpenTTD crashes.

**Attachments**
- [crash.dmp](https://bugs.openttd.org/task/6453/getfile/10489/crash.dmp) (6810.85 KiB)
- [crash.log](https://bugs.openttd.org/task/6453/getfile/10490/crash.log) (8.45 KiB)
- [crash.png](https://bugs.openttd.org/task/6453/getfile/10491/crash.png) (199.40 KiB)
- [crash.sav](https://bugs.openttd.org/task/6453/getfile/10492/crash.sav) (131.88 KiB)

**Reported version**: _1.6.0_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_Samu_ wrote:**

> Uploading another crash that can occur due to the Configure window not closing. This time it was a mix of two AIs and a dropdown list. It's difficult to trigger this crash. Sometimes when selecting a label from the dropdown crashes, sometimes it doesn't. Steps are quite similar.
> 
> Steps:
> 
>  \- launch OpenTTD
>  \- click AI/Game Script Settings
>  \- click an AI slot, click Select AI, select an AI which you know it contains a dropdown parameter
>  \- click Configure, expand the dropdown list, and let this window open without chosing a value from the dropdown list
>  \- click Select AI and select another AI, click Accept.
> 
> bug 1: Configure window didn't close.
> bug 2: Dropdown list is still reflecting the values from the previous AI
> 
> \- click on a value from the dropdown list...
> ... OpenTTD may or may not crash.

**Attachments**
- [crash.dmp](https://bugs.openttd.org/task/6453/getfile/10493/crash.dmp) (6807.85 KiB)
- [crash.log](https://bugs.openttd.org/task/6453/getfile/10494/crash.log) (8.88 KiB)
- [crash.png](https://bugs.openttd.org/task/6453/getfile/10495/crash.png) (212.76 KiB)
- [crash.sav](https://bugs.openttd.org/task/6453/getfile/10496/crash.sav) (132.04 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6453#comment14166_

**Comment by DorpsGek** [comment]
**_Samu_ wrote:**

> Mixed up parameters of Chopper and AdmiralAI when I last switched to Random AI.

**Attachments**
- [Chopper with AdmiralAI.png](https://bugs.openttd.org/task/6453/getfile/10497/Chopper+with+AdmiralAI.png) (950.38 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6453#comment14167_

**Comment by DorpsGek** [comment]
**_Samu_ wrote:**

> Just found out that it can also crash for View readme, Changelog and License windows in a very similar fashion. They didn't close when Selecting another AI or GS and clicking Accept.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6453#comment14170_

**Comment by DorpsGek** [comment]
**_Samu_ wrote:**

> This is a crash report for NewGRF Settings window, which is similar in nature.
> 
> Steps:
> 
> \- launch OpenTTD
> \- click NewGRF Settings
> \- have 1 active NewGRF file
> \- click License button
> \- without closing the License window, remove the active NewGRF file...
> 
> ... OpenTTD crash.
> 
> 

**Attachments**
- [crash.dmp](https://bugs.openttd.org/task/6453/getfile/10508/crash.dmp) (6811.58 KiB)
- [crash.log](https://bugs.openttd.org/task/6453/getfile/10509/crash.log) (8.58 KiB)
- [crash.png](https://bugs.openttd.org/task/6453/getfile/10510/crash.png) (261.17 KiB)
- [crash.sav](https://bugs.openttd.org/task/6453/getfile/10511/crash.sav) (118.86 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6453#comment14175_

**Comment by DorpsGek** [comment]
**_3298_ wrote:**

> Attaching a simple patch that prevents the issues that eventually lead to the crashes. It closes the parameters window and the textfile window more aggressively. The new behavior is also consistent with other settings windows: one or the other can be open - the parameters and textfile close when the list is opened.

**Attachments**
- [fs6453.diff](https://bugs.openttd.org/task/6453/getfile/10825/fs6453.diff) (1.50 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6453#comment14635_

**Comment by andythenorth** [comment]
I can't repro this behaviour at all.  Assuming prior fix, maybe someone applied this patch or fixed it independently, I'm not going gravedigging to find out.  Thanks!

**Comment by SamuXarick** [comment]
>           I can't repro this behaviour at all.  Assuming prior fix, maybe someone applied this patch or fixed it independently, I'm not going gravedigging to find out.  Thanks!

it was fixed in svn r27787
