### ISSUE TITLE
[patch] GS api for querying network clients

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6459]
**__dp__ opened the ticket and wrote:**

> GS API to query network clients. Nothing too fancy, just basics.
> Please let me know what you think of it because I plan on doing some more stuff based on this patch.

**Attachments**
- [gs-clients-api.diff](https://bugs.openttd.org/task/6459/getfile/10512/gs-clients-api.diff) (20.08 KiB)
- [testclients.tar.gz](https://bugs.openttd.org/task/6459/getfile/10513/testclients.tar.gz) (0.86 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
Now that we're on github, this would be good to handle as a pull request.
