### ISSUE TITLE
Impossible to switch from big/tiny font back to normal in strings

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6465]
**__dp__ opened the ticket and wrote:**

> There are {BIG_FONT} and {TINY_FONT} control codes but no {NORMAL_FONT} or something.
> So it's only possible to use normal font at the beginning of the string.

**Reported version**: _1.6.0_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> The text renderer also does not support different font sizes in the same text.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6465#comment14181_

**Comment by DorpsGek** [comment]
**__dp__ wrote:**

> Really? Looks fine to me. That's also why I marked it as bug since it doesn't seem to be intended.

**Attachments**
- [Screenshot from 2016-05-16 15:11:19.png](https://bugs.openttd.org/task/6465/getfile/10524/Screenshot+from+2016-05-16+15%3A11%3A19.png) (23.08 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6465#comment14182_

**Comment by DorpsGek** [comment]
**__dp__ wrote:**

> Made a pretty straightforward patch that adds {NORMAL_FONT} and {MONO_FONT} control codes, seems to work ok even in weird combinations.
> Also attached simple gs for testing that just shows popup message.

**Attachments**
- [testmonofont.tar.gz](https://bugs.openttd.org/task/6465/getfile/10547/testmonofont.tar.gz) (0.93 KiB)
- [monofont.diff](https://bugs.openttd.org/task/6465/getfile/10546/monofont.diff) (2.24 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6465#comment14207_

**Comment by TrueBrain** [comment]
Looks simple enough; not sure if we want it, but 1 remark on the patch:

With 2 an if() is fine, but now with 4 it becomes a bit much. Especially as a few places map from SCC_NNNFONT to FS_NNN. Maybe a tiny function that does this lookup via a switch or something?
