### ISSUE TITLE
New game start date set to date of loaded scenario

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6474]
**_Samu_ opened the ticket and wrote:**

> The Start Date year from the last loaded scenario in Scenario Editor is copied over to the New Game Start Date window.
> 
> 
> Steps:
> 1) Check what's the current start Date when you click New Game from OpenTTD main menu.
> \- Launch OpenTTD
> \- Click New Game (don't start it)
> \- See what's the value of Date in there and memorize it (let's say it's 1950)
> \- Close the World Generation window
> 
> 2) Launch Scenario Editor, and change the Date.
> \- Click Scenario Editor
> \- The start Date should still be the same (1950) when coming from Step 1
> \- Change the Date to some other value (like 1965), and memorize this value as well
> 
> 3) Save the scenario, then abandon Scenario Editor to see if the Date is still the same as it was seen on Step 1.
> \- Click Save Scenario and Click Save
> \- Click Abandon scenario editor and click Yes
> \- Click New Game (don't start it)
> \- The value of Date in there is still the same as it was in Step 1 (1950)
> \- Close the World Generation window
> 
> The bug:
> 4) Load the saved scenario, then go back to main menu to see the Date becoming that of the loaded scenario.
> \- Click Scenario Editor
> \- The value of Date in there is still the same as it was in Step 1 (1950)
> \- Click Load scenario
> \- Select the saved scenario from step 3 and click Load
> \- The value of Date is now that of the saved scenario in Step 2 (1965)
> \- Click Abandon scenario editor and click Yes
> \- Click New Game (don't start it)...
> 
> ... BUG: the value of the Date is now that of the loaded scenario (1965) instead of that of Step 1 (1950)

**Reported version**: _1.6.1-RC1_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> So the bug is "new game start date set to date of loaded scenario". I wonder if more than just date is affected though.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6474#comment14363_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Not same, but related concern: https://bugs.openttd.org/task/6604

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6474#comment14599_

**Comment by TrueBrain** [comment]
I have a hard time classifying this as a bug. It shows the last "start date" of what ever was loaded. Sounds sane to me?

Going to close the ticket; feel free to rebuttal if you disagree with my conclusion :)
