### ISSUE TITLE
Suggested changes for pathfinding for automatic servicing

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6476]
**_juanjo_ opened the ticket and wrote:**

> I saw several things in YAPF and NPF that in my opinion can be improved:
> 1) Using a FindDepotData struct in YAPF makes code more readable.
> 2) NPF doesn't use the max_distance provided when looking for a RAIL OR ROAD depot for automatic servicing. The code included the option of using it, but the pathfinder didn't get the value of the max_distance to look ahead.
> 3) YAPF doesn't use the max_distance provided when looking for a ROAD depot for automatic servicing.
> 
> See attached patches.

**Attachments**
- [1-FindDepotData.diff](https://bugs.openttd.org/task/6476/getfile/10552/1-FindDepotData.diff) (4.62 KiB)
- [2-NPF-max_distance.diff](https://bugs.openttd.org/task/6476/getfile/10553/2-NPF-max_distance.diff) (4.17 KiB)
- [3-YAPF-max_distance.diff](https://bugs.openttd.org/task/6476/getfile/10554/3-YAPF-max_distance.diff) (2.74 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> The first patch seems to impact trains finding depots. Ran a quick test with a savegame and found that the results (and therefore vehicleenterdepot() calls eventually) are different. Reading the patch, I can't immediately see why...

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6476#comment14411_

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> Okay, seems to be an existing bug. Despite setting max_penalty the pathfinder can still return a tile that is beyond the limit. Because currently the find depot code ignores the actual distance and uses a fake value, the fact that the destination is out of range is ignored.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6476#comment14412_

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> First part has been added. I found 2 other bugs due to it...

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6476#comment14416_

**Comment by andythenorth** [comment]
See also #7001

**Comment by J0anJosep** [comment]
This may be closed. #7009

**Comment by andythenorth** [comment]
Thanks @J0anJosep
