### ISSUE TITLE
Stations: store sprite layout entry in station var68

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6477]
**_mb_ opened the ticket and wrote:**

> Proposal:
> 
> In "station info of nearby tiles (68)", bits 14 .. 31 are still "reserved for future use". It would be helpful to store the "entry from sprite layout" (prop09/1A) in this range, probably only using 8 bits 14 .. 21, so there´d be still 10 bits left for future use.

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> See also:
> https://www.tt-forums.net/viewtopic.php?t=40788

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6477#comment14210_

**Comment by DorpsGek** [comment]
**_mb_ wrote:**

> > [...] when you use this variable in callback 0x14 and the other tile does the same and
> > queries the layout of the first tile, you will end up with a nice recursion
> 
> Hm, yes. Didn´t recall my proposal from 2008. At least this shows that there´s ongoing demand for. :D
> 
> Well, obviously such circular references makes no sense whatsoever, and would be avoided.
> I mean, there are already a lot of other bear traps in grf-coding which might result in "unwanted game behaviour". And at least, this can´t be achieved by an unprepared user, only by a buggy newgrf.
> 
> ?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6477#comment14211_

**Comment by TrueBrain** [comment]
Of course we can use any reversed bits for anything, but without a clear use case why we should use it as such (what does it add? what value does it bring? etc), I do not think anyone will pick this up in any foreseeable future. So I am sorry, but I am going to close this issue, to avoid having tickets linger till the end of times :)
