### ISSUE TITLE
Helicopters do not autorenew/autoreplace while in routes consisting of heliports

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6493]
**_juanjo_ opened the ticket and wrote:**

> (r27616)
> Helicopters are serviced each time they take off from an helipad/heliport, but do not autorenew or autoreplace on helipads.
> Old helicopters with routes involving only heliports (no hangars) are not headed to an airport with a hangar when they need autorenewing or autoreplacing.
> 
> By the way, the DEPOT_LOCATE_HANGAR flag is currently unused.

**Attachments**
- [Fenfingpool Bridge Transport, 25th Sep 2057.sav](https://bugs.openttd.org/task/6493/getfile/10578/Fenfingpool+Bridge+Transport%2C+25th+Sep+2057.sav) (119.79 KiB)

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> The code for DEPOT_LOCATE_HANGAR apparently got lost in r12658.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6493#comment14248_

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> Only rarely. It's mainly because when the serviceathelipad setting is enabled, helicopters are never eligible for autorenew/autoreplace as they have always just been serviced by the time the helicopter takes off.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6493#comment14384_

**Comment by nielsmh** [comment]
This is not an actual problem. The `serviceathelipad` setting exists in OpenTTD because it was implemented in TTDPatch at the dawn of time, and its only purpose was to make helipad-only routes somewhat viable when helistations with hangars did not yet exist. Now helistations do exist, and thus the setting is pretty much pointless.

Closing as not a bug.
