### ISSUE TITLE
Money bug in Detailed performance rating window

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6498]
**_Samu_ opened the ticket and wrote:**

> reported version is 1.6.1
> 
> I think I found a bug in "Detailed performance rating" window. The amount of money in the bank says £2,147 M, but on this savegame, NoNoCAB already has £3,2 M.

**Attachments**
- [NoNoCAB - v3, 1st Mar 2023.sav](https://bugs.openttd.org/task/6498/getfile/10583/NoNoCAB+-+v3%2C+1st+Mar+2023.sav) (2898.01 KiB)

**Reported version**: _other_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_adf88_ wrote:**

> "2,147 M" This number seems familiar ... 2^31 = 2 147 483 648
> Looks like a bug, indeed.
> 
> //EDIT
> I found it.
> http://hg.openttd.org/trunk.hg/file/4051bab2730c/src/economy.cpp# l245
> All scores are stored in 'int' variables.
> 
> So what's the decision? Turn into int64?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6498#comment14259_

**Comment by DorpsGek** [comment]
**_Alberth_ wrote:**

> Attached the screenshot of the ratings window, to avoid having to download and run the game.
> 
> It shows "100%" on required amount of money, so the rating is displayed correctly, it's just the displayed user money amount that does not match with the real user amount.
> However, both 2^31 and the real amount are above the required amount. Using either will work.
> 
> The data only seems to be used for the window (and is not stored somewhere, it seems), so it's probably fine to extend the size of the numbers.
> 

**Attachments**
- [ratingswindow.png](https://bugs.openttd.org/task/6498/getfile/10621/ratingswindow.png) (14.18 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6498#comment14282_

**Comment by nielsmh** [comment]
Can confirm this is still present.
