### ISSUE TITLE
Orders: after deleting an order which is target of a jump, the jump points to the previous order

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6501]
**_deep42thought_ opened the ticket and wrote:**

> Imho, deleting an order should behave the same as keeping that order in the queue but deleting/ignoring the instruction of the order.
> However, deleting an order (say the n-th order), which is target of a (conditional) jump, the jump points to the (n-1)-st order (and not the n-th).
> 
> example of orders:
> before:
> 
> 1. always jump to order 3
> 2. go to waypoint1
> 3. go to waypoint2
> 4. go to waypoint3
> 
> after deleting order 3:
> 1. always jump to order 2
> 2. go to waypoint1
> 3. go to waypoint3
> 
> expected:
> 1. always jump to order 3
> 2. go to waypoint1
> 3. go to waypoint3
> 
> The current behaviour is unintuitive, since "waypoint1" was not reached before the deletion, but afterwards it is. In case the "n-th" is the last order, the target of the jump should change to 1.
> Sry for not attaching a patch, but frankly I didn't understand the logic of what happens when I delete an order.
> 
> greetings,
> deep42thought

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
These kind of problems sadly don't have one solution. Sometimes you want it to change to the 3rd, sometimes to the 2nd. Basically, there is no good solution when you remove the order that a conditional jump is pointing to.

For now the code changes it to the one before; in your case it makes more sense to jump to the one after. But I am sure others can find situations where that doesn't make sense.

So sorry, going to close this issue. But feel free to rebuttal!
