### ISSUE TITLE
Crash: corrupt savegame

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6507]
**_LordAro_ opened the ticket and wrote:**

> Assertion failed at line 113 of /home/lordaro/dev/openttd/src/core/pool_type.hpp: index < this->first_unused
> 
> Files attached. (I know it says 'video-tidy', but the branch is unchanged from master)

**Attachments**
- [British Railways, 2nd May 2087.sav](https://bugs.openttd.org/task/6507/getfile/10599/British+Railways%2C+2nd+May+2087.sav) (144.66 KiB)
- [crash.log](https://bugs.openttd.org/task/6507/getfile/10600/crash.log) (2.77 KiB)
- [ottd-gdb-trace.txt](https://bugs.openttd.org/task/6507/getfile/10601/ottd-gdb-trace.txt) (6.46 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> Savegame is corrupt, two invalid depot tiles at 224x13 and 52x24. Other stuff might be wrong.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6507#comment14362_

**Comment by James103** [comment]
Loading the attached savegame above ("British Railways, 2nd May 2087.sav") still crashes with the same assertion as in the initial comment (`Assertion failed at line 113 of d:\a\1\s\src\core\pool_type.hpp: index < this->first_unused`) in OpenTTD 1.9.0-beta2 on Win 7 Ultimate.

[Crash files attached](https://github.com/OpenTTD/OpenTTD/files/2882268/crash.zip)
