### ISSUE TITLE
Roads: ugly home stretch

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6517]
**_valis_ opened the ticket and wrote:**

> Please add a new type of road, where no build houses. They will not expand the city at the exit from them. Sorry for the translator

**Attachments**
- [screenshot.png](https://bugs.openttd.org/task/6517/getfile/10622/screenshot.png) (707.71 KiB)

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> This facility will be part of road types currently under separate development.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6517#comment14365_

**Comment by andythenorth** [comment]
This is solved in the NRT fork, which is not yet merged to OpenTTD as of April 12th 2018, but may be in future.

https://github.com/andythenorth/NotRoadTypes/commit/b13a79ca7d8ad91b5f38690155dcdb7980e4e70b
