### ISSUE TITLE
Ubutu Xenial 16.04 build

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6519]
**_beruic_ opened the ticket and wrote:**

> The build for Ubuntu Trusty 14.04 does not work on Ubuntu Xenial 16.04 because it doesn't provide libicu52.
> However libicu55 is available, so a new build with that dependency changed should work, provided that the versions are not too different of course, and that I didn't miss any other dependencies.

**Reported version**: _1.6.1_
**Operating system**: _Linux_

---

**Comment by DorpsGek** [comment]
**_burty_ wrote:**

> Hi Jimmy,
> 
> As a workaround you can manually install libicu52: http://packages.ubuntu.com/trusty/amd64/libicu52/download, I did this myself and it seemed to work. If you do custom compiles you'll need to do this manual install as well.
> 
> Kind Regards,
> Burty

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6519#comment14353_

**Comment by TrueBrain** [comment]
We should add Xenial to the release targets (a bit late, with 18.04 around the corner). Till then, you either have to go for the above solution or compile it yourself.

In general, the targets we produce are meant for those targets. Not for any newer :)
