### ISSUE TITLE
Refit bug in newer versions

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6521]
**_mb_ opened the ticket and wrote:**

> For newgrf development, I´m still using an older OTTD version (sprite aligning and CB32 are still working as it should) and it turns out that in recent versions "refitting to the same cargo" (using subtypes) does not work anymore, see pics.
> 
> I didn´t test in what version this first happened, since there had been a lot of changes with refitting/autorefitting.

**Attachments**
- [130beta2.png](https://bugs.openttd.org/task/6521/getfile/10626/130beta2.png) (55.48 KiB)
- [r27677.png](https://bugs.openttd.org/task/6521/getfile/10627/r27677.png) (51.75 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> Seems to work here with old DBSetXL but the UI is slightly different.

**Attachments**
- [Findington Transport, 12th Feb 1931.png](https://bugs.openttd.org/task/6521/getfile/10666/Findington+Transport%2C+12th+Feb+1931.png) (263.83 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6521#comment14361_

**Comment by DorpsGek** [comment]
**_mb_ wrote:**

> > Seems to work here with old DBSetXL but the UI is slightly different.
> 
> Yes, o/c. The UI has been changed slightly in DBXL 0.9, however "refitting to the same cargo" seems to have been changed in newer versions (-> changelogs).
> 
> Meanwhile, I´ve modified my code, to work around it.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6521#comment14385_

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> "sprite aligning and CB32 are still working as it should"
> 
> Meaning they are not working now?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6521#comment14413_

**Comment by DorpsGek** [comment]
**_mb_ wrote:**

> > "sprite aligning and CB32 are still working as it should"
> > Meaning they are not working now?
> 
> For the sprite aligner problem see discussion here:
> https://www.tt-forums.net/viewtopic.php?f=68&t=72647&sid=f9fdef5e634fceaa7eb0d748e8f7a23a
> 
> 
> And for CB32:
> 
> \----------
> 32-day callback (32)
> 
> This callback is called every 32 game days for each vehicle, although not for all vehicles on the same day. The callback is always used when defined, no bit in the action 0 property needs to be set to activate it.
> 
> The return value is a bit mask of the following bits:
> Bit	Value	Meaning 
> 0	1	Trigger vehicle trigger 10
> 1	2	Update colour map via callback 2D
> \-----------
> 
> In DBXL 0.9, and in Snail´s French Train set, a combination of CB2D and CB32 is used to "age" train vehicles, i.e. subtly changing their colour by "recolouring", *while travelling*.
> 
> Since OTTD 1.3 Beta 2 this doesn´t work anymore due to some changes by "frosch", with invalidating the colour palette, i.e. expanding de-caching, to more reasons (due to some request by George), other than "loading/starting the game or rearranging the consist", apart from CB32 (see spec above ^).
> 
> See my original bug report # 5775 including a test case.
> 
> See also discussion with Snail on IRC:
> 
> \----------
> 10:22	<Snail>	I saw frosch123's comment to #5775...
> 10:23	<Snail>	The problem there seems to me that the recoloring procedure is somewhat broken in the new nightlies
> 10:23	<frosch123>	it is now recoloured more often
> 10:23	<Snail>	It also occurs when a vehicle reverses. Recoloring there is instantaneous in 1.3.2 but not anymore in the nightlies 
> 10:23	<frosch123>	there is nothing "broken" with that
> 
> [...]
> 
> \**** 10:49	<frosch123>	ok, "2" now basically always causes the whole consist to be recoloured ****
> 10:49	<Snail>	cb32 has a value that's specific for recoloring, I think I return that one
> \**** 10:49	<Snail>	I see. And this has changed since 1.3.2? ****
> \**** 10:49	<frosch123>	yes ****
> 10:49	<frosch123>	and for xussr requirements recolouring may be triggered even more often
> 
> http://irclogs.thegrebs.com/openttd/2013/11/13
> \-----------
> 
> Obviously, this is against the (original) spec, and it ruins behaviour of our sets. To come up to George´s requests (I don´t know them), this had to be done in some other way, keeping the original mechanism of CB32, e.g. by introducing some extra bit(s) for those "requirements".

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6521#comment14414_

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> So it seems that the issue is that vehicles recolour is updating when you don't expect it. However this can always happen anyway. You need to base your recolour decision on something that won't change at the same time for all the vehicles.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6521#comment14423_

**Comment by DorpsGek** [comment]
**_mb_ wrote:**

> > So it seems that the issue is that vehicles recolour is updating when you don't expect it.
> > However this can always happen anyway. You need to base your recolour decision on
> > something that won't change at the same time for all the vehicles.
> 
> That´s exactly what CB32 is made for:
> 
> "This callback is called every 32 game days for each vehicle, although not for all vehicles on the same day. The callback is always used when defined, no bit in the action 0 property needs to be set to activate it.
> 
> The return value is a bit mask of the following bits:
> Bit	Value	Meaning 
> 0	1	Trigger vehicle trigger 10 
> 1	2	Update colour map via callback 2D
> 
> If no bits are set, nothing happens."
> 
> And for CB2D:
> 
> "Select colour mapping for vehicle (2D)
> 
> Called while drawing the vehicle. [...]
> 
> The return value is cached to speed up sprite processing, and *only updated via callback 32 bit 1 (or when loading/starting a game or rearranging the consist)*."
> 
> 
> Anyway, thanks for your interest.
> 
> Michael

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6521#comment14424_

**Comment by frosch123** [comment]
Caches are caches, not storage.
Caches are allowed to be updated at any time.

CB32 can be used to ensure that the cache is updated at least every 32 days.
It can not be used to ensure that the cache is updated at most every 32 days.
