### ISSUE TITLE
Crash: passwording company

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6524]
**_qwertymain_ opened the ticket and wrote:**

> my game crash will passwording company in multiplayer
> 
> (note: the crash.sav is a reddit server 3 so you need NewGRF to open crash.sav)

**Attachments**
- [crash.log](https://bugs.openttd.org/task/6524/getfile/10629/crash.log) (5.71 KiB)
- [crash.png](https://bugs.openttd.org/task/6524/getfile/10630/crash.png) (301.30 KiB)
- [crash.sav](https://bugs.openttd.org/task/6524/getfile/10631/crash.sav) (2637.06 KiB)

**Reported version**: _1.6.1_
**Operating system**: _Mac OS X_

---

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> Judging by the highlighted character at the start of the password field, this is something to do with input methods.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6524#comment14420_

**Comment by andythenorth** [comment]
Thanks for this.  At the time of writing this appears to be an isolated bug, and hard to reproduce.  We do try to address bugs where they occur frequently and/or are easy to reproduce, but this one doesn't look like we can any go further, so I'm closing it.  Thanks for contributing!
