### ISSUE TITLE
Spritesorter: track fence sprite paints on top of landed UFO

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6529]
**_jfisher446_ opened the ticket and wrote:**

> When a UFO landed on a piece of maglev track...
> The expected behavior was that the UFO is painted on top of the fence instead of behind it. 
> The actual behavior is that the fence is painted on top of the UFO.
> 
> OS: Windows 10 Pro 64-bit

**Reported version**: _1.6.1_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_jfisher446_ wrote:**

> Attached save and image.

**Attachments**
- [BugFenceDrawnOverLandedUFO.sav](https://bugs.openttd.org/task/6529/getfile/10637/BugFenceDrawnOverLandedUFO.sav) (411.64 KiB)
- [BugFenceDrawOverLandedUFO.png](https://bugs.openttd.org/task/6529/getfile/10638/BugFenceDrawOverLandedUFO.png) (210.59 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6529#comment14306_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Confirmed, same issue (I tested with 8bpp original base set) in r27896

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6529#comment14633_

**Comment by TrueBrain** [comment]
Poor little bug :) How ever did you find this ... :D

**Comment by andythenorth** [comment]
Although this would be nice to fix, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though!
