### ISSUE TITLE
Airports: 'closed' var for newgrf airport tiles

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6534]
**_matrix_ opened the ticket and wrote:**

> Hello All
> 
> Close Airport function is really useful however is any chance to present this graphically on the airport itself like on real "closed" airports?
> Please see attached files for more details.
> 
> Regards
> Lukasz

**Reported version**: _1.6.1-RC1_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_matrix_ wrote:**

> This time with attachments.
> 

**Attachments**
- [Closed_Airport.jpg](https://bugs.openttd.org/task/6534/getfile/10651/Closed_Airport.jpg) (128.25 KiB)
- [Closed_Airport2.jpg](https://bugs.openttd.org/task/6534/getfile/10652/Closed_Airport2.jpg) (176.48 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6534#comment14346_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> There is no current work for this goal in OpenTTD.
> 
> If there was an 'airport is closed' var for Airports... https://newgrf-specs.tt-wiki.net/wiki/VariationalAction2/Airports 
> 
> ...then this might be possible with AirportTiles https://newgrf-specs.tt-wiki.net/wiki/Action0/Airport_Tiles
> 
> That might be my misunderstanding though.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6534#comment14565_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> I retitled this to reflect how I think it should be implemented.  Others might disagree ;)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6534#comment14745_

**Comment by andythenorth** [comment]
Although it would be graphically neat, the most common use case for closure is replacing the airport.  So closed sprites would be shown very briefly before demolishing the airport.

On that basis, TMWFTLB for all concerned (core devs and newgrf authors).  So closing, thanks.
