### ISSUE TITLE
"Load scenario" dialog remains focusable while downloading missing online content for a scenario

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6539]
**_NG_ opened the ticket and wrote:**

> This means that, if the scenario loading dialog is dragged to the side of the game window first so it is not covered by the opened content download dialog, another set of downloads can be started while the first set is still running. However, if this is done, only the first set of downloads will complete successfully, and an "Unable to unpack file" error window will be shown for all downloads of the second set.

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
Thanks for this.  At the time of writing this appears to be an isolated bug, and not frequently reported.  We do try to address bugs where they occur frequently and/or are easy to reproduce, but this one doesn't look like we can any go further, so I'm closing it.  Thanks for contributing!
