### ISSUE TITLE
change text on viewport window

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6553]
**_hackalittlebit_ opened the ticket and wrote:**

> Maybe it is only me but it always confuses me this
> 'Copy to viewport' and 'Paste from viewport'
> I tried to give a more descriptive text.
> 'Copy to viewport' was changed to 'Scroll to main' and
> 'Paste from viewport' to 'Scroll main window'
> I do not think it is necessary to mention the viewport because the buttons are on the viewport.
> See patch below.

**Attachments**
- [viewporttext_22643.patch](https://bugs.openttd.org/task/6553/getfile/10690/viewporttext_22643.patch) (1.21 KiB)

**Reported version**: _Version?_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_adf88_ wrote:**

> I must admit that it was always confusing to me too. But the proposed changes are not much better IMO. Perhaps these buttons should be graphical? Quick mock-up:

**Attachments**
- [vp_cp_moc.png](https://bugs.openttd.org/task/6553/getfile/10691/vp_cp_moc.png) (5.56 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6553#comment14417_

**Comment by DorpsGek** [comment]
**_hackalittlebit_ wrote:**

> Maybe this is a better try.
> See patch
> Graphics are so small on my 4000k screen.:-(

**Attachments**
- [viewport_text_2_22629.patch](https://bugs.openttd.org/task/6553/getfile/10692/viewport_text_2_22629.patch) (3.49 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6553#comment14418_

**Comment by DorpsGek** [comment]
**_peter1138_ wrote:**

> It's still ambiguous

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6553#comment14421_

**Comment by DorpsGek** [comment]
**_hackalittlebit_ wrote:**

> Agreed.
> This however should be better.
> Note buttons were swapped.
> 

**Attachments**
- [scroll.png](https://bugs.openttd.org/task/6553/getfile/10693/scroll.png) (116.94 KiB)
- [viewport_text_3_22629.patch](https://bugs.openttd.org/task/6553/getfile/10694/viewport_text_3_22629.patch) (3.50 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6553#comment14422_

**Comment by andythenorth** [comment]
I am labelling this one a bug.  I thought 'copy to viewport' and 'paste from viewport' actually copied the tile contents (I was confused how anyone had managed to achieve that or why it was useful).
