### ISSUE TITLE
Stations: extended byte for NewStation ID

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6562]
**_kiwitree_ opened the ticket and wrote:**

> This patch makes NUM_STATIONS_PER_GRF to 65535.
> It's using grf version 9 and savegame version 197.
> 
> NewGRF syntax changes
> NewStation ID: byte to extended byte
> Action 4: Not using C4xx and C5xx range. It uses feature 0x04 and extended byte id for name of stations and it uses feature 0x48 and D0xx range for class id.
> Action 0: Added Property 0x1B. It sets text id for station class.

**Attachments**
- [openttd-morestations.patch](https://bugs.openttd.org/task/6562/getfile/10701/openttd-morestations.patch) (16.43 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> "Nobody needs 65535 stations".  But I left it open because frosch indicates that increasing newgrf limits is a valid OpenTTD goal :)
> 
> Changed status to reflect the attached patch.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6562#comment14699_

**Comment by andythenorth** [comment]
Eddi suggests this is useful for grfv9.  

Is anyone prepared to maintain a grv9 branch?  This could then be committed to it.
