### ISSUE TITLE
Crash: [ICU] when using "Times New Roman" as large font

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6563]
**_Norrit_ opened the ticket and wrote:**

> Game simply crashed while picking up new plane.

**Attachments**
- [OpenTTD_crash.zip](https://bugs.openttd.org/task/6563/getfile/10702/OpenTTD_crash.zip) (3367.14 KiB)

**Reported version**: _1.7.1-RC1_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> part of the archive

**Attachments**
- [autosave1.sav](https://bugs.openttd.org/task/6563/getfile/10703/autosave1.sav) (337.18 KiB)
- [crash.png](https://bugs.openttd.org/task/6563/getfile/10704/crash.png) (2846.45 KiB)
- [crash.log](https://bugs.openttd.org/task/6563/getfile/10705/crash.log) (13.91 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6563#comment14437_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Information from crash.dmp:
> 00000000\`00efd6e0 00007ff6\`23faf061 : 00000000\`00efde80 00000000\`00efd7e0 00000000\`00efd9a0 00000000\`00ef1930 : openttd!icu_51::MultipleSubstitutionSubtable::process+0x240
> 00000000\`00efd780 00007ff6\`23fb5d86 : 00000000\`00efdaf0 00000000\`00000007 00000000\`27d3e226 00000000\`28386d40 : openttd!icu_51::GlyphSubstitutionLookupProcessor::applySubtable+0x121
> 00000000\`00efd7f0 00007ff6\`23faf15f : 00000000\`00efde80 00000000\`00efd9a0 00000000\`00000007 00000000\`00000000 : openttd!icu_51::ExtensionSubtable::process+0x1d6
> 00000000\`00efd8b0 00007ff6\`23faf538 : 00000000\`00000000 00000000\`00000001 00000000\`00efde80 00000000\`00000000 : openttd!icu_51::GlyphSubstitutionLookupProcessor::applySubtable+0x21f
> 00000000\`00efd920 00007ff6\`23fab097 : 00000000\`00efde80 00000000\`00efdc90 00000000\`00000000 00000000\`00efdc90 : openttd!icu_51::LookupProcessor::process+0x1b8
> 00000000\`00efda90 00007ff6\`23fac15b : 00000000\`29a49320 00000000\`00efde80 00000000\`00efde80 00000000\`0000006a : openttd!icu_51::GlyphSubstitutionTableHeader::process+0xb7
> 00000000\`00efdbb0 00007ff6\`23fabc6d : 00000000\`29a49320 00000000\`0000006a 00000000\`29e7c170 00000000\`0000006a : openttd!icu_51::OpenTypeLayoutEngine::glyphProcessing+0x19b
> 00000000\`00efdc30 00007ff6\`23fa79c0 : 00000000\`0000006a 00000000\`00efde80 00000000\`00000000 00000000\`00000000 : openttd!icu_51::OpenTypeLayoutEngine::computeGlyphs+0x12d
> 00000000\`00efdd00 00007ff6\`23f80f97 : 00000000\`26c11460 00000000\`29a48600 00000000\`00efddf9 00000000\`00000000 : openttd!icu_51::LayoutEngine::layoutChars+0xc0
> 00000000\`00efdd60 00007ff6\`23bc626f : 00000000\`29a48600 00000000\`0325dc90 00000000\`00000000 00000000\`00000002 : openttd!icu_51::ParagraphLayout::ParagraphLayout+0x457
> 00000000\`00efde40 00007ff6\`23bc10cf : 00000000\`00efdfc8 00000000\`00efe09c 00000000\`000001ac 00007ff6\`00000010 : openttd!Layouter::Layouter+0x4df [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\gfx_layout.cpp @ 661]
> 00000000\`00efdf90 00007ff6\`23bc1164 : 00000000\`000001ac 00000000\`00efe8d0 00000000\`00000000 00007ff6\`23f82b76 : openttd!GetStringHeight+0x2f [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\gfx.cpp @ 549]
> 00000000\`00efdff0 00007ff6\`23c8b9de : 00000000\`29b7d910 00007ff6\`2480bf30 00000000\`27d1d7e0 00000000\`00000000 : openttd!GetStringHeight+0x2c [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\gfx.cpp @ 564]
> 00000000\`00efe820 00007ff6\`23c30aae : 00000000\`29b7dbb0 00007ff6\`24843988 00000000\`28616730 00000000\`27d1d7e0 : openttd!NewsWindow::UpdateWidgetSize+0x13e [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\news_gui.cpp @ 357]
> 00000000\`00efe860 00007ff6\`23c2e249 : 0000009a\`000001ac 00000000\`29b7dbb0 00000000\`28616730 00007ff6\`23f8d7ed : openttd!NWidgetLeaf::SetupSmallestSize+0x6f2 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\widget.cpp @ 2386]
> 00000000\`00efe8d0 00007ff6\`23c2f08c : 00000000\`26a7daa0 00000000\`00efe960 00000000\`26a7daa0 00007ff6\`23c2d916 : openttd!NWidgetVertical::SetupSmallestSize+0x59 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\widget.cpp @ 1313]
> 00000000\`00efe910 00007ff6\`23c2e249 : 00000000\`29b7d520 00000000\`26a7daa0 00000000\`00000000 00007ff6\`23c2d916 : openttd!NWidgetBackground::SetupSmallestSize+0x70 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\widget.cpp @ 1767]
> 00000000\`00efe970 00007ff6\`23c355f8 : 00000000\`27d1d7e0 00000000\`00efebe0 00000000\`27d1d7e0 00000000\`0000000a : openttd!NWidgetVertical::SetupSmallestSize+0x59 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\widget.cpp @ 1313]
> 00000000\`00efe9b0 00007ff6\`23c8b7a2 : 00000000\`27d1d7e0 00000000\`27d1d7e0 00000000\`26a7e310 00000000\`00ef0000 : openttd!Window::FinishInitNested+0xa0 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\window.cpp @ 1777]
> 00000000\`00efea00 00007ff6\`23c8c1b2 : 00000000\`27d1d7e0 00000000\`26a7e310 00007ff6\`23b90000 00000000\`00000146 : openttd!NewsWindow::NewsWindow+0x142 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\news_gui.cpp @ 282]
> 00000000\`00efea60 00007ff6\`23c8c94a : 00000000\`27d1d7e0 00000000\`00000000 00007ff6\`247fd7e8 00000000\`00efebe0 : openttd!ShowNewspaper+0xba [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\news_gui.cpp @ 548]
> 00000000\`00efeaa0 00007ff6\`23bf526a : 00000000\`00000000 00000000\`00efebe0 00007ff6\`247fd7e8 00000000\`0000019b : openttd!NewsLoop+0x10e [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\news_gui.cpp @ 896]
> 00000000\`00efeae0 00007ff6\`23be19fd : 00000000\`00000001 00000000\`0051742c 00000000\`0051742c 00000000\`00000001 : openttd!StateGameLoop+0x17a [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\openttd.cpp @ 1396]
> 00000000\`00efec60 00007ff6\`23bf55f1 : 00000000\`00517400 00000000\`0051742c 00000000\`00000000 00007ff6\`248da78c : openttd!NetworkGameLoop+0x165 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\network\network.cpp @ 1003]
> 00000000\`00efeca0 00007ff6\`23e9ad94 : 00000000\`0051742c 00000000\`00efef00 00000000\`0051741c 00000000\`0051741c : openttd!GameLoop+0xe9 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\openttd.cpp @ 1473]
> 00000000\`00efedb0 00007ff6\`23bf329d : 00000000\`00000000 00000000\`00efef40 00000000\`00000000 00000000\`00000000 : openttd!VideoDriver_Win32::MainLoop+0x3cc [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\video\win32_v.cpp @ 1278]
> 00000000\`00efee40 00007ff6\`23e9d4ad : 00000000\`00000000 00000000\`00eff170 00000000\`02c69f01 00000000\`00000000 : openttd!openttd_main+0xfa5 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\openttd.cpp @ 865]
> 00000000\`00eff150 00007ff6\`23f898f0 : 00000000\`00000000 00000000\`00000000 00000000\`00000000 00000000\`00000000 : openttd!WinMain+0x165 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w64bit\src\os\windows\win32.cpp @ 467]
> 00000000\`00eff850 00007fff\`278d2774 : 00000000\`00000000 00000000\`00000000 00000000\`00000000 00000000\`00000000 : openttd!__tmainCRTStartup+0x154 [f:\dd\vctools\crt_bld\self_64_amd64\crt\src\crt0.c @ 275]
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6563#comment14438_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Same issue as in #6494.
> 
> Please pick a large font other than "Times New Roman". It crashes the ICU text layouting library which we use.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6563#comment14439_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> See also https://www.tt-forums.net/viewtopic.php?p=1181908# p1181908

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6563#comment14670_

**Comment by andythenorth** [comment]
Thanks. ICU has known issues, and there is a project underway to replace it. We're not keeping the reports relating to it open, but they can still be found here as and when they are needed. Thanks for the report and diagnosis efforts.
