### ISSUE TITLE
No top panel in full screen 4k resolution

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6567]
**_b25_ opened the ticket and wrote:**

> Windows 10 64-bit
> Intel HD 620

**Attachments**
- [screenshot.png](https://bugs.openttd.org/task/6567/getfile/10707/screenshot.png) (3245.24 KiB)

**Reported version**: _1.7.1-RC1_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_james1101_ wrote:**

> Nor bottom panel.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6567#comment14459_

**Comment by TrueBrain** [comment]
As per #6682, most likely fixed.
