### ISSUE TITLE
Selected Music subset does not include the first song; first song still plays

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6582]
**_james1101_ opened the ticket and wrote:**

> Launch OpenTTD.
> 1. Select or create a music program that does not include the first song in the set. (in OpenMSX first song in the set is 'OpenTTD journey'.)
> 2. Restart OpenTTD or reload OpenMSX (or whatever music set you're using).
>    \-> Either the first song in the set may or may not play.
> 3. Start new game.
> 4. Make sure the music program does not include the first song in the set, and check whatever the first song is playing.
> 5. Abandon game.
>    \-> Again, either the first song in the set may or may not play.
>       If not, repeat steps 3 through 5 until the first song in the set plays.
> 
> Using Win7 Ultimate 32bit.

**Attachments**
- [music.png](https://bugs.openttd.org/task/6582/getfile/10730/music.png) (19.77 KiB)

**Reported version**: _1.7.1_
**Operating system**: _Windows_

---

**Comment by nielsmh** [comment]
I believe #6839 fixes this.
