### ISSUE TITLE
Preview GUI text drops text in German translation

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6584]
**_mb_ opened the ticket and wrote:**

> 
> In the preview GUI, the German translation is missing the descenders of the last text line ("Kapazität: 216 Passagiere"). Reason might be shown inconsistencies between languages, see picture.
> 
> In addition, it would be nice if both preview and advertisement messages would also show
> the railtype of announced vehicles. There seems to be room enough.

**Attachments**
![preview-GUI.png](https://bugs.openttd.org/task/6584/getfile/10733/preview-GUI.png)

**Reported version**: _1.7.1_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
Seems there is more wrong .. I also don't see the cost and weight in the German version. Sounds this needs a closer look :)

**Comment by nikolas** [comment]
Seems like it might be a bug in how text is laid out. You can do a temporary fix by altering the call to `SetMinimalSize()` in `_nested_engine_preview_widget` of `engine_gui.cpp`. But I'd like to get to the bottom of exactly why it's behaving like this.

with `SetMinimalSize(320, 0)`:
![2019-01-28-204959_355x212_scrot](https://user-images.githubusercontent.com/59292/51879087-147b1300-2340-11e9-8d5f-350c5e3843d2.png)

with `SetMinimalSize(300, 0)` (as the code is currently):
![2019-01-28-205106_321x202_scrot](https://user-images.githubusercontent.com/59292/51879179-5c9a3580-2340-11e9-93f9-20fa16153205.png)

with `SetMinimalSize(280, 0)`:
![2019-01-28-210137_304x213_scrot](https://user-images.githubusercontent.com/59292/51879197-6e7bd880-2340-11e9-834d-9749e9d5c65e.png)


So, slightly increasing the minimal widget width here by 20 pixels fixes the immediate problem. But there's something deeper going on: decreasing to 280 also fixes the problem, but causes the engine's image color to still be off.

**Comment by PeterN** [comment]
Wow. Wrong but mostly working for nearly 10 years.
