### ISSUE TITLE
Crash: running the "rescannewgrf" command while newgrfs are already being scanned

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6589]
**_james1101_ opened the ticket and wrote:**

> Using Windows 7 Ultimate
> 
> When running the rescannewgrf command twice in quick succession, a game crash occurs.
> 
> To Reproduce: (Works best when the game has a lot of GRFs to scan.)
> Run the rescannewgrf command twice in quick succession.
> 
> Suggested Fix: When attempting to run the rescannewgrf command while the newgrfs are already being scanned, it should, instead of restarting the scan and crashing, output "Error: Newgrfs still being scanned, please wait til it's finished.", "ERR_NEWGRF_ALREADY_BEING_SCANNED", "ERR_NEWGRF_SCAN_IN_PROGRESS" or something like that.
> 

**Attachments**
- [crash.png](https://bugs.openttd.org/task/6589/getfile/10740/crash.png) (376.32 KiB)
- [crash.log](https://bugs.openttd.org/task/6589/getfile/10741/crash.log) (14.91 KiB)
- [crash.dmp](https://bugs.openttd.org/task/6589/getfile/10742/crash.dmp) (13152.76 KiB)

**Reported version**: _Version?_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_adf88_ wrote:**

> "Run the rescannewgrf command twice in quick succession" - how are you doing this? Seems impossible from the in-game console thus I see no need for a full-blown, language-aware GUI error. It's rather a case of blocking/queuing/dropping calls to rescannewgrf properly. The in-game console (~) is already blocked when scan is in progress. It should be anyway - is it different at your side?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6589#comment14484_

**Comment by DorpsGek** [comment]
**_james1101_ wrote:**

> I meant: Type 'rescannewgrf', then press the following in quick succession: Enter, Up arrow, Enter, Up arrow, Enter, ...

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6589#comment14485_

**Comment by DorpsGek** [comment]
**_adf88_ wrote:**

> What version of OpenTTD are you using? Where did you get it?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6589#comment14486_

**Comment by DorpsGek** [comment]
**_james1101_ wrote:**

> I meant to say OpenTTD 1.7.1, downloaded from the Openttd website.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6589#comment14487_

**Comment by DorpsGek** [comment]
**_adf88_ wrote:**

> OK I see where's the problem now. At lest one of them. When newgrfrescan is in progress, hidden windows receive and process keyboard input (they shouldn't). So it is actually possible to run the command twice, even though you don't see it. It's a separate issue how commands are processed inside scripts tho.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6589#comment14488_

**Comment by andythenorth** [comment]
Thanks for this.  At the time of writing this appears to be an isolated bug, and not frequently occurring.  We do try to address bugs where they occur frequently and/or are easy to reproduce, but this one doesn't look like we can any go further, so I'm closing it.  Thanks for contributing!
