### ISSUE TITLE
Stations: allow building stations on railtypes other than the one currently selected

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6590]
**_james1101_ opened the ticket and wrote:**

> Expected:
> 1. Place a piece of "Electrified Rail".
> 2. Try to Place an "Unelectrified Rail" station. Succeeds if track is compatible.
> 
> Actual:
> 1. Place a piece of "Electrified Rail".
> 2. Try to Place an "Unelectrified Rail" station. Fails with "must remove railway track first" error message.
> 
> Suggested Fix: When placing a station whose track is not the type selected, check for track compatibility, and if the two types are compatible, continue anyway with the track type on the tile instead.
> 
> (The area inside the white border is the tile that I was trying to place station at.)
> 
> Using Windows 7 Ultimate.

**Attachments**
- [ottd_unable_to_place_station.png](https://bugs.openttd.org/task/6590/getfile/10743/ottd_unable_to_place_station.png) (41.12 KiB)

**Reported version**: _1.7.1_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> From irc: Eddi|zuHause: anyway, if the question was whether overbuilding an existing track/station should ignore which tracktype you have selected in the gui, then yes, i'm for that

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6590#comment14549_

**Comment by DorpsGek** [comment]
**_adf88_ wrote:**

> related: http://www.tt-forums.net/viewtopic.php?f=33&t=54126

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6590#comment14576_

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
