### ISSUE TITLE
Can still click on buy button in vehicle selection window even if no vehicle is selected

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6599]
**_james1101_ opened the ticket and wrote:**

> To Reproduce:
> 1. Open a depot window and click the 'New Vehicles' button.
> 2. Deselect the vehicle by doing the following:
>     3. Select a vehicle. (Example: a locomotive without any capacity)
>     4. Filter the list such that the selected vehicle disappears. (Example: Show only vehicles that can carry <cargo name>.)
> 5. Click the 'Buy Vehicle' button in the vehicle selection window.
> \-> Nothing happens. The button is not greyed out, but it does nothing. Please fix this.

**Attachments**
- [ottd_buy_vehicle_none_selected.png](https://bugs.openttd.org/task/6599/getfile/10767/ottd_buy_vehicle_none_selected.png) (403.18 KiB)

**Reported version**: _1.7.1_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Confirmed - can reproduce this using steps described.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6599#comment14506_

**Comment by DorpsGek** [comment]
**_adf88_ wrote:**

> I have something for this, and more.
> 
> 0-disable-build-button-if-no-engine-selected.diff
> Fixes the issue (disables/enables the button when needed).
> 
> 1-select-first-available-rail-engine-to-buy.diff
> Enable auto-selecting first available engine also in train lists (currently, when the selected train is being filtered out, nothing gets selected). Also remove some duplicated code.
> 
> 2-use-gui-sorlists-for-buildvehgui-engines-sorting.diff
> Remove duplicated code and use GUIList class for sorting engine lists.
> 
> 3-use-gui-sorlists-for-buildvehgui-engines-filtering.diff
> Remove duplicated code and use GUIList class for filtering engine lists.
> 
> 4-uncache-buildvehgui-listviewmode.diff
> Remove useless caching of "list-view mode" in BuildVehicleWindow class.
> 
> 5-uncache-buildvehgui-cargofilterarray.diff
> Remove useless caching of cargoes and cargo names in BuildVehicleWindow class.
> 

**Attachments**
- [0-disable-build-button-if-no-engine-selected.diff](https://bugs.openttd.org/task/6599/getfile/10796/0-disable-build-button-if-no-engine-selected.diff) (0.73 KiB)
- [1-select-first-available-rail-engine-to-buy.diff](https://bugs.openttd.org/task/6599/getfile/10797/1-select-first-available-rail-engine-to-buy.diff) (6.87 KiB)
- [2-use-gui-sorlists-for-buildvehgui-engines-sorting.diff](https://bugs.openttd.org/task/6599/getfile/10798/2-use-gui-sorlists-for-buildvehgui-engines-sorting.diff) (25.46 KiB)
- [3-use-gui-sorlists-for-buildvehgui-engines-filtering.diff](https://bugs.openttd.org/task/6599/getfile/10799/3-use-gui-sorlists-for-buildvehgui-engines-filtering.diff) (10.21 KiB)
- [4-uncache-buildvehgui-listviewmode.diff](https://bugs.openttd.org/task/6599/getfile/10800/4-uncache-buildvehgui-listviewmode.diff) (3.99 KiB)
- [5-uncache-buildvehgui-cargofilterarray.diff](https://bugs.openttd.org/task/6599/getfile/10801/5-uncache-buildvehgui-cargofilterarray.diff) (8.11 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6599#comment14574_

**Comment by DorpsGek** [comment]
**_adf88_ wrote:**

> Sorry, a mistake got in. I'm uploading a fixed patch # 3. Now I tried harder at testing ;)

**Attachments**
- [3-use-gui-sorlists-for-buildvehgui-engines-filtering.diff](https://bugs.openttd.org/task/6599/getfile/10802/3-use-gui-sorlists-for-buildvehgui-engines-filtering.diff) (10.21 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6599#comment14582_

**Comment by andythenorth** [comment]
I can't get the patch to apply to master (as of 12th Jan 2019).  Issue still looks valid.
