### ISSUE TITLE
Stations: additional animation triggers

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6607]
**_mb_ opened the ticket and wrote:**

> For stations it is (near?) impossible to set up *multi-tile* animations using triggers which are only happening on platforms "where the train is" (bits 3 .. 5), since the animation will only being run for those platform tiles. Since prop18 (animation triggers) is a WORD and only 7 bits are being used today, it would be feasible to add those three platform-restricted triggers for the whole station as well?
> 

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> So change to 'whole station' for bits 3-5 in the table here? https://newgrf-specs.tt-wiki.net/wiki/Action0/Stations# Animation_triggers_.2818.29
> 
> Does it need any toolchain update, or just OpenTTD and docs?  
> 
> Does it break any existing grf behaviour?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6607#comment14524_

**Comment by DorpsGek** [comment]
**_mb_ wrote:**

> > So change to 'whole station' for bits 3-5 in the table here?
> 
> Nah, I was talking about introducing 3 new triggers, e.g.:
> 
> 7  80   Train enters station (starts loading/unloading) whole station
> 8  100  Train leaves station (done loading/unloading)	whole station
> 9  200  Train loads/unloads cargo                       whole station
> 
> > Does it need any toolchain update, or just OpenTTD and docs?
> 
> Probably 3 new constants in m4nfo and NML, besides implementation in OTTD and adding it to the specs/docs.
> 
> > Does it break any existing grf behaviour?
> 
> I don´t think so, because "The remaining bits are reserved for future triggers, they must be zero for now."

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6607#comment14525_

**Comment by TrueBrain** [comment]
A good issue to pick up for someone who wants to start to learn more about NewGRFs and their handling.

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
