### ISSUE TITLE
Scenario Editor: additional powerful terrain tools

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6612]
**_Wolf01_ opened the ticket and wrote:**

> New terrain tools to:
> \- Raise / lower land like a paintbrush (resizable)
> \- Raise / lower terrain area keeping the same form (resizable)
> \- Fill valleys without changing the terrain over the starting height (drag&drop)
> \- Trim mountains without changing the terrain below the starting height (drag&drop)
> 
> Branch with features can be found here: https://github.com/Wolfolo/OpenTTD/tree/terraform-tools

**Reported version**: _1.7.1_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
As this now has a fork, and will generate a pull request when its ready, we no longer need a ticket open for it :)
