### ISSUE TITLE
Makes the upgrade/convert tool upgrade trains stationed in depots between incompatible rail types

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6617]
**_zegentzy_ opened the ticket and wrote:**

> Ever upgraded from rail to monorail (or manglevs)? Annoyed at having to recreate all your trains? I got the solution for you!
> 
> This patch allows the upgrading of depots containing parked trains. It also autoreplaces all trains in said depots. 
> 
> Now you can:
> 1- Set autoreplace to upgrade rail engines/wagons to monorail (or manglave) engines/wagons. 
> 2- Send all trains to a depot
> 3- Use the upgrade/convert tool on the depot!
> 4- Watch as all your trains are now monorail/manglev, no order cloning of 400 trains required!
> 
> Changes:
> 1- Made autoreplace gui show incompatible rail types - as far as I can tell trains don't upgrade to non-compatible rail types of the depot can't buy the rail type so this should have no effect on anything
> 2- Reworked Upgrade rails command to still upgrade depot tiles if they have trains on em' only if all trains are stationed in the depot. It then calls autoreplace on all those trains.

**Attachments**
- [easier_upgrading.diff](https://bugs.openttd.org/task/6617/getfile/10836/easier_upgrading.diff) (4.60 KiB)

**Reported version**: _1.7.1_
**Operating system**: _All_

---

**Comment by andythenorth** [comment]
Although cross-railtype upgrading is micro-management, eliminating it is not a current goal.  Thanks for the patch, but we'll have to pass on this one :)
