### ISSUE TITLE
Games freezes at start-up if -n command line option is used.

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6619]
**_sincx_ opened the ticket and wrote:**

> Games freezes at start-up if -n command line option to connect to a specific server is used.
> 
> On 1.6.0, using the command line option "openttd -n [server ip]" works fine.
> On 1.7.1 or 1.7.0, using the same command line to connect to the exact same server (after adjusting the version of the game running on the server to match) results in a freeze at the Scanning NewGRFs screen.

**Reported version**: _1.7.1_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_james1101_ wrote:**

> Able to reproduce on Win 7 Ultimate.
> Ram: 4 GB, CPU: 2 cores, 2 GHz
> 
> Task Manager says CPU usage of client is on average, near 0.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6619#comment14759_

**Comment by DorpsGek** [comment]
**_gpsoft_ wrote:**

> I can also reproduce it on Windows 8.1
> It seems it's a deadlock on mutexes.
> 1.6.1 is still fine, 1.7.0 locks up.
> Will try to debug more and check where it was broken exactly.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6619#comment14810_

**Comment by DorpsGek** [comment]
**_gpsoft_ wrote:**

> The problem is since revision 27775 (doesn't happen in revision 27774):
> introducing AcquireBlitterLock() and ReleaseBlitterLock() interface which seems it locks (enters into critical section) it with a _draw_mutex object.
> In the same time PaintWindowThread is also in the _draw_mutex critical section so two threads are in dead-lock here. It is possible there is another interaction with a _modal_progress_paint_mutex and _modal_progress_work_mutex but I am not sure about it, possibly just a _draw_mutex is dead-locked.
> I included the stack trace in a deadlocked state. It is running with a source code of version 1.7.0 (revision 27840).
> Author of the modification was frosch, the message on revision 27775 is:
> \-Fix [#6510]: Insufficient thread synchronisation when switching blitters. (JGR)

**Attachments**
- [stack_trace.txt](https://bugs.openttd.org/task/6619/getfile/10891/stack_trace.txt) (2.84 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6619#comment14811_

**Comment by DorpsGek** [comment]
**_gpsoft_ wrote:**

> It seems the difference in other cases is the AcquireBlitterLock() is called from the main thread.
> The patch seems to fix this problem (although there might be another reason to run that particular code from new thread named "ottd:newgrf-scan"). In this patch I am running it from main thread and it doesn't get locked up.
> 

**Attachments**
- [newgrf_config.cpp.patch](https://bugs.openttd.org/task/6619/getfile/10892/newgrf_config.cpp.patch) (0.95 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6619#comment14812_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> This disables the 'Cancel scanning' button, doesn't it?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6619#comment14868_

**Comment by glx22** [comment]
Fixed with e76fd99c472237125f03d46ed7bff915e2d6a20b
