### ISSUE TITLE
Incorrect news message if Game Script funds a town.

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6622]
**_james1101_ opened the ticket and wrote:**

> To Reproduce:
> 1. Code/Download a game script that funds a town such as the attached one.
> 2. Launch OpenTTD and start new game with that game script.
> 3. Wait until a town funded message appears.
> BUG: It will say: "_ sponsored construction of new town <TOWNNAME>!" instead of "<COMPANY> sponsored construction of new town <TOWNNAME>!". (underscore is leading blank space)
> Suggested Fix: It should say something like "A new town <TOWNNAME> has been constructed!"
> 
> Possible Reason: Neutral company is the Game Script's internal company, and it has no name, so it shows as blank.
> 
> OpenTTD Version 1.7.1 running on Win 7 Ultimate.
> 

**Attachments**
- [TownGS.tar](https://bugs.openttd.org/task/6622/getfile/10852/TownGS.tar) (4.50 KiB)
- [ottd_wrong_news_message.png](https://bugs.openttd.org/task/6622/getfile/10853/ottd_wrong_news_message.png) (245.89 KiB)

**Reported version**: _1.7.1_
**Operating system**: _Windows_

---

**Comment by TrueBrain** [comment]
Sounds spot-on :D Should be an easy fix.
