### ISSUE TITLE
Docks can't be connected into a single station

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6628]
**_lsalehar_ opened the ticket and wrote:**

> When building docks they cant be connected to a single station pressing Ctrl.

**Reported version**: _1.7.1_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_james1101_ wrote:**

> Watch this video https://www.youtube.com/watch?v=h-cM-e9V6Ac&t=1092s (by LtJoker) for a possible fix to this bug.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6628#comment14781_

**Comment by DorpsGek** [comment]
**_Wolf01_ wrote:**

> Not a bug, it's by design.
> I'll change it to a feature request, James already pointed you to a possible solution (use a patchpack)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6628#comment14782_

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
