### ISSUE TITLE
In singleplayer, you cannot buyout one human-player company as another.

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6631]
**_james1101_ opened the ticket and wrote:**

> To Reproduce:
> 1. Launch OpenTTD. Start multiplayer game.
> 2. Create 2 companies of the 'Human Player' type.
> 3. Save the game in multiplayer.
> 4. Load the game in singleplayer.
> 5. Make sure...
>   \- that Company # 1 has enough money to buyout Company # 2 (use money cheat if needed),
>   \- both companies are at least 6 years old (use date cheat if needed), and
>   \- the setting "Allow buying shares" under "Competitors" is set to true.
> 6. BUG: In singleplayer, Attempt to buyout Company # 2 as Company # 1. This will fail at 75% progress, with no error message and a greyed out "Buy Share" button. (see attached image)
> Suggested Fix: When loading a multiplayer save in singleplayer (defined as a save with multiple human-player companies), convert all of the human player companies (except Company # 1) to dummy AI companies. AI companies can be completely bought, while human-player companies cannot be completely bought.
> 

**Attachments**
- [ottd_can't_buyout_company.png](https://bugs.openttd.org/task/6631/getfile/10866/ottd_can%27t_buyout_company.png) (48.46 KiB)

**Reported version**: _1.7.1_
**Operating system**: _Windows_

---

**Comment by TrueBrain** [comment]
We talked this over a bit; converting humans to AIs when loading the game in Single Player most likely won't work. It is very unlikely the AI can do anything with the layout the human has made.

Our current suggestion is to add two commands: `attachai` and `detachai`, so someone can opt-in (via console) to do this conversion.

Of course that doesn't really resolve the described issue, but I am not sure it needs a solution as such. Comments? Thoughts?

**Comment by James103** [comment]
Some more info on the commands:

The `attachai` command would hook an AI to a company. It is like `startai` except it does not create a new company, it only attaches to an existing company. This succeeds on all company types as long as there's no AI attached to the company and the AI does not crash when starting up.
Syntax: `attachai <company> <ai> <settings ...>`
Success message: "AI successfully started and attached" 
Possible failure message: "There is already an AI attached to this company."

The `detachai` command would remove an AI from a company. It is like `stopai` except that it does completely delete the company. This succeeds as long as the company being affected has an AI attached.
Syntax: `detachai <company>`
Success message: "AI successfully detached and stopped"
Possible failure message: "There is no AI attached to this company."

For both commands, the following error message would appear when either of the above commands are run in multiplayer: "ERROR: This command is only available in single player."

Using those commands in a game with no cheats enabled would prompt the following warning message:
> You are about to change the AI status of a running company, which counts as a cheat. By using cheats, you betray your fellow competitors. Keep in mind that such a disgrace will be remembered for eternity (This means that the use of cheats will be recorded in your saved game). Do you want to do this?

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
