### ISSUE TITLE
airplane going for helistation depot

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6636]
**_Samu_ opened the ticket and wrote:**

> Steps to reproduce:
> 
> Build 2 airports, A and B and have an airplane going from A to B.
> Build an helidepot, C, between A and B.
> 
> When airplane is heading to B, and is closer to C than A, demolish B.
> Send airplane to hangar.
> 
> Bug: Airplane tries to go to C, but that is an helidepot and can't land there.
> 
> I attach a savegame, set to reproduce the bug. Demolish the airport located south, then send airplane to hangar to have it trigger the bug.
> 

**Attachments**
- [nearest hangar bug.sav](https://bugs.openttd.org/task/6636/getfile/10876/nearest+hangar+bug.sav) (48.64 KiB)

**Reported version**: _1.7.1_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_Samu_ wrote:**

> There is another bug related to this.
> 
> Build 2 airports, A and B and have an airplane going from A to B.
> 
> When airplane is heading to B, demolish airport B, and replace it with an helidepot B in its place.
> Send airplane to hangar.
> 
> Bug: Airplane still tries to go to B, but that is no longer an airport, it's now a helidepot and can't land there.
> 
> I attach my proposed fix to deal with these two bugs.

**Attachments**
- [aircraft nearest hangar fix v1 r27930.patch](https://bugs.openttd.org/task/6636/getfile/10877/aircraft+nearest+hangar+fix+v1+r27930.patch) (1.67 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6636#comment14798_

**Comment by andythenorth** [comment]
Ok this is referenced by https://github.com/OpenTTD/OpenTTD/pull/6925

Removing 'stale' and 'patch from flyspray' as no longer relevant labels.
