### ISSUE TITLE
Modernizing for C++11: replacing instances of SmallVector

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6649]
**_M3Henry_ opened the ticket and wrote:**

> After discussions on IRC about modernising the code to make it easier to work on, replacing non time-critical instances of SmallVector<T,S> with std::vector<T> was deemed more practical than making SmallVector STL-like.
> 
> This allows use of range-based for loops and STL algorithms to improve expressiveness in the code base.
> 
> No changes to functionality have been made.
> Patches are based on r27956.

**Attachments**
- [0001-Added-new-adapter-functions-to-help-transition-from-.patch](https://bugs.openttd.org/task/6649/getfile/10901/0001-Added-new-adapter-functions-to-help-transition-from-.patch) (4.99 KiB)
- [0002-Window-scheduled_invalidation_data-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10902/0002-Window-scheduled_invalidation_data-std-vector.patch) (1.89 KiB)
- [0003-SubtypeList-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10903/0003-SubtypeList-std-vector.patch) (6.16 KiB)
- [0004-GetBestFittingSubType-subtypes-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10904/0004-GetBestFittingSubType-subtypes-std-vector.patch) (1.87 KiB)
- [0005-TextfileWindow-lines-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10905/0005-TextfileWindow-lines-std-vector.patch) (4.01 KiB)
- [0006-CheckSubsidised-towns_near-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10906/0006-CheckSubsidised-towns_near-std-vector.patch) (1.75 KiB)
- [0007-StringFilter-word_index-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10907/0007-StringFilter-word_index-std-vector.patch) (3.17 KiB)
- [0008-IcuStringIterator-SmallVector-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10908/0008-IcuStringIterator-SmallVector-std-vector.patch) (3.69 KiB)
- [0009-SmallIndustryList-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10909/0009-SmallIndustryList-std-vector.patch) (1.71 KiB)
- [0010-FileList-files-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10910/0010-FileList-files-std-vector.patch) (2.44 KiB)
- [0011-VehicleGroupWindow-indents-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10911/0011-VehicleGroupWindow-indents-std-vector.patch) (1.21 KiB)
- [0012-_hotkey_lists-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10912/0012-_hotkey_lists-std-vector.patch) (2.39 KiB)
- [0013-Hotkey-keycodes-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10913/0013-Hotkey-keycodes-std-vector.patch) (2.24 KiB)
- [0014-LanguageList-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10914/0014-LanguageList-std-vector.patch) (4.19 KiB)
- [0015-LinkGraph-NodeVector-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10915/0015-LinkGraph-NodeVector-std-vector.patch) (2.24 KiB)
- [0016-LinkGraphJob-NodeAnnotationVector-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10916/0016-LinkGraphJob-NodeAnnotationVector-std-vector.patch) (1.29 KiB)
- [0017-NetworkAddressList-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10917/0017-NetworkAddressList-std-vector.patch) (6.05 KiB)
- [0018-_tcp_connectors-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10918/0018-_tcp_connectors-std-vector.patch) (2.24 KiB)
- [0019-_http_connections-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10919/0019-_http_connections-std-vector.patch) (2.22 KiB)
- [0020-IndustryCargoesWindow-Fields-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10920/0020-IndustryCargoesWindow-Fields-std-vector.patch) (5.00 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_M3Henry_ wrote:**

> The rest of the patches done so far.

**Attachments**
- [0021-ContentVector-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10921/0021-ContentVector-std-vector.patch) (15.48 KiB)
- [0022-GetLinkGraphJobDesc-saveloads-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10922/0022-GetLinkGraphJobDesc-saveloads-std-vector.patch) (1.61 KiB)
- [0023-_old_waypoints-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10923/0023-_old_waypoints-std-vector.patch) (6.69 KiB)
- [0024-StationList-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10924/0024-StationList-std-vector.patch) (3.97 KiB)
- [0025-_text_effects-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10925/0025-_text_effects-std-vector.patch) (3.88 KiB)
- [0026-OutputStore-output_buffer-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10926/0026-OutputStore-output_buffer-std-vector.patch) (2.12 KiB)
- [0027-TrainList-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10927/0027-TrainList-std-vector.patch) (1.40 KiB)
- [0028-CmdSetTimetableStart-vehs-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10928/0028-CmdSetTimetableStart-vehs-std-vector.patch) (1.87 KiB)
- [0029-AfterLoadGame-skip_frames-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10929/0029-AfterLoadGame-skip_frames-std-vector.patch) (2.35 KiB)
- [0030-VehicleSet-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10930/0030-VehicleSet-std-vector.patch) (3.61 KiB)
- [0031-station_gui.cpp-SmallVectors-std-vector.patch](https://bugs.openttd.org/task/6649/getfile/10931/0031-station_gui.cpp-SmallVectors-std-vector.patch) (5.61 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6649#comment14820_

**Comment by StefanBruens** [comment]
There is https://www.boost.org/doc/libs/master/doc/html/container/non_standard_containers.html#container.non_standard_containers.small_vector

**Comment by LordAro** [comment]
Closed in favour of #6817
