### ISSUE TITLE
Improve CargoDist flow palette

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6651]
**_Borg_ opened the ticket and wrote:**

> Current default palette for CargoDist flow tool is pretty bad.
> Especialy on temperate climate, green color is not readable.
> Also white as not-used make too much difference compared to rest of palette.
> 
> I suggest following palette:
> C8 CA CB CC AC AD AE AF BC BB BA B9
> 

**Reported version**: _1.7.2_
**Operating system**: _All_

---

**Comment by TrueBrain** [comment]
Please do research on good readable colours before creating a patch for this ticket.

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
