### ISSUE TITLE
Patch to guard for NO_DEBUG_MESSAGES

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6652]
**_Borg_ opened the ticket and wrote:**

> Here is patch do suppress all debug messages when
> someone is compiling with NO_DEBUG_MESSAGES defined.
> No all places had it.
> 

**Attachments**
- [no_debug_mesg.patch](https://bugs.openttd.org/task/6652/getfile/10932/no_debug_mesg.patch) (3.78 KiB)

**Reported version**: _1.7.2_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> The desync debug messages are no ordinary debug messages. They are for replaying games.
> Making NO_DEBUG_MESSAGES interfer with that sounds weird to me.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6652#comment14866_

**Comment by DorpsGek** [comment]
**_Borg_ wrote:**

> Woops, indeed.. I got carried away here..
> Attaching fixed patch.
> 

**Attachments**
- [no_debug_mesg.patch](https://bugs.openttd.org/task/6652/getfile/10993/no_debug_mesg.patch) (3.01 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6652#comment14874_

**Comment by TrueBrain** [comment]
~~This feels off to me. NO_DEBUG_MESSAGE seems a bit unrelated to debugging the debug_desync_level. I would at least except either another define, or higher up an error that you cannot have a debug_desync_level with NO_DEBUG_MESSAGE.~~ I should have read the comments; frosch already said this :D

The genworld.cpp seems valid :D

**Comment by TrueBrain** [comment]
Okay, this NO_DEBUG_MESSAGES is a bit weird. First of all, you cannot change it without modifying files. But also, debug_desync_level does a lot more than just spitting out messages. But the other debug_NNN_level mostly only changes what is being printed. A very weird combination, that is hard to untangle. Not sure that the supplied patch is the best way.

Possibly it is easier to just remove NO_DEBUG_MESSAGES.
