### ISSUE TITLE
Crash: [ICU] The game never opens and the Arabic language in the form of numbers and symbols

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6655]
**_zaidx499_ opened the ticket and wrote:**

> The game never opens and the Arabic language in the form of numbers and symbols
> 

**Attachments**
- [crash.png](https://bugs.openttd.org/task/6655/getfile/10934/crash.png) (1.07 KiB)
- [crash.dmp](https://bugs.openttd.org/task/6655/getfile/10935/crash.dmp) (13086.46 KiB)
- [crash.sav](https://bugs.openttd.org/task/6655/getfile/10936/crash.sav) (63.87 KiB)
- [crash.log](https://bugs.openttd.org/task/6655/getfile/10937/crash.log) (12.52 KiB)

**Reported version**: _1.7.2_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Information from crash.dmp:
> 0014e938 006d52ee 0000040f 0000060e 0000000b openttd!icu_51::LigatureSubstitutionSubtable::process+0xec
> 0014e980 006dad92 0014e9ac 00000004 0014eaa8 openttd!icu_51::GlyphSubstitutionLookupProcessor::applySubtable+0x12e
> 0014e9e0 006d539d 0014eb48 20210000 0014eaa8 openttd!icu_51::ExtensionSubtable::process+0xc2
> 0014ea2c 006d55c6 0014ea58 00000007 0014eaa8 openttd!icu_51::GlyphSubstitutionLookupProcessor::applySubtable+0x1dd
> 0014ea80 006d5724 00000001 00000007 00000000 openttd!icu_51::LookupProcessor::applyLookupTable+0xc6
> 0014eb20 006d1b57 0000000a 00000000 00000001 openttd!icu_51::LookupProcessor::process+0x114
> 0014eba8 006d29a1 041d9cb4 0014ec1c 00000001 openttd!icu_51::GlyphSubstitutionTableHeader::process+0x87
> 0014ebe8 006d2488 041d9cb4 00000000 0000000a openttd!icu_51::OpenTypeLayoutEngine::glyphProcessing+0x111
> 0014ec54 006ceeb6 2507e6d8 00000000 0000000a openttd!icu_51::OpenTypeLayoutEngine::computeGlyphs+0xc8
> 0014ec84 006a8f0c 2507e6d8 00000000 0000000a openttd!icu_51::LayoutEngine::layoutChars+0x76
> 0014ecec 00423f23 00000000 250a1db8 0014ed28 openttd!icu_51::ParagraphLayout::ParagraphLayout+0x33c
> 0014ed58 0042481e 2507e6d8 0000000a 00000000 openttd!GetParagraphLayout+0xae [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\gfx_layout.cpp @ 207]
> 0014edc8 00420ea2 0014edf0 0014ee37 7fffffff openttd!Layouter::Layouter+0x327 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\gfx_layout.cpp @ 661]
> 0014ee10 00420f0a 0014ee20 00000000 d98881ee openttd!GetStringBoundingBox+0x37 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\gfx.cpp @ 701]
> 0014f624 0046517d 000005ba 036a33f0 0426d850 openttd!GetStringBoundingBox+0x2a [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\gfx.cpp @ 717]
> 0014f668 00463052 04217908 00000000 0426d850 openttd!NWidgetLeaf::SetupSmallestSize+0x47a [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\widget.cpp @ 2338]
> 0014f688 004633ab 04217908 00000000 04217908 openttd!NWidgetHorizontal::SetupSmallestSize+0x37 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\widget.cpp @ 1148]
> 0014f6a8 00463d74 04217908 00000000 041ad0c8 openttd!NWidgetVertical::SetupSmallestSize+0x37 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\widget.cpp @ 1313]
> 0014f6e0 004633ab 04217908 00000000 000001bc openttd!NWidgetBackground::SetupSmallestSize+0x37 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\widget.cpp @ 1767]
> 0014f700 00467b82 04217908 00000000 00000000 openttd!NWidgetVertical::SetupSmallestSize+0x37 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\widget.cpp @ 1313]
> 0014f718 0046a317 00000000 00000000 250a18e8 openttd!Window::ReInit+0x24 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\window.cpp @ 976]
> 0014f730 0042155a 00f5fdb0 0014fb98 0014fb98 openttd!ReInitAllWindows+0x3f [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\window.cpp @ 3304]
> 0014f74c 00452c1f 0179ee4c 00000000 00000001 openttd!LoadStringWidthTable+0x92 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\gfx.cpp @ 1140]
> 0014fb98 0043f1a3 00000001 01b055dc 00000000 openttd!CheckForMissingGlyphs+0x121 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\strings.cpp @ 2154]
> 0014fbac 0043ff72 00000000 00000001 00000001 openttd!LoadIntroGame+0x67 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\openttd.cpp @ 345]
> 0014fdd4 005de44f 00000001 0014fdf0 006b07ff openttd!openttd_main+0xa78 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\openttd.cpp @ 857]
> 0014fef0 006b07ac 00400000 00000000 01d4258f openttd!WinMain+0x99 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\os\windows\win32.cpp @ 467]
> 0014ff80 753d9564 002ba000 753d9540 b8456871 openttd!__tmainCRTStartup+0x11a [f:\dd\vctools\crt_bld\self_x86\crt\src\crt0.c @ 275]

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6655#comment14827_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Similar issue as in #6563, but this time with Arial.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6655#comment14828_

**Comment by andythenorth** [comment]
Thanks. ICU has known issues, and there is a project underway to replace it. We're not keeping the reports relating to it open, but they can still be found here as and when they are needed. Thanks for the report and diagnosis efforts.
