### ISSUE TITLE
Bus stations can be demolished when not in the demolish mode.

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6659]
**_james1101_ opened the ticket and wrote:**

> Using Win 7 Ultimate
> 
> To Reproduce:
> 1. Build a bus stop.
> 2. Select the bus stop building icon and then select the demolish icon.
> 3. Click and hold on the bus stop you just built.
> 4. Press R to go out of the demolishing mode.
> 5. Release the mouse button.
> 6. The bus stop is still demolished, even though when you released the mouse it was not in the demolish mode.
> To clarify the steps, I've attached a visual version of them.
> 
> Works with: Bus and tram stops (both passenger and freight)
> Does not work with: Train stations, railway tracks and roads

**Attachments**
- [ottd-busstop-destroy-build_mode.png](https://bugs.openttd.org/task/6659/getfile/10939/ottd-busstop-destroy-build_mode.png) (50.72 KiB)

**Reported version**: _1.7.2-RC1_
**Operating system**: _Windows_

---

**Comment by andythenorth** [comment]
Probably mouse-up vs. mouse-down event handling, but I haven't checked src.
