### ISSUE TITLE
Crash on quit after running slowly

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6665]
**_Kanddak_ opened the ticket and wrote:**

> macOS 10.12.6, OpenTTD 1.7.2.
> 
> Noticed today that OpenTTD was running slowly, which I'd never noticed before (it was running fine yesterday). I decided to stop playing for a while, saved & went to quit, but upon clicking "Yes" in the "Are you sure you want to quit" dialog, the game crashed.
> 
> First try to reproduce: Opened OpenTTD, CPU usage went up & stayed up but game window never appeared. Killed the process.
> 
> Second try to reproduce: Opened OpenTTD, game opened fine but was running slowly again on the title screen. Loaded save made right before crash. Tried quitting the game. Game quit fine with no crash.

**Attachments**
- [crash.log](https://bugs.openttd.org/task/6665/getfile/10954/crash.log) (1.63 KiB)
- [crash.png](https://bugs.openttd.org/task/6665/getfile/10955/crash.png) (187.53 KiB)
- [crash.sav](https://bugs.openttd.org/task/6665/getfile/10956/crash.sav) (601.91 KiB)
- [Ninston Transport, Jul 9th, 2078.sav](https://bugs.openttd.org/task/6665/getfile/10957/Ninston+Transport%2C+Jul+9th%2C+2078.sav) (601.91 KiB)

**Reported version**: _1.7.2_
**Operating system**: _Mac OS X_

---

**Comment by TrueBrain** [comment]
I strongly suspect the system ran out of memory (OpenTTD can be memory-hungry); even more as it was running the 32bit version of OS X.

We are currently in the process of building more stable OS X binaries. Possible these can fix your issue. An experimental (HEAVILY experimental!) can be found here:

https://devs.openttd.org/~truebrain/osx-experimental/

Please give this a try. Going to close this issue now; feel free to reopen one if the problem reappears with the experimental binaries. Thank you!
