### ISSUE TITLE
Incorrect costs in bridge list after joining an AI company

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6667]
**_Chaos03_ opened the ticket and wrote:**

> After I start the simpleAI and join his company, the bridge selection window shows incorrect (too high) prices. The prices are right when I am in a separate company.

**Attachments**
- [Lekdorp Transport, 28 Jan 1980.png](https://bugs.openttd.org/task/6667/getfile/10960/Lekdorp+Transport%2C+28+Jan+1980.png) (193.34 KiB)
- [Oostmuiden Transport, 21 Jan 1980.png](https://bugs.openttd.org/task/6667/getfile/10961/Oostmuiden+Transport%2C+21+Jan+1980.png) (186.67 KiB)
- [Lekdorp Transport, 26 Feb 1980.sav](https://bugs.openttd.org/task/6667/getfile/10962/Lekdorp+Transport%2C+26+Feb+1980.sav) (65.31 KiB)

**Reported version**: _1.7.1_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Caused by an optimisation when calculating cost of all bridges:
> tunnelbridge_cmd.cpp:
```
 	/* for human player that builds the bridge he gets a selection to choose from bridges (DC_QUERY_COST)
 	 * It's unnecessary to execute this command every time for every bridge. So it is done only
 	 * and cost is computed in "bridge_gui.c". For AI, Towns this has to be of course calculated
 	 */
 	Company *c = Company::GetIfValid(company);
 	if (!(flags & DC_QUERY_COST) || (c != NULL && c->is_ai)) {
```
 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6667#comment14869_

**Comment by LordAro** [comment]
Seems to be a visual-only glitch as per frosch's previous comments, that you can only trigger by using cheats and switching companies. Perhaps not a bug (that we care about) ?
