### ISSUE TITLE
OpenTTD crash in ICU routine

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6668]
**_Samu_ opened the ticket and wrote:**

> Windows 7 Ultimate 32-bit with Service Pack 1
> 
> I was testing BorkAI on a 1024x1024 map in single player with fast forward and openttd crashes after a while.

**Attachments**
- [crash.sav](https://bugs.openttd.org/task/6668/getfile/10963/crash.sav) (663.66 KiB)
- [crash.dmp](https://bugs.openttd.org/task/6668/getfile/10964/crash.dmp) (12976.38 KiB)
- [crash.log](https://bugs.openttd.org/task/6668/getfile/10965/crash.log) (9.27 KiB)
- [crash.png](https://bugs.openttd.org/task/6668/getfile/10966/crash.png) (37.58 KiB)

**Reported version**: _1.7.2_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Information from crash.dmp:
> 0012f788 77202900 117bfd20 00000000 116c1880 ntdll+0x529ac
> 0012f7a0 7736c5f4 02a50000 00000000 117f9298 ntdll+0x52900
> 0012f7b4 006aa081 02a50000 00000000 117f9298 kernel32+0x4c5f4
> 0012f7c8 0064e1ba 117f9298 0012f7ec 006ceb4d openttd!free+0x1c [f:\dd\vctools\crt_bld\self_x86\crt\src\free.c @ 51]
> 0012f7d4 006ceb4d 117f9298 00000000 0012f8a8 openttd!uprv_free_51+0x2a
> 0012f7ec 006ceeb6 117f8290 00000000 00000800 openttd!icu_51::LayoutEngine::computeGlyphs+0x9d
> 0012f81c 006a8f0c 117f8290 00000000 00000800 openttd!icu_51::LayoutEngine::layoutChars+0x76
> 0012f884 00423f23 00000000 0f733ea8 0012f8c0 openttd!icu_51::ParagraphLayout::ParagraphLayout+0x33c
> 0012f8f0 0042481e 117f8290 00000800 000001c0 openttd!GetParagraphLayout+0xae [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\gfx_layout.cpp @ 207]
> 0012f960 00420b55 0012f988 044fe4f8 7fffffff openttd!Layouter::Layouter+0x327 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\gfx_layout.cpp @ 661]
> 0012f9a8 0055104c 00000007 00000241 000001aa openttd!DrawString+0xb8 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\gfx.cpp @ 512]
> 0012f9f0 00464301 0012fa20 00000005 044a36a0 openttd!AIDebugWindow::DrawWidget+0x135 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\ai\ai_gui.cpp @ 1233]
> 0012fa30 00462fd2 044a36a0 0438be98 00462fd2 openttd!NWidgetBackground::Draw+0x352 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\widget.cpp @ 1864]
> 0012fa3c 00462fd2 044a36a0 0438be40 00462fd2 openttd!NWidgetPIPContainer::Draw+0x11 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\widget.cpp @ 1114]
> 0012fa48 00462fd2 044a36a0 0438bbd8 00462fd2 openttd!NWidgetPIPContainer::Draw+0x11 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\widget.cpp @ 1114]
> 0012fa54 00462fd2 044a36a0 044a36a0 0046292e openttd!NWidgetPIPContainer::Draw+0x11 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\widget.cpp @ 1114]
> 0012fa60 0046292e 044a36a0 044a36a0 005db289 openttd!NWidgetPIPContainer::Draw+0x11 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\widget.cpp @ 1114]
> 0012fa84 00550be9 044a36a0 0012fae0 0012fba0 openttd!Window::DrawWidgets+0x13 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\widget.cpp @ 609]
> 0012faa8 00467ab1 00000000 044a36a0 00000258 openttd!AIDebugWindow::OnPaint+0x16 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\ai\ai_gui.cpp @ 1108]
> 0012fac0 00467b36 00000019 00000258 000001d0 openttd!DrawOverlappedWindow+0xff [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\window.cpp @ 921]
> 0012fafc 004218e9 00000000 00000019 00000258 openttd!DrawOverlappedWindowForAll+0x7e [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\window.cpp @ 938]
> 0012fb20 00421a5c 00000000 00000019 00000000 openttd!RedrawScreenRect+0x5f [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\gfx.cpp @ 1299]
> 0012fb58 0046a061 7588a21e 00ccd437 0012fb70 openttd!DrawDirtyBlocks+0x156 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\gfx.cpp @ 1389]
> 0012fb70 005dc156 00000000 00000000 0012fddc openttd!UpdateWindows+0x117 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\window.cpp @ 3057]
> 0012fbb8 0043ff92 00000001 00000001 02949748 openttd!VideoDriver_Win32::MainLoop+0x323 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\video\win32_v.cpp @ 1297]
> 0012fddc 005de44f 00000001 0012fdf8 00000000 openttd!openttd_main+0xa98 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\openttd.cpp @ 865]
> 0012fef8 006b07ac 00400000 00000000 001e1dc7 openttd!WinMain+0x99 [c:\bamboo-agent-home\xml-data\build-dir\ottd-rls-w32bit\src\os\windows\win32.cpp @ 467]
> 0012ff88 7736ef8c 7ffde000 0012ffd4 7721367a openttd!__tmainCRTStartup+0x11a [f:\dd\vctools\crt_bld\self_x86\crt\src\crt0.c @ 275]

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6668#comment14837_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Well, now ICU even crashes when using the sprite font...

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6668#comment14838_

**Comment by andythenorth** [comment]
Thanks. ICU has known issues, and there is a project underway to replace it. We're not keeping the reports relating to it open, but they can still be found here as and when they are needed. Thanks for the report and diagnosis efforts.
