### ISSUE TITLE
Cursor artefacts on Mac

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6672]
**_modmynitro_ opened the ticket and wrote:**

> The game always renders artifacts around the cursor.
> If you reposition or resize the window these artifacts will change, sometimes the cursor will not be drawn at all.
> The artifacts also change sometimes if you open dialogs and windows ingame (Close prompt, Save dialog, ...)
> If I take a screenshot the artifacts are gone, therefore I attached a photo.
> 
> High Sierra 10.13.2
> MacBook Air(13" 2014)
> Intel HD 5000

**Attachments**
- [Artifact.jpg](https://bugs.openttd.org/task/6672/getfile/10969/Artifact.jpg) (82.81 KiB)
- [Artifact2.jpg](https://bugs.openttd.org/task/6672/getfile/10970/Artifact2.jpg) (188.17 KiB)

**Reported version**: _1.7.2_
**Operating system**: _Mac OS X_

---

**Comment by DorpsGek** [comment]
**_IvanLeshev_ wrote:**

> I could not reproduce these artifacts on OpenTTD 1.8.0-RC1
> 
> Operating system: Sierra 10.12.6
> Device: MacBook Pro (13'', Early 2011)
> Processor: 2,3 GHz Intel Core i5
> Graphics card: Intel HD Graphics 3000 384 MB
> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6672#comment14880_

**Comment by andythenorth** [comment]
Can't replicate on Mac OS 10.12.6 

MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
3.5 GHz Intel Core i7
Intel Iris Plus Graphics 650 1536 MB

**Comment by andythenorth** [comment]
Got a repro on Mac OS 10.13.2 with OpenTTD 1.7.1.  Seeing the same artefacts.

**Comment by zydeco** [comment]
I can reproduce this on the release versions (tried on 1.8.0), but when I compile it myself it doesn't happen.

OpenTTD 1.8.0
macOS 10.13.4
Apple LLVM version 9.1.0 (clang-902.0.39.1)

**Comment by TrueBrain** [comment]
Would you mind trying one of the experimental OSX builds from here: https://devs.openttd.org/~truebrain/osx-experimental/ ? We updated the SDK and compiler; does that change anything?

**Comment by zydeco** [comment]
It can't reproduce it in the experimental build either

**Comment by TrueBrain** [comment]
Perfect! Than the effort of upgrading it was worth it :) Thank you!

Fixed in next release!

**Comment by Jorl17** [comment]
Sorry to bring this back from the dead, but I am seeing this issue with the latest release. I presume it is because "next release" hasn't come out yet? In such case, is this the right place to request that a small minor release be put out for MacOS?

Sorry if this is not the right place :(

**Comment by nielsmh** [comment]
@Jorl17 What OS version are you on?

Am I right in assuming this is the 20190126 nightly build for macOS 64 bit you are testing with?

**Comment by Jorl17** [comment]
I tested with https://binaries.openttd.org/releases/1.8.0/openttd-1.8.0-macosx-universal.zip (Latest Stable)
Your experimental version https://devs.openttd.org/~truebrain/osx-experimental/  fixes the issue for me.

The latest nightly build also works.

macOS High Sierra 10.13.6

**Comment by nielsmh** [comment]
Seems it might be related to how the OTTD binary is compiled, based on the previous conversation. Since all binaries from here out are being built on a real macOS system with current development tools, it probably won't resurface.
