### ISSUE TITLE
Game crashes with AI

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6674]
**_Theennus_ opened the ticket and wrote:**

> Everytime I start a game with AI (mostly NoCAB and NoNoCAB) the game crashes when it's time for the AI to show in the game. I used the default 730 days and also change it to 30 days and always crashes...

**Reported version**: _1.7.2_
**Operating system**: _Mac OS X_

---

**Comment by DorpsGek** [comment]
**_TrainFanatic_ wrote:**

> Is it possible to include the crashlog for people to see?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6674#comment14883_

**Comment by TrueBrain** [comment]
Please always include a crash.log (and dmp and sav and png) when creating a crash report; with only a description, we have no way of reproducing the issue.

Going to close the ticket, as too much time has gone by to still retrieve the information. Feel free to open an new issue if you have the crash again and can supply us with the indicated files. Thank you.
