### ISSUE TITLE
Crash when switching language in game

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6675]
**_PaulC_ opened the ticket and wrote:**

> r27967 crashes when switching to Hebrew language in game.
> 
> I keep getting "secure connection failed" when trying to post this with files attached, so trying again without...

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_PaulC_ wrote:**

> Sorry, I've tried attaching the crash files down here but it's not working. Hopefully someone else can reproduce this crash?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6675#comment14839_

**Comment by DorpsGek** [comment]
**_Samu_ wrote:**

> Crash files, tested on 1.7.2, Windows 10.

**Attachments**
- [9x.lzma2.1t.512md.192w.ons.7z](https://bugs.openttd.org/task/6675/getfile/10976/9x.lzma2.1t.512md.192w.ons.7z) (396.85 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6675#comment14851_

**Comment by DorpsGek** [comment]
**_PaulC_ wrote:**

> It's not just Arabic, I get a similar crash when trying to select Hebrew on the main menu. Something to do with right-to-left text?

**Attachments**
- [crash.7z](https://bugs.openttd.org/task/6675/getfile/10977/crash.7z) (1182.16 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6675#comment14852_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Related to these?
> #6563
> #6655

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6675#comment14861_

**Comment by andythenorth** [comment]
Thanks. ICU has known issues, and there is a project underway to replace it. We're not keeping the reports relating to it open, but they can still be found here as and when they are needed. Thanks for the report and diagnosis efforts.
