### ISSUE TITLE
Fast Forward Button

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6677]
**_Vantri_ opened the ticket and wrote:**

> Hi!
> In OpenTTD 1.7.2 for win9x/2000/XP "Fast Forward the game" button does nothing. :(

**Reported version**: _1.7.2_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_3298_ wrote:**

> Not a bug, working as intended. The fast forward button makes the game go as fast as the processor can, and apparently your processor is already maxed out at normal speed.
> Note that OpenTTD will mostly use a single thread, so multiple cores are next to useless; single-core performance is what OpenTTD needs. Writing a savegame to disk happens in a separate thread, and Cargodist uses another thread to calculate the cargo flow across the transport network; everything else (drawing, moving vehicles, updating the landscape, etc.) is done on a single core. If that can only go e.g. 1 GHz, then big maps and/or many vehicles will quickly hit the performance ceiling.
> Upgrade your hardware, or reduce map size and vehicle count (not zooming out as far as possible may help as well by reducing the drawing load), and you'll notice that fast forward does work.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6677#comment14849_

**Comment by DorpsGek** [comment]
**_Vantri_ wrote:**

> No speed increase is seen even on smallest 64*64 map from the very start of the game, when there are no transport networks at all. Fast forwarded day still lasts exactly same time as usual day.
> I retrieved my old openttd 1.3.0 for comparison and in that version speed dramatically increases even in big map.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6677#comment14850_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Turn 'full animation' off.  

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6677#comment14856_

**Comment by DorpsGek** [comment]
**_Vantri_ wrote:**

> Elaborate please.
> Currently I'm playing 1.3 without turning off anything.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6677#comment14860_

**Comment by andythenorth** [comment]
Thanks for reporting this.  There are reported issues with ffwd, but they vary widely depending on platform, hardware etc.  I'm closing this one as there we close issues that have no obvious current fix, but they stay here in the tracker and can be found if we need them in future.  Thanks for the report.
