### ISSUE TITLE
Add "RUB" as new currency

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6678]
**_PaulC_ opened the ticket and wrote:**

> Currency used by Russia since 1998 is the Russian Ruble (RUB), not (RUR). Current real-world exchange rate is approx. £1 x 80 which is higher than the OTTD rate.
> 
> Also (and this mainly affects the UK English translation), currencies are mostly named in the singular which means these two are incorrect:
> 
> \* Russian Rubles -- should be Russian Ruble
> \* Estonian Krooni -- should be Estonian Kroon

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> There are 3 issues here.  For 2 of them:
> • Exchange rates won't be maintained :)
> • Translations should be fixable via https://translator.openttd.org/
> 
> I've left the issue open as RUB has replaced RUR in real life.  This could be changed in the translation, but also the string names should then change.  But that would need a migration of all translated strings, or the existing translations would be lost.  I can't see that getting fixed, but I can't really just close this either.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6678#comment14855_

**Comment by DorpsGek** [comment]
**_PaulC_ wrote:**

> Exchange rates don't have to be actively maintained but they also don't need to be set in stone, no good reason why they couldn't or shouldn't be changed when it makes sense to do so.
> 
> For RUR/RUB, would it really be necessary to change the string name? While the discrepancy may not be ideal it doesn't really matter what name you give to the strings.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6678#comment14857_

**Comment by DorpsGek** [comment]
**_andythenorth_ wrote:**

> Suggestion: add a new currency for RUB.  RUB wasn't just a change of ISO code, RUB and RUR are two different currencies. 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6678#comment14862_

**Comment by ldpl** [comment]
One Ruble is enough imo :) 
Also people get used to exchange rates and prices so constantly changing them would be annoying. Especially on goal servers where goal is set in one currency. But having some rates changed once in a while for a good reason is ok I guess.

**Comment by nielsmh** [comment]
Wouldn't a better solution actually be to generalize the "Euro system", so instead of currencies having a simple "gets replaced with Euro in year 2000" flag, they have a "replaced by other currency" and "replaced year" field, so DEM becomes EUR in 2000, RUR becomes RUB in 1998, and EEK becomes EUR in 2011?

**Comment by TrueBrain** [comment]
As a new ticket, sure :) Would be even better if it could be done with a NewGRF or something, as constant code changes for this feels silly ;P

But first just adding the currency seems to easiest step forward; after that we can overengineer it :D

**Comment by TrueBrain** [comment]
Fixed!
