### ISSUE TITLE
menu bars disappear if enable windows screen scaling on high dpi monitors

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6682]
**_dealer_ opened the ticket and wrote:**

> If using Windows7 with a high dpi monitor and enable screen scaling (125%) the top and bottom menu bar ingame will disappear(only on fullscreen mode), so the game is not playable.
> 
> workaround is deactivating image scaling for that moment.
> 
> Microsoft provide some Information on that topic.
> https://msdn.microsoft.com/library/windows/desktop/mt843498(v=vs.85).aspx(d=robot)
> 

**Reported version**: _1.7.2_
**Operating system**: _Windows_

---

**Comment by TrueBrain** [comment]
Possibly duplicate of #6567.

**Comment by TrueBrain** [comment]
Possibly duplicate of #6057.

**Comment by LordAro** [comment]
Is this still an issue? I think there's been some high-dpi related work since this issue was raised.

This is linked from one of the duplicates, for helpfulness:
https://docs.microsoft.com/en-gb/windows/desktop/hidpi/high-dpi-desktop-application-development-on-windows

**Comment by glx22** [comment]
Found another probably useful link from the one in LordAro's comment:
https://blogs.windows.com/buildingapps/2017/05/19/improving-high-dpi-experience-gdi-based-desktop-apps/

Edit: OpenTTD seems to not be concerned by this as we use DIB

**Comment by nielsmh** [comment]
One issue that can occur in high-DPI is mouse coordinate scaling, i.e. clicks are sent to different coordinates than the user sees the cursor. Probably not a potential issue right now with fully software mouse cursor.

**Comment by TheHendla** [comment]
originally dealer writing here: with version 1.8.0 the issue seems to be fixed. cannot reproduce the issue anymore.

**Comment by TrueBrain** [comment]
Thank you for getting back to us :) Closing issue in that case :) Tnx!
