### ISSUE TITLE
DirectMusic hanging notes with hardware synths

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6683]
**_nielsm_ opened the ticket and wrote:**

> When using the DirectMusic driver with an external (hardware) MIDI synth, sometimes when exiting the game it leaves hanging notes. Adding a short sleep after calling Stop seems to avoid this problem, likely by allowing DMusic to process its own messages.

**Attachments**
- [dmusic-hanging-notes.r27967.patch](https://bugs.openttd.org/task/6683/getfile/10980/dmusic-hanging-notes.r27967.patch) (0.63 KiB)

**Reported version**: _trunk_
**Operating system**: _Windows_

---

**Comment by nielsmh** [comment]
Obsoleted by merge of #6787.
