### ISSUE TITLE
Mimic original DOS behavior regarding music more closely

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6684]
**_nielsm_ opened the ticket and wrote:**

> The premise of this patch is that the DOS version of TTD is primary canon, while the Windows version is a port that didn't get everything perfectly accurate. I.e. when using data from the original game, it should act as closely to the DOS version as reasonably possible. However the game data must be used without direct modification.
> 
> This patch does three things:
> 1) Make the title screen music loop tightly, no pause between loops at all
> 2) Remove the long silence in "Can't Get There From Here", which wasn't there in the DOS version
> 3) Not play the theme song during regular gameplay
> 
> This patch only implements the changes for DirectMusic, since I don't have any systems at hand for attempting to replicate on. I quickly gave up on trying to do anything with the Win32 (MCI) music driver since MCI Sequencer appears to be broken in Windows 10, taking 5+ seconds just to load a single song.
> 
> Items 1 and 2 are achieved by adding new annotations to the orig_win.obm file that describes the MIDI timestamps the actual music runs from and to. This allows the music driver to accurately skip the unwanted silences. There is currently an assumption that this will only be used with the original files, to be fully general the code will need at least a partial MIDI file parser to read out the actual time division of the file.
> 
> Item 3 is handled by simply special-casing the first entry in the .obm file ("theme"), so if it exists it gets taken out of rotation from the "All" playlist, but still gets used on the title screen. Additionally, the music is restarted when changing game modes, so the theme song doesn't bleed into the gameplay.

**Attachments**
- [music-accuracy.v1.r27967.patch](https://bugs.openttd.org/task/6684/getfile/10981/music-accuracy.v1.r27967.patch) (16.33 KiB)

**Reported version**: _trunk_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_nielsm_ wrote:**

> I think this will also close #6582

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6684#comment14865_

**Comment by DorpsGek** [comment]
**_nielsm_ wrote:**

> Cleaned up version of the patchset, split out into multiple logical changes. Application order is music-1, music-2, music-3, music-4. The dmusic-3 patch also depends on patches in #6683 and #5807.

**Attachments**
- [music-1-mainmenu_force_theme.r27980.patch](https://bugs.openttd.org/task/6684/getfile/10985/music-1-mainmenu_force_theme.r27980.patch) (2.52 KiB)
- [music-2-theme_not_ingame.r27980.patch](https://bugs.openttd.org/task/6684/getfile/10986/music-2-theme_not_ingame.r27980.patch) (1.22 KiB)
- [music-3-loopandcut.r27980.patch](https://bugs.openttd.org/task/6684/getfile/10987/music-3-loopandcut.r27980.patch) (3.36 KiB)
- [music-4-driver_playsong_prototype.r27980.patch](https://bugs.openttd.org/task/6684/getfile/10988/music-4-driver_playsong_prototype.r27980.patch) (9.42 KiB)
- [dmusic-3-loopandcut.r27980.patch](https://bugs.openttd.org/task/6684/getfile/10989/dmusic-3-loopandcut.r27980.patch) (1.59 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6684#comment14871_

**Comment by DorpsGek** [comment]
**_nielsm_ wrote:**

> If the changes in #6685 are applied, this additional patch to the DirectMusic driver will use the MidiFile class to read correct time scale values from the MIDI file, instead of assuming only the TTD-Windows files are ever used.

**Attachments**
- [dmusic-4-midifile.r27980.patch](https://bugs.openttd.org/task/6684/getfile/10992/dmusic-4-midifile.r27980.patch) (1.72 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6684#comment14873_

**Comment by nielsmh** [comment]
With #6839 all changes in the original patches have been implemented.
