### ISSUE TITLE
Win32 music driver rewrite

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6685]
**_nielsm_ opened the ticket and wrote:**

> This is a complete rip-out and rewrite of the Win32 music driver. The current Win32 music driver uses MCI, which is poorly supported on modern Windows versions, and causes large pauses between songs. The DirectMusic driver doesn't have those issues, but it's still a technology marked "deprecated" and not shipped with current Windows SDK versions.
> 
> This rewrite implements a lower level driver with a new parser for MIDI files, and manages timing to send the data to the synthesizer in correct order. The MidiFile class implemented is intended to be cross-platform and could be used to implementing similar lower-level playback on other platforms. Handling the raw MIDI data directly should also allow for reading music from other sources than standard MIDI files, e.g. it may allow reading the ROLAND.CAT/GM.CAT files from the DOS version of TTD, to use that as a music source instead.

**Attachments**
- [w32music-1-rewrite.r27980.patch](https://bugs.openttd.org/task/6685/getfile/10990/w32music-1-rewrite.r27980.patch) (30.14 KiB)
- [w32music-2-rewrite-projectfiles.r27980.patch](https://bugs.openttd.org/task/6685/getfile/10991/w32music-2-rewrite-projectfiles.r27980.patch) (28.60 KiB)

**Reported version**: _trunk_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_nielsm_ wrote:**

> This depends on the changes in #6684, except for the DirectMusic part of the patch.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6685#comment14872_

**Comment by nielsmh** [comment]
This is now contained in PR #6749 and can be closed.

**Comment by michicc** [comment]
Was merged.
