### ISSUE TITLE
Signal removal with (CTRL+)drag not possible from level crossing

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6686]
**_Transportman_ opened the ticket and wrote:**

> Using r2799, I cannot remove signals while dragging if I start dragging from a level crossing and following the rail, stating that there is no railway track.

**Reported version**: _trunk_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_james1101_ wrote:**

> Can reproduce, OpenTTD 1.7.2-RC1, Win 7 Ultimate

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6686#comment14875_

**Comment by DorpsGek** [comment]
**_IvanLeshev_ wrote:**

> Can reproduce, OpenTTD 1.8.0-RC1, MacOS Sierra

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6686#comment14881_

**Comment by andythenorth** [comment]
For clarity: signals can't be built starting on crossings, so nor can they be removed starting from crossings. I think that's TMWFTLB to change. 

However the error message could be more helpful.  I am unsure that will get changed, but I'll leave this open.  If it's not changed by 2021 or so, I'd recommend closing it as 'not happening' :)

**Comment by TrueBrain** [comment]
Feels weird, you cannot drag from a crossing. Feels like a bug :P But better messages goes first!

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
