### ISSUE TITLE
Random game crash

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6688]
**_bnegrut_ opened the ticket and wrote:**

> Random game crash
> 
> OS Windows 10, 64 bit
> Game version 1.7.2. 64 bit
> 
> Crash at: Mon Mar 19 19:27:44 2018
> In game date: 1922-10-08 (16)
> 
> Crash reason:
>  Exception: C0000005
>  Location:  00007FF70AAB5440
>  Message:   <none>
> 
> OpenTTD version:
>  Version:    1.7.2 (0)
>  NewGRF ver: 17286d2d
>  Bits:       64
>  Endian:     little
>  Dedicated:  no
>  Build date: Dec 24 2017 12:25:35
> 

**Attachments**
- [crash.log](https://bugs.openttd.org/task/6688/getfile/10994/crash.log) (13.31 KiB)
- [crash.png](https://bugs.openttd.org/task/6688/getfile/10995/crash.png) (1020.56 KiB)
- [crash.sav](https://bugs.openttd.org/task/6688/getfile/10996/crash.sav) (1754.59 KiB)

**Reported version**: _1.7.2_
**Operating system**: _Windows_

---

**Comment by DorpsGek** [comment]
**_bnegrut_ wrote:**

> Crashed again today. DMP file will not upload.

**Attachments**
- [crash.log](https://bugs.openttd.org/task/6688/getfile/10997/crash.log) (13.42 KiB)
- [crash.png](https://bugs.openttd.org/task/6688/getfile/10998/crash.png) (1400.83 KiB)
- [crash.sav](https://bugs.openttd.org/task/6688/getfile/10999/crash.sav) (1754.59 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6688#comment14876_

**Comment by DorpsGek** [comment]
**_3298_ wrote:**

> From the crash.log of both crashes:
>     Tick 14454: GRF config changed
>     Removed NewGRF: GRF ID 52455400, unknown GRF
> There is a reason changing NewGRFs is hidden behind a openttd.cfg-only option and displays a red warning window (which should also have told you NOT to report issues that happen after you do so): Changing NewGRFs can wreak all kinds of havoc in a savegame, including setting it up so it crashes later. That appears to be what happened here, so ... warranty void, I guess.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6688#comment14877_

**Comment by DorpsGek** [comment]
**_bnegrut_ wrote:**

> Now I understood that the cause is a GRF, specifically GRF ID 52455400, checksum 1600687C50C5AB1E72EDD487CAD50E2A, filename: coded_by_aegir._artwork_by_aegir-1/ae_cityw.grf (md5sum matches). 
> What I can not understand is why a GRF that is not loaded cause such havoc. Also, as far as I remember I did not load it for this game. Is there a way to check if this GRF was loaded at some point in the game?
> 
> Attached is a screenshot with the GRFs in use in game. 
>  

**Attachments**
- [Blue Moon Transport, May 30th, 1936.png](https://bugs.openttd.org/task/6688/getfile/11000/Blue+Moon+Transport%2C+May+30th%2C+1936.png) (1610.24 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6688#comment14878_

**Comment by DorpsGek** [comment]
**_3298_ wrote:**

> That would be the gamelog, which got thrown into both crash.log files. As far as I know, there's also a console command that outputs the gamelog of a running game, but why bother with that when it's right there. - It's the section I took those lines from. The rest of the gamelog tells me that the game was started with all the GRFs I see listed in your screenshot plus that missing one at the end of the list, using version 1.7.1. On tick 1280 (approximately in-game day 18) you switched to version 1.7.2. On tick 14454 (approximately day 192, i.e. after almost six and a half in-game months) the GRF got removed. The gamelog section of both crash.log files is identical, so I guess that after you experienced the first crash, you reloaded a save that was made after the GRF was already removed (e.g. the emergency save created during the crash).
> I'm not the developer of that GRF (or even a GRF dev at all), so I don't know how it's coded (and I'm not familiar with OpenTTD's NewGRF handling code either) and therefore don't know if the following even has a chance of working, but my first attempt at fixing this savegame would be adding the GRF back (at least you were able to identify the missing one, so there's that). Considering that it's a fairly old and possibly a relatively simple GRF just providing station graphics, it might just work, but that's unfortunately far from guaranteed.
> GRFs are deeply integrated into the system, so they can have great influence on the game state. When GRFs are changed, a lot of lists get updated, but when the stuff in the lists has been used already, we are screwed. Then some hilarious things can happen, like lone helicopter rotors swimming across the ocean, or a coal plant's exhaust plume pulling into a bus station. But things can go more wrong than that - try loading passengers into that exhaust plume, for instance. They'll probably choke, as does the game that assumed the plume was a bus instead. Though I can't think of a reason why the absence of a station set would lead to a crash (and I can't check the stacktrace to see what the game was doing, because unlike Linux, Windows stacktraces need tools to decipher), there appears to be one.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6688#comment14879_

**Comment by DorpsGek** [comment]
**_bnegrut_ wrote:**

> New Game, without changing any GRF, still crash.

**Attachments**
- [crash.png](https://bugs.openttd.org/task/6688/getfile/11005/crash.png) (1043.24 KiB)
- [crash.log](https://bugs.openttd.org/task/6688/getfile/11006/crash.log) (13.78 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6688#comment14882_

**Comment by bnegrut** [comment]
Another new game. Still random crash.

[crash.log](https://github.com/OpenTTD/OpenTTD/files/1975692/crash.log)
![crash](https://user-images.githubusercontent.com/38473675/39648733-ebbfba24-4feb-11e8-9b30-c5ae75b074b3.png)

**Comment by glx22** [comment]
Without the dmp it will be impossible to trace the crash.

**Comment by janisozaur** [comment]
Out of curiosity: why is the provided stack trace insufficient?

**Comment by glx22** [comment]
Because, for some reasons, the provided stack trace is not decoded. and with just the addresses it's hard to know where the crash happened.

**Comment by bnegrut** [comment]
Unfortunately, i can't upload the .dmp file.
It is available here https://drive.google.com/drive/folders/1yaz_diStSmebXJpz2sG9yakPrXxCx5eU?usp=sharing. Please let me know if you can access it.

Thank you

**Comment by janisozaur** [comment]
@glx22 yes, I saw, but you didn't answer my question. To rephrase what I meant: why can't you load the process in a debugger, attach the symbols and symbolise the trace? Or just symbolise it with stack walker, skipping the debugger?

@bnegrut as long as it is smaller than 10MiB, GitHub will accept files with names ending in `.zip`, `.txt`, `.jpg`, `.png`, so renaming or packing should suffice.

**Comment by bnegrut** [comment]
Understood.
Reattached, as an archive.
[crash.zip](https://github.com/OpenTTD/OpenTTD/files/1977824/crash.zip)

**Comment by andythenorth** [comment]
Thanks.  ICU has known issues, and there is a project underway to replace it.  We're not keeping the reports relating to it open, but they can still be found here as and when they are needed.  Thanks for the report and diagnosis efforts.
