### ISSUE TITLE
crash when first boat reaches destination for subsidised transport

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6691]
**_gemonta_ opened the ticket and wrote:**

> Hi,
> Opened crashed just when my boat was reaching a quay for the first time for a subsidised transport. find attached necessary files. Thanks for your help and effort, opened is awesome!

**Attachments**
- [crash.log](https://bugs.openttd.org/task/6691/getfile/11008/crash.log) (1.32 KiB)
- [crash.sav](https://bugs.openttd.org/task/6691/getfile/11009/crash.sav) (0.01 KiB)
- [crash.png](https://bugs.openttd.org/task/6691/getfile/11010/crash.png) (621.55 KiB)
- [autosave7.sav](https://bugs.openttd.org/task/6691/getfile/11011/autosave7.sav) (477.70 KiB)

**Reported version**: _1.7.2_
**Operating system**: _Mac OS X_

---

**Comment by PeterN** [comment]
Crash log says it ran out of memory. Does this issue reoccur if you load the autosave and let it run? You're running the 32bit build on a 64bit system, so can you try the 64bit build and see if that "fixes" it?

**Comment by andythenorth** [comment]
Thanks for reporting this.  We don't currently have other reports of this, so I don't believe it to be a common issue.  We close bug reports that aren't common or easily reproduced, but they stay here in the tracker and can be found if we need them in future.  Thanks for report and diagnosis.
