### ISSUE TITLE
Deleting a company that has subsidies awarded to them deletes the subsidies as well.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#6697]
To Reproduce:
NOTE: You will need SimpleAI from the content download to complete the following steps:
1. Start a new game with 'SimpleAI' as the first AI player, Make sure to turn up "The chance of taking subsidies" setting to 10 for almost guaranteed attempt of subsidy.
2. Wait for two **passenger** subsidies to appear. Passengers because that is easier for SimpleAI to handle.
3. Start the ai. ('start_ai simpleai subsidy_chance=10' in console), and open the subsidies window and the list of companies (list of companies: open a company stats graph, open the company key, then close the graph window)
4. Wait until **one** of the subsidies gets awarded to the AI company, and then Pause the game. If both subsidies get awarded by the same company, you may have to start over.
5. Once you reach that point, watch the subsidy window as you enter 'stop_ai 2' into the console.
BUG: The subsidy awarded to the company that just got deleted, gets deleted as well.
Expected: The subsidy awarded to the company that just got deleted, should turn back into a subsidy on offer, with the original offer expiry date; if that has already passed, then the subsidy is deleted.

I've attached a picture and a save file ([subsidy_error.zip](https://github.com/OpenTTD/OpenTTD/files/1888247/subsidy_error.zip)) to show the bug. In the picture, "Key to company graphs" is renamed to "Companies", but it will be the former in game. In the save file, all of the previous four steps are already completed, you just have the last step to do.
![ottd-subsidy-deleted-on-company-deletion](https://user-images.githubusercontent.com/37945304/38475861-50c967d4-3b70-11e8-8164-c0fe28cda6e4.png)

**Comment by PeterN** [comment]
The subsidy is deleted because it was assigned to the company and is no longer a subsidy on offer.

**Comment by frosch123** [comment]
I see no reason why subsidies should be reoffered.
They are also not reoffered when the company just sells their vehicles.
