### ISSUE TITLE
Developer docs updates for git / github move

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/OpenTTD#6698]
List of docs that will need updated following move to git and github:

* https://wiki.openttd.org/FAQ_development
* the various 'compiling for x' pages, e.g.
  * https://wiki.openttd.org/Compiling_on_(GNU/)Linux_and_*BSD
  * https://wiki.openttd.org/Compiling_on_Mac_OS_X
* readme.txt (for svn, and also flyspray), e.g. https://github.com/OpenTTD/OpenTTD/blob/master/readme.txt#L60
* https://wiki.openttd.org/Requested_features#How_to_request_a_feature

I will do some of these if nobody else can/will.  But I have some other stuff on right now (OpenTTD and IRL).

**Comment by frosch123** [comment]
Probably also needs deleting of about half of the static pages on www.openttd.org

**Comment by TrueBrain** [comment]
I did frontpage voodoo during migration already. Not sure if there were any other pages that need love?

**Comment by frosch123** [comment]
https://www.openttd.org/en/about has a link to vcs.openttd.org
https://www.openttd.org/en/development has two links to bugs.openttd.org

**Comment by TrueBrain** [comment]
README should be done in markdown style to make GitHub happy.

**Comment by TrueBrain** [comment]
Fixed links in above URLs on www.openttd.org.

**Comment by TrueBrain** [comment]
Any further progress here? Do we want to keep this issue around? Seems only wiki needs further updating?

**Comment by andythenorth** [comment]
Fixed 
* https://wiki.openttd.org/FAQ_development
* https://wiki.openttd.org/Requested_features
* https://wiki.openttd.org/Compiling_on_Mac_OS_X#Configure
* README.md

I added 'update needed' notes to the Linux compiling page, it's a wiki, calling that done for now:
* https://wiki.openttd.org/Compiling_on_(GNU/)Linux_and_*BSD#Arch_Linux

**Comment by andythenorth** [comment]
Done, enough.
