### ISSUE TITLE
Startup ticks don't allow multiple DoCommands

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/OpenTTD#6712]
Part of issue #5304, but deserving his own ticket:

**_Yexo_ wrote:**

> When generating a new game a GameScript should have 2500 ticks to initialize everything it wants as long as it doesn't call Sleep(). However this is currently broken since not only a sleep but also any DoCommand will stop the initialization and start the game. These 2500 ticks could be increased easily, it then doesn't take any time at all to call SetCargoGoal on all towns. I've discussed this with frosch and we both think this is a better solution than introducing a function that works on all towns since such a function would be pretty limited.

---

**Comment by LordAro** [comment]
Still relevant, and should be a relatively simple change, if I understand the issue correctly

**Comment by TrueBrain** [comment]
Mostly solved with the introduction of `GSAsyncMode`. In this mode, you can queue commands and will not be scheduled out. It is not exactly what was asked for, but most likely the best we can do within the current constraints of the system.

Given in 4 years nobody mentioned this as an issue anymore, and given we now have something that kinda solves it, going to close this bug as solved.
