### ISSUE TITLE
GSTown.ExpandTown (town_id, houses ) adds up to ten times less houses than he should add.

### ISSUE THREAD

**Issue by agentw4b** [OpenTTD/OpenTTD#6724]
"GSTown.ExpandTown (town_id, houses )"  sometimes adds 2 times less buildings, sometimes adds up to 10 times less buildings.

**Comment by TrueBrain** [comment]
Please be more descriptive in your bug report. Just repeating the title rarely makes a good report. Think about information like:

- What version of OpenTTD are you using?
- Do you have an example snippet of what you were trying?
- What did you expect?
- What did you get?
- Do you have a screenshot to show what you mean?

Please help us help you. Be descriptive.

Feel free to reopen this issue if you did just that. Thank you!
