### ISSUE TITLE
Warning during compiling under GCC 7

### ISSUE THREAD

**Issue by xendistar** [OpenTTD/OpenTTD#6729]
I got the following warning when I ran make with GCC 7.2.0 under Linux.

```
In file included from /usr/include/string.h:494:0,
                 from /usr/include/c++/7/cstring:42,
                 from /home/mit/ottd-source/openttd-1.8.0/src/stdafx.h:85,
                 from /home/mit/ottd-source/openttd-1.8.0/src/newgrf.cpp:12:
In function ‘void* memset(void*, int, size_t)’,
    inlined from ‘ChangeInfoResult StationChangeInfo(uint, int, int, ByteReader*)’ at /home/mit/ottd-source/openttd-1.8.0/src/newgrf.cpp:1975:13:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:71:70: warning: ‘void* __builtin_memset(void*, int, long unsigned int)’: specified size between 18446744073709551361 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
   return __builtin___memset_chk (__dest, __ch, __len, __bos0 (__dest)); 

```
I am running SolydXK 10 (Based on Debian testing) and downloaded the source from the OTTD web site. The game starts and appears to run ok but that is about all I have done to present

**Comment by TrueBrain** [comment]
Do you have a bit more information for us?

For example
- What compiler are you running? If you can copy the result of `./configure` that would be very welcome (as it contains all that information). (come to think of it; not the version of the compiler. Please add that too :D)
 - Did this happen on older code that you know?
 - "Downloaded the source from OTTD web site" is also very vague to me; which source? which version?

I assume you meant that there was a warning during compilation; an error would mean it stops compiling. But as you say you can run the game fine, I am going to assume you meant warning :)

Please help us help you, and be verbose. This snippet sadly enough is not much to go on. Thank you!

**Comment by xendistar** [comment]
Hi TheBrain, apologise for the admission, first time I have compiled from source for anything.

Your first question, I still had the terminal open that ran the ./configre, hopefully this is what you wanted.
[dot-slash-configure-output.txt](https://github.com/OpenTTD/OpenTTD/files/1916993/dot-slash-configure-output.txt)

I believe my compiler is gcc 4:7.2.0

I have no idea if this has happened with older version of the source, as this was my first attempt.

Here where I downloaded the source from (version 1.8.0)

https://binaries.openttd.org/releases/1.8.0/openttd-1.8.0-source.tar.gz

I would tend to agree that the output I have shown above is a warning of some kind although there is no explicit wording saying warning. Yes the program starts and seem to run but I have only had chance to run it for about 15 minutes and no issues were seen in that time.

Hope this helps

**Comment by TrueBrain** [comment]
Thank you! Exactly the information we needed :)

It seems that you can ignore this warning safely, but we will see if we can fix it properly :)

**Comment by TrueBrain** [comment]
Bogus warning by GCC 7. We do `byte` - `byte` under the condition that the first is bigger than the latter. Still it sees a range of -1 .. -254 as possible values for memset. This is bogus. Possible fix is to introduce a temporary variable to put the value in; also cleans up the code a tiny bit.

**Comment by TrueBrain** [comment]
Fixed! Compiling the latest code no longer shows this warning.

Thank you for the report!
