### ISSUE TITLE
Offer offical Snap

### ISSUE THREAD

**Issue by JakobDev** [OpenTTD/OpenTTD#6734]
It would be nice, if OpenTTD has a official Snap. Snaps are a good Way to distribute Programs for many Linux Distoros, so you don't have build a Package for each Distro. And the User will get automatic Updates without a PPA or something else who can crash your Package Manager.

**Comment by PeterN** [comment]
What about flatpak? Any other competing systems? I don't know who the 'winner' is in this case. I do think it's a reasonable idea, though.

**Comment by TrueBrain** [comment]
Sounds like a cool idea! If you are willing to maintain it, please do make a Pull Request for it! As long as not many things have to change to make it happen, I am sure it will find its way. And of course if someone wants to do the same for flatpak, that would be lovely.

Going to close this ticket now, as it is currently not part of our roadmap; but feel free to rebuttal (or better yet, make a Pull Request). Thank you!
