### ISSUE TITLE
Only possible to build station next to competitor by using CTRL+click

### ISSUE THREAD

**Issue by jursky** [OpenTTD/OpenTTD#6742]
Hello, 

I don't know if it's actually a bug or not, but I discovered that it is possible to build a rail station directly next to other player airport (see attached screenshot) using ctrl+click (building a station with possibility of combining two stations into one).

It is **not possible** to build station directly by just clicking (without ctrl), because that way an popup pops up saying that: 
**Can't build railroad station here...
Adjoins more than one existing station/loading area**

So I think it should not be allowed even using ctrl+click. If I am wrong, just close/delete this issue. :)

![adjoined_heli_and_train](https://user-images.githubusercontent.com/520423/39087331-a4336904-459f-11e8-8412-ab547479325c.JPG)

Version 1.8.0, playing on Rpi 1/b+, custom build (without any changes to the source code).

**Comment by TrueBrain** [comment]
It is a bug for sure; the question is, is the need for CTRL a bug, or that you can place it there a bug :D

I think that you need to press CTRL is a bug; as why shouldn't you be able to build there :)

**Comment by LordAro** [comment]
Knew I'd seen this before somewhere - basically duplicates #4185 , not that that has any reasonable resolution

**Comment by topalavlad** [comment]
If everyone agrees that CTRL should not change the behavior and the user should not be able to build the station there regardless of the modifier key, I'd like to give it a try and fix this behavior.

**Comment by planetmaker** [comment]
I think the desired behaviour is: you can build a station there without need for CTRL+click:

As you are two companies, you are building two completely separate stations. Thus you should simply click the tile and get your station. Thus effectively:
* keep the possibility to build stations there
* remove the need for CTRL+click

**Comment by andythenorth** [comment]
I am +1 to Planetmaker's proposal.

**Comment by Hopman** [comment]
I was looking into this and this is the solution I found.

I'm still new to C++ and this project, so any feedback is welcome.
