### ISSUE TITLE
[Suggestion]Why not add  CEF(Chromium Embedded Framework) to OpenTTD?

### ISSUE THREAD

**Issue by co-owner** [OpenTTD/OpenTTD#6747]
Why not add  CEF(Chromium Embedded Framework) to OpenTTD?

**Comment by LordAro** [comment]
No.

**Comment by LordAro** [comment]
To elaborate slightly further, why? What possible reason could there be to adding this?

**Comment by dpk** [comment]
why would you even want this tbh

**Comment by TrueBrain** [comment]
Sorry @co-owner for the somewhat rude answers above. I do not disagree with the closing, but the tone could be a bit more friendly.

That said, how it goes in many Open Source communities, just a simple solution to an unknown problem is rarely a good suggestion. So let me put the question back to you:

How would you feel/see that CEF would add something of value to OpenTTD? I currently cannot see how it could help, but of course I can be convinced.

But yes, currently I do not see how this increases the value of OpenTTD, so we are going to pass on it for now. But, as always, feel free to rebuttal. Just please describe what you are trying to solve; not a random solution :) Thank you!
