### ISSUE TITLE
Vehicles hidden status is not saved in save games.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#6759]
I have found out that if I,
1. start a new game,
2. open the available vehicles list (go into vehicles list and select Available vehicles),
![image](https://user-images.githubusercontent.com/37945304/39399593-34161bac-4ae6-11e8-8fff-f91c7cf6b5dd.png)
3. hide some vehicles,
![image](https://user-images.githubusercontent.com/37945304/39399599-509edffc-4ae6-11e8-92e2-2163e22d1524.png)
4. save the game and load it back, and
5. check the hidden status of the vehicles that I hid before,
![image](https://user-images.githubusercontent.com/37945304/39399606-75d901f8-4ae6-11e8-803f-18ee3075d10a.png)

that the vehicles that I hid from the list are shown again. This is unexpected; the expected outcome is that the vehicles would remain hidden. No NewGRF is required to do this although the attached screenshots have NewGRFs in them.
I was using OpenTTD 1.8.0 on Win 7 Ultimate when that happened.

Possible solution: Make the list of hidden vehicles one of the things saved and loaded in a save game.

**Comment by TrueBrain** [comment]
Thank you for the very clear bug report :)

In general these kind of things are currently not stored in the Savegame, but I agree that it is not what you would expect. We will have to think about how to fix it properly, but I like your suggestion :)

**Comment by J0anJosep** [comment]
I cannot reproduce the bug.
@James103  Did you save the game properly and then loaded the save game that had those engines hidden?

**Comment by James103** [comment]
I was able to reproduce the bug without any NewGRFs.
1. Start a new game without NewGRFs.
2. Go into the vehicle list window for some vehicle type (example: Trains).
3. Open the available vehicles list for that vehicle type.
4. Hide the first 4 vehicles in the list.
5. Save the game (go into Save game, and select Save).
6. Load the game back into OpenTTD (go into Load game, select the save game you just saved, and select Load).
7. Go into the vehicle list window for the vehicle type you hid vehicles in (example: Trains).
8. Open the available vehicles list for that vehicle type.
9. You will see that the vehicles you hid from the list are shown again.

**Comment by J0anJosep** [comment]
@James103 I followed your indications and cannot reproduce the bug. The vehicles I hid are still hidden when I reloaded the savegame.
Before looking into other possibilities and with no intention of being rude, I will insist: Can you try again hiding engines on a game, saving it with a custom name and reloading it?

**Comment by TrueBrain** [comment]
You are right @J0anJosep . Hidden status is stored in the savegame (ever since 1.5.0 .. I should get my facts straight), and I too cannot reproduce it with the steps above.

What I did was: download latest 1.8.0 stable, unpack, run (so no NewGRFs no nothing), and followed both steps-to-reproduce. Both cases hidden state is recovered after loading the game.

**Comment by PeterN** [comment]
Working fine for me in master with or without NewGRFs as well. Closing for now as no feedback from OP.
