### ISSUE TITLE
config.lib doesn't detect native Apple clang

### ISSUE THREAD

**Issue by michicc** [OpenTTD/OpenTTD#6773]
The compiler detection in `config.lib` doesn't recognize a native Apple clang compiler as the version output differs.

Output is: https://gist.github.com/michicc/f26844cd9b62ccdd07ddf203520939f5

For comparison, an Apple gcc has https://gist.github.com/michicc/bdd04cd665f973e888345340ad2f6d88

**Comment by JGRennison** [comment]
In case it's useful for progressing this, I have a fix of sorts for this issue in this commit: https://github.com/JGRennison/OpenTTD-patches/commit/094e04a04d23bb3aa5634274b2727bd75b8fdebc which could be used as a start.

**Comment by andythenorth** [comment]
FWIW, trunk 2ed0e30a8fd37173ef16bf3eca2f615a56550a1e fails to compile for me on macOS with Apple LLVM version 9.0.0 (clang-900.0.39.2)  - 3 compile errors.

With JGR's patch applied, compile works.
