### ISSUE TITLE
Separate tram & bus station graphics

### ISSUE THREAD

**Issue by kevinfields777** [OpenTTD/OpenTTD#6799]
So Wallyweb and I are working on something and we discovered that while there are sprites in the OpenTTD base set which indicate there are separate tram and bus station graphics, in actuality the game only uses one set for both.  Is there a possibility of getting these separated?

**Comment by frosch123** [comment]
The sprites are there since TTDP. And also TTDP never used them.
The reason is simple: Which sprites to use for shared bus/tram stations?

**Comment by kevinfields777** [comment]
Whichever was last built? If a player doesn't like one they can overbuild with the other.

**Comment by RoqueDeicide** [comment]
How about extra sprites for the combined station?
