### ISSUE TITLE
Train Loses Orders After Clone.

### ISSUE THREAD

**Issue by PinochleLover** [OpenTTD/OpenTTD#6804]
The clone button works fine, it is just what you do afterwards.  

Situation: Engine needs replacing with Same model and the train pulls into the depot with a full load.  You want to save the load but replace the engine.  Reason for doing it as stated below.  Faster then Deleting the engine , Clicking the New button, Selecting a engine,. clicking the buy button.  The game I have going at this time has over 350 trains,  200 Boats , 150 planes and 150 trucks.   

Steps to reproduce.
1. Remove engine from train (do not delete) put it on a new line.
2. Clone Engine Only (Orders Exist)
3 Delete Old Engine (Orders Exist)  Step not needed to reproduce.
4. Put new engine in Train.  Game will not let you put it first so put it as the second car.
5. Move first car behind the engine.
The Train Orders are now gone.  It happens more often when engine is placed inside the train then when the first car is moved behind the engine.  I found both case when troubleshoot the cause. 

I know I do not have to do it as per the steps above and delete just the engine and replace it with a new engine and the orders and Group remain.  But that only seems to work when there is only one train in the depot.  When there is more then one train in the depot in different groups (I.E. You have a Grain Group and a Livestock Group and a train from each group is in the depot.) it will drop the Group the train is in but keep the orders.

**Comment by nielsmh** [comment]
I can reproduce your steps, but I believe it's not a bug. Only a front engine can have orders, meaning when you place the cloned engine as a non-front engine in step 3 it loses its orders. The original engine (if you don't sell it) keeps the orders, so the shared orders list is not affected, just the cloned engine having orders is.

The correct way to do step 3 would be to hold Ctrl and drag the first car of the train stem onto the cloned engine, this moves the entire stem at once and keeps the cloned engine as a front engine.

**Comment by PinochleLover** [comment]
Just got back on the game and tried it. It works as you stated. Thanks.
