### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [OpenTTD/OpenTTD#6806]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [ScriptConfig::Change](https://github.com/OpenTTD/OpenTTD/blob/f84ad5f7c053dc4af3c0fc12bc6584d825a5bf91/src/script/script_config.cpp#L21 "ScriptConfig::Change function")
- [ScriptInstance](https://github.com/OpenTTD/OpenTTD/blob/f84ad5f7c053dc4af3c0fc12bc6584d825a5bf91/src/script/script_instance.cpp#L134 "Destructor for ScriptInstance")

**Comment by TrueBrain** [comment]
If you like, and these things annoy you enough, please create a Pull Request to address them. I see no reason why these won't see a short review process before being accepted.

That said, currently we are not actively making these kind of code-style changes on existing code. Especially as there is no security impact (and most compilers optimize the 'if != NULL' away anyway), there is no reason to focus our attention on these minor coding inconsistencies.

For that reason, going to close this issue. Thank you!

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?
