### ISSUE TITLE
Debian Stretch - unable to install due to missing dependency

### ISSUE THREAD

**Issue by Tuharsky** [OpenTTD/OpenTTD#6830]
Hi all,
on Debian Stretch, the version of OpenTTD is 1.6.1-1 that is quite old. On OpenTTD.org site, there is only Jessie package for 1.8.0 available. I attempted to install it anyway, but there are conflicting dependencies. I'm afraid the package is not sufficient for installation anyway since I don't see openttd-data package anywhere on openttd.org for download, ant the Stretch package seems conflicting with openttd.org's package. Besides, other packages, like openttd-msx, openttd-gfx and openttd-sfx, are available only as .tgz libraries.

Don't You consider moving the distribution of new versions to the official debian-backports repository?

Here's my dependency trouble:

dpkg -i openttd-1.8.0-linux-debian-jessie-amd64.deb 
dpkg: considering removing openttd-data in favour of openttd ...
dpkg: no, cannot proceed with removal of openttd-data (--auto-deconfigure will help):
 openttd depends on openttd-data (= 1.6.1-1)
  openttd-data is to be removed.

dpkg: regarding openttd-1.8.0-linux-debian-jessie-amd64.deb containing openttd:
 openttd conflicts with openttd-data
  openttd-data (version 1.6.1-1) is present and installed.

dpkg: error processing archive openttd-1.8.0-linux-debian-jessie-amd64.deb (--install):
 conflicting packages - not installing openttd
Errors were encountered while processing:
 openttd-1.8.0-linux-debian-jessie-amd64.deb

**Comment by PeterN** [comment]
A new build farm which should solve this is in progress. For now I'd say just grab and unpack the Linux Generic Binaries tarball. This does not need to be installed, just run it where it unpacks to. No other data packages are required, OpenTTD can download them itself. The data files will be placed in ~/.local/share/openttd

**Comment by Tuharsky** [comment]
Thank You.
