### ISSUE TITLE
RetroAppX selling OpenTTD on Microsoft Store

### ISSUE THREAD

**Issue by niveuseverto** [OpenTTD/OpenTTD#6832]
Greetings

Is this normal for them to sell opensource?

**Comment by planetmaker** [comment]
Hi, thank you for the notification.

Not sure it's normal for *them* to sell open source games for money. For sure it is in no way endorsed by us nor do we see any money from that.

However if they go by the license (thus if the app store puts no further restrictions on (re-)distribution, give appropriate credits and source is available by the same means, or at least upon request), there is little leverage to stop them. Possibly we should consider to put it ourselves into the store and have its sales help finance our necessary IT infrastructure (forums, website).

**Comment by PeterN** [comment]
@planetmaker Yes, @orudge had some patches to work towards this.

**Comment by orudge** [comment]
I am still intending to look at this further; part of the problem might be if Microsoft decides that "there's already OpenTTD on the store, you can't have another one", but since we 'are' openttd.org, etc, hopefully that could be resolved.

**Comment by EgyLynx** [comment]
Whaaaaaaaaaaaaaaaaaaaat !? Are this real happen? ! :( :( .
I don´t like hear :( . OPEN SOURCE think at sell? who are allowed to this... well you know whose is crazy now...

**Comment by planetmaker** [comment]
@orudge sure, Microsoft might have that stance. Yet we're the official developers. Being Microsoft they should see the point that it should be us who get the official name in their store - and in my experience Microsoft support so far was the few times I had contact with them usually quite supportive in a very positive way.

**Comment by TrueBrain** [comment]
I appreciate the report and the feedback. Behind the scenes we are working on this, but in general not much we can do about these things. So to answer the initial question: sadly, yes, it is normal :(

**Comment by saxbophone** [comment]
On this point, this might be of interest: https://github.com/KonradJanica/RetroAppX-WebPage
