### ISSUE TITLE
Linux SDL video driver runs slightly too fast

### ISSUE THREAD

**Issue by nielsmh** [OpenTTD/OpenTTD#6857]
Using SDL video driver on Linux will (at least sometimes?) cause the game to run slightly faster than the intended 33.33 fps. In my own tests, I see a 1%-2% speedup, about 34.1 fps measured.
Is this even a problem that needs to be addressed?

![image](https://user-images.githubusercontent.com/1062071/43015828-f8b620f0-8c50-11e8-8966-325aa56f8c30.png)

**Comment by TrueBrain** [comment]
Depends on the complexity of the problem, I guess :) Would be nice if someone at least looked into it, why this is caused. We can go from there if we want it fixed :)

**Comment by nielsmh** [comment]
Should re-test this after the separation of video output/game ticks.
