### ISSUE TITLE
Baseset translations are not updated by automated translator commit.

### ISSUE THREAD

**Issue by PeterN** [OpenTTD/OpenTTD#6862]
Building the basesets has the ability to use translations from the language files. This is not currently done for translator commits which affect the used strings, so the compiled basesets are left out of date.

The translator  system should be building the basesets to update these strings to include in the commit.

**Comment by TrueBrain** [comment]
Okay, this was a bit too cryptic for me, so a retranslation:

Basesets have both a template (`media/baseset`) and a compiled version (`bin/baseset`). The latter contains translated language strings. Both are stored in git.

On `eints` commit, only `src/lang` is updated. Not the baseset files in `bin/baseset`, making them out-of-sync with `src/lang`. This of course shouldn't happen, and both should be updated at the same time.

**Comment by TrueBrain** [comment]
The OpenTTD project itself is not responsible for the `eints` commits. This is done by `eints` itself. The project around `eints` for OpenTTD is hosted on:

https://dev.openttdcoop.org/projects/openttd-eints

Please create a feature request there with this request.
