### ISSUE TITLE
Drawing vertical/horizontal lines of width>1 problem

### ISSUE THREAD

**Issue by J0anJosep** [OpenTTD/OpenTTD#6865]
Blitter doesn't draw lines of width > 1 correctly:

1. Sometimes there are some pixels moved at the beginning or end of the line.
2. The width of the line doesn't match the one passed as an argument.

`GfxDrawLine(x_zero, y_zero, x_zero, y_max, _colour_gradient[COLOUR_BLUE][1], 4);`
`GfxDrawLine(x_max, y_zero, x_max, y_max, _colour_gradient[COLOUR_BLUE][1], 5);`
See attached image:
![lines](https://user-images.githubusercontent.com/3152990/43097564-b42ba482-8ebc-11e8-874b-0842736b54fc.png)
... where the left line should have a width of 5 and the right one a width of 4 pixels (and they have a width of 4 and 3 respectively).

**Comment by nielsmh** [comment]
I can't reproduce the thickness issue.

    GfxDrawLine(x_zero +  0, y_zero, x_zero +  0, y_max, 1, 1);
    GfxDrawLine(x_zero +  5, y_zero, x_zero +  5, y_max, 1, 2);
    GfxDrawLine(x_zero + 10, y_zero, x_zero + 10, y_max, 1, 3);
    GfxDrawLine(x_zero + 15, y_zero, x_zero + 15, y_max, 1, 4);
    GfxDrawLine(x_zero + 22, y_zero, x_zero + 22, y_max, 1, 5);
    GfxDrawLine(x_zero + 30, y_zero, x_zero + 30, y_max, 1, 6);

![image](https://user-images.githubusercontent.com/1062071/47969521-199a3000-e079-11e8-8938-9a879ead8fac.png)

**Comment by andythenorth** [comment]
So do we have a repro or not? :)
