### ISSUE TITLE
[Suggestion]OpenTTD Revolution

### ISSUE THREAD

**Issue by openbu-owner** [OpenTTD/OpenTTD#6874]
## OpenTTD Revolution

Version number of this document: 18.08.01 (this document needs to be revised)

**Keywords**: streamlined, KISS (Keep It Simple, Stupid), HTML5, NodeJS, Markdown

Branch into OpenTTD server version  &  OpenTTD client version.

### 1.1. OpenTTD client needs to add features

1.1.1.CEF (Chromium Embedded Framework)

1.1.2.Electron

1.1.3 Reports are displayed with HTML5 and Markdown

- Profit chart
- Income chart
- Transport cargo chart
- Company evaluation chart
- Company market value chart
- Freight freight chart

### 1.2. Features that the OpenTTD client needs to remove.

1.2.1. Remove the stand-alone mode

1.2.2. Remove the toy landscape style

1.2.3. Remove AIs and Game Scripts

1.2.4. Remove squirrel2

1.2.5. Remove the music jukebox

1.2.6. Remove Dmusic_for_OpenTTD.zip Old DirectMusic includes.

1.2.7. Remove the town list

### 2.1. OpenTTD server side needs to add features

2.2.1. Web server

Used to process and present reports

2.2.2.JSON

- Town list
- Shipping company list

### 2.2. Features that need to be removed on the OpenTTD server side

2.2.1. Remove the stand-alone mode

2.2.2. Remove the toy landscape style

2.2.3. Remove AIs and Game Scripts

2.2.4. Remove squirrel2

2.2.5. Remove the music jukebox

2.2.6. Remove Dmusic_for_OpenTTD.zip Old DirectMusic includes.

2.2.7. Remove the town list

**Comment by TrueBrain** [comment]
Thank you for your suggestion. You clearly put thought in this and tried to understand OpenTTD before making your suggestion.

Although, "suggestion", it is more a list of actions to perform; what it fails to bring is a reason why those changes are needed/required, and why it would add value to a game like OpenTTD. This is too bad, as you most likely have thought about each and every point. But without context, it is just that, a point.

You mainly seem to want to remove stuff. Without any further context, this seems to be out of personal frustration, more than anything else. For example, removing "music jukebox". To me it seems that if you don't like the jukebox, simply don't use it. But why remove it, while others to enjoy it?

You also mention KISS. Yet the list is far from KISS. Adding a webserver to a game sounds like bloating the software for no good reason except for the fact of adding it. Of course that can be a very good reason: adding it, just for adding it, so you learn how that works, etc. But what value does it add to OpenTTD?

The best suggestion I can give you:

Find a few people that agree with your list, create a fork, and add/remove the things in there. If other people like it, your fork will become popular. It is a really good way to do these kinds of radical changes.

So thank you, but no thank you. Going to close this issue, as it is not something OpenTTD will actively work on to implement.
