### ISSUE TITLE
Compile fails on src/economy.cpp:702:20: error: expected expression

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/OpenTTD#6880]
```
[SRC] Compiling economy.cpp
src/economy.cpp:702:20: error: expected expression
                c->cur_economy = {};
```

```
$ clang --version
Apple LLVM version 9.1.0 (clang-902.0.39.2)

```

**Comment by andythenorth** [comment]
selected ./configure output (LordAro asked for just flags)

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/c++/4.2.1
using CFLAGS_BUILD...  -fno-strict-aliasing -Wall -W -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-multichar -Wno-self-assign -Wno-parentheses -Wno-sign-compare -DOSX -D_FORTIFY_SOURCE=2 -O1 
using CXXFLAGS_BUILD...  
using LDFLAGS_BUILD...  -rdynamic 
using CFLAGS...  -O2 -fomit-frame-pointer  -fno-strict-aliasing -Wall -W -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-multichar -Wno-self-assign -Wno-parentheses -Wno-sign-compare -DOSX -D_FORTIFY_SOURCE=2 -DWITH_SSE -isystem/opt/local/include -DNO_QUICKTIME -DUNIX -DWITH_COCOA -DENABLE_COCOA_QUARTZ -DWITH_ZLIB   -DWITH_LZMA -I/usr/local/Cellar/xz/5.2.4/include  -DWITH_LZO -D_SQ64 -I/Users/andy2/workspace/OpenTTD.OpenTTD/src/3rdparty/squirrel/include -DWITH_PNG -I/usr/local/Cellar/libpng/1.6.35/include/libpng16  -DWITH_FREETYPE -I/usr/local/opt/freetype/include/freetype2  -DWITH_ICONV -DENABLE_NETWORK -DWITH_PERSONAL_DIR -DPERSONAL_DIR=\"Documents/OpenTTD\" -DWITH_SHARED_DIR -DSHARED_DIR=\"/Library/Application\ Support/OpenTTD\" -DGLOBAL_DATA_DIR=\"/usr/local/share/games/openttd\" 
using CXXFLAGS...  
using LDFLAGS... -lstdc++ -lc -F/System/Library/Frameworks -framework Cocoa -framework Carbon -framework AudioUnit -framework AudioToolbox -lz  -L/usr/local/Cellar/xz/5.2.4/lib -llzma  -llzo2 -L/usr/local/Cellar/libpng/1.6.35/lib -lpng16 -lz  -L/usr/local/opt/freetype/lib -lfreetype    -rdynamic -framework Cocoa 

```

**Comment by andythenorth** [comment]
$ clang -v
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0

**Comment by andythenorth** [comment]
$ clang -v | head -n1 | sed s@[^0-9]@@g | cut -c 1-2
Apple LLVM version 9.1.0 (clang-902.0.39.2)

**Comment by andythenorth** [comment]
clang -v 2>&1 | head -n1 | sed s@[^0-9]@@g | cut -c 1-2
91

**Comment by andythenorth** [comment]
Workaround / fix, thanks to lethosor and michicc

CC=clang CXX=clang++ LDFLAGS="-liconv" ./configure

Then the build works.  My mac OS is 10.13.6.  lethosor has 10.13 also, and can build clean from OpenTTD master around 27c4f5517f1f104e36ac2ea773462f20e3ddeb59

**Comment by lethosor** [comment]
I'm building exactly 27c4f5517f1f104e36ac2ea773462f20e3ddeb59. For reference, here is [andythenorth's linker command](https://gist.githubusercontent.com/andythenorth/2bc9029cecbf952a8476c61b8b4c3429/raw/5a72cb7a6b8e1678dd9c5fa00a135f780d53eebc/gistfile1.txt) (without the LDFLAGS above) and here is [mine](https://gist.githubusercontent.com/lethosor/7e1c2c274dfed20f6462bafe56b86378/raw/06309d1042725b29ef9011e59ba95318567888c9/gistfile1.txt). The only notable difference is the -liconv near the end of mine. It's worth noting that I did not modify LDFLAGS myself at all (just ran ./configure and make), so something odd is causing -liconv not to be added properly on some machines.

**Comment by glx22** [comment]
maybe you should compare the output of your ./configure runs

**Comment by andythenorth** [comment]
New fun.

Apple upgraded clang. Apple LLVM version 10.0.0 (clang-1000.11.45.2)

This now fails again, same error as originally posted in the issue.  Also fails on LordAro's fixed branch.

nielsm suggested adding 'CXXFLAGS=-std=c++11' to configure flags, which works.

Currently I'm not sure all of the following flags are needed, but it compiles, and I need to sleep :P
CC=clang CXX=clang++ CXXFLAGS=-std=c++11 LDFLAGS="-liconv" ./configure
