### ISSUE TITLE
fatal application failure

### ISSUE THREAD

**Issue by kika160** [OpenTTD/OpenTTD#6882]
waht i need to do?

*** OpenTTD Crash Report ***

Crash at: Wed Aug 08 14:11:47 2018
In game date: 2116-05-26 (52)

Crash reason:
 Exception: C0000005
 Location:  006DCCD9
 Message:   <none>

OpenTTD version:
 Version:    1.8.0 (0)
 NewGRF ver: 18086d62
 Bits:       32
 Endian:     little
 Dedicated:  no
 Build date: Apr  1 2018 13:17:31

Registers:
 EAX: 0000FFFF EBX: 0000FFFF ECX: 25F9BE25 EDX: 00000000
 ESI: 25F8A61D EDI: 00008C02 EBP: 0019E91C ESP: 0019E860
 EIP: 006DCCD9 EFLAGS: 00010296

 Bytes at instruction pointer:
 0F B7 04 59 0F B6 D0 0F B6 C4 66 C1 E2 08 66 0B D0 0F B7 C2 89 4D D8 8D

Stack trace:
 C719D150 0019EB48 0019ED10 00000006 00EA7D50 FFFFFFFF 00000008 FFFFFFFF
 00000008 0019EC1C 00000000 FFFFFFFF FFFFFFFF 00190001 00000000 00000000
 04F944F8 47444546 03A03660 04E60E5C 00000346 04F944F8 47444546 03A03660
 04E610D8 000000CA 00000000 3F3F3F3F 00000000 25F8A334 FFFFFFFF 25F8A5D8
 25F8A334 00000048 00000964 000002E8 00008C02 25F8A886 25F8A334 25F8ABBE
 00000003 00000005 25F8A88A 0000FFFF 0019E974 006EC9DB 00000002 0019E938
 006DCF13 0019EB48 0019EAA8 00000000 0019ED10 0019ED10 0019E980 006D66E2
 0019EB48 0019EAA8 00000000 0019ED10 C719D1CC 25F85E82 0019ED10 00000006
 04F944F8 47535542 0019E9AC 25F8A332 00002EBE 0019E9D4 006EC4F8 00000005
 0019E9E0 006DBD42 0019E9AC 00000006 0019EAA8 00000000 0019ED10 C719D1AC
 0019EB48 0019ED10 00000007 04F944F8 47535542 0019E9C0 25F8A332 00002EBE
 04F944F8 47535542 0019EB84 25F84E18 000083D8 0019EA20 006EC870 00000001
 0019EA2C 006D671D 0019EB48 1A550000 0019EAA8 00000000 0019ED10 C719D260
 0019EB00 0000000F 0019EAA8 04F944F8 47535542 0019EA58 25F85E82 0000736E
 0019EA74 006EC4F8 00000006 0019EA80 006D6896 0019EA58 00000007 0019EAA8
 00000000 0019ED10 C719D2CC 0019ED10 0019EB48 80000000 04F944F8 47535542
 0019EB00 25F85E82 0000736E 00000007 0019EB48 0019EB14 006EC528 00000000
 0019EB20 006D69F4 00000018 00000003 00000000 0019ED10 C719D36C 0019ED10
 0019ED10 03A0364C 00EA7D50 FFFFFFFF 00000003 FFFFFFFF 00000008 0019EC1C
 00000000 FFFFFFFF FFFFFFFF 00000001 80000000 00000000 04F944F8 47444546
 03A03660 04E60E5C 00000346 04F944F8 47444546 03A03660 04E610D8 000000CA
 04F944F8 47535542 0019EB4C 25F85DD4 0000741C 0019EB9C 006EC560 00000001
 0019EBA8 006D3097 00000008 00000000 00000001 03A03660 00000000 0000000F
 C719D3E4 03A03620 00EA52D0 04F944F8 47535542 03A0364C 25F85724 00007ACC

Operating system:
 Name:     Windows
 Release:  6.2.9200 ()
 Compiler: MSVC 1600

Configuration:
 Blitter:      32bpp-anim
 Graphics set: OpenGFX (5580)
 Language:     C:\Program Files (x86)\OpenTTD\lang\hebrew.lng
 Music driver: dmusic
 Music set:    OpenMSX (96)
 Network:      no
 Sound driver: win32
 Sound set:    NoSound (2)
 Video driver: win32

Fonts:
 Small:  Arial
 Medium: Arial
 Large:  Arial
 Mono:   sprite

AI Configuration (local: 0):
  0: Human

Libraries:
 FreeType:   2.4.11
 ICU i18n:   51.2
 ICU lx:     51.2
 LZMA:       5.0.4
 LZO:        2.06
 PNG:        1.5.14
 Zlib:       1.2.7

Module information:
 C:\Program Files (x86)\OpenTTD\openttd.exe handle: 00400000 size: 11955712 crc: 1710B4CD date: 2018-04-01 13:21:36
 C:\WINDOWS\SYSTEM32\ntdll.dll handle: 77540000 size: 1620872 crc: E633E528 date: 2018-07-06 07:13:57
 C:\WINDOWS\System32\KERNEL32.DLL handle: 76D80000 size: 607840 crc: 925D9B04 date: 2018-04-11 23:35:01
 C:\WINDOWS\System32\KERNELBASE.dll handle: 73FA0000 size: 1981896 crc: 27439988 date: 2018-07-06 07:14:28
 C:\WINDOWS\System32\WS2_32.dll handle: 754C0000 size: 412792 crc: D65A595A date: 2018-04-11 23:35:02
 C:\WINDOWS\System32\RPCRT4.dll handle: 74C10000 size: 786176 crc: 05EED7D3 date: 2018-06-30 13:55:59
 C:\WINDOWS\System32\SspiCli.dll handle: 73E00000 size: 123520 crc: F6A5A838 date: 2018-04-11 23:35:01
 C:\WINDOWS\System32\CRYPTBASE.dll handle: 73DF0000 size: 31592 crc: 23CC4CE4 date: 2018-04-11 23:35:01
 C:\WINDOWS\System32\bcryptPrimitives.dll handle: 77340000 size: 356960 crc: 4C78C7CD date: 2018-06-15 05:03:39
 C:\WINDOWS\System32\sechost.dll handle: 74CD0000 size: 269200 crc: F63FB8BB date: 2018-04-11 23:35:02
 C:\WINDOWS\System32\IMM32.dll handle: 755D0000 size: 147288 crc: E7BD90AE date: 2018-04-11 23:34:50
 C:\WINDOWS\SYSTEM32\WINMM.dll handle: 6B4D0000 size: 134920 crc: 9CC40B44 date: 2018-04-11 23:34:45
 C:\WINDOWS\System32\USER32.dll handle: 75070000 size: 1626536 crc: 0F0BDF19 date: 2018-04-11 23:34:48
 C:\WINDOWS\System32\msvcrt.dll handle: 76FB0000 size: 774288 crc: 5D313FA1 date: 2018-04-11 23:35:01
 C:\WINDOWS\System32\win32u.dll handle: 773A0000 size: 86840 crc: 78157AC3 date: 2018-04-11 23:34:48
 C:\WINDOWS\System32\GDI32.dll handle: 77110000 size: 134856 crc: BCA9C868 date: 2018-04-11 23:34:46
 C:\WINDOWS\System32\gdi32full.dll handle: 73E30000 size: 1454024 crc: F4025B2E date: 2018-06-30 13:55:59
 C:\WINDOWS\System32\msvcp_win.dll handle: 75320000 size: 504168 crc: 32672ADB date: 2018-04-11 23:34:51
 C:\WINDOWS\System32\ucrtbase.dll handle: 753A0000 size: 1175568 crc: D3FA1040 date: 2018-07-06 07:14:09
 C:\WINDOWS\System32\ADVAPI32.dll handle: 75200000 size: 481976 crc: E19EBFD9 date: 2018-04-11 23:35:01
 C:\WINDOWS\SYSTEM32\WINMMBASE.dll handle: 70A20000 size: 131776 crc: BD097D44 date: 2018-04-11 23:34:45
 C:\WINDOWS\System32\SHELL32.dll handle: 75600000 size: 20383720 crc: 725EFAA8 date: 2018-06-15 15:25:32
 C:\WINDOWS\System32\cfgmgr32.dll handle: 75280000 size: 228864 crc: 87E76360 date: 2018-04-11 23:34:51
 C:\WINDOWS\System32\shcore.dll handle: 773C0000 size: 553248 crc: 4ECF2EE5 date: 2018-06-30 13:55:39
 C:\WINDOWS\System32\combase.dll handle: 74190000 size: 2479272 crc: 6BB194BC date: 2018-06-30 13:55:39
 C:\WINDOWS\System32\windows.storage.dll handle: 745E0000 size: 6043600 crc: AFCA7DC2 date: 2018-06-15 05:03:48
 C:\WINDOWS\System32\shlwapi.dll handle: 77140000 size: 278960 crc: FD5C05E3 date: 2018-04-11 23:34:59
 C:\WINDOWS\System32\kernel.appcore.dll handle: 74BA0000 size: 50208 crc: B2B13399 date: 2018-06-30 13:55:54
 C:\WINDOWS\System32\profapi.dll handle: 77320000 size: 89440 crc: 552BEB89 date: 2018-04-11 23:35:03
 C:\WINDOWS\System32\powrprof.dll handle: 74E20000 size: 274352 crc: 0238FF3F date: 2018-04-11 23:34:50
 C:\WINDOWS\System32\FLTLIB.DLL handle: 74C00000 size: 27936 crc: F67D7293 date: 2018-04-11 23:34:51
 C:\WINDOWS\system32\uxtheme.dll handle: 72CD0000 size: 485888 crc: 7F418F65 date: 2018-04-11 23:35:00
 C:\WINDOWS\System32\MSCTF.dll handle: 76E60000 size: 1326400 crc: C7B9322C date: 2018-04-11 23:34:50
 C:\WINDOWS\System32\OLEAUT32.dll handle: 77070000 size: 606448 crc: CFC02B48 date: 2018-06-30 13:55:39
 C:\WINDOWS\system32\dwmapi.dll handle: 72CA0000 size: 124824 crc: 41EAA3AB date: 2018-04-11 23:34:51
 C:\WINDOWS\SYSTEM32\TextInputFramework.dll handle: 72C20000 size: 509328 crc: E13C8724 date: 2018-04-11 23:34:46
 C:\WINDOWS\SYSTEM32\CoreMessaging.dll handle: 6A1E0000 size: 567144 crc: 771BB91D date: 2018-07-06 07:16:47
 C:\WINDOWS\SYSTEM32\CoreUIComponents.dll handle: 640C0000 size: 2486992 crc: 52A39B22 date: 2018-06-30 13:55:54
 C:\WINDOWS\SYSTEM32\wintypes.dll handle: 6B030000 size: 880152 crc: 8E4ADE24 date: 2018-06-30 13:55:39
 C:\WINDOWS\SYSTEM32\ntmarta.dll handle: 715F0000 size: 154016 crc: 0B67B6A0 date: 2018-04-11 23:34:50
 C:\WINDOWS\system32\mswsock.dll handle: 71BC0000 size: 341920 crc: 2544915A date: 2018-04-11 23:34:51
 C:\WINDOWS\SYSTEM32\MMDevAPI.DLL handle: 709B0000 size: 360104 crc: A98F638F date: 2018-04-11 23:34:45
 C:\WINDOWS\SYSTEM32\DEVOBJ.dll handle: 72A00000 size: 133824 crc: BEC65282 date: 2018-04-11 23:34:51
 C:\WINDOWS\SYSTEM32\PROPSYS.dll handle: 717E0000 size: 1584128 crc: 57C5E14A date: 2018-06-30 13:55:54
 C:\WINDOWS\SYSTEM32\wdmaud.drv handle: 619D0000 size: 219648 crc: 95EE3927 date: 2018-04-11 23:34:45
 C:\WINDOWS\SYSTEM32\ksuser.dll handle: 73AC0000 size: 20728 crc: 62A28D70 date: 2018-04-11 23:34:45
 C:\WINDOWS\SYSTEM32\AVRT.dll handle: 709A0000 size: 27416 crc: F3D6798B date: 2018-04-11 23:34:45
 C:\WINDOWS\SYSTEM32\AUDIOSES.DLL handle: 6B110000 size: 1011968 crc: 34E9B2CB date: 2018-06-15 05:03:47
 C:\WINDOWS\SYSTEM32\msacm32.drv handle: 72C10000 size: 24576 crc: B858B404 date: 2018-04-11 23:34:45
 C:\WINDOWS\SYSTEM32\MSACM32.dll handle: 6AE00000 size: 94080 crc: 8FE45C38 date: 2018-04-11 23:34:45
 C:\WINDOWS\SYSTEM32\midimap.dll handle: 714E0000 size: 18944 crc: A7771BB1 date: 2018-04-11 23:34:45
 C:\WINDOWS\System32\clbcatq.dll handle: 75540000 size: 526848 crc: CEC4CD73 date: 2018-04-11 23:34:50
 C:\WINDOWS\System32\ole32.dll handle: 74D20000 size: 1026896 crc: 9EF898F8 date: 2018-06-15 15:22:54
 C:\WINDOWS\System32\dmime.dll handle: 61990000 size: 204800 crc: 98383825 date: 2018-04-11 23:34:50
 C:\WINDOWS\System32\DSOUND.dll handle: 60640000 size: 502272 crc: 29E2B7DC date: 2018-04-11 23:34:45
 C:\WINDOWS\System32\dmusic.dll handle: 61960000 size: 113152 crc: 102CD654 date: 2018-04-11 23:34:50
 C:\WINDOWS\System32\dmsynth.dll handle: 60610000 size: 113152 crc: 9AA4C000 date: 2018-04-11 23:34:50
 C:\Windows\System32\Windows.UI.dll handle: 5F710000 size: 886400 crc: 32D3C35E date: 2018-04-11 23:34:55
 C:\Windows\System32\InputHost.dll handle: 5F6B0000 size: 364200 crc: A98D6F6A date: 2018-04-11 23:34:47
 C:\WINDOWS\System32\dmloader.dll handle: 70BA0000 size: 42496 crc: FF29F4D5 date: 2018-04-11 23:34:50
 C:\WINDOWS\System32\psapi.dll handle: 75530000 size: 17104 crc: 7D2EF3AC date: 2018-04-11 23:34:50

---- gamelog start ----
Tick 11496: game loaded
Revision text changed to 1.3.0, savegame version 180, not modified, _openttd_newgrf_version = 0x130061eb
New game mode: 1 landscape: 0
Tick 11496: game loaded
Revision text changed to 1.8.0, savegame version 197, not modified, _openttd_newgrf_version = 0x18086d62
New game mode: 0 landscape: 0
---- gamelog end ----

*** End of OpenTTD Crash Report ***

Decoded stack trace:
[00] openttd              0x006DCCD9
[01] openttd              0x006DCF13
[02] openttd              0x006D66E2
[03] openttd              0x006DBD42
[04] openttd              0x006D671D
[05] openttd              0x006D6896
[06] openttd              0x006D69F4
[07] openttd              0x006D3097
[08] openttd              0x006D3E61
[09] openttd              0x006D39C8
[10] openttd              0x006D02C6
[11] openttd              0x006AA32C
[12] openttd              0x0042417A
[13] openttd              0x00424AA3
[14] openttd              0x004211A8
[15] openttd              0x00421210
[16] openttd              0x00465073
[17] openttd              0x00462F2B
[18] openttd              0x004632A1
[19] openttd              0x00463C6A
[20] openttd              0x004632A1
[21] openttd              0x00467BBF
[22] openttd              0x0046A3FB
[23] openttd              0x00421860
[24] openttd              0x00452C6A

*** End of additional info ***

**Comment by glx22** [comment]
crash.dmp could help, but a quick look at the crash log I can guess it's related to ICU

**Comment by kika160** [comment]
how can i fix this?

**Comment by glx22** [comment]
would be nice if you could provide crash.dmp, so we could see exactly where the crash is. Anyway if it's ICU related you can't do anything on your side to fix it but the ICU issue is solved in current master (we replaced it on windows)

**Comment by nielsmh** [comment]
Try playing the game with English language. If it works there, it's definitely the ICU text rendering bug, where right-to-left languages (Hebrew and the Arabic language family) simply cause crashes. The only workaround is to not use those translations.

**Comment by andythenorth** [comment]
Thanks. ICU has known issues, and there is a project underway to replace it. We're not keeping the reports relating to it open, but they can still be found here as and when they are needed. Thanks for the report and diagnosis efforts.
