### ISSUE TITLE
Installer reports success even if not all files were copied

### ISSUE THREAD

**Issue by nielsmh** [OpenTTD/OpenTTD#6884]
Per this forum topic: https://www.tt-forums.net/viewtopic.php?f=31&t=83038

The Windows installation program will pretend to complete installation, and report success, even if some core files are locked and cannot be overwritten. For example, if the game is running while attempting to install a newer version over it, parts of the running game will be overwritten, but not the main EXE file.

If writing any file during installation fails, the installer should probably stop and request that the user attempts to remedy the locked file/out of disk space/whatever situation. Ideally, before starting installation it should try to open any existing OpenTTD.exe file for writing in the destination, and if it fails, warn the user beforehand to exit the game.

**Comment by TrueBrain** [comment]
Clearly the NSIS is misconfigured :D This will be fixed with #7270. I suggest we do not spend any additional time on it, till that lands :D
