### ISSUE TITLE
Add layer showing boundaries for local authorities

### ISSUE THREAD

**Issue by YodasWs** [OpenTTD/OpenTTD#6887]
I'd like to request adding a map layer showing the boundaries of the local authorities.

Ideally use four colors to cover the whole map, but I suppose you could just use red boundary lines.

I want to help a town expand, but don't want to (or just can't) place a station in a different town's authority, so I need a better, easier way to see where the line is between the two besides querying every square in the area of interest.

Also would like to see how far out into the more rural/unclaimed areas a town's authority stretches.

**Comment by vbornand** [comment]
Note that some cells in rural zone isn't owned by any municipalities.

**Comment by YodasWs** [comment]
Yes, I noticed. Still would be nice to see the extent of the local authorities' jurisdiction without having to tap every square&hellip;

**Comment by GabdaZM** [comment]
I am thinking about ways to do this. I think it is enough to show the boundaries of one town at a time.
Ideas about turning on boundary showing:
1, Click anywhere within the town boundary with the "Land area information" tool.
2, Add a button in the town window (next to Location, Local authority, Rename, making it a 2x2 button grid)
Ideas to show boundaries:
1, Adding blue (or other color) selection tile sprites to every tile within the boundary (pic. attached).
2, Draw a fence like border at the boundary (I think it is further from the TTD style).
Any idea about the 2 questions which direction should I go in?
![authority](https://user-images.githubusercontent.com/25156653/50705467-3a700900-105b-11e9-9655-00e18d0df38b.png)

**Comment by LordAro** [comment]
Personally I'd say idea 2 and idea 1, respectively

**Comment by andythenorth** [comment]
JGR Patch Pack has already implemented this via 'zoning'.  I found it quite un-intuitive to use, but eh :)

**Comment by GabdaZM** [comment]
What happens in this case? Is this issue counts an open one, or will be closed/abandoned?

**Comment by andythenorth** [comment]
Issue stays open.  Anyone who wants to patch for this is wise to look at the implementation in JGRPP, to see what's nice and not nice about it ;)
