### ISSUE TITLE
Add layer(s) showing station coverage

### ISSUE THREAD

**Issue by YodasWs** [OpenTTD/OpenTTD#6888]
I'd like to request adding a map layer showing the coverage areas of the stations.

When placing a new station, I would like to place my stations in a consistent pattern but without (or with as little as possible) overlap in station coverage. I envision simply using the company owner's primary and/or secondary color.

Additionally, maybe add an option to each station's info box to show just this station's coverage area while the box is open. This can help me see where the cargo and/or passengers are coming from and help me determine how and where to expand the station (since I can connect disjoint stations together).

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.
