### ISSUE TITLE
Crash: disconnecting road vehicle

### ISSUE THREAD

**Issue by RailwAI** [OpenTTD/OpenTTD#6890]
I was testing my AI, when suddenly the game crashed with a message "Disconnecting road vehicle". To reproduce the crash: the savegame (and the crash dump file) can be download from [this forumpage](https://www.tt-forums.net/viewtopic.php?f=31&t=83778). The AI, RailwAI version 7, is available via the in-game content downloader (BaNaNaS). Crash occurred on the in-game date 2000, August 7th (1½ in-game years after the savegame start).

The crash log file: [crash.txt](https://github.com/OpenTTD/OpenTTD/files/2349668/crash.txt)

**Comment by nielsmh** [comment]
Sorry, I can't reproduce the error. I tried using 1.8.0, downloading missing NewGRFs from BaNaNaS, as well as RailwAI from BaNaNaS too, and let the savegame run until 2000-08-07 (looking around the map and at the AI debug window, but not building/changing anything) and nothing happened on the date.

**Comment by RailwAI** [comment]
Weird bug indeed. Yesterday, I was able to reproduce the crash by running the savegame again. Now, I'm not able to reproduce the crash either. I see in the AI debug that multiple AI instances are busy with building and removing roads. Also, a few AI are telling some road vehicles to skip a few orders in the order list. I don't know what could cause the message "disconnecting road vehicle".

**Comment by nielsmh** [comment]
There's only one place in the code that can produce the message, and it's when the `FollowPreviousRoadVehicle` function fails for a road vehicle trailer.

I think one possible case is if a bridge, tunnel, or depot is deleted the tick after a road vehicle has left it. Possibly also if the road is changed on a tile after the truck has left that tile but the trailer hasn't yet.

**Comment by andythenorth** [comment]
Thanks for this.  At the time of writing this appears to be an isolated bug, and hard to reproduce.  We do try to address bugs where they occur frequently and/or are easy to reproduce, but this one doesn't look like we can any go further, so I'm closing it.  Thanks for contributing!
