### ISSUE TITLE
Question Building the project on Windows

### ISSUE THREAD

**Issue by bou6** [OpenTTD/OpenTTD#6891]
I want to build the project on Windows, what is the project file to open ?

I cannot understand this sentence in the documentation: "need Microsoft Visual Studio .NET. Open the project file and it should build automatically"

**Comment by glx22** [comment]
It depends on your version of Visual Studio. You just need to open the corresponding solution file (.sln), for example vs140 is for Visual Studio 2015.

**Comment by nielsmh** [comment]
Only Visual Studio 2015 and Visual Studio 2017 work with the current codebase. The free Community edition of either works perfectly. For VS 2015, use `openttd_vs140.sln` as the Solution file to open, for VS 2017 use `openttd_vs141.sln`.

The ".NET" part in Visual Studio is not really present any longer, I think it was only the 2002, 2003, and 2005 versions that used that, it's just the documentation here that hasn't been updated.

Maybe the project files for the no-longer-supported Visual Studio versions should be removed?

**Comment by glx22** [comment]
I think removing outdated versions should be ok.

**Comment by bou6** [comment]
Ok, Thank you for the feedback

**Comment by bou6** [comment]
Using VS 2017 and openttd_vs141.sln, I am getting compilation error table/strings.h no such file or directory, am I missing something ?

**Comment by glx22** [comment]
This file should be generated when language files are compiled. Are you building the full solution or just the project ?
