### ISSUE TITLE
destroy but keep land

### ISSUE THREAD

**Issue by ghost** [OpenTTD/OpenTTD#6894]
On using the destroy button, one sells automatically its land. I'd like to have a second option (e.g. as a config option) that allows me not to sell the land on destroying sth.. This way, I could even buy many land by click'n'drag.

A pity there is no "sell land" tool, it's the destroy button...

**Comment by EgyLynx** [comment]
Well... I not same think... but ...

**Comment by LordAro** [comment]
It's not entirely clear what you're asking for - is it for a "sell land" option? Technically, there already is one - the destroy button. What the land was before it was bought is already lost, and you do gain money from "selling" the land.

If you want to avoid that, you should only buy land that you're going to use - there's a reason the buy land button is kept as a one tile at a time button (it's also far too easy to abuse in multiplayer)

**Comment by andythenorth** [comment]
Thanks for taking time to add this jottyfan :)

To explain why this got closed - it doesn't meet all the guidelines for a good feature request, in "Feature Requests" here: https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md

It's unclear whether you want to change the destroy land tool, or buy land with click'n'drag or both :)

Thanks, 

Andy

**Comment by ghost** [comment]
Thanks for the explanation why the issue has been closed. In the end, I'd like to have any tool that allows me to destroy airports without loosing the land, mostly to replace the old airport by a new one (a bigger one). In single player, I can pause the game, but in multiplayer, I do not have this option. Therefore, I thought it could be a good solution to allow the player to set a flag in the configuration (ingame changable) wether to sell the land on destroying sth. or not (or in other words: destroy and buy in one operation).

I can understand why you reject this feature; I'm not disappointed. Just an idea.

**Comment by andythenorth** [comment]
I wonder if we could allow over-building closed airports?  So no need to destroy.  I don't know if that's possible though.

**Comment by LordAro** [comment]
There's a very old cirdan patch for this, but I think it got rejected on gameplay reasons...
