### ISSUE TITLE
Wrong release version?

### ISSUE THREAD

**Issue by szymex73** [OpenTTD/OpenTTD#6895]
I wanted to compile OpenTTD on my linux machine so I pulled the code from github, changed the branch to 'origin/release/1.8' and compiled everything without a problem.
The thing is that I want to play online but the version of the compiled one is 1.8.0~1 instead of 1.8.0

**Comment by LordAro** [comment]
Assuming the version code hasn't been broken (there's not been a release since the move to got), you'll want to check out the 1.8.0 tag, rather than the branch
The branch also contains future changes (that will go into a 1.8.1 release, should it happen)
