### ISSUE TITLE
Seeds above 32bit max int.

### ISSUE THREAD

**Issue by Blauw67** [OpenTTD/OpenTTD#6898]
When trying to create a new game with the same seed as an older game (even when it's from the same version), and the seed created with the older game is higher than the 32-bit integer, the one that will be created, will use the 32-bit (2^31 -1) as the seed. 

![image](https://user-images.githubusercontent.com/43176136/45365640-3e27dd80-b5dd-11e8-8e0d-8e66c828afce.png)

(For example "C:\Program Files\OpenTTD\openttd.exe" -g -G 3584050622 will result in a game with seed 2147483647)

![image](https://user-images.githubusercontent.com/43176136/45365806-a4acfb80-b5dd-11e8-8962-1918dfb6617a.png)

**Comment by LordAro** [comment]
Found the issue: https://github.com/OpenTTD/OpenTTD/blob/94961732a3667f9b2f38da4be5209b1259db6733/src/openttd.cpp#L669

Specifically, `generation_seed` is a uint (32 bits), `atoi` is an int (32 bits).

Apparently it's undefined behaviour when `atoi`  is given a number outside int bounds. Should probably be a `strtoul` or similar function
