### ISSUE TITLE
Not clear when an opponent has exclusive transport rights

### ISSUE THREAD

**Issue by MrOriKlein** [OpenTTD/OpenTTD#6899]
I had trains shifting coal from a mine to a nuclear power plant. All nice and dandy.
After several years of activity when I open the industry index I see the mine has jumped up to around 1.7 million in production and it signifies that 0% is being transported (IIRC it was around 300-400k prior with 80% transported).
So I go over to the location and all my trains are sitting in the station waiting to load up. One was at 72% when it stopped loading (I guess whenever the industry has bugged out) and the other two at 0%.
I released the train to unload and cash out, then sent it and the other two into the hangar waited a bit then sent them out. But still nothing happens. No production.
![openttd_buggedmine](https://user-images.githubusercontent.com/24391224/45367334-ab417000-b5e9-11e8-8b1c-171eec486664.png)

**Comment by MrOriKlein** [comment]
Tried sending the trains to the other terminal's hangars, destroyed the station and gave it some time lapse until the name disappeared and then rebuilt the station and reset the goto orders on each train, the coal meanwhile dropped to 1.5 mil production, but still nothing happens. As can be seen it clearly indicates to supply coal to the station's location.
![openttd_buggedmine2](https://user-images.githubusercontent.com/24391224/45368071-5bfc3f00-b5eb-11e8-9d1a-6738c0b7899f.png)

**Comment by planetmaker** [comment]
Are you sure that the trains have wagons capable of carrying and actually refitted to carry coal?
If the answer is yes: can you provide a savegame?

**Comment by MrOriKlein** [comment]
Absolutely positive. As said, the coal industry was there before with a "normal" high value of production and the trains were making very good profit. I actually started with one train/terminal and added the other two because the production increased. But this over a million jump is something I've never seen before (I only started playing openTTD a few days ago; I used to play TTD years ago for many years and it never done anything like that) and since it happened the industry acts as if it is ex-communicated.
This happened sometime in the middle of the current year.
![openttd_buggedmine3](https://user-images.githubusercontent.com/24391224/45368405-2efc5c00-b5ec-11e8-9bda-acd3893e73b8.png)

**Comment by MrOriKlein** [comment]
Apparently it had already surpassed 1 million production several years prior (I had no idea), but it didn't bug out until just this current year.
![openttd_buggedmine4](https://user-images.githubusercontent.com/24391224/45368574-96b2a700-b5ec-11e8-95aa-2e6399dff6d1.png)

**Comment by planetmaker** [comment]
We will need a savegame to investigate

**Comment by planetmaker** [comment]
https://github.com/OpenTTD/OpenTTD/issues/6647 was suggested to be of the same kind. Do you play with Cargodist enabled? Do your trains have (new) implicit orders and were recently renewed?

**Comment by MrOriKlein** [comment]
Of course.
It is 30MB so I had to upload externally.
http://www.fast-files.com/getfile.aspx?file=171280

No idea what Cargodist is, but I did enable in advanced settings for vehicles to be auto-renewed...did nothing to stop the pesky "X is getting very old and needs replacing", sigh.
No idea what implicit orders is, either. As far as I could tell the trains still had the same "go mines, full any cargo, goto power plant, unload and take" I set them to initially.

**Comment by EgyLynx** [comment]
Over million coals production? Are it changed something else?

**Comment by LordAro** [comment]
The level of production isn't actually related here (it's actually only 1000, just with some fancy units)

What's actually happened is that an AI has bought exclusive transport rights in Slindhattan, so your station isn't getting any cargo delivered to it

I'd probably say that this could be made a lot clearer, perhaps with a message in the station window. I'll adjust the issue accordingly

**Comment by LordAro** [comment]
Ah, actually there already is a message - it's just a bit hidden under the "Ratings" tab of the station window

Incidentally, fast-files.com is terrifying as a file host - chrome won't let me download from it at all...

I'll go ahead and close this issue now

**Comment by MrOriKlein** [comment]
Ah, I see. Didn't even occur to me to check. Thank you very much! I'll go settle the issue now. >D
And thanks for the tip about the file host. I just googled free upload and used the first thing that came.
