### ISSUE TITLE
Cargo capacity should be recalculated on TRIGGER_VEHICLE_NEW_LOAD

### ISSUE THREAD

**Issue by George-VB** [OpenTTD/OpenTTD#6907]
Tested on 1.8.0 stable

I've got serious problem with varying capacity wagons (container platform). 
A platform can carry one or two containers, which is defined with TRIGGER_VEHICLE_NEW_LOAD.
The loading speed CB, the capacity CB, graphics are different depending on random_bits.
Loading speed CB and graphics work well, but capacity CB works only once. After the first change it stays unchanged, providing capacity, that is incorrect for the current graphics.
Please force the recalculating of capacity CB after TRIGGER_VEHICLE_NEW_LOAD.

You can test the issue with 11-H004 flatbed http://bundles.openttdcoop.org/xussrset/push/LATEST/
 
![image](https://user-images.githubusercontent.com/43310520/45593891-ec92a080-b998-11e8-8737-714921639555.png)

**Comment by George-VB** [comment]
A workaround for the correct values. Force the train to refit to some other cargo, that is not available on both stations, and back to the required cargo on loading. You will get capacity to be recalculated on refit and always get the right values and graphics.

**Comment by George-VB** [comment]
Capacity CB code
https://dev.openttdcoop.org/projects/xussrset/repository/entry/src/freight/cargoes-capacity-refit.pnml
Loading speed CB code
https://dev.openttdcoop.org/projects/xussrset/repository/entry/src/freight/cargoes-loadspeed.pnml
Graphics code
https://dev.openttdcoop.org/projects/xussrset/repository/entry/src/freight/cargoes8/container/containers.pnml

Typical code to choose - (random_bits >> 1) & 0x01

switch (FEAT_TRAINS, SELF, cargo8_container_2_20or40_sprites, (random_bits >> 1) & 0x01)
{
0: cargo8_container_40_sprites;
cargo8_container_2_20_sprites;
}

**Comment by George-VB** [comment]
A workaround does not work for long train. last wagons of 9 square train become damaged the same way - capacity does not fit the random bits

**Comment by George-VB** [comment]
To prevent error I've commented the difference in capacity CB.
If you would like to test you have to uncomment these strings:
switch (FEAT_TRAINS, SELF, container_20and40_cargo_capacity, 
[  STORE_TEMP(2, 7),
   ((random_bits >> 1) & 0x01) ] )
{
//  0: container_2040_cargo_capacity;
  container_2_20_cargo_capacity;
}

switch (FEAT_TRAINS, SELF, container_2_20or40_cargo_capacity, 
[  STORE_TEMP(2, 7),
   ((random_bits >> 1) & 0x01) ] )
{
//  1: container_2_20_cargo_capacity;
  container_40_cargo_capacity;
}

**Comment by TheGwyd** [comment]
I think the problem here is that the game doesn't like to change the cargo capacity of vehicles when they are not in the depot. This is because is can cause desyncs and is unreliable in certain situations (giving the vehicle more cargo that it can actually take). This is seen if a NewGRF which has been adjusted to give a vehicle in the game a different capacity. This gives an error saying "vehicle xx has had capacity changed. This can harm the game state" or something along those lines. 
I would not consider this a bug, rather the approach of your NewGRF may need a different approach to the issue.

**Comment by George-VB** [comment]
The game already allows changing capacity at station with autorefit (outside depot!). 
The problem is that it does not force recalculating capacity before loading (after autorefit and new cargo trigger) .

**Comment by George-VB** [comment]
The problem is not fixed in master 27012019

**Comment by PeterN** [comment]
Hmm, the trigger is called after the cargo quantity is reserved, as well.

**Comment by andythenorth** [comment]
I might be 100% wrong, but this issue reminds me of autorefit bugs I saw when testing cdist stuff for fonsinchen, which resulted in this fix https://github.com/OpenTTD/OpenTTD/commit/f790d70cd62b2a9e4ddf87c20f6a22755bc24881#diff-ebbc445f07842947d83d0f98b7fa5140L1568

The comment is interesting, curious if cargo loading reservation causes the autorefit to not happen.

**Comment by George-VB** [comment]
https://yadi.sk/d/NdfWgDWMlMD2BA
https://yadi.sk/d/3uZONAAy_1RSvg
