### ISSUE TITLE
Your script made an error: the index '6658' does not exist

### ISSUE THREAD

**Issue by cpthooker** [OpenTTD/OpenTTD#6914]
I was playing the game as normal and this error appeared
![openttd](https://user-images.githubusercontent.com/8558503/45925118-7dbcc680-bf07-11e8-8061-90b2eb4f7479.jpg)
Cannot seem to find a crash log, but as you can see I took a screenshot.

**Comment by nielsmh** [comment]
This is the AdmiralAI computer opponent failing to do something, not an error in the game itself. You should send this to the author of that AI script instead.

**Comment by cpthooker** [comment]
ok thanks
