### ISSUE TITLE
Re-implement building binaries via compile farm

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/OpenTTD#6916]
*Current* 

Alongside the move to GitHub, the compile farm for building binaries (nightly, stable etc) is being re-implemented.  At time of writing (September 2018) the old compile farm infrastructure is not being used, and the new infrastructure is not implemented yet.

TrueBrain made a Trello list of what needs to be done for new infra.  https://trello.com/b/6j90aRB1/openttd

*Desired*

New infra is implemented and in production.

**Comment by TrueBrain** [comment]
A lot of work is done, and can been seen here:

https://github.com/OpenTTD/OpenTTD-CF

**Comment by TrueBrain** [comment]
Reminder: we decided to only produce 64bit OSX binaries. See #6978 for more detail.

**Comment by TrueBrain** [comment]
Currently in testing:
https://www.staging.openttd.org/

If all checks are completed, it will be moved to production (read: https://www.openttd.org)

**Comment by andythenorth** [comment]
@TrueBrain want the glory of closing this one? :)
