### ISSUE TITLE
Tractive Effort displayed incorrectly in purchase menu

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/OpenTTD#6920]
Actual TE used by vehicle was fixed in  https://github.com/OpenTTD/OpenTTD/commit/cad47bbefe5007a4d6c4e02b2cbc6f69484475f7 

TE displayed in purchase menu shows a different value (the old, slightly incorrect calculation).

**Comment by Eddi-z** [comment]
try something like this:
https://paste.openttdcoop.org/pzhptiu3b
