### ISSUE TITLE
Unable to delete a level crossing whose rail is yours but whose road is owned by another company

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#6934]
Using OpenTTD 1.8.0 on Win 7 Ultimate
I notice that whenever I try to delete a level crossing whose rail is yours but whose road is owned by another company, the entire action fails, even though only the rail should have been destroyed.

To Reproduce this bug:
1. Play as Company 1.
2. Build a rail piece.
3. Switch to Company 2.
4. Build a road piece on top of Company 1's rail piece. This should work as expected.
5. Switch back to Company 1.
6. You should end up with a level crossing whose rail is yours but whose road is owned by another company.
7. Try to use the general demolish (bomb/dynamite) button to delete such a level crossing you just created. You'd expect for just the rail to be removed, leaving the road intact, but instead neither the rail nor the road get deleted, and you get an ERR_OWNED_BY_ANOTHER_COMPANY message.

This is you deleting the level crossing whose road is owned by you but whose rail is not owned by you. The road is deleted, but the rail stays.
![image](https://user-images.githubusercontent.com/37945304/46587603-7263b200-ca54-11e8-9ebe-4ade9b4755c7.png)

This is you trying to delete the level crossing whose rail is owned by you but whose road is not owned by you. No element is deleted and you get an ERR_OWNED_BY_ANOTHER_COMPANY message.
Note: "IdlePlus Transport 1" is the name of the other company.
![image](https://user-images.githubusercontent.com/37945304/46587641-d9816680-ca54-11e8-9e73-16557b14255a.png)

This is the _expected_ result you _should_ get when you delete the level crossing whose rail is owned by you but whose road is not owned by you. The rail is removed, but the road stays.
![image](https://user-images.githubusercontent.com/37945304/46587691-b6a38200-ca55-11e8-99a7-d4c45ae61fac.png)

**Comment by Eddi-z** [comment]
not quite sure what you're asking for here.

title reads like a bug report, but description reads more like a feature request

**Comment by nielsmh** [comment]
IMO the dynamite tool should destroy everything on a tile, or fail entirely if there is one or more parts that can't be destroyed.

**Comment by andythenorth** [comment]
The established behaviour is that the dynamite tool clears an entire tile.  It's not for selectively clearing.

The case can be made for selectively clearing, but it's not obviously better than the established behaviour.  It's potato/potato, and the current behaviour is what players, AIs etc expect. 

Thanks for reporting the issue, but closing this one :)
