### ISSUE TITLE
Bananas - unhandled exception when updating grf

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/OpenTTD#6940]
Bananas is throwing 'Unhandled Exception' when trying to update an existing grf.

To repro: 

* log in
* navigate to existing grf via 'Manage'
* follow 'Update' link
* exception thrown
* http status for the page is 200, so I'm assuming this is something entirely internal to bananas

Example path http://bananas.openttd.org/en/manager/update/5446

I didn't test whether this also applies to adding a grf to bananas for the first time as this will leave junk entries behind in production Bananas.

![bananas_exception](https://user-images.githubusercontent.com/1780327/47136034-55c44700-d2aa-11e8-9fe1-ea7412dbf46e.png)

**Comment by TrueBrain** [comment]
From time to time, this happens for some uploads (rarely all, often some, mostly when they did something weird (UTF-8 character, big upload, ..)). The best way to upload at the moment, and has been for a few years now, is using musa. It has far less problems, and allows much bigger files. It is also written with UTF-8 in mind.

The list of bugs for BaNaNaS is not small. There have been rumors about a BaNaNaS2. I think any effort should be towards BaNaNaS2,, and not towards fixing a 10+ year old system ;)

Assuming musa allows you to upload the update, I am going to close this ticket (as mainly this is the wrong GitHub project to add them to. If we want to track BaNaNaS bugs, we should open a new project ;)). If musa doesn't allow you, poke me on IRC, and I will investigate further. Tnx!

**Comment by andythenorth** [comment]
Fanks

Musa is here https://www.tt-forums.net/viewtopic.php?t=63119

**Comment by TrueBrain** [comment]
Finally solved.

**Comment by andythenorth** [comment]
Bananas is again showing the same behaviour as originally described in this issue.  

I have no way to confirm it's the same cause (unhandled UTF-8), but it seems a likely explanation, so I've re-opened.

**Comment by spnda** [comment]
Last 2 times it was due to a non-UTF-8 character in a GRF title ("Ö", "™️"), see #6967.
I don't see any new GRF with a non-UTF-8 character in its title or description.
Just wanted to note this.

**Comment by TrueBrain** [comment]
This is not like the other times we had. I can navigate and upload just fine. So it is not the usual issue as @spnda pointed out. That means I need more information than just this. Is this problem only happening for you? Is it still happening? On what URL exactly? If you can let me know some more details, I can look into it further! Tnx!

**Comment by andythenorth** [comment]
GRF is Iron Horse 2, path is http://bananas.openttd.org/en/manager/update/5887

Attached is a zip of the tar I'm trying to upload.  To be specific, the tar is the failing upload, but GH rules require me to zip it, so eh.

[iron-horse-2.0.0-alpha-9.tar.zip](https://github.com/OpenTTD/OpenTTD/files/3184094/iron-horse-2.0.0-alpha-9.tar.zip)

"""
Unhandled Exception

An unhandled exception was thrown by the application.
"""

Tried both Chrome and Firefox in case the browser was truncating the upload.  The tar _seems_ ok.

**Comment by TrueBrain** [comment]
So the problem happens on upload? Not like before when loading the page?

That most likely means there is something in the tar-file that the web interface doesn't like. We had that before. I can look into the details of it, but the best next step would most likely be to try it via `musa`. Can you give that a try?

**Comment by andythenorth** [comment]
Yes I'll set up a musa ini file and try it.

**Comment by andythenorth** [comment]
"metadata validated at server side
uploaded 1253695 bytes of 1253695 bytes (100%)"

But bananas does not show Iron Horse 2.0.0 Alpha 9.
[musa.ini.zip](https://github.com/OpenTTD/OpenTTD/files/3184257/musa.ini.zip)

**Comment by frosch123** [comment]
Musa rejects the upload as already present. Apparently the previous upload attempts left some incomplete stuff in the database.
Probably needs manual SQL stuff. But requires understanding the DB schema first :)

**Comment by TrueBrain** [comment]
Or just try uploading `alpha 9a` ;) :D

**Comment by andythenorth** [comment]
Upload of `alpha 9a` has worked

**Comment by TrueBrain** [comment]
\o/ So that means we can close the issue :D Like it never happened :P
