### ISSUE TITLE
Music doesn't works

### ISSUE THREAD

**Issue by JakobDev** [OpenTTD/OpenTTD#6943]
I use the Binary Version for Linux 64 Bit. I had started the Game installed Sounds and Music Packs. After that, I selected it in The Options Menu. The Sounds are played but there is no Music. I had tried a few Music Packs.

**Comment by LordAro** [comment]
Sounds like you're missing `timidity`, the external program that's currently required to play midi music under Linux, can you confirm that it's installed?

**Comment by JakobDev** [comment]
Yes
```
User@PC:~$ sudo apt install timidity
Reading package lists... Done
Building dependency tree       
Reading state information... Done
timidity is already the newest version (2.13.2-40.3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
User@PC:~$ 
```

**Comment by nielsmh** [comment]
Which version, 1.8.0, an earlier, or a current development version?

**Comment by JakobDev** [comment]
I use the newest stable Version 1.8.0

**Comment by BrunoDSL** [comment]
Can confirm this issue also happen with me on Arch Linux. Music doesn't play no matter what you set on the options or launch parameters. I tried using both fluidsynth and timidity and both work playing OpenMSX's mid files, but not with the game.

**Comment by BrunoDSL** [comment]
Music works on openSUSE Tumbleweed, btw.

**Comment by nielsmh** [comment]
We added a new music driver based on Fluidsynth recently, if you're feeling adventurous or confident in building OpenTTD from source yourself, that might make music work better.

The current extmidi driver (which generally calls Timidity) is rather difficult to debug, and personally I wouldn't mind seeing it removed entirely.

**Comment by Asdew95** [comment]
Arch Linux here. Works perfectly. Could be missing soundfonts, but it really doesn't seem like that (playing the MIDI files worked for MR4Y, but no sounds in game and I think Ubuntu installs soundfonts with timidity)

**Comment by JakobDev** [comment]
Is there any binary for me to test it?

**Comment by JakobDev** [comment]
I have build it from source and the music works now.

**Comment by terminal-root** [comment]
I'm on Fedora 37. For me, when I looked at the music player, the tracks were displaying one after another extremely quickly without actually playing.

I installed `timidity++`, and the music began working.

```bash
sudo dnf install timidity++
```
