### ISSUE TITLE
A new variable Vehicle is loading required

### ISSUE THREAD

**Issue by George-VB** [OpenTTD/OpenTTD#6947]
Currently there is a Variable without parameter "vehicle_is_unloading", but there is no variable "vehicle_is_loading". Please provide it (required during running cost factor CB)

**Comment by andythenorth** [comment]
Although this would be nice to have, it isn't something we expect to fulfill in the next year, and on that basis I'm closing it.  We do this to keep the project manageable, productive and fun. We hope you do understand. Thanks for contributing though! [Here](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) you can find more about how we handle feature requests.

**Comment by Eddi-z** [comment]
the discussion in #7000 might be related to this

**Comment by andythenorth** [comment]
I considered re-opening this following Eddi's comment, but let's see what #7000 delivers first.
