### ISSUE TITLE
Music plays on my spearkers, sound effects plays on my headphones

### ISSUE THREAD

**Issue by thewinner958** [OpenTTD/OpenTTD#6950]
Hi there, I am using Kali Linux (KDE) and I installed OpenTTD's latest stable (1.8.0) debian package on my computer. I was trying to use my headphones (HyperX Cloud 2) to play this game but only outputs the sound effects, while the game music outputs on my speakers. What should have happened was both music and sound effects output on the same device (aka. my headphones). Can someone help me?

PS: I know that it is outside of the issue (and possibly the guidelines), but I kinda need to tell this. If you think that I am just some rambling kid who has a weird picture, then do not reply to this issue. I am not kidding, you can just save your time replying and also my time to read the. What I just need is answer to my issue and that's all.

**Comment by nielsmh** [comment]
Most likely you're having music played via Timidity. I'm not sure how your audio configuration is, whether you're using pure ALSA, or if you use PulseAudio on top of ALSA, but I suspect it's the latter. It's also likely that Timidity then either uses ALSA output, while OpenTTD uses PulseAudio for output, in which case the ALSA output might end up on a different output device in one way or another. Alternatively, Timidity does not know how to properly follow the system default output device.

Either way, the problem probably lies with Timidity somewhere, but can probably also be worked around by changing some configuration or either Timidity, ALSA, or PulseAudio.

**Comment by thewinner958** [comment]
Yeah I have no idea how to configure Timidity, ALSA and PulseAudio, so if someone can help me configure these, I will be really thankfull, or I could just close the issue and switch to Windows.

**Comment by nielsmh** [comment]
We have an open PR for a new music driver based on Fluidsynth, #6901. If we can get that merged it will probably avoid issues like this in the future, at least.

I suggest you ask a general users' forum for your distro about configuring PulseAudio or ALSA to send ALSA output to your intended device, since Timidity can only output via ALSA. (I just checked.)
