### ISSUE TITLE
GSTown.PerformTownAction crashes OpenTTD if called during world generation

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#6966]
To reproduce this, do the following:
1. Download the attached Game Script (appears as "BaseGS" in list)
2. Select it in the AI/Game Script menu.
3. Start new game.
4. OpenTTD crashes when it's world gen phase should have moved to "Running script".

Note: OpenTTD only crashes due to GSTown.PerformTownAction if it is called under a valid company scope and during world generation. If GSTown.PerformTownAction is called outside of valid company scope, or during the main gameplay, OpenTTD does not crash.

[Test Game Script](https://github.com/OpenTTD/OpenTTD/files/2564746/Basegs.tar.zip)
[Attached crash files](https://github.com/OpenTTD/OpenTTD/files/2564748/crash.zip)

**Comment by Alberth289346** [comment]
The zipped `BaseGS.tar` file has no `BaseGS` directory prefix, either unpack the tar in such a directory or rebuild the tar to include such a directory.

The application crashes on
``` cpp
openttd: /home/alberth/openttd/openttd.git/src/ai/../core/pool_type.hpp:113: Titem* Pool<Titem, Tindex, Tgrowth_step, Tmax_size, Tpool_type, Tcache, Tzero>::Get(size_t) [with Titem = Company; Tindex = Owner; long unsigned int Tgrowth_step = 1; long unsigned int Tmax_size = 15; PoolType Tpool_type = (PoolType)1; bool Tcache = false; bool Tzero = true; size_t = long unsigned int]:
Assertion `index < this->first_unused' failed.
```
where `_company_pool.first_unused` is 0 (ie no **Companies** available in the pool).

**Comment by LordAro** [comment]
Same assert as #6605 & #6507 ...

**Comment by Alberth289346** [comment]
#6605 and #6507 crash on town pools rather than company pools, so this issue is different
