### ISSUE TITLE
BaNaNaS: Unhandled exception when uploading new

### ISSUE THREAD

**Issue by Balsiefen** [OpenTTD/OpenTTD#6967]
Hi, can't find anyone else with this problem. Bananas is throwing an 'Unhandled Exception' error whenever I click "Upload New" in my manager page. I seem to still be able to edit/update the files I've already uploaded so the problem is specifically with the upload new button.  I've tried both with chrome and edge and I get the same error.

**Comment by planetmaker** [comment]
Make use of our upload tool MUSA: https://www.tt-forums.net/viewtopic.php?f=29&t=63119

**Comment by Balsiefen** [comment]
Thanks. Not having much luck with that either though. I've downloaded the executable and the C++ package but the  musa.exe seems to just open and close immediately without doing anything.

**Comment by planetmaker** [comment]
Read musa's description... it's a command line tool.

**Comment by Balsiefen** [comment]
I'm afraid that's not something I'm familiar with.

**Comment by Balsiefen** [comment]
Is there any option for those not used to code/scripting? Or a simplish tutorial perhaps? I'm afraid I only usually make scenarios so I'm rather out of my depth with this.

I take it Bananas' upload function has been taken down deliberately also.

**Comment by andythenorth** [comment]
Thanks for reporting.  Bananas is known to be broken currently.

Please see https://github.com/OpenTTD/OpenTTD/issues/6940

A fix is unlikely.

There is a forum thread here https://www.tt-forums.net/viewtopic.php?f=26&t=83908 - Musa help may be available from other users there :)

**Comment by Balsiefen** [comment]
Oh dear. Anywhere I can get help for musa then?
Edit: Thanks andy.

**Comment by andythenorth** [comment]
Duplicates #6940

**Comment by TrueBrain** [comment]
Thank you for reporting this issue! Although we heavily prefer people to use musa for various of reasons (upload limit issues with HTTP, among others), it turns out the page was not rendering due to an UTF-8 issue in the backend.

Names of uploads should always be latin-1, but there is a flow that allows non-latin-1 characters to slip in. We are still not sure how. In this case, there was (well, two to be more exact) an upload with the name "ÖBB set". This Ö causes some weird trouble.

I resolved the issue for now by renaming the Ö to O, so the Upload New should work again. Still, please consider using musa :)

Tnx again for the report!

**Comment by spnda** [comment]
Thanks for fixing it, I am also very sorry for naming the GRF "ÖBB Set"....
I will prevent this in further uploads until Bananas is made compatible to handle this.
Also, it would be nice if you could change it again to "Austrian Trains" for completely resolving the issue.

**Comment by TrueBrain** [comment]
Haha, tnx @ThePNDA :D I changed the name of both entries as requested ;)

**Comment by spnda** [comment]
Hey @TrueBrain,
This is already a while back and it was fixed. 
I just saw someone uploading a GRF with a "™️" at the end of the name and you now can't upload anything new. This might have something to do with it. Its throwing the same error as it did the last time. 
```
Unhandled Exception
An unhandled exception was thrown by the application.
```
GRF Name: U&ReRMM™
GRF Author: ufiby89
Thanks :D

**Comment by Ufiby** [comment]
Sorry I broke it, not knowing what the symbol was.

**Comment by andythenorth** [comment]
@Ufiby we know it's not deliberate, thanks for dropping by to comment :) Hopefully it gets fixed soon.

**Comment by TrueBrain** [comment]
@Ufiby: no worries; it is a system bug, so you as user are never to blame. Hopefully soon someone can fix it .. till then, we have to be reactive, and fix when it breaks :)

I removed the "tm", hope you don't mind!

@ThePNDA : tnx for the report; much appreciated :)

All fixed again!

**Comment by Ufiby** [comment]
Thank you! :)

ср, 9 янв. 2019 г. в 19:44, Patric Stout <notifications@github.com>:
