### ISSUE TITLE
Bug in extracting .tar file

### ISSUE THREAD

**Issue by RailwAI** [OpenTTD/OpenTTD#6969]
When in OpenTTD the AI RailwAI (version 8 or version 9) is downloaded from BaNaNaS, OpenTTD seems to incorrectly extracts the downloaded .tar file. Specifically: the file shippathfinder.nut gets an additional 3 bytes appended. Because the tar file doesn't have zero-padding here, the characters "Rai" are added, that are part of the folder/filename for the next file in the .tar file.
Extracting the downloaded .tar file with any extraction software (I use 7-zip) and put the files in the ai-folder gives the correct version of the AI. Thus, it is clearly a bug in openTTD that needs to be solved.

Note that I'll give the AI an update (version 10), hoping to work around this issue. For reproducing the bug, one can download [version 9](http://binaries.openttd.org/bananas/ai/RailwAI-9.tar.gz) and put it manually in the content_download folder.

**Comment by LordAro** [comment]
An impressive find! This bug was only triggered because shippathfinder.nut is an exact multiple of 512 bytes in size *and* has a (3 byte) BOM, which was not being accounted for. A single byte longer and the tar file would've added another 512 bytes of padding and no one would've noticed :)

**Comment by RailwAI** [comment]
Thank you for the quick fix!
