### ISSUE TITLE
Minor spelling mistake in comment of code.

### ISSUE THREAD

**Issue by comicsads** [OpenTTD/OpenTTD#6977]
This is honestly the smallest thing I can think of so I'm not sure if I'm supposed to create an issue for it but the contributing.md didn't offer anywhere better to put this.

On line 366 of OpenTTD/src/script/script_event_types.hpp there's a multi line comment that says
`The company that can be bough.`
And I'm pretty sure it's supposed to be "bought."
A quick grep through the OpenTTD folder shows that this typo doesn't show up anywhere else (command I used on unix was `grep -Ri bough OpenTTD/ | grep -vi bought`)
That's all though, sorry if I did anything incorrectly it's 2 am, and thanks for making an amazing game.

**Comment by SpComb** [comment]
If you browse the source file on GitHub, you'll find an edit button that lets you easily make minor edits 
like this to the file: https://help.github.com/articles/editing-files-in-another-user-s-repository/

You'll find the file here: https://github.com/OpenTTD/OpenTTD/blob/master/src/script/api/script_event_types.hpp

The GitHub editor will automatically fork the repo for you, and submit a PR.

**Comment by TrueBrain** [comment]
We would very much welcome a Pull Request fixing this :) Going to close this issue now, and I hope you (@comicsads) will make a PR for us soon :) Tnx!

**Comment by comicsads** [comment]
I think I created a pull request. This is my first time contributing to a git project but I think I did everything correctly.
Can't wait to brag to my friends about being _technically*_ featured in the blame!
