### ISSUE TITLE
Current (1.8.0) macOS binaries out-of-date (deprecation warning because of 32bit on start)

### ISSUE THREAD

**Issue by WS3023** [OpenTTD/OpenTTD#6978]
Program needs to be updated for newest Mac OS. Computer says it will not work after next update.

**Comment by nielsmh** [comment]
This is something we're aware of. The game code itself does not need any changes, only the tooling used to prepare a release. While working on a new toolchain to make automated releases compatible with future macOS versions, we might look into making a one-off build of the current release that will also be forward-compatible.

**Comment by TrueBrain** [comment]
Possibly fixed with #6916. Keeping this ticket around to validate if it that is the case.

**Comment by TrueBrain** [comment]
@andythenorth can you investigate (if possible) what the exact issue is? 32bit? 10.8? (current binary is both 32bit and targeted for 10.8)

**Comment by andythenorth** [comment]
I assume the OP is seeing the 32-bit deprecation warning, which is present in 10.13.6 (High Sierra).

<img width="731" alt="32-bit-deprecation-warning" src="https://user-images.githubusercontent.com/1780327/48978339-2fac7680-f0a2-11e8-90d4-7063f3b76111.png">

10.14.x (Mojave) will be the last macOS to run 32 bit apps.
https://support.apple.com/en-gb/HT208436

AFAICT, when I compile locally, I'm getting a 64 bit build.  

As we can't currently compile official binaries, it's fine to park this until compile farm is rebuilt.

**Comment by andythenorth** [comment]
Officially compiled binaries are now being tested.  The Mac binaries produced by the new cf are 64 bit, so this ticket can be closed when the new cf is finished.

**Comment by TrueBrain** [comment]
Will be fixed by issue #6916. Closing this in favor of the other.
