### ISSUE TITLE
Version names truncated after move to git

### ISSUE THREAD

**Issue by nielsmh** [OpenTTD/OpenTTD#7021]
Builds of most non-master branches will currently print `dbg: [misc] String too long for destination buffer` messages to the console. This is a symptom of the version strings generated being longer than the 15 byte buffer allocated.

This becomes relevant especially for network games. The server's version name is truncated to 15 bytes, which can lead to unrelated versions being indistinguishable, with a large risk of desyncs.

https://github.com/OpenTTD/OpenTTD/blob/5ff6053326c060c0c717a0b5745423dda92d7af9/src/network/core/game.h#L44
https://github.com/OpenTTD/OpenTTD/blob/5ff6053326c060c0c717a0b5745423dda92d7af9/src/network/core/config.h#L40

As far as I can tell, it should be possible to increase `NETWORK_REVISION_LENGTH` without breaking compatibility with older clients. The `Recv_string` function does handle data longer than the supplied buffer, and will truncate strings longer than the buffer.

https://github.com/OpenTTD/OpenTTD/blob/5ff6053326c060c0c717a0b5745423dda92d7af9/src/network/core/packet.cpp#L242-L265

The main thing to watch out for with increasing `NETWORK_REVISION_LENGTH` is the MTU for UDP server discovery packets. Increasing it by 20 will cost one possible NewGRF for network games, but should cover most if not all cases.

**Comment by Eddi-z** [comment]
i'd rather make sure the string is cut in a way that the end is always included, as that tends to include the revision hash and makes the versions distinguishable. or make a hash of the complete string and transmit that.

**Comment by nielsmh** [comment]
Possibly transmit just the revision hash (that should normally be enough), perhaps encoded in a way so more of the hash fits in 15 bytes, perhaps with some indicator bits for modified/non-modified checkout and release build or not.

**Comment by nielsmh** [comment]
I tried summing up the packet structure as it currently is:

field | size | repeats | total
-- | --: | --: | --:
packet size | 2 | 1 | 2
packet type | 1 | 1 | 1
network game info version | 1 | 1 | 1
newgrf count | 1 | 1 | 1
newgrf data | 20 | 62 | 1240
game date | 4 | 1 | 4
start date | 4 | 1 | 4
companies max | 1 | 1 | 1
companies on | 1 | 1 | 1
spectators max | 1 | 1 | 1
server name | 80 | 1 | 80
server revision | 15 | 1 | 15
server lang | 1 | 1 | 1
use password | 1 | 1 | 1
clients max | 1 | 1 | 1
clients on | 1 | 1 | 1
spectators on | 1 | 1 | 1
map name | 80 | 1 | 80
map width | 2 | 1 | 2
map height | 2 | 1 | 2
map set | 1 | 1 | 1
dedicated | 1 | 1 | 1
**Total** |  |  | **1442**

The MTU we work with is 1460 bytes, meaning there should be room for 18 bytes expansion. I suggest expanding server revision by 17 bytes to 32 bytes.

**Comment by nielsmh** [comment]
A separate issue is the gamelog. It also uses the NETWORK_REVISION_LENGTH constant for the size of revision string it writes to the log, I'm not sure how safe it would be to increase the size here, is this ever written to a file as a binary format? Ideally the field should probably be sufficiently long to contain a full untruncated "display revision string" i.e. the one used in the title screen window.

**Comment by glx22** [comment]
Game log is stored in the savegame IIRC
https://github.com/OpenTTD/OpenTTD/blob/b60b193a6d9b682f731b24763b44108d7fccd7f8/src/saveload/gamelog_sl.cpp#L32
may be a problem

**Comment by nielsmh** [comment]
https://github.com/OpenTTD/OpenTTD/blob/82fc28f77f4ba1d613c1930781f77b45e4af5121/src/gamelog_internal.h#L36-L49
This union definitely makes it difficult to change. Should probably just write a prefix of the revision hash to this.
