### ISSUE TITLE
Ugly regular font after FreeType update

### ISSUE THREAD

**Issue by Epicus7** [OpenTTD/OpenTTD#7032]
After 3be6ab555caf54222c7a43a188558ed6ec51e11a regular font (not bolded as in english translation) has become ugly. Especially noticeable, for example, in the Russian translation.

![image](https://user-images.githubusercontent.com/5204667/50939508-39414080-148e-11e9-8079-7de24680c476.png)

* OpenTTD was compilled with **Visual Studio 2017** and runned on **Windows 10** with **Russian localization**.
* All libraries was dowloaded via vcpkg, according to readme.
* OpenTTD version is 5e51d9ee823af27d00f88ef38ea4753e249e296c.

The problem is new version of **FreeType library (>=2.8.0)**. You can downgrade it to 2.6.3 by vcpkg or take version from "useful" pack and see how fonts looked like earlier.

The small font on the map is generally unreadable, so it's impossible to play with such font.

I have tried to enable antialiasing, but it makes fonts blurred and texts should be readable without it as in previous version.

OS: Windows 10 x64
Compiler: VS2017
Version: 5e51d9ee823af27d00f88ef38ea4753e249e296c
Localization: Russian

Steps to reproduce:
* Prepare 3rd-party libraries according to readme, using vcpkg.
* Check version of FreeType (.\vcpkg list). It should be 2.8.1.
* Compile with VS2017.
* Run OpenTTD.
* Enable Russian localization.
* Fonts are ugly :(

Steps to see how fonts were looked earlier (or you can just run OpenTTD 1.8.0 release with Russian localization):
* Remove FreeType (.\vcpkg remove freetype:x64-windows-static)
* Revert FreeType folder of vcpkg repo to 2.6.3 (git checkout f7de134 -- ports/freetype)
* Install FreeType (.\vcpkg install freetype:x64-windows-static)
* Recompile OpenTTD with VS2017, run and change localization to Russian.
* Fonts are fine.

**Comment by nielsmh** [comment]
I think the issue has to do with hinting, or perhaps lack of it.

**Comment by glx22** [comment]
Using MSYS2, fonts are ugly with freetype 2.9.1 too

**Comment by PeterN** [comment]
Is anyone able to try with an update-to-date freetype on Linux? Mine is from Debian Stable, so not so much...

**Comment by planetmaker** [comment]
For what it's worth: on linux with libfreetype 2.8 the same issue shows.
