### ISSUE TITLE
Disconnected towns during world generation

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7043]
[14:59] Samu> bt, I found a bug regarding town bridges, during world generation the code deletes towns that are generated with 0 population, but by doing so, nearby bridges are also removed
[14:59] Samu> btw*
[14:59] Eddi|zuHause> then maybe the code that assigns bridge ownership is wrong?
[15:00] Samu> those bridges didn't belong to the town being deleted
[15:00] Gabda> it is a world generated bridge
[15:00] Samu> it results in disconnected towns

https://imgur.com/a/hqCAgsO

![dbbzcfq](https://user-images.githubusercontent.com/43006711/51075001-b2eb5100-167d-11e9-8bd4-b6996bf27ef9.jpg)
![i7epssm](https://user-images.githubusercontent.com/43006711/51075002-b54dab00-167d-11e9-81ca-664216bd180c.jpg)

**Comment by J0anJosep** [comment]
I think that storing the TownID of the town that builds the bridge on the map array instead of using CalcClosestTownFromTile(*) would solve the problem. The needed space in the map array is free.

Lots of pieces of code will need to be changed, but changes are easy and mostly obvious. I think it is a **good first issue**. Feel free to investigate if my suggestion is right.

See these functions (for a starting point):
GetTownIndex
SetTownIndex
CmdBuildTunnel
CmdBuildBridge
GrowTownInTile
(update also doc landscape*.html)

**Comment by fibbo** [comment]
Is there a way to reproduce this so it's testable? I don't know the game very well but I'm interested in contributing to this project because I think it's amazing.

**Comment by TrueBrain** [comment]
It might be a bit trial and error at first, to find a map seed that shows this on the generation screen (so you can spot it going wrong). Once you have found such map, you could regenerate the same map with the same seed. `getseed` in the console gives the seed of the map. Possibly that helps out? (I am a bit guessing here; possibly there are easier ways).

**Comment by SamuXarick** [comment]
A town is created here:
https://github.com/OpenTTD/OpenTTD/blob/master/src/town_cmd.cpp#L1957


If it's generated with 0 population, it is deleted right away. The deletion code takes bridges of nearby towns away by mistake, here:

https://github.com/OpenTTD/OpenTTD/blob/master/src/town_cmd.cpp#L93

**Comment by andythenorth** [comment]
Why does OpenTTD even generate towns with popn. 0?   It's odd to permit this then remove the result if 0 popn.

Is this simply to handle the case of pathological sites where no buildings can be located, and/or pathological placement rules for newgrf houses?

**Comment by PeterN** [comment]
To make a town, a town is created and then it grows it for several iterations. During this iteration is when it discovers a site is suitable. If it ends up with no population, the town is then removed as unviable. It is very rare, though.

**Comment by andythenorth** [comment]
If this was my solo project, I'd probably just have done "popn = 8 + sum(popn buildings)".  Nobody would _ever_ notice 😈  Might have a problem producing pax for transport with no buildings though.
