### ISSUE TITLE
Ship pathfinders ignore the max order distance

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7062]
https://github.com/OpenTTD/OpenTTD/blob/6b0a467a50c706546129044a5bd6013bf6d310a1/src/ship_cmd.cpp#L462
[Fentwood Transport, 1954-11-03.zip](https://github.com/OpenTTD/OpenTTD/files/2757414/Fentwood.Transport.1954-11-03.zip)

After #6784, the ship in this savegame becomes lost.
The ship becomes out of distancemanhattan reach, and the pathfinder won't be invoked.

When the ship reaches map border and comes back again, it becomes within distancemanhattan reach and re-invokes the pathfinder again, only to get out of reach again, lost.

**Comment by PeterN** [comment]
The path distance between the two docks is too far, you need to use buoys.
I believe it's a bug that the pathfinders ignore the max order distance.

**Comment by J0anJosep** [comment]
It is difficult for pathfinders to be constrained by SHIP_MAX_ORDER_DISTANCE + 5, as that is a condition for consecutive orders in ManhattanDistance, not for the length of the path. I don't think it is a bug of the pathfinders.

**Comment by PeterN** [comment]
Likely the change that caused this could be partially reverted now that we have ship path caching.

**Comment by PeterN** [comment]
In fact, since we have ship path caching, it is now feasible to remove the ship order distance limit completely.

**Comment by TrueBrain** [comment]
Rescheduling to 1.10 for a proper solution, given that the PR that fixes this depends on 2 other PRs, which are not approved yet. Especially as this has been a long outstanding issue, I see no reason to rush this for 1.9.
