### ISSUE TITLE
Crash when Removing NewGRF from Active list

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7089]
Steps
- launch OpenTTD
- click NewGRF Settings
- add a NewGRF to the top list
- select it at the top list
- click License
- without closing the License window
- remove the selected NewGRF

Crash!

**Comment by andythenorth** [comment]
Reproed.  I had to click 'apply' to get the crash.

**Comment by SamuXarick** [comment]
crashes here: https://github.com/OpenTTD/OpenTTD/blob/master/src/newgrf_config.cpp#L128


  | Name | Value | Type
-- | -- | -- | --
◢ | name | 0xcccccccccccccccc <Error reading characters of string.> | const char *

0xcccccccccccccccc <Error reading characters of string.>

**Comment by glx22** [comment]
yeah 0xccc... values are guards added around memory allocations by MSVC in debug builds to check for invalid accesses
