### ISSUE TITLE
Query box sets value to hidden parameters

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7090]
This bug require many steps to reproduce. AIAI v97 will serve as example. It is an AI that has hidden parameters that become visible when ai_developer_tools is on.

Steps:
- launch openttd
- start new game
- open console
- type in 'startai aiai'
- type in 'set ai_developer_tools on'
- open AI/GS Debug window
- click Settings
- scroll the bar down to the last parameters
- open a query box in one of them, for instance, 'no_road_cost' (default value should be 1)
- before changing the value, type in console 'set ai_developer_tools off'
- now change the value in the query box (to 123 or so) and click OK
- back to the console, type in again 'set ai_developer_tools on'
- scroll down the list of AIAI settings again to the bottom

Bug: 'no_road_cost' was changed to the new value (123)

**Comment by SamuXarick** [comment]
> now change the value in the query box (to 123 or so) and click OK

In debug build, clicking OK crashes OpenTTD at this point.

**Comment by SamuXarick** [comment]
![2019-01-25 3](https://user-images.githubusercontent.com/43006711/51778777-7d257e00-20fb-11e9-993b-b12b7843fea7.png)

https://github.com/OpenTTD/OpenTTD/blob/master/src/ai/ai_gui.cpp#L537

**Comment by glx22** [comment]
I noticed many problems with missing invalidation in these windows. This issue and #7091 are two of them, but there's also the textfile window and more.
