### ISSUE TITLE
Dropdown menu can set value to a parameter of a different AI

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7091]
Requires two AIs. AroAI v127 and LuDiAI AfterFix v7 will serve for this report.

Steps:
- launch openttd
- click AI/GS Settings
- click Select AI
- select LuDiAI AfterFix and click Accept
- click Configure
- click the first parameter, 'Town Cargo' dropdown menu, but don't chose anything yet
- back to the previous window, click Select AI
- Select AroAI
- Before clicking Accept, ensure that 'Town Cargo' dropdown menu is still open
- After clicking Accept, the list of settings change to the new AI, but the dropdown menu is still open
- The new first parameter is now 'Enable Road Vehicles' and is shown as enabled.
- Now click 'Passengers' from the dropdown menu.

BUG: 'Enable Road Vehicles' of AroAI becomes disabled.

**Comment by SamuXarick** [comment]
If the AI that is switched to is Random AI, which has no parameters, clicking 'Passengers' will crash OpenTTD, but only if it's a debug build.

**Comment by SamuXarick** [comment]
![2019-01-25](https://user-images.githubusercontent.com/43006711/51778313-f079c080-20f8-11e9-99b7-3e07a905c2fb.png)

**Comment by SamuXarick** [comment]
> https://github.com/OpenTTD/OpenTTD/blob/master/src/ai/ai_gui.cpp#L549

**Comment by glx22** [comment]
I noticed many problems with missing invalidation in these windows. This issue and #7090 are two of them, but there's also the textfile window and more.
