### ISSUE TITLE
Crash: cannot dereference end map/set iterator

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7098]
Can only trigger this crash in debug build.

Steps:
- Start a new game

Crashes exactly here:
https://github.com/OpenTTD/OpenTTD/commit/05da5a177c7e976d5da0da541a842482ab23017d#diff-2ae6b3007c6f3365cdb8e428dc6439d2R316

> ---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Assertion Failed!

Program: ...OpenTTD GitHub\OpenTTD\projects\..\objs\x64\Debug\openttd.exe
File: c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\xtree
Line: 222

Expression: cannot dereference end map/set iterator

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

---------------------------
Abortar   Repetir   Ignorar   
---------------------------

**Comment by PeterN** [comment]
Reproduced with MSVC 2017 build. No issue on Linux.

ts.tile_to_new_height does not contain tile. I wonder if the check on line 316 is inverted? It doesn't make sense as is.

**Comment by nielsmh** [comment]
That would be the integration of #7061 introducing this bug then.
