### ISSUE TITLE
Ships turning around pixel alignment

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7119]
This is difficult to spot, but I noticed in the master main menu savegame.

When the hovercraft is departing from the bottom dock and is facing south, it will make a turn to its right. Just before turning, I could spot a misalignment, the ship tilts horizontally to the left while it's still in a vertical position.

The same thing I noticed when the ship is facing east and turns to its left. Just before turning, the ship tilts vertically up while it's still in a horizontal position.

Hope this explanation makes sense.

**Comment by PeterN** [comment]
I remember seeing this during development, and making an elaborate set of changes that made it work visually, but ended up causing tons of crashes. I guess I dropped it...

**Comment by andythenorth** [comment]
Nice spot!  Sounds like it's TMWFTLB to fix though, so we'll let this one go unfixed.

**Comment by PeterN** [comment]
I'm not sure it's TMWFTLB, I haven't had a chance to look too much into it yet.

**Comment by J0anJosep** [comment]
This should be reopened and fixed. It cannot be left like this for the next release.

**Comment by PeterN** [comment]
The issue is the ship moves and gets a new direction, but we postpone the direction a few ticks. If the ship does not move, we cannot set the new direction.
