### ISSUE TITLE
Convert singleplayer game to multiplayer server

### ISSUE THREAD

**Issue by nielsmh** [OpenTTD/OpenTTD#7125]
It'd be neat to have a feature to convert a singleplayer game to a multiplayer server, without going through a manual save-quit-reload cycle.

**Comment by M3Henry** [comment]
I have seen some games where single-player is just a multiplayer server that only accepts one local connection.

**Comment by PeterN** [comment]
@M3Henry That wouldn't be appropriate here as it would involve running the whole simulation twice.

**Comment by nielsmh** [comment]
For the record, the background for this idea was some discussion on IRC about maybe adding some kind of IPC interface to OpenTTD that would allow other local software such as Discord or perhaps Steam to query status of the game, and help with matchmaking with friends. The idea here being that if you were playing singleplayer you could simply invite your friends to the game and it would be converted to a network server.
