### ISSUE TITLE
custom font settings in openttd.cfg seem to be ignored

### ISSUE THREAD

**Issue by paulcobbaut** [OpenTTD/OpenTTD#7126]
In openttd.cfg there are custom font settings:

`small_font = DejaVu Sans`
`medium_font = DejaVu Sans, Bold`
`large_font = DejaVu Serif, Bold`
`mono_font = DejaVu Sans Mono, Bold`
`small_size = 12`
`medium_size = 12`
`large_size = 16`
`mono_size = 12`

The current nightly build ignores these settings (only in Mac OSX?), resulting in very tiny fonts in 'Map of world' and in the 'Trains' dialog.

The wiki mentions these settings here https://wiki.openttd.org/FAQ_troubleshooting#My_User_Interface_is_too_small_to_read_.2F_My_font_is_unreadable_or_faulty as a solution to tiny unreadable fonts. I have tried editing these settings with other fonts, and with the full path to the fonts, but that didn't help.

The resulting tiny fonts are only 4 or 5 pixels high, making them unreadable on 1920x1200 resolution. (I have a retina Mac.)

**Comment by nielsmh** [comment]
They work for me on Windows. It's probably a Mac-only issue.

**Comment by PeterN** [comment]
Do you have these fonts installed, to start with?

**Comment by paulcobbaut** [comment]
Yes I have the fonts installed. I even tried installing custom fonts in ~/Library/Fonts, same thing.
OpenTTD 1.8.0 works fine with these font settings and fonts.

**Comment by PeterN** [comment]
Thanks for confirming that.

**Comment by PeterN** [comment]
Confirmed on Linux. Some fonts work, not all do. Font is requested, and does not error, but then it seems to fallback to another font instead.

This is caused by missed glyphs in the typeface. If just a single glyph is missing it will fall back to a default font, however, there is no warning that this has happened!

"Polish Złoty" is in the English translation and seems to trip up most typefaces I have.

**Comment by PeterN** [comment]
Hmm, sorry, not confirmed at all. For me, if a typeface doesn't work, it falls back to a default font, not the bitmap fonts. Which version of OpenTTD are you using? Is it self-compiled or downloaded from us?

**Comment by paulcobbaut** [comment]
I've downloaded the last nightly build every day since filing this issue. Map view and trains list have very tiny fonts, even when I set font size to 24.
<img width="541" alt="screen shot 2019-02-28 at 3 01 03 pm" src="https://user-images.githubusercontent.com/524195/53571701-d6088c00-3b69-11e9-8224-ff368f0cfba5.png">

I have just tested with 1.8.0 again, and this works as documented (though size 24 is huge ;-).

I have also noticed that when completely removing openttd.cfg, then version 1.8.0 will generate a new one with empty font lines, whereas the nightly build generates a new openttd.cfg without any of the font configuration lines.

Please let me know if I can do anything else to help this issue (log files? debug options?). I have MacOS 10.14.3 Mojave.

**Comment by PeterN** [comment]
I wonder if simply the OS X build is built without freetype support...?

Confirmed!
`checking freetype2... not found`
