### ISSUE TITLE
Graphics glitch with tunnels

### ISSUE THREAD

**Issue by George-VB** [OpenTTD/OpenTTD#7133]
![image](https://user-images.githubusercontent.com/43310520/51886221-ecbb9780-239f-11e9-9889-092abef9fc99.png)
Graphics glitch with tunnels in trunk 20190127

**Comment by Eddi-z** [comment]
Can't reproduce this with default graphics, got a NewGRF to test this with?

**Comment by PeterN** [comment]
Confirmed with various NewGRF track sets. Only the NE tunnel head is affected.

**Comment by PeterN** [comment]
Caused by commit 479f13fc4133f2970aff82d2d0fb9b3c0cb919da

**Comment by nikolas** [comment]
I'm seeing some similar glitches on master. Here's an example between a boat and a bridge:
![2019-01-30-200529_1366x768_scrot](https://user-images.githubusercontent.com/59292/52023282-854e3680-24ca-11e9-811a-9b2d15871311.png)

I've seen similar behavior with buses when they get close to buildings.

**Comment by nikolas** [comment]
Here's another example of that tunnel glitch, on master. Just posting this here in case it's helpful.
![2019-01-30-233325_1366x768_scrot](https://user-images.githubusercontent.com/59292/52030800-85106400-24e7-11e9-9acf-b2a1164e0bcf.png)

And as soon as a train went through, the glitch disappeared:
![2019-01-30-233518_1366x768_scrot](https://user-images.githubusercontent.com/59292/52030864-bdb03d80-24e7-11e9-9295-d8be10fd3bd2.png)

It seems to happen when a train is in the tunnel.

**Comment by nikolas** [comment]
Okay, what's causing this glitch for me is the "Show path reservations for tracks" option. The glitch is caused by the path shadow when a train has this path selected. So it should be reproducible pretty easily.

I can't say whether or not this is the same issue that George is having.

**Comment by George-VB** [comment]
Fixed successfully
