### ISSUE TITLE
Sprite sorting issue with FIRS

### ISSUE THREAD

**Issue by George-VB** [OpenTTD/OpenTTD#7136]
![image](https://user-images.githubusercontent.com/43310520/51923570-4baefa00-23fc-11e9-99c8-a0988a837019.png)

**Comment by LordAro** [comment]
It's very unclear from this (even with the nice red box) what's wrong with this image and what it is supposed to look like. Can you elaborate?

**Comment by PeterN** [comment]
This is likely related to #7133, as both involve child ground sprites.

**Comment by PeterN** [comment]
@George-VB, in your bug report please elaborate on what the issue is. You should write down what you expected to happen, and what behaviour happens instead. Just a single picture is not really enough. You should also include steps to reproduce this issue. That is standard bug-reporting etiquette!

**Comment by George-VB** [comment]
I expect ground tiles to be drawn "behind" objects on them
![image](https://user-images.githubusercontent.com/43310520/51930885-989acc80-240c-11e9-9a32-bb50ca4ac2ca.png)

**Comment by PeterN** [comment]
Thanks @George-VB. I have now play tested another NewGRF and in that case the images are flickering as well. Definitely a sprite-sorter issue.

**Comment by George-VB** [comment]
Fixed successfully
