### ISSUE TITLE
Editable AI/GS Parameters in the 3 game modes

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7144]
## Version of OpenTTD
2019-01-30-g8334a573

## Expected result
Main Menu:
- GS config in slot, GS instance active, alive: all parameters editable
- GS config in slot, GS instance active, dead: all parameters editable
- GS config in slot, GS instance not active: all parameters editable
- AI company in slot, AI instance active, alive: all parameters editable
- AI company in slot, AI instance active, dead: all parameters editable
- Hu company in slot: all parameters editable
- No company in slot: all parameters editable

Scenario Editor:
- GS config in slot, GS instance active, alive: no parameters editable
- GS config in slot, GS instance active, dead: no parameters editable
- GS config in slot, GS instance not active: all parameters editable
- AI company in slot, AI instance active, alive: no parameters editable
- AI company in slot, AI instance active, dead: no parameters editable
- Hu company in slot: all parameters editable
- No company in slot: all parameters editable

Normal Game:
- GS config in slot, GS instance active, alive: only in-game parameters editable
- GS config in slot, GS instance active, dead: all parameters editable
- GS config in slot, GS instance not active: all parameters editable
- AI company in slot, AI instance active, alive: only in-game parameters editable
- AI company in slot, AI instance active, dead: all parameters editable
- Hu company in slot: all parameters editable
- No company in slot: all parameters editable

## Actual result
Main Menu:
- GS config in slot, GS instance active, alive: not sure
- GS config in slot, GS instance active, dead: not sure
- GS config in slot, GS instance not active: all parameters editable
- AI company in slot, AI instance active, alive: not sure
- AI company in slot, AI instance active, dead: not sure
- Hu company in slot: not sure
- No company in slot: all parameters editable

Scenario Editor:
- GS config in slot, GS instance active, alive: only in-game parameters editable
- GS config in slot, GS instance active, dead: not sure
- GS config in slot, GS instance not active: all parameters editable
- AI company in slot, AI instance active, alive: only in-game parameters editable
- AI company in slot, AI instance active, dead: not sure
- Hu company in slot: only in-game parameters editable
- No company in slot: all parameters editable

Normal Game:
- GS config in slot, GS instance active, alive: only in-game parameters editable
- GS config in slot, GS instance active, dead: not sure
- GS config in slot, GS instance not active: not sure
- AI company in slot, AI instance active, alive: only in-game parameters editable
- AI company in slot, AI instance active, dead: only in-game parameters editable
- Hu company in slot: not sure
- No company in slot: all parameters editable

## Steps to reproduce
- Very boring steps

**Comment by SamuXarick** [comment]
Issues that currently happen on master:
- AI Config window in SE: loading a scenario of a savegame with multiple human companies, only one human company is displayed as being human. The other human companies can be selected and editable. It's not what happens on a NG (normal game).
- AI Config window in SE: loading a scenario of a savegame with AI companies, will allow selecting and moving AI slots up and down between AIs. This will cause AI crashes when the scenario is then loaded in a normal game, because they can't handle parameters of AIs that weren't theirs.
- AI Settings window in SE: non in-game parameters and Reset button are disabled when the slot is currently belonging to a Hu company.
- AI Settings window in SE or NG: Reset button is enabled for GS when a GS is running, but disabled for AI when an AI is running. Resetting the GS settings in this way will not consider whether all parameters are visible and editable.
- AI Config window on a NG: Max no competitors does not consider the first slot being without a company and will display it as selectable  when no more AI companies could start.
- AI Settings window in SE: loading a scenario of a savegame with AI companies, allows editing of in-game parameters when the instance is active. The way saved AI data is handled in the scenario editor is different than that in a NG. It's still the same data that was loaded that will be saved again when saving the scenario. I'm not sure AIs can handle their own parameters being altered in this manner, because when loading this back in a normal game, it's still gonna use the previously mentioned loaded data. Doesn't feel right.

**Comment by PeterN** [comment]
One issue per... issue, please.
