### ISSUE TITLE
Town Y value reported by var 80 is inconsistent on different map sizes

### ISSUE THREAD

**Issue by PikkaBird** [OpenTTD/OpenTTD#7149]
Town var 80 is the XY of the town. On a 256x256 map, the variable returns the expected values. On all map sizes, the X value in the low byte appears to work correctly (town X position truncated to a byte).

On larger or smaller maps, however, the Y value becomes erratic. On larger map sizes, it multiplies, and can take an overflow from the X coordinate. On smaller map sizes, it halves, with odd values underflowing into the X coordinate. The behaviour seems to be the same whether the variable is accessed as the high byte of var 80, or as var 81.

A test newgrf is attached. The reported values from var 80 are stored in the persistent town registers - to view them, inspect a test house then click the "parent" button.

![image3](https://user-images.githubusercontent.com/39507755/52029104-841a1980-255d-11e9-8c8e-d866a22c88cb.png)
Doubled Y value on 512x map
![image5](https://user-images.githubusercontent.com/39507755/52029105-84b2b000-255d-11e9-9423-ce3471a90e2e.png)
Halved Y value (with underflow) on 128x map
[testhouse.zip](https://github.com/OpenTTD/OpenTTD/files/2815612/testhouse.zip)

**Comment by Eddi-z** [comment]
Var 80 is not part of the specs, and the meaning has diverged a bit from the original TTD meaning. So i don't think this is technically a bug, but the behavior might need better documentation.

**Comment by PikkaBird** [comment]
Okay, I think I understand how it works now. I'll experiment.

**Comment by Eddi-z** [comment]
Basically, you need to read out the "X" bits from ["Patch Var 13"](https://newgrf-specs.tt-wiki.net/wiki/ReadingPatchVariables) and then recreate the [TileX/TileY functions](https://github.com/OpenTTD/OpenTTD/blob/ba38a7ca652c00a1d0851f4d97f0b7d360df853c/src/map_func.h#L207), this will be correct for all map sizes (smaller or bigger)

**Comment by PeterN** [comment]
This is an internal data variable which requires masking to get the data as required, and is working as expected.
