### ISSUE TITLE
Reverse at signal timeouts occur unexpectedly quickly, affects title game

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#7159]
## Version of OpenTTD
master: from commit e934f09f02a022c7ef3d54879ce6c07454c098a6 onwards

## Expected result
When _settings_game.pf.reverse_at_signals is true, reversing of trains at a red signal occurs after the interval given by _settings_game.pf.wait_oneway_signal or _settings_game.pf.wait_twoway_signal.

## Actual result
When _settings_game.pf.reverse_at_signals is true, reversing of trains at a red signal occurs at a shorter interval than expected.

## Steps to reproduce
Watch the title game for a few minutes, diesel trains going over the bridge at the top occasionally reverse on the bridge or in the the signal block prior to the bridge, due to moderate delays which are less than that given by _settings_game.pf.wait_oneway_signal. This did not occur prior to commit e934f09f and is probably undesirable in the title game.

**Comment by PeterN** [comment]
Seems to ultimately be caused by separate things using the same counter?

**Comment by J0anJosep** [comment]
Is it caused by https://github.com/OpenTTD/OpenTTD/pull/7114?

**Comment by JGRennison** [comment]
> Seems to ultimately be caused by separate things using the same counter?

Train::wait_counter is only used for one thing in this case.
It looks to me like the change in e934f09 would cause Train::wait_counter to be incremented every tick as the signal is now checked every tick, whereas previously some progress would have to be made between checks. Adjusting the scaling constants in the tests with _settings_game.pf.wait_oneway_signal or _settings_game.pf.wait_twoway_signal ought to be sufficient.

> Is it caused by #7114?

No, it is not a pathfinder issue. Reverting e934f09 is sufficient to resolve the issue.

**Comment by PeterN** [comment]
I was referring to the use of progress, not wait_counter.

**Comment by michicc** [comment]
With the current code, a train waiting at a one-way signal will increment wait_counter twice each tick, i.e. on both `TrainLocoHandler` calls.

Previously, the update rate of wait_counter depended on train speed and acceleration. For example train 2 from the title game (Turner Turbo) incremented wait_counter every ten ticks, while train 12 (Lev4) incremented every five ticks.

The easiest change would be to the factor in the `++v->wait_counter < _settings_game.pf.wait_oneway_signal * 20` line, to get an approximate and speed independent wait time. Factor 200 would be right for the Lev4, 400 for the Turner, but to avoid integer overflow 255 is the max factor anyway. So maybe just stick with it.

**Comment by PeterN** [comment]
Apart from being twice as fast, this new behaviour also seems to match the setting description better. However I guess the comment was wrong before. Should be possible to at least not increment it  on both `TrainLocoHandler` calls.
