### ISSUE TITLE
Network messages do not disappear after a while

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7161]
## Version of OpenTTD
20190202
## Expected result
Network messages disappear after a while
## Actual result
Network messages do not disappear after a while
## Steps to reproduce
- Start a multiplayer game.
- Create a new company.
- Wait.

Btw, I took a screenshot of it, but it's not displayed on the captured shot.

**Comment by PeterN** [comment]
Thank for your report!
