### ISSUE TITLE
GRF Airport landing trigger does not reflect documentation

### ISSUE THREAD

**Issue by frosch123** [OpenTTD/OpenTTD#7181]
4e9e115760658099a6dd5a677bdf03145ab93e82

The documentation in the source claims the animation trigger is called for all tiles.
But the implementation actually only triggers for the touchdown tile.

No idea what is intended, I also do not know anyone wanting to use it, so I suggest: revert.

**Comment by PeterN** [comment]
From the original feature request, the comment is wrong as the code was changed. The current intention does seem to be to trigger only at the landing tile.

**Comment by planetmaker** [comment]
IIRC it was ntended was the trigger for the touchdown tile of the airport so that it can draw skid marks on it.

It can be tested with OpenGFX+airports 0.5.0 with the  small modern airport
