### ISSUE TITLE
Can't send train to depot, paths are reserved for no reason

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7183]
## Version of OpenTTD
r27929M
## Expected result
Train should find depot
## Actual result
Can't send train to depot
## Steps to reproduce
Manually send train to depot
[Freningville Transport, 1989-05-08.zip](https://github.com/OpenTTD/OpenTTD/files/2832675/Freningville.Transport.1989-05-08.zip)

**Comment by PeterN** [comment]
The setting "pf.reserve_paths" is on, which is why paths are reserved.

**Comment by PeterN** [comment]
Invalid report, savegame was created with a modified version, including a savegame bump.
