### ISSUE TITLE
Both server and client crash, AI related

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7188]
## Version of OpenTTD
2019-02-06-master-gbfdad9ad1b
## Expected result
No crash
## Actual result
Crash
## Steps to reproduce
1 - on server, start multiplayer non-dedicated server game with 14 AIs set up, with 250000 #opcodes, build speed set to very fast, and a start_date of 0 on every AI.
2 - on client, join server as Spectator while not all companies have started yet.
3 - on server, open AI Debug Window, click Reload on one of the AIs. If it doesn't crash right away, try Reload on another AI, until one of them crashes.
4 - on client, a timeout of 20 seconds is displayed, then it crashes after that, I suppose when exiting to main menu, not sure.

[crash.log](https://github.com/OpenTTD/OpenTTD/files/2838675/crash.log)
[crash.log](https://github.com/OpenTTD/OpenTTD/files/2838736/crash.log)

![2019-02-06 4](https://user-images.githubusercontent.com/43006711/52380710-cf08c500-2a66-11e9-8019-07d1b2b4b8ea.png)
Left = server, Right = client

**Comment by SamuXarick** [comment]
[00:00] <Samu> for the client crash, I think the problem is here at network_client.cpp line 1176 and 1174 should be switched
[00:01] <Samu> CloseConnection makes _networking = false, and when the save occurs, it is already saving with no network
[00:01] <Samu> there is no instance running on the client, only on the server
[00:01] <Samu> should save empty

https://github.com/OpenTTD/OpenTTD/blob/bfdad9ad1b19dfd68c277641b406ebc98ee82af3/src/network/network_client.cpp#L1171-L1178

There are two emergency saves. Shouldn't 1 be enough? CloseConnection does an emergency save, then another is done after the error message. Is that the intention? Even the error message is repeated.

**Comment by glx22** [comment]
https://github.com/OpenTTD/OpenTTD/commit/4fb76db42f886ff21a9f60fc89c786de79d79705 added the function, and the extra call it seems.

**Comment by glx22** [comment]
And for the server crash, I think some test must be added to https://github.com/OpenTTD/OpenTTD/blob/bfdad9ad1b19dfd68c277641b406ebc98ee82af3/src/ai/ai_instance.cpp#L261
