### ISSUE TITLE
Station catching area corrupted

### ISSUE THREAD

**Issue by George-VB** [OpenTTD/OpenTTD#7198]
master 20190207
![image](https://user-images.githubusercontent.com/43310520/52519285-fda2bd80-2c69-11e9-93a9-ea2a2453f63b.png)
Station should not get food from industry
Looks like station catching area is calculated not as shown, but a ship station (the ship station is connected, but on the other side)

**Comment by nielsmh** [comment]
Total catchment area is not quite as you'd imagine from the visualisation of a single station part's catchment area.

The "base" station area is the orthogonal bounding box for all station parts (i.e. min and max X/Y bounds), and the catchment radius around that is the largest radius for any one station part. Meaning if you place an international airport outside a city, and then link a single bus stop to it, up to 16 tiles away (or however settings are set), that bus stop will not just have the same catchment radius as the airport, but all the empty tiles between the two parts will also be considered.

**Comment by Eddi-z** [comment]
Short version: if you add a dock to a station, all station tiles get a radius of 5, not just the dock tiles.
(there's also a discrepancy between delivering and receiving cargo for non-rectangular stations)

**Comment by nielsmh** [comment]
I tried making an illustration of the concept:
![image](https://user-images.githubusercontent.com/1062071/52519509-7b5fcc80-2c5c-11e9-92cc-4cbcda3c45b2.png)
![image](https://user-images.githubusercontent.com/1062071/52519512-7ef35380-2c5c-11e9-87df-a8052b03f67b.png)

The white outline is the combined station area, the purple is the catchment radius. The total catchment area is the sum of those.

**Comment by Eddi-z** [comment]
Here's an illustration of the deliver/receive discrepancy, the station accepts vehicles, but does not get any coal
![bardingham transport 24 feb 1965](https://user-images.githubusercontent.com/43699911/52519631-992e3100-2c5e-11e9-9a37-b478d8872053.png)

reason is, for delivering vehicles, the rectangle around the station is considered, like in nielsm's picture, and there is an industry tile in that rectangle (radius 4)

but for receiving coal, the rectangle around the industry is considered, and there is no station tile in the rectangle (radius 4)

**Comment by Eddi-z** [comment]
if you add another station tile, the train now loads coal
![bardingham transport 3 jun 1965](https://user-images.githubusercontent.com/43699911/52519671-502aac80-2c5f-11e9-9524-1880ea0496fb.png)

**Comment by George-VB** [comment]
Can drawing of the catchment area be improved in such a way, that allows to see the real area of the station? May be some button "show catchment area"?

**Comment by Eddi-z** [comment]
i believe someone tried that on the forum once, but gave up when he noticed this discrepancy

**Comment by George-VB** [comment]
Is it documented on the wiki (with pictures like nielsmh's)?

**Comment by planetmaker** [comment]
Extensively and for years and under a clear title: https://wiki.openttd.org/Catchment_area

**Comment by J0anJosep** [comment]
> Can drawing of the catchment area be improved in such a way, that allows to see the real area of the station? May be some button "show catchment area"?

> i believe someone tried that on the forum once, but gave up when he noticed this discrepancy

There are several patches and patchpacks that have a "Show catchment are" feature.
About the discrepancy about in/out areas, I wrote a patch with a new setting to make them equal long ago.
