### ISSUE TITLE
File failed to decompress / OpenTTD crashes when downloading CZTR_Truck_set-1.0.0.tar

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#7211]
## Version of OpenTTD
1.9.0-beta2

## Expected result
The file internally named "CZTR_Truck_set-1.0.0.tar" and displayed as "CZTR Truck set 1.0.0" from the OpenTTD content server downloads and decompresses successfully with no crashes.

## Actual results
1. CZTR_Truck_set-1.0.0.tar fails to decompress after downloading. This is coupled with a message saying that the "C:\$MFT" directory is corrupt and unreadable and telling the user to run Chkdsk on the system partition.
2. Downloading CZTR_Truck_set-1.0.0.tar crashes OpenTTD with [this crash report.](https://github.com/OpenTTD/OpenTTD/files/2848444/OpenTTD.zip)

## Steps to reproduce (OpenTTD with GUI)
1. Start OpenTTD normally.
2. Click on "Check Online Content".
3. Wait while OpenTTD gathers online content info from the server.
4. Search for "CZTR".
5. Select the "CZTR Truck set 1.0.0" item for downloading (approx. 20 MiB)
6. Click "Download" and wait.
7. Ethier OpenTTD crashes (actual), the download fails to decompress (actual), or the download completes without problem (expected).

## Steps to reproduce (OpenTTD dedicated server)
1. Open the command prompt.
2. Navigate to your OpenTTD 1.9.0-beta2 install directory.
3. Run "openttd -D ::1" to start the OpenTTD dedicated server.
4. Wait until game starts.
5. Execute command "content update" and wait.
6. Execute command "content state cztr".
7. Execute command "content select [id]", where [id] is the ID of the "CZTR Truck set 1.0.0" item on the OpenTTD content server.
8. Execute command "content download" and wait.
9. Ethier OpenTTD crashes (actual), the download fails to decompress (actual), or the download completes without problem (expected).

**Comment by glx22** [comment]
I followed the steps, no crash for me.

You may have an issue with your drive.

**Comment by PeterN** [comment]
Yes, works fine for me. The fact you get a message saying you need to run ChkDsk is absolutely nothing that could be caused by OpenTTD, so either a hardware issue or malware.

**Comment by James103** [comment]
I was finally able to get the CZTR_Truck_set-1.0.0.tar to download, decompress, and be recognized without any crashes. Closing for now...
