### ISSUE TITLE
Is there any way to crawling a new version?

### ISSUE THREAD

**Issue by telk5093** [OpenTTD/OpenTTD#7221]
Sorry that it is not for game issue itself.

~~Since new website is launched, [finger.openttd.org](finger.openttd.org) seems not to be updated.
I hope that it is also updated, too.~~

**+ Edit:**
I've noticed that OpenTTD is now using something new rather than finger.openttd.org,
so is there any way to crawling a new version information?

**Comment by telk5093** [comment]
Sorry, I found them on [here](https://openttd.ams3.digitaloceanspaces.com/openttd-nightlies/listing.txt)

**Comment by Eddi-z** [comment]
see https://github.com/OpenTTD/website/issues/48

**Comment by TrueBrain** [comment]
Sorry @telk5093 ; we don't really have a simple way to broadcast these changes. If you have suggestions so people using things like finger and devs like me can contact each other easily, I would very much welcome that.

Hope you figured out by now how to work with the new information. Feel free to participate in https://github.com/OpenTTD/website/issues/48 if you have suggestions / ideas / etc.

Tnx!
