### ISSUE TITLE
Terminal Start Network game not work for Connect : ./openttd -n xxx.xxx.xxx.xxx:3797  Game Crash and show the load windows with: Load new grf ....

### ISSUE THREAD

**Issue by mattimat47** [OpenTTD/OpenTTD#7222]

**Comment by nielsmh** [comment]
Please fill in the issue template properly.

By the limited description this sounds like it might be a duplicate of #6619.

**Comment by glx22** [comment]
Maybe duplicate of #7007 too, and fixed with #7103, so yes we at least need the version info

**Comment by mattimat47** [comment]
och Yea Sorry its the version 1.8.0  and its this issue https://github.com/OpenTTD/OpenTTD/issues/6619

**Comment by nielsmh** [comment]
Can you test with the newly release beta version of 1.9.0 if the issue is solved?

**Comment by mattimat47** [comment]
OK i have Compile the 1.9.0 beta2 and its run !! under Ubuntu 18 thx 
do you know when the new version will be released?
