### ISSUE TITLE
NPF: Ship: Assertion failure when ship encounters shore

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#7226]
## Version of OpenTTD
Trunk (since commit d814dd343410bb989162aa1daece20b60aa7a737)

## Expected result
No assert failures occur

## Actual result
Assertion: `Error: Assertion failed at line 1166 of /home/jgr/openttd/trunk/src/pathfinder/npf/npf.cpp: ftd.best_trackdir != INVALID_TRACKDIR` can be triggered by obstacles in the path of ships when using NPF pathfinder.
This assertion was added in d814dd343410bb989162aa1daece20b60aa7a737 (PR #7114)

## Steps to reproduce
See attached savegame. The issue seems to occur when the ship is travelling in a diagonal (with reference to the tile axes) direction and encounters a perpendicular shore slope.
[JGR Testing & Maintenance Ltd, 1945-09-12.sav.zip](https://github.com/OpenTTD/OpenTTD/files/2862859/JGR.Testing.Maintenance.Ltd.1945-09-12.sav.zip)

**Comment by PeterN** [comment]
Should be pretty simple to revert just that single hunk from d814dd3. I can prepare this later.

**Comment by J0anJosep** [comment]
I will look into it. NPF shouldn't be executed on that case. It seems a 90º turn problem. I will look into it this weekend. Reverting the previous changes is doable, but it would be better to modify the ShipController code and keep the asserts on NPF.
