### ISSUE TITLE
Waiting cargo show cargo that should be hidden

### ISSUE THREAD

**Issue by SylvainDevidal** [OpenTTD/OpenTTD#7259]
## Version of OpenTTD
Nightly build 20190219-master-g21d8636722

## Expected result
In the station list, I disabled passengers.
I should not see waiting passengers in this window.

## Actual result
Sometimes (it looks like it applies only to stations built _after_ the window was open and the filter set) I see passengers in the window.
You can see in the attached screenshot passengers waiting at Beaujolais and Troyes airports.

## Steps to reproduce
Open the station list.
CTRL + CLICK on the PS to hide passengers.
Build some stations accepting passengers and wait a while. Sometimes passengers appears.

![valence transport apr 9th 1931](https://user-images.githubusercontent.com/6975555/53207585-5a23b680-3634-11e9-8c25-7543ddbafda2.png)

[trucks.zip](https://github.com/OpenTTD/OpenTTD/files/2891625/trucks.zip)

**Comment by Eddi-z** [comment]
It's not meant to hide passengers from the displayed cargos, it just won't show stations that have _only_ passengers. if you select stations that have mail, it will also show the passengers on those stations

**Comment by SylvainDevidal** [comment]
You're right.
I just remembered that.
