### ISSUE TITLE
Programmable signals doesn't works

### ISSUE THREAD

**Issue by nirasa1957** [OpenTTD/OpenTTD#7263]
## Steps to reproduce - Programmable signals are constantly red. If I do not delete the signal, but only change the normal combined signal, it then works as programmable. Everything is OK and the signal works.
Game file: 
[https://www.dropbox.com/preview/public/OpenTTD/programmable-sign-bug.sav?role=personal](url)

**Comment by PeterN** [comment]
Please use this forum thread for JGR issues: https://www.tt-forums.net/viewtopic.php?f=33&t=73469
