### ISSUE TITLE
News font size is bugged if font size was changed for a multiple times

### ISSUE THREAD

**Issue by Nik-mmzd** [OpenTTD/OpenTTD#7266]
## Version of OpenTTD
Compiled from source, commit 00d28a500d9b2c32877871e0d2b917c8b28a82a6

## Expected result
News with "Normal size" font

## Actual result
News still using "Quad size" font instead of "Normal size"

## Steps to reproduce
Settings => Font Size
Set it to "Quad Size" and then back to "Normal Size"
News will be in "Quad Size" font instead of "Normal"
![image](https://user-images.githubusercontent.com/19509291/53286033-65ccc580-3779-11e9-9a42-ec329345959f.png)

**Comment by nielsmh** [comment]
I can reproduce this. It probably requires using vector fonts to trigger, not sure.
#7003 is the PR introducing this bug.

**Comment by Nik-mmzd** [comment]
If needed:
I'm using Hack monotype font
```
small_font = Hack, Bold
medium_font = Hack, Bold
large_font = Hack, Bold
mono_font = Hack
```

**Comment by nielsmh** [comment]
According to @LordAro the bug manifests differently if using bitmap fonts, then the news window is just offset on screen.

This bug probably isn't critical, it doesn't affect game logic, and can be worked around by a save, quit, reload cycle.

**Comment by LordAro** [comment]
![](https://i.imgur.com/8ykUAD4.png)

**Comment by PeterN** [comment]
I can't reproduce this, is it perhaps something that only occurs on Windows?

**Comment by Nik-mmzd** [comment]
@PeterN I'm using Linux 🤷‍♂️ 
And set up custom font using openttd.cfg

**Comment by PeterN** [comment]
I'm on Linux, and have set up the same fonts, and cannot reproduce. Hmm.
