### ISSUE TITLE
Fatal Application Failure

### ISSUE THREAD

**Issue by drsid** [OpenTTD/OpenTTD#7300]
*** OpenTTD Crash Report ***

Crash at: Thu Feb 28 19:44:14 2019
In game date: 2116-05-26 (52)

Crash reason:
 Exception: C0000005
 Location:  00007FF7A9311A2A
 Message:   <none>

OpenTTD version:
 Version:    1.8.0 (0)
 NewGRF ver: 18086d62
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: Apr  1 2018 13:23:25

Registers:
 RAX: 0000000000000000 RBX: 0000000000000100 RCX: 000000002568129B RDX: 0000000000000061
 RSI: 0000000026A300D0 RDI: 0000000025673D9B RBP: 00000000010FE030 RSP: 00000000010FDEC0
 R8:  0000000026A300D0 R9:  00000000010FDF78 R10: 000000000000A000 R11: 000000000000A007
 R12: 0000000025673B9A R13: 0000000000000061 R14: 00000000010FE360 R15: 00000000010FE880
 RIP: 00007FF7A9311A2A EFLAGS: 00010206

 Bytes at instruction pointer:
 0F B7 01 49 8B F9 49 8B D8 44 0F B6 D0 66 89 44 24 40 0F B6 44 24 41 66

Stack trace:
 010FE360 00000000 A9307BE9 00007FF7 00000061 00000000 00006100 00000000
 FFFFFFFF 00000000 A77D2B36 00007FFE 25673D9B 00000000 A9311B6F 00007FF7
 47504F53 00000000 00000100 00000000 25673F9C 00000000 0000C848 00000000
 010FE360 00000000 A930DFC8 00007FF7 010FE178 00000000 26A300D0 00000000
 000000D5 00000000 00000200 00000000 010FDF78 00000000 00000000 00000000
 00000160 00000000 00000061 00007FF7 00000000 00000000 44264000 00000000
 0000000D 00000000 FFFFFFFE FFFFFFFF 00000000 00000000 AAB30101 00000000
 000001D0 00000200 FFFFFFFE 00000200 010FDFE0 00000000 286A9A70 00000000
 00000200 00000000 00000000 00000000 00000000 00000000 286A9A70 00000000
 00000000 00000000 00000200 00000000 286A9A70 00000000 00000000 00000000
 00000160 00000000 A92DCFE1 00007FF7 00000004 00000000 00000200 00000000
 26A300D0 00000000 47504F53 00000000 010FE178 00000000 25673B9A 00000000
 0000CC4A 00000000 A9255D0E 00007FF7 A9BEA6B0 00007FF7 00DB1980 00000000
 00000000 00000000 00DB0000 00000000 0000011A 00000000 286A9A70 00000000
 03565020 00000000 00000010 00000000 00000000 00000000 00DB54C0 00000000
 00DB0D20 00000000 00000008 00007FF7 00000030 00000000 00000005 00000000
 035CA800 00000000 00000030 00000000 0000001C 00000000 00000000 00000000
 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
 00000000 00000000 010FE360 00000000 47504F53 00000000 010FE4A0 00000000
 010FE360 00000000 00000004 00000000 010FE1A0 00000000 A9308253 00007FF7
 00000102 00000000 010FE178 00000000 010FE880 00000000 00000061 00000000
 010FE880 00000000 010FE4A0 00000000 FFFFFFFE FFFFFFFF 26A300D0 00000000
 47504F53 FFFFFFFF 010FE210 00000000 25673B9A 00000000 0000CC4A 00000000
 010FE219 00000000 A9304BE6 00007FF7 010FE4A0 00000000 00000009 00000000

Operating system:
 Name:     Windows
 Release:  6.2.9200 ()
 Compiler: MSVC 1600

Configuration:
 Blitter:      32bpp-anim
 Graphics set: OpenGFX (5580)
 Language:     D:\Games\OpenTTD\lang\russian.lng
 Music driver: win32
 Music set:    OpenMSX (96)
 Network:      no
 Sound driver: win32
 Sound set:    OpenSFX (87)
 Video driver: win32

Fonts:
 Small:  Arial
 Medium: Arial
 Large:  Arial
 Mono:   sprite

AI Configuration (local: 0):
  0: Human

Libraries:
 FreeType:   2.4.11
 ICU i18n:   51.2
 ICU lx:     51.2
 LZMA:       5.0.4
 LZO:        2.06
 PNG:        1.5.14
 Zlib:       1.2.7

Module information:
 D:\Games\OpenTTD\openttd.exe handle: 00007FF7A8F80000 size: 13549568 crc: DD9F7941 date: 2018-04-01 13:27:46
 C:\WINDOWS\SYSTEM32\ntdll.dll handle: 00007FFEAAB20000 size: 1946328 crc: C407C580 date: 2018-06-08 09:29:38
 C:\WINDOWS\System32\KERNEL32.DLL handle: 00007FFEAA6F0000 size: 720632 crc: E36109EF date: 2018-04-11 23:34:40
 C:\WINDOWS\System32\KERNELBASE.dll handle: 00007FFEA77A0000 size: 2570712 crc: DAC36F9D date: 2018-06-08 09:29:25
 C:\WINDOWS\System32\WS2_32.dll handle: 00007FFEAA570000 size: 430408 crc: BCF23F7A date: 2018-04-11 23:34:22
 C:\WINDOWS\System32\RPCRT4.dll handle: 00007FFEA82A0000 size: 1190152 crc: 1A405132 date: 2018-06-08 09:29:15
 C:\WINDOWS\SYSTEM32\WINMM.dll handle: 00007FFEA5150000 size: 123584 crc: 94826B12 date: 2018-04-11 23:34:04
 C:\WINDOWS\System32\IMM32.dll handle: 00007FFEAA2B0000 size: 173648 crc: C00419EB date: 2018-04-11 23:34:24
 C:\WINDOWS\System32\USER32.dll handle: 00007FFEAA960000 size: 1639448 crc: A440790A date: 2018-04-11 23:34:14
 C:\WINDOWS\System32\win32u.dll handle: 00007FFEA7700000 size: 124048 crc: FACB4E5F date: 2018-04-11 23:34:12
 C:\WINDOWS\SYSTEM32\winmmbase.dll handle: 00007FFEA5120000 size: 162240 crc: 20283370 date: 2018-04-11 23:34:04
 C:\WINDOWS\System32\GDI32.dll handle: 00007FFEA9F50000 size: 155040 crc: C6B0F3EA date: 2018-04-11 23:34:08
 C:\WINDOWS\System32\msvcrt.dll handle: 00007FFEA8200000 size: 636936 crc: D6A3C60E date: 2018-04-11 23:34:20
 C:\WINDOWS\System32\gdi32full.dll handle: 00007FFEA7AC0000 size: 1634808 crc: 111F1116 date: 2018-06-08 19:02:19
 C:\WINDOWS\System32\cfgmgr32.dll handle: 00007FFEA6FA0000 size: 286744 crc: B7105488 date: 2018-04-11 23:34:22
 C:\WINDOWS\System32\msvcp_win.dll handle: 00007FFEA7A20000 size: 642088 crc: E7CD7CF9 date: 2018-04-11 23:34:22
 C:\WINDOWS\System32\ucrtbase.dll handle: 00007FFEA7CC0000 size: 1018616 crc: C6C134F0 date: 2018-04-11 23:34:22
 C:\WINDOWS\System32\ADVAPI32.dll handle: 00007FFEAA640000 size: 645208 crc: 88E62B78 date: 2018-04-11 23:34:44
 C:\WINDOWS\System32\sechost.dll handle: 00007FFEA8430000 size: 368352 crc: D55ED681 date: 2018-04-11 23:34:22
 C:\WINDOWS\System32\SHELL32.dll handle: 00007FFEA8490000 size: 21389360 crc: 4691D7E6 date: 2018-05-20 19:43:42
 C:\WINDOWS\System32\shcore.dll handle: 00007FFEA98D0000 size: 678840 crc: 1B1EF8E3 date: 2018-06-08 09:29:20
 C:\WINDOWS\System32\combase.dll handle: 00007FFEA9F80000 size: 3296896 crc: 0B69D280 date: 2018-06-08 09:30:08
 C:\WINDOWS\System32\bcryptPrimitives.dll handle: 00007FFEA7720000 size: 494400 crc: F7DA43B9 date: 2018-04-11 23:34:22
 C:\WINDOWS\System32\windows.storage.dll handle: 00007FFEA6FF0000 size: 7436632 crc: EF872850 date: 2018-05-20 11:52:46
 C:\WINDOWS\System32\shlwapi.dll handle: 00007FFEAA510000 size: 326496 crc: 9E999772 date: 2018-04-11 23:34:33
 C:\WINDOWS\System32\kernel.appcore.dll handle: 00007FFEA6E30000 size: 57960 crc: 36F6CB72 date: 2018-06-08 09:29:20
 C:\WINDOWS\System32\profapi.dll handle: 00007FFEA6E50000 size: 115800 crc: F2EDFE5C date: 2018-04-11 23:34:22
 C:\WINDOWS\System32\powrprof.dll handle: 00007FFEA6E70000 size: 300208 crc: 615A899E date: 2018-04-11 23:34:22
 C:\WINDOWS\System32\FLTLIB.DLL handle: 00007FFEA6EE0000 size: 31584 crc: F9E8EFD2 date: 2018-04-11 23:34:22
 C:\WINDOWS\system32\uxtheme.dll handle: 00007FFEA5330000 size: 599040 crc: 688AC957 date: 2018-04-11 23:34:36
 C:\WINDOWS\System32\MSCTF.dll handle: 00007FFEAA2E0000 size: 1523752 crc: 6FF09421 date: 2018-04-11 23:34:23
 C:\WINDOWS\System32\OLEAUT32.dll handle: 00007FFEA7FB0000 size: 788216 crc: EB44C960 date: 2018-05-14 10:06:02
 D:\Program Files (x86)\Yandex\Punto Switcher\PSHook64.dll handle: 00007FFE75850000 size: 145768 crc: 97A98BBD date: 2017-03-10 22:49:48
 C:\WINDOWS\System32\imagehlp.dll handle: 00007FFEA9F30000 size: 105456 crc: CBDBF1AA date: 2018-04-11 23:34:22
 C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL handle: 00007FFEA6880000 size: 31648 crc: 489701F2 date: 2018-04-11 23:34:20
 C:\WINDOWS\system32\dwmapi.dll handle: 00007FFEA55C0000 size: 146840 crc: 5A168920 date: 2018-04-11 23:34:20
 C:\WINDOWS\SYSTEM32\TextInputFramework.dll handle: 00007FFE96460000 size: 616800 crc: 6CE95817 date: 2018-04-11 23:34:08
 C:\WINDOWS\SYSTEM32\CoreUIComponents.dll handle: 00007FFEA2280000 size: 3283408 crc: BAF539AB date: 2018-06-08 09:29:15
 C:\WINDOWS\SYSTEM32\CoreMessaging.dll handle: 00007FFEA4BD0000 size: 885880 crc: 17B32F3C date: 2018-06-08 09:29:15
 C:\WINDOWS\SYSTEM32\ntmarta.dll handle: 00007FFEA5F20000 size: 187576 crc: 751ABC3F date: 2018-04-11 23:34:23
 C:\WINDOWS\SYSTEM32\wintypes.dll handle: 00007FFEA2130000 size: 1363632 crc: DBE17A9C date: 2018-06-08 09:30:06
 C:\WINDOWS\system32\mswsock.dll handle: 00007FFEA66B0000 size: 401968 crc: 76C6C00A date: 2018-04-11 23:34:22
 C:\WINDOWS\SYSTEM32\MMDevAPI.DLL handle: 00007FFEA09C0000 size: 469576 crc: D3E68B51 date: 2018-04-11 23:34:02
 C:\WINDOWS\SYSTEM32\DEVOBJ.dll handle: 00007FFEA6C40000 size: 152440 crc: B6F9124E date: 2018-04-11 23:34:22
 C:\WINDOWS\SYSTEM32\PROPSYS.dll handle: 00007FFEA36B0000 size: 1792808 crc: D78166E2 date: 2018-06-08 09:29:34
 C:\WINDOWS\SYSTEM32\wdmaud.drv handle: 00007FFE76B70000 size: 253952 crc: 294BD9E8 date: 2018-04-11 23:34:04
 C:\WINDOWS\SYSTEM32\AVRT.dll handle: 00007FFEA2770000 size: 30056 crc: 1F1BBFD7 date: 2018-04-11 23:34:04
 C:\WINDOWS\SYSTEM32\ksuser.dll handle: 00007FFE98E40000 size: 23360 crc: DA1D21C1 date: 2018-04-11 23:34:04
 C:\WINDOWS\SYSTEM32\AUDIOSES.DLL handle: 00007FFE8FE10000 size: 1209800 crc: 17A40B7A date: 2018-06-08 09:29:33
 C:\WINDOWS\SYSTEM32\msacm32.drv handle: 00007FFE98670000 size: 29184 crc: 43AA51E1 date: 2018-04-11 23:34:02
 C:\WINDOWS\SYSTEM32\MSACM32.dll handle: 00007FFE76DA0000 size: 106480 crc: 54E5FD19 date: 2018-04-11 23:34:04
 C:\WINDOWS\SYSTEM32\midimap.dll handle: 00007FFE98330000 size: 25088 crc: 3F472519 date: 2018-04-11 23:34:02
 C:\WINDOWS\System32\clbcatq.dll handle: 00007FFEAA470000 size: 635368 crc: 219EFEA4 date: 2018-04-11 23:34:20
 C:\Windows\System32\Windows.UI.dll handle: 00007FFE8E9B0000 size: 1128616 crc: 62A15344 date: 2018-04-11 23:34:39
 C:\Windows\System32\InputHost.dll handle: 00007FFE948A0000 size: 491744 crc: BEAA3FC5 date: 2018-04-11 23:34:12
 C:\WINDOWS\SYSTEM32\DNSAPI.dll handle: 00007FFEA6470000 size: 766608 crc: 2CFBA828 date: 2018-04-11 23:34:22
 C:\WINDOWS\System32\NSI.dll handle: 00007FFEAA950000 size: 24888 crc: ED39864C date: 2018-04-11 23:34:22
 C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL handle: 00007FFEA6430000 size: 219616 crc: 8E8EB6FC date: 2018-04-11 23:34:23
 C:\WINDOWS\System32\fwpuclnt.dll handle: 00007FFEA08B0000 size: 446976 crc: 11C9A474 date: 2018-04-11 23:34:12
 C:\WINDOWS\SYSTEM32\bcrypt.dll handle: 00007FFEA6990000 size: 137568 crc: CBD588A8 date: 2018-06-08 09:30:03
 C:\Windows\System32\rasadhlp.dll handle: 00007FFEA0680000 size: 16896 crc: C5D4D052 date: 2018-04-11 23:34:33
 C:\WINDOWS\System32\ole32.dll handle: 00007FFEA9DD0000 size: 1375544 crc: BBABDC4A date: 2018-04-11 23:34:19
 C:\WINDOWS\SYSTEM32\mciseq.dll handle: 00007FFEA4E60000 size: 30208 crc: CAF44370 date: 2018-04-11 23:34:04
 C:\WINDOWS\System32\psapi.dll handle: 00007FFEA8080000 size: 18712 crc: AA3B87EF date: 2018-04-11 23:34:20

---- gamelog start ----
Tick 11496: game loaded
Revision text changed to 1.3.0, savegame version 180, not modified, _openttd_newgrf_version = 0x130061eb
New game mode: 1 landscape: 0
Tick 11496: game loaded
Revision text changed to 1.8.0, savegame version 197, not modified, _openttd_newgrf_version = 0x18086d62
New game mode: 0 landscape: 0
---- gamelog end ----

*** End of OpenTTD Crash Report ***

Decoded stack trace:
[00] openttd              0x00007FF7A9311A2A
[01] openttd              0x00007FF7A9311B6F
[02] openttd              0x00007FF7A930DFC8
[03] openttd              0x00007FF7A9308253
[04] openttd              0x00007FF7A9304BE6
[05] openttd              0x00007FF7A9308343
[06] openttd              0x00007FF7A92FE2D8
[07] openttd              0x00007FF7A92FFC5D
[08] openttd              0x00007FF7A92FB1DB
[09] openttd              0x00007FF7A92F68CF
[10] openttd              0x00007FF7A92CFE97
[11] openttd              0x00007FF7A8FB0BA0
[12] openttd              0x00007FF7A8FAB7F9
[13] openttd              0x00007FF7A9040F31
[14] openttd              0x00007FF7A9041A2D
[15] openttd              0x00007FF7A9006D95
 <infinite loop>

*** End of additional info ***

**Comment by nielsmh** [comment]
Did this happen on the title screen, or during a game?

Also, have you had more than one crash, or is this the first?

**Comment by Eddi-z** [comment]
Could you update to 1.9.0-beta3, please? 1.8.0 has a known issue with displaying some languages.

**Comment by nielsmh** [comment]
Confirmed this is a crash in ICU code.

Offset 7FF7A9311A2A (top of stack) from 7FF7A8F80000 (load address) is 391A2A, and that offset corresponds to `icu_51::AnchorTable::getAnchor` in 1.8.0 Win64.

The current beta and next release of OpenTTD no longer depends on ICU on Windows, so this crash is already fixed.

The only known "workaround" in 1.8.0 is to use sprite fonts.
