### ISSUE TITLE
AI Sign List slowdowns the more signs there are

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7303]
## Version of OpenTTD
1.9.0-beta3
## Expected result
no stalls
## Actual result
stalls each time a sign is added or removed from the sign list
## Steps to reproduce
Have an AI that masses add and removal of signs, like AIAI with all debug signs options.
Open Sign list.
Experience it slowing down the more signs it creates.

Savegame has about 61700 signs created by AIAI.
[Sarnton Transport, 1962-08-19.zip](https://github.com/OpenTTD/OpenTTD/files/2920590/Sarnton.Transport.1962-08-19.zip)

**Comment by SamuXarick** [comment]
![sarnton transport 1961-08-26](https://user-images.githubusercontent.com/43006711/53657821-2b6a9900-3c4f-11e9-957e-31946bec1464.png)

**Comment by James103** [comment]
Based on the above image, it takes about 58 microseconds (barring all other graphics routines) to render a sign in the sign list. Also, it appears the simulation rate is capped at the graphics frame rate if the game is not in fast forward mode.
