### ISSUE TITLE
Performance in DOS is terrible

### ISSUE THREAD

**Issue by nielsmh** [OpenTTD/OpenTTD#7332]
## Version of OpenTTD
#7331 test build
DJGPP (DOS) build running in Windows 95 DOS box on a Via EPIA-VE5000 board with 128 MB RAM installed. (No VM or emulation.)

openttd.cfg:
```
blitter = 8bpp-optimized
support8bpp = hardware
resolution = 640,480
```

## Expected result
Playable framerates.

## Actual result
![image](https://camo.githubusercontent.com/87d198778a65c6fb9841ff13dbfeaef7e948baaf/68747470733a2f2f3078302e73742f7a6f56552e6a7067)
Framerate is very low and game is not really playable, despite no individual performance measurement being bad. Something slow is happening between GameLoop and the video output.

## Steps to reproduce
1. Obtain some old hardware
2. Install a long out of support operating system
3. Figure out a way to transfer files from the internet to the system
4. Run the game

**Comment by nielsmh** [comment]
A possible suspect for the cause might be the timing routine, except then fast-forward mode should still work (which it doesn't):
https://github.com/OpenTTD/OpenTTD/blob/f52e5a4d6191a63b69a6e35950a8bf1a9d8e9a12/src/video/allegro_v.cpp#L464-L479

**Comment by Gymnasiast** [comment]
Don't take this the wrong way (I don't want to tell you how to develop OpenTTD), but why does OpenTTD still support operating systems this old? Isn't it a noticeable burden on development? (At OpenRCT2, we even dropped XP because of compiler support and missing APIs, which might be the other extreme.)

**Comment by TrueBrain** [comment]
@Gymnasiast: in simple terms, because we can :D But .. we are planning on dropping it for other reasons ;)
