### ISSUE TITLE
FindStationsAroundTiles with use_nearby=true returns no results for industry tiles

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#7372]
## Version of OpenTTD
Since 8b1b3fd0f91fd30d09d3acaa65bd9a7d23d966cc

## Expected result
`void FindStationsAroundTiles(const TileArea &location, StationList *stations, bool use_nearby)` should fill *stations

## Actual result
When use_nearby is true and `IsTileType(location.tile, MP_INDUSTRY)`.
`stations = &Industry::GetByTile(location.tile)->stations_near;` changes the value of the stations parameter pointer.
This does not write to *stations, and the change of pointer is not visible to the caller.

Presumably it should be `*stations = Industry::GetByTile(location.tile)->stations_near;`

**Comment by PeterN** [comment]
Weird, I remember seeing this but must have forgotten :-(

**Comment by PeterN** [comment]
Now that I look, the only affected caller of this is newgrf houses querying cargo acceptance history of nearby stations with var 0x64, and only if they provide an offset which points to an industry tile.

I'm not sure what the purpose of this check (with an offset) is, and I suspect providing the result of the industry's nearby stations is incorrect at this point.

**Comment by PeterN** [comment]
Okay, so it's for multi-tile buildings to check the for other possible stations of their other tiles. Basically this bug is a non-issue as checking an industry tile wouldn't produce useful results anyway.
