### ISSUE TITLE
Day length multiplayer not available in options

### ISSUE THREAD

**Issue by perkel666** [OpenTTD/OpenTTD#7377]
Day length is available in code to modify but it is not available in options to change.
This causes people to release patches which are quickly outdated and cause confusion.

**Quick fix:** Add as an advanced/extra option with disclaimer that economy is not scaled to day length multiplayer changes.

**Long therm goal/fix:** Add this as an option and adjust economy scripts to properly scale of game day length with economy. FE: Increased day length means increased daily maintenance cost, loans cost etc.

**Reasoning**
This will give player an ability to play in historic periods for an extended amount of time.
Should be considered as optional new feature extending players fun.
In current OpenTTD historical era fly past and you barely have any time to play with older hardware and build any reasonable network with it. 

**Question**
Should Quick/Long fix be split into own separate issues or should be bundled here.

**Comment by TrueBrain** [comment]
Thank you for your suggestion.

Daylength patch is a feature that has been around for years, and many times over debated if it should be include in OpenTTD itself, or remain in patchpacks only. Sadly, the nature of such patch breaks many mechanics in the game. Nobody so far has taken ownership of these problems, and as such it is not stable enough to include such patch in OpenTTD. In result, the conclusion is, it is indeed better to have it in patchpacks, which by nature are more cutting edge, and breaking mechanics there is perfectly fine. Introducing it in OpenTTD, needs far more work (and nobody has stepped up to put that work in it).

In result, we don't see this patch landing in OpenTTD in, say, the next year. To keep the issue tracker clean with actionable items,  I am going to close this suggestion for now. Of course if someone did address all the issues, we welcome a Pull Request debating the implementation. If you want to tackle this issue, I do suggest to step by on IRC to talk it over first, to get an idea of all the mechanics that break with such patch (many examples can be found on the forums too).

Thank you again!

**Comment by perkel666** [comment]
Then should i add this to projects section ? I saw there "ideas" project but it was closed.
If such a thing will not exist as long therm goal then no one will pick it up in the end as no one will be aware that some want such feature.

**Comment by TrueBrain** [comment]
I think you are underestimating our community here :) That people want such features is well known ;) But that of course is not really your point here :D

For now we [decided](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) that the forums is the best place for such long term ideas and requests, as GitHub is not really facilitating this. A Project in GitHub also needs an open issue, and having tens (if not hundreds) of ideas open in the issue tracker means the real issues are hiding between the feature requests. This is sadly a direct result of how GitHub considers issues and feature request on identical level.

We could consider other platforms for long-term feature requests, but so far nobody has stepped up and organize anything for that. If you are up to that, and have some good ideas, we are all ears!

**Comment by Alberth289346** [comment]
Mostly the forum acts as discussion platform for long term ideas and projects.

I don't think the idea will die, there are patchpacks that have it, and the feature is used. It just needs soneone that has the drive to work out all the problems with the current implementation, which btw are not always clear conceptually either.
