### ISSUE TITLE
Problem with stations and nearby industry

### ISSUE THREAD

**Issue by gh658804** [OpenTTD/OpenTTD#7381]
## Version of OpenTTD
1.8.0

## Problem description
I have a game with two stations in it, which are 12 squares apart. Between the two stations (nearest to one of them) is an Ore Mine (the cover area of the other one does not reach it). Near the second station is a Steel Mill.

I had placed a train loading Ore from the 1st station and unloading it at the 2nd station. So far so good. Everything run smoothly until i added an International Airport near the 2nd station (not as a new station but as an addition to the existing one). In the place i added it, its cover area still did not include the Ore Mine, however for some unknown reason, the 2nd station started accumulating ore from the Ore Mine as if it was very near to it and its cover area included it.

The result is that now both stations receive Ore from the Ore Mine, so now the train does a pointless trip from one station to the other, without loading or unloading ore (as it is already fully loaded).

The attached zip contains two savegames (the older one without the airport, the newer one after the addition of the airport).

The 1st station is named "Flefingford Mines" and the 2nd one is named "Flefingford Woods". The Ore-train is "Train 1"

**Comment by gh658804** [comment]
Savegame attach

**Comment by Eddi-z** [comment]
Try "Unload and No Loading" orders

**Comment by gh658804** [comment]
[010.zip](https://github.com/OpenTTD/OpenTTD/files/2975513/010.zip)

**Comment by gh658804** [comment]
> Try "Unload and No Loading" orders

I thought of that but the 2nd station will have a negative grade for me as far as Ore is concerned. Also, apart from that, i don't think this behaviour is correct.

**Comment by Eddi-z** [comment]
The negative rating will time out eventually, if no ore is picked up for a while

**Comment by Eddi-z** [comment]
The behavior may be undesirable, but it is technically correct.

* Train loads ore at A (because mine in range)
* Train unloads ore at B (because steel mill in range)
* Train loads ore at B (because mine in range)
* Train cannot unload at A (because no steel mill in range)
* Train cannot unload at B (because cargo came from here)

**Comment by PeterN** [comment]
This is how catchment areas work in 1.8.0 (and 1.9.0)

Fixed by #7235.

**Comment by gh658804** [comment]
@Eddi-z I was curious and just tried your suggestion. Unfortunately the unloaded ore was just added in the amount of the already-accumulated Ore in the 2nd station, without it being absorbed by the Steel-Mill.

**Comment by Eddi-z** [comment]
Yes, the load already on the train will just rot there. but future trips will work correctly now

**Comment by gh658804** [comment]
Sorry, scratch my last. It was probably used by the Steel Mill. The 2nd station though is still accumulating Ore from the Ore mine...

**Comment by gh658804** [comment]
> The behavior may be undesirable, but it is technically correct.
> 
> * Train loads ore at A (because mine in range)
> * Train unloads ore at B (because steel mill in range)
**> * Train loads ore at B (because mine in range)**

Here is the problem. Mine is NOT in range of B. if i try to create a new train station or a new airport over the existing ones, i see that the Ore min will NOT be in its range.

> * Train cannot unload at A (because no steel mill in range)
> * Train cannot unload at B (because cargo came from here)

**Comment by Eddi-z** [comment]
> Here is the problem. Mine is NOT in range of B. if i try to create a new train station or a new airport over the existing ones, i see that the Ore min will NOT be in its range.

that part is already fixed with the feature mentioned by @PeterN, it will likely be in 1.10

**Comment by PeterN** [comment]
Basically when you add the airport to the train station, the catchment radius of the airport also applies to the train station tiles. So although the airport isn't within range, and the train station isn't within range, the two combined together are in range.

**Comment by gh658804** [comment]
> Basically when you add the airport to the train station, the catchment radius of the airport also applies to the train station tiles. So although the airport isn't within range, and the train station isn't within range, the two combined together are in range.

Ah. OK, now i think i get it. So, in that case, the only way to prevent Ore from accumulating in the 2nd station would have been to instruct Train 1 to NOT load anything from the 2nd station before creating the Airport, right?

If that is the case then there should be a way to "tell" the station not to accumulate resources of a certain type (i.e. Ore) regardless of train orders. Mine is an easy case because the game is rather small but for bigger and more complicated games, "telling" the station what to accept would be more clear and easy to handle.

**Comment by PeterN** [comment]
This is now verging in to feature-request territory, which is better served by our [suggestions](https://www.tt-forums.net/viewforum.php?f=32) forum.

Feel free to re-open if you disagree.

**Comment by andythenorth** [comment]
Thanks for contributing!

**Comment by gh658804** [comment]
OK, i have transferred the feature-request part here: https://www.tt-forums.net/viewtopic.php?f=32&t=84987

Thanks all for everything.
