### ISSUE TITLE
Funding a new primary industry fails on top of trees

### ISSUE THREAD

**Issue by gbomfim** [OpenTTD/OpenTTD#7400]
1.9.0-RC1

Fund a new industry.

Always shows "Can't construct this industry type here... site unsuitable"

Using a savegame from 1.8, (re-saved in 1.9.0-RC1) try to fund a new industry. This not happen when using a new fresh game.

**Comment by TrueBrain** [comment]
Thank you for your bug report!

Would you mind to attach this savegame? As you mention already, a fresh game works. So without that savegame, this is hard to reproduce for us, and see what is going on exactly :)

Tnx!

**Comment by gbomfim** [comment]
Sure!
Here.
[Teestable Park Transport, 18 Jul 2019.zip](https://github.com/OpenTTD/OpenTTD/files/2999697/Teestable.Park.Transport.18.Jul.2019.zip)

**Comment by nielsmh** [comment]
Can you provide some help finding these missing NewGRF files as well?

![image](https://user-images.githubusercontent.com/1062071/54871250-7476be80-4db1-11e9-9241-2751041bccfb.png)

**Comment by nielsmh** [comment]
Okay found the files.

[eGRVTS 1.0](https://www.tt-forums.net/viewtopic.php?p=1048813#p1048813) (compatible, not exact match)
[newstats.grf](https://www.tt-forums.net/viewtopic.php?f=67&t=63651&hilit=newstats.grf)
[indstatr.grf](http://bundles.openttdcoop.org/isr/nightlies/v5574-186/)

**Comment by nielsmh** [comment]
Yep, this reproduces. All old savegames loaded cannot fund new industries, _on trees_! If you fund the industry on clear land it works, or if you clear the terrain of trees before.

**Comment by gbomfim** [comment]
Okay, thank you!

**Comment by nielsmh** [comment]
The bug was introduced in PR #7309
