### ISSUE TITLE
Signs made by AIs do not show up at the creation time

### ISSUE THREAD

**Issue by stormcone** [OpenTTD/OpenTTD#7410]
## Version of OpenTTD
20190324-master-g37b9fdc0c1

## Expected result
The signs are visible

## Actual result
The signs are invisible

## Steps to reproduce
- Enable the AI called "AIAI". (I chosed AIAI because it is always put it's HQ into the biggest town on the map, and puts some signs immediately there about itself so it is easier to observe the problem.)
- Start a new game
- Make sure the "Competitor signs and names displayed" option is checked on and the transparency settings is configured to show them
- Open the signs list window. (It is empty)
- Click on the biggest town in the town directory, so the main viewport will be scrolled there
- Wait until the AI starts. It's HQ will be placed in the town with some signs, but they are not visible
- Check the signs list window. (It has got some entries now)
- Save the game then load it and the signs will be visible

(You can configure the AI to show the path finding steps in which case wait until it builds its first route and check the path on the screen. The signs list window will contain many more items but you can not see them on the map. Again save and load the game and they will be visible.)

**Comment by nielsmh** [comment]
Sounds like another k-d tree bug.
