### ISSUE TITLE
Deleted signs do not always disappear from the screen

### ISSUE THREAD

**Issue by stormcone** [OpenTTD/OpenTTD#7414]
The signs still have some issues.

## Version of OpenTTD
20190325-master-g698241e16e

## Expected result
The signs always disappears from the screen after they are deleted.

## Actual result
Varied: They mostly stay on screen, in a few a cases they disappears. If I move the map back and forth they starting to disappear partially until they fully disappear. They disappear immediately if I change the zoom level.

## Steps to reproduce
- Place some signs here and there
- Start to delete them
- Check whether you can still see them

**Comment by LordAro** [comment]
Confirmed, visual glitch - the viewport is not invalidated when sign is removed
