### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by planetmaker** [OpenTTD/OpenTTD#7425]
## Version of OpenTTD
1.8.0
## Expected result
no crash
## Actual result
crash
## Steps to reproduce
[crash.zip](https://github.com/OpenTTD/OpenTTD/files/3012005/crash.zip)

unknown. received report w/o further info via e-mail to info@
[crash.log](https://github.com/OpenTTD/OpenTTD/files/3011994/crash.log)
![crash](https://user-images.githubusercontent.com/3167964/55057527-be89c980-5069-11e9-81bd-d760d3ee253b.png)

**Comment by PeterN** [comment]
Judging by the text, it's probably the usual ICU problem.

**Comment by LordAro** [comment]
1.8, Hebrew & Windows? Yeah, got to be ICU
Closedalreadyfixed
