### ISSUE TITLE
AI Airports: the "out of range" indexes are marked as available, and can even be built.

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7433]
## Version of OpenTTD
1.9.0-RC2
## Expected result
AIs should only build available airport types.
## Actual result
the "out of range" indexes are marked as available, and can even be built.
## Steps to reproduce
Create an AI with this:
```
	for (local type = 0; type < 9999; type++) {
		if (AIAirport.IsValidAirportType(type)) {
			local w = AIAirport.GetAirportWidth(type);
			local h = AIAirport.GetAirportHeight(type);
			local r = AIAirport.GetAirportCoverageRadius(type);
			local c = AIAirport.GetMaintenanceCostFactor(type);
			local p = AIAirport.GetPrice(type);
			local i = AIAirport.IsAirportInformationAvailable(type);
			AILog.Info("Type: " + type + "; Width: " + w + "; Height: " + h + "; Radius: " + r + "; MaintenanceCostFactor: " + c + "; Price: " + p + "; IsAirportInformationAvailable: " + i);
		}
	}

```
Vanilla Airports:
![Unnamed, 2051-01-02](https://user-images.githubusercontent.com/43006711/55195354-365c0f00-51a4-11e9-9725-b99bec419b58.png)

OpenGFX+ Airports 0.5.0 Airports:
![Unnamed, 2051-01-31](https://user-images.githubusercontent.com/43006711/55195365-4116a400-51a4-11e9-931e-bd80091ddd91.png)

**Comment by glx22** [comment]
Following the steps, I can't reproduce in 1.9-RC2.
Without newgrf airports loaded, I get 8 lines, for types 1, 2, 3, 4, 5, 6, 7, 8.
With OpenGFX+ Airports 0.5.0 I get 15 lines, for types 1, 2, 3, 4, 7, 11, 12, 14, 15, 16, 17, 18, 19, 21, 23.
Same with 20190328-master-gacb09eb9a8.

**Comment by SamuXarick** [comment]
do you have airports never expire disabled?

**Comment by glx22** [comment]
Indeed it was disabled. When enabled I can reproduce.
