### ISSUE TITLE
Server reports CRR_AUTOCLEAN instead of CRR_MANUAL to admin port

### ISSUE THREAD

**Issue by ldpl** [OpenTTD/OpenTTD#7439]
1.9.0-RC2

When company is reset by console command (e.g. reset_company 1) server reports reason 1 (autoclean) instead of 0 (CRR_MANUAL). Because CmdCompanyCtrl expects reason to be in p2 but command is marked as CMD_CLIENT_ID so DoCommandP sets p2 as CLIENT_ID_SERVER when it's zero (and CRR_MANUAL is).

There is an old bug #4804 and as far as I can tell by code it wasn't actually fixed in r23031 (din't try runnig tho).

**Comment by EgyLynx** [comment]
Are that happened also 1.9.0?

**Comment by nielsmh** [comment]
@EgyLynx Yes this will also be happening in 1.9.0, and any other version. The bug was not fixed and is many years old.
