### ISSUE TITLE
Crash when trying to delete town in scenario editor

### ISSUE THREAD

**Issue by buttercup5** [OpenTTD/OpenTTD#7440]
## Version of OpenTTD
20190329-master-g1d14e31be3-windows-win64

## Expected result
Clicking on Delete in the town window when in the Scenario Editor should delete the town.

## Actual result
Clicking on Delete in the town window when in the Scenario Editor crashes the game.

## Steps to reproduce
1. Go into the scenario editor
2. Create a town
3. Try to delete the town
4. Crash game

**Comment by nielsmh** [comment]
Yep I can reproduce this. Seems to be an issue with viewport signs not being updated correctly in the k-d tree.

**Comment by JGRennison** [comment]
See: https://github.com/OpenTTD/OpenTTD/blob/master/src/town_cmd.cpp#L2874

`_viewport_sign_kdtree.Insert(ViewportSignKdtreeItem::MakeTown(t->index));` is called from within CmdDeleteTown, which looks wrong.

Changing Insert to Remove is sufficient to make the problem go away.
