### ISSUE TITLE
Text for some railway station NewGRFs is missing/invisible

### ISSUE THREAD

**Issue by buttercup5** [OpenTTD/OpenTTD#7447]
## Version of OpenTTD
Working in 20190319-master-g559d4e8335; broken in 20190324-master-g37b9fdc0c1. I don't have any of the builds in between those two to narrow it down further.

## Expected result
In the railway station construction window there should be a list of station tiles provided by the NewGRF(s), with accompanying preview picture.

## Actual result
The text for _some_ NewGRF station sets is not displayed, but clicking on the line where there should be text still shows a preview picture. Also, the name of the station tile isn't correct (it shows "Default station" instead). 

## Steps to reproduce
Load the savefile, open the railway station build window.

## Other notes
Hopefully the screenshots are enough to show what I'm talking about. Not sure how useful a savefile is but I included one anyway, and it has a load more station NewGRFs - some fine, some broken.

![20190319](https://user-images.githubusercontent.com/49045149/55280281-2a468d80-531b-11e9-8f5c-df2cfaa64291.png)
![20190324](https://user-images.githubusercontent.com/49045149/55280282-2a468d80-531b-11e9-98cd-a1e8930b8fd3.png)

[stationtest.zip](https://github.com/OpenTTD/OpenTTD/files/3025836/stationtest.zip)

**Comment by eekee** [comment]
Oh boy... It's really nice to see a bug fixed *before* I even spotted it, but... Will the fix be in 1.9.1?  Or was today's 1.9.0 April Fools?

**Comment by nielsmh** [comment]
I don't think there's been any decision regarding 1.9.1 yet, whether a release will be made or not. I guess it depends on any other bugs discovered in 1.9.0 release.

**Comment by eekee** [comment]
Oh.  Well, this bug alone is somewhat serious to me.  I can play cargo games because CHIPS and ISR aren't affected, but in pax games I like to build complex stations.  I use the Dutch station sets, all of which are affected -- 19 consecutive blank entries!  I might learn to remember a few, but it's hard.

I'm sorry I didn't load up a pax game when I returned to OTTD a few weeks ago.  If I had, you would have got this bug report a lot sooner.

**Comment by LordAro** [comment]
The fix for this *should* have gone into 1.9.0, but it got forgotten. It will be in 1.9.1, which I do currently expect to happen (maybe a month or so, maybe sooner)

**Comment by eekee** [comment]
Good to know.  Thanks!
