### ISSUE TITLE
Inverted scrolling with right click no longer working in 1.9.0

### ISSUE THREAD

**Issue by Beercules48** [OpenTTD/OpenTTD#7463]
## Version of OpenTTD
1.9.0, same in 20190402-master-g24fc25164a, released on 2019-04-02 18:02 UTC.
## Expected result
When scrolling with right mouse button clicked direction should be inverted when the corresponding option is activated, option is missing from settings in-game
## Actual result
Setting the option "reverse_scroll = true" in the openttd.cfg file has no effect
## Steps to reproduce
Any time I try to scroll the view holding RMB
[SAV_and_CFG_file.zip](https://github.com/OpenTTD/OpenTTD/files/3036513/SAV_and_CFG_file.zip)

**Comment by PeterN** [comment]
In the Settings window, ensure Advanced settings are shown (this is probably miscategorised)
The setting you want is "Viewport scroll behaviour".
The old setting "reverse_scroll" no longer exists.
