### ISSUE TITLE
Runs as windows admin from installer

### ISSUE THREAD

**Issue by brunom** [OpenTTD/OpenTTD#7470]
## Version of OpenTTD
1.9.0

## Expected result
openTTD should run without elevation

## Actual result
openTTD runs with admin right from the isntaller

## Steps to reproduce
Choose run in the last page of windows installer. Check process elevation woth process explorer.

**Comment by TrueBrain** [comment]
One would think NSIS solves this for you; seems that thinking is wrong.

We have two options here: either we remove the option, or we find out how to fix it properly. As we are switching to CMake / CPack to control NSIS, we have far less control over these things, so I am very tempted to just remove the option.
Possibly it would be good if we invest in one of the other installers .. but that is for another day.

Tnx for noticing this @brunom !
