### ISSUE TITLE
Request to make new game settings those of the last loaded game

### ISSUE THREAD

**Issue by eekee** [OpenTTD/OpenTTD#7473]
I hate that OpenTTD makes it hard to clone settings from one game to the next.  For new games, it remembers whatever experiment I tried weeks ago and forgot all about, instead of taking settings I like and use all the time.  There is a workaround for NewGRFs in the form of presets, but not for the bulk of the settings, of which there are far too many to go through when I want to start a new game.  The option to see only basic settings is of no use to me, some settings I use all the time and wouldn't play without are not visible at that level.

I propose a simple fix: When a game is loaded or changes are made in the game, make the new game settings the same.  Essentially, the new game settings no longer become a visible feature.  They are retained only for the case of creating a new game before any other game is loaded.  

Amongst other things, this would allow players to keep presets of new game settings; as many as they like!  It's not even "allow players to...", those presets would be retained automatically if the player saved the game.  What a convenience!

This is not exactly the same as https://github.com/OpenTTD/OpenTTD/issues/5244, but it may be considered to have the same result for less work.

**Comment by andythenorth** [comment]
Thanks for this.  For UI / behaviour changes like this, it's quite subjective what's better.  As the game is long-established, changing behaviour is as likely to annoy players as please them.  Therefore it's simple not to make certain changes like this one.

We try to keep the issue count low for the health of the project, so I'm closing this one.  Thanks!
