### ISSUE TITLE
Can't Refit Certain NewGRF Trains (undefined string error)

### ISSUE THREAD

**Issue by nocunoct** [OpenTTD/OpenTTD#7476]
## Version of OpenTTD
1.9.0
## Expected result
For the available liveries corresponding to each train to show up on the list to the right, and to be able to select between the options that used to be available in the previous version.
## Actual result
The game shows a single (undefined string) message instead of the list of available liveries; it is impossible to change liveries/refit the train.
![version 1-8-0](https://user-images.githubusercontent.com/49333379/55666121-304ed980-5807-11e9-999e-32d37c2a71fa.png)
![version 1-9-0](https://user-images.githubusercontent.com/49333379/55666123-32189d00-5807-11e9-95c4-33ee8eb0e177.png)
## Steps to reproduce
Using the Japan Train Set v. 3.3, purchase a passenger EMU such as the 115 series or 415 series, etc. Then attempt to refit the train.

**Comment by PeterN** [comment]
Same cause as #7447, fixed by #7449 which didn't reach 1.9.0.

**Comment by PeterN** [comment]
Fixed in 1.9.1
