### ISSUE TITLE
1.9.0 Cannot display language properly.

### ISSUE THREAD

**Issue by capitalismlab-owner** [OpenTTD/OpenTTD#7477]
## Actual result
[![20190406194943.png](https://i.postimg.cc/1zx9Rjws/20190406194943.png)](https://postimg.cc/NK4hpbdz)

**Comment by nielsmh** [comment]
That's some serious mojibake. Which language is selected in Settings?

**Comment by TrueBrain** [comment]
And possibly some other additional information that could really help:
- What OS are you running?
- Would you mind attaching your `openttd.cfg`?
- Does this happen every time, or only when you change language or something?

Anything else you can share would be really helpful! Tnx!

**Comment by capitalismlab-owner** [comment]
OS:Windows10,Simplified Chinese.
I have already set openttd.cfg up.
openttd-1.8.0 works，openttd-1.9.0 Cannot display all languages.

**Comment by capitalismlab-owner** [comment]
openttd.cfg
> ...
> small_font = C:\WINDOWS\Fonts\simsun.ttc
> medium_font = C:\WINDOWS\Fonts\simsun.ttc
> large_font = C:\WINDOWS\Fonts\simsun.ttc
> mono_font = C:\WINDOWS\Fonts\simsun.ttc
> small_size = 24
> medium_size = 24
> large_size = 24
> mono_size = 24
> 
openttd-1.9.0 works.
