### ISSUE TITLE
Changing client name closes construction windows

### ISSUE THREAD

**Issue by ldpl** [OpenTTD/OpenTTD#7479]
## Version of OpenTTD
1.9.0

## Expected result
Not close. Because why?

## Actual result
Closes construction windows and goal question windows (that are considered to be construction ones for some reason).

## Steps to reproduce
join server
open some building tools
open console
type "name new_name"

**Comment by ldpl** [comment]
ClientNetworkGameSocketHandler::Receive_SERVER_CLIENT_INFO calls SetLocalCompany which calls DeleteConstructionWindows

**Comment by bendevnull** [comment]
Is there a reason that this is unexpected behavior? It seems simple enough to fix.
