### ISSUE TITLE
Text rendering error under CJK system locale

### ISSUE THREAD

**Issue by YJSoft** [OpenTTD/OpenTTD#7511]
## Version of OpenTTD
All version above 1.9.0-beta1

## Expected result
(Windows 10 RS5)
![image](https://user-images.githubusercontent.com/5893514/56090539-5c8ce900-5ede-11e9-9942-e09f264ce1e2.png)

## Actual result
(Win7)
![image](https://user-images.githubusercontent.com/5893514/56090547-74fd0380-5ede-11e9-8113-7f92b09bccc9.png)

(Win8.1)
![image](https://user-images.githubusercontent.com/5893514/56090551-7cbca800-5ede-11e9-962d-d146c56a5d35.png)

(Did't tested Win10 RTM ~ RS1 due to not supported by MS anymore)

(Win10 RS2)
![image](https://user-images.githubusercontent.com/5893514/56090553-87773d00-5ede-11e9-9f77-7b60bb294f52.png)

(Win10 RS3)
![image](https://user-images.githubusercontent.com/5893514/56090554-90680e80-5ede-11e9-8699-f2d51701610b.png)

(Win10 RS4)
![image](https://user-images.githubusercontent.com/5893514/56090555-98c04980-5ede-11e9-8cfb-43c48326ecac.png)

## Steps to reproduce
Execute OpenTTD 1.9.1 on Korean version of Windows(below Win10 RS5)
All strings are corrupted, even english.lng is not displayed correctly.
OpenTTD 1.8.0 works well, but OpenTTD 1.9.0-beta1 or above doesn't works.

**Comment by nielsmh** [comment]
Looks like this is #7477, thanks for the detailed report.

**Comment by telk5093** [comment]
Notes:
1) There is a one Win 8.1 user and it is fine for him
2) A similar issue was at JGRPP(JGRennison/OpenTTD-patches/issues/58)

**Comment by nielsmh** [comment]
It may have to do with having an MBCS ANSI locale set since (so far) only users with Chinese or Korean languages have reported this. I'm still on 1803 so I should try switching my ANSI locale and see if that affects language file loading.

**Comment by YJSoft** [comment]
All systems above used config file from [Here](https://telk.kr/ottd/download), which bundles NanumGothic font file. By default, config file will set OpenTTD font to ./font/NanumGothic.ttf and that is causing problem.

![vmware_8SBEDD75fV](https://user-images.githubusercontent.com/5893514/56866758-30ae4f00-6a18-11e9-9acb-7e0f62109f8f.png)
(Batang)

![vmware_UGZ0VuSp6e](https://user-images.githubusercontent.com/5893514/56866786-94387c80-6a18-11e9-954b-e7e3ce282934.png)
(NanumGothic font installed)
If I change font to Batang(which is one of default korean font) or install NanumGothic.ttf, everything works fine.

I tried to debug that, but vs debug build simply refuses to load ttf file.

**Comment by michicc** [comment]
> If I change font to Batang(which is one of default korean font) or install NanumGothic.ttf, everything works fine.

OpenTTD switch to Microsoft's Uniscribe for text layout with the 1.9 release, as the layout component of the previously used ICU library is deprecated and has random crashes.

Font rendering is still done using FreeType and not GDI. FreeType will happily try to eat any font it is given, but Uniscribe, being a system components, relies on data provided by Windows, and seems to fail on uninstalled fonts. #6980 would fix that dissonance, but I'd assume Windows would automatically still select an installed font and not the one you want.

**Comment by nielsmh** [comment]
Running the game under a Chinese locale with https://github.com/xupefei/Locale-Emulator reproduces this bug, so we have something to work with now.

**Comment by nielsmh** [comment]
It turns out the language data is being loaded correctly, and conversions from internal UTF-8 to the UTF-16 required by Uniscribe is correct. The problem seems to be somewhere in the shaping process, and it seems that it's (somehow) adding 3 to the value of each glyph number, or something similar to that.

**Comment by clzls** [comment]
Although it was marked as **Fixed** as early as 14 May, but the problem seems to remain in 1.9.3, and my `openttd-20190824-master-gc7c1d1cb0c-windows-win64` worked fine...

**Comment by LordAro** [comment]
Yes, it missed the 1.9 branch, and due to the significance of the fix (completely swapping out the text rendering engine) it couldn't be backported. It will be in the 1.10 release
