### ISSUE TITLE
Load/Save screen got lost, unrecoverable.

### ISSUE THREAD

**Issue by cheako** [OpenTTD/OpenTTD#7523]
## Version of OpenTTD
1.8.0-2 
## Expected result
Full or at least adequate control over CWD in save/load screens.
## Actual result
Unable to enter ~/.local/
## Steps to reproduce
Enter the dialog in game and goto previous directory repeatedly until at the home dir.  This should present an inability to recover back to the default saves folder.

I agree that hidden files should be hidden, but there should be a method for entering hidden folders(a place to type the names of folders to cd)  There should also just be a button for going to the default folder.

Thanks!

**Comment by PeterN** [comment]
There is a little "Home" icon next to the sorter buttons / above the scrollbar. This will take you back to the default folder.

**Comment by nielsmh** [comment]
Closing this as the above suggestion probably solves it, and reporter hasn't replied.
