### ISSUE TITLE
Feature Request: Delivery Caps/Throttling.

### ISSUE THREAD

**Issue by cheako** [OpenTTD/OpenTTD#7524]
I had a map where one coal mine was close to two Power Plants.  This leads to an interesting situation where there is little incentive to service both PP at the same time as a single PP will take all the coal.

**Comment by PeterN** [comment]
That can be provided for by NewGRFs (whether there is a particular one that will do this for power plants is another matter.)

**Comment by cheako** [comment]
@PeterN I think you have mixed this issue up with another, maybe?

**Comment by PeterN** [comment]
No, delivery caps can definitely be achieved with NewGRF industries.

**Comment by odisseus** [comment]
I think [ECS](https://www.tt-wiki.net/wiki/ECS_Vectors) has this feature.

**Comment by andythenorth** [comment]
Try "Pikka's Basic Industries" or Pikka's newer "Town and Industry - Basic Industries".  

Both feature delivery caps for industries such as power plant. https://pikka.users.tt-forums.net/wiki/index.php?title=Pikka%27s_Basic_Industries

**Comment by nielsmh** [comment]
Closing this as the feature is already provided by mods, and this kind of gameplay change is preferred to only be available by mods according to [the official project goals](https://wiki.openttd.org/FAQ_development#What_are_the_goals_of_the_offical_branch.3F).
