### ISSUE TITLE
Cant read error

### ISSUE THREAD

**Issue by Roki100** [OpenTTD/OpenTTD#7535]
## Version of OpenTTD

1.8.0

## Expected result

Can read error

## Actual result

Cant read error

## Steps to reproduce

Start OpenTTD On SSH

![gre](https://user-images.githubusercontent.com/35699619/56516610-2b926100-653b-11e9-9af5-6847404f08d6.png)

**Comment by PeterN** [comment]
If you compiled with Allegro, this is Allegro being funny and using ASCII Art output. Compile without Allegro, and if you want a dedicated server only, compile with --enable-dedicated.
