### ISSUE TITLE
[FreeBSD] Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by ChiiFii** [OpenTTD/OpenTTD#7536]
## Compile and install OpenTTD from Ports

I've tried to run OpenTTD in a jail as a dedicated Server. The shells answers the syntax error.
What should I do?

Second try: download and compile OpenTTD by my own - there is also a bug. You will find it in another issue.

**Comment by nielsmh** [comment]
`/usr/local/bin/openttd` should usually be an executable binary, not a shell script or similar, which that error message seems to suggest. Can you check the actual contents of the file?

**Comment by ChiiFii** [comment]
it works :)
