### ISSUE TITLE
Fix for power/running cost sorting algorithm.

### ISSUE THREAD

**Issue by dorobouNeko** [OpenTTD/OpenTTD#7561]
The algorithm assumes that running cost (in GBP) is always higher than power, which is not always true. 
Solution would be to make the division and compare two floats, with enough precision. Also take into account zero running cost when dividing.
I would code this but my c++ is kinda rusty and i bet someone else could make this much more elegant and consistent with the project.

**Comment by MingweiSamuel** [comment]
(link: #7573)
