### ISSUE TITLE
Feature Request: Add drag functionality to land purchase tool

### ISSUE THREAD

**Issue by tbasten** [OpenTTD/OpenTTD#7562]
Currently purchasing land is a single click only action. Extending this to be a box selection like the landscaping tools would be really useful.

**Comment by nielsmh** [comment]
I believe it's not draggable on purpose to limit some types of griefing in multiplayer.

**Comment by tbasten** [comment]
I could be a game option that has to enabled? That way server admins can
set it if they want

**Comment by kiwitreekor** [comment]
There's already a patch on forum for this.
https://www.tt-forums.net/viewtopic.php?f=33&t=29495&p=1164202

**Comment by andythenorth** [comment]
Thanks for this.  Single-click purchasing **is** annoying to do.  But we would have to add a setting for this, as server owners often want to prevent this type of griefing.  We try to avoid adding more settings as they make the core game more fragile and complicated to work with (and test).  I think this is unlikely to be accepted for vanilla OpenTTD (it might be something a patchpack would consider).\\

We try to keep the issue count low, so I'm closing this one.  Thanks!
