### ISSUE TITLE
[NRT] The 'build tunnel' tool displays the wrong cursor for road and tram

### ISSUE THREAD

**Issue by Andrew350** [OpenTTD/OpenTTD#7565]
## Version of OpenTTD
20190503-master-g6f33cfd059
## Expected result
When selecting the "build tunnel" tool for road or tram, the cursor sprite should be that of road or tram
## Actual result
The displayed sprite is the railroad tunnel cursor. Note that this only affects the default road/tram types and any NRT sets which do not provide explicit GUI sprites. If a NewGRF overrides the GUI/cursor sprites via callback then the correct sprites will be shown.
## Steps to reproduce
Start up a nightly with NRT and select the 'build tunnel' tool for road or tram.

**Comment by Hexus-One** [comment]
I've noticed this issue since release 1.8.0 - there's only one sprite enum for "bridge" in `sprites.h` which is shared by both road and rail bridges.
