### ISSUE TITLE
Crash When bombing level crossing

### ISSUE THREAD

**Issue by Fortitude44** [OpenTTD/OpenTTD#7576]
Open TTD 20190507-master-g652268ad1a

Crash when bombed highlighted tiles in screenshot

Full crash, exit to windows

Rebuild the level crossing using a rough tramway and then bomb.

[crash.log](https://github.com/OpenTTD/OpenTTD/files/3164287/crash.log)
![crash](https://user-images.githubusercontent.com/50467160/57491897-9c18dc00-72b6-11e9-927b-603e6d1d9d07.png)

[Crash.zip](https://github.com/OpenTTD/OpenTTD/files/3164304/Crash.zip)

**Comment by Fortitude44** [comment]
I see this is now closed. What was the issue?

**Comment by nielsmh** [comment]
It seems it wasn't checking whether a tile actually could have a road before doing some other road-related checks.
