### ISSUE TITLE
Feature Request: When loading a saved game, the file picker should remember the last used directory

### ISSUE THREAD

**Issue by btzy** [OpenTTD/OpenTTD#7580]
It seems that when using the file picker to find a saved game, OpenTTD initialises the file picker to `${Home}/OpenTTD/save` (or something similar), at least on Windows.  Some people might want keep their saved games in a different directory, and hence have to take the time to navigate to it everytime they launch OpenTTD to continue their saved games.  (I keep my saved games on a network drive so that I can access it from other machines, and there are probably people who would like to keep their saved games on a different drive, or just a different directory on the default drive.)

It would be more convenient if OpenTTD remembers the directory that was last used (i.e. the directory containing the file that was last selected).  This is consistent with the way Windows file pickers work by default, and is probably consistent with other operating systems too.  For OpenTTD, the last used directory could be saved in `openttd.cfg`.

It probably wouldn't matter much whether the *load* file picker and the *save* file picker shares the same configuration entry.  On Windows file pickers, they are remembered separately (so launching a file *save* dialog defaults to the directory last used to *save* a file, even if the directory last used to *open* a file is different).  For OpenTTD, I can't think of a use case where we would need the *load* and *save* directories to be remembered separately.

**Comment by EgyLynx** [comment]
What if wanna load other game file than just saved?

**Comment by btzy** [comment]
> What if wanna load other game file than just saved?

Well you could simply navigate to another folder, just like you can do in a regular Windows/Mac/Linux file picker.  The key point is that 99% of the time you will want to load a game from the folder that you last used.

**Comment by andythenorth** [comment]
Thanks for this.  It's unlikely this behaviour will change in vanilla OpenTTD.  The game has been around a long time, and for UI / behaviour changes that are quite subjective, it's as likely that changes will annoy players as please them.  Therefore it's just simpler to not make certain changes.  

We try to keep the issue low, so I'm closing this one.  Thanks!
