### ISSUE TITLE
Inverted scrolling unavailable

### ISSUE THREAD

**Issue by gprints** [OpenTTD/OpenTTD#7585]
## Version of OpenTTD
1.9.1

## Expected result
my .openttd/openttd.cfg contains
reverse_scroll = true
and this worked fine before I upgraded from 1.8.0 to 1.9.1

## Actual result
Scrolling no longer is inverted and the Interface section in the settings menu does no longer contain "interaction", which is where to enable it.

## Steps to reproduce
click the cog wheel, choose settings, choose interface and notice the missing "interaction" menu.

**Comment by kiwitreekor** [comment]
Maybe duplicate of #7463?

**Comment by gprints** [comment]
yes, sorry. I didn't check closed bugs.
