### ISSUE TITLE
Loading old waypoints from savegame version 72 causes crash

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#7587]
## Version of OpenTTD
1.9.1 stable

## Expected result
The savegame loads and simulates normally.

## Actual result
The savegame "[Sundinghattan Transport, 10th Dec 2110.sav](https://github.com/OpenTTD/OpenTTD/files/3170439/1131.-.Sundinghattan.Transport.10th.Dec.2110.crashes.zip)" (#1131) always crashes on load (after a few game ticks) with "NOT_REACHED triggered at line 2711 of d:\a\1\s\src\rail_cmd.cpp". [Crash files have been attached.](https://github.com/OpenTTD/OpenTTD/files/3170440/1131.-.Sundinghattan.Transport.10th.Dec.2110.zip)

This is probably caused by an invalid rail track tile being accessed.

## Steps to reproduce
Load the attached savegame and wait a few game ticks.

**Comment by LordAro** [comment]
Purely for informational purposes, can you try with latest master as well? There's been some changes in that area - #7544 comes to mind

**Comment by James103** [comment]
The same savegame, loaded in the latest master (20190511) crashes immediately on load, but with a different assertion (Assertion failed at line 113 of d:\a\1\s\src\core\pool_type.hpp: index < this->first_unused). [Crash files have been attached.](https://github.com/OpenTTD/OpenTTD/files/3170533/OpenTTD.zip)

**Comment by James103** [comment]
When I try to load the "Sundinghattan Transport, 10th Dec 2110.sav" save game using the 2019-05-16 (or later) version of OpenTTD master, the game crashes (Assertion failed at line 212 of d:\a\1\s\src\rail_map.h: IsPlainRailTile(t)), but says that the NewGRF "total_town_replacement_set-3.02a\ttrs3w.grf" with GRFID 56430001 and MD5 checksum AF3E0A1E6EF0B98DB966594578D1775B was not found and a compatible NewGRF was loaded, therefore no additional crash info has been generated.

Do you have the exact version of the following NewGRF that I need to load the saved game and possibly allow crash info to be generated?
![image](https://user-images.githubusercontent.com/37945304/57976323-98661300-79a2-11e9-97c4-efa8aecae2c7.png)

**Comment by LordAro** [comment]
Investigation shows that it's crashing on tile 50011, which looks like it's a RailTileType of `RAIL_TILE_WAYPOINT`. This type was later removed when waypoints were reorganised to be more like stations. I managed to compile 0.6.x and load the save successfully:

![](https://i.imgur.com/26P0ibB.png)

Nothing special about the waypoint on first glance...

With bisecting, I nailed down the crash to 2646a99d29535a44c5998f080131cbca2e85bdcf . There is a change in afterload.cpp in there...

**Comment by LordAro** [comment]
The issue is, as far as I can tell, that at that point in the loading sequence waypoint still has tiletype of `MP_RAILWAY` (rather than station) and then causes `SetTrackReservation` to fall over

**Comment by LordAro** [comment]
With the following diff I was able to load the save in current master: (Though the game crashes somewhere in YAPF after running for a few ticks - possibly because there's a depot tile pretending to be a railtrack)

```
diff --git a/src/saveload/afterload.cpp b/src/saveload/afterload.cpp
index 47d2c7b03c..cb3e05e5c3 100644
--- a/src/saveload/afterload.cpp
+++ b/src/saveload/afterload.cpp
@@ -1951,8 +1951,10 @@ bool AfterLoadGame()
                                        /* Clear PBS reservation on track */
                                        if (IsRailDepot(t)) {
                                                SetDepotReservation(t, false);
-                                       } else {
+                                       } else if (IsPlainRailTile(t)) {
                                                SetTrackReservation(t, TRACK_BIT_NONE);
+                                       } else {
+                                               fprintf(stderr, "Unknown MP_RAILWAY tile: %i\n", t);
                                        }
                                        break;
 
```

which outputs

```
Unknown MP_RAILWAY tile: 50011
Unknown MP_RAILWAY tile: 52370
```

and looks like:

![](https://i.imgur.com/CFiEElC.png)

I notice that neither of these tiles are apparently stored in the old WAYP save block, which will presumably be why they're getting converted to depots instead. As to why they're not in the WAYP block...
