### ISSUE TITLE
If you change the game mode 9 times in succession, then the game crashes on the ninth attempt.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#7590]
## Version of OpenTTD
20190511-master-g38bb6b7d1b

## Expected result
The game doesn't crash at all when creating a new map, loading a saved game, or otherwise modifying the game state.

## Actual result
On the ninth time that you create a new world, load a saved game, or otherwise modify the gamemode, the game crashes hard. Note that the exact crash is different depending on the last game-mode-modifying action you took, but there are two similar crash logs that account for all situations mentioned below.
[Crash log for the hard crash (no error message)](https://github.com/OpenTTD/OpenTTD/files/3170748/Crash.log.when.creating.new.world.zip)
[Crash log for the crash with the error message](https://github.com/OpenTTD/OpenTTD/files/3170749/Crash.log.when.loading.any.savegame.zip)

## Steps to reproduce
Create a new world, load a saved game, start scenario editor, connect to or (re)start a server, return to the title screen, or otherwise modify the game mode 9 times. The 1st through 8th attempts will go through, but the 9th attempt crashes with either an E06D7363 error or C0000005 error.

Edit: Just running "rescanai" 9 times or running "rescangame" 18 times is enough to crash the game with [this log (should be similar to above).](https://github.com/OpenTTD/OpenTTD/files/3175085/OpenTTD.-.1.zip)

**Comment by glx22** [comment]
Hard crash call stack:
``` 	openttd.exe!StringCompare::operator()(const char * a, const char * b) Ligne 25	C++
 	[Code externe]	
 	[Cadre en ligne] openttd.exe!std::_Tree<std::_Tmap_traits<char const *,int,StringCompare,std::allocator<std::pair<char const * const,int> >,0> >::lower_bound(const char * const &)	C++
 	[Cadre en ligne] openttd.exe!std::_Tree<std::_Tmap_traits<char const *,int,StringCompare,std::allocator<std::pair<char const * const,int> >,0> >::find(const char * const &)	C++
>	openttd.exe!ScriptConfig::GetSetting(const char * name) Ligne 101	C++
 	openttd.exe!ScriptConfig::AddRandomDeviation() Ligne 136	C++
 	openttd.exe!ScriptConfig::ScriptConfig(const ScriptConfig * config) Ligne 58	C++
 	openttd.exe!ScriptConfig::AnchorUnchangeableSettings() Ligne 97	C++
```
Seems it's doing ScriptConfig::GetSetting(nullptr) and crash on `strcmp(something, nullptr)` in `StringCompare`

Other crash call stack:
``` 	KERNELBASE.dll!7535969b()	Inconnu
 	KERNELBASE.dll![Les frames ci-dessous sont peut-être incorrects et/ou manquants, aucun symbole chargé pour KERNELBASE.dll]	Inconnu
 	[Code externe]	
>	openttd.exe!ScriptAllocator::CheckLimit() Ligne 46	C++
 	openttd.exe!Squirrel::CallMethod(tagSQObject instance, const char * method_name, tagSQObject * ret, int suspend) Ligne 355	C++
 	openttd.exe!Squirrel::CallStringMethodStrdup(tagSQObject instance, const char * method_name, const char * * res, int suspend) Ligne 383	C++
 	openttd.exe!ScriptInfo::Constructor(SQVM * vm, ScriptInfo * info) Ligne 91	C++
 	openttd.exe!AIInfo::Constructor(SQVM * vm) Ligne 73	C++
 	openttd.exe!SQVM::CallNative(SQNativeClosure * nclosure, __int64 nargs, __int64 stackbase, SQObjectPtr & retval, bool & suspend) Ligne 1188	C++
 	openttd.exe!SQVM::Execute(SQObjectPtr & closure, __int64 target, __int64 nargs, __int64 stackbase, SQObjectPtr & outres, unsigned __int64 raiseerror, SQVM::ExecutionType et) Ligne 798	C++
 	openttd.exe!SQVM::Call(SQObjectPtr & closure, __int64 nparams, __int64 stackbase, SQObjectPtr & outres, unsigned __int64 raiseerror, unsigned __int64 can_suspend) Ligne 1483	C++
 	openttd.exe!sq_call(SQVM * v, __int64 params, unsigned __int64 retval, unsigned __int64 raiseerror, int suspend) Ligne 978	C++
 	openttd.exe!Squirrel::LoadScript(SQVM * vm, const char * script, bool in_root) Ligne 666	C++
 	[Cadre en ligne] openttd.exe!Squirrel::LoadScript(const char *)	C++
 	openttd.exe!ScriptScanner::AddFile(const char * filename, unsigned int basepath_length, const char * tar_filename) Ligne 57	C++
 	[Cadre en ligne] openttd.exe!ScanTar(FileScanner *) Ligne 1378	C++
 	openttd.exe!FileScanner::Scan(const char * extension, Subdirectory sd, bool tars, bool) Ligne 1411	C++
 	openttd.exe!ScriptScanner::RescanDir() Ligne 98	C++
 	openttd.exe!AI::Rescan() Ligne 357	C++
 	[Cadre en ligne] openttd.exe!AI::Uninitialize(bool) Ligne 186	C++
 	openttd.exe!AI::Initialize() Ligne 167	C++
 	openttd.exe!InitializeGame(unsigned int size_x, unsigned int size_y, bool reset_settings, bool) Ligne 110	C++
 	openttd.exe!GenerateWorld(GenWorldMode mode, unsigned int size_x, unsigned int size_y, bool reset_settings) Ligne 314	C++
 	openttd.exe!MakeNewGame(bool from_heightmap, bool reset_settings) Ligne 976	C++
 	openttd.exe!SwitchToMode(SwitchMode new_mode) Ligne 1176	C++
 	openttd.exe!GameLoop() Ligne 1456	C++
 	openttd.exe!VideoDriver_Win32::MainLoop() Ligne 1266	C++
 	openttd.exe!openttd_main(int argc, char * * argv) Ligne 862	C++
 	openttd.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Ligne 444	C++
 	[Code externe]	
```
`Maximum memory allocation exceeded` exception thrown by ScriptAllocator

**Comment by PeterN** [comment]
I'd imagine that the new squirrel memory tracking isn't getting cleared at some point.

**Comment by James103** [comment]
Actually, just executing the console command "rescangame" 18 times or executing the command "rescanai" 9 times is enough to [crash the game.](https://github.com/OpenTTD/OpenTTD/files/3175085/OpenTTD.-.1.zip) You don't need to repeatedly change the game mode multiple times like I originally said.

**Comment by glx22** [comment]
Number of times probably depends on number of AI/GS you have, and also on the memory limit set for scripts.

**Comment by James103** [comment]
As for number of command "rescanai" or "rescangame" reruns, it is the same no matter the RAM limit set in openttd.cfg. However, the number of Ais and Game Scripts and the complexity of their info.nut files do affect the number of times that "rescanai" or "rescangame" need to be rerun until a crash occurs. For example, with all AIs and Game Scripts available on Bananas, it takes 10-15 loops until crash. With just a single PathZilla AI, it takes 1000-1500 loops until crash.
 In addition to that, a game script or AI that normally only uses ~2-10 MB depending on number of towns can report itself to the performance monitor as using many times even that the OpenTTD.exe process itself as a whole is using (for example: displayed 1 GB ram usage, actual 5 MB).
