### ISSUE TITLE
Road vehicles don't balance between multiple loading bays

### ISSUE THREAD

**Issue by nielsmh** [OpenTTD/OpenTTD#7592]
Based on [post on TT-Forums](https://www.tt-forums.net/viewtopic.php?p=1221859#p1221859)

## Version of OpenTTD
Likely after merge of road vehicle path caching

## Expected result
Road vehicles choose a free loading bay to head towards when multiple are available at a station.

## Actual result
Road vehicles head towards the same loading bay even after it has been filled.

## Steps to reproduce
Send many road vehicles to the same few stations with mutiple loading bays.

## Suggested fix
Prevent road vehicles from caching the last 1 or 2 turns (or 10 tiles if that's shorter) before their scheduled next stop.

**Comment by MingweiSamuel** [comment]
I'm guessing caching also breaks road vehicle balancing https://wiki.openttdcoop.org/Road_Vehicle_Networking#Balacing

**Comment by Wirdal** [comment]
Would `RoadVehUpdateCache` in `roadveh_cmd.cpp` be a good place to start poking around? 

Edit:

Looks like that function is mostly for updating `GroundVehicleCache`, which seems to be thing more mechanical in nature, such as speed, weight, and drag.

`RoadVehPathCache` is the structure that caches hold the cached path that nielsmh mentioned in the suggested fix. I'll see where it updates.

**Comment by Wirdal** [comment]
After some digging and wrestling with my own IDE, the cache is updated in `ChooseRoadTrack` in the `yapf_road.cpp` file.

I think that there is another _kind_ of pathfinding that OpenTTD has, although I am not sure. I'll look into it, though.

Edit:


NPF is the other type, but does not cache, therefor, this issue (probably) does not exist with it.

**Comment by Wirdal** [comment]
I just need to work on the turn counting that was the other part of the suggested fix.

Hopefully what I have now works for "less that 10 tiles", although I am not sure if they are always before the next scheduled stop.

I'll do some testing by just sending a bunch of before and after things and see how things stack up.

**Comment by nielsmh** [comment]
I'm not sure what I was thinking with the suggested fix, it makes no sense to not cache the last 10 tiles if that's a straight road/no intersections, as that still doesn't give the vehicle any alternates.
A better attempt: Do not cache segments on the last 5, 8, or 10 (not sure, probably needs tuning?) tiles before the destination, but always at least 1 segment not cached regardless of distance.

**Comment by Eddi-z** [comment]
How about a different approach: still cache all the segments, but have the pathfinder add penalties for cached loading bay selections, so on average it still balances out?

**Comment by Wirdal** [comment]
Any good resource for understanding YAPF? The wiki is very sparse.

**Comment by Eddi-z** [comment]
Rules for understanding YAPF:
1. don't try to understand YAPF
2. you only need to change the "follow track" function, which assigns the penalties

**Comment by JGRennison** [comment]
YAPF is not so complicated that you should not try to understand it. The source can be understood with a little time, and is by nature authoritative.

For what it's worth this is one I prepared earlier which gave satisfactory results at my end: https://github.com/JGRennison/OpenTTD-patches/commit/79d5be7e265df3be8b73d484f0c7261b3c23229d

A more heavyweight solution to issues around road vehicle cache invalidation in general is here: https://github.com/JGRennison/OpenTTD-patches/commit/829c635addf77965129c0889d69dab709f51b827, parts of this may come in handy.

**Comment by Wirdal** [comment]
OK. I'll reset what I worked on and try to make some progress towards one of those suggestions (whatever may be easier for me at that time).

Also, I have never worked with this kind template work before. Double whammy.

**Comment by Wirdal** [comment]
I like to think I have made progress in the the understanding of the system, or at least a semblance of 
progress. However I think that @JGRennison 's first fix was the general area I was headed in, just two weeks earlier.

I don't see myself writing anything better than that, although I would be more than willing to help test it, if needed.
