### ISSUE TITLE
Null pointer dereference in ScriptOrder::GetOrderDistance in VT_AIR mode on waypoint tiles

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#7593]
## Version of OpenTTD
Current master

## Expected result
No null pointer dereference occurs when calling ScriptOrder::GetOrderDistance in VT_AIR mode with either origin_tile or dest_tile as a waypoint tile.

## Actual result
Null pointer dereference occurs when calling ScriptOrder::GetOrderDistance in VT_AIR mode with either origin_tile or dest_tile as a waypoint tile.
ScriptTile::IsStationTile() (i.e. IsTileType(tile, MP_STATION)) returns true for waypoint tiles, however Station::GetByTile() returns nullptr.

## Steps to reproduce
Load and unpause the attached savegame.
AIAI v97 calls ScriptOrder::GetOrderDistance in VT_AIR on the west and north corners at initialisation.

[GetOrderDistance bug.sav.zip](https://github.com/OpenTTD/OpenTTD/files/3184950/GetOrderDistance.bug.sav.zip)

See also:
https://github.com/JGRennison/OpenTTD-patches/commit/bdcafb38ccad4bb5ce94ee9c54dc9adfe2edca03
Thread starting from: https://www.tt-forums.net/viewtopic.php?p=1221446#p1221446

**Comment by glx22** [comment]
Please open a PR with your fix.

**Comment by PeterN** [comment]
Wouldn't it make more sense for `ScriptTile::IsStationTile()` to return false for waypoints?

**Comment by glx22** [comment]
`ScriptTile::IsStationTile()` only checks for `MP_STATION`. Adding `&& ::Station::GetByTile() != nullptr` could work, but then we'd need to add `ScriptTile::IsWaypointTile()` with `&& ::Waypoint::GetByTile() != nullptr` and an API compatibility function for the old behaviour in scripts.
