### ISSUE TITLE
Max speed string dparam set incorrectly in road vehicle purchase window when using original acceleration model

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#7594]
## Version of OpenTTD
Since e6bb9054

## Expected result
Road vehicle max speed rendered correctly in road vehicle purchase window when using original acceleration model

## Actual result
Road vehicle max speed not rendered correctly in road vehicle purchase window when using original acceleration model

## Steps to reproduce
Use road vehicle purchase window when using original acceleration model

See also:
https://github.com/JGRennison/OpenTTD-patches/commit/f5f72611c20833a7c047422fb83ae82b02340ad0

**Comment by glx22** [comment]
Please open a PR with your fix.
