### ISSUE TITLE
openttd: symbol lookup error: /lib/x86_64-linux-gnu/libiculx.so.60: undefined symbol: _ZNK6icu_6012LayoutEngine14getCharIndicesEPiiR11LEErrorCode

### ISSUE THREAD

**Issue by cosminCos** [OpenTTD/OpenTTD#7598]
## Version of OpenTTD
1.9.1
## Expected result
launch the game
## Actual result
app crushes
## Steps to reproduce
OS: ubuntu 19.04
```
VERSION="19.04 (Disco Dingo)"
VERSION_ID="19.04"
VERSION_CODENAME=disco 
```
Try to launch OpenTTD from terminal:
output:
``` 
teminal~ openttd 
openttd: symbol lookup error: /lib/x86_64-linux-gnu/libiculx.so.60: undefined symbol: _ZNK6icu_6012LayoutEngine14getCharIndicesEPiiR11LEErrorCode
```

**Comment by PeterN** [comment]
We don't build OpenTTD for Ubuntu 19.04. You must use a binary that is designed to run on Ubuntu 19.04, or build it yourself from source.
