### ISSUE TITLE
UI zoom appearance problems relative to 1.9.1

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/OpenTTD#7599]
## Version of OpenTTD

38bb6b7d1b04e0e9402b489758bf7471d37cc36f

## Expected result

UI appearance on 2x UI zoom is consistent with 1.9.1

## Actual result

UI appearance has multiple issues

* button spacing is too much on new game window
* title game is shown at 2x zoom
* after changing the UI zoom to 1x, the new game window appearance is wrong in multiple ways (this does not always reproduce)
* vehicle windows have grown an extra frame
* aspect ratio of error messages is changed (too wide relative to line length, height, padding)
* aspect ratio of some news messages now looks _better_ relative to 1.9.1 (some text clipping is fixed), but news messages now fill a very large proportion of the screen, and new vehicle messages are very wide and have excess whitespace
* vehicle exclusive preview windows look odd, but I haven't been able to trigger one quickly 
* minimap window has an extraneous frame around the map
* main date / money / news bar has inconsistent top / bottom padding

<img width="1440" alt="UI_with_2x_ui_zoom_1_9_1" src="https://user-images.githubusercontent.com/1780327/58048311-625f9500-7b42-11e9-904f-4da01ba83e7e.png">

<img width="1434" alt="UI_with_2x_UI_zoom" src="https://user-images.githubusercontent.com/1780327/58048289-54aa0f80-7b42-11e9-9c91-f69ec4b9fb7a.png">
<img width="1439" alt="UI_after_changing_2x_UI_zoom_to_1x" src="https://user-images.githubusercontent.com/1780327/58048294-57a50000-7b42-11e9-866b-f61f0e0ce561.png">
<img width="560" alt="new_vehicle_1_9_1" src="https://user-images.githubusercontent.com/1780327/58048324-6ab7d000-7b42-11e9-8b14-fcedd4f19899.png">
<img width="950" alt="new_vehicle" src="https://user-images.githubusercontent.com/1780327/58048327-6d1a2a00-7b42-11e9-8049-dee8274bebc3.png">
<img width="376" alt="errors_1_9_1" src="https://user-images.githubusercontent.com/1780327/58048336-71464780-7b42-11e9-8597-e7235eb137b6.png">
<img width="537" alt="errors" src="https://user-images.githubusercontent.com/1780327/58048346-75726500-7b42-11e9-8d09-841e9cf2ee40.png">
<img width="542" alt="train_window_1_9_1" src="https://user-images.githubusercontent.com/1780327/58048363-7c997300-7b42-11e9-8394-ee3936e9a812.png">
<img width="535" alt="train_window" src="https://user-images.githubusercontent.com/1780327/58048372-7efbcd00-7b42-11e9-9bb5-f9c156c1ab04.png">

## Steps to reproduce

Use 2x UI zoom (I am also using 2x font zoom)

**Comment by nielsmh** [comment]
Keep in mind that most windows don't re-layout fully after changing UI zoom, and you need to close and re-open them This includes the main menu window.
Most of these don't appear for me.

The newspaper window proportions should match those of unzoomed UI with unscaled text.

**Comment by andythenorth** [comment]
Thanks for reply nieslmh :)
- the 'choose climate' bug doesn't trivially reproduce.
- the extra frame on vehicle windows is reliably reproducible, I'm +/-0 to that one as long as it's expected
- same +/-0 on error messages, I guess I'm just noticing the change

The news messages, specific to my screen size, fill a lot of screen, and obscure the map when they appear, whereas in 1.9.1 etc they are quite minimal and unintrusive.  I could solve this by turning news messages off.

<img width="720" alt="news_1-9-1" src="https://user-images.githubusercontent.com/1780327/58583606-4e0b4e80-824c-11e9-9213-6977f6331001.png">
<img width="720" alt="news_38bb6b7" src="https://user-images.githubusercontent.com/1780327/58583610-506da880-824c-11e9-8dad-9d29813fd177.png">

**Comment by andythenorth** [comment]
Issue is resolved by turning news messages off.
