### ISSUE TITLE
Town::cargo_accepted, Town::cargo_produced saveload and consistency issues

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#7603]
## Version of OpenTTD
Current master

Town::cargo_accepted is a TileMatrix with a 2x2 grid, of data type CargoTypes (i.e. uint64).
In src/saveload/town_sl.cpp it is saved and loaded with type uint32 for the data array, such that only the first half of the data array is actually saved and loaded.
The data array (but not the rectangular tile area extent) is unconditionally recalculated on load via AfterLoadGame -> UpdateHousesAndTowns -> RebuildTownCaches -> UpdateTownCargoes.

The 3 argument form of UpdateTownCargoes calculates the acceptance of each 2x2 square using an area up to 6x6 as returned by AcceptanceMatrix::GetAreaForTile with extent 1.
What is the rationale for: storing acceptance on a 2x2 tile basis, and using an area larger than 2x2 to populate the acceptance of that area?

In the case where a house is removed (in ClearTownHouse), the 2x2 square in which the northernmost house tile is, is updated by use of the 3 argument form of UpdateTownCargoes.
The case where the the house has multiple tiles which extend out of that 2x2 region doesn't seem to be handled, nor does the case where the immediately adjacent 2x2 regions also need to be re-updated due to the use of an enlarged region in the 3 argument form of UpdateTownCargoes.

In the case where the last house which accepts a particular cargo is removed, adjacent 2x2 squares can incorrectly retain the acceptance bit for that cargo, such that Town::cargo_accepted_total has the bit incorrectly set (see UpdateTownCargoTotal). This is used in subsidy generation.

UpdateTownCargoes is called both monthly (from TownsMonthlyLoop), and at load (as described above). In the case where Town::cargo_accepted/Town::cargo_accepted_total has become incorrect since the last TownsMonthlyLoop, and this a multiplayer server, if a new client joins it will recalculate Town::cargo_accepted and Town::cargo_accepted_total immediately with different values from those on the server, and this creates an opportunity for multiplayer desyncs.

Town::cargo_produced is also used in subsidy generation. It is added to from the 3 argument form of UpdateTownCargoes which is called on house add/remove, but removals are only made monthly or on load/join. In the event where the last house which produces a particular cargo is removed between a call to TownsMonthlyLoop and a multiplayer client join, the client and server would have differing values for Town::cargo_produced, and this also creates an opportunity for multiplayer desyncs.

What is the rationale for using a TileMatrix of bitmasks for acceptance and a single bitmask for production?

The acceptance and production of a house may be defined by means of NewGRF callbacks. If the results of the callbacks differ between the start the month and mid-month when a multiplayer client joins, this could also result in a multiplayer desync for the same reason as above.

Less importantly, enabling desync logging results in UpdateTownCargoes being called periodically from CheckCaches via RebuildTownCaches, however Town::cargo_accepted, Town::cargo_accepted_total and Town::cargo_produced are not among the variables which are checked for changes, and the old values are not restored. Consequently enabling desync logging masks the problem rather than highlighting it.

**Comment by JGRennison** [comment]
*Bump*

There are unresolved desync issues at present, and this could be an area of interest for investigation.

These are not directly rebasable but could point to potentially interesting areas of the code to look into for debugging:
https://github.com/JGRennison/OpenTTD-patches/commit/326dfd33ebd964222143a1252203f0a6066a4056
https://github.com/JGRennison/OpenTTD-patches/commit/9519c5c1fb6aee15f85cecf7a253e61e149755e4
https://github.com/JGRennison/OpenTTD-patches/commit/3c2ebc4588c77f84abeacd2c6dc9cbdb6157b910
https://github.com/JGRennison/OpenTTD-patches/commit/546b5248e0230d293446eb9908c7a20a1e9e83da
https://github.com/JGRennison/OpenTTD-patches/commit/5155afee9bf44933f7794208c170170272d48f22
https://github.com/JGRennison/OpenTTD-patches/commit/6d9f9ec3523e615b661ab093a958f517d4ae028b
https://github.com/JGRennison/OpenTTD-patches/commit/c2470a21af6e02d11befb7f9a2a9a84accc091f4

I will see if I can tidy all this up at some point.

**Comment by TrueBrain** [comment]
I see several merged PRs in relation to this issue; what is left of this issue that needs resolving (if any)?

**Comment by JGRennison** [comment]
All of this stuff was nicely deleted by #8159, so this can indeed be closed.
