### ISSUE TITLE
Buildings "wander" north away from roads

### ISSUE THREAD

**Issue by MingweiSamuel** [OpenTTD/OpenTTD#7604]
Buildings "wander" away from roads in the negative x and negative y directions. As suggested by Eddi|zuHause on irc, this seems to happen when a lot larger than 1x1 is replace by a 1x1 lot, then that in turn is replaced by a larger lot again. When the 1x1 lot replaces a larger lot, it always goes in the top corner (-x, -y dir), which means buildings can slowly move north over time. This process seems to take maybe 6-10 in-game years. See attached pictures.

![image](https://user-images.githubusercontent.com/6778341/58286528-cf05aa00-7d63-11e9-9361-1e52aaf6cb74.png)

![image](https://user-images.githubusercontent.com/6778341/58286979-cd88b180-7d64-11e9-993c-1910527976ac.png)

~~I have observed this happening with the Total Town Replacement Set new GRF, so it may be related to that GRF, or the GRF may have some changes that exacerbate this problem. I'll test in vanilla soon~~
happens in vanilla as well

## Version of OpenTTD
1.9.1

## Expected result
Buildings should be built adjacent to roads.

## Actual result
Buildings are able to move away from roads when they are replaced

## Steps to reproduce
Build a city. Make some busses so it'll grow. Make sure "towns are allowed to build roads" is off. Fast forward, over time this will begin to happen.

**Comment by erenes** [comment]
I can confirm this happens in 1.10.2 as well. 

Specifically I saw a football stadium being replaced with houses, then a stadium again, and another house, resulting in a house 2 tiles away from the road.

1987: ![image](https://user-images.githubusercontent.com/3177915/103754862-38a3fc00-500d-11eb-9a3d-a702430638d1.png)
1989: ![image](https://user-images.githubusercontent.com/3177915/103754830-2cb83a00-500d-11eb-90bf-692cc7e8f5e1.png)

**Comment by andythenorth** [comment]
Would it be convenient to have a house and industry check 'at least one tile of a house/industry layout is adjacent to road'?

This could be used by the house placement algorithm, and exposed as a newgrf house/industry var.

It is possible for newgrf industry to check for adjacent road currently, but it's fiddly to do.

**Comment by TrueBrain** [comment]
The code to replace houses is lovely naive:

```
		ClearTownHouse(t, tile);

		/* Rebuild with another house? */
		if (GB(r, 24, 8) >= 12) BuildTownHouse(t, tile);
```

So yeah, there is a good chance this happens :D It also means it doesn't really wander off, as in, it doesn't continue to happen, I think. At most, with non-grid layouts, a house can be 2 tiles away from a road :)

**Comment by TrueBrain** [comment]
Nope, I am wrong; it can truly wonder. Chances are very slim, but it is possible :D When a 2x2 house is build, it can put it in all directions .. so yeah, truly "wandering" :D

![image](https://user-images.githubusercontent.com/1663690/103761547-2038df00-5017-11eb-920d-881889c53ead.png)
