### ISSUE TITLE
Competitors Signs and Names

### ISSUE THREAD

**Issue by Barj0na** [OpenTTD/OpenTTD#7622]
Competitors signs and names aren't displaying properly - see below.

Version 1.9.1

![openttd](https://user-images.githubusercontent.com/51793421/59444759-53dd6400-8df6-11e9-8c03-f12bf7e6607b.JPG)

**Comment by LordAro** [comment]
Sounds like you've turned the transparency options on?

https://wiki.openttd.org/Transparency_options

**Comment by Barj0na** [comment]
Ah, it was the "signs displayed" option that was on - although I don't know why all those signs appeared.

Anyway it's fixed now - thanks for the "very quick" response. Have a nice day. :)
