### ISSUE TITLE
Support for macOS Catalina.

### ISSUE THREAD

**Issue by 15458434** [OpenTTD/OpenTTD#7623]
## Version of OpenTTD

1.9.1

## Expected result

OpenTTD can be launched.

## Actual result

The game can't be launched.

## Steps to reproduce

Use macOS Catalina.

**Comment by 15458434** [comment]
I installed OpenTTD through Home brew by the way.

**Comment by LordAro** [comment]
Can you give any more detail than "can't be launched"? Is there an error message?

**Comment by joshvickerson** [comment]
I just gave it a go on Catalina public beta 2 (build 19A501i). When you try to run OpenTTD you're given this message:

![Screen Shot 2019-07-06 at 9 28 26 AM](https://user-images.githubusercontent.com/2325487/60756846-c2b27500-9fd0-11e9-9887-d3ef68984f25.png)

By holding control (or presumably right-clicking) and choosing Open from the context menu, you're given the same message with the option to open it:

![Screen Shot 2019-07-06 at 9 28 57 AM](https://user-images.githubusercontent.com/2325487/60756854-e4abf780-9fd0-11e9-87b3-975aa5a8989c.png)

Subsequent opens don't give you the message once you choose to open it. I'm not sure what would need to be done to avoid this message in the first place, but once you get past it, OpenTTD seems to run fine.

**Comment by nielsmh** [comment]
So Apple wants us to have a digital signature for the package.

**Comment by michicc** [comment]
If going by https://eclecticlight.co/2019/06/07/notarization-in-mojave-and-catalina/, it's quite a bit more than just a digital signature.

**Comment by James103** [comment]
This issue also affects OpenRCT2 in that the game can't be started in MacOS 10.14.5 because "it is from an unidentified developer". Can you confirm that here? See OpenRCT2/OpenRCT2#9508 for more info.

**Comment by 15458434** [comment]
I guess the binary is 32-bit and Catalina only supports 64-bit binaries. There is blocking icon over the icon. And it’s impossible to press the icon to launch Openttd.

**Comment by andythenorth** [comment]
The 'cannot be checked' message is just Gatekeeper, has been triggering for OpenTTD for years, because OpenTTD isn't signed. https://en.wikipedia.org/wiki/Gatekeeper_(macOS).  That said, something might have changed in Gatekeeper for Catalina.

Stable OpenTTD releases from 1.9.x onwards are 64 bit binaries, see https://github.com/OpenTTD/OpenTTD/issues/6978

Mystery deepens?  I don't have Catalina yet, so I can't test, but eh :)

**Comment by prokopsimek** [comment]
> I just gave it a go on Catalina public beta 2 (build 19A501i). When you try to run OpenTTD you're given this message:
> 
> ![Screen Shot 2019-07-06 at 9 28 26 AM](https://user-images.githubusercontent.com/2325487/60756846-c2b27500-9fd0-11e9-9887-d3ef68984f25.png)
> 
> By holding control (or presumably right-clicking) and choosing Open from the context menu, you're given the same message with the option to open it:
> 
> ![Screen Shot 2019-07-06 at 9 28 57 AM](https://user-images.githubusercontent.com/2325487/60756854-e4abf780-9fd0-11e9-87b3-975aa5a8989c.png)
> 
> Subsequent opens don't give you the message once you choose to open it. I'm not sure what would need to be done to avoid this message in the first place, but once you get past it, OpenTTD seems to run fine.

It's common problem with games on MacOS for me. I am used to confirming to run the app from an unidentified developer.

**Comment by bryan-lunt** [comment]
It dies catastrophically on multiplayer.

**Comment by andythenorth** [comment]
There is currently nothing practical that OpenTTD can do about this.  FWIW there is widespread Mac community opinion is that Catalina is a car-crash release from Apple.

We may need to deal with forthcoming Apple app notorisation in future, but that's not now.

**Comment by andythenorth** [comment]
FWIW 1.10.0 Beta 1 and 1.10.0 Beta 2 both work fine for me on Catalina.

**Comment by nickpan** [comment]
I opened the package and ran the terminal file. It showed a missing font error then crashed.

It's missing a font, so I downloaded "Aaux Pro Medium" installed it and problem solved.

http://fontsgeek.com/fonts/Aaux-ProMedium-Regular/download is where I downloaded the font file.

**Comment by andythenorth** [comment]
Leaving this one closed.  All builds I've tried (official binary and self-compiled) work for me on Catalina.  There's no repro and no further reports.
