### ISSUE TITLE
Building drive through road stop on town-owned one-way road crashes game.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#7626]
## Version of OpenTTD
20190603-master-g846fc8fe09
(and probably any version after merge of PR #7547)

## Expected result
The drive through road stop is built and the game does not crash.

## Actual result
When you try to build a drive through road stop on any town-owned one-way road, it fails and crashes the game with `Assertion failed at line 311 of d:\a\1\s\src\company_cmd.cpp: owner != OWNER_TOWN || tile != 0`.
[crash.zip](https://github.com/OpenTTD/OpenTTD/files/3303788/crash.zip)

## Steps to reproduce
1. Load up a saved game/scenario with town-owned one-way roads, e.g. Cindini.
2. Make sure that the game is unpaused or that "command_pause level" == 3 (Advanced Settings -> Limitations -> When paused allow: All actions)
3. Make sure that "road_stop_on_town_road" == true (Advanced Settings -> Limitations -> Allow drive through stops on town owned roads: On)
4. Try to build a road stop on a town-owned one-way road. If it would be successful (before the money check), then it instead crashes the game.

**Comment by EgyLynx** [comment]
Are you mean these where cam at vechiles? Are youre think at game "wait" vechiles at right/Left and when one side is not possible it isnt know how continue?  So there should be message tells at it not work that way...

**Comment by James103** [comment]
![image](https://user-images.githubusercontent.com/37945304/60056052-32f1fa00-96a5-11e9-9897-925f5f64a7ca.png)

1. Select one of the drive-through road stops, which looks like this (for buses). Note that this crash affects only the drive through road stops, not the road vehicle bays.
![image](https://user-images.githubusercontent.com/37945304/60056137-7cdae000-96a5-11e9-8dc4-bb0ebc000b2e.png)

2. If the highlighted tile is owned by towns AND one-way, then the game will crash when building a drive through road stop there. In this case, both conditions are true.

3. When building a drive through road stop under these conditions, the game crashes because one or more special cases weren't handled properly (in this case the special case of drive-through stop on town-owned road)

**Comment by Ben79487** [comment]
It's probably due to the fact that bus stops can't be one-way, therefore the game tries to build a one-way bus stop but can't.

**Comment by James103** [comment]
Still crashes in 20190723-master-g2e686ad5d5. [Crash files have been attached.](https://github.com/OpenTTD/OpenTTD/files/3445628/crash_one_way.zip)
Why haven't the PR fixing this crash, #7627, been merged already? It's been more than a month since the PR was opened, and 3 and a half weeks since it was approved to merge.

**Comment by LordAro** [comment]
Because there are some questions about the fix. I should've removed the review, tbh
