### ISSUE TITLE
Extremely low (x1/128) track build/remove cost severely restricts the track conversion feature.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#7633]
## Version of OpenTTD
OpenTTD 20190603-master

## Expected result
You should be able to universally convert track no matter what the costs are for building track.

## Actual result
When you use BaseCosts 5.0 newGRF to set the "build track" cost multiplier and "remove track" cost multiplier to x1/128, track conversion is no longer universal: Instead, you can convert (electrified) rail to monorail or maglev, and you can convert from monorail to maglev and vice versa. That's it. You can't convert from monorail/maglev to normal railway, nor can you (de)electrify railways. 

I think reducing the build track and remove track costs to x1/128 causes some combinations to return 0 as the cost, which the game treats as being invalid, and so those conversions return "No suitable railway track" and are therefore prohibited.

## Steps to reproduce
1. Load BaseCosts 5.0 newGRF and set the "build track" cost multiplier and "remove track" cost multiplier to x1/128.
2. Build one piece each of Rail, Electrified Rail, Monorail, and Maglev.
3. Attempt to convert the rail types. The results (from my testing) look like this:
* Normal Rail: can convert to Maglev/Monorail only
* Electric Rail: can convert to Maglev/Monorail only
* Monorail: can convert to Maglev only
* Maglev: can convert to Monorail only
* Unable to downgrade Monorail/Maglev to Railway
* Unable to (de-)electrify railways

**Comment by nielsmh** [comment]
It looks like the problem would be the cost becoming 0 rather than -1.

https://github.com/OpenTTD/OpenTTD/blob/0db31ae27f391f83f8f2f5272506adaa245c0962/src/rail_cmd.cpp#L1776

The solution will likely have to be tracking a separate error flag throughout the function.

**Comment by James103** [comment]
Does the same problem with zero-cost conversion failing occur with road and tramway? If so, could you fix those as well (same/similar method to #7634, tracking separate "found_convertible_road" and "found_convertible_tramway" flags in addition to "found_convertible_track")?

**Comment by nielsmh** [comment]
I can't reproduce it with RattRoads at least, I haven't tried with tram tracks though. (This is without the patch in #7634.) Still might be worth making the same change to road building.
