### ISSUE TITLE
Save game can't open (liblzma returned error code)?

### ISSUE THREAD

**Issue by Rk8ley** [OpenTTD/OpenTTD#7649]
Reddit told me this was the best place to go for answers on this 

## Steps to reproduce - No idea

Screenshot - https://imgur.com/a/w7nodN1

Non-working Save game - https://drive.google.com/file/d/1HOTRSZLrYPpJAhrD-4mNg9bFLhQPwZs4/view?usp=sharing

Reddit post - https://www.reddit.com/r/openttd/comments/ccamz3/person_with_little_openttd_experience_here_my/

Save game with nothing done - https://drive.google.com/file/d/1fT7tQiDB6tLun7BSiBGxVoRi2sMU27L_/view?usp=sharing

The exact scenario that I used - https://drive.google.com/file/d/1m2PGehKRn_g0Gv00N-1pdL1KOGoP31P-/view?usp=sharing

The scenario that it is all ultimately based on - https://drive.google.com/file/d/1qGrdczGatKrdaz-EgPRC1nyVLIRp7JXX/view?usp=sharing

**Comment by Eddi-z** [comment]
That error usually means the file is corrupted (like, disk was full while saving). inthat case, there's probably no solution to that

**Comment by nielsmh** [comment]
I tried loading the savegame under debugger to get the exact error code. The LZMA library returns error 9 (LZMA_DATA_ERROR): "Decoders return this error if the input data is corrupt. This can mean, for example, invalid CRC32 in headers or invalid check of uncompressed data."

In short, the save file is plain broken. As far as I can tell from the internal data, the error happens about 128 kb before the end of the file.

**Comment by James103** [comment]
Is there any way to display the exact error code that is being outputted by the LZMA library inside of the error text in the savegame select windows (i.e. "Broken savegame - liblzma returned error code **9**") in the standard nightly OpenTTD versions? If so, how?
