### ISSUE TITLE
OpenTTD company HQ graphics bug in x-ray mode

### ISSUE THREAD

**Issue by Ben79487** [OpenTTD/OpenTTD#7650]
I'm using OpenTTD 1.9.2 on Windows 8 64-bit.
I was using x-ray mode (key X) to build bus stations when I realized that the company HQ sprite experiences a weird clipping issue with the station sprite.

I expected that the HQ would be rendered with the shadowed graphic, like town buildings and stations, or that it would be rendered in full color.

The actual result was that the HQ sprite was clipped off by the train station sprite of Cuthill Main.

Steps to reproduce:
1. Stick your HQ in a town, preferably near tall buildings, or right in front of a train station.
2. Let your company grow a bit, so the HQ will get taller. (Iterations 1 and 2 don't suffer from this glitch.)
3. Get into xray mode by pressing [X].
4. See that the HQ sprite is clipped.

(First image is regular mode, second image is xray mode)
![Cuthill   Sundhead Railways, 14th May 1987#1](https://user-images.githubusercontent.com/52835868/61149770-c9406100-a496-11e9-8538-246d1197397a.png)
![Cuthill   Sundhead Railways, 14th May 1987](https://user-images.githubusercontent.com/52835868/61149771-c9406100-a496-11e9-851c-84a96a437078.png)

**Comment by nielsmh** [comment]
Nah that's just how the graphics is designed to look. OpenGFX is means to be exactly compatible with the original graphics from Transport Tycoon Deluxe, and that means it clips sprites the same way too. The bottom of the house you see is part of the "ground sprite" and only the part that gets hidden is part of the "house sprite". It looks bad but it's unfortunately intentional and I'm not sure it can be fixed. (Someone else please chime in on that.)

**Comment by Ben79487** [comment]
Wait... So the ground sprite, in the case of the "Office blocks", is the pavement texture (the gray one) and the building sprite is the building itself?

**Comment by nielsmh** [comment]
Exactly. You can see the spritesheet here: https://github.com/OpenTTD/OpenGFX/blob/master/sprites/png/miscellaneous/hq.png
Sprite 53 and 55 in that sheet are the HQ top corner ground and building graphics.

**Comment by Ben79487** [comment]
Thanks. I'll wait to see if anybody else comments before closing this issue.

**Comment by Alberth289346** [comment]
I tried original TTDX graphics (windows version), and I get
![Screenshot_20190726_104043](https://user-images.githubusercontent.com/3254232/61938664-f2321d00-af91-11e9-9036-938dac82a99e.png)
and
![Screenshot_20190726_104020](https://user-images.githubusercontent.com/3254232/61938680-f9f1c180-af91-11e9-9add-d2619f6c899b.png)

Note that industries do this too. "flat" industries are always drawn, and eg factories do
![Screenshot_20190726_104402](https://user-images.githubusercontent.com/3254232/61938932-7edcdb00-af92-11e9-86a0-65f6c3e8a998.png)
and
![Screenshot_20190726_104433](https://user-images.githubusercontent.com/3254232/61938943-8308f880-af92-11e9-9198-c1bf8379a5ad.png)


So yeah, everything within the contour of the ground plate is always shown.

**Comment by LordAro** [comment]
Yup, feature, not a bug ;)
