### ISSUE TITLE
Cheat window date '<' arrow incremements date

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/OpenTTD#7655]
## Version of OpenTTD

Reproducible in 1.9.1 (Mac build)

## Expected result

Cheat window date control '<' arrow decrements date.

## Actual result

Cheat window date control '<' arrow incremements date.

Also applies to max height levels control in cheat window.  
I can't repro this for money or company controls in  cheat window.

## Steps to reproduce

Click the '<' arrow for the date control in the cheat window.  
Reproducible at all combinations of 1x ui zoom, 2x ui zoom, 1x font zoom, 2x font zoom

The issue is sensitive to mouse position, moving the mouse further left gets the expected result.  However note that the '<' UI control is showing the down state on click, this isn't just a mis-click.

![is_it_bug_wow](https://user-images.githubusercontent.com/1780327/61181384-c58b1680-a61d-11e9-8db7-69264b2c8fc2.gif)

**Comment by nielsmh** [comment]
Reproduces in 1.9.2 on Windows and on master a52bbb72a8a2
(Edit from previous, didn't try hard enough to reproduce on master)

**Comment by nielsmh** [comment]
Lots of code in the cheat window forgets to scale all kinds of coordinates by the UI scale factor.

**Comment by Ben79487** [comment]
Can reproduce. Also happens with the "maximum map height" arrow buttons.
