### ISSUE TITLE
Railway construction menu disappears

### ISSUE THREAD

**Issue by Shindurion** [OpenTTD/OpenTTD#7659]
## Version of OpenTTD
1.9.2 on android
In 1.9.1 everything worked fine! Bug exists since yesterday when this version was released to google play store!
## Actual result
After selection maglev Construction From the Railway Menu once, the menu entries above disappear. It is not possible to get to the railway menu again. 

## Steps to reproduce
Start a new game in the year 2020. Select maglev. Open railway construction menu again.

**Comment by glx22** [comment]
We don't make the android version, does it also happen with non android version ?

**Comment by Shindurion** [comment]
After downloading the current version from the creators website (not google play) the bug is gone.
