### ISSUE TITLE
Station sets using ground tile numbers using incorrect tiles for maglev and monorail

### ISSUE THREAD

**Issue by EratoNysiad** [OpenTTD/OpenTTD#7662]
## Version of OpenTTD
1.9.2
## Expected result
Station tiles using tile 3981 as ground tile should show up as grass when placed.
 
## Actual result
For monorail it loads a coast tile and for maglev it loads a farmland tile.
https://imgur.com/a/IFjC2nT

## Likely culprit
Basetiles for track are, for instance tiles 1011, 1093 and 1175 for rail, monorail and maglev respectively.
Monorail and maglev are thus 82 and 164 sprites "higher" than normal rail. Adding those numbers to 3981 gives you 4063 and 4145, which are the exact sprites shown.

## Steps to reproduce
load either North Korean station set or Dutch Stations Addition Set Part 2.
Select Monorail (it's blatantly obvious there)
For the North Korean set look at the "Non-Track Tiles" tab.
For the Dutch set look at the "Non-track tiles" tab.

**Comment by Yexo** [comment]
I haven't looked at those particular NewGRFs yet, but it isn't clear to me that this is a bug in OpenTTD rather than those NewGRFs. From the spec (https://newgrf-specs.tt-wiki.net/wiki/Action0/Stations#Sprite_layout_.2809.29):

> Depending on the railtype the sprites may get additional offsets:
> 
>   | Normal/electrified rail | Monorail | Maglev
> -- | -- | -- | --
> TTD sprites | 0 | 82 | 164
> Action 1 sprite (first ground sprite) | 0 | 1 | 2
> Action 1 sprite (other sprites in the layout) | 0 | 0 | 0
> 
> So, TTD sprites and the first ground sprite are affected by the railtype, while other action 1 sprites in the layout are not. The offset "82" refers to the offset between the default TTD track sprites; if you are using non-track ground sprites which are not from an action 1, you need to supply fake spritenumbers which preemptively reverse the offsets (that is, you need different sprite layouts for every railtype your station is available for).

**Comment by frosch123** [comment]
This is a difficult part / trap in the NewGRF specs.
OpenTTD's behavior is correct.
The NewGRFs need fixing.
