### ISSUE TITLE
Crash when opening Game Options

### ISSUE THREAD

**Issue by nikolas** [OpenTTD/OpenTTD#7672]
## Version of OpenTTD
git master (425cd3e4ca8cf6812bdf015c649a7bf4b76a71a1)

## Expected result
Opens Game Options

## Actual result
Crash: [crash.log](https://github.com/OpenTTD/OpenTTD/files/3438799/crash.log)

## Steps to reproduce
* Install new copy of openttd from git
* Install OpenGFX, OpenSFX, OpenMSX from within openttd
* Try to open Game Options

**Comment by James103** [comment]
Message: `NOT_REACHED triggered at line 1684 of /home/nik/src/OpenTTD/src/strings.cpp`

This crash blocks three important things: switching languages, changing the font and GUI scale, and changing the base set, all of which are important to have easy ways to access and change. The only other ways to access all three are as far as I know, is modifying the openttd.cfg file, looking for the right settings, and changing them to the right values, something which takes far longer then just going into the game options and changing it there.

**Comment by glx22** [comment]
I guess you have more than 32 resolutions available, and I think it happens since 9195f2337a7c4f9154058877093bbb74db33cf32 (not tested, but high probability)
