### ISSUE TITLE
Crash on loading saved game from #4397

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#7678]
## Note
I'm adding this because the original issue, #4397, when it was marked as fixed, didn't specify whatever or not it fixed existing savegames. Also, the savegames listed below assert on load in master (but load fine in 1.9.2), but the savegames "British Rail, 20-12-1996.sav" and "crash.sav" from #4424 (duplicate of #4397) load fine in master as well.

## Version of OpenTTD
20190723-master-g2e686ad5d5

## Expected result
The savegame loads and simulates normally.

## Actual result
* When loading in 1.9.2: The savegame does not crash on load.
* When loading in 20190707-master-g1e723934a1: Game crashes while loading with `Assertion failed at line 1493 of /usr/src/OpenTTD/compile/src/tunnelbridge_cmd.cpp: GetTunnelBridgeTransportType(tile) != TRANSPORT_RAIL`. [Crash files have been attached.](https://github.com/OpenTTD/OpenTTD/files/3429257/crash-4397.zip)
* When loading in 20190723-master-g2e686ad5d5: Game crashes while loading with `Assertion failed at line 1127 of d:\a\1\s\src\vehicle_base.h: v->type == Type`. [Crash files have been attached.](https://github.com/OpenTTD/OpenTTD/files/3459676/crash-4397.1.zip) Note: Assertion here is different than the assertion in the older version listed.

## Steps to reproduce
Load the attached savegame: [#4397 - crash.sav, autosave30.sav.zip](https://github.com/OpenTTD/OpenTTD/files/3459682/4397.-.crash.sav.autosave30.sav.zip)

**Comment by LordAro** [comment]
Both of these saves load fine for me now (20200103) - can you confirm that this has been fixed?

**Comment by James103** [comment]
Even on 20191207 master, both saves load fine. This can safely be closed.

**Comment by LordAro** [comment]
Thanks for confirming
