### ISSUE TITLE
Coop play not working correct

### ISSUE THREAD

**Issue by yzaazy** [OpenTTD/OpenTTD#7682]
## Version of OpenTTD
1.9.2, Docker Server, 2 windows clients

## Expected result
When player 2 is replacing railtracks of player 1 within the same company, the trains will drive over the replaced rail.

## Actual result
The trains do not drive over the rails laid down by player 2, whilst he is in the same company

## Steps to reproduce
Make a server,
Keep default config,
Create a company
Join company with 2 players,
Players 1 sets up a rail track, then player 2 replaces 1 piece of rail, and then the train will stop at that piece or the signal before the block where that piece is in.

**Comment by glx22** [comment]
Rail type incompatible with the train ?
Screenshots and/or savegames will help.

**Comment by yzaazy** [comment]
I am stupid
