### ISSUE TITLE
Cannot download new mods and cant save the game

### ISSUE THREAD

**Issue by DoarDinamo** [OpenTTD/OpenTTD#7689]
## Version of OpenTTD:
1.9.2

## Expected result:
helping fixing the bug

## Actual result:
When I try to download mods, on my screen apears a message, which tells that download failed, file not writen

**Comment by LordAro** [comment]
It seems like your system user doesn't have permission to write files to your user area, or possibly you're out of disk space, can you give some more details about your setup?

**Comment by DoarDinamo** [comment]
I have OpenTTD on my Local Disk C, with 115 GB Free, out of 225. Download it via installer. The OS is Windows 8 with 64 bit.  
 
  Pe vin., aug. 9, 2019 la 13:39, Charles Pigott<notifications@github.com> a scris:   
It seems like your system user doesn't have permission to write files to your user area, or possibly you're out of disk space, can you give some more details about your setup?

**Comment by DoarDinamo** [comment]
Later Edit: I ve found the problem. The antivirus sistem denied the changes of the files. I m sorry for the inconvinience caused and for your lost timeBest regards, Tudor. 

Trimis din Yahoo Mail pe Android 
 
  Pe vin., aug. 9, 2019 la 13:39, Charles Pigott<notifications@github.com> a scris:   
It seems like your system user doesn't have permission to write files to your user area, or possibly you're out of disk space, can you give some more details about your setup?

**Comment by LordAro** [comment]
No problem, glad you found the solution :)
