### ISSUE TITLE
Some nonsensical news texts when industry production changes

### ISSUE THREAD

**Issue by Wuzzy2** [OpenTTD/OpenTTD#7693]
## Version of OpenTTD
1.9.2

## Description

Some news texts regarding to industry production changes don't make sense. Here I will show 3 problematic strings:

### STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_FARM

Here, it's just a wrong German translation.

English: “Improved farming methods at {INDUSTRY} are expected to double production!”
German: “Neue Getreideanbaumethoden bei {INDUSTRY} werden Erträge verdoppeln!”

Please just change the German translation to “Neue Anbaumethoden bei {INDUSTRY} werden Erträge verdoppeln!”.

(Explanation: “Getreideanbaumethoden” = “wheat farming methods”, not “farming methods”. The current German translation therefore does not make sense when {INDUSTRY} is a kautchuk plantain, cotton candy forest or battery plantain.)

### STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_FARM

Like the string above, but when production decreases.

The English sting is: “Insect infestation causes havoc at {INDUSTRY}!{}Production down by 50%”

This works in most cases, but is slightly weird when {INDUSTRY} is a battery plantain. Granted, it's toyland, but how should insects damage batteries?
I suggest to use STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL instead, when production of a battery plantain decreases.

### Passenger production …

When you have the “smooth” economy changes enabled and play in temperate climate zone, you very frequently get messages like these:

“Passenger production at Somecity Oil Platform increases 50%!”

:D Anyway, apart from being funny, these news just get very annoying fast, especially when there are lots of oil platforms in the game.

I think these messages are not really neccessary and should not be in the news in the first place. Oil platforms tend to have very low numbers of passengers, so an increase/decrease of 50% or even 100% doesn't make a huge difference.

Or maybe don't put any passenger changes into the news, ever.

**Comment by auge8472** [comment]
OpenTTD runs an own [translation service](https://translator.openttd.org/) independent from the Git-repository. So you can change the strings at your own *if* you have a translator account. On the other hand someone else who already has an acocunt, can do the changes (I will have to search for my user data).

Exception is the battery thingy and the oil-platform-passenger-production because using another or no string in this cases should be a real code change (if I'm not missing something).

**Comment by LordAro** [comment]
Closed, translation issues are not handled here

**Comment by Wuzzy2** [comment]
@LordAro: Did you read everything? The translation problem was only a part of this issue. The other 2 things appear to require code changes. Those still stand. Please re-open.

**Comment by Wuzzy2** [comment]
OK, I tried to create an account and do the translation change myself, but apparently I am not allowed to. :-( I don't know where to post translation issues elsewhere. Sorry. So how to fix this string?

If you do not trust me: I am a translator of countless free software games, including Cataclysm: Dark Days Ahead, Hedgewars, Minetest, Voxelands, Stunt Rally, SuperTux, SuperTuxKart, FLARE, Pioneer, 0 A.D. and others.

**Comment by LordAro** [comment]
I did read it all. I don't see 
STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_FARM usage as an issue. Insects can cause issues in places other than the farmland itself of course, and as you say it's Toyland, so maybe it has insects that eat batteries?

Passenger production messages are covered by your other issue #7694 

Becoming a translator does take a bit of time, it requires someone to manually approve the request that they will get round to eventually. There's also the concern of not wanting more than one translator per language, as disagreements over translations could devolve into flipping translations back and forth. There is a discussion thread on the [forum](https://www.tt-forums.net/viewtopic.php?f=29&t=39481)

**Comment by auge8472** [comment]
I left [a message in the named thread](https://www.tt-forums.net/viewtopic.php?f=29&t=39481&p=1224359#p1224359).

**Comment by Wuzzy2** [comment]
I can agree with the rationale. OK.

Thx, auge8472.
