### ISSUE TITLE
Too much news spam on small economy changes

### ISSUE THREAD

**Issue by Wuzzy2** [OpenTTD/OpenTTD#7694]
## Version of OpenTTD
1.9.2

## My problem
This is not a bug, but it's something that I find annoying.

Smooth economy mode must be on.

When you have small changes on the production rate of an industry (less than 50%), the news quickly becoms unreadable. Every minor change gets reported, drowning all the other news. This problem gets worse if there are many industries on a large map.

I know, you can configure the news to some extent, but it's not enough and doesn't really solve the underlying problem.

## Possible solution
Add two-cut off points for a change to be considered “news-worthy”:

1) The hard cut-off: For very small changes, the change is not considered newsworthy and does not appear in the news at all.
2) Small to medium changes go to the ticker.
3) Big changes make the newspaper.

Note that “ticker” and “newspaper” means that this is the highest theoretical “news level” the news can achieve. It still can be suppressed or “demoted to ticker news” by the player news settings.

E.g. If the player said that all production changes must go into the ticker, then even big changes will be forced into the ticker.

What change is “small”, “medium” or “big” needs to be discussed.

These cut-off points should work regardless if the “smooth” economy is on or off.

**Comment by andythenorth** [comment]
Probably not the answer wanted, but can be done in newgrf :)

**Comment by LordAro** [comment]
In general, one of the first settings I change is to turn off news of production changes. Even the big changes are so rarely worth worrying about

**Comment by Wuzzy2** [comment]
I also currently disable or move to ticker the production news, but it would be nice to have a little more fine-grained control. AFAIK the changes can go from as little as 10% up to 100%. For me, a 100% change is interesting.

Moved over from an other issue (#7693):

I also add a suggestion to drop all news on “passenger production” changes, regardless of settings. The rationale being that, 1) it sounds strange when “Oil Rig XYZ passenger production increased by 50%!”, and 2) on oil rigs there are only a few passengers and even a change in 100% is not much, so it's not really newsworthy.

**Comment by andythenorth** [comment]
Thanks for this.  This won't be addressed for vanilla OpenTTD.  

It could be done in newgrf by modifying industries to only trigger news messages for certain production increases: although that may seem like a sledgehammer to crack a nut, we prefer to see behaviour changes via add-on content not the core game, it keeps everything simpler and more reliable.  

We try to keep the issue count low so I'm closing this one.  Thanks!
