### ISSUE TITLE
Loading savegame from a multiplayer game might assign you to the wrong company

### ISSUE THREAD

**Issue by Wuzzy2** [OpenTTD/OpenTTD#7695]
## Version of OpenTTD
1.9.2

## Summary
When you save a game in multiplayer, then load the savegame, you usually end up playing a different company.

## Expected result
When you load the savegame, you play as the same company you controlled when you saved the game.

## Actual result
When you load the savegame, you always play as company no. 1 which might or might be your company.
If you're unlucky, it was not your company and you have to resort to cheats to fix this.

## Steps to reproduce
1. Play online multiplayer, any vanilla server will do
2. Play for a while
3. Save the game
4. Quit the game
5. Load the savegame in singleplayer mode
6. Check which company you control

**Comment by Eddi-z** [comment]
I'd say this is intended behavior.

Single player will always be company 0, and the information which company you played is not saved. besides there will be confusion if you load a server autosave or someone else's save that they sent you.

Anyway, you can load the game as a multiplayer game (local server), if you don't want to use cheats.

**Comment by LordAro** [comment]
The possible enhancement here is to know when the save was a multiplayer save (is there anything to indicate that currently?), and give a company selection window when loading (then drop the "is multiplayer" bit and assign the correct company)

But until then, yeah, this is intended behaviour. Feel free to implement the above though!
