### ISSUE TITLE
Highscore table screw-up in double-size interface

### ISSUE THREAD

**Issue by Wuzzy2** [OpenTTD/OpenTTD#7702]
## Version of OpenTTD
1.8.0 (Sorry! :-( But in my defence, I did reseach to see if this bug was reported before. Apparently, it wasn't. Nor did I find anything in the changelogs. So here you go. It's possible the bug was fixed by pure luck in 1.9.2 already, but I doubt that.)

## Expected result
The texts in the highscore table does not overlap.

## Actual result
They do overlap when using double-size interface. The texts are completely mis-placed.

Screenshot:
![billede](https://user-images.githubusercontent.com/1062071/63251367-db6ba700-c26d-11e9-9306-fe95aa57d1ab.png)

## Steps to reproduce
1. Start OpenTTD
2. Somehow have a few entries in the highscore table
3. Go into game settings
4. Select interface size = double size
5. Go into the highscore table

## Other notes
The highscore table is fine in normal size interface.

A similar issue (no screenshot) seems to have happened with the “tycoon of the century” screen. The written text seemed to be mis-placed. So I recommend to check this screen as well while fixing this bug.

I did not test quadruple size interface, but I am assuming the issue is even worse here.

**Comment by nielsmh** [comment]
There's several hardcoded coordinates in the highscore GUI code, that's definitely the cause.

https://github.com/OpenTTD/OpenTTD/blob/dabccf70b4c02f68ebf51aca807376ca4f2a0e15/src/highscore_gui.cpp#L140-L151
https://github.com/OpenTTD/OpenTTD/blob/dabccf70b4c02f68ebf51aca807376ca4f2a0e15/src/highscore_gui.cpp#L188-L204
