### ISSUE TITLE
Inactive industries make inappropriate/unlogical sounds

### ISSUE THREAD

**Issue by Wuzzy2** [OpenTTD/OpenTTD#7703]
## Version of OpenTTD
1.8.0

## Expected result
Industries make no sound effects if they are “inactive”. Inactive means:

- If the industry has a potential output: That output is 0
- If the industry has no output (e.g. power plant): Nothing has been delivered to it in the recent past (<3 months or so)

Example:
- A paper mill with 0 paper production
- A power plant with no coal input in the last 3 months

## Actual result
Several secondary industries make inappropriate/misleading sounds when they have no production / no input:

- Paper mill (saw sound)
- Sawmill in temperate climate (saw sound)
- Factory (factory line sound)
- Power plant (electricity sound)
- Food factory?
- Possibly others?

All these particular sounds suggests these industries are active, while in fact they aren't. For instance, the sawmill sounds don't make sense when there's no wood.

## Steps to reproduce
1. Play OpenTTD
2. Pan camera to any inactive industry and listen

**Comment by Wuzzy2** [comment]
Okay, the power plant one might be arguable, I'm fine if you reject that one. I noticed the electricity sound is linked with a graphical effect as well. This should be taken into consideration.

**Comment by Wuzzy2** [comment]
Oh, I want to add: An industry is also (obviously) inactive while under construction. I noticed that industries under construction also make their industry sound.

**Comment by nielsmh** [comment]
Some places to start at:

https://github.com/OpenTTD/OpenTTD/blob/e4414471dd10c3afebc49f3cc7c51f76852b08e0/src/industry_cmd.cpp#L893-L898

https://github.com/OpenTTD/OpenTTD/blob/e4414471dd10c3afebc49f3cc7c51f76852b08e0/src/industry_cmd.cpp#L1124-L1133

The `Industry::cargo_last_accepted_at` and `Industry::last_month_production` fields are probably useful as well.
