### ISSUE TITLE
finding multiplayer servers

### ISSUE THREAD

**Issue by Arthurooooo** [OpenTTD/OpenTTD#7706]
[crash.log](https://github.com/OpenTTD/OpenTTD/files/3551848/crash.log)
[crash.sav.zip](https://github.com/OpenTTD/OpenTTD/files/3551852/crash.sav.zip)
![crash](https://user-images.githubusercontent.com/31555164/63874095-25b4fc80-c9c1-11e9-8f5b-716d51057f9d.png)

## Version of OpenTTD
1.9.2
## Expected result
finding servers
## Actual result
crashes
## Steps to reproduce
clicking the "find server" button

**Comment by nielsmh** [comment]
From crash log looks like a duplicate of #7704.

**Comment by Arthurooooo** [comment]
> From crash log looks like a duplicate of #7704.

thanks!
