### ISSUE TITLE
#7612 causes multiple news messages to show at once and overlap.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#7711]
## Version of OpenTTD
Since #7612 is merged

## Expected result
When multiple newspaper messages are shown, they don't overlap.

## Actual result
When multiple newspaper messages are shown, they do overlap.

Example 1 (the second news message is still appearing)
![image](https://user-images.githubusercontent.com/37945304/64056563-bf171680-cb59-11e9-9e28-caa0f35efdf8.png)

Example 2 (both news messages have fully appeared)
![image](https://user-images.githubusercontent.com/37945304/64056618-3e0c4f00-cb5a-11e9-92c7-214942458dbb.png)

## Steps to reproduce
Trigger lots of various newspaper messages, repeating until you get an overlap.
Example 1:
* Make sure that "opening of industries" newspaper setting is set to "Full" and "accidents/disasters" newspaper setting is set to "Summary".
* Pause the game.
* Build a power station.
* Unpause game, wait a second, pause game.
* Build 2 trains, make them ignore next signal, and start them.
* Unpause game, wait a second, pause game.
* Build a power station.
* Unpause the game.
* You will see overlapping news messages. Pressing spacebar closes the most recent/top news message.

Example 2:
* Load the savegames "wentbourne.sav" (found in #7247) or "gr0_50k_stations.sav" (found in #7235) and make sure to have all news messages set to display as "Full".

**Comment by Eddi-z** [comment]
this should be fixed by #7739?

**Comment by James103** [comment]
Might as well call it fixed, according to some testing with fast-forward. Haven't tested with the 50k stations or the Westbourne save yet
