### ISSUE TITLE
Game crashes on MacOS High Sierra 10.13.6 when i try to refresh servers list for multiplayer

### ISSUE THREAD

**Issue by vasiedd** [OpenTTD/OpenTTD#7712]
## Steps to reproduce Run program, goto multiplayer mode, refresh servers list (from internet)
[crash.log](https://github.com/OpenTTD/OpenTTD/files/3562512/crash.log)
![crash](https://user-images.githubusercontent.com/54744441/64064883-e16b6b80-cc0f-11e9-927e-c33f39480beb.png)

**Comment by nielsmh** [comment]
Duplicate of #7704
