### ISSUE TITLE
Shared orders allows only two vehicles

### ISSUE THREAD

**Issue by auslambert** [OpenTTD/OpenTTD#7732]
1.9.2

share orders allows many vehicles to share order set.

<ctrl> clicking on third vehicle to share order set. Second vehicle has *copy* of orders but is not shared. Shared order list only shows first and third vehicle. You get warnings about duplicate orders on vehicle #2 constantly.
On my game these are actually trains, #9,10 and 11.
Order set is a round robin of three passenger stations. 
Create order set on train #9.
<ctrl> click and share order set with Train #10.
<ctrl> click and share orders with train #11.
Train #11 now shows 'end of shared orders" in list. Train #10 has reverted to a plain order set, not the shared set.

**Comment by nielsmh** [comment]
I think you'll have to share your save game for this, I can't determine what you've done and what has happened from your description.
Shared orders have always worked for me.

**Comment by andythenorth** [comment]
Thanks!  There are no other reports of this, and the original poster hasn't provided a save.  I'm closing, re-open if more reports arrive, thanks.
