### ISSUE TITLE
Crash of OpenTTD master gf81cb0a90d possibly after trying to sell the default human user

### ISSUE THREAD

**Issue by Wormnest** [OpenTTD/OpenTTD#7737]
## Actual result: Crash.
[crash.log](https://github.com/OpenTTD/OpenTTD/files/3603247/crash.log)
![crash](https://user-images.githubusercontent.com/3215891/64745607-8c183f80-d4d6-11e9-9569-ab42850ef9a6.png)

It seems like GitHub doesn't like the crash.sav and crash.dmp even if I zip them up. Maybe they are too big? crash.dmp is about 20 MB.

## Steps to reproduce.
Started a test run with myself and 1 AI: the development version of my AI WormAIDev testing only trains for computer players, max trains 50.
Started in 1980 and let it run for a long time. Me (the human user didn't do any building at all).
Around 2147 it crashes and it looks like it possibly was trying to sell the human user company.
Same or similar looking crash happened on a previous master from around Sept 5 around the same date.

**Comment by glx22** [comment]
I quickly checked crash.log and indeed crash.dmp will be needed.
According to https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests zipped crash.dmp should be ok.

**Comment by Wormnest** [comment]
When trying to upload crash.zip with the crash.dmp in it it says  We don’t support that file type. Try again with a GIF, JPEG, JPG, PNG, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX or ZIP.
I renamed it to crashdmp.gz (but it is a zip) and that seems to have worked.

[crashdmp.gz](https://github.com/OpenTTD/OpenTTD/files/3603337/crashdmp.gz)

**Comment by glx22** [comment]
```
>	openttd.exe!NewsWindow::DrawWidget(const Rect & r, int widget) Ligne 396	C++
 	openttd.exe!NWidgetLeaf::Draw(const Window * w) Ligne 2520	C++
 	openttd.exe!NWidgetPIPContainer::Draw(const Window * w) Ligne 1113	C++
 	openttd.exe!NWidgetPIPContainer::Draw(const Window * w) Ligne 1113	C++
 	openttd.exe!NWidgetPIPContainer::Draw(const Window * w) Ligne 1113	C++
 	openttd.exe!NWidgetBackground::Draw(const Window * w) Ligne 1865	C++
 	openttd.exe!NWidgetPIPContainer::Draw(const Window * w) Ligne 1113	C++
 	openttd.exe!Window::DrawWidgets() Ligne 608	C++
 	openttd.exe!DrawOverlappedWindow(Window * w, int left, int top, int right, int bottom) Ligne 933	C++
 	openttd.exe!DrawOverlappedWindowForAll(int left, int top, int right, int bottom) Ligne 951	C++
 	openttd.exe!RedrawScreenRect(int left, int top, int right, int bottom) Ligne 1293	C++
 	openttd.exe!DrawDirtyBlocks() Ligne 1387	C++
 	openttd.exe!UpdateWindows() Ligne 3185	C++
 	openttd.exe!VideoDriver_Win32::MainLoop() Ligne 1284	C++
 	openttd.exe!openttd_main(int argc, char * * argv) Ligne 862	C++
 	openttd.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Ligne 444	C++
 	[Code externe]	

```

**Comment by Wormnest** [comment]
I can reproduce this without any AI too. Just start a new map (I used 512x512 now, start in 1980), don't build anything and use fast forward.
This one crashes in 2062 just when the transport company in trouble message starts popping up.
[crash.log](https://github.com/OpenTTD/OpenTTD/files/3606411/crash.log)
![crash](https://user-images.githubusercontent.com/3215891/64800566-cc1e0780-d554-11e9-8136-762ed0be240f.png)
[crash.dmp.gz](https://github.com/OpenTTD/OpenTTD/files/3606415/crash.dmp.gz)
This time it really is a gz and not a renamed zip.

**Comment by glx22** [comment]
I think I see what happens, but my system seems too slow to reproduce it.
It seems the "Company in trouble" ```NewsItem``` is deleted while the news is still displayed, causing the invalid read.

**Comment by glx22** [comment]
A probable faster way to trigger it is to disable inflation and set max loan to the minimum possible value, then when the game starts spend all money in terraforming.

**Comment by Eddi-z** [comment]
Can't you just cheat -1000000...00 money?

**Comment by Eddi-z** [comment]
just out of curiosity, can you reproduce that without https://github.com/OpenTTD/OpenTTD/commit/afbf6a59182d9b1ca36b9dab9bd391ad0ae6222f?

**Comment by Milek7** [comment]
I think this fixes it:
```
diff --git a/src/news_gui.cpp b/src/news_gui.cpp
index 34cfa7a58..3b9b0fca9 100644
--- a/src/news_gui.cpp
+++ b/src/news_gui.cpp
@@ -676,7 +676,7 @@ static void MoveToNextNewsItem()
 
                        case ND_FULL: // Full - show newspaper
                                ShowNewspaper(ni);
-                               break;
+                               return;
                }
        }
 }
```

**Comment by Eddi-z** [comment]
there's two other breaks in the other function that should also be returns
