### ISSUE TITLE
Cannot select partially visible station items

### ISSUE THREAD

**Issue by kiwitreekor** [OpenTTD/OpenTTD#7742]
## Version of OpenTTD
20190914-master-gd35254139a (It works properly on 1.9)

## Expected result
Station item is selected.

## Actual result
Station item is not selected.

## Steps to reproduce
 1. Start a game with station NewGRF
 1. Open rail station selection window
 1. Scroll down
 1. Click any item in the top line
![openttd-bug](https://user-images.githubusercontent.com/24273113/64933235-284b9900-d87f-11e9-8c62-d7529433ab1e.PNG)

**Comment by glx22** [comment]
It's caused by 66dd7c3879123bb99b712375b66b577f81d53a96
