### ISSUE TITLE
Emoji results in question mark 😀 🠚 ?

### ISSUE THREAD

**Issue by generateui** [OpenTTD/OpenTTD#7762]
## Version of OpenTTD
1.9.3

## Expected result
emoji in chatbox

## Actual result
question mark in chatbox

## Steps to reproduce
1. open OpenTTD
2. enter a network game
3. hit enter so that the chat input box opens
4. type windows key + dot (⊞ + .)
5. pick an emoji, resulting in a character (? instead of, say, 😀) being added in the chat input box

**Comment by glx22** [comment]
'?' just means the character is not present in the font used by OpenTTD. So it works as intended.

**Comment by planetmaker** [comment]
You might want to configure OpenTTD to use a font of your choice which supports emojis as "characters". See https://wiki.openttd.org/FAQ_troubleshooting#My_User_Interface_is_too_small_to_read_.2F_My_font_is_unreadable_or_faulty

**Comment by FLHerne** [comment]
For in-game chat, configuring the user's own font won't help much, because the *recipient* will still see such characters as "?".

Does OTTD really need emojis?

**Comment by generateui** [comment]
> Does OTTD really need emojis?

It's the defacto standard nowadays to communicate emotion. *Needing* is maybe overstated. But if you make a chatbox, why allow a big chunk of the communication to be broken?

**Comment by Eddi-z** [comment]
The main problem is to find a reliable way to select fonts, that works across all OSes. But in the end, you can never know if that worked for the other player, or they even had any emoji fonts installed at all, so there's always a chance that the other person only sees garbage.

**Comment by LordAro** [comment]
Known, ultimately there's nothing we can do about it

https://github.com/OpenTTD/OpenTTD/blob/ac2111873626263ae5492bd2c18ec30f69e84158/known-bugs.txt#L249-L269
