### ISSUE TITLE
Cost estimate always shows "Estimated Cost: £0" even if actual cost is not £0.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#7764]
## Version of OpenTTD
Working on 2019-08-24, broken on 2019-10-02.

## Expected result
Cost estimates should give nonzero number. 
Example: "Estimated Cost: £15" or "Estimated Income: £8,203".

## Actual result
Cost estimate always returns zero.
Example: "Estimated Cost: £0" or "Estimated Income: £0".
Affects error message for not enough money, displaying "Not enough cash - requires £0".
Does not affect the script API (GSAccounting + GSTestMode returns nonzero results)

This could possibly be due to commits b3fd7879596defeb6af78acb4ea45e4418821bdf or 0549a81c30be09529ab8a1f9acb4e435100c7c26 (both dealing with command flags).

## Steps to reproduce
Hold Shift while attempting to perform a game command (such as clearing land, buying or selling an engine, or doing a town action) to get the cost estimate. It will always say £0. Alternatively, attempt to perform a game command when you don't have enough money to do so. It will also say £0 in the error message.

**Comment by glx22** [comment]
I think it's already fixed by #7760

**Comment by glx22** [comment]
After checking the code, I can confirm it's fixed by #7760.
