### ISSUE TITLE
The cars overlaps themselves

### ISSUE THREAD

**Issue by wxwisiasdf** [OpenTTD/OpenTTD#7768]
## Version of OpenTTD
1.9.3 (Windows x86)

## Expected result
Normal cars, just going around and making a big line jam

## Actual result
https://gyazo.com/dadcc5ca1602ca45845ec2995fb9100c

## Steps to reproduce
Just plot the train, in a very jammed street and wait.
(It happens with NewGRFS AND vanilla OTTD)

**Comment by Eddi-z** [comment]
That's not a bug. The road vehicles become pass-through if they waited too long, this is a (poor) method to resolve traffic jams

**Comment by LordAro** [comment]
"Feature", not a bug. Could've sworn it was listed in known-bugs, but apparently not...

**Comment by LordAro** [comment]
Probable duplicate of #3981
