### ISSUE TITLE
Music sounds weird on Linux

### ISSUE THREAD

**Issue by SJang1** [OpenTTD/OpenTTD#7769]
## Version of OpenTTD
OpenTTD Master branch commit https://github.com/OpenTTD/OpenTTD/commit/ac2111873626263ae5492bd2c18ec30f69e84158

## Expected result
Music & Sounds all comes out correctly.

## Actual result
Effects / ...etc all are correct, but music is weird.
I am using OpenMSX as a music, OpenSFX as effect sounds.

Before(using SDL1, release ~1.9.3) music didn't came out and seemed all skipped like this
![image](https://camo.githubusercontent.com/37b264f009b224b2c1a16479527cdb9d6cb75ebb/68747470733a2f2f696d672e6e7477732e6b722f5065656b253230323031392d31302d303425323031312d33322e676966)
this is fixed at commit https://github.com/OpenTTD/OpenTTD/commit/2d27e8e6856cc7488842b01a271f57ae4bd07230 and having this problem.

## Steps to reproduce
On Fedora 31, happened even on Ubuntu 18.04 LTS.
1. git clone
2. ./configure
3. make & put OpenMSX(for me) on baseset 
4. run openttd & play music.

It happens even on main page.

**Comment by Eddi-z** [comment]
That commit has nothing to do with music drivers ("sound" and "music" are different things in OpenTTD)

`openttd -h` should list the available music drivers, and usually it will default to using the "extmidi" driver to access timidity, however you should also have support for the "fluidsynth" driver.

**Comment by SJang1** [comment]
using "fluidsynth" is also weird. (better than others, but weird on some of its.)
I have found out that using "extmidi" made all musics skipped. Looks like I was using "allegro" from SDL2.
![image](https://user-images.githubusercontent.com/29011440/66729545-0d247700-ee87-11e9-93b4-d58351ef0f9a.png)
