### ISSUE TITLE
Right-click Skip to Skip-backwards

### ISSUE THREAD

**Issue by Mysteron347** [OpenTTD/OpenTTD#7773]
Having inserted a new instruction, it's painful to back up the current-instruction pointer (only 46 clicks in this example  I've worn out three mouses this week already!)

Now - if right-clicking on the SKIP button were to move the current-order backwards to the pink arrow, it'd make this exercise a whole lot easier.
![openttd4](https://user-images.githubusercontent.com/47810334/66946151-e92d8500-f082-11e9-9530-4882214101ff.jpg)

**Comment by Eddi-z** [comment]
Right click is not possible, because that is already taken for "show tooltip" (if tooltip delay is set to 0)

Ctrl+Click might be possible.

**Comment by telk5093** [comment]
> Ctrl+Click might be possible.

Ctrl + Click to [Skip] button is already binded as skipping a certain order.

**Comment by Mysteron347** [comment]
I'm not married to right-click and it appears Ctrl-Click is also occupied.

So - shift-Click perhaps?

Or probably easier (and easier to remember) - split the Skip button into two adjacent buttons, **Skip-down** which performs identically to the current **Skip** button and **Skip-up** which also acts identically to the current **Skip** button *except* that it moves the current-order backwards in the list, not forwards.

**Comment by telk5093** [comment]
> So - shift-Click peraps?

Most Shift combined commands stand for estimating its cost, so I think Shift+click is not quite great.

**Comment by JGRennison** [comment]
Ctrl-Click already allows you to skip to an arbitrary order, it is not necessary to repeatedly press the skip button.
Select the order you want to skip to and then Ctrl-Click skip.

**Comment by LordAro** [comment]
That's a much better solution, thanks for that @JGRennison :)

**Comment by Mysteron347** [comment]
So - let's re-state the situation:

You can move the order pointer to any position in the list (forward or backward) by selecting the order and Ctrl-clicking the Skip button.

You can move the order pointer forward one position by clicking the Skip button.

You can move the order pointer back one position by following the select and Ctrl-click ceremony.

Right-click, shift-click and Ctrl-click on the Skip button are all occupied, and splitting the Skip button is too complex.


Since there is a way to move back one, there is no possibility of improving the situation.

How 'bout you cowpokes go sashay down to th'O.K. corral.

Now what's a good-lookin' white-hat to do when even the Marshall's out gunnin' for him?

Obvious! Ask Yoda.

Used here pgdn and pgup are not. Them to move one position down or up use.
. Hrmmm.
