### ISSUE TITLE
Notify button

### ISSUE THREAD

**Issue by Mysteron347** [OpenTTD/OpenTTD#7774]
How about adding an extra button between Skip and Delete named Notify.

The purpose would be to toggle the "notify" status of the currently-selected (white) order.

When the operation has been completed (eg Train arrives at Noonamah) then generate a pop-up notifying the fat controller of the event.

Whether the Notify flag for that order then auto-clears or remains should be available as a game-options item.
![openttd6](https://user-images.githubusercontent.com/47810334/66948614-9dc9a580-f087-11e9-8b89-19f8770b49fc.jpg)

**Comment by nielsmh** [comment]
What should the behaviour be in multiplayer games with multiple players controlling the same company? Should all receive a notification or just the one that requested it?

**Comment by Mysteron347** [comment]
I'll confess to have not considered multiplayer as I have only ever played as a single player.

I'm a systems analyst, so I try not to be overly prescriptive in my suggestions. Perhaps my approach to a solving a problem or adding a feature would be impractical or awkward, so I value others' contributions and work to a consensus position.

I this case, I've suggested that the order number be highlighted in another colour to indicate "notification active". Implicitly re-selecting a "notify" order and clicking it would clear the notification and the order would return to its default colour.

In the multi-player situation, I would suggest that the "notification status" be something like
Orders I have selected  for notification should appear in say, green (as shown)
Orders that any team member has in Green should appear as say Pink to me.
Notifications in which I have no interest should appear as say, Blue
Otherwise, shown in Black (or white for "currently selected" order)

Players should always receive Green notifications and may select whether or not to receive Pink notifications. 

Clicking Notify should cycle the notification indicator from Black to Green to Pink to Blue to Black.

Black : No notification preference
Green: I'm interested in this event. Notify me.
Pink: Someone else is interested in this event. Notify me if I so choose.
Blue: I am not interested in this event, even if others are. No notifications, please.

**Comment by andythenorth** [comment]
Thanks for this.  I do see the case for it, but I think it's unlikely to be accepted for vanilla OpenTTD, as orders are already complex (similar reasons to #7775).

If it's any help, I tend to pin the vehicle window if I am interested in tracking where a vehicle, or its behaviour en-route.

We try to keep the issue count low for the health of the project, so I'm closing this one.  Thanks!
