### ISSUE TITLE
Omit button

### ISSUE THREAD

**Issue by Mysteron347** [OpenTTD/OpenTTD#7775]
I'd like to see an "Omit" button, placed as below:

![openttd7](https://user-images.githubusercontent.com/47810334/66990359-9f7f8180-f0f8-11e9-8551-728a3958b9e0.jpg)
Why there? Because I am forever clicking "delete" when I intend to use "Go To".

How it might work:

Each order has an "omit status"
0 : Execute - normal operation as exists now. Just do this.
1: Once. Execute the first time this order is encountered then switch Omit Status to 3.
  Indicate by appending **(ONCE)** to the order as shown in pink.
2: Skip-once. Do not execute the first time this is encountered, proceed to next order and switch omit status to 0
  Indicate by appending **(OMIT)** to the order as shown in pink.
3: Omit. Simply skip this order permanently. Indicate by using strike-out.

The player may use the **OMIT** button to cycle the order between these four states.

This facility could be used to ease the "initialisation shuffle" where a train must visit a resource before the supplies become available for transport. You'd simply set the first visit and the following visit-nearby-station to **ONCE** then the orders are automatically converted to **OMIT** and bypassed in future.

There's also the "excuse-me dance" where a train is sent to a "siding" station to allow another train to pass. Just Go to Siding, then set that order to **ONCE**. When the second train has passed, the first has executed the Go To and the order is converted to **OMIT** and bypassed in future.

Note that I propose that the order remains in **OMIT** status, shown stuck-out - it is not **deleted**. In this way, it can easily by brought back into the orders schedule if required for a further rounds of pirouetting by changing its "omit status".

**Comment by andythenorth** [comment]
Thanks for this.  I think this one is unlikely to be accepted for vanilla OpenTTD.  Orders are already quite complex, both for players, and in the code (where conditional orders and timetables also have to be accommodated), and we don't want to increase the complexity further.

We try to keep the issue count low for the health of the project, so I'm closing this one.  Thanks!

PS: I use the 'G' hotkey to select 'Go To' when setting orders.
