### ISSUE TITLE
Go To Depot default

### ISSUE THREAD

**Issue by Mysteron347** [OpenTTD/OpenTTD#7776]
Inserting a Go To command to go to a depot assigns a simple go-to unconditional order.

It would be useful to have a player-option to insert a _Service_ non-stop order in place of a Go To to save having to change it in the majority of cases.

**Comment by JGRennison** [comment]
This is already implemented by means of having Ctrl pressed when selecting the depot tile.

**Comment by LordAro** [comment]
Already fixed, closed

**Comment by Mysteron347** [comment]
Simply because there is a voodoo ceremony that can be invoked each time a player wishes to  apply a non-default option doesn't mean that it is desirable to force that method.

Take

Expert Settings>Company>New Orders are non-stop by default

as an instance. This, using the "already fixed" logic above is totally unnecessary as the player could always apply non-stop manually after adding the order.

This suggestion is simply the same thing in blue. 

And the purple version is #7777

**Comment by nielsmh** [comment]
Holding Ctrl to do a variation of an action is a regular UI convention in OpenTTD, nothing strange about it.
