### ISSUE TITLE
Change default load percentage when setting conditional orders

### ISSUE THREAD

**Issue by Mysteron347** [OpenTTD/OpenTTD#7777]
I find that I usually use a load-percentage of 100 when I use a conditional order, but the default is zero. So - a user-option to auto-select 100% instead would be my preference.

**Comment by andythenorth** [comment]
Thanks for this.  Whilst I see the benefit of this, we try not to add further player options to OpenTTD where possible, as they make the code more complex to work with (and test and debug).  Especially in the case of conditional orders, which are already complicated.  So I think this is unlikely to be accepted for vanilla OpenTTD (a patchpack might consider it?).

We try to keep the issue count low for the health of the project, so I'm closing this one.  Thanks!
