### ISSUE TITLE
SDL2: Not possible to type shift-T into a edit context in multiplayer

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#7783]
## Version of OpenTTD
Since 2d27e8e6856cc7488842b01a271f57ae4bd07230

## Expected result
In multiplayer: pressing shift-T in the console, chat box or an text input dialog inputs a T character

## Actual result
In multiplayer: pressing shift-T opens the chat box and replaces its contents.

## Steps to reproduce
In multiplayer: pressing the shift and T keys at the same time

A possibly non-ideal fix is: https://github.com/JGRennison/OpenTTD-patches/commit/87acac9700a2f33f327f8acf1aeaf14de48ded2d

**Comment by nikolas** [comment]
Wow - really strange bug! Good catch. I'm not sure yet why this is happening. I'll take a look.
