### ISSUE TITLE
SDL2: Not possible to use the up/down keys in the console

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#7784]
## Version of OpenTTD
Since 2d27e8e

## Expected result
In the console, pressing the up/down keys selects items from the command history

## Actual result
In the console, pressing the up/down keys has no action

## Steps to reproduce
Open the console and press the up or down keys once the history has some items

A possibly non-ideal fix is: https://github.com/JGRennison/OpenTTD-patches/commit/299becbb2fe8db18d0bfa216700793675893fd6b

**Comment by nikolas** [comment]
Your patch here looks good. That's what I would've done to fix this problem.

**Comment by Nik-mmzd** [comment]
Not only up/down and not only in the console
Can't move cursor in text fields with home/end (latest git build; sdl2)
Should I open separate issue for this?

**Comment by nikolas** [comment]
No need to open a separate issue, we'll probably just have to add the home and end keys to the list here as well: https://github.com/JGRennison/OpenTTD-patches/commit/299becbb2fe8db18d0bfa216700793675893fd6b
