### ISSUE TITLE
SDL2: Version 2.0.5 is required, but configure script only checks for 2.0

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#7785]
## Version of OpenTTD
Since 2d27e8e

## Expected result
Running ./configure detects whether sdl2 is present and usable.
If found, compiling subsequently works.

## Actual result
Attempting to configure and build with sdl2 < 2.0.5 fails, due to use of the SDL_CreateRGBSurfaceWithFormat function.

## Steps to reproduce
Build on Ubuntu 16.04

A possible fix could be along the lines of: https://github.com/JGRennison/OpenTTD-patches/commit/c45d963b0f15edb09067176ee060b55909997f7e https://github.com/JGRennison/OpenTTD-patches/commit/93dffed00aea4589c02d0a89a88e4340c424b3a6

**Comment by nikolas** [comment]
Thank you for pointing this out, and yes, the solution you've come up with looks good.

**Comment by nikolas** [comment]
Ideally, OpenTTD wouldn't rely on SDL 2.0.5, if it's not available by default in ubuntu 16. I'm looking into whether we can use [SDL_CreateRGBSurface](https://wiki.libsdl.org/SDL_CreateRGBSurface) here instead.
