### ISSUE TITLE
Wrong Station is added to the Orderlist

### ISSUE THREAD

**Issue by altheeagle** [OpenTTD/OpenTTD#7789]
## Version of OpenTTD
1.9.3
## Expected result
Adding the correct Station to the Order list
## Actual result
The wrong station is added
## Steps to reproduce
I have a Station in the City of Wuppertal, which I recently moved a few tiles. The Station is divided in two parts, as shown in the Picture. (The Station is marked red).
![ottd_1](https://user-images.githubusercontent.com/22564116/67204312-8d118a80-f40d-11e9-8228-0ad1ed17fc5a.png)
When I want to place that station in Wuppertal to the Order list of a new Train, the Station in Wittenberg (wich is quite far away) is added. I have tried to add the Wuppertal Station with different Stationtile, but it brings the same result every time.
![ottd_2](https://user-images.githubusercontent.com/22564116/67204317-8f73e480-f40d-11e9-88f9-01819094607e.png)
Here is the Savegame
[Europäische Bundesbahn, 28. Jan 2362.zip](https://github.com/OpenTTD/OpenTTD/files/3750707/Europaische.Bundesbahn.28.Jan.2362.zip)

**Comment by glx22** [comment]
It's a known bug introduced in 1.9.3. If you have a station where the tile below the sign is not part of the station, you can't make an order to that station. The workaround is to force the station sign to move, or to (temporarily) build a tile for the station below the sign again.

**Comment by altheeagle** [comment]
Thank you :)
