### ISSUE TITLE
On a large and very heavily-developed map, ordering a vehicle to station A sends the vehicle to station B instead

### ISSUE THREAD

**Issue by nazdakka** [OpenTTD/OpenTTD#7798]
## Version of OpenTTD
64-bit 1.9.3 running on Windows 10.

## Expected result
In the attached savegame, ordering a vehicle to go to Wandering Docks results in Wanneroo station appearing as an order instead.

## Actual result
The vehicle is instead ordered to go to Wanneroo, a station on the other side of the map. I believe that Wanneroo was the first station built during this game.

## Steps to reproduce
1) Select a train in the attached 3593 save (any type)
2) Order it to stop at Wandering Docks
3) Note that the order selects Wanneroo instead

NB: Wanneroo is normally only a Maglev station. However, adding an airport or dock to it can produce the same problem with aircraft or boats.

## Other Information
Save game that produces the problem:
[Outback Transport Saves.zip](https://github.com/OpenTTD/OpenTTD/files/3769664/Outback.Transport.Saves.zip)

Screenshots before/after ordering a train to Wandering Docks:
[Outback Transport Screenshots.zip](https://github.com/OpenTTD/OpenTTD/files/3769715/Outback.Transport.Screenshots.zip)

I don't have a small-scale or NewGRF-free reproduction of this bug. The attached save game is a very large network in game year 3593, covering a 1024x1024 map. My oldest save with this game was on the 7th Dec 2016; I can't say what version of the game I had installed at that time.

I've attached three saves. 1878 is my very first save with this game. 3579 is the last one I have that does not exhibit this bug. 3593 is the first I have that does. Between these saves, I expanded Wandering Docks with an extra conventional rail station.

Other things I have tried:
- Creating another random station. Orders to that station work fine.
- Following a train after ordering it to go to Wandering Docks. The train goes to Wanneroo.

**Comment by glx22** [comment]
Duplicate of #7789

**Comment by nielsmh** [comment]
Known bug in 1.9.3, it will likely not be fixed. The workaround is to make sure the tile below the station sign belongs to the station signed.
