### ISSUE TITLE
Missing Industries

### ISSUE THREAD

**Issue by SkippyCoo9** [OpenTTD/OpenTTD#7846]
## Version of OpenTTD
1.9.3 and beta 20191125_Master_g40ebf3c765
## Expected result
No Lumber mills and no Forest
## Actual result
Sawmill is present
## Steps to reproduce
Unistall and redownloaded to day 11/27/2019 still missing items.

**Comment by SkippyCoo9** [comment]
Plenty of sawmills but not forest or lumber mills appear on the map.  Same before I installed the beta 1.10 download.

**Comment by nielsmh** [comment]
Are any NewGRFs loaded? If they are, try without.

Which climate are you playing? Forest industries only exist in Temperate and Sub-Arctic.

Try starting the scenario editor, place a town, then try placing each of the industries. Does that work or do you get any errors? Or are the industries completely missing from the list of available industries?

**Comment by SkippyCoo9** [comment]
Its working now. I did not load any new GRF's. I removed the open GFX Industries, clicked on Temperate map, ran pgm, Forest showed up. Added GFX Industries back in and checked, had Forest. In both landscapes maps. Before their was a  water system and water storage tanks in the landscapes map . Clicked on the sawmill  and the  display chain showed lumber, sawmill furniture, factory, Houses. Now they are gone and so it the lumber mill.  This happen right after I install the 1.10.01beta over the 1.9.3 version. Is it possible that the prg  was  using  the sub-arctic map. Or something messed up on the install of the beta over the original version . But why was it  all green and NO Desert (sand color) So I didn't think I was in the sub-arctic map Now that I think about it, there were  fruit trees as in the  the sub-arctic. The water icon was like a four small water jets. The map looked Temperate. Maybe the computer grimblem was tricking me  I got forest now.  Close out the issue. Thank you for your time and consideration. Have a enjoyable Thanksgiving
Best wish
SkippyCoo9

What Greater Honor can you have than, Too Fight for Your Country!
