### ISSUE TITLE
Cannot scroll when building on Android

### ISSUE THREAD

**Issue by xsrvmy** [OpenTTD/OpenTTD#7848]
It used to be possible to scroll with 2 fingers when building on Android. In the current version this is no longer the case.
## Version of OpenTTD
1.9.3.84 (Play Store)

## Expected result
Nothing gets build
## Actual result
The rail gets built
## Steps to reproduce
- Select the autobuild railway tool
- Start building with one finger
- Without releasing the first finger, use a second finger to click on the screen

**Comment by nielsmh** [comment]
This sounds like a bug with the Android version specifically, not something that exists or can be fixed in the mainline version. You'll have to report this with the developer of the Android port.
