### ISSUE TITLE
Reverse scroll direction?

### ISSUE THREAD

**Issue by acmsal** [OpenTTD/OpenTTD#7855]
## Version of OpenTTD
1.9.3
## Expected result
reverse scrolling
## Actual result
map/landscape scrolls in the wrong direction with right mouse button

**Comment by acmsal** [comment]
Just upgraded from 1.8.0 - now scrolling of map/landscape is in the wrong direction.
https://wiki.openttd.org/Advanced_Settings/Interface#Reverse_scroll_direction does not work.

**Comment by FLHerne** [comment]
The setting is different in 1.9.x.

Change the value of `Interface > Viewports > Viewport scroll direction` - "move viewport" and "move map" are opposite directions, 'mouse position locked' is obvious.

**Comment by acmsal** [comment]
OK - found it... The German version calls it:
Oberfläche > Kartenansichten > Verhalten beim Verschieben der Zusatzansicht
I'd never have guessed this.
Thanks
