### ISSUE TITLE
Seperate server config files

### ISSUE THREAD

**Issue by Ariikitty** [OpenTTD/OpenTTD#7858]
This is more of a suggestion then an issue but unless I am mistaken, when creating a dedicated server, the server will use the settings from the main game. This is fine however what would be more user friendly is have it so the dedicated server uses separate config files from the main game.

This will allow people to be able to play on their normal version and change the world to whatever they like without affecting the server or having to remember to revert the changes before starting the server. 

Feel free to discuss this or let me know if there is a way to do the above but from my current understanding, there isn't a way

**Comment by LordAro** [comment]
```
  -c config_file      = Use 'config_file' instead of 'openttd.cfg'
```
Would that not be sufficient?

**Comment by Ariikitty** [comment]
Are you saying to create a copy of the config file and rename it or something else cause if so then yeah that probably would work

**Comment by LordAro** [comment]
Yes, you can give `-c` any file you wish

**Comment by Ariikitty** [comment]
Ah okay I'll give this a go then and hopefully get the result  I was hoping for. Thanks for your help
