### ISSUE TITLE
Train auto replace and replace engine if old

### ISSUE THREAD

**Issue by tbajcsi** [OpenTTD/OpenTTD#7865]
## Version of OpenTTD
V1.9.3

## Expected result
A) Possibility to replace old rail vehicles when it becomes old.
B) Auto replace all trains to the same type of engine.

## Actual result
A) It is not possible to replace engines if they go old. Only replace all eingine works to any other model.
B) It is not possible to replace to the engine to a same model. If I would like to change to the same engine again, I need to replace all engines to some other model and replace them again to the desired engine.  Sometime the replace order jams even if it removed and engines are keeps constantly replaced one to an other engine. 

## Steps to reproduce
A)
1) Get some old engines.
2) Set the replace order if engine old.
Result: nothing will happen.

B) 
1) Get some engines, not necessary old ones. 
2) Change to same mode (does not work).
3 Change to a different model, let change when to an other version.
4) Set a new order to replace the engines to the desired one. 
Result: the engines sometimes keep replacing even if auto-replace order was removed.

**Comment by planetmaker** [comment]
OpenTTD distinguishes between autoreplace (with another type) and autorenew (with a newly-built vehicle of the same type).

While autoreplace is never automatic (as it needs an active decision). Autorenew is usually an automatic thing which depends on the settings you set for it - which are unfortunately found at another place than autorenew. There's a few settings to fine-tune its usage and execution:
https://wiki.openttd.org/Advanced_Settings/Vehicles#Autorenew

Arguably, for a better user experience, autorenew should (also) be accessible from the same place as autoreplace.

**Comment by nielsmh** [comment]
I have a proposed change in PR #7729 to allow autoreplace with the same model vehicle, and make the autorenew setting more visible.
