### ISSUE TITLE
Train routes labeling

### ISSUE THREAD

**Issue by bojleros** [OpenTTD/OpenTTD#7879]
## Problem definition
Usually i want to keep my freight traffic separated from mainline passenger tracks. On the other side it is handy to have a good's train connecting factories/refineries to the cities crossing the boundry between freight and passenger lines. It is now possible do have it defined but you need to define waypoints and use 'non-stop' order. This method lacks flexibility/scalability and does not behave well when you modify your network.

## Suggested improvement
I think it would be great if it would be possible to label track routes that connects the junctions. Such labels can be attached to trains and train groups so particular routes can be allowed or disallowed in a quite flexible way that allows failover (as soon as failover route exists). This idea was inspired by kubernetes affinity/anti-affinity/taints/tolerations/etc ...

**Comment by andythenorth** [comment]
Thanks for this. Feature requests are welcomed, but in many cases they they are beyond the scope of what anyone can or will do in a volunteer project :)

 It doesn't look likely that this one will go any further.  Therefore I'm closing it as we try to keep the issue count low for OpenTTD, it helps us focus on things that are important and fun. Feel free to discuss in irc or request re-opening if you disagree. Thanks for contributing!
