### ISSUE TITLE
Use of deprecated fluid_synth_set_sample_rate

### ISSUE THREAD

**Issue by LordAro** [OpenTTD/OpenTTD#7885]
## Version of OpenTTD
master

## Expected result
Compiles without warnings

## Actual result
```
/home/lordaro/dev/openttd/src/music/fluidsynth.cpp:85:53: warning: ‘void fluid_synth_set_sample_rate(fluid_synth_t*, float)’ is deprecated [-Wdeprecated-declarations]
   85 |  fluid_synth_set_sample_rate(_midi.synth, samplerate);
      |                                                     ^
In file included from /usr/include/fluidsynth.h:97,
                 from /home/lordaro/dev/openttd/src/music/fluidsynth.cpp:16:
/usr/include/fluidsynth/synth.h:179:38: note: declared here
  179 | FLUID_DEPRECATED FLUIDSYNTH_API void fluid_synth_set_sample_rate(fluid_synth_t *synth, float sample_rate);
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## Steps to reproduce
Compile

From http://www.fluidsynth.org/api/synth_8h.html#ac89771633b393c807e5d5766f5a219b0 :
>As of fluidsynth 2.1.0 this function has been deprecated. Changing the sample-rate is generally not considered to be a real-time use-case, as it always produces some audible artifact ("click", "pop") on the dry sound and effects (because LFOs for chorus and reverb need to be reinitialized). The sample-rate change may also require memory allocation deep down in the effect units. However, this memory allocation may fail and there is no way for the caller to know that, because the actual change of the sample-rate is executed during rendering. This function cannot (must not) do the sample-rate change itself, otherwise the synth needs to be locked down, causing rendering to block. Esp. do not use this function if this synth instance is used by an audio driver, because the audio driver cannot be notified by this sample-rate change. Long story short: don't use it.

**Comment by nielsmh** [comment]
The annoying thing with this is that the setting needs to be set before creating the synthesizer, but the sample rate to use is only known after setting the music stream callback from the mixer. So the music callback needs to handle the situation where the synthesizer is not yet ready, which means a mutex and atomic flag are definitely needed.
