### ISSUE TITLE
[Request] Company rating via Server Admin Port

### ISSUE THREAD

**Issue by Hezkore** [OpenTTD/OpenTTD#7889]
I think it would be really useful if the server admin port was able to tell what company is leading according to the Company League Table found in-game.

![openttd_2020-01-01_04-44-13](https://user-images.githubusercontent.com/1727541/71637923-5f3c9380-2c51-11ea-8581-31fe7a9065fb.png)

The information could be stored inside the company class itself as the value `rating` or similar, along with the already existing values like `inaugurated` and `president`.

**Comment by nielsmh** [comment]
While theoretically any enhancements to the admin port ought to be made through Game Script custom messages, I agree that having the admin port more useful by default is not bad.

Anyone wanting to look at this can start here:
https://github.com/OpenTTD/OpenTTD/blob/90f4abe03f7c1e1abeae3b2a2b4a37dd6086ded6/src/network/network_admin.cpp#L312-L345

**Comment by marimeireles** [comment]
hey! I wanna work on this one :)

**Comment by nielsmh** [comment]
@marimeireles Nice, welcome :)

One thing to keep in mind if you extend the network protocol, there are existing software that works with the existing protocol, so any changes should aim to stay compatible. I think just adding new fields to the end of the existing message should be safe, but I'm not entirely sure. The alternative would be to define a new type of packet with the additional data.

**Comment by Hezkore** [comment]
> 
> 
> hey! I wanna work on this one :)

Any news?

**Comment by pon-droid** [comment]
If @marimeireles isn't working on it already, would it be alright if I could have a try?

**Comment by Hezkore** [comment]
> If @marimeireles isn't working on it already, would it be alright if I could have a try?

I think it's fair to say that @marimeireles isn't working on it, as is been two years heh.

**Comment by marimeireles** [comment]
Oops, sorry folks. Go for it!

**Comment by TrueBrain** [comment]
This information is already available in `COMPANY_ECONOMY`, as performance rating. You can just sort this list, and the one with the highest score is #1 in rating!

If you have any questions about this, do let us know!
