### ISSUE TITLE
Dedicated server crash

### ISSUE THREAD

**Issue by nikolas** [OpenTTD/OpenTTD#7893]
## Version of OpenTTD
1.10.0-beta2

## Expected result
No crash

## Actual result
(full log file attached below)
[crash.sav](http://nikolas.us.to/crash.sav)
[crash.log](https://github.com/OpenTTD/OpenTTD/files/4017964/crash.log)

```
[2019-12-31 12:56:55] dbg: [net] [udp] queried from 88.101.33.11                     
Crash encountered, generating crash log...                           
*** OpenTTD Crash Report ***                                                                                                                                                            
Crash at: Tue Dec 31 17:57:03 2019                                           
In game date: 2435-10-04 (36)                                    
                                                                     
Crash reason:                                                                  
 Signal:  Segmentation fault (11)                                            
 Message: <none>                                                           
                                                                                            
OpenTTD version:
 Version:    1.10.0-beta2 (0)
 NewGRF ver: 1a006d64
 Bits:       32
 Endian:     little
 Dedicated:  yes
 Build date: Dec 26 2019 21:55:08
```

## Steps to reproduce
I don't have reproduction steps.. I was just running a dedicated server and not playing on it for a while, then I saw that it crashed. Maybe the crash log and save files attached can give some clues.

**Comment by nielsmh** [comment]
Log shows it happened when someone in company 8 was removing a ship dock. Any chance of getting hold of the player and ask if they can remember which dock exactly?

**Comment by glx22** [comment]
A save from before the crash, with the dock present would probably help too.

**Comment by nikolas** [comment]
Yeah sorry, I don't have that.. this was a public game that I wasn't even a part of so I don't have the player's contact info. I don't have a save either, I will try to reproduce the crash with more info.

**Comment by Yexo** [comment]
Closing for lack of updates. Feel free to reopen if you experience this bug again or have more information.
