### ISSUE TITLE
Slow framerates with town list window

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7899]
## Version of OpenTTD
1.10.0-beta2
## Expected result
smooth framerate, 33 fps
## Actual result
2 fps
## Steps to reproduce
Generate a 4096x4096 map with High number of towns
Display town directory

![Unnamed, 1950-01-27](https://user-images.githubusercontent.com/43006711/71771605-d31eba80-2f35-11ea-9fa3-6c98af364f70.png)

**Comment by James103** [comment]
How many towns do you get when you generated a 4k * 4k map with "High" number of towns?

**Comment by SamuXarick** [comment]
When it was generating it said about 13k. Not sure if it generated that many.

**Comment by SamuXarick** [comment]
Found the faulty commit.
https://github.com/OpenTTD/OpenTTD/commit/196d586849684e62aa9a40093f2a1ce60e1cd53f

Found no issues when tested a build with the commit before this one.
