### ISSUE TITLE
"Show the NewGRF name in the build vehicle window" is missing the "On/Off" display.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#7908]
## Version of OpenTTD
12f4602

## Expected result
The setting reads: "Show the NewGRF name in the build vehicle window: On/Off".

## Actual result
The setting reads: "Show the NewGRF name in the build vehicle window".

## Steps to reproduce
1. Open Advanced Settings.
2. Expand "Interface".
3. Look at the setting described above.

![image](https://user-images.githubusercontent.com/37945304/71790123-5b639500-2ff4-11ea-9fa1-8be274225c1b.png)

**Comment by frosch123** [comment]
@stormcone Can you please take a look at this, this seems to be a regression from #7852.
