### ISSUE TITLE
Building docks does not account the cost of clearing the sloped tile

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#7945]
## Version of OpenTTD
1.10.0-beta2
## Expected result
Cost of dock + cost of clearing sloped tile
## Actual result
Cost of dock
## Steps to reproduce
Dock 1: Build a dock, see total cost
Dock 2: Clear sloped tile before building a dock, see total cost

**Comment by Yexo** [comment]
Change seems fine. There is a related issue that the cost of clearing a coastal tile is inconsistent:

Clearing normal grass: 15
Clearing coastal tile: 30
Clearing grass with single tree: 15
Clearing coastal tile with single tree: 15

Looks like we intend to add a little cost for the coast, but fail to do so when there are trees.
