### ISSUE TITLE
Normal screenshot mode may incorrectly show a huge screenshot warning dialog

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#7950]
## Version of OpenTTD
Since e558aa8ff461ddf660240c9ed209e7d2823f0b2b / 6dfe5c852eba98dd51d5ff7b65817113213e091f

## Expected result
Clicking "Normal Screenshot" does not show a "Huge screenshot" dialog, at any zoom level.

## Actual result
Clicking "Normal Screenshot" may show a "Huge screenshot" dialog at higher zoom levels, where the reported dimensions are the same as in the "Default zoom screenshot" case.
The actual size of the output screenshot does not match the large values reported in the "Huge screenshot" dialog, nor is the screenshot rendered at that resolution at any point.

## Steps to reproduce
Zoom fully out.
Select "Normal screenshot" from the screenshot window.
Observe the "Huge Screenshot" dialog.
Select "Yes".
Observe the output screenshot file.

**Comment by JMcKiern** [comment]
I'll have a look at it on the weekend if no one else gets around to it

**Comment by James103** [comment]
Could a very large monitor / display (as in a resolution of 12K, 11520 x 6480, or 6480p) still cause the huge screenshot dialog to pop up when taking a regular screenshot in full-screen? If that is the case, then the huge screenshot threshold will have to be eventually raised (currently at 8192p square = 67 million pixels) once 12K and 16K become the norm for high-end displays and monitors (i.e. several decades from now).

**Comment by JMcKiern** [comment]
It could, yeah. I guess it depends what the purpose of the dialog is. It might be just to warn the user that "this file will be a big one, don't be surprised if it takes a little time" rather than "this screenshot will be bigger than your monitor".

Either way, it's grand for now
