### ISSUE TITLE
When closing an interface window within the game whilst typing in Japanese with IME keyboard, the game crashes

### ISSUE THREAD

**Issue by oss-vineet** [OpenTTD/OpenTTD#7952]
## Version of OpenTTD
1.9.3

## Expected result
The program shouldn't crash

## Actual result
The program crashes

## Steps to reproduce
Not sure if something can be done about this but here goes:
I use the standard English keyboard, but since I need to use Japanese often, I have the Microsoft IME for Japanese downloaded. Two things to know: I have enabled the setting where right clicking on a box closes it, and I use the fonts `small_font = MS Gothic` & `medium_font = MS Gothic` in the `openttd.cfg` file so that Japanese shows up properly. So I'm playing normally, and I create one city. I start creating the next city, so I type the "Town name" in the "Town generation" box and I enter 2 characters in Japanese, but then I think Nah that city's not needed. Now if you have used the Microsoft Japanese IME keyboard, you would know it shows suggestions of different kanjis as a dropdown. While that dropdown box with kanji suggestions was active, I right clicked on the "Town generation" box (since I had decided that town was not needed). And right there, my game crashes. I hope this information is sufficient, attached are the dumps from the crash, thank you!
[crash.log](https://github.com/OpenTTD/OpenTTD/files/4091884/crash.log)

**Comment by glx22** [comment]
Confirmed.
