### ISSUE TITLE
Roadtype catenary not shown over bridges

### ISSUE THREAD

**Issue by danielplaumann** [OpenTTD/OpenTTD#7958]
## Version of OpenTTD
20200124-master-gf88ac83408

## Expected result
If a road type provides catenary graphics, they should be shown instead of default catenary.

## Actual result
The new catenary graphics are shown on normal tiles but not on bridge tiles. Instead, the default catenary is shown on bridges.

## Steps to reproduce
The attached grf defines catenary for ROAD (just a large red square) which shows the behaviour.
[catenarytest.grf.zip](https://github.com/OpenTTD/OpenTTD/files/4111817/catenarytest.grf.zip)

**Comment by nielsmh** [comment]
Screenshot using the attached test GRF:
![image](https://user-images.githubusercontent.com/1062071/74106926-5baefd00-4b6b-11ea-8ae8-0266d3ccfd17.png)

The bridge does indeed not use the red square catenary graphics.

**Comment by nielsmh** [comment]
I looked at this, and it will require an annoyingly large refactor of DrawRoadTypeCatenary to make it usable for bridge surfaces too.
https://github.com/OpenTTD/OpenTTD/blob/e340934d04a26a8917f23f73141556e85fbae0b1/src/road_cmd.cpp#L1370-L1427

The part in DrawBridgeRoadBit doesn't seem to have everything ready at least, and several of the parameters to DrawRoadTypeCatenary would have to be synthesized in some way.
https://github.com/OpenTTD/OpenTTD/blob/e340934d04a26a8917f23f73141556e85fbae0b1/src/tunnelbridge_cmd.cpp#L1167-L1190
