### ISSUE TITLE
Changelog for nightlies is empty

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/OpenTTD#7960]
## Version of OpenTTD
n/a

## Expected result
A changelog of the last 7 days

## Actual result
Empty file

## Steps to reproduce
https://www.openttd.org/downloads/openttd-nightlies/latest.html
Click "Changelog"
an empty file is presented

This is true for almost a year. The problem seems to be here:
https://github.com/OpenTTD/OpenTTD/blob/master/azure-pipelines/changelog.sh#L3

This is always true, so it thinks it is always a tag, and that logic there doesn't work on a non-tag. In result, the changelog is empty.

**Comment by James103** [comment]
A workaround would be to go into the GitHub commit history to view the changes, but some people may not want to go to Github just to see the changelog, which means this is still a bug that could be fixed.
