### ISSUE TITLE
Error in script error message for type mismatch

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#7966]
## Version of OpenTTD
Since d7a928a-windows-win32 (Windows 7 Ultimate)

## Expected result
"Your script made an error: parameter N has an invalid type A, expected: E"

## Actual result
"Your script made an error: parameter N has an invalid type (null), expected: A"
Where,
- N is the parameter number with the type mismatch
- A is the actual input type
- E is the type that the function or operation expects.

## Steps to reproduce
* Run the following code in an AI or Game Script: `ScriptController.Sleep([1,2,3])`
It will generate the above error with N = 1, A = "array", E = "integer".
* Run the following code in an AI or Game Script: `ScriptController.Sleep(2e9)`
It will generate the above error with N = 1, A = "float", E = "integer".
* Note that running "array(2e9)" will *not* generate the above error, instead, it will execute as normal, crashing the game in the process.

### Note
To anyone trying to reproduce this issue, please comment what result you got, as well as the version of OpenTTD, the OS, and whether it's 32-bit or 64-bit.

**Comment by glx22** [comment]
I tried both `ScriptController.Sleep()` steps and I get the expected result. No `(null)` in the message but the actual types(`'array'` and `'float'`).

**Comment by LordAro** [comment]
He's not specified, but from memory @James103 always runs a Win32 build for whatever reason. Could it be specific to that somehow?

**Comment by James103** [comment]
@glx22 What build did you attempt reproduction on (include the OpenTTD version, the OS, and whether it's 32-bit or 64-bit)?

**Comment by glx22** [comment]
I tried with 64-bit debug build of current master. But I can retry with 32-bit.

Edit: Ok bug confirmed for 32-bit.

**Comment by James103** [comment]
The following line is the root cause of the issue:
https://github.com/OpenTTD/OpenTTD/blob/11ab3c4ea2f6a6d29efda8c9ba2af04194621ea7/src/3rdparty/squirrel/squirrel/sqdebug.cpp#L125

**Comment by glx22** [comment]
Yes, it's because `nparam` is a 64-bit value
