### ISSUE TITLE
Crash in crash handler - Assertion failed at line 2981 of window.cpp

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#7970]
## Version of OpenTTD
Last tested: d7a928a-windows-win32 (Windows 7 Ultimate)

## Expected result
No crash in crash handler

## Actual result
Crash in crash handler - `Assertion failed at line 2981 of window.cpp: HasModalProgress() || IsLocalCompany()`
No crash log created (a crash in the crash handler does not produce a crash log).

## Steps to reproduce
??? (Seems to randomly occur, especially with starting new games, testing scripts, loading games, saving the config, etc.)

**Comment by LordAro** [comment]
Extremely difficult to tell what's happened here given just an assertion.

Looking at the code, this function is HandleMouseEvents. This is only called from InputLoop (which is guarded by the same assertion, so it can't be that), and then several places in the win32 video driver, which I must presume you're using. These places are all relating mouse button presses or movements, so I guess you might have more luck reproducing it with lots of those?

As for the failure itself, `HasModalProgress` is only true during grf scanning and world generation. `IsLocalCompany` is a check that `_current_company == _local_company`.  There's only a couple of places where this is specifically set to not be true - network commands (not relevant here), Script GameLoop function (also GS::SetCompany) and, oddly, (re)building a company HQ

Hopefully that helps you reproduce whatever's happening :) Ideally we'd fix the issue in the crash handler first, then fix whatever is causing the crash...

**Comment by LordAro** [comment]
Going to close this for now, as there's been no other instances of it, and no way of reproducing it either. Feel free to comment/request reopen if you come up with anything more concrete

**Comment by James103** [comment]
Tested on 2020-05-09 master:
1. Load the first savegame: [#4723 - original_savegame.sav](https://bugs.openttd.org/task/4723/getfile/7683/original_savegame.sav)
2. Do not return to the title menu.
3. Load the second savegame: [#4723 - crash.sav](https://bugs.openttd.org/task/4723/getfile/7678/crash.sav)
4. The game will crash with `Assertion failed at line 131 of d:\a\1\s\src\pathfinder\follow_track.hpp: ...` where what follows is a long if condition that may warrant splitting.
5. Click "OK" on the error message.
6. The game may crash with `Assertion failed at line 2981 of window.cpp: HasModalProgress() || IsLocalCompany()`. This assertion may repeat many times, causing OpenTTD to close anyway.

Note that this is on Windows 10 64-bit.

Additional valid reproduction steps.
1. Load the attached savegame: [#4723 - crash.sav](https://bugs.openttd.org/task/4723/getfile/7678/crash.sav)
2. Pause the game on load and stop all trains.
3. While the game is paused, go to one of the trains in the "Food Pick" station and make it skip the current order.
4. Unpause the game. The game will crash with `Assertion failed at line 131 of d:\a\1\s\src\pathfinder\follow_track.hpp: ...` where what follows is a long if condition that may warrant splitting.
5. Click "OK" on the error message.
6. The game may crash with `Assertion failed at line 2981 of window.cpp: HasModalProgress() || IsLocalCompany()`. This assertion may repeat many times, causing OpenTTD to close anyway

**Comment by glx22** [comment]
Ah yes it's when the mouse moves over openttd window while the crash dialog is open.
And `_current_company` is `OWNER_NONE` when the assert fails
https://github.com/OpenTTD/OpenTTD/blob/800ade77021b34adf8daa5ca5de0efaa8df24152/src/openttd.cpp#L1376-L1397 (pathfinding happens during `CallVehicleTicks()`

**Comment by JGRennison** [comment]
I've encountered this before, this commit https://github.com/JGRennison/OpenTTD-patches/commit/102405e0822194c03d49e3c3dc747143f711c6a4 is a mitigation.
