### ISSUE TITLE
Station coverage area stays visible sometimes even when turned off

### ISSUE THREAD

**Issue by ldpl** [OpenTTD/OpenTTD#7980]
## Version of OpenTTD
master

## Expected result
Coverage area is hidden when turned off.

## Actual result
Coverage area stays active.

## Steps to reproduce
0. Open station building window.
1. Build a station.
2. Move station selection window over that station.
3. Enable coverage area and mouse over existing station so that it coverage is shown.
4. Move cursor from station directly to the window.
5 . Turn off coverage highlight.

Crucial part is 4, if moved over map far enough coverage will disappear as expected.

![Screenshot from 2020-02-06 23-56-34](https://user-images.githubusercontent.com/413570/73978191-e5c54e80-493c-11ea-932d-183484dec2af.png)

**Comment by LordAro** [comment]
Connected stations make this a bit funky:
![](https://i.imgur.com/LnYhNyq.png)
