### ISSUE TITLE
Assertion failed at line 111 of src\core\pool_type.hpp

### ISSUE THREAD

**Issue by grv87** [OpenTTD/OpenTTD#7998]
## Version of OpenTTD
1.10.0-RC1

Operating system: Windows 10 x64

## Expected result
No error

## Actual result
Error:
```
Assertion failed at line 111 of src\core\pool_type.hpp:
index < this > first_unused
```

## Steps to reproduce
1. Load saved game:
[Basil Peace Transport, 2467-07-13.001.gz](https://github.com/OpenTTD/OpenTTD/files/4215491/Basil.Peace.Transport.2467-07-13.001.gz)
[Basil Peace Transport, 2467-07-13.002.gz](https://github.com/OpenTTD/OpenTTD/files/4215493/Basil.Peace.Transport.2467-07-13.002.gz)
[Basil Peace Transport, 2467-07-13.003.gz](https://github.com/OpenTTD/OpenTTD/files/4215494/Basil.Peace.Transport.2467-07-13.003.gz)
[Basil Peace Transport, 2467-07-13.004.gz](https://github.com/OpenTTD/OpenTTD/files/4215495/Basil.Peace.Transport.2467-07-13.004.gz)
[Basil Peace Transport, 2467-07-13.005.gz](https://github.com/OpenTTD/OpenTTD/files/4215496/Basil.Peace.Transport.2467-07-13.005.gz)
installing required NewGRFs
2. Play for some time.
I got the error after 1-5 minutes of play

`crash.log` and `crush.dmp` in archive:
[crash.001.zip](https://github.com/OpenTTD/OpenTTD/files/4215517/crash.001.zip)
[crash.002.zip](https://github.com/OpenTTD/OpenTTD/files/4215518/crash.002.zip)
[crash.003.zip](https://github.com/OpenTTD/OpenTTD/files/4215519/crash.003.zip)
[crash.004.zip](https://github.com/OpenTTD/OpenTTD/files/4215520/crash.004.zip)
[crash.005.zip](https://github.com/OpenTTD/OpenTTD/files/4215521/crash.005.zip)

**Comment by nielsmh** [comment]
Please attach the savegame directly to this ticket, don't link to third-party file upload sites. You may need to pack it in a ZIP file first.

**Comment by glx22** [comment]
crash.log and crash.dmp may help too

**Comment by grv87** [comment]
@nielsmh, @glx22, done.

GitHub doesn't accept files larger than 10M, so I used 7-Zip to split them. Also I had to rename. `crash.001.zip` was `crash.zip.001` after 7-Zip.
If you aren't able to unpack and open them, please, let me know, I'll try something else.

**Comment by glx22** [comment]
```
 	[Code externe]	
 	openttd.exe!raise(int signum) Ligne 516	C++
 	openttd.exe!abort() Ligne 71	C++
 	openttd.exe!error(const char * s, ...) Ligne 127	C++
 	[Cadre en ligne] openttd.exe!Pool<Company,enum Owner,1,15,1,0,1>::Get(unsigned __int64) Ligne 111	C++
 	[Cadre en ligne] openttd.exe!Pool<Company,enum Owner,1,15,1,0,1>::PoolItem<&_company_pool>::Get(unsigned __int64 index) Ligne 331	C++
>	openttd.exe!ScriptCompany::GetCompanyHQ(ScriptCompany::CompanyID company) Ligne 253	C++
 	[Cadre en ligne] openttd.exe!SQConvert::HelperT<int (__cdecl*)(enum ScriptDate::Date),0>::SQCall(void * func, int(*)(ScriptDate::Date)) Ligne 222	C++
 	openttd.exe!SQConvert::DefSQStaticCallback<ScriptDate,int (__cdecl*)(enum ScriptDate::Date)>(SQVM * vm) Ligne 827	C++
 	openttd.exe!SQVM::CallNative(SQNativeClosure * nclosure, __int64 nargs, __int64 stackbase, SQObjectPtr & retval, bool & suspend) Ligne 1188	C++
 	openttd.exe!SQVM::Execute(SQObjectPtr & closure, __int64 target, __int64 nargs, __int64 stackbase, SQObjectPtr & outres, unsigned __int64 raiseerror, SQVM::ExecutionType et) Ligne 798	C++
 	[Cadre en ligne] openttd.exe!sq_resumecatch(SQVM * v, int) Ligne 1023	C++
 	openttd.exe!Squirrel::Resume(int suspend) Ligne 326	C++
 	openttd.exe!ScriptInstance::GameLoop() Ligne 244	C++
 	openttd.exe!AI::GameLoop() Ligne 82	C++
 	openttd.exe!StateGameLoop() Ligne 1389	C++
 	openttd.exe!GameLoop() Ligne 1471	C++
 	openttd.exe!VideoDriver_Win32::MainLoop() Ligne 1264	C++
 	openttd.exe!openttd_main(int argc, char * * argv) Ligne 860	C++
 	openttd.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Ligne 442	C++
 	[Code externe]	
```
So one of the AIs triggered it

If the values available in debugger are correct it should be company 13, so RoadRunner v12

And I attach the log here for easier access
[crash-7998.log](https://github.com/OpenTTD/OpenTTD/files/4216380/crash-7998.log)
