### ISSUE TITLE
Base graphics set is missing 5 sprites

### ISSUE THREAD

**Issue by Limyx826** [OpenTTD/OpenTTD#7999]
## Version of OpenTTD
1.10.0-RC1

## Issue
The main menu show that the currently base graphics set is missing 5 sprites and ask to update. I check the online update and it was up to date. 

The base graphics set is OpenGFX. 

This message also shows up on aBase, zBase, and NightGFX graphics set. The only set where this message not shows up is the Original Windows TTD graphics. 

![SharedScreenshot4](https://user-images.githubusercontent.com/38696851/74524438-ffc4e980-4f59-11ea-82e3-8b37f72a807b.png)

**Comment by LordAro** [comment]
Yes, this is a known "issue", but not with OpenTTD. New sprites need to be drawn for OpenGFX before the 1.10 release. It's on our list and won't be forgotten, don't worry!

aBase, zBase & NightGFX are (entirely) 3rd party and it's up to the creators of those GRFs to update them accordingly

**Comment by Limyx826** [comment]
May I ask if there are new sprites, how is the original TTD graphics set being handle then?

**Comment by LordAro** [comment]
Because the "extra" sprites are distributed with OpenTTD by necessity. OpenGFX is ultimately just another base set GRF - it's not special like the original graphics are - and needs to be updated separately like all other base sets
