### ISSUE TITLE
Multiplayer -- Missing Train Engines

### ISSUE THREAD

**Issue by SiegeMstr** [OpenTTD/OpenTTD#8013]
## Version of OpenTTD
1.9.3
## Expected result
Mulitplayer Build Trains
## Actual result
Can only purchase train Cars, no engines available
## Steps to reproduce
Every Server I create has this issue

**Comment by FLHerne** [comment]
What is the start date? Normal rail locomotives become available after around 1925 in the Temperate climate, or 1945 in the others, and may not be available later in the game after being replaced by monorail and maglev.

Are you using any NewGRFs?

**Comment by SiegeMstr** [comment]
Using a vanilla download, changed the start year to 2020.

**Comment by glx22** [comment]
2020 may be too late

**Comment by SiegeMstr** [comment]
so its an ID10T error...

**Comment by glx22** [comment]
but you should have monorail and maglev engines available
https://wiki.openttd.org/Train_Comparison

**Comment by SiegeMstr** [comment]
no engines available, only cars. Can also only buy basic rails.

I will test starting game at default date in the next hour or so

**Comment by SiegeMstr** [comment]
Just got the chance to test....ID10T error confirmed
