### ISSUE TITLE
Crash log - after open, before server selection

### ISSUE THREAD

**Issue by TJ-1975** [OpenTTD/OpenTTD#8016]
[crash.log](https://github.com/OpenTTD/OpenTTD/files/4232950/crash.log)

## Version of OpenTTD 
1.9.3

## Expected result
Game opens, see main menu, with the choice of what servers to play on
![crash](https://user-images.githubusercontent.com/61294647/74977593-fd024280-53f8-11ea-97b2-117d291f1872.png)

## Actual result
Game opens, saw no servers, tried toggling between the two services, still saw no servers, game unexpectedly crashed, fatal exception, asked that I submit it here on github.

## Steps to reproduce
WAS UNABLE TO REPRODUCE.  GAME OPENED FINE FOR ME IMMEDIATELY FOLLOWING THIS.  I thought I would post the crash log just in case someone wanted to take a look at it.  Totally understand if this issue gets closed or deleted.

**Comment by LordAro** [comment]
This is a custom client (there's no "Select community" window in "actual" OpenTTD). Report the crash to wherever you downloaded the client from
