### ISSUE TITLE
"Check Online Content" lags the UI

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/OpenTTD#8024]
## Version of OpenTTD
1.10.0-RC1

## Expected result
Opening "Check Online Content" works like any other window.

## Actual result
Opening "Check Online Content" lags the crap out of the game. The title screen becomes sluggish, the mouse moves like it is on 2 FPS, etc.

## Steps to reproduce

Open "Check Online Content"

## More details
It seems that for every entry it adds to the list, it redraws the full UI. As the list is ~1300 entries long, and entries are being added one by one, this makes the UI become rather unresponsive.

An easy fix seems to be to not update the UI for every entry, as you cannot use the UI anyway during this time-of-lag.

**Comment by nielsmh** [comment]
Maybe set a timer (e.g. 250 ms) on the content window and check for a flag that gets set by the network receive code. Redraw if the flag is set.

**Comment by frosch123** [comment]
Mind that unoptimised builds spend a considerable amount of time on computing md5sums of savegames on your disk, to check which content you already have.

**Comment by TrueBrain** [comment]
Isn't that at boot? Anyway, the above problem also happens when there is only OpenGFX loaded.

**Comment by James103** [comment]
> Mind that unoptimised builds spend a considerable amount of time on computing md5sums of savegames on your disk, to check which content you already have.

This means that pressing `Check Online Content` can cause lots of disk activity, which may result in minutes-long hangs on some hard drives. Is there any way to cache/skip this intensive verification step if on a hard drive?

**Comment by LordAro** [comment]
In no way should OTTD have to care about your storage medium

**Comment by spnda** [comment]
Both Debug and Release builds don't show ANY disk usage on my drives.
And I think the window in general lags the game quite a bit. I get 30-40ms draw times in that window even after all the data has returned from the server and has been drawn.

**Comment by James103** [comment]
@spnda Did you test this without having any scenarios or savegames installed, or did you test with the scenarios and savegames installed? Did it come up with no disk usage either way, or is it that the presence of the scenarios and savegames is what causes the "Check Online Content" to trigger some disk activity?

**Comment by spnda** [comment]
> Did you test this without having any scenarios or savegames installed, or did you test with the scenarios and savegames installed?

I have 11 savegames installed and 2 scenarios.

> Did it come up with no disk usage either way, or is it that the presence of the scenarios and savegames is what causes the "Check Online Content" to trigger some disk activity?

Not exactly sure what you mean. My C: and E: drives (C: for documents and E: for the installation) show 0-1% (most of the time 0%, the 1% might be from other programs running simultaneously) disk usage when checking for online content. When checking for missing content in save games and scenarios it runs as smooth as it should, no issues there.
