### ISSUE TITLE
Crash when Reloading AI in single player

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#8037]
## Version of OpenTTD
1.10.0-RC1
## Expected result
Reload the AI
## Actual result
Crash when reloading AI in single player
## Steps to reproduce
Start only one AI in single player
Cheat and move to AI company
Let human company bankrupt.
Reload AI -> crash
[crash.zip](https://github.com/OpenTTD/OpenTTD/files/4351009/crash.zip)

**Comment by SamuXarick** [comment]
I can't reproduce this in 1.10.3 downloaded from openttd.org, but still asserts in master. Is it because asserts are disabled?

**Comment by James103** [comment]
When I do the following:
1. Start the first AI
2. Switch company cheat to AI company
3. Bankrupt human company
4. Start the second AI
5. Reload the first AI

Result: You are automatically switched over to the other AI company. Repeating steps 4-5 reproduces this result again.

**Comment by SamuXarick** [comment]
That's fine, I suppose. It tries to pick some other company to move you in.

This is where stuff happens:
https://github.com/OpenTTD/OpenTTD/blob/4f8e7b2a2b97475fa45a3117c63c91116a884703/src/economy.cpp#L291-L302

When there's only one AI company and no human companies, there is no other company to move to when the AI company is reloading. The assert then triggers (in master, but not in 1.10.3).

The Reload AI is located in AI Debug window. It runs 2 commands:
https://github.com/OpenTTD/OpenTTD/blob/4f8e7b2a2b97475fa45a3117c63c91116a884703/src/ai/ai_gui.cpp#L1288-L1293
- bankrupts company
- start company

**Comment by James103** [comment]
> The Reload AI is located in AI Debug window.

The same crash occurs if you write `reloadai 1`, `reloadai 2`, ... inside the console and hit enter to execute them.

**Comment by SamuXarick** [comment]
Got it.
https://github.com/OpenTTD/OpenTTD/blob/4f8e7b2a2b97475fa45a3117c63c91116a884703/src/console_cmds.cpp#L1236-L1241

**Comment by James103** [comment]
The same crash occurs when doing the following:
1. Start a dedicated server.
2. Server: Execute `startai`
3. Server: Execute `save a.sav`
4. Start a client instance.
5. Client: Open "Load Game" and navigate to where the newly saved `a.sav` is located.
6. Client: Load `a.sav`
7. Client: Open AI/GS Debug Window
8. Client: Hit "Reload AI"
9. Client: Crashes (same error as above)

**Comment by glx22** [comment]
So based on the steps, it crashes when you restart AI of a company with an active human player.
