### ISSUE TITLE
AIOrder.SetOrderFlags doesn't always work for ships

### ISSUE THREAD

**Issue by RailwAI** [OpenTTD/OpenTTD#8039]
## Version of OpenTTD
OpenTTD 1.10.0-RC1

## Expected result
When my AI creates a new freight service with ships from a ship depot (`location1`), via an oil rig (`location2`) to an oil refinery, it executes code similar to below when giving the ship (`vehicle`) its orders. After the following lines I would expect that the second order of the ship is marked as "full load any cargo".
```
AIOrder.AppendOrder(vehicle, location1, AIOrder.OF_NONE)
AIOrder.AppendOrder(vehicle, location2, AIOrder.OF_NONE);
AIOrder.SetOrderFlags(vehicle, 1, AIOrder.OF_FULL_LOAD_ANY)
```
Note that `location1` and `location2` contain a TileIndex. `vehicle` is the VehicleID of the ship.

## Actual result
The second order has no order flags that are visible in the order list of the ship. I'm not sure if it is related to the oil rig or to the ship. I know that similar code (with location1 and location2 being other stations/depots) does work properly with trains and trucks.

A workaround that works and I'll use for my AI is to change the code to
```
AIOrder.AppendOrder(vehicle, location1, AIOrder.OF_NONE)
AIOrder.AppendOrder(vehicle, location2, AIOrder.OF_FULL_LOAD_ANY)
```

## Steps to reproduce
Install RailwAI version 20 (I'll add a workaround in version 21), and wait until a freight route for ships is made. With the code in the file idea.nut I would expect it to set the order flag to.

**Comment by SamuXarick** [comment]
https://github.com/OpenTTD/OpenTTD/blob/6fde8547595c2ae99e823a8afd2bdcf7c094cffb/src/script/api/script_order.cpp#L262-L265
Problem is there! It's not checking for oil rigs

Somebody with time, the fix is replace that line with 
`if (IsTileType(t, MP_STATION) && (IsDock(t) || IsOilRig(t)) && GetStationIndex(t) == st->index) return t;`
Got no time atm to make a pr.

**Comment by SamuXarick** [comment]
This is also affecting AIOrder.GerOrderDestination
