### ISSUE TITLE
Unable to connect to content server

### ISSUE THREAD

**Issue by kirtangajjar** [OpenTTD/OpenTTD#8042]
## Version of OpenTTD
1.9.3
## Expected result
When I click "Check online content", it should show all the newgrf and scripts etc... 

## Actual result
It shows empty box for a while and then shows an error saying "Could not connect to content server". Even http://uk.binaries.openttd.org/index.html is showing be empty page.
 
## Steps to reproduce
Click "Check online content" from main menu

**Comment by James103** [comment]
Do you have a good internet connection?
I can still "Check Online Content" (no error messages) and even download stuff from there. I can still access openttd.org, account.openttd.org (including login), bananas.openttd.org, etc etc. But I can't access us.binaries.openttd.org or uk.binaries.openttd.org (they both return empty responses and no errors). What could be the cause?

**Comment by TrueBrain** [comment]
For user support please visit our forum (https://www.tt-forums.net). It is more likely someone can help you diagnose your problem there, as this is most likely an issue with your connection (firewall, etc). Please see if they can help you out. Thank you :)

BTW, the URL you mention is intentionally blank; a protection against illegal crawlers.
