### ISSUE TITLE
Scoring year is -1 when loading old savegame

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#8050]
## Version of OpenTTD
1.10.0-RC1
## Expected result
Set the old default scoring year
## Actual result
scoring year is -1
## Steps to reproduce
Load old savegame. I loaded "empty.sav", the regression savegame
![Unnamed, 1954-11-16](https://user-images.githubusercontent.com/43006711/77889048-210d3b00-7265-11ea-806e-733ed1725841.png)

**Comment by SamuXarick** [comment]
There's also another issue. Max year can go over 5000000:
- Set the scoring year to 5000000
- Start a game in 4999999
- Fast forward and it goes past 5000000

**Comment by SamuXarick** [comment]
There's yet another issue. Start year can be 0.
- Set the scoring year to Never
- Start a game in 0
- Fast forward and the score chart is shown

**Comment by LordAro** [comment]
as best as I can tell, _old_ending_year_slv_105 is never set, being left as default initialised to 0. The "old_ending_year_slv_105" setting has a default set to DEF_END_YEAR (2050, which is also wrong, as _old_ending... gets decremented before being used) but that's not being used at all.

I don't know enough about the settings system to know how the defaults are supposed to work...

**Comment by LordAro** [comment]
While we're in the same area, 
https://github.com/OpenTTD/OpenTTD/blob/71e79edfc1adaa4ea1e19d6ec87cb045ef7f69fe/src/highscore_gui.cpp#L186

could do with being changed to the settings year (the newspaper sprite is still wrong, but one thing at a time...)
