### ISSUE TITLE
Road Construction UI unavailable

### ISSUE THREAD

**Issue by Irokis** [OpenTTD/OpenTTD#8055]
If you start the game with Maximum number of road vehicles per company: 0, u cannot build any road, the button is just greyed out and disabled. If you go into settings while in that game and set the number of vehicles to 100, the road construction becomes available and u can build road, but if you go back into settings set the road vehicle limit back to 0 WITHOUT closing the ROAD CONSTRUCTION UI the game just crashes.

## Version of OpenTTD
openttd-1.10.0-windows-win64.exe

## Expected result
To be able to do road construction even tho the allowed road vehicle per company is set to 0

## Actual result
The road construction is greyed out, if road vehicle per company is set to 0. Also crashes OpenTTD if you leave the Road Construction UI on, while going into Settings to change road vehicles per company 100 -> 0.

## Steps to reproduce
1. Create any game with Limitations -> Maximum number of road vehicles per company: 0
2. Go into Settings while in the created game.
3. Find Limitations -> Maximum Number of road vehicles per company, set it to 100
4. Road Construction becomes available, select it, build some road whatever doesnt matter.
5. Do not close Road Construction UI.
6. Go back into Settings -> Limitations -> Maximum number of road vehicles per company, set it back 100 -> 0.
7. Game crashes.

**Comment by James103** [comment]
What exactly is the crash? If possible, can you please upload the crash report and dump file?

**Comment by Irokis** [comment]
[RoadUIcrash.zip](https://github.com/OpenTTD/OpenTTD/files/4428275/RoadUIcrash.zip)
The crash is that the whole OpenTTD just closes, no ERROR nothing.

**Comment by LordAro** [comment]
Crash now fixed, still need to address road building availability
