### ISSUE TITLE
Recognize NT 5.2 Service Pack 2 as supported in the installer

### ISSUE THREAD

**Issue by chungy** [OpenTTD/OpenTTD#8057]
## Version of OpenTTD

1.10.0

## Expected result

The installer to run without complaining about minimum operating system version requirements.

## Actual result

Installer complains that "You are trying to install [..] on Windows 95, 98, ME, 2000 and XP without SP3.", though it allows continuing past the warning.

## Steps to reproduce

Install the game on ReactOS. Presumably this also happens on Windows Server 2003 and Windows XP x64 Edition, though I haven't tested the latter two cases.

**Comment by nielsmh** [comment]
Any support for Windows XP level Windows API implementation is coincidental, it's not something we aim to run on. None of our core developers have the time to test on operating systems that aren't their primary, so if the installer claimed to support ReactOS but the game by chance uses some API missing and wouldn't run/crashed, we'd never know.

A pull request resolving this would be welcome, but I wouldn't expect anyone on the core team to come up with something.

**Comment by chungy** [comment]
> if the installer claimed to support ReactOS but the game by chance uses some API missing and wouldn't run/crashed, we'd never know.

It's not really about ReactOS even though that's where I noticed the issue. ReactOS itself aims to be and claims to applications that it is compatible with NT 5.2 SP2 (Windows Server 2003, XP x64). although from what I've seen, OpenTTD is fully functional, compatibility breaks are probably on ReactOS's part, not OpenTTD.

The main issue here is that the installer recognizes NT 5.1 SP3 (XP 32-bit) as compatible, and while NT 5.2 is a superset of API compatibility from that, the installer creates a warning when running on it.

Or maybe all Windows versions prior to some recent one (7?) are just untested and should be "unsupported" by OpenTTD. That would seem fair to me; it might happen to work, but without a guarantee of doing so.

**Comment by nielsmh** [comment]
Yes I should probably have written "anything earlier than Windows 7", I think that's the current intended target.

**Comment by glx22** [comment]
We just determine win9x or not using https://github.com/OpenTTD/OpenTTD/blob/e7b901462e6d3b0b31c9861191cbdfd2fcbfc7aa/os/windows/installer/install.nsi#L554-L572
And with #7270 the installer will be generated by CPack.

**Comment by TrueBrain** [comment]
Since CMake is merged, we no longer have a check like this anymore. So for our next release (1.11) this problem is resolved :)
