### ISSUE TITLE
Toggling "Full animation" first glitches, then reduces vertical size

### ISSUE THREAD

**Issue by tomstorey** [OpenTTD/OpenTTD#8067]
## Version of OpenTTD
1.9.3

## Expected result
None

## Actual result
The first time "Full animation" is toggled (on to off), the vertical screen size reduces slightly and the top of the screen (ala menu bar) is duplicated.

<img width="1440" alt="Screen Shot 2020-04-07 at 12 33 39" src="https://user-images.githubusercontent.com/7754310/78624137-3836d300-78cc-11ea-8a8a-f6bd50a4a5d9.png">

Subsequently, each time "Full animation" is toggled on and off, the veritcal screen size is reduced slightly, this can be done until the game is an unplayable slither on the screen.

![Prenfingpool Transport, 6th Feb 1954](https://user-images.githubusercontent.com/7754310/78624625-6b2d9680-78cd-11ea-9628-368da7643fe2.png)

Exiting and then re-entering full screen restores the full vertical size again.

## Steps to reproduce
On Mac OS X, open game and go to full screen. Toggle "Full animation" repeatedly.

**Comment by andythenorth** [comment]
Got a repro of this. 10.0 official binary. macOS 10.15.1 Catalina.

Happens in full-screen mode only.  Cannot repro in windowed mode.

There was a previous incidence of this bug which was visible in windowed mode.  I haven't looked yet if/how that was fixed, but I haven't seen that one happen for quite some time

**Comment by tomstorey** [comment]
I wasn't able to repro in windowed mode either. Unfortunately I wasn't able to test 1.10.0 as it's not starting on my Mac (crash on start).
