### ISSUE TITLE
Streetcar track removal fails when bank balance negative

### ISSUE THREAD

**Issue by bfut** [OpenTTD/OpenTTD#8068]
## Version of OpenTTD
20200407-master-gd50e4641ae
## Expected result
Removing streetcar track generates income, e.g. €156.
## Actual result
Removing streetcar track issues error, e.g. "Not enough cash - requires -€156", when bank balance is negative, but generates income when bank balance is positive. Haven't checked bank balance equal to zero.

## Steps to reproduce
1. Start new game, making sure to load a tram NewGRF. Tested with Fake Subways + other NewGRFs, and vanilla + CZTR Tram set)
2. Build streetcar tracks.
3. Reduce bank balance until negative.
4. Attempt removing streetcar track, see screenshot.
![Screenshot from 2020-04-08 13-42-21](https://user-images.githubusercontent.com/34510704/78781540-bd8bb780-79a0-11ea-80aa-194c9b078b9e.png)

Note: may be related to #7656, even though not a duplicate

**Comment by James103** [comment]
Can reproduce in 1.10.0 stable, tried removing tram track on both normal road and bridges. Only occurs if current bank balance (negative) plus removal cost (positive) < 0.

**Comment by TrueBrain** [comment]
Thank you @James103 for that final remark ("Only occurs if current bank balance (negative) plus removal cost (positive) < 0."). Took me a while to reproduce :D I was balancing in the in-between at first, not being able to reproduce :D Bug confirmed, fix incoming :)
