### ISSUE TITLE
Check Online Content displays too much

### ISSUE THREAD

**Issue by Goury** [OpenTTD/OpenTTD#8070]
## Version of OpenTTD
1.10.0

## Expected result
Go grab some cool mods

## Actual result
Got ton of outdated crap that crashes the game

## Steps to reproduce
Click "Check Online Content", do suffer and get sad.

Once cool and very nice feature became completely useless nowdays since there's a lot of content yet no way to sort it by version compatibility or popularity/rating/anything.  
Not only that, but the library is bloated with obsolete and deprecated entities that only make things harder.  
Proposition: at least do automated testing of all and every piece of content and filter out faulty ones per game version.  
Also clean up decade old smelling garbage from there.  
Also something like user tags would be nice to have.  
Sorting by review rating is my dream at this point.

**Comment by LordAro** [comment]
We're working on redoing bits of the BaNaNaS (content server) backend, so things should be improving "soon". Quite likely, you'll be able to report bugs on specific content having its metadata set incorrectly (e.g. versions) and that can be improved.

Setting version compatibility of items has been somewhat wonky for a while, which means there's rather more displayed than perhaps should be (though there's plenty that's already being filtered out). This should be improving with the updates.

Anything that crashes the game should be reported as such. No 3rd party content should be able to crash the game and any that do is a bug.

Reviews... I can't see them happening anytime soon

**Comment by andythenorth** [comment]
Thanks for this!  I don't think anybody disagrees that the content list can be overwhelming, but no viable solution has ever been found.  We try and keep the number of issues low to keep the project tidy and fun to work on.  Therefore I'm going to close this one, as it is unlikely to result in a change.  Thanks for contributing!
