### ISSUE TITLE
Vehicles renewing and new technologies

### ISSUE THREAD

**Issue by jpsouzamatos** [OpenTTD/OpenTTD#8071]
When a new version of a vehicle is released, the old vehicles are always autorenewed in the old technology, so if you want to prevent the autorenew in the old technology, so you need to buy a Hereford Leopard, copy the orders of MPS Regal and sold the old car but this process is tedious. It would the nice to have a configuration to allow autorenew in new released technologies.
## Version of OpenTTD
1.9.3

**Comment by glx22** [comment]
You can use [autoreplace](https://wiki.openttd.org/Autoreplace#Autoreplace) for that

**Comment by jpsouzamatos** [comment]
> You can use [autoreplace](https://wiki.openttd.org/Autoreplace#Autoreplace) for that

Thank you very much. I wasn't aware that this was an already existing feature.
