### ISSUE TITLE
Toll

### ISSUE THREAD

**Issue by jpsouzamatos** [OpenTTD/OpenTTD#8077]
It would be nice to have a feature to make competitors that use your roads automatically pay tolls every time that use another company's roads to prevent the Free-rider problem.

**Comment by auge8472** [comment]
Is there really a "free-rider-problem"? I never heard of it. As anyone else can use your streets you can use anyone elses streets as well. So there are equal conditions for everyone and I *as an external observer* see no "problem".

That said, you'll find patchpacks including the [Infrastructure Sharing Patch](https://www.tt-forums.net/viewtopic.php?f=33&t=42254) (IS). The patch provides an implementation of the requested feature. A currently well maintained patchpack, that includes IS, is [JGRPP](https://github.com/JGRennison/OpenTTD-patches) ([project thread](https://www.tt-forums.net/viewtopic.php?f=33&t=73469) on TT-Forums).

**Comment by embeddedt** [comment]
As far as I know, the JGR version of infrastructure sharing charges you while you are loading/unloading in a station, but not while you're just driving on the road.

**Comment by agentw4b** [comment]
"Highway Toll Game Script" charges highways

**Comment by andythenorth** [comment]
Thanks for this.  There have been many suggestions and patches for infrastructure sharing and/or tolls, but none that have been completed so far.  It's a frequent request that is unlikely to be met. 

So I'm closing this request as we try to keep the issue count low for OpenTTD, it helps us focus on things that are important and fun. Feel free to discuss in irc or request re-opening if you disagree. Thanks for contributing!
