### ISSUE TITLE
Wrong station is added to the train's orders when clicking on a station.

### ISSUE THREAD

**Issue by DonaldDuck313** [OpenTTD/OpenTTD#8080]
## Version of OpenTTD
1.9.3

## Expected result
When I click on a train's order list and then on "go to" and then on a station, it should add that station to the train's order list.

## Actual result
It adds another, seemingly random, station to the train's order list instead.

## Steps to reproduce
1. Open the saved game that can be downloaded [here](https://gofile.io/?c=b8H2kL)
2. Open train 40's order list
3. Add Grönälv to train 40's order list
4. It will add Trollbro instead

![](https://i.ibb.co/G3BztKv/Open-TTD-1-9-3-2020-04-11-18-03-14.gif)

**Comment by nielsmh** [comment]
This is a known bug in 1.9.3, and no other versions. It's fixed in 1.10.0.
