### ISSUE TITLE
Add currency Unit - Indian  Rupee

### ISSUE THREAD

**Issue by Aswn** [OpenTTD/OpenTTD#8083]
I know that we can add a custom currency unit, but would prefer if the option for Indian Rupee (INR) was available for the player to choose.

**Comment by EgyLynx** [comment]
You can name WHATEVV ER almost  C... maybe just coins...

Intresting... why not?

**Comment by ilayaraja97** [comment]
I added INR but I'm confused on what should be the conversion unit. Can someone help? And I'll raise a pull request.

**Comment by FLHerne** [comment]
If you mean the exchange rate, it's relative to GBP.

It looks like roughly 90 INR == 1 GBP in the last few years?

**Comment by ilayaraja97** [comment]
Okay sure 90 it is :)

**Comment by FLHerne** [comment]
Really, just pick something that makes the in-game prices look about the right size of number to you. ;-)
.
OpenTTD doesn't simulate changes in exchange rate over time, so it'll never be historically accurate.

**Comment by ilayaraja97** [comment]
Created PR fixing this issue #8136

**Comment by ilayaraja97** [comment]
> Really, just pick something that makes the in-game prices look about the right size of number to you. ;-)
> .
> OpenTTD doesn't simulate changes in exchange rate over time, so it'll never be historically accurate.

Would be interesting though. Like imported trains will cost according to the currency and whatnot.
