### ISSUE TITLE
Feature suggestion: option to automatically space out vehicles in a shared order

### ISSUE THREAD

**Issue by twpol** [OpenTTD/OpenTTD#8095]
## Version of OpenTTD

1.10.0

## Expected result

A single-click option to space out vehicles evenly, which is particular useful for road vehicles carrying passengers/mail around towns.

## Actual result

You need to:

1. Already have all the vehicles going around the route, so they game knows which order they're running in
1. Fully timetable the route, which means "Autofill" and waiting for that vehicle to go around once
1. Add a small bit of slack somewhere, lest they be stuck forever delayed
1. Control-click "Start date"
1. Manually select the expected arrival date shown for the first order
1. Click "Set date"
1. Keep a constant eye out for vehicles which are delayed and stuck behind another vehicle which is on time

And then, if *anything* changes about the route, number or type of vehicles, you have to repeat the whole process from the top.

## Notes

This is probably a resurrection of #5354, and something I have wanted since before the timetable feature arrived. :)

I have an algorithm worked out and have been poking around the code, so I think this is a very achievable feature that will make many people happy.

**Comment by sheepo99** [comment]
If you already have an algorithm planned, I'd say finish something that's workable first, and then submit a PR. That's the best way of obtaining feedback and of testing whether or not this is feasible.

**Comment by techgeeknz** [comment]
JGRPP has this feature, along with automatic timetabling. If you're happy with the way they work there, and there is sufficient interest in adding this feature, it may be possible to isolate the patches and port them to mainline.

**Comment by twpol** [comment]
I am amused as "JGR" are my initials too, but I've already written all the code for this feature. I am in the testing and tidying-up phase.

**Comment by techgeeknz** [comment]
> I am amused as "JGR" are my initials too

Two JGRs working on the same project? What are the odds, @JGRennison?

**Comment by JGRennison** [comment]
That is quite a coincidence. :)

The implementation in my branch is based on this one: https://www.tt-forums.net/viewtopic.php?p=1140899#p1140899, it's not something I came up with myself, though I have fixed/extended various bits of it.

There are many patches which do this sort of thing already on the forum, it's probably worth having a browse to see what's been done before for background context.

**Comment by twpol** [comment]
I've created PR #8342 and cleaned up all reviewer feedback and the compile warning, is there anything else I can do here to help progression?

**Comment by MrSmoke** [comment]
Any progress on this? Looks like https://github.com/OpenTTD/OpenTTD/pull/8342 hasn't been updated in 6 months 😢

**Comment by twpol** [comment]
> Any progress on this? Looks like #8342 hasn't been updated in 6 months 😢

Sorry for the lack of progress. I have resumed work in the PR now: https://github.com/OpenTTD/OpenTTD/pull/8342#issuecomment-1859291523

**Comment by 2TallTyler** [comment]
Since you now have a PR to follow your progress, I'm closing this issue to clean up the bug tracker a bit. 😃
