### ISSUE TITLE
commands redirected to other stations 

### ISSUE THREAD

**Issue by koala12345** [OpenTTD/OpenTTD#8096]
## Version of OpenTTD
1.9.3.
## Expected result
When I click on a bus station while I am giving commands, the bus should have this station in commands.
## Actual result
When I try to give a command to a bus, it is commanded to totally different station.  I click on a station in city Colchester, the bus is directed into Upminster or any other station, changing randomly. It happened to 15th bus going from this station, all of the others were OK. The stations are properly connected, it works just fine when I copy the command from another bus. 
## Steps to reproduce
Build a map with several trains and busses going to the train stations.

**Comment by James103** [comment]
Known issue in 1.9.3 only (#7789). Update to 1.10.x or above to fix the problem you are having.

**Comment by koala12345** [comment]
Thanks
