### ISSUE TITLE
The transfer value in "Transfer: £[number]" can be negative.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8098]
## Version of OpenTTD
1.10.0 (2fee030a26996a167adbf28f96fca8c4fd749005) and 20200426-master

## Expected result
"Transfer: £[nonnegative value] / Income: £[number]"
"Transfer: £[nonnegative value] / Cost: £[number]"
"Transfer: £[nonnegative value]"
## Actual result
"Transfer: £[negative value] / Income: £[number]"
"Transfer: £[negative value] / Cost: £[number]"
"Transfer: £[negative value]"

![image](https://user-images.githubusercontent.com/37945304/80296459-14cfad00-8741-11ea-8178-34b0bf304d6a.png)

## Steps to reproduce
Load the title game as a normal game, watch and observe.

**Comment by nielsmh** [comment]
I don't see why this is necessarily a bug.

https://github.com/OpenTTD/OpenTTD/blob/e45bccb83347bd0b36ae0915b6874e440f1c9164/src/economy.cpp#L1211-L1231

The transfer virtual payment is calculated as the difference in the cargo packet's potential earnings so far on its route, and the earnings it would have gotten for a non-stop route from its origin to the current unload point, over the total number of transit days so far. If the packet is significantly slower, or moves backwards relative to the origin, on a hop, then that difference in potential earnings can become negative.

**Comment by Yexo** [comment]
As explained in the last comment, this is working as expected.
