### ISSUE TITLE
Empty game runs too slow on Windows

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8100]
## Version of OpenTTD
1.10.0 and 20200426-master

## Expected result
```
Simulation rate: ~33 fps (expected 33.33 fps)
Graphics frame rate: ~33 fps (expected 33.33 fps)
```
or
```
Simulation rate: ~30 fps (expected 30 fps)
Graphics frame rate: ~30 fps (expected 30 fps)
```

## Actual result
```
Simulation rate: ~30 fps (expected 33.33 fps)
Graphics frame rate: ~30 fps (expected 33.33 fps)
Game speed factor: ~0.90x
```
CPU, GPU usage is <10% and tick times are <1ms (on an i5-9400F running at ~1.5 GHz)
![image](https://user-images.githubusercontent.com/37945304/80307265-8d5c5b00-878d-11ea-9deb-1b2a0bf1ced5.png)

## Steps to reproduce
On a fast enough computer, perform the following:
1. Open a new game.
2. Open the FPS window (Help > Show frame rate)
3. Observe the stats

**Comment by nielsmh** [comment]
OS? Game resolution? Screen resolution? Blitter? Multimonitor or single monitor? Any OS colour management in effect?

**Comment by James103** [comment]
Here is my OpenTTD config:
[openttd-cfg.txt](https://github.com/OpenTTD/OpenTTD/files/4535284/openttd-cfg.txt)

Win 10 Home, 1080p (single-monitor)

**Comment by nielsmh** [comment]
Can you try joining a multiplayer game on a remote server, ideally on a small-ish map with no or very few other players, and check what framerate you get?
Also see if the simulation seems to be playing catch-up in some way, e.g. appears to run normally (or slightly slow) and then suddenly run several frames at once.

In multiplayer mode the game should lock on to the server's rate and run that regardless of the timing otherwise used in local play. For that reason you will often see 32.9 fps on Windows in local play, but 34 fps on the same Windows machine joined a server running on Linux.

**Comment by nielsmh** [comment]
Also, try running a dedicated server on your own machine (run openttd.exe with the `-D´ commandline switch) and check what the rate it with the fps command. If the rate then is correct, try joining the server and see if that affects the rate.

**Comment by James103** [comment]
Running a dedicated server and connecting to it returns framerates anywhere from 25 to 28 frames per second (average of 26 fps), or about 75-80% normal speed (average of 78%).
![image](https://user-images.githubusercontent.com/37945304/80307966-f2b24b00-8791-11ea-8803-f4f960ee9d4e.png)

Additionally, "Brodong's OpenTTD Sandbox" runs at almost exactly 1/2 speed, or about 17 ticks per second.

**Comment by nielsmh** [comment]
Is this a portable or a desktop computer? If it's a portable, is it running on battery power or on charger?

Can you try screenshotting (or recording) the Game loop total timing graph on that multiplayer server where the game runs half speed?

**Comment by James103** [comment]
Static image including last 5 seconds of game ticks:
![image](https://user-images.githubusercontent.com/37945304/80308197-2772d200-8793-11ea-8bfa-bf48d84b9947.png)

The computer is a full desktop computer with no noticeable battery, but the CPU speed adapts to the load. The higher the load, the higher the CPU speed (up to 3.9 GHz).

**Comment by James103** [comment]
I can't seem to reproduce this. I'm getting 32-33 fps on an empty game, on Windows 10 Home 10.0.18363 Build 18363. Therefore, I will close for now.
