### ISSUE TITLE
Installer does not say that Windows 8 and 10 are supported.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8102]
## Version of OpenTTD
1.10.1 on Win 10

## Expected result
Installer says that Windows 8 and 10 are supported.
"OpenTTD 1.10.1 for Windows XP, Vista, 7, 8, and 10"

## Actual result
Installer does not say that Windows 8 and 10 are supported.
"OpenTTD 1.10.1 for Windows XP, Vista, and 7"

## Steps to reproduce
1. Uninstall OpenTTD.
2. Reinstall OpenTTD from the installer.
3. Look at the OS version component of the "OpenTTD 1.10.1 for ...".

**Comment by orudge** [comment]
It'd probably be better if it just says "Windows XP and higher" or similar.

**Comment by duckfullstop** [comment]
I'll put a PR in for this in a sec, seems simple enough.
