### ISSUE TITLE
SDL2 : Fullscreen to Window

### ISSUE THREAD

**Issue by BeWorld2018** [OpenTTD/OpenTTD#8104]
## Version of OpenTTD
Last version 1.10.1

## Steps to reproduce
When OpenTTD opened in fullscreen, when switch to window, impossible to resize window

## solution (maybe)
let SDL_WINDOW_RESIZABLE with FULLSCREEN
You can delete condition :
https://github.com/OpenTTD/OpenTTD/blob/master/src/video/sdl2_v.cpp#L265

flags |= SDL_WINDOW_FULLSCREEN | SDL_WINDOW_RESIZABLE;

Thanks

**Comment by glx22** [comment]
Maybe @nikolas can look at it

**Comment by nikolas** [comment]
Thank you for the report! I will take a look this weekend.
