### ISSUE TITLE
Desync related to diagonal track next to dock end

### ISSUE THREAD

**Issue by Yexo** [OpenTTD/OpenTTD#8119]
## Version of OpenTTD
1.10.1, also head as of https://github.com/OpenTTD/OpenTTD/commit/bc8333723ccf0ea5e889a6bc412c89ea623138bc

CmdBuildRailroadTrack does not keep the 'is dockable' tile status bit intact. (CmdBuildSingleRail does). This can easily lead to a desync.

To reproduce, load the attached savegame. The ship is able to dock at Benfingford Docks. When you remove/rebuild the diagonal tracks, the ship can no longer dock. Any client that connects after rebuilding the tracks will instantly desync since the ship can still dock on the client.

[desync.zip](https://github.com/OpenTTD/OpenTTD/files/4589685/desync.zip)

**Comment by frosch123** [comment]
Looks like various calls to SetDockingTile must be replaced with calls to CheckForDockingTile. The latter also updates the station's area.

**Comment by LordAro** [comment]
This is likely the desync-immediately-after-join seen by @ldpl in #8093

**Comment by glx22** [comment]
Quick test using the provided savegame and desync debug

```
cmd: 000ade87; 09; 00; 0006cf; 000006cf; 00000000; 0dd3004b; "(null)" (CmdClearArea)
station docking mismatch: station 0, company 0
cmd: 000ade8a; 43; 00; 0006cf; 00000000; 00000005; 0e600002; "(null)" (CmdBuildSingleRail) station docking mismatch: station 0, company 0
cmd: 000ade8c; 39; 00; 0006cf; 00000000; 00000005; 0e610003; "(null)" (CmdRemoveSingleRail)
cmd: 000ade8e; 11; 00; 0006cf; 00000000; 00000005; 0e600002; "(null)" (CmdBuildSingleRail)
station docking mismatch: station 0, company 0
```

**Comment by glx22** [comment]
Desync still happens when destroying (not removing) the diagonal rail track in the attached save
