### ISSUE TITLE
"Unable to find local depot" on dead-end tram tracks (regardless of location)

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8123]
## Version of OpenTTD
20200504-master

## Expected result
When ordered to go to depot, the tram stops at the depot.

## Actual result
An error message appears.
![image](https://user-images.githubusercontent.com/37945304/81351868-e203ae00-908a-11ea-95ad-e2f9c513dc8f.png)

This appears to be specific to trams only. Does not occur with road vehicles or trains.

## Steps to reproduce
1. Load a tram newGRF.
2. Build a tram depot and tram tracks as shown.
3. Buy and start any tram.
4. Wait until tram is on a dead-end tram track tile.
5. Order the tram to go to depot.

**Comment by ilayaraja97** [comment]
I do want to try this issue but I couldn't figure out how the path finding is done. :)

**Comment by James103** [comment]
Most likely still occurs as of 53a3d940b15ca2e769b4db19079b3b6913c48647 (and none of the JGRPP commits fixed it) - tried with same reproduction steps.

Also, I checked each of the diffs in the recent commits, and none of the later commits in the master branch touched any road vehicle pathfinder code.
