### ISSUE TITLE
Stations being visited against instructions.

### ISSUE THREAD

**Issue by Mysteron347** [OpenTTD/OpenTTD#8126]
1.10.1

Expected: Train "A" in attached scenario I expect to follow instructions : Go to Nat King Coal, then Newcastle.

Actual: Train "A" visits Old King Coal (and loads), then Natalie Wood (despite being unable to load/unload) and then Nat King Coal and Newcastle.

Steps: Run scenario.
[test2.zip](https://github.com/OpenTTD/OpenTTD/files/4603430/test2.zip)

**Comment by nielsmh** [comment]
Use the "non-stop" orders flag if you want a vehicle to not stop at any other station before it reaches the one in the order. The default without non-stop is to stop at any station the vehicle passes through. This is by design.

**Comment by Mysteron347** [comment]
Certainly - thanks. Using a standby machine whilst my usual is in intensive care, so new installation needing modified setup.
