### ISSUE TITLE
Mexican Stand-off

### ISSUE THREAD

**Issue by Mysteron347** [OpenTTD/OpenTTD#8128]
Version 1.10.1

Result: Allowing the scenario to run, train "B" and "C" stop, facing each other. Ditto "D" and "E".
Reversing "B" will trigger "C" to use clear path - whether "B" is moving or stopped. "D" has to be reversed until it resumes its original direction of travel by taking the loop - only then will "E" start.

Expected: Both "C" and "E" should take the alternative path without "B" / "D" needing to reverse.
[test2.zip](https://github.com/OpenTTD/OpenTTD/files/4603521/test2.zip)

**Comment by nielsmh** [comment]
Initial situation:
![image](https://user-images.githubusercontent.com/1062071/81476238-1c975300-9211-11ea-9fd0-61b3d4f6fc02.png)

If I remove the opposite-facing (two-way) path signal on the passing track, a train chooses a route through it:
![image](https://user-images.githubusercontent.com/1062071/81476261-4e101e80-9211-11ea-8105-45618dac5d9d.png)

It looks like the PF does not want to reserve a path through an opposite-facing path signal.

Note that your design goes against the usual recommendations, and against prototypical railroad design. Your path signals on the single-line segments of the network are what I would consider unsafe, as they can allow a train to wait in a position where it can deadlock with trains wanting to pass the opposite direction.
The following setup works:
![image](https://user-images.githubusercontent.com/1062071/81476470-63d21380-9212-11ea-9a3d-5aa930bbdc17.png)

**Comment by Yexo** [comment]
While it's possible to tweak the pathfinder costs so it doesn't cause this particular deadlock, in general that's not possible. What happens here is that the cost of going around is higher than the cost of the train standing still on the tracks in front of it (the small train length has a large influence here to make that cost low). The PF makes the assumptions that trains in front of it will eventually move, and in this case it thinks that going around is more expensive than waiting.

You can resolve this on your tracks by not allowing trains to stop where they would be blocking other trains. If the South-east signal was not present for example, the train couldn't have stopped there and would have gone to the bypass route directly.

Closing this as it doesn't seem feasible to make code-changes to prevent such situations.
