### ISSUE TITLE
Missing bounding boxes for bridge pillars of height 1 cause graphical glitches

### ISSUE THREAD

**Issue by Andrew350** [OpenTTD/OpenTTD#8131]
## Version of OpenTTD
Any
## Expected result
Pillars are displayed over objects underneath bridge
## Actual result
Objects are displayed over pillars
## Steps to reproduce
This issue is described with pictures in this post by Quast65: https://www.tt-forums.net/viewtopic.php?p=1231775#p1231775

I'm not sure if there's a reason for this omission or it is simply an oversight/original behavior, but either way it doesn't look right so I wanted to bring it to your attention.
 
Search history reveals a lot of issues with sprite sorting in the past but I didn't find anything about this particular issue, so hopefully this isn't just a compromise arising from an earlier fix.

**Comment by ilayaraja97** [comment]
What objects can I place? To recreate the issue?

**Comment by Andrew350** [comment]
The city objects set is a good one (available on Bananas)

Just to further highlight the issue, the lack of a bounding box can even cause objects _behind_ the pillars to overlap them (as shown in the image below), so it isn't just an issue of improperly set bounding boxes on the objects.
![Binpool Transport, 03_28_19303](https://user-images.githubusercontent.com/50259667/81585527-259b3800-9369-11ea-9af0-a434edf40bcf.png)

**Comment by ilayaraja97** [comment]
For the pillar of small bridges the code uses the function `DrawGroundSpriteAt()` and I believe the layering is done by which sprite is called first, by calling the `AddChildSpriteToFoundation()`.

Now that is why the white line is coming over the pillar and the grey _foundation_ is coming below. We need to change this behavior to fix this.

I am thinking if the `AddChildSpriteToFoundation()` adds like a priority queue so that a higher priority can be given to pillars and the rest will be first call first rendered.

**Comment by ilayaraja97** [comment]
> For the pillar of small bridges the code uses the function `DrawGroundSpriteAt()` and I believe the layering is done by which sprite is called first, by calling the `AddChildSpriteToFoundation()`.
> 
> Now that is why the white line is coming over the pillar and the grey _foundation_ is coming below. We need to change this behavior to fix this.
> 
> I am thinking if the `AddChildSpriteToFoundation()` adds like a priority queue so that a higher priority can be given to pillars and the rest will be first call first rendered.

I figured changing the `DrawGroundSpriteAt()` is much more tougher than just giving small pillions the same treatment as big pillions. So my PR is treating small and big pillions the same.
