### ISSUE TITLE
Loading savegame from 1.10.1 fails: ”Wrong owner for station tile”

### ISSUE THREAD

**Issue by hpiirai** [OpenTTD/OpenTTD#8142]
## Version of OpenTTD
20200512-master-gd15c7dbdeb

## Expected result
Savegame created in OpenTTD 1.10.1 can be loaded in this version.

## Actual result
Load fails with error message ”Wrong owner for station tile”.

![image](https://user-images.githubusercontent.com/45715592/81662363-2229ae80-9446-11ea-809a-92b8a7837936.png)

## Steps to reproduce
Try to load this savegame from 1.10.1 in the current master version: [savegame.zip](https://github.com/OpenTTD/OpenTTD/files/4614486/savegame.zip)

**Comment by SamuXarick** [comment]
The tile is a buoy placed on sea. GetTileOwner is OWNER_WATER, but base station -> owner is OWNER_NONE
