### ISSUE TITLE
Roadtype speed limit values are doubled in scenario editor drop-down menu

### ISSUE THREAD

**Issue by Andrew350** [OpenTTD/OpenTTD#8155]
## Version of OpenTTD
master-20200517
## Expected result
Speed limits are displayed correctly
## Actual result
Speed limits are not displayed correctly
## Steps to reproduce
 - Load any roadtype NewGRF with speed limits (RattRoads is shown below)
 - Observe speeds shown in the scenario editor menu vs everything else

![screenshot#1](https://user-images.githubusercontent.com/50259667/82158597-c2fcdd00-983d-11ea-9ba2-198156f691cb.png)

The doubling effect only appears on this drop-down menu and does not appear to affect anything functionally; it is merely cosmetic and limited to the scenario editor.

**Comment by James103** [comment]
I believe I saw that even before 1.10.0 while I was modifying the Cindini scenario with roadtype NewGRFs.

**Comment by Yexo** [comment]
https://github.com/OpenTTD/OpenTTD/blob/2514f43909b08c62a9e34703bcdbb89081faef9c/src/road_gui.cpp#L1321 (toolbar in normal game) has rti->max_speed/2 while https://github.com/OpenTTD/OpenTTD/blob/2514f43909b08c62a9e34703bcdbb89081faef9c/src/road_gui.cpp#L1362 (toolbar in scenario editor) shows simply rti->max_speed.

**Comment by James103** [comment]
So just a simple copy-paste error / typo in code?
