### ISSUE TITLE
Problem OpenTTD

### ISSUE THREAD

**Issue by Ufiby** [OpenTTD/OpenTTD#8161]
## Version of OpenTTD
master-20200517 and master-20200518
## Expected result
does not start the game, causes an error
## Actual result
should not be with errors, runs the game without a problem
## Steps to reproduce
download from the official OpenTTD website
![Problem](https://user-images.githubusercontent.com/46504018/82294685-34ac6680-99b7-11ea-849d-d9c41dab11e1.jpg)

**Comment by glx22** [comment]
It's caused by #8154, but I don't see why yet.

**Comment by glx22** [comment]
Ok I found it, it's an EOL issue.
