### ISSUE TITLE
Crash when loading stupid roadtypes newgrf

### ISSUE THREAD

**Issue by FLHerne** [OpenTTD/OpenTTD#8166]
## Version of OpenTTD
1.10.1

## Expected result
No crash

## Actual result
OpenTTD crashes after clicking 'Generate' in the new game dialog.

## Steps to reproduce
Load the attached GRF and start a new game.

The grf is a quick hack while trying to reproduce OpenTTD/nml#147 and is probably severely buggy in some way, but shouldn't be able to crash the game.

Crash log:
[crash.log](https://github.com/OpenTTD/OpenTTD/files/4669704/crash.log)

Stupid grf:
[roads-test.zip](https://github.com/OpenTTD/OpenTTD/files/4669716/roads-test.zip)

**Comment by FLHerne** [comment]
The grf fails to define a label for the roadtypes. When adding a label, OpenTTD refrains from instantly crashing.

**Comment by glx22** [comment]
Indeed a newgrf should not crash the game.

**Comment by FLHerne** [comment]
The issue doesn't occur with a roughly-identical railtype grf.
