### ISSUE TITLE
It takes two actions to move your company HQ by one tile.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8168]
## Version of OpenTTD
Since several years ago, last tested on 1.10

## Expected result
You can move your company HQ by one tile in one action, and it costs the same as if you were to move it multiple tiles.

## Actual result
It takes two actions to move your company HQ by one tile. Therefore, it costs 2x as much to move your company HQ by one tile than it is to move it by multiple tiles. This is because attempting to move your company HQ by one tile results in "company headquarters in the way" even though the original HQ will be demolished when successfully moved.

## Steps to reproduce
1. Build company HQ.
2. Attempt to move it by one tile in a single action.

**Comment by Andrew350** [comment]
I can't reproduce this on 1.10.1 or latest master. I get an error message but the HQ doesn't get demolished, even with magic bulldozer enabled. Does this happen only in a special case? Is there another step you forgot to mention?

**Comment by glx22** [comment]
That's the issue @Andrew350, to move it 1 tile you need to move it to another location first else you get the error message. So you need to move it 2 times.

**Comment by Andrew350** [comment]
Hmm, ok, the way the last sentence is phrased made it sound like something else. Nevermind me, carry on :)

**Comment by TrueBrain** [comment]
What a cute little bug you found, that has even annoyed me several times over the years :D
