### ISSUE TITLE
No trains past diesel models?

### ISSUE THREAD

**Issue by mintyface** [OpenTTD/OpenTTD#8172]
I can't access any of the trains after the final diesel model is released. When I get asked if I want a year's exclusivity and click "Yes", I still can't purchase that train.

Version 1.10.1 Windows 10

**Comment by James103** [comment]
What in-game year are you in? Are you using any Game Scripts? If so, which Game Script?

**Comment by Yexo** [comment]
Make sure you build electric rails and an electric rails depot, you can't build electric trains in a non-electrified depot. To do so: when clicking the rail button on the main toolbar, keep your mouse pressed and select "electric rail" from the dropdown menu.

**Comment by Yexo** [comment]
Closing for lack of response and suspected no bug. Feel free to reopen if you have extra information and this turns out to be a real bug.
