### ISSUE TITLE
cmake: make install DESTDIR="something" ignores GLOBAL_DIR option

### ISSUE THREAD

**Issue by Nik-mmzd** [OpenTTD/OpenTTD#8204]
## Version of OpenTTD
Git commit 90e849198fbac0136ca9bb9149e53f25265eeab5
## Expected result
OpenTTD files being installed to selected GLOBAL_DIR
## Actual result
OpenTTD files being installed to DEFAULT_GLOBAL_DIR
## Steps to reproduce
`cmake -DGLOBAL_DIR="/custom/global/dir" path/to/sources && make && make install` (in my case, `make install DESTDIR="path/to/install"`)

Maybe I did something wrong?

System: Arch Linux, cmake 3.17.2

PS can't find an option like old `--binary-name`; and does it still create a .desktop file at `install` step?
PPS Options list in COMPILING.md for cmake newbies like me maybe?

**Comment by glx22** [comment]
Based on https://cmake.org/cmake/help/v3.17/envvar/DESTDIR.html and https://cmake.org/cmake/help/v3.17/variable/CMAKE_INSTALL_PREFIX.html, I guess, with your steps, openttd is installed in "path/to/install/usr/local" 
I think the right way to set a custom install dir is to invoke cmake with `-DCMAKE_INSTALL_PREFIX="path/to/install"`

And I think there's indeed an issue with DEFAULT_GLOBAL_DIR, it doesn't respect OPTION_INSTALL_FHS

**Comment by Nik-mmzd** [comment]
> I guess, with your steps, openttd is installed in "path/to/install/usr/local

And this is what I'm trying to do. My problem is "I can't rename openttd GLOBAL_DIR to make it not collide with release version to have both compiled-from-git and release versions at same time"

@glx22 can you investigate this problem? I need this to be solved to be able to update [AUR openttd-git](https://aur.archlinux.org/packages/openttd-git) package
So I need to set GLOBAL_DIR to something like `${CMAKE_INSTALL_PREFIX}/share/openttd-git` (to avoid conflicts with `openttd` package)

**Comment by glx22** [comment]
GLOBAL_DIR is not used for install, it's only a define for openttd executable.
I think what you need is a way to configure XXX_DESTINATION_DIR in https://github.com/OpenTTD/OpenTTD/blob/8ef3d8f584fdc97c02bdc25e6d13d4c8bb4251ff/cmake/InstallAndPackage.cmake#L2-L12

**Comment by Nik-mmzd** [comment]
> GLOBAL_DIR is not used for install, it's only a define for openttd executable.

So, as far as I understand, if I will compile OpenTTD with -DGLOBAL_DIR="/games/openttd" and will install it (to /usr/local/games/openttd, because of defaults) OpenTTD will not be able to find it's own files? Seems like a bug

> I think what you need is a way to configure XXX_DESTINATION_DIR

Yes, it'll be useful. Maybe, unify some variables like GLOBAL_DIR (make it dependent on DATA_DESTINATION_DIR)
Also, seems to be missing an option to rename man page, etc...

In some words: reimplement configurable `binary-name`, `data-dir`, `doc-dir` from old build script

**Comment by glx22** [comment]
GLOBAL_DIR must be a full path, not a relative. Anyway I'll check how to use cmake GNUInstallDirs module.

**Comment by Nik-mmzd** [comment]
GLOBAL_DIR="${CMAKE_INSTALL_PREFIX}${DATA_DESTINATION_DIR}" maybe? Or smth like it

**Comment by glx22** [comment]
Please test #8218, it may not be complete but should improve things.

**Comment by Nik-mmzd** [comment]
@glx22 Seems to be working, except one thing: man page name is always "openttd"
