### ISSUE TITLE
Vehicles not sorted by cargo capacity when filtering specific cargo

### ISSUE THREAD

**Issue by SHADOW-XIII** [OpenTTD/OpenTTD#8205]
## Version of OpenTTD
1.10.2

## Expected result
Ships ordered by cargo capacity of the cargo I am checking/filtering through

## Actual result
Wrong order of ships when sorting is set as by cargo capacity

## Steps to reproduce
Install FISH 0.9.2
(Tested in 1970s) Visit ship depot,
Set "Sort by" (Descending) as "Cargo capacity": top 3 ships: 1080 aluminium ore, 800 passengers, 720 aluminium
Now change cargo filtering to "Oil": top 3 ships: 1080000 litres, 467000 litres, 720000 litres (same ships as above)

Changing "Sort by" filter does nothing. The list is using original vehicle cargo amount, ie. pre-refit option. Post-refit values are ignored.

Tested with ships only, might affect all types. Not sure if any other ordering type (other than cargo capacity) is also affected

**Comment by 2TallTyler** [comment]
This was also reported in #9584, and that issue explains why this can't (easily) be fixed.
