### ISSUE TITLE
It is possible to get a "Cost: £0" float from autoreplace.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8216]
## Version of OpenTTD
1.10.2

## Expected result
When a vehicle is replaced by another vehicle, and the value of the old vehicle is equal to the total purchase/refit price of the new vehicle, no "Cost: £0" float appears.

## Actual result
When a vehicle is replaced by another vehicle, and the value of the old vehicle is equal to the total purchase/refit price of the new vehicle, a "Cost: £0" float appears.
![image](https://user-images.githubusercontent.com/37945304/84421948-e53a0e80-abe1-11ea-9f27-3ea85db0a848.png)

## Steps to reproduce
1. Install a NewGRF that provides multiple vehicles at the same price (such as £0 as provided by Eyecandy road vehicles GRF).
2. Build a road vehicle depot.
3. Build a vehicle whose price is £0 (such as "Police car").
4. In "Replace vehicles", select the vehicle, and select it to be replaced with another vehicle with a price of £0 (such as "Ambulance"). Hit the start replace button. Do not hit the replace button in the depot.
5. Start the vehicle.
6. Reverse the vehicle.
7. Let it go back into the depot and get replaced.
8. You should see a "Cost: £0" float when the vehicle is replaced.

**Comment by andythenorth** [comment]
Thanks!

Is there a specific rationale for why this should be shown?

**Comment by James103** [comment]
I think this is not intended. In all other unique places so far, no "Cost: £0", "Income: £0", or "Transfer: £0" float is produced. Additionally, if the cost of autoreplace is £0, the money check is skipped, but the "Cost: £0" float still displays.

**Comment by andythenorth** [comment]
Sounds like a valid consistency issue.
