### ISSUE TITLE
No error message subtitle for if no bridge types available for target length < max bridge length

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8221]
## Version of OpenTTD
1.10.2

## Expected result
The error message should appear with any of the following subtitles:
* "...bridge too long" (same as if bridge was over the length limit specified by "Max bridge length")
* "...no bridge types available" (new message)

## Actual result
The error message ("can't build bridge here") does not render a subtitle.

## Steps to reproduce
1. Install and load the NewGRF "Expensive, Short, and Slow Bridges" (pb_bridges.grf).
2. Also install and load an early vehicle NewGRF (such as eGRVTS 2).
3. Set "Max bridge length" to 64 tiles or more.
4. Start a game in between 1890 and 1950.
5. Try to build a bridge greater than ~14 tiles long. It will fail but the error message will not have a subtitle.

Alternative steps to reproduce:
1. Download the scenario "Trans-Siberian Railway (1890)".
2. Select the scenario from within the "Play Scenario" menu and let it download any missing NewGRfs.
3. Start the scenario.
4. Try to build a bridge greater than ~14 tiles long. It will fail but the error message will not have a subtitle.

**Comment by aruscher** [comment]
> 1. Install and load the NewGRF "Expensive, Short, and Slow Bridges" (pb_bridges.grf).
> 2. Set "Max bridge length" to 64 tiles or more.
> 3. Start a game in 1890.
> 4. Try to build a bridge greater than ~14 tiles long. It will fail but the error message will not have a subtitle.

Can't reproduce bug by following these steps due to "No vehicles unavailable". However can confirm the bug for the alternative steps. 

Edit: Can also confirm the bug following the original steps but starting in year 1950.
