### ISSUE TITLE
Sidewalk trees don't have transparency

### ISSUE THREAD

**Issue by wsfsbvchr** [OpenTTD/OpenTTD#8242]
Below are screenshots of the same spot in normal view, with transparency options enabled and with everything set to invisible. The issue should be evident.

![ottd_transparency1](https://user-images.githubusercontent.com/61580558/85920897-79fa6880-b880-11ea-8a9c-691713d56c30.png)
![ottd_transparency2](https://user-images.githubusercontent.com/61580558/85920898-7c5cc280-b880-11ea-8e30-b92f69ae459b.png)
![ottd_transparency3](https://user-images.githubusercontent.com/61580558/85920899-7ebf1c80-b880-11ea-8d1a-fc539170dd46.png)

**Comment by LordAro** [comment]
OTTD issue, not OGFX, i've moved the issue
