### ISSUE TITLE
Possible duplication of functionality in `screenshot.cpp`

### ISSUE THREAD

**Issue by techgeeknz** [OpenTTD/OpenTTD#8252]
## Version of OpenTTD
Since e04ca904a9455afc63aa87db775fe4463ab899b7

The introduction of the minimap screenshot feature appears to be duplicating functionality that will be used elsewhere for drawing the widgets within the minimap window; specifically, the `GetMinimapOwner` function is very likely to be replicating functionality used by the _owner information_ overlay of the minimap window.

## Expected result
We shouldn't have multiple codepaths that perform substantially similar functions.

**Comment by sauntheninja2** [comment]
I would like to work on this issue but how would you eliminate duplication here?

**Comment by phyrik** [comment]
Hi, I'd also like to work on this if possible.

It looks like ```GetMinimapOwner``` in ```screenshot.cpp``` returns the Owner based on the tile given, and that is then used in ```MinimapScreenCallback``` to get the colour of the tile. This code seems to have been duplicated from ```GetSmallMapOwnerPixels``` in ```smallmap_gui.cpp```, which returns the colour of the tile for the small map, with very little difference.

This could possibly be put into a new file, or an existing one, tasked with getting a colour for a specific world tile, which both the screenshot file and small map file could use instead.

I'm new to open source and OpenTTD development so please let me know if I got anything wrong or if there's a better solution!

**Comment by TrueBrain** [comment]
I honestly suspect none of the devs really looked into it, as that most likely would also result in a solution :P But what you describe sounds good, but we won't really know till we see the code :D

I would say, just give it a spin, and make a Pull Request when you think it is done. We take it from there :)

As for new file or existing, I would go with an existing one. Finding a good place might be a bit tricky, but between the 500+ files we have I am sure it fits in one of them :D

**Comment by phyrik** [comment]
Thanks for the very quick response!

Yep, I'll try and work on a proper coded solution and open a PR when I think it's ready, as well as try to find somewhere the code could go.

**Comment by pon-droid** [comment]
Is it all good if I work on this issue ? I might not start this month since I have some stuff going on though.

**Comment by 2TallTyler** [comment]
No need to ask permission. Just do it and open a Pull Request. 🙂
