### ISSUE TITLE
Very large company values are not graphed correctly

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8253]
## Version of OpenTTD
master (2020-07-01)

## Expected result
* Company value of 2^63-1 is recorded on the company value graph.
* Company value of e.g. 2^63-10000 is recorded on the company value graph, with data points being visible.
* The scale in these cases runs from 0 to 2^63-1.

## Actual result
* Company value of 2^63-1 is not recorded on the company value graph at all (scale still runs from -5 to 4).
![image](https://user-images.githubusercontent.com/37945304/86307343-279cad00-bbdc-11ea-9c8c-8e703d909335.png)

* Company value of e.g. 2^63-10000 is still recorded on the company value graph, but the points do not appear.
![image](https://user-images.githubusercontent.com/37945304/86307414-561a8800-bbdc-11ea-9562-889cb039d5d0.png)

* The scale runs from 0 to (2^63-1)/10 (~922 billion million) instead of from 0 to 2^63-1 (~9.22 trillion million).
(see above images)

## Steps to reproduce
1. Load the attached savegame.
2. Fast forward a few years. The money (and company value) will max out.
3. Open the company value graph. It appears blank.
4. Open your company finances window, and hit the "Borrow £10,000" button a couple of times.
5. Fast forward a few months.
6. Take a look at the company info window and company value graph.
7. Hit the "Repay £10,000" button until the loan has been repaid.
8. Take a look at the company info window and company value graph.

## Savegame
[Gronnway Transport, 363576-09-15.zip](https://github.com/OpenTTD/OpenTTD/files/4861520/Gronnway.Transport.363576-09-15.zip)
(The savegame contains a single company with maxed-out (2^63-1) company value and cash, and has been optimized to run at up to several in-game years per second on high-end modern hardware.)

**Comment by TrueBrain** [comment]
You are an absolute madman to make a savegame for this and clear steps to reproduce :D Awesome, tnx :)

**Comment by LordAro** [comment]
The first part's quite fun - the graphing code uses INT64_MAX as "INVALID_DATAPOINT" . Of course, if it actually gets that value, it just ignores all the data.

https://github.com/OpenTTD/OpenTTD/blob/1e529e16329b905e625bb69cc501edbc478186bc/src/graph_gui.cpp#L39

A hacky fix might be to use INT64_MIN as a sentinel value, but I'd say that in real world conditions one is no less likely to appear than the other, so probably wouldn't actually fix anything

I'm not quite sure about the second issue. The `y` value that it's trying to draw the datapoint at is a very small negative number. I suspect it has something to do with the bitshifting of the very large datapoints to create the "x million" value

https://github.com/OpenTTD/OpenTTD/blob/1e529e16329b905e625bb69cc501edbc478186bc/src/graph_gui.cpp#L437-L457

**Comment by TrueBrain** [comment]
I really do not know why I just spend 2 hours fixing this bug. It is so unlikely for anyone to ever hit it in any real (or sane) game .. but there we go :P

It was a collection of problems starting when you were `~2**31 / 10` away from the max ... and hopefully soon they are all part of the past.

Please stop abusing OpenTTD :P (nah, it is okay; it was a fun little bug, that escalated into the madness of how compilers and computers actually work. I learnt things today :D)
