### ISSUE TITLE
Chat history

### ISSUE THREAD

**Issue by abmyii** [OpenTTD/OpenTTD#8270]
Is there a way to view messages after they fade away (i.e. chat history)?

**Comment by ldpl** [comment]
Yes, press ~ (or whatever key  you have left of 1) or choose "toggle console" from ? menu. It will open the console that, among other things, includes chat history.

**Comment by abmyii** [comment]
Ah I see it - though I had to use (`). Are there plans for a dedicated "chatbox"?

**Comment by abmyii** [comment]
One annoyance is that the hotkeys override the chat.

**Comment by abmyii** [comment]
> Ah I see it - though I had to use (`). Are there plans for a dedicated "chatbox"?

Or to have the last 5/10 messages shown when the chat is opened regardless of the time since they were sent.

**Comment by LordAro** [comment]
In general, there are no plans for anything until someone makes it :)

However, hotkeys overriding the chat (when the chat window is open) sounds like a bug (There was a similar one when SDL2 support was first introduced)

As this "issue" has been solved, I'll close this

**Comment by abmyii** [comment]
Thanks for the info! Shall I make new issue(s) - one for the chatbox and another for the bug?

**Comment by LordAro** [comment]
I think just one for the bug - include as much information about your system as you can.

The chatbox suggestion (last n messages) seems like a good idea, but in general we don't like "suggestions" as issues

**Comment by abmyii** [comment]
Just to clarify, I had the chatbox opened, but unfocused - I was selecting a rail and was trying to type the letter `c` but instead the upgrade tool was selected. I don't think it's a bug, but it is quite annoying. A possible solution would be that `Shift+Enter` opens a chatbox which captures all input, though a dedicated chatbox is probably an ideal long-term solution.
