### ISSUE TITLE
Stopped vehicule destination should be red when mouse over

### ISSUE THREAD

**Issue by SylvainDevidal** [OpenTTD/OpenTTD#8272]
## Version of OpenTTD
Lastest trunk

## Expected result
When moving the mouse over the status bar of a stopped vehicule, it displays the vehicle destination.
The destination color is blue, the same as when the vehicule actually run. This give impression the vehicule actually restarted, and the user may click again to stop it... so the vehicule restart can may crash (for trains by exemple).
To avoid confusion, IMO the destination color should be red, so the player don't think the vehicule restarted.

## Actual result
Destination color is blue and it's confusing.

## Steps to reproduce
Stop a vehicule.
Move the mouse over it's status bar: the (very little thin) red cross remains, but the status bar shows destination in blue the same when than when the vehicule is running.

**Comment by nielsmh** [comment]
This is regarding the change from #7772.

**Comment by TrueBrain** [comment]
So that was what has been annoying me lately .. I couldn't figure out what I found weird and wrong ... tnx :D
