### ISSUE TITLE
[Small compile issue] wrong name for bin/

### ISSUE THREAD

**Issue by rubyFeedback** [OpenTTD/OpenTTD#8294]
Hey there openttd devs,

I use a hybrid system that is similar to GoboLinux. Without going into all details,
I compile into versioned AppDirs.

For the latest openttd I would use:

    /home/Programs/Openttd/1.10.3/

Upon compiling this, I noticed that directory was created:

    /home/Programs/Openttd/1.10.3/games/

In that directory the binary called **openttd** was placed.

I believe this is wrong. The directory name should be bin/
which would conform to the FHS; at the least it would make
versioned appdirs a bit simpler.

It's not a big deal so if you guys want to, you can keep on
arbitrarily calling it "games/" (even though, technically,
there is only a single file, a binary, inside, so I am not sure
why the name is "games/" - I assume the assumption by
whoever wrote the code is that everyone would have
a /usr/games/ directory which makes no real sense to 
me, but hey). Actually I was not sure if I should even
report it since it seems so minor, but the good thing about
minor problems is that they are simple to fix. Please
feel free to close this issue at any moment in time.

**Comment by LordAro** [comment]
In the master branch we now use a cmake-based system which fixes many of the oddities of our old configure script. Can you try building and installing with that and see if it produces a more acceptable result?

**Comment by TrueBrain** [comment]
Hi @rubyFeedback ,

We haven't heard back from you; did you try out our latest `master` to see if this fixes your problem? We now let CMake do all the magic, so hopefully that is more FHS-compatible :)

I am going to close this issue for now; if you find that `master` did not solve the issue, feel free to reopen! Tnx!
