### ISSUE TITLE
Non-latin text language not showing in mac os

### ISSUE THREAD

**Issue by ecolortest** [OpenTTD/OpenTTD#8296]
## Version of OpenTTD
jgrpp-0.35.1-H3be17758
## Expected result
should show the text
## Actual result
![Screen Shot 2020-08-20 at 21 32 29](https://user-images.githubusercontent.com/34646054/90771319-1182b180-e32e-11ea-8ed3-410fa1c6613f.png)

## Steps to reproduce
change to any non-latin language (korean, chinese, japanese, and more...)

**Comment by James103** [comment]
Do you have the required fonts? If so, are you able to reproduce this in vanilla? If not, this should be forwarded to [JGRennison/OpenTTD-patches](https://github.com/JGRennison/OpenTTD-patches).

**Comment by standaniels** [comment]
This may be related, I'm redirected from https://github.com/JGRennison/OpenTTD-patches/issues/188.

## Version of OpenTTD
nightly (openttd-20200902-master-g53a3d940b1)

## Expected result
Font face and alias settings are effect rendering text.

Screenshot of OpenTTD 1.10.3:
![92921899-3225bf00-f435-11ea-9f8e-398e5026ccdb](https://user-images.githubusercontent.com/1199737/92961082-f60f5000-f46e-11ea-8edc-afa9552dcec3.png)

## Actual result
Font face and alias settings seem te be ignored while rendering text.

Screenshot of OpenTTD nightly (openttd-20200902-master-g53a3d940b1):
<img width="487" alt="image" src="https://user-images.githubusercontent.com/1199737/92961240-3a9aeb80-f46f-11ea-822a-5eca49b227e6.png">

## Steps to reproduce
Set the following font values:

```
small_font = SF Pro Text Medium
medium_font = SF Pro Text Medium
large_font = SF Pro Text Medium
mono_font = SF Mono Medium
small_size = 12
medium_size = 13
large_size = 18
mono_size = 12
small_aa = true
medium_aa = true
large_aa = true
mono_aa = true
```

[Full openttd.cfg file.](https://github.com/OpenTTD/OpenTTD/files/5210972/openttd.cfg.txt)

**Comment by TrueBrain** [comment]
@standaniels : good news, this recently has been fixed! Thank you for the report :)

@ecolortest : we haven't heard back from you. I am going to assume it is because you didn't have custom fonts loaded. If I am wrong, and after following the configuration snippet @standaniels gave it is still not working, feel free to re-open this ticket!

Thank you both!

**Comment by melekhine** [comment]
Same with Russian, and I have not idea how to run it in English instead system language
OpenTTD 1.10.3

**Comment by glx22** [comment]
With 1.10.3 you need to [set fonts in openttd.cfg](https://wiki.openttd.org/en/Archive/Manual/Settings/Unicode) (you can also change language there if needed). But please also try 1.11.0-beta1, it should use fallback fonts provided by OS (at least on windows).
