### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by valisak** [OpenTTD/OpenTTD#8298]
## Feature requests
1. Hi, is it possible to add a train length in the purchase list? Some GRFs have different train and wagon lengths. It would make the exchange easier.
2. Prevent another company from deleting the sign

**Comment by James103** [comment]
I assume you are on the latest version of OpenTTD (1.10.3), is that correct? Both feature requests are also not implemented in JGRPP 0.34.4 (and by extension JGRPP 0.35.1).

**Comment by valisak** [comment]
Yes 1.10.3. I do not support JGRPP

**Comment by LordAro** [comment]
Hi! Thanks for your interest in the project. To keep the issue list clear and focused, we generally don't keep feature requests here. As such I will be closing this. Other feature requests may go on the [suggestions forum](https://www.tt-forums.net/viewforum.php?f=32)

I do like the train length in purchase list idea, though fitting it into an already very full window might be tricky...
