### ISSUE TITLE
OpenTTD does not find GM.CAT when named uppercase.

### ISSUE THREAD

**Issue by ipatix** [OpenTTD/OpenTTD#8313]
## Version of OpenTTD
OpenTTD 1.10.3

## Expected result
When I copy the GM.CAT file from the DOS version to get the original music it should be detected when named uppercase.

## Actual result
The game does not find GM.CAT and does not show the music set in the settings.

## Steps to reproduce
Pretty much what the title says: Copy the GM.CAT file from the original DOS version to the baseset/ folder. Probably only happens on Linux since Windows is case insensitive.

So what confused me most about this is that GM.CAT is clearly mentioned as uppercase in the README.md while the game is looking for a file in lowercase. Either it should be mentioned correctly in the README.md or the game should look for both filenames.

**Comment by RuinTD** [comment]
Yeah, this issue doesn't occur on Windows. I checked the baseset descriptions and it would appear that these files have incorrectly capitalized filenames:
- [`orig_dos.obm`](https://github.com/OpenTTD/OpenTTD/blob/master/media/baseset/orig_dos.obm) (DOS Music)
- [`orig_tto.obm`](https://github.com/OpenTTD/OpenTTD/blob/master/media/baseset/orig_tto.obm) (TTO Music)
- [`orig_win.obg`](https://github.com/OpenTTD/OpenTTD/blob/master/media/baseset/orig_win.obg) (Windows Graphics)
- [`orig_win.obm`](https://github.com/OpenTTD/OpenTTD/blob/master/media/baseset/orig_win.obm) (Windows Music)
- [`orig_win.obs`](https://github.com/OpenTTD/OpenTTD/blob/master/media/baseset/orig_win.obs) (Windows Sounds)

As defined by both the [readme] and the original games' file structures, the DOS files should be uppercase and the Windows files should be lowercase; and as defined by just the [readme], the TTO file should be uppercase.

[readme]: https://github.com/OpenTTD/OpenTTD#143-original-transport-tycoon-deluxe-music

**Comment by ipatix** [comment]
Thanks!
