### ISSUE TITLE
Strong temporal autocorrelation in Max. Reliability ratings across vehicles

### ISSUE THREAD

**Issue by Afdill** [OpenTTD/OpenTTD#8325]
## Version of OpenTTD
v1.9.0 - 1.10.3

## Expected result
An assortment of random maximum reliability ratings so there is endgame variety in vehicle choice.

## Actual result
Max. reliability is temporally autocorrelated across large groups of vehicles.  Vehicles with introduction dates only several years apart will tend to vary in their max. reliability ratings by only one or two percentage points.

## Steps to reproduce
Can be observed by starting up a game past all introduction dates (year 2100 or so), sorting vehicles by introduction date and observing max. reliability.  Pattern is most readily observed with large vehicle set newGRFs such as NUTS and eGRVTS, but can be see with default vehicles as well.

## Why this is a problem for people who play with breakdowns on
Making dense vehicle networks with poor vehicle reliability is undesirable even with the best vehicle servicing.  Depending on the random seed, this could be really nice: every single vehicle in a 50-year introduction span might be 95-100% max. reliable.  **Or it can be game-ruining bad: every single vehicle in a 50-year introduction span might have reliability in a 75-80% range.**  If the latter happens your game is essentially ruined and requires a full map re-roll in hopes of getting better reliabilities.  This also means one needs to run the year out far into the future on new maps just to check that they didn't get one of these very bad assortments of reliabilities for endgame vehicles they might want to use later.  Making and remaking new maps that aren't going to turn sour in late game is now very tedious.

## Probably an inadvertent consequence of #7147

**Comment by James103** [comment]
Are you sure that this issue is not present in OpenTTD 1.8.x? Your note about it being caused by #7147 implies the statement that I just said.

**Comment by Afdill** [comment]
Yes, the issue doesn't appear to have been present in v1.8.0 but emerged in v1.9.0.  I haven't checked the release candidate or beta builds of v1.9.0 yet.
