### ISSUE TITLE
No installation on Ubuntu 20.10 possible

### ISSUE THREAD

**Issue by embeddeddev** [OpenTTD/OpenTTD#8330]
The DEB-Package for Ubuntu 20.04/Focal depends on ``libicu66``, but since Ubuntu 20.10/Groovy it's not available any more and was replaced by ``libicu67``.

Please provide an adapted build for Groovy.

Thanks so far.

**Comment by erenes** [comment]
I think that's already resolved? 
https://packages.ubuntu.com/groovy/openttd

**Comment by LordAro** [comment]
Not really, this issue refers to the self-published builds on openttd.org . Should hopefully be fixed by a new release, after the release CI is rewritten...
