### ISSUE TITLE
Null pointer dereference in group window when vehicle/group dragging

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#8332]
## Version of OpenTTD
master (since 567d0ff3a7286fe830bf188c2911e3d10d70eb8c)

## Expected result
No null pointer dereferences

## Actual result
A null pointer dereference

## Steps to reproduce
1. Have at least two groups and one vehicle
2. Start dragging one of the groups
3. Press ESC to stop dragging
4. Delete the group
5. Drag the vehicle onto another existing group

group_sel is set when group dragging is started, but not cleared when dragging is aborted
OnDragDrop will execute both a vehicle drag and a group drag if vehicle_sel and group_sel are both set.
OnDragDrop_Group does not check that group_sel is valid before getting the Group* and dereferencing it.

**Comment by James103** [comment]
By following the above steps without deleting the group, the actual result is that not only is the vehicle assigned to the selected group, but also the last group hierarchy action that should have been aborted is instead finally completed.

Also, try the following steps:
1. Have at least two groups and one vehicle.
2. Start dragging one of the groups.
3. Press ESC to stop dragging.
4. Delete the group.
5. In another vehicle type window, create a new group.
6. Drag the vehicle onto another existing group of the same vehicle type.

The result is that the 'assign vehicle to group' action succeeds in step 6, but the 'set parent group' action which was initialized in step 2 persists and fails with the error message "Can't set parent group".

**Comment by TrueBrain** [comment]
Tnx for the detailed reports, and even the solution, @JGRennison ;)
