### ISSUE TITLE
[Game play] Vehicle disasters should always be banner headlines.

### ISSUE THREAD

**Issue by TinCanTech** [OpenTTD/OpenTTD#8336]
## Version of OpenTTD
1.9.3

## Expected result
**Settings**: News / Advisors -> Advice / Information on compamy's vehicles: **Summary**

Vehicle disasters should never be "Summary" items.

## Actual result
Vehicle disasters are not noticed.

## Steps to reproduce
Use: 
**Settings**: News / Advisors -> Advice / Information on compamy's vehicles: **Summary**

I know it is trivial and it may not be possible to change the source .. even so, vehicle disasters should never be "_summary_" items.

**Comment by andythenorth** [comment]
Is this of use? 👍 

<img width="317" alt="8336" src="https://user-images.githubusercontent.com/1780327/98421575-8c33b100-2081-11eb-9a65-eb988a93ee8e.png">

**Comment by TinCanTech** [comment]
Noice! TYVM :)

**Comment by TinCanTech** [comment]
For the record, I was _shocked_ that I was allowed to carry on without _the game_ **insisting** that I know about the deaths!  The families of the victims would surely have caused uproar!

**Comment by TinCanTech** [comment]
Aircraft disasters are still not reported. Tested again and Rail disasters are not reported either.

Either I have the wrong settings or this is a bug in 1.9.3

**Comment by TinCanTech** [comment]
Finally managed to get a disaster banner!
