### ISSUE TITLE
Errornous subsidy for valuables 

### ISSUE THREAD

**Issue by smierlo** [OpenTTD/OpenTTD#8338]
[Black & Co., 5th Oct 2084.zip](https://github.com/OpenTTD/OpenTTD/files/5506337/Black.Co.5th.Oct.2084.zip)

## Steps to reproduce nothing, automatically created.
Savegame and screenshoot attached
![image](https://user-images.githubusercontent.com/74139787/98465193-cd35dd80-21c7-11eb-9241-1d9484a81bfc.png)

**Comment by glx22** [comment]
Fixed by #8305
