### ISSUE TITLE
Forbid 90 degree turns does not work

### ISSUE THREAD

**Issue by TinCanTech** [OpenTTD/OpenTTD#8364]
## Version of OpenTTD
1.10.3

## Expected result
No 90 degree turns allowed

## Actual result
90 degree turns are allowed

## Steps to reproduce
Force a 90 degree turn

See:
![MAG-01, 6th Jul 3541#1](https://user-images.githubusercontent.com/25598447/101385157-4d2c9180-38b3-11eb-9b0d-67c26eb3fee6.png)

**Comment by auge8472** [comment]
That's not a 90-degree-turn but the shortest and sharpest possible construction of a two-times-45-degree-turn.

**Comment by JGRennison** [comment]
This setting can be overridden on a per-railtype basis by NewGRFs,
It would probably be useful if you could include a savegame which shows the issue.

**Comment by James103** [comment]
@TinCanTech At the very least, what NewGRFs do you have in your savegame?

**Comment by TinCanTech** [comment]
> That's not a 90-degree-turn but the shortest and sharpest possible construction of a two-times-45-degree-turn.

I presume you mean something like this:
![MAG-01, 25th Feb 3544x](https://user-images.githubusercontent.com/25598447/101391072-bb755200-38bb-11eb-8860-716ca51fc98a.png)
90 degree turns are banned - 2x 45 degree bends are not ?

**Comment by TinCanTech** [comment]
> what NewGRFs do you have in your savegame?

#openttdcoop NewGRF package 0.8
OpenGFX+ Landscape 1.1.2

**Comment by TinCanTech** [comment]
Save game - Enjoy ;-)

[MAG-01, 11th Jan 3544.sav.zip](https://github.com/OpenTTD/OpenTTD/files/5654599/MAG-01.11th.Jan.3544.sav.zip)

**Comment by glx22** [comment]
Is the train lost ?

**Comment by TinCanTech** [comment]
> Is the train lost ?

Something like that, I was having congestion problems ..

**Comment by glx22** [comment]
Forbid 90° is used when pathfinding but lost train can't find path so they don't follow the rule.

**Comment by TinCanTech** [comment]
OK - That explains it, thanks!

**Comment by JGRennison** [comment]
> Forbid 90° is used when pathfinding but lost train can't find path so they don't follow the rule.

This is not consistent with the code or what the setting is supposed to do. 90° detection is done outside the pathfinder as well, in track following, end of line detection, PBS reservation follow/extension, safe waiting position detection, etc. (Take a look at the call sites of Rail90DegTurnDisallowed).
The only time a train should be able to do this is if the setting is switched after the leading vehicle has already passed over the 90° turn.

**Comment by TinCanTech** [comment]
For the record, I always have "Forbid trains from making 90 degree turns: On"

**Comment by auge8472** [comment]
At zerost: Sorry for being so very short in my first comment. Writing on the phone is a pain. May the technical progress big as a whole planet, my fingers does and will not shrink to match the char-key-buttons in any way.

> > That's not a 90-degree-turn but the shortest and sharpest possible construction of a two-times-45-degree-turn.

At first: I was wrong with interpreting your screenshot in the opening message. I payed attention to the two sharp two-times-45-degree-curves but not to the turning train. Sorry.

> I presume you mean something like this:
> ![MAG-01, 25th Feb 3544x](https://user-images.githubusercontent.com/25598447/101391072-bb755200-38bb-11eb-8860-716ca51fc98a.png)
> 90 degree turns are banned - 2x 45 degree bends are not ?

At second: Sharp curves with two times 45°-turns are not affected by the setting.

![examples of 90-degree turns compared to two-times-45-degree-turns](https://user-images.githubusercontent.com/1734660/101459567-b3a7c300-3938-11eb-9d4f-f116fa357298.png)

Because the discussion shows that the issue seems to be independent from that take my notice only as a notice.

**Comment by TinCanTech** [comment]
> At first: I was wrong with interpreting your screenshot in the opening message. I payed attention to the two sharp two-times-45-degree-curves but not to the turning train. Sorry.

No problem, I should have made my 'shot more clear ;-)

> the discussion shows that the issue seems to be independent from that

Agreed.

For the time being, we must accept: 
 There is more to _detecting_ a 90 degree bend than to _banning_ them.
