### ISSUE TITLE
In game music does not play (Ubuntu / Snap version)

### ISSUE THREAD

**Issue by jukey** [OpenTTD/OpenTTD#8370]
## Version of OpenTTD
snap-id:      vIoqO99N39KayGkEhJO4nW6o06tk5SYt
tracking:     latest/stable
version: 1.10.3 2020-12-10 (392) 95MB

I installed the game from the official Ubuntu App Store (using snaps) in Ubuntu 20.04.1 LTS.

## Steps to reproduce
1. Install the Game
2. Run the Game
3. Ensure that the OpenMSX is set in the Game Options
4. Start a game
5. Open the In Game Music Player
6. Press the play button of the player

## Expected result
Game Music is playing if started using the player within the game.

## Actual result
Music does not play and the in game player 'jumpes' from track to track multiple times a second.

**Comment by LordAro** [comment]
Snaps aren't something that's made (or tested) by us, but this issue is usually due to a missing midi music player - installing `fluidsynth` or `timidity` should work, assuming the snap version has been built with support for them

Failing that, you're going to need to file a bug with whoever made the snap

**Comment by jukey** [comment]
Thanks for the quick response. Installing the packages you mentioned did not solve the issue but I filled bug report at https://github.com/diddlesnaps/openttd/issues/5

**Comment by TrueBrain** [comment]
Let us know if we can help out! Best reachable via IRC, but always feel free to drop a message here if you need any further help. Hopefully the author of the snap can help you out :)

**Comment by lucyllewy** [comment]
Thanks for pointing the way, @TrueBrain :-) I've got a fix for this building now.
