### ISSUE TITLE
Impossible to play a saved game or scenario from a previous versiomn

### ISSUE THREAD

**Issue by piiskop** [OpenTTD/OpenTTD#8380]
## Version of OpenTTD
1.10.3
## Expected result
I can play saved games and scenarios created with 1.9.3.
## Actual result
I can't play saved games and scenarios created with 1.9.3.
## Steps to reproduce
Play a game in 1.9.3 and then try to continue playing it in 1.10.3!

**Comment by TrueBrain** [comment]
You ... really have to be more specific than this I am afraid :)

OpenTTD is fully backwards compatible with any savegame ever made by it, kinda, back to 15 years ago. If a game was made with vanilla 1.9.3 it is very likely it works without issues on 1.10.3. So we need more information :)

Most helpful would be the savegame or scenario you try to open, and a crashlog / error what happened when you try to open it :)

If you can help us there, we can most likely help you more too :) Tnx!

**Comment by piiskop** [comment]
So I give you more information. So far, I started _1.9.3_ server and I have lots of _SAV_-files played with _1.9.3_. Once a buddy installed _1.10.3_, he couldn't play my server as there was a version conflict. Even before that as I had like the version _1.7_ and somebody else version _1.9_ they didn't talk to each other. So I wanted to create a server with _SAV_-file under _~/.openttd/save/_ in _1.10.3_ and what happened was:

> kalmer@test:/snap/bin$ sudo ./openttd -D -g ~/.openttd/scenario/island11.scn 
> mkdir: cannot create directory '/run/user/0': Permission denied
> dbg: [net] Starting dedicated version 1.10.3
> dbg: [net] [core] starting network...
> dbg: [net] [udp] initializing listeners
> dbg: [net] [core] network online, multiplayer available
> dbg: [net] Detected broadcast addresses:
> dbg: [net] 0) 192.168.1.255
> dbg: [net] 1) 172.18.255.255
> dbg: [net] 2) 172.17.255.255
> dbg: [net] 3) 172.19.255.255
> dbg: [sl] Game Load Failed
> File not readable
> dbg: [net] Loading game failed, so a new (random) game will be started!
> dbg: [net] Generating map, please wait...
> dbg: [net] Map generation percentage complete: 5
> dbg: [net] Map generation percentage complete: 10
> dbg: [net] Map generation percentage complete: 15
> dbg: [net] Map generation percentage complete: 20
> dbg: [net] Map generation percentage complete: 25
> dbg: [net] Map generation percentage complete: 30
> dbg: [net] Map generation percentage complete: 35
> dbg: [net] Map generation percentage complete: 40
> dbg: [net] Map generation percentage complete: 45
> dbg: [net] Map generation percentage complete: 50
> dbg: [net] Map generation percentage complete: 55
> dbg: [net] Map generation percentage complete: 60
> dbg: [net] Map generation percentage complete: 65
> dbg: [net] Map generation percentage complete: 70
> dbg: [net] Map generation percentage complete: 75
> dbg: [net] Map generation percentage complete: 80
> dbg: [net] Map generation percentage complete: 85
> dbg: [net] Map generation percentage complete: 90
> dbg: [net] Map generation percentage complete: 99
> dbg: [net] Map generated, starting game
> dbg: [net] Loading requested map failed, aborting
> dbg: [net] Dedicated server could not be started, aborting
> dbg: [net] [udp] closed listeners
> dbg: [net] [udp] initializing listeners
> dbg: [net] [udp] closed listeners
> dbg: [net] [core] shutting down network

These files run very well in _1.9.3_. And I can't open these files directly in _1.10.3_ client neither. A further problem is that even the contents of folders are shown empty. Lately, I downloaded some sample scenarios and if I go into the folder _/home/peacecop/snap/openttd/407/.openttd/scenario/_ the client shows these downloaded scenarios as yellow there but if I go into that folder directly it's empty. This is very confusing.

**Comment by TrueBrain** [comment]
The logs return `File not readable`. In other words, in your installation, OpenTTD cannot open the savegame. This is most likely due to permissions, or locations of file. Sadly not something we can really help with :(

You would have to solve this problem in order for this to work. I am really sorry, but there is not much I can do for you here ...

It seems you are using `snap` to run OpenTTD; possibly this has something to do with the permission problems. But as we don't make the `snap` versions of OpenTTD, that is a bit hard to tell ..

Again, really sorry, but there is not much I can do for you :(

**Comment by piiskop** [comment]
Yes I run _1.10.3_ via _snap_ while _1.9.3_ runs via _apt_. Who does make _snap_ version? What version do you make and how can I use that? Even if I set world readable-writable-executable permissions I can't see that file listed within the game navigator.

**Comment by TrueBrain** [comment]
We publish our binaries via https://www.openttd.org/ . I know `snap` does things with the filesystem, but I am not an expert here. So I don't know :) Maybe others do.

**Comment by piiskop** [comment]
I don't think it's a _snap_ issue. I just downloaded your binary and the problem remains.

**Comment by TrueBrain** [comment]
Can you, as example, try to upload one of those savegames so we can take a look? Is it more than 0 bytes?

**Comment by piiskop** [comment]
It really looks that _snap_-version has the problem only. Now, I removed _1.9.3_ from my server machine and installed your binary of _1.10.3_ and the result's amazing - it works with old savegames! Meanwhile the error message was because an incorrect file name. However, after copying the file over to _snap_ part, there was the permission issue. So the issue can be considered as non-present for now. Thank's for making me rest assured that the game is backwards compatible!

**Comment by TrueBrain** [comment]
Great to hear it works again for you! That makes me happy :) Enjoy the game!!
