### ISSUE TITLE
HDR rendering (12-bit, 16-bit, high brightness) !

### ISSUE THREAD

**Issue by lodewijkadlp** [OpenTTD/OpenTTD#8389]
Faith Despair!

My OpenTTD does not PUSH INTO THE HIGHEST OF COLOR RANGES

A main menu item should assure a person what color treatment is given. There is a lot possible in this realm, but OpenTTD seems to be pretty forward on 32 bit graphics (only). Simply enabling this in software can enhance contract on many modern monitors. Depending on monitors it may be possible to achieve the same color intensity, but this is not assured.

Not sure where HDR (extra-brightness) should come in. Perhaps in highlighting awards and menu items? Perhaps if a train passes in a turn?

**Comment by TrueBrain** [comment]
OpenTTD does not support HDR (it is a game from 1994 :P). We welcome Pull Request to extend on our current video drivers to improve quality, but as far as my knowledge goes, HDR also needs adjustment in source material. This might be a huge undertaking.

Anyone that feels up taking the job is very welcome. But not having HDR is not an issue, so I guess this is a feature request. We tend not to leave feature requests on our issue-tracking, as it would only be a long long long long list of all kinds of different stuff people want :)

Tnx for the suggestion, and we welcome Pull Requests for it :)
