### ISSUE TITLE
Broken build on non-Debian/Ubuntu distros

### ISSUE THREAD

**Issue by Nik-mmzd** [OpenTTD/OpenTTD#8407]
## Version of OpenTTD
Any after commit 6228dde3da9b1368e8ca26e16fb2623f25b249ed

## Expected result
Build is configuired and ready for compiling

## Actual result
FATAL_ERROR at cmake/InstallAndPackage.cmake:138:
```
CMake Error at cmake/InstallAndPackage.cmake:138 (message):
  Unknown Linux distribution found for packaging; please consider creating a
  Pull Request to add support for this distribution.
```

## Steps to reproduce
Use not Ubuntu/Debian when
```
mkdir -p build
cd build
cmake ..
```

**Comment by TrueBrain** [comment]
Oops, sorry about that. Latest `master` should fix this, I hope .. let me know if it doesn't ;)

We would still highly appreciate anyone making a PR to implement what-ever distro it is you are running on, so those can create pack-files too :)

Tnx for the report!

**Comment by Nik-mmzd** [comment]
> Oops, sorry about that. Latest master should fix this, I hope .. let me know if it doesn't ;)

It's better that my dirty fix. All works, thanks
