### ISSUE TITLE
Trains stuck at path through implicit destinations after fixing route towards real destination

### ISSUE THREAD

**Issue by perezdidac** [OpenTTD/OpenTTD#8419]
## Version of OpenTTD
1.10.3

## Expected result
Train should find its way to non-implicit destination.

## Actual result
Train gets stuck heading implicit destinations. Skipping stops to force going to the non-implicit destination does not work (does not get selected, the arrow skips to the next one).

## Steps to reproduce
* Create a route which will make the train have implicit destinations.
* Create a semaphore in such a way the train cannot reach a destination and has to loop back following an alternative path.
* Remove the semaphore.
* Observe that the train sticks to the path through implicit destinations and is not able to fix itself and realize that now there is a path to its real destination.

**Comment by TrueBrain** [comment]
Would you be able to provide us with a savegame? That makes it easier for us to see what you mean exactly :) Tnx!

**Comment by 2TallTyler** [comment]
Not triaged after two years, closing it unless someone can reproduce. 🙂
