### ISSUE TITLE
MacOS CMake fails to load "Options"

### ISSUE THREAD

**Issue by SJang1** [OpenTTD/OpenTTD#8423]
## Version of OpenTTD
2e6f37e (master)

## Expected result
OpenTTD Builds correctly

## Actual result
![image](https://user-images.githubusercontent.com/29011440/103042445-f9ad8980-45bc-11eb-9cfd-1c38494f6eac.png)
```
CMake Error at CMakeLists.txt:23 (include):
  include could not find load file:

    Options


CMake Error at CMakeLists.txt:24 (set_options):
  Unknown CMake command "set_options".


-- Configuring incomplete, errors occurred!
```
And it fails to build

## Steps to reproduce
1. clone or download source of openttd, and go into the folder
2. mkdir build
3. cd build
4. cmake .. <--Error on this

Spec: Apple Silicon M1 Macbook Air / Big Sur 11.1
However, [right now on JGRpatch](https://github.com/JGRennison/OpenTTD-patches/tree/8ac436f50762caf800d8c10ae37ac6dd8a4cc678) it builds correctly, but same happened for the [current release of that patch](https://github.com/JGRennison/OpenTTD-patches/releases/tag/jgrpp-0.39.1).

**Comment by glx22** [comment]
Attached error message is from JGR source.
Anyway I don't see how CMake can't find a file present in source, and I don't see important changes in this area between both JGR revisions, or even between JGR and openttd master.

**Comment by SJang1** [comment]
Oh, attached one was a mistake, BTW error message is same. 
I even can't see any important changes between both JGR revisions, but only current master of JGR version builds sucsessfully.

**Comment by TrueBrain** [comment]
It seems CMake has issues finding our `cmake` folder. This will be a bit hard to debug for us, as it is possible it is only a local issue (we build Mac builds daily, so we know it should, in theory, work :P). So let us try to gather some information to help you further.

`Options` is included on line 32 of master, and used on line 33. Those are the two errors you are seeing. Line 22 extends the locations it looks for these files to include the local `cmake` folder. Could you tell us the output of the following commands (from the git clone root folder; so **not** inside the `build` folder):

`ls -lh cmake/Options.cmake`
`find cmake`

Next, we need to know a bit what CMake is doing. Could you add above line 22 something like:

`message("${CMAKE_SOURCE_DIR}")`
The line that follows should be:
`set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake")`

and rerun `cmake ..` from your `build` folder, to let us know the first line CMake gives you back?

That info might help us a bit further along this venture, as a venture it will be! :)

**Comment by SJang1** [comment]
Hmmm.. It's weird.
I have downloaded source again and restarted my computer, it's working propually like others do.

But anyway, message comming from `message("${CMAKE_SOURCE_DIR}")` is NOT that.
Output was `/Users/(my_username)/Downloads/OpenTTD` on above line 22, and even below line 22.

(I git cloned on Downloads folder, so Downloads/OpenTTD is a local git repository)

**Comment by TrueBrain** [comment]
Very odd; but I guess we can call this ticket resolved in that case? :)

If there is anything else we can help with, let us know!

**Comment by SJang1** [comment]
Of course why not? thanks for help :)
