### ISSUE TITLE
Color tracks and lanes by used capacity

### ISSUE THREAD

**Issue by bernardoct** [OpenTTD/OpenTTD#8447]
## Version of OpenTTD
Future version
## Expected result
To help tracking system bottlenecks, it would be great to see tracks and roads colored on a gradient from green to red depending on capacity used. For example, tracks which can't convey more trains would show as red, while sub-utilized tracks would show as green.
## Actual result
N/A
## Steps to reproduce
N/A

**Comment by TrueBrain** [comment]
Thank you for your feature request!

Personally, I am not a big fan of colouring things in-game like that. But I agree it would be nice to more easily spot bottlenecks etc. This for sure needs more thinking and tuning before it becomes an idea that can be build.

If you feel up for it, working out this idea further would be very welcome. Possibly a good place for that would be our [forums](https://tt-forums.net), so others can pitch in too how they think this should look. And of course, afterwards, we need someone to build it.

As this issue tracker is not really the place to keep these kind of feature request, I am going to close this for now. For more details how we consider feature requests, please see our [feature-requests](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) section.

Thank you, and I hope to see your idea worked out a bit more soon :D Would be a great addition to the game!
