### ISSUE TITLE
New feature: option to see charts of all items in the balance sheet dating from 10 years prior.

### ISSUE THREAD

**Issue by bernardoct** [OpenTTD/OpenTTD#8448]
## Version of OpenTTD
Future version
## Expected result
Option to generate charts of each item in the balance sheet dating from at least 10 years prior. This would help identify the reasons for fluctuations in yearly profits and to track the impact of big upgrades to the company's assets.
## Actual result
N/A
## Steps to reproduce
N/A

**Comment by TrueBrain** [comment]
Thank you for your feature request!

As you might understand, we have many of similar feature requests for projects like this. And we would love to extend on the parts of the game that give you more insight how your economy is doing! If you feel up for it, we would love to have a Pull Request to show us how it could look, and what the benefits for it are to the game-play.

Sadly, we tend to not keep these feature requests around on our issue-tracker. This is further explained in our [feature-requests](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#feature-requests) section. Mainly, an issue-tracker isn't really useful for feature-request, we found out over the years. But again, if you feel up for it, and want to try out building this yourself, that would be greatly appreciated. If you need help or tips&tricks, drop by on our [IRC](https://webchat.oftc.net/?channels=openttd)!

Tnx!
