### ISSUE TITLE
AIs can fail at requesting 170 years inflation loan with a 4% interest rate

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#8453]
![maxloaninflation](https://user-images.githubusercontent.com/43006711/103179258-f4cd2c00-4881-11eb-9a05-855f5e06c461.png)
The AI is setting loan amount to £1,641,693,900,000 and has a current loan of £82,050,000.
https://github.com/OpenTTD/OpenTTD/blob/edbb5f4f737e2670faa1ac392fe179b7278921ec/src/script/api/script_company.cpp#L207-L209
Following the code, `abs(1,641,693,900,000 - 82,050,000)` = 1,641,611,850,000 is passed to this function:
https://github.com/OpenTTD/OpenTTD/blob/edbb5f4f737e2670faa1ac392fe179b7278921ec/src/script/api/script_object.hpp#L69-L72
`uint32 p1` transforms the value to 934,342,928
This ends up failing to set the loan even to the bugged value:
https://github.com/OpenTTD/OpenTTD/blob/edbb5f4f737e2670faa1ac392fe179b7278921ec/src/misc_cmd.cpp#L57-L58
`p1 % LOAN_INTERVAL != 0` is true, returns `CMD_ERROR`

**Comment by glx22** [comment]
I think it should be possible to split 64bit value in two 32bit values passed in p1 and p2, with lower 2 bits discarded in the call, then forced to 0 in `CmdIncreaseLoan()` when reconstruction the original 64bit value. Amount being a multiple of `LOAN_INTERVAL` it should be fine.

**Comment by James103** [comment]
Possible workaround: In the AI script, set the loan value to incrementally higher amounts. For example, do the following:
```squirrel
AICompany.SetLoanAmount(2000000000);
AICompany.SetLoanAmount(4000000000);
AICompany.SetLoanAmount(6000000000);
AICompany.SetLoanAmount(8000000000);
...
```
until the target loan amount has been reached.
