### ISSUE TITLE
Maglev train stuck in deadlock on title screen

### ISSUE THREAD

**Issue by condac** [OpenTTD/OpenTTD#8467]
## Version of OpenTTD
latest stable 1.10.3
## Expected result
Maglev trains moving around and looking fabulous.
## Actual result
Maglev trains looking sad...
## Steps to reproduce
Start game. 
![image](https://user-images.githubusercontent.com/1023885/103343686-ebfc7600-4a8c-11eb-976f-a81bdae2c280.png)

This is pure cosmetic but still a sad looking issue.

**Comment by LordAro** [comment]
Nice spot! 1.11 will have a new title game, so that will become a non-issue then (and there won't be a further 1.10.x release)
