### ISSUE TITLE
Graph Window - Colors of the mauve, dark green and purple companies are barely visible

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#8539]
## Version of OpenTTD
Probably all, including the current 1.10.3

## Expected result
![Clearly visible lines](https://user-images.githubusercontent.com/67662046/104074795-4aee8780-5211-11eb-93bb-833c9b1ef4d1.png)
Visible and easily distinguishable charts of each company.

## Actual result
![Barely visible lines](https://user-images.githubusercontent.com/67662046/104074587-c865c800-5210-11eb-9f31-14a1eb92c149.PNG)
Company chart lines with the colors mauve, dark green and purple are faint or very faint in the charts windows. The problem is especially with the color of the mauve.

## Comment
It is enough to change the colors of the lines of the mauve, dark green and purple charts to 1 shade darker (looks more, but the difference is only 1 shade). Helpful, but not so important, will also be to darken the orange color also by one shade.

**Comment by TrueBrain** [comment]
Assuming you are also https://www.tt-forums.net/viewtopic.php?f=32&t=88329, let me say: big fan of the work :)

Let's see what we can do for the graph .. I have no clue :D I am about to find out ;)

**Comment by TrueBrain** [comment]
So, how things work in OpenTTD:

These graph-colours are based on the company-colour. Every company has 8 "gradients" you can pick from. This is currently set to "6", which is a very light variant of the company colour. In the PR I just created I changed that to "4", which is a bit darker variant. The downside? It means ALL lines are now darker, not just the few that stood out. But there is not much choice in the matter honestly.

![image](https://user-images.githubusercontent.com/1663690/104088802-bebc7e80-5269-11eb-8ee4-a43178c7c5ff.png)

I tried "5" too, but this made other colours much harder to read:

![image](https://user-images.githubusercontent.com/1663690/104088788-a9dfeb00-5269-11eb-8635-4cf90fd99098.png)

I would love opinions about my choice here! You can see the work I did here: https://preview.openttd.org/pr8542/

**Comment by TrueBrain** [comment]
For future-reference, https://grf.farm/misc/company_colour_reference/html/company_colour_indexes.html shows the gradient per company.

**Comment by LC-Zorg** [comment]
Thanks for the feedback. I have a bit more of these scribbles, but there is not enough time to describe and refine them in places. Well, unfortunately these are just only more ideas, but I hope they will be useful somehow. For example by showing how not to do something. :)

This was what I expected and was afraid that the level of these colors may be combined. Level 5 is definitely out of the question due to the gray color which would be completely invisible - I checked it before. Level 6 seems a little too dark and didn't refer well with the companies colors elsewhere in the game (I think so). I am not a programmer (I read OTTD code as easily as Asian characters for an average European) and usually when it seems to me that something is easy, it turns out to be surprisingly difficult. Here, I could write that the best solution would be the possibility of assigning a selected color to each company individually (preferably including the full RGB palette). And that seems like the only right solution, but I also think it may not be that simple.

So I have another solution, but not necessarily easier. ;)
Another, although one of the first of my graphics.
![New Graph window v01 1](https://user-images.githubusercontent.com/67662046/104091347-1ca69180-527d-11eb-8efb-b12f4dbc324a.png)
This graphics also include other ideas, but I mean the dark background color (black -1). I've also checked it with the NewCC add-on colors and everything looks fine. However, there would be a problem with the chart of transport rates and the planned chart of production levels - there a dark background in the case of add-ons such as FIRS would be a bad solution. I don't know if it would be good to use a different background color for different graphs.

The graphic below is almost two years old. It might be a light offtop, but I think it could be useful...
![New Graph window](https://user-images.githubusercontent.com/67662046/104091362-38119c80-527d-11eb-887f-93808b9e42a0.png)
In some time I will try to post it on the forum along with the description so that it doesn't disappear.

**Comment by TrueBrain** [comment]
Oeh, pretty GUI.

I think the solution I propose, is not a good one. Sure, it does fix some of the problems, but I am sure others will become as visible as easily. I like your dark background solution, and it seems to be a more correct solution.

In general, as you noticed, many of our GUIs could use a facelift to become a bit .. modern? more readable? less weird? :D None of us are UI or UX designers, which might be apparent :)

Not sure what a good next step is; I have to think about it for a bit :)

**Comment by andythenorth** [comment]
> For future-reference, https://grf.farm/misc/company_colour_reference/html/company_colour_indexes.html shows the gradient per company.

Cleaned up grf.farm a bit, file now at https://grf.farm/misc/company_colour_indexes.html

**Comment by TrueBrain** [comment]
![image](https://user-images.githubusercontent.com/1663690/104232661-f5082280-5450-11eb-8d29-bd1b41dad953.png)

Looks pretty good honestly. I think your other changes are also well worth integrating, but this might just be a nice temporary solution for 1.11, while we make all the UIs a bit better in 1.12 :)

**Comment by TrueBrain** [comment]
This is now available in preview in https://preview.openttd.org/pr8557/ ; what you do think @LC-Zorg , good enough solution for now?
