### ISSUE TITLE
Flat maps of arctic and tropical climates are completely inaccessible

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#8551]
## Version of OpenTTD
20210108-master
## Actual result
Flat and very flat maps with the setting of the arctic and tropical climate are completely inaccessible to the player, no matter what industrial set he uses and whether he is interested in the industry at all.
## Expected result
**Variant 1**
![Terrain warning v01](https://user-images.githubusercontent.com/67662046/104110164-20fe9900-52d5-11eb-9f2f-69b5153dafc9.png)
An inexperienced player who wants to generate a flat or very flat map with dimensions 256x256 or smaller with the default industrial set and only this will receive a warning when "Generate" is clicked that the terrain type is too flat for this industry set. Nevertheless, he will be able to continue.

**Variant 2**
![Terrain limiting v01](https://user-images.githubusercontent.com/67662046/104110169-2a880100-52d5-11eb-98a0-2249268802f0.png)
Using the industry default set, for arctic or tropical climate and 256x256 or smaller maps, flat and very flat terrain setting will not be available. (Here, the lack of warning / information may cause confusion)
## Comment
This way of solving the problem causes a large limitation of the game freedom. Turning off the ability to generate very flat and flat maps for Arctic and Tropical settings entirely due to a handful of not very bright players is a really bad solution. Almost no industrial set requires mountainous terrain. This also applies to the default tropical industry, which may well have only coasts to generate each enterprise. There are great opportunities to create interesting games using tropical and arctic climates (sometimes it's just about the color or properties of the ground) combined with flat terrain, and now it will be impossible. It really doesn't make sense. It is also inconsistent with the project goals, as the change does not take into account the different way of playing - a large number of players like flat maps, even completely flat ones.
Another disadvantage of this approach is that the terrain type setting for both arctic and tropical climates will have two dead settings, giving the same result as the third.
As for the changes to the terrain generator, in my opinion some changes would be useful to make the maps more diverse and the water bodies more often interconnected, but when it comes to flat maps they should just stay flat - it shouldn't be forced to build a hills with each setting. Flat maps with a high variety setting, yes, they could and should even have higher single mountains or areas - that will be good, but really not forced.
I think the best solution here will be to add a warning about the possible incompatibility of certain terrain settings with certain industries.

**Comment by TrueBrain** [comment]
> Flat and very flat maps with the setting of the arctic and tropical climate are completely inaccessible to the player, no matter what industrial set he uses and whether he is interested in the industry at all.

We recently made a change to how maps are generated, and this should no longer be the case. As in .. "very flat" is not as flat as the word suggests on Arctic and Tropic. With that change, do you still think we should inform the users? Is it still "too flat"?

(basically, I went for an alternative solution to your suggestion, and just made "very flat" a bit more mountain-like as .. it is arctic and tropic after all ;) )

Would love to get your feedback on the recent changes (should be in the latest nightly).

**Comment by LC-Zorg** [comment]
> We recently made a change to how maps are generated, and this should no longer be the case. As in .. "very flat" is not as flat as the word suggests on Arctic and Tropic. With that change, do you still think we should inform the users? Is it still "too flat"?
> 
> (basically, I went for an alternative solution to your suggestion, and just made "very flat" a bit more mountain-like as .. it is arctic and tropic after all ;) )

Well ...
![Not flat land](https://user-images.githubusercontent.com/67662046/104138491-ae5cee80-53a4-11eb-8026-ea38979b2793.png)

No, it's definitely not a very flat map. ;)

I don't change my opinion: It's the wrong way...

There is still a problem with the forests and in addition the map is not compatible with the selected settings.

**Comment by TrueBrain** [comment]
I have been considering changing the labels for those 2 climates :P I am not sure, that might just be evil, but so if you select Arctic or Tropic, "Very Flat" becomes something like "normal",, "flat" becomes "a bit more hills", etc. And we increase the hilliness even further :P Playing those maps on flat maps like you show is just silly ... but okay, at least there is now always snow, so there is a that :D

The other solution is far more drastic, and revamp the whole "newgame" window. As in, by default show a "basic" window where you select the climate and you get like: "easy", "challenging", "very difficult", or something. And that is it.

Than there is an "advanced" button you can click that allows you to tune all these settings. And even allows you to make a full flat map in arctic; totally pointless from a gameplay perspective, but allowed. That means we don't really have to warn people doing silly stuff, as .. well .. it is "advanced" :D What do you think? (as you notice, I am searching for a solution, not really have a clue what works .. people might dislike this idea very much, but I think the current window is a bit much for new players :D)

**Comment by LC-Zorg** [comment]
There is also a third solution - the first of my suggestions, which is just adding a warning - probably the simplest, causing the least controversy and anger among some players, not restricting anyone and causing the least inaccuracies. ;)

Flat maps are neither pointless nor silly. The fact that you don't like these maps is not a good basis for other players not to use them. Not everyone needs mountains to have fun. Some players just tire of the mountains - building routes is much more time-consuming. This largely applies to novice players for whom this change was supposed to be.

**Comment by auge8472** [comment]
Problem with subarctic climate is, that you will not get the full chain of industries without mountains (at least with original industries). The warning has to be verbose to clarify the economic limitations.

**Comment by LC-Zorg** [comment]
I will say a little more:
1. Tropical climate, does not require any changes in the way the terrain is generated, nor any warnings - no elevations are necessary for the map generator to build any type of enterprise.
2. The problem mainly concerns arctic forests that can only be placed on snow - such forests are included in the default set and UKRS Industries.
3. The problem is not only with the setting of the terrain type - here it is not so much the height of the terrain that matters, but the set snow level, because the forests must always remain in the snow zone. In its present form, I see the importance of four parameters: Terrain type, Map height, Map size (the smaller of the dimensions) and Snowline height. Additions changing the height of the snow line can have an additional impact - here the properly setting of upper snow line limit is important.
4. Additives that alter the height of the snow line, such as OpenGFX + Landscape, can put arctic forests almost anywhere, also on very flat maps. But it can also prevent to creating farms or other enterprises from other industrial sets when the snow line is too low.
![No problem but still problem](https://user-images.githubusercontent.com/67662046/104363055-f1d66a80-5514-11eb-8710-4d9e9ff622fe.png)

5. Due to the number of variables, the warning generated by the game should rather only concern the default set of industries with certain settings.

Perhaps a better solution would be to leave only the information after generating the map, but supplement it with tips on what the player can / should do?

**Comment by andythenorth** [comment]
Can't reproduce with 20210112-master.

Map generation works as expected in arctic and tropic.

Thanks for contributing.
