### ISSUE TITLE
Plane sprite and shadow get reversed when terrain under hangar tile of airport is lowered

### ISSUE THREAD

**Issue by Andrew350** [OpenTTD/OpenTTD#8560]
## Version of OpenTTD
20210111-master
## Expected result
Planes are drawn normally
## Actual result
When a plane lands at an airport where the tile under the hangar is lowered (see screenshot), the plane sprites and their shadows appear to get swapped around, causing them to clip into the terrain and buildings. This affects all airports.
## Steps to reproduce
Build airport
Lower terrain under hangar
Land plane at airport

Screenshot showing the issue:

![plane-bug](https://user-images.githubusercontent.com/50259667/104365713-32aa9100-54cd-11eb-8975-b5bd0ee8ddbe.png)

And a small savegame with an airport and plane already built showing the issue:

[plane-bug-save.zip](https://github.com/OpenTTD/OpenTTD/files/5804477/plane-bug.zip)

**Comment by erenes** [comment]
I could not reproduce this in 1.10.2, but when loading the savegame I made (in 1.10.2) using the latest nightly (20210112) it reproduced immediately, so definitely a regression.

**Comment by James103** [comment]
@erenes Have you tried reproducing this in 1.10.3?

**Comment by erenes** [comment]
I did now, it also does not reproduce on 1.10.3 for me.

**Comment by James103** [comment]
Are you able to `git bisect` through the nightlies from release 1.10.3 through present? If so, which commit introduced the bug?

**Comment by LordAro** [comment]
This will be a result of #8458 . Made assumptions about the hangar being on flat land, which obviously isn't the case. Should be a relatively easy fix.
