### ISSUE TITLE
Stopped road vehicle displays a speed different than 0.

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#8565]
## Version of OpenTTD
ebaeceb
## Expected result
Either display 0 km/h or omit the speed since it's currently stopped.
## Actual result
![Henfingburg Transport, 1952-07-26](https://user-images.githubusercontent.com/43006711/104494514-7638f400-55ce-11eb-95a8-bc629e72dc80.png)
Road vehicle 22 is stopped, but when I hover over the "current vehicle action" it says it's moving at 53 km/h.
## Steps to reproduce
Stop a moving road vehicle.

**Comment by James103** [comment]
Does the same apply for ships and/or aircraft?

**Comment by TrueBrain** [comment]
> 
> 
> Does the same apply for ships and/or aircraft?

What did trains ever do to you?! :D

**Comment by glx22** [comment]
Seems to be a cache update issue. On Start/Stop speed is set to 0 https://github.com/OpenTTD/OpenTTD/blob/1411f878abdd22c04ef5783f3100ab9456d2520a/src/vehicle_cmd.cpp#L622
Then cache is supposed to be updated by https://github.com/OpenTTD/OpenTTD/blob/516e8633955840b44fd5329d872c9bfcd455012a/src/roadveh_cmd.cpp#L1600
But it's prevented by https://github.com/OpenTTD/OpenTTD/blob/516e8633955840b44fd5329d872c9bfcd455012a/src/roadveh_cmd.cpp#L1565
