### ISSUE TITLE
Game does not launch on windows XP 32 bit

### ISSUE THREAD

**Issue by AlexBassett** [OpenTTD/OpenTTD#8593]
## Version of OpenTTD
1.10.3 Stable release

## Expected result
Game  launch on windows xp sp3 32 bit
## Actual result
0xc000001d error(https://pastebin.com/ef4eBJb5)
## Steps to reproduce
1. Install OpenTTD on WinXP 32bit
1.5. Specific system specs - Pentium III 733mhz, 256mb ram, nvidia fx 5200 pci
2. Attempt to launch game

**Comment by orudge** [comment]
This is probably related to SSE instructions or similar not being supported by your processor. Building the code from source with customisations to restrict the instruction set might be necessary. (This may potentially be in one of the libraries OpenTTD uses rather than OpenTTD itself.)

**Comment by James103** [comment]
Additionally, you may not have enough RAM to run OpenTTD with all the features you are trying to run:
* Windows XP SP3 requires 64 MB of RAM and recommends 128 MB of RAM for the OS (see [documentation](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-xp/bb457057(v=technet.10)#memory-and-performance)).
* OpenTTD requires 64 MB of RAM and recommends 128 MB of RAM according to the [system requirements](https://wiki.openttd.org/en/Archive/Manual/System%20Requirements), but I've found that OpenTTD actually requires upwards of 128 MB of RAM for itself just to launch, meaning that 256 MB is the recommended amount (this increases with larger maps, AI/GS, and NewGRF).

**Comment by orudge** [comment]
For what it's worth, I have just dug out an old Windows XP 32-bit ISO and installed it in a VM and was able to run OpenTTD 1.10.3 on it. The problem will almost certainly be with OpenTTD or its libraries requiring features your CPU doesn't support, unfortunately.

**Comment by James103** [comment]
Should OpenTTD 1.11+ even still support Windows XP (and earlier)? Since April 2020, the market share for Windows XP is has been less than 1% (around 0.8%) according to [TechSpot](https://www.techspot.com/news/86269-people-wont-abandon-windows-7-os-found-almost.html#:~:text=Windows%20XP), [Security Boulevard](https://securityboulevard.com/2020/11/23-of-windows-in-use-is-old-insecure-win7-or-xp/#:~:text=Windows%20XP), and [statcounter](https://gs.statcounter.com/windows-version-market-share/desktop/worldwide/).

**Comment by LordAro** [comment]
Usage is never the deciding factor - we support various forms of BSD, and a few others besides that probably have fewer users than XP even now. The fact that it's been out of support for 7 years on the other hand...

@orudge, feel like testing a recent nightly with your VM just to see if it even still works?

**Comment by orudge** [comment]
> @orudge, feel like testing a recent nightly with your VM just to see if it even still works?

No, it doesn't. The .exe has a minimum version of 6.00 (Vista). I think, before cmake integration, we built OpenTTD with the v141_xp MSVC compiler (or an earlier version). We now just use the standard MSVC 2019 compiler, which doesn't support XP.

I don't see that this is a problem, to be honest. If we are able to continue supporting Vista without it being a major overhead, then fine, but making Windows 7 a practical baseline seems reasonable to me.

That's not to say that we should intentionally break compatibility with these older versions, and a dedicated user could still build for those older platforms manually, but we are not providing builds any more.

I think we'll need to go and update the descriptions on the web site...

**Comment by AlexBassett** [comment]
> > @orudge, feel like testing a recent nightly with your VM just to see if it even still works?
> 
> No, it doesn't. The .exe has a minimum version of 6.00 (Vista). I think, before cmake integration, we built OpenTTD with the v141_xp MSVC compiler (or an earlier version). We now just use the standard MSVC 2019 compiler, which doesn't support XP.
> 
> I don't see that this is a problem, to be honest. If we are able to continue supporting Vista without it being a major overhead, then fine, but making Windows 7 a practical baseline seems reasonable to me.
> 
> That's not to say that we should intentionally break compatibility with these older versions, and a dedicated user could still build for those older platforms manually, but we are not providing builds any more.
> 
> I think we'll need to go and update the descriptions on the web site...

Okay, That makes sense. I was essentially just using it as a ttd source port to avoid the dos weirdness, but I guess ill just find a legacy version.

**Comment by LordAro** [comment]
https://cdn.openttd.org/openttd-releases/

This may help
