### ISSUE TITLE
Intrusive buoys

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#8595]
## Version of OpenTTD
All, including 1.10.3
## Actual result
When ships are used by many companies, the water areas are often littered with inscriptions, most of which are buoy names. This makes it difficult to see where the enterprises are located on the water. The map view itself is also not delightful then.
## Expected result
The names of the buoys don't dominate the view of the water areas, it is easy to spot the enterprises on the water.
## Basic solution
Added the ability to turn on/off buoy names regardless of station names.
## Additional solution 1
It would also be helpful to shorten the buoy names (optional or permanent). Then, instead of the long text **_Little Grunborough Bay Buoy#3_**, there would be a short **_B#32_** - Many players do this or similar. Thanks to this, the labels of the buoys visible on the map wouldn't be so intrusive, they wouldn't cover the playing field, it would be much easier to notice those belonging to enterprises.
## Additional solution 2
Buoy labels visible only when creating orders for the ship and after hovering the cursor over the buoys - the function would work if the buoy name view was turned off. For the station names it could work similar.

Current view
![Intrusive Buoys x1 ON-ON](https://user-images.githubusercontent.com/67662046/105104890-67ad7980-5ab3-11eb-8d34-0f666e7f8695.png)

Station names: On
Buoy names: Transparent
![Intrusive Buoys x2 ON-trans](https://user-images.githubusercontent.com/67662046/105104900-6da35a80-5ab3-11eb-9482-c836cc463481.png)

Station names: On
Buoy names: Transparent with shorter text
![Intrusive Buoys x2 1 ON-trans (short)](https://user-images.githubusercontent.com/67662046/105104909-73993b80-5ab3-11eb-8702-f583aa049c25.png)

Station names: On
Buoy names: Off
![Intrusive Buoys x3 ON-OFF](https://user-images.githubusercontent.com/67662046/105104927-78f68600-5ab3-11eb-843a-168ed4f4d41e.png)

Station names: Transparent
Buoy names: Transparent
![Intrusive Buoys x4 trans-trans](https://user-images.githubusercontent.com/67662046/105104951-7f84fd80-5ab3-11eb-9644-e99ace8e12a0.png)

Station names: Transparent
Buoy names: Transparent with shorter text
![Intrusive Buoys x4 1 trans-trans (short)](https://user-images.githubusercontent.com/67662046/105104966-857ade80-5ab3-11eb-9ed4-ee4a2651a96c.png)

Station names: Transparent
Buoy names: Off
![Intrusive Buoys x5 trans-OFF](https://user-images.githubusercontent.com/67662046/105104984-8b70bf80-5ab3-11eb-8978-3a794f86dfff.png)

**Comment by Eddi-z** [comment]
Dunno, this feels awfully niche to me.

i would feel more comfortable if it also would address the problem in this thread: https://www.tt-forums.net/viewtopic.php?f=32&t=88400

**Comment by LC-Zorg** [comment]
> i would feel more comfortable if it also would address the problem in this thread: https://www.tt-forums.net/viewtopic.php?f=32&t=88400

Buoys have little to do with the topic of distinguishing between stations IMHO. It is rather a separate issue. There, in response to some player problem, I wrote a proposal to add transparency for each type of station, but I don't think that's a best solution. Maybe because I rather not need it, unlike hiding the buoy labels. :)
A much more interesting solution in that topic would be to differentiate the size of the inscription due the meaning of the station - the greater the significance, the greater the name (within reason). The smaller labels would have stations with a smaller meaning. Actually, that could also apply to the buoys. However, it seems to me a much more complicated change than the split of the transparency options.

**Comment by Eddi-z** [comment]
> Maybe because I rather not need it, unlike hiding the buoy labels. :)

But that's the entire point i'm trying to make. this issue is purely about your personal itch, not designed to help a broader audience.

**Comment by LC-Zorg** [comment]
I wrote how I see it, but it's rather not only my problem, since I often see in the game that players themselves shorten the names of the buoys. It is time consuming and yet they do it.

**Comment by frosch123** [comment]
There is already an option to hide signs of waypoint/buoys in the settings dropdown.
There have also been idea to move them into the transparency options window, but no draft was convincing so far.

More info:
https://wiki.openttd.org/en/Development/Design%20Drafts/Transparency%20options
https://www.tt-forums.net/viewtopic.php?t=54262
