### ISSUE TITLE
On Debian-based distributions, the executable should go to /usr/games, not /usr/bin

### ISSUE THREAD

**Issue by hpiirai** [OpenTTD/OpenTTD#8599]
## Version of OpenTTD
1.11.0-beta1

## Expected result
The OpenTTD executable is installed as `/usr/games/openttd`.

## Actual result
The executable is `/usr/bin/openttd`.

## Steps to reproduce
Install (or just unpack) any of the pre-packaged deb files from [https://www.openttd.org/downloads/openttd-releases/testing.html](https://www.openttd.org/downloads/openttd-releases/testing.html).

**Comment by James103** [comment]
As a workaround, can you try moving the `openttd` folder from `/usr/bin/` to `/usr/games/`?

**Comment by hpiirai** [comment]
> As a workaround, can you try moving the `openttd` folder from `/usr/bin/` to `/usr/games/`?

It’s not a folder, just the executable – everything else is installed correctly (manpage in `/usr/share/man/man6`, other game files in `/usr/share/games/openttd`).

Of course I could move it, but it works as is. This is not a functionality problem, just a matter of adhering to conventions of the rest of the system.

**Comment by Eddi-z** [comment]
I don't think this is an issue in the actual OpenTTD source code, but rather in the configuration of the build service for the .deb files

**Comment by Eddi-z** [comment]
FWIW, my distribution (openSUSE) doesn't use `/usr/games` and google says `/usr/games` is an old way of doing things

i honestly don't see the point, but if it's common in deb-based distros, it should be limited to those.

**Comment by glx22** [comment]
So we have two options:
- [restore default value as it was in configure](https://github.com/OpenTTD/OpenTTD/compare/master...glx22:fix_8599)
- [set the correct folder when building the release](https://github.com/OpenTTD/OpenTTD/compare/master...glx22:fix_8599_alt)

**Comment by TrueBrain** [comment]
@glx22 : I am fine with either one. Seems nobody else has an opinion about it either, so .. just pick one, I would say :D Which one helps the broader audience most, you think?
