### ISSUE TITLE
`terraform_frame_burst` (and similar settings) are stored to 16-bit integers instead of 32 bits.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8610]
## Version of OpenTTD
1.11.0 beta 1
## Expected result
`set terraform_frame_burst 131071` should set `terraform_frame_burst` to 131071. The setting is stored as a 32-bit int.
## Actual result
`set terraform_frame_burst 131071` sets `terraform_frame_burst` to 65535 due to a 16-bit unsigned integer overflow.
## Steps to reproduce:
Run the following console commands and notice the output:
```
set terraform_frame_burst
set terraform_frame_burst 131071
set terraform_frame_burst
```

**Comment by TrueBrain** [comment]
I looked at this ticket a few times, and did not really understand what you meant. But now with the fast-foward limiter setting, I get it. It is not so much that the value should be stored in 32-bit, rather that the maximum value was higher than the storage size. That makes sense :) So limiting the maximum value to be within the 16-bit size also solves the problem; as it was never possible to exceed it anyway, that doesn't give a regression, and avoids a savegame bump :D
