### ISSUE TITLE
Desktop file no longer installed

### ISSUE THREAD

**Issue by ghisvail** [OpenTTD/OpenTTD#8613]
## Version of OpenTTD

Version 1.11.0-beta1

## Expected result

Version 1.10.3 used to install `openttd.desktop` under `$PREFIX/share/applications`. It is no longer the case for version 1.11.0-beta1, probably missing as a result of the change of build system. This is likely to break downstream packaging efforts expecting this file to be present, like [Flatpak](https://flathub.org/builds/#/builders/35/builds/4468/steps/6/logs/stdio).

It should be enough to surround templated fields with `@@` and call `configure_file(..., @ONLY)` on the current [template](https://github.com/OpenTTD/OpenTTD/blob/1.11.0-beta1/media/openttd.desktop.in).

**Comment by glx22** [comment]
Ah yes should be part of these TODOs
https://github.com/OpenTTD/OpenTTD/blob/da78b5c13006dc420ebc2ade00be8ae5259a7494/cmake/InstallAndPackage.cmake#L61-L62

**Comment by ghisvail** [comment]
I was able to fix it as a post-install step in the [beta](https://github.com/flathub/org.openttd.OpenTTD/blob/58c0892805287509d87922629a298db295e78ce8/org.openttd.OpenTTD.yaml#L71) channel.

Thank you again for your recent pointers.

**Comment by ghisvail** [comment]
Apart for the missing media and desktop file integration, I expect the next stable release of the game should build fine downstream.

**Comment by TrueBrain** [comment]
As I don't really have another place to leave this information: you are currently parsing www.openttd.org to find the latest version. This is fine by me, but just so you know we also have this information in YAML format here: https://cdn.openttd.org/openttd-releases/latest.yaml ; might be useful :)

(similar we have those files for any other package we publish, like https://cdn.openttd.org/opengfx-releases/latest.yaml etc :))

**Comment by ghisvail** [comment]
@TrueBrain thanks, that's potentially very useful indeed. I'd have to check the capabilities of the Flathub parser first before considering a switch.
