### ISSUE TITLE
Unused sounds

### ISSUE THREAD

**Issue by Wuzzy2** [OpenTTD/OpenTTD#8619]
## Version of OpenTTD
1.11.0-dev (48698403a8a095611aa2575587008e7c7f419308)

A couple of sounds are unused:

* `SND_0D_STEAM` (OpenSFX: steam exhaust sound, like from a steam engine)
* `SND_11_CRASH` (OpenSFX: light crash sound, less dramatic than the `SND_13_BIG_CRASH` sound)
* `SND_22_CAR_HORN` (OpenSFX: empty sound)
* `SND_23_CAR_HORN_2` (OpenSFX: 'modern' car horn sound, twice)
* `SND_32_POP_2` (OpenSFX: empty sound; note that `SND_2F_POP` is the bubble pop for the Toyland bubble extraction)

Is it intentional or is this just an oversight?

**Comment by Wuzzy2** [comment]
By the way: If the sounds are really *intentionally* unused in OpenTTD, I think the corresponding sound IDs should be marked in the source code (via code comments).

**Comment by Wuzzy2** [comment]
OK. I was told by @frosch123 that the sounds are intentinoally unused. I therefore change the issue to this:

* Add comments in source code to mark the unused sounds

**Comment by frosch123** [comment]
Done in #8701
