### ISSUE TITLE
Too little spacing in newslog

### ISSUE THREAD

**Issue by Wuzzy2** [OpenTTD/OpenTTD#8620]
## Version of OpenTTD
1.11.0-dev (4869840)

## Expected result
In the news log, there is at least a little bit of spacing between the date and the news text

## Actual result
In the news log, there is no spacing between the date and the news text. The text directly follows after the date numbers, making it a little bit annoying to read.

## Steps to reproduce
1. Start a game
2. Wait for some news to be generated
3. Open the news log

**Comment by TrueBrain** [comment]
Would you mind attaching a screenshot of what you see? Font-size, font-family, etc, has a lot to do with any and all spacing in our UI, so having an idea of what you talk about helps a lot in evaluating possible fixes :D Tnx!

**Comment by Eddi-z** [comment]
I can't reproduce this (original grf)

![Ravenswald Transport, 27  Jun 1988#1](https://user-images.githubusercontent.com/43699911/106365758-ea49fa80-6337-11eb-9e80-12df4261031a.png)

**Comment by Wuzzy2** [comment]
I use double GUI size, double font size, and OpenGFX 0.6.0.
Interestingly, there's a little bit of spacing with default settings, however.

**Comment by Wuzzy2** [comment]
Image:
https://satoshiupload.com/images/6lV7x14EiD.png

![image](https://user-images.githubusercontent.com/1663690/106366626-5ed36800-633d-11eb-91e2-0af801276b88.png)
