### ISSUE TITLE
Profit window - Not all cargo colours are visible

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#8631]
## Version of OpenTTD
from 20210114-master (applies to change #8557)
## Expected result
Graphs of rates of all loads, of each industrial set are visible without scrutinizing.
## Actual result
For complex industrial sets, many lines of freight rates are dark and almost invisible. In the case of manganese (XIS) it is completely invisible.
![Bug - XIS Manganese 2](https://user-images.githubusercontent.com/67662046/106398396-cdcec080-6412-11eb-9fe7-0687882ea15b.png)
Challenge: Take a stopwatch and count the lines of the graphs ;)
## Possible solutions
1. Adding the option to select the background color of the graphs - there can be three options:
- bright (all windows)
- dark (all windows)
- dark except for the payment rate graph
2. Permanent use of a different dark background for the company performance graphs and another bright background for the rate graph - at the moment it would be consistent, as the rate graph, unlike the rest, it is the only one that remains unchanging. However, this may change with the addition of a planned and interesting production graph, or if the variable transport rate function was introduced.
3. Make the background color of the rate graph dependent on the request from the industrial addition - a light background would be used by default, but the new additions could force the use of a dark one.
4. Restore the background color to light and use a different solution for the faintly visible violet, dark green, and violet graph lines.

## Note
Too bright auxiliary grid additionally worsens legibility - this also needs to be changed (#8630)

**Comment by 2TallTyler** [comment]
Speaking as the author of an industry NewGRF (Improved Town Industries): the core game should not have to adapt to my colour choices when it is much easier for I, and other industry NewGRF authors, to change our sets to better suit the new graph. Before 1.11 is released in April, I'll take a look at any changes needed for ITI and release an update if required.

If there were popular industry sets which were no longer maintained, this might be a bigger problem, but as we only have a few -- FIRS by a long shot, possibly followed by XIS? -- and both of these are in active development, I think this is not worth worrying about.

I don't disagree with your other issues about grid contrast, but there are other issues to discuss those. :)

**Comment by TrueBrain** [comment]
1) if we are adding an option to change colours of windows, it will be in the form of themes (PRs welcome). Only adding a setting to change a single or a set of windows, is only adding another setting to the mix of settings we already have, and not something we are willing to do.

2) our UI is already a mess, and making different backgrounds for different graphs adds to that. Let's keep things consistent over all graph windows.

3) see 2)

4) no

All in all, NewGRFs authors indicated they will change their cargo colours; can I say I am really happy we have a community that goes: owh, yeah, sure, I will change this in my NewGRF. That is really really really cool, I am happy we have a community that is supportive of change like this :) So thank you for that guys!

That said, with that all in mind, I think this problem will be resolved by itself.

On a side-note: no matter what background colour you pick, it will always block certain colours from being used. The old grey we had was somewhere in the middle of it all, blocking out a lot of colours. By being a lot darker, it allows for more contrast colours that can be used by NewGRF authors. So in the bigger picture, having a darker background will only result in a better game. It might take a bit of time for all NewGRFs to get there, but in the end, it will be for the better!
