### ISSUE TITLE
Electric trains not going faster than 160km/h

### ISSUE THREAD

**Issue by robm82** [OpenTTD/OpenTTD#8642]
## Version of OpenTTD
1.10.3

## Expected result
When replacing electric trains for newer models, I would expect the train speed to increase (if applicable)

## Actual result
For some reason, the electric trains within OpenTTD do not go any faster than 160km/h. I upgraded all of my trains from SH 30 to SH 40, and the speed never increased from 160 to 177km/h. Then when I upgraded from SH 40 to T.I.M, the trains do not go above 160km/h even though they can go up to 241km/h. Power (hp) goes up as designed, but not the speed

## Steps to reproduce
I tried using the replace vehicle option, and manually replacing trains with newer models and the result is always the same. When replacing with a slower diesel, the speed is correct and is lower.

Here is a screenshot example of one of many trains that have this issue:
![image](https://user-images.githubusercontent.com/47445676/107067651-7e541000-67d7-11eb-8c9c-a9bc1680f1d7.png)

**Comment by nielsmh** [comment]
Are you using any NewGRFs?
Do you have wagon speed limits enabled?

Two things can limit the top speed, running on track that limits the top speed (that could be a NewGRF track type) and using wagons with a limited top speed (those would also come from a NewGRF).

**Comment by robm82** [comment]
> Are you using any NewGRFs?
> Do you have wagon speed limits enabled?
> 
> Two things can limit the top speed, running on track that limits the top speed (that could be a NewGRF track type) and using wagons with a limited top speed (those would also come from a NewGRF).

Thanks for reply - yes it seemed that the wagons were posing a speed restricted of 160KM/h which is weird as I don't think I have any NewGRFs that introduce any different types of wagons. I got around it by setting the enable wagon speed limits in the settings to off:

![image](https://user-images.githubusercontent.com/47445676/107212769-5c3cd680-69ff-11eb-8480-b29e54c81c39.png)


Thanks again for responding - didn't even realise that wagons could impose a speed limit on a train!
