### ISSUE TITLE
With win32 video driver, mouse movement is very sluggish

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/OpenTTD#8658]
## Version of OpenTTD

1.10.3 / 1.11.0-beta1

## Expected result

Mouse movement of at least 30fps.

## Actual result

Mouse movement of < 30fps.

## Steps to reproduce

Start the game on a recent updated Windows.

## Technical details

OpenTTD uses `Sleep(1)` to yield the process back to the OS when the gameloop was called before the next tick. It handles events, updates the mouse etc, and then does a `Sleep(1)`. In the old days, this yielded for a few ms. With recent update of Windows, it yields for 60+ms. This delay is so severe, that the game will miss its deadline for the next tick, but for me even worse: mouse movement feels really sluggish.

It is most likely related to: https://randomascii.wordpress.com/2020/10/04/windows-timer-resolution-the-great-rule-change/

This was found when fiddling with SDL2 on Windows. SDL sets the timer resolution to a much higher value (so lower ms), resulting in a much smoother mouse movement. So possibly we can borrow the solution there in our own codebase.

**Comment by erenes** [comment]
I don't think I really notice this at all (OTTD 1.10.3 + Win 10 20H2 19042.746). 
I can tell the mouse cursor is drawn quite slowly if I move the mouse slowly, but it always points where I want it.

**Comment by James103** [comment]
From the blog post, the bug should not occur on Windows 10 1909, even though you should be able to reproduce the bug on Windows 10 2004.

**Comment by glx22** [comment]
Can't test as I'm still on 1909, but I wonder if music playback with dmusic driver is affected, as it also uses Sleep().
BTW it should be quite trivial to fix (I already have some ideas).

**Comment by glx22** [comment]
Not opening a pull request as I can't really test if it fixes the problem, but I have a possible solution [here](https://github.com/OpenTTD/OpenTTD/compare/master...glx22:windows_sleep)

**Comment by TrueBrain** [comment]
Measurements via TIC/TOC:

With your patch: ~7ms per `CSleep(1)`.
Without your patch: ~46ms per `CSleep(1)`.

SDL (on Windows): ~7ms per `CSleep(1)`.

So yeah, works for me :D
