### ISSUE TITLE
Orders not showing correctly in the UI

### ISSUE THREAD

**Issue by fmodesto** [OpenTTD/OpenTTD#8661]
## Version of OpenTTD
1.10.x 1.11.0-beta

## Expected result
Options stick in the UI

## Actual result
Options are working but not stick in the UI.

## Steps to reproduce
Select train / Orders / Full load any cargo, Full load all cargo, No loading

The three types are selectable but doesn't stick in the UI. It prevents using shortcuts to select unselect them.

**Comment by nielsmh** [comment]
I'm not sure what you mean, or what you are doing.
The full load/no loading/force unload are modifiers for existing orders. You need to select one or more orders and then use those buttons to mark the loading/unloading rules for those selected orders. If this didn't work someone else would have reported it a year ago.

**Comment by LC-Zorg** [comment]
> I'm not sure what you mean, or what you are doing.

I had the same problem. :)

But ok, I think I understand. For me, the method of selecting orders where some is visible on top and some is hidden on the list is not a good solution.

If I understand correctly what fmodesto expects, these would be all the orders available in the form of buttons. Yes?

Out of curiosity, I made a small attempt of how it could look like...

**Version 1** - With all orders on top
![Orders window - with all orders on top v1 2](https://user-images.githubusercontent.com/67662046/107445659-31589c80-6b3d-11eb-9ef6-022cbb854582.png)

**Version 2** - with changed logic
![Orders window - change logic v0 1](https://user-images.githubusercontent.com/67662046/107445684-3ae20480-6b3d-11eb-85ae-4b263a0e9fc2.png)

-Press LMB to select the next available order
-Press LMB+Ctrl to select the previous one
-Press RMB to open a selection from the list

**Version 3** (alpha) ;) - combination of orders and timetable into one window; defining orders by icons
![Orders window v2 7](https://user-images.githubusercontent.com/67662046/107445695-40d7e580-6b3d-11eb-8dbf-dc0afb23662d.png)

Another, earlier variant
![Orders window v0 2b](https://user-images.githubusercontent.com/67662046/107445710-48978a00-6b3d-11eb-889f-8f52d9b4d6a7.png)

The orders window is one of the most demanding improvements. It is illegible, not intuitive, and creating orders is overly absorbing. It would be worth changing something.

**Comment by fmodesto** [comment]
Sorry I was a bit cryptic. This is a subset of my hotkeys.cfg:
```
[order]
fullload = J
no_load = L
```

If inside any order I select the station and press J, it toggles between setting "Full load any cargo" or removing it. 
But If I press L, it only sets the "No Loading" option, it never removes it.

Furthermore in the UI when selecting "Full Load any Cargo" or pressing key "J" it updates the options below.
But when selecting "No loading" or pressing "L" it doesn't update the options.
![Sprite-0001](https://user-images.githubusercontent.com/1070143/107473457-abeae180-6b68-11eb-9fc2-7bd1d8534f09.png)

I'm using the Windows 64-bit version.

**Comment by embeddedt** [comment]
I'm not sure why @LC-Zorg's comment was marked as off-topic. I understand that it doesn't relate directly to the reported issue, but I have also experienced difficulties with explaining how this window works to newer players. A redesign (even if less major than what was suggested) might not be a bad idea to consider.
