### ISSUE TITLE
Company HQ cannot be bulldozed

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#8662]
## Version of OpenTTD

1.11.0 beta (and earlier).

## Expected result

Players can bulldoze their own HQ.

## Actual result

Nothing happens to the HQ, but other tiles in the bulldozed area are cleared.

If the bulldozed area selection begins on the HQ, a message appears saying `Can't clear this area...`, otherwise no message appears.

Magic Bulldozer successfully demolishes the HQ.

## Steps to reproduce

1. Build HQ
2. Attempt to bulldoze

**Comment by orudge** [comment]
I'd argue this isn't a bug, just the behaviour working as designed (and the same way that TTD and TTO previously worked too).

**Comment by TrueBrain** [comment]
I agree, the behaviour is fully intended. How dare you remove the place you work from?! Relocate or go home!

What is a bug in my opinion, is that deleting the HQ gives an odd error. It should just say: "Can't clear this area .... how dare you remove the roof above my head!" (it now only says: "Can't clear this area ....")

:D
