### ISSUE TITLE
Publish a docker image

### ISSUE THREAD

**Issue by psh** [OpenTTD/OpenTTD#8663]
## Version of OpenTTD
production - 1.10.3 or later

## Feature Requested
To facilitate the influx of players who will want to play multiplayer (after going live on Steam), it would be nice to have a docker image, and documentation, for running a headless dedicated server.

## Are you willing to work on this issue

- [x] Yes

- [ ] No

**Comment by LordAro** [comment]
I don't see why a docker image is necessary. Documentation is here:
https://github.com/OpenTTD/OpenTTD#14-installing-and-running-openttd
&
https://github.com/OpenTTD/OpenTTD/blob/master/docs/multiplayer.md

(Though any and all improvements are welcome!)

**Comment by psh** [comment]
Why docker?  What I was specifically thinking was having the ability to launch a dedicated server on a service like Digital Ocean without much effort.  I went hunting based on the links you posted.  It looks like someone has a docker image for running a dedicated server - https://registry.hub.docker.com/r/bateau/openttd/ - so I'll start experimenting from there.

**Comment by TrueBrain** [comment]
Other alternatives I know about:
- https://github.com/ich777/docker-openttd-server
- https://github.com/ropenttd/docker_openttd 

So as far as Docker images, I think the community got us covered. They are easily findable if you search for them, as you also found out. That only means we are mostly lacking a wiki page on https://wiki.openttd.org pointing out they exist and where to find them. Maybe you could help us with that?

For Docker images, where you have many choices how to implement it, it is good to let the community figure out what works best. You can clearly see that between these three images: they are pretty different, yet they do the same. It is pretty nice :)

Their documentation on how to run a dedicated server is also pretty solid.

So, in general, I am fine with how things are currently. Anything we as core-team don't have to maintain is a big win for me :) Means we have more time to focus on the stuff we love to do: improve the game :P

That said, I am in no way against having an "official" Docker image; but which of the three should we pick (as reinventing the wheel would be silly). I don't think that is fair to the other two .. so yeah, to me, a wiki page mentioning that there are multiple to pick from and where they can be found, would be more than sufficient for people to find them and run their own server :D

I love our community :D

Going to close this issue for now; if you (strongly) disagree, please do let us know. This is not a hard "no" or anything, just more: we already have this, and we don't think we should change the current status quo :)

Tnx!
