### ISSUE TITLE
Crash on macOS Big Sur after downloading graphics to 200%

### ISSUE THREAD

**Issue by EdisonDD** [OpenTTD/OpenTTD#8670]
I'm having an issue where OpenTTD won't open on MacOS Big Sur. it'll download the graphics up to 200% then crash

## Version of OpenTTD
1.10.3

## Expected result
Game will download 100% of the graphics then open

## Actual result
Game will download 200% of graphics, then crash

## Steps to reproduce
1. download OpenTTD as an Apple disk image.
2. Click "yes download the graphics"

**Comment by TrueBrain** [comment]
Some questions before we can pick this up:

What OpenTTD version is this with? We do not have "10.12", so I am a bit confused :D

What kind of crash is this? Does it just stop? Does it give you a window? And is there a `crash.log` created? If so, can you please attach this.

Tnx!

**Comment by orudge** [comment]
Could you try OpenTTD 1.11.0-beta1 from our site please and see if the same happens?

**Comment by EdisonDD** [comment]
> Some questions before we can pick this up:
> 
> What OpenTTD version is this with? We do not have "10.12", so I am a bit confused :D
> 
> What kind of crash is this? Does it just stop? Does it give you a window? And is there a `crash.log` created? If so, can you please attach this.
> 
> Tnx!

Sorry, little correction: I'm on 1.10.3
<img width="652" alt="Screen Shot 2021-02-13 at 4 56 17 PM" src="https://user-images.githubusercontent.com/79023260/107862715-a5849000-6e1c-11eb-8e0e-0c7235ef3eef.png">

This is a screen shot

**Comment by James103** [comment]
@EdisonDD Do you have the `crash.log` for such a crash? If so, can you post that here?

**Comment by TrueBrain** [comment]
And more importantly, did you try what @orudge suggested, and see if 1.11.0-beta1 has the same issue? You can find the download here: https://www.openttd.org/downloads/openttd-releases/testing.html

Cheers!

**Comment by TrueBrain** [comment]
@EdisonDD : did you have the time to try out 1.11.0-beta1, to see if the issue has been resolved?

**Comment by EdisonDD** [comment]
I tried out 1.11 beta1 and the issue is resolved. Thanks for the help. I had a lot of work so I didn't have time to respond immediately. Thanks for the help!

**Comment by LordAro** [comment]
Thanks for the confirmation!
