### ISSUE TITLE
Crash when opening settings window

### ISSUE THREAD

**Issue by Ufiby** [OpenTTD/OpenTTD#8676]
## Version of OpenTTD
20210215-master-gdb246b82ac
## Expected result
Should open the setting
## Actual result
To open the setting causes an accident
## Steps to reproduce
![OpenTTD](https://user-images.githubusercontent.com/46504018/107991332-72dac300-6fe7-11eb-9392-b8c348ba46b2.png)

**Comment by James103** [comment]
I assume you mean a crash? If so, can you post the corresponding `crash.log`, `crash.dmp`, and `crash.png` files here (zip the `crash.dmp` first)?

**Comment by Ufiby** [comment]
[OpenTTD.zip](https://github.com/OpenTTD/OpenTTD/files/5984030/OpenTTD.zip)

**Comment by James103** [comment]
```
Crash reason:
 Message:   Assertion failed at line 883 of ..\src\settings_gui.cpp: this->setting != nullptr
```
Can you try resetting your `openttd.cfg` to default values? For example, move `OpenTTD.cfg` from `C\Users\[user]\Documents\OpenTTD` to another folder to allow you to keep the file while also generating a new default configuration.

**Comment by Ufiby** [comment]
This will not help to solve the problem in any way

**Comment by James103** [comment]
It crashes for me in `20210215-master-gdb246b82ac`, but does not crash for me in `20210213-master-g0f621b4956`. Likely a regression from PR #8566.

**Comment by LordAro** [comment]
https://github.com/OpenTTD/OpenTTD/compare/0f621b4956...db246b82ac

More likely  https://github.com/OpenTTD/OpenTTD/commit/a2c3197f424daa6e02201d8304015b0eb67d0b04

It's being worked on
