### ISSUE TITLE
GRF scanner progress updating no longer works due to _realtime_tick changes

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#8697]
## Version of OpenTTD
Since d437445c67bb76713614ae5a4242168c891b9978

Checked on SDL2 and Win32/WINE

It appears that DrawDirtyBlocks/HasModalProgress releases the locks so that the scanner thread can progress, but as _realtime_tick is no longer updated, the scanner thread will not release the locks to allow DrawDirtyBlocks/HasModalProgress to re-acquire them until all scanning has completed.

## Expected result
NewGRF scanner window periodically updates at startup.

## Actual result
NewGRF scanner does not update, the entire window is frozen until the scan completes.

## Steps to reproduce
Run the game (preferably with lots of NewGRFs).

**Comment by glx22** [comment]
I can confirm the issue with my 1305 NewGRFs :)

**Comment by TrueBrain** [comment]
"oops".

Sorry :)

Happy you spotted this so quickly!
