### ISSUE TITLE
Vehicle list windows fail to update profit display whilst open, after 584df54

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/OpenTTD#8705]
## Version of OpenTTD

https://github.com/OpenTTD/OpenTTD/commit/584df548f1bdfa27482aa995d151542abe4f0bca

## Expected result

An open vehicle _list_ window should continuously update profit per vehicle (this year / last year), which changes as vehicle travels, earns income etc.

## Actual result

An open vehicle _list_ window  profit per vehicle (this year / last year) shows profit per vehicle as calculated when the window was opened, or when a different vehicle group was switched to (in case of windows with groups)

## Steps to reproduce

- Start game, build a vehicle and a short route, set it running
- Open the 'all vehicles' window, observe profit per vehicle.  
- Open and close window, observe updated profit per vehicle.  
- Change group, observe updated profit per vehicle.
- Add a station, observe same behaviour in 'vehicles for this station' window.  

<img width="349" alt="8705" src="https://user-images.githubusercontent.com/1780327/108602544-5dc0b400-739a-11eb-84c7-53caf674613f.png">

**Comment by stormcone** [comment]
I think it's a duplicate of #8575.

**Comment by andythenorth** [comment]
> I think it's a duplicate of #8575.

Agree, closing.
