### ISSUE TITLE
Win32 OTTD2FS/FS2OTTD used from multiple threads but use a static buffer

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#8713]
## Version of OpenTTD
master

## Expected result
No thread safety issues

## Actual result
The OTTD2FS/FS2OTTD functions are used in a wide variety of places in the codebase, including indirectly from non-main threads. (e.g. file scanner thread, network threads when debug output is on, crash logger). Various macros also use these functions (e.g. fopen, MB_TO_WIDE/WIDE_TO_MB, etc.).

On Win32, these methods use a static buffer, and return a pointer to that buffer.
In the event that the method is called from multiple threads in the same general time frame, callers could receive output from a different thread. Theoretically this could result in a buffer over-read if a thread is reading the buffer at the same time as another is in the middle of writing it.

I used TLS to make this go away: https://github.com/JGRennison/OpenTTD-patches/commit/0a61671ff15e3c05835632a447421597f618348b. std::string conversion could also be an option.

## Steps to reproduce
I'm sure there must be a way of automatically detecting this on Windows.

**Comment by nielsmh** [comment]
`unix.cpp` also appears to use a global iconv instance and global buffers.
