### ISSUE TITLE
Vehicles not rendered in 2CC when dragged inside a depot

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#8734]
## Version of OpenTTD

Not present in 1.10.3, but found in a build of master when the latest commit was c93c9c0. I have not investigated when exactly this began.

## Expected result

When dragging a vehicle inside a depot, it remains the proper company colour.

## Actual result

The company colour is lost and it reverts to the 1CC blue of the sprite.

![depot_no_2cc](https://user-images.githubusercontent.com/55058389/108896844-6657fb00-75e3-11eb-8dd7-d2328dcefd4c.PNG)

## Steps to reproduce

1. Build a depot
2. Buy a vehicle
3. Drag it to the Sell button, or anywhere else

**Comment by TrueBrain** [comment]
Happens only with OpenGL driver for me on Windows, both `8bpp-optimized` as `40bpp-anim`
Does not happen with non-OpenGL driver.
