### ISSUE TITLE
Transparency of houses, etc., rendered too dark

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#8735]
## Version of OpenTTD

Not present in 1.10.3, but found in a build of master when the latest commit was c93c9c0. I have not investigated when exactly this began.

## Expected result

Transparent objects like houses look like this:
![shadow_current](https://user-images.githubusercontent.com/55058389/108897757-70c6c480-75e4-11eb-8445-cfcd3f6120ec.PNG)

## Actual result

They look like this, much darker and with ugly noise:
![shadow_new](https://user-images.githubusercontent.com/55058389/108897913-96ec6480-75e4-11eb-9c9f-4391782ad931.PNG)

I assume this is not intentional. 🙂 

## Steps to reproduce

1. View houses in transparency mode

**Comment by James103** [comment]
Are you running OpenTTD using OpenGL (`openttd -v sdl-opengl`)?

**Comment by TrueBrain** [comment]
Happens with `8bpp-optimized`, no matter what your driver is. Will bisect :)

**Comment by TrueBrain** [comment]
Well, I went down a weird rabbit hole there, but what you are seeing is the 32bpp blitter vs the 8bpp blitter. There are less "grey" in the 8bpp, so it quickly becomes weirdly dark .. has always been that way.

OpenGL now starts in 8bpp by default, if there is no need for 32bpp. This is a change into how it was before, and that is what you are seeing.

Another argument to make 32bpp default :)

**Comment by 2TallTyler** [comment]
> Another argument to make 32bpp default :)

+1 from me. But since this isn't a bug, I'll close the issue.
