### ISSUE TITLE
Disconnecting clients affect other clients in the queue

### ISSUE THREAD

**Issue by ldpl** [OpenTTD/OpenTTD#8751]
## Version of OpenTTD
master (af326753a95489459c509088010350d09b0af1f8), 1.10.3, 1.9.3

## Expected result
Client connects without issues regardless of what other clients do.

## Actual result
Client loses connection

## Steps to reproduce
1. Start a network server. (larger map size and no indusries will make testing easier)
2. Start two clients and select that server
3. Join the server on both clients at about the same time
4. Cancel first client while it is downloading the map
5. Second client will fail to connect

There is also a variation of this bug where second client gets desync. Happens when first client connects with "new company" and leaves the server before the second one finishes downloading the map.

P.S. it also says 0 clients in front of you while waiting

**Comment by JGRennison** [comment]
It appears that clients only transition out of STATUS_MAP_WAIT in the success path of ServerNetworkGameSocketHandler::SendMap of the client in the STATUS_MAP phase.
Also doing that check in the failure paths ought to make that go away.

The 0 clients thing just looks like an off by one error in ServerNetworkGameSocketHandler::SendWait(), probably the initial value should be 1.

**Comment by ldpl** [comment]
And desync happens because clients are not queued so by the time second client executes COMPANY_CTRL first client is already gone and company is not created. So it may actually need to be moved to a separate bug as it can likely cause issues not just for connecting players but in other cases as well (e.g. client lag).

**Comment by JGRennison** [comment]
That seems like a misdesign of CmdCompanyCtrl really. It shouldn't be the job of clients to synchronously track the states of other clients.
Probably the client ID check could be just removed entirely. It looks like everything would be fine if ci is nullptr.

**Comment by TrueBrain** [comment]
> 
> P.S. it also says 0 clients in front of you while waiting

Linguistic this is correct. There is nobody *waiting* in front of you :P

An additional bug: if the client in `SEND_MAP` is taking for-ever, everyone in the queue gets a notification that the server is not responding. There is no ping/pong while waiting, I guess.

**Comment by ldpl** [comment]
Suddenly remembered, this desync may actually be the one I was looking for in #8093
