### ISSUE TITLE
Alignment issues dragging articulated vehicles in depot

### ISSUE THREAD

**Issue by mattkimber** [OpenTTD/OpenTTD#8762]
## Version of OpenTTD

Nightly 20210226-master-gaf326753a9

## Expected result

This is the result of dragging a vehicle from a NewGRF providing articulated vehicles in 1.11 beta 1:

![drag_work](https://user-images.githubusercontent.com/13691859/109403005-7e68ab00-7952-11eb-990a-54dff5281127.png)

## Actual result

This is the result in a recent nightly:

![drag_nightly](https://user-images.githubusercontent.com/13691859/109403014-950f0200-7952-11eb-97d4-e92f837923ba.png)

The articulated units split apart and become misaligned. This is an extreme case (Timberwolf's Trains has each vehicle composed of 3 articulated units, so the screenshot is actually a 6-unit articulated vehicle) but can be observed in any GRF which provides articulated vehicles, either road or rail.

This does not affect non-articulated vehicles, or vehicles using the built-in "double-headed" logic. It may only affect vehicles shorter than 8/8, I was unable to assemble enough GRFs to test this theory.

I also noted in this version that the vehicles do not align with the "sell vehicle" and other buttons, this may be related.

## Steps to reproduce

Install a NewGRF providing articulated vehicles (tested: Timberwolf's Trains, Timberwolf's UK Road Vehicles 3, Bob's Random British Vehicles).
Build an articulated vehicle in depot.
Drag the vehicle.

**Comment by stormcone** [comment]
Can you try with the current nightly (2021-02-27)? I think #8757 should have solved this problem.

**Comment by mattkimber** [comment]
Yep, latest nightly fixes the problem. (I managed to miss that issue while looking to see if one was already open :/ )
