### ISSUE TITLE
Start/stop icon in vehicle status bar is off-center vertically

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8770]
## Version of OpenTTD
1.11.0-beta2

## Expected result
The start/stop icon in the vehicle status is centered vertically properly with the text, as shown here:
![image](https://user-images.githubusercontent.com/37945304/109432884-fd9dc380-79d2-11eb-81b3-0626dbc68a5b.png)
(1 pixel movement upwards is sufficient to cover both the stopped flag and the running flag)

## Actual result
The start/stop icon in the vehicle status is not fully centered properly on the vertical axis despite the works of #8602, as shown here:
![image](https://user-images.githubusercontent.com/37945304/109432854-d3e49c80-79d2-11eb-809d-fb6ebc7752df.png)

## Steps to reproduce
1. Start a new map.
2. Build a depot, and buy any vehicle.
3. In the vehicle window, look at the statusbar. Notice that the icon is off-center vertically.
4. Start the vehicle (or stop it).
5. Notice that the icon is still off-center.

**Comment by LordAro** [comment]
Quad zoom to make it a little more obvious:

![image](https://user-images.githubusercontent.com/4007992/109433055-4fac0c80-7a06-11eb-88bb-4c441b83ba5f.png)

**Comment by PeterN** [comment]
The sprite is centred, it just has offsets that mean the centring places it lower. However with 10114 a lot of sprites are now drawn ignore offsets, so this could be done here too.
