### ISSUE TITLE
Blur with new grpahics dirver support

### ISSUE THREAD

**Issue by Rau117** [OpenTTD/OpenTTD#8771]
## Version of OpenTTD
1.11.0-beta2

## Expected result
Regular OpenTTD picture
![Снимок экрана (1099)](https://user-images.githubusercontent.com/47086324/109434234-5e55ec00-7a25-11eb-9de4-7c73e2c5ef51.png)

## Actual result
Sticky letters, blur on map
![Снимок экрана (1098)](https://user-images.githubusercontent.com/47086324/109434224-5138fd00-7a25-11eb-9203-3495f52167ac.png)

## Steps to reproduce
Not needed. Tested with clear openttd.cfg and original_windows base graphics

**Problem was solved by changing graphic card settings to default for openttd.exe**

**If you have same problem try to run openttd via another graphics card or create individual profile for openttd.exe in your card driver settings/control panel**

**Comment by nielsmh** [comment]
You need to provide some more information, because I don't get any blurring like that.

- What operating system and version?
- What GPU?
- What graphics driver and version?
- Do you use display scaling?
- Do you have any override settings in your graphics driver, such as forced antialiasing?

![image](https://user-images.githubusercontent.com/1062071/109434974-2e541c00-7a18-11eb-8478-50d9fcbf2489.png)

**Comment by michicc** [comment]
One possible explanation for the font differences: we modified default blitter choices. If the openttd.cfg previously allowed using an 8bpp blitter (e.g. through the support8bpp setting), we would use one, no matter if font anti-aliasing was enabled or not. Now we always try selecting a 32bpp blitter if anti-aliasing is enabled.

**Comment by nielsmh** [comment]
> 
> 
> One possible explanation for the font differences: we modified default blitter choices. If the openttd.cfg previously allowed using an 8bpp blitter (e.g. through the support8bpp setting), we would use one, no matter if font anti-aliasing was enabled or not. Now we always try selecting a 32bpp blitter if anti-aliasing is enabled.

Look at the edges of roads (red and yellow stripes), it's very clear there is some kind of blurring going on there, it's not just text that's affected.

**Comment by michicc** [comment]
I can't reproduce that in any shape or form.

Purely theoretical, I can think of two reasons: Either the window size doesn't match what we draw, but that would entail Windows somehow lying to us about it. Or there's some kind of filtering going on in the graphics driver (like maybe always enabled anti-aliasing, texture anisotropy or something like that).

**Comment by PeterN** [comment]
@Rau117 as you closed this, did you manage to solve the issue? If so a pointer to the cause/solution would be useful, thanks!
