### ISSUE TITLE
Some screenshot buttons produce all-black screenshots

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#8774]
## Version of OpenTTD
1.11.0-beta2

## Expected result

The screenshot button captures screenshots.

## Actual result

Some of the screenshot buttons save a screenshot which is all black pixels:
- Fully zoomed in screenshot
- Default zoom screenshot
- Whole map screenshot

The other buttons (Normal screenshot, Heightmap screenshot, and Minimap screenshot) all work as intended.

## Steps to reproduce

Attempt to take a screenshot using the screenshot menu.

**Comment by perezdidac** [comment]
Taking a screenshot using the keyboard screen capture key on Windows 10 also produces a black image. I see the mouse though!

**Comment by James103** [comment]
Which video driver were you running? Can you try using other video drivers and/or blitters to see if that still reproduces the issue? It could be that some of the screenshots being blank are specific to certain video drivers and/or blitters.

**Comment by Eddi-z** [comment]
please note that those screenshot types can be much larger than your screen, and areas that are not on the map are filled in black. try zooming or scrolling and check that there are really no non-black areas in the screenshot file

also some image viewers may have problems with large files

**Comment by TrueBrain** [comment]
Confirmed. OpenGL only. Needs triage :)

**Comment by TrueBrain** [comment]
More specific, it is the `40bpp-anim` blitter.
