### ISSUE TITLE
Fullscreen OpenTTD cannot be alt-tabbed back into

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#8775]
## Version of OpenTTD

1.11.0-beta2
(I have not bisected to find when this started, but it works fine in 1.10.3)

## Expected result

On Windows 10: When running OpenTTD in fullscreen mode and having alt-tabbed to another window, it is possible to alt-tab back to OpenTTD.

## Actual result

Alt-tabbing back to OpenTTD does not show the OpenTTD window.

## Steps to reproduce

Put OpenTTD into fullscreen mode on Windows 10, alt-tab to another window, and then attempt to alt-tab back.

**Comment by TrueBrain** [comment]
Confirmed, only happens with OpenGL.

Who plays FullScreen in this day and age?! :P

**Comment by decitrig** [comment]
I just experienced this as well. Crash information attached.

[openttd_crash.zip](https://github.com/OpenTTD/OpenTTD/files/6062122/openttd_crash.zip)

**Comment by James103** [comment]
@decitrig Did you reproduce this crash simply by alt-tabbing back to OpenTTD when it is in fullscreen? If now, how did you get the crash?

**Comment by decitrig** [comment]
Yes, sorry for being unclear. The crash happened just by alt-tabbing back into a fullscreen OpenTTD. The crash did not happen with a windowed OpenTTD.

Let me know if you need more info.

**Comment by James103** [comment]
Doing the following reproduces the issue but allows you to get back into windowed mode:
1. Start OpenTTD in windowed mode.
2. Alt-Enter to make OpenTTD fullscreen.
3. Alt-Tab out of OpenTTD.
4. Alt-Tab back to OpenTTD. The OpenTTD window does not actually get focused.
5. Alt-Enter to exit fullscreen for OpenTTD.
