### ISSUE TITLE
Alt-Enter to make OpenTTD fullscreen desyncs actual fullscreen state from toggle in Game Options

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8784]
## Version of OpenTTD
OpenTTD 1.11.0-beta2 on Windows 10
Started with `openttd -v win32-opengl -b 40bpp-anim` (autodetected defaults with my setup)

## Expected result
When you use Alt-Enter to make OpenTTD full-screen while the Game Options window is open, the fullscreen toggle is visually pressed inside said window immediately once full-screen mode is enabled.

## Actual result
When you use Alt-Enter to make OpenTTD full-screen while the Game Options window is open, the fullscreen toggle gets visually desynced from the actual fullscreen state, until you reopen the Game Settings window.

## Steps to reproduce
1. Start OpenTTD in windowed mode with the given settings.
2. Open Game Options.
3. Alt-Enter to make OpenTTD fullscreen.
4. Notice that OpenTTD is fullscreen, but the fullscreen toggle is not on.
5. Close and re-open Game Options.
6. Notice that the fullscreen toggle is now on, as expected when OpenTTD is fullscreen.
7. Alt-Enter to exit fullscreen mode for OpenTTD.
8. Notice that OpenTTD is windowed, but the fullscreen toggle is still on.
9. Close and re-open Game Options.
10. Notice that the fullscreen toggle is now off, as expected when OpenTTD is windowed.

Discovered while testing #8775

**Comment by LordAro** [comment]
I've reproduced this too, on Linux (using Win+F to fullscreen in that case, but whatever)
Around the same time I got a crash as well. Didn't look further, but I suspect this & #8775 are the same issue.

**Comment by TrueBrain** [comment]
Sounds like a missing "mark dirty" on the window :)
