### ISSUE TITLE
OpenTTD doesn't start properly after a clean installation

### ISSUE THREAD

**Issue by giordy** [OpenTTD/OpenTTD#8785]
## Version of OpenTTD
1.11.0-beta2

MacOS Big Sur 11.2.2

## Expected result
After installing OpenTTD and starting it, I would expect that it downloads the base packages and start.

## Actual result
The window stays black and non responsive

https://user-images.githubusercontent.com/6016950/109538589-8f372f00-7ac0-11eb-825b-c61057c6e658.mp4

## Steps to reproduce
1. Make sure that OpenTTD is not installed
2. install the version 1.11.0-beta2
3. Start OpenTTD

I tried it from the command line and I could see this output:

```
dbg: [driver] Could not change to foreground application. Error -50
dbg: [freetype] Font is missing glyphs to display char 0xB3 in medium font size
```

**Comment by James103** [comment]
What do you get if you run `openttd -d 3` from a clean first-time installation? If that doesn't help, what output do you get if you run `openttd -d 9` from the same first-time installation?
Pipe the output (or copy-paste it) to a text file, then upload the file here.

**Comment by giordy** [comment]
In both cases I got the same results as above. 

I attach the output of the commands you asked me to run:
[openttd-d3.txt](https://github.com/OpenTTD/OpenTTD/files/6063610/openttd-d3.txt)
[openttd-d9.txt](https://github.com/OpenTTD/OpenTTD/files/6063611/openttd-d9.txt)

**Comment by Ufiby** [comment]
Same thing with the Window 10

**Comment by PeterN** [comment]
This issue is introduced by c4df0f95a

**Comment by TrueBrain** [comment]
While a fix is pending, the solution till our next release is to either use another version of OpenTTD to bootstrap, or to download [OpenGFX](https://cdn.openttd.org/opengfx-releases/0.6.0/opengfx-0.6.0-all.zip) manually and unzip (!) it in your `baseset` folder in your OpenTTD folder.

Sorry about this, and tnx for reporting; this is exactly why we release betas :D
