### ISSUE TITLE
Die with failed assertion on MacOSX with cocoa-opengl driver

### ISSUE THREAD

**Issue by scovit** [OpenTTD/OpenTTD#8808]
## Version of OpenTTD
1.11.0-beta2

## Expected result
Play game

## Actual result
Assertion failed messagebox and crash:

Assertion failed at line 50 of /Users/runner/work/OpenTTD/OpenTTD/src/blitter/40bpp_anim.cpp: VideoDriver::GetInstance()->GetAnimBuffer() != nullptr

## Steps to reproduce
Start the game with `./openttd -v cocoa-opengl`

[crash.log](https://github.com/OpenTTD/OpenTTD/files/6094332/crash.log)

**Comment by James103** [comment]
Can you please try the following?
1. Run `./openttd -v cocoa-opengl -d 9`
2. Pipe the output from the command to a file.
3. Upload that file here.

**Comment by scovit** [comment]
Here it is:

[debugging-stderr.txt](https://github.com/OpenTTD/OpenTTD/files/6094406/debugging-stderr.txt)
[debugging-stdout.txt](https://github.com/OpenTTD/OpenTTD/files/6094408/debugging-stdout.txt)
