### ISSUE TITLE
Assertion failed downloading content from BaNaNaS.

### ISSUE THREAD

**Issue by spnda** [OpenTTD/OpenTTD#8814]
## Version of OpenTTD
master @ 2860de7

## Expected result
It downloads the content fine (currently just tested NewGRFs).

## Actual result
```
File: minknernel/crts/ucrt/src/appcrt/lowio/lseek.cpp
Line: 103

Expression: _osfile(fh) & FOPEN
```

Errors out at:
https://github.com/OpenTTD/OpenTTD/blob/2860de7bf448b5d1170256ab4aa833eb72b45ed8/src/network/network_content.cpp#L414

## Steps to reproduce
Build the game from master, run the game, try to download any newgrfs from the content downloader.
Using latest vcpkg with all packages updated to latest versions. (This seems to be a new recent issue, never encountered this before.) I also recently updated VS2019.

**Comment by spnda** [comment]
Some context when the exception is thrown. (Downloading Polish PKP Set 2.0.11)
![image](https://user-images.githubusercontent.com/43609023/110224923-6cea4a80-7ee0-11eb-8c38-f392cdee09a6.png)

The exact error message:
```
Unhandled exception at 0x00007FF84AF7AFEC (ucrtbased.dll) in openttd.exe: 
An invalid parameter was passed to a function that considers invalid parameters fatal.
```

**Comment by TrueBrain** [comment]
I too have this issue. It also happens for me when I make a screenshot.

It only happens when I build a version myself; it does not happen with official binaries.

In VSCode, you have to hit "Ignore" first to get the debugger to tell you where it failed.

**Comment by TrueBrain** [comment]
Error with whole map screenshot:

```
Exception has occurred: W32/0xC0000409
Unhandled exception at 0x00007FF9AF3CB7EC (ucrtbased.dll) in openttd.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.
```

at screenshot.cpp, line 388. 387 is calling `png_write_row`.

**Comment by PeterN** [comment]
I switched from x64-windows to x64-windows-static (like the official binaries use) and this seems to have solved the issue. I wonder if there's some core DLL mismatch happening with the shared versions.

**Comment by PeterN** [comment]
https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=msvc-160

> string(REPLACE "/MD" "/MT" ${MSVC_FLAGS} "${${MSVC_FLAGS}}")

This line in CompileFlags.cmake is forcing use of the static LIBCMT[D] lib.
If the vcpkg dependencies are built as shared libraries, then they link with MSVCRT instead, causing the conflict.

This problem doesn't occur with the official binaries because they are built with static dependencies.

I would expect a warning about conflicts though, as you get when you DON'T use /MT when compiling against static libs...

**Comment by glx22** [comment]
I guess it should be possible to analyse vcpkg triplets to determine compile flag.
