### ISSUE TITLE
"Place Objects" menu sorts objects alphabetically even when there are no filter string provided.

### ISSUE THREAD

**Issue by Azusa257** [OpenTTD/OpenTTD#8817]
## Version of OpenTTD
Tested on the latest nightly (openttd-20210306-master-g2860de7bf4-windows-win64)

possible issue with PR #8603 
## Expected result
When the "filter strring" field is empty, it is expected of the game to sort the placeable objects with their default behaviour (to list them in their NewGRF load order). 

The list should only be sorted alphabetically once the user starts entering string into the filter.
## Actual result
The object menu lists the objects in alphabetical order without any input in the search box.
![image](https://user-images.githubusercontent.com/76620903/110229264-7fe63480-7f4b-11eb-98f1-a5b35aa13a73.png)

This breaks many NewGRFs for example the Auz objects seen here with unique classnames and categories. This also is a problem for players who have ordered their NewGRFs in their NewGRF settings in a specic manner so that similar NewGRFs get loaded closely.

## Steps to reproduce
Loading different NewGRF Objects then opening the place objects menu. - the list is sorted alphabetically from the moment the window is opened.

**Comment by perezdidac** [comment]
I am taking over this one as I implemented the recent change to filter and sort. Working on it.

**Comment by perezdidac** [comment]
Here is the fix: https://github.com/OpenTTD/OpenTTD/pull/8818.
I also updated https://github.com/OpenTTD/OpenTTD/pull/8706 (same feature but for stations, still not merged to trunk) to sort by NewGRF as well, never alphabetically.
