### ISSUE TITLE
You can't convert the road type, because the road belongs to the city

### ISSUE THREAD

**Issue by Ufiby** [OpenTTD/OpenTTD#8839]
## Version of OpenTTD
Starting from version 1.10.0
## Expected result
road type conversion - must perform
## Actual result
![Road_type](https://user-images.githubusercontent.com/46504018/110650026-3a379f00-81cb-11eb-82bc-06081d83baa7.png)
## Steps to reproduce
This is the case with NewGRF: U&RaTT, Timberwolf s Roads, and other NRT sets

**Comment by LordAro** [comment]
Unless I'm mistaken, this is a duplicate of #8162 - i.e. it is the error message that is wrong/unclear - your town authority rating is too low, so you cannot change their roads - this is by design. The unclear error message has already been fixed

**Comment by Ufiby** [comment]
Somewhat differently, this case is related to the conditions (powered_road type_list) and city. I figured it out, found the problem
For example: I set up a set with three roads: a dirt road, a asphalt roads and a highway
Dirt road(DIRT)
powered_road type_list: ["DIRT", "ROAD", "HWAY" ]
Asphalt roads(ROAD)
powered_road type_list: ["DIRT", "ROAD", "HWAY" ]
Highway(HWAY)
powered_road type_list: ["ROAD", "HWAY" ]
So, please note that the Highway does not have the list of road types "DIRT" installed
So in the conditions of the city, no matter what the rating was.
Convert from asphalt road to highway - completed
Convert from asphalt road to dirt road - completed
Convert from dirt road to highway - completed
Convert from dirt road to asphalt road - completed
Convert from a highway to asphalt road - completed
Convert from a highway to a dirt road - failed, causes the error "belongs to the city"
This also applies to the electrification road, because the list of powered types is only "ELRD". A normal road has established two types of "ROAD", "ELRD". In the city, the conversion from an ordinary road to electrification is successful, but on the contrary, it is unsuccessful.

**Comment by Ufiby** [comment]
I mean, there are problems with the type of road and city if the rating was Good.
![Road_types](https://user-images.githubusercontent.com/46504018/110669779-bb982d00-81dd-11eb-8594-b2b6d39242d6.png)
