### ISSUE TITLE
Production indicator on the mini-map

### ISSUE THREAD

**Issue by ZarTek-Creole** [OpenTTD/OpenTTD#8850]
## Version of OpenTTD
1.10.3
## Expected result
I would like to see an option on the minimap in industry display mode that displays the output of industries displayed in text (such as city names) or an indicator (a gauge).
## Actual result
the mini-map in industry mode show the industry squares in their colors without production indicator
![image](https://snipboard.io/a1kWcX.jpg)

**Comment by TrueBrain** [comment]
Hi @MalaGaM ,

Thank you for your suggestion!

The best thing to do for suggestions, is to post them on our forums ( https://tt-forums.net/ ). Here people can pitch in what they think of your idea and often we see a few iterations later the suggestion becomes a solid idea that can be implemented.

Of course than it needs to catch the interest of any programmer to actually implement it in OpenTTD. They create a Pull Request in our repo, and we evaluate the idea and implementation.

We generally do not tend to let suggestions like this open as issue on our issue-tracker; this mainly as there are so many good and fun ideas to add to the game, the list on the issue-tracker would be endless, and nobody would know where to start :) Additionally, the forum gives us an indication how much people like (or dislike) a suggestion.

So please head over there and see what others think. In the mean time, thank you for thinking how to improve the game, I very much appreciate that!

Cheers!
