### ISSUE TITLE
There are 17 places where "IConsoleError" can be used instead of "IConsolePrintF".

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8853]
## Version of OpenTTD
9c5a7d3a572d02813e6bab83004334b9a154a62b

## Expected result
The function `IConsoleError` behaves exactly the same as using `IConsolePrintF(CC_ERROR, "ERROR: %s", string);`, but is shorter and more concise.
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console.cpp#L168-L171

Therefore, `IConsoleError(string)` should in general be used instead of `IConsolePrintF(CC_ERROR, "ERROR: %s", string)`.

## Actual result
The following 14 occurrences of `IConsolePrintF(CC_ERROR, "ERROR: %s", string)` still exist:
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L361-L364
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L385-L388
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L430-L433
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L487
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L534
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L558
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L738
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L759
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L791
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L830
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L1577

Additionally, there are 3 additional occurrences of `IConsolePrint(CC_ERROR, "ERROR: %s", string)`:
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L271
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L284
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L314

## Steps to reproduce
Look in the source of `commands.cpp` for the above occurrences.

**Comment by TrueBrain** [comment]
Have you ever considered making Pull Requests yourself? These kind of things are easy things to start with in a codebase like OpenTTD, and it seems you have a good grasp on what should happen/change?

Possibly also easier for yourself, as making these changes in code would have been faster than writing this ticket :D

Not saying you have to btw, I am perfectly fine with these tickets; I was just wondering :)

**Comment by TrueBrain** [comment]
PS : not all cases you highlight are `"ERROR: "` atm. But by the looks, most should be. So it is a two-for-oner :D

Example: ` IConsolePrint(CC_ERROR, "Saving map failed"); ` <- currently doesn't contain the word `ERROR: ` :)

**Comment by TrueBrain** [comment]
`IConsolePrintF(CC_ERROR, "%s: Not a savegame.", file); ` currently cannot be replaced with `IConsoleError`, as it doesn't use a plain string. I guess we need a `IConsoleErrorF` instead. Would make sense to me, to have that.

Looking over the list, all instances except for the last 3 are this, and this is also most likely the reason they are not `IConsoleError` yet. The last three are just silly, so they can be fixed easily :)

**Comment by AyushRaj8271** [comment]
Is this issue stilll available ?

**Comment by AyushRaj8271** [comment]
I would like to work on it !!
