### ISSUE TITLE
SDL2/Linux: OpenGL: Window sometimes filled with unitialised pixels at startup

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#8871]
## Version of OpenTTD
Current master (since OpenGL was merged)

## Expected result
Glorious perfect hardware accelerated pixels

## Actual result
On one of my machines, when OpenTTD is launched using OpenGL, quite frequently when the window first appears it is filled with uninitialised pixels. This is then later replaced with black followed by the title game screen/menu.
Depending on how loaded the machine is and whether it is a optimised/debug/etc build, this can be a coloured flash or last for a few seconds or so.

The GPU is a AMD Radeon R9 270.

`-d driver=4` outputs:
```
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Resolution for display: 1920x1025
dbg: [driver] SDL2: Mouse is at (972, 689), use display 0 (0, 0, 1920, 1080)
dbg: [driver] SDL2: using mode 1920x1025
dbg: [driver] SDL2: using driver 'x11'
dbg: [driver] OpenGL driver: X.Org - AMD PITCAIRN (DRM 2.50.0, 5.10.17-051017-generic, LLVM 11.0.0) (4.5 (Compatibility Profile) Mesa 20.2.6)
dbg: [driver] OpenGL: Using persistent buffer mapping
dbg: [driver] OpenGL shading language version: 4.50, texture units = 192
dbg: [driver] Successfully probed video driver 'sdl-opengl'
dbg: [driver] Successfully probed sound driver 'sdl'
dbg: [driver] Successfully probed music driver 'extmidi'
dbg: [driver] using thread for game-loop
dbg: [driver] Switching blitter from '32bpp-anim' to '40bpp-anim'... 
dbg: [driver] Successfully loaded blitter '40bpp-anim'
dbg: [driver] Successfully switched to 40bpp-anim.
dbg: [driver] SDL2: using mode 1920x1025
dbg: [driver] extmidi: set volume not implemented
```

![Screenshot_2021-03-16_21-32-51](https://user-images.githubusercontent.com/3910080/111386369-129d7680-86a4-11eb-845d-01ac871b1f1c.png)
![Screenshot_2021-03-16_21-39-46](https://user-images.githubusercontent.com/3910080/111386378-1630fd80-86a4-11eb-9c60-f8e3bcf6be9f.png)

If a new user were to notice such an effect the first time they ran the game it could set a bad first impression.

## Steps to reproduce
I assume that this is highly hardware and OS/driver dependant.

**Comment by ldpl** [comment]
Same thing on my old laptop with Nvidia GT 540M, I'll add driver output next time I use it.
