### ISSUE TITLE
It is possible to run the `rescannewgrf` command while NewGRFs are being scanned.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8874]
## Version of OpenTTD
379b6b4

## Expected result
One or more of the following:

* When you run the `rescannewgrf` command, the console loses focus until the command completes.
* When you run the `rescannewgrf` command, the command should output an error if it detects that NewGRFs are still being scanned.
* When you run the `rescannewgrf` command, the NewGRF scan is cancelled and restarted (@Eddi-z).

## Actual result

When you run the `rescannewgrf` command while newgrfs are still being scanned, the command silently aborts, without printing an error. This may be related to #6589. 

## Steps to reproduce

1. Start up the game with several hundred NewGRFs. The more NewGRFs, the easier it is to reproduce.
2. Pull down the console and run console command `clear`.
3. Type `rescannewgrf`, then hit the Enter key.
4. As quickly as you can, hit the up arrow key followed by the Enter key.
5. When the NewGRF scan completes, you should see two or more successive invocations of the `rescannewgrf` command and no error, even though NewGRFs were only scanned once.

**Comment by Eddi-z** [comment]
actually, what should happen is that the current scan gets cancelled and restarted.

**Comment by LordAro** [comment]
Extremely difficult to cancel a scan in progress. Would require interruptible functions of some sort. Best to just error if it's already in progress, imo

**Comment by TrueBrain** [comment]
NewGRF scan is already protected not two can run at the same time. The bug here appears to be that the user is not notified of this "I ignored you" :D

**Comment by rubidium42** [comment]
Regarding the cancelling of the NewGRF scan; that is, with the current design kind of pointless. The actual scanning runs in the GameLoop thus locking all UI updates, so the second rescannewgrf is either processed before it actually starts the scanning or it is processed after the rescan has been performed. In neither case cancelling is needed.
With #9022 OpenTTD will just show a warning when a NewGRF scan is requested but one is already pending to be done the next GameLoop.
