### ISSUE TITLE
Changelog button crashes the game if NewGRF contains relative folder

### ISSUE THREAD

**Issue by telk5093** [OpenTTD/OpenTTD#8886]
## Version of OpenTTD
20210322-master-gf9d24ff45e

## Expected result
Changelog button is disabled

## Actual result
Changelog button is enabled and crashes if I click it:
![image](https://user-images.githubusercontent.com/10726524/112175134-552df880-8c3a-11eb-8fe2-2421908f771c.png)

## Steps to reproduce
I recently updated [my NewGRF](https://github.com/KoreanGRF/KoreanTrainSet/releases/tag/2.0.0-beta1) and it contains a markdown file, which is named ``changelog.md``
It is awkward that Changelog button appears when ``changelog.md`` file exists, even though I refered a related codes at 
https://github.com/OpenTTD/OpenTTD/blob/e5c325364285b1e6e93afa2a0a79b1ec437f238e/src/textfile_gui.cpp#L385

1. Download [Korean Train Set 2.0.0-beta1](https://github.com/KoreanGRF/KoreanTrainSet/releases/tag/2.0.0-beta1)
2. Put it ``/newgrf`` or ``/content_download/newgrf`` folder
3. Open NewGRF Settings window, select Korean Train Set 2.0.0-beta1, and click changelog

**Comment by LordAro** [comment]
So this is good...

Due to the [command](https://github.com/KoreanGRF/KoreanTrainSet/blob/435c725a7d56046575638dbac84a51e79a573e58/Makefile#L121) used to create your tar file, it appears to contain a folder named '.'. Normally, this just means "current directory". OTTD then looks on this path and finds... its own changelog.txt, which it then crashes trying to display it (known issue, it's too big)

**Comment by telk5093** [comment]
Then, it won't crash anyway if I remove dots for my grf for now! Thanks for it.

**Comment by James103** [comment]
Actually, when the game tries to display any file in its readme viewer that is longer than 6,553 lines, it crashes with the same assertion as in the original comment: https://github.com/OpenTTD/OpenTTD/blob/f9d24ff45e99279a71f53f9f5b00619a275b593c/src/widget_type.h#L672

This means that not only is OpenTTD's `changelog.txt` able to cause the crash when "Wrap Text" is enabled (and unconditionally starting from 1.12 or 1.13 onward), but also a NewGRF, AI, or GS can crash the game simply by a user clicking on the readme, changelog, or license buttons when their corresponding files have 6,554 lines or more (whether raw or after "Wrap Text").

Fun fact: 6,553 * 10 < 65,536 < 6,554 * 10, which means the assertion is triggered based on the total number of vertical pixels, of which there are 10 per line.

**Comment by nielsmh** [comment]
Need to finish #7786 or maybe at least pull some of the text file viewer improvements out of it so they can be committed.
