### ISSUE TITLE
Quit function in disk toolbar menu doesn't work in scenario editor

### ISSUE THREAD

**Issue by LifWirser** [OpenTTD/OpenTTD#8889]

**Comment by LordAro** [comment]
I disagree. Please fill out the template with more details.

**Comment by LifWirser** [comment]
let me finish putting it in
on ver 1.11.0 rc1 installed from debian openttd-1.11.0-RC1-linux-debian-buster-amd64.deb. doesn't quit from in senerrio toolbar disk menu. it does quit from main menu and from window "x".
is repeatable

**Comment by LordAro** [comment]
Nope, no one here can reproduce this issue, with various builds and operating systems. Can you explain in more detail what's happening (if anything) when you press the button?

(Also, you can fill out details *before* submitting the issue)

**Comment by LifWirser** [comment]
BTW as I am new to openttd github page If by template you mean the line 
"Version of OpenTTD
Expected result
Actual result
Steps to reproduce" above on this page I was attempting to enter (or at least find a place to enter information when I was called a liar by 
LordAro

If I came to the wrong place when I signed to giothub and searched for openttd and landed here I am sorry

**Comment by planetmaker** [comment]
https://user-images.githubusercontent.com/3167964/112365163-9cb69200-8cd7-11eb-9701-124e10efd067.mp4


This is the right place to report bugs.
Depending on your desktop environment, sure: On Gnome I can take a short video by ctrl+alt+shift+r which you might use to illustrate the issue.

I cannot reproduce it on Fedora (yes, that's of course a different build, I know)

**Comment by LifWirser** [comment]
Version of OpenTTD openttd-1.11.0-RC1-linux-debian-buster-amd64.deb
Expected result recieve confirm quit dialog box
Actual result none, all  other toolbar / disk submenu items appear to function includind "abdongame
Steps to reproduce 1 start either new game or load game in main menu
2 click on tollbar disk icon
3 scroll to "quit game"

the follow may be pertanent 
uname -a

Linux WS-1 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

cinnamin window manager

**Comment by LordAro** [comment]
Just to clear up the GitHub UI misunderstanding:

![image](https://user-images.githubusercontent.com/4007992/112365721-e13e2f80-8ccf-11eb-8b70-958daac16c4e.png)

You can also edit existing issues:
![image](https://user-images.githubusercontent.com/4007992/112365765-ed29f180-8ccf-11eb-85c1-1bc647f99a73.png)

**Comment by LifWirser** [comment]
Well I just tried it today and you seams to be all right, however last night it was not working otherwise I would not of gone through the trouble. I may have had some yet unkown/competition for resources, as I tried repeatedly with the same results - rebooting sinnce.
 I apoligize for all the fuss, if I have a reacurance I'll be back
btw on cinnamin "ctrl + alt+ }shift| r" doesn't work
