### ISSUE TITLE
Panning extremely laggy as of 1.11 beta2

### ISSUE THREAD

**Issue by SMCA25** [OpenTTD/OpenTTD#8890]
## Version of OpenTTD
1.11 beta2 portable
1.11 RC1 portable

## Expected result
Right click and mouse move smoothly pans main window

## Actual result
Panning is extremely laggy both in window mode and in full screen mode when in playing with native screen resolution at 4K (3840 x 2160). Changing the screen resolution to e.g. FHD (1980 x 1080) in Game Settings results in smooth panning as expected. 

Panning worked/works flawlessly in 1.11 beta1 on same PC.

## Steps to reproduce
Start OpenTTD 1.11 beta2 or RC1 (portable version, did not try installer version)
New game with default settings
Pan -> window pan is stuttering / laggy
Change screen resolution to 1980 x 1080 -> panning works smoothly
Change screen resolution to 3840 x 2160 -> laggy panning

**Comment by LordAro** [comment]
This feels like the same issue as #8790 , so I'll close this in favour of that one.

In that issue, can you confirm your graphics card information (with `-ddriver=4` flag), and also if unchecking the "Hardware acceleration" button in Game Options helps at all?
