### ISSUE TITLE
Unable to sort BaNaNaS content in-game by upload date yet

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#8903]
## Version of OpenTTD
After merge of PR #8902 and PR OpenTTD/bananas-server#43

## Expected result
You should be able to sort the BaNaNaS content based on when it is uploaded, allowing you to see what the newest BaNaNaS additions are.

## Actual result
You are unable to sort the BaNaNaS content based on when it is uploaded. Currently, in order to find out what the newest additions to BaNaNaS are since a given date, you first have to download every single content item from BaNaNaS on that particular date, which requires OpenTTD to restart several times, can take several hours, and uses several GiB of CDN bandwidth.

Once #8902 and OpenTTD/bananas-server#43 have been merged, OpenTTD will now have the necessary data (upload date/time) to be able to sort the BaNaNaS content based on upload date, which is why I'm opening this issue.

I suggest that the new button be labelled "Upload date" or just "Date".

## Steps to reproduce
1. Use "Check Online Content".
2. Attempt to sort by date uploaded. There is no such option available yet.

**Comment by nielsmh** [comment]
That's not a bug, and there is also already PR #8902 opened to implement this.

**Comment by perezdidac** [comment]
Hi! I believe @James103 referred to using the upload date field for sorting, which I was going to work on anyway, but my first PRs were in place to send/receive the upload date first, and was going to work on a separate PR to actually use it to sort.
