### ISSUE TITLE
Text characters in minimap key sometimes touch each other

### ISSUE THREAD

**Issue by Wuzzy2** [OpenTTD/OpenTTD#8905]
## Version of OpenTTD
2d7b34bc68f7fb0e707129e4d97383b18f1da55e

## Expected result
The minimap key is readable.

## Actual result
There are several letters touching each other. One example where this issue becomes obvious is with letters with diacritics (“ä”, “ö”, “ü”, “Ä”, “Ö”, “Ü”.

Here is an example:

![image](https://user-images.githubusercontent.com/1062071/112771205-0feb3b80-902b-11eb-9250-8e75258905f1.png)

This is the minimap in German.

Black is “Transportstrecken” (correct), dark red is “Gebaude/Industrien”. However, in the translation file it is “Gebäude/Industrien” (note the “ä”).
If you look closely, it turns out that there really is an “ä”, but it is touching the “n” of “Transportstrecken” so the really looks like an “a”.

In general, the whole characters seem to be very close to each other, I noticed other letters that touch each other (for example, “Züge” and “Fahrzeuge”, that's not even a German-specific thing).

## Steps to reproduce
1. Set language to German
2. Open the minimap
3. Select vehicle mode

(you can try other languages as well)

## Possible solution
Add at least one "pixel" of space between the lines, to make sure the letters never touch each other. I'm not sure how practical this is, however. :-(

**Comment by LC-Zorg** [comment]
In most cases, this problem and similar #8907 could be solved by changing the font (#8596)- however, currently the player doesn't have easy access to this option.
![Another character](https://user-images.githubusercontent.com/67662046/112772460-39a76100-9031-11eb-9afc-306fa22b7961.png)

There is a related, more general problem of line spacing of text, which is often too small and degrades readability. The flagship example for me is the vehicle orders window, but also industries list, readme, news list...
Another problem that may also be related to this is that the game uses the spacing assigned to each font, which in many cases results in inappropriate, too large spacing and too large sign labels on the map.

Therefore, it might be a good idea to let the game create these spacings independent to the fonts specifics and allow the player to be able to adjust them.

**Comment by PeterN** [comment]
This is a bug in OpenGFX, the small font is supposed to be 6 pixels tall (including line spacing), but OpenGFX is overlapping those bounds, mainly because it tries to stuff lowercase letters in there which is not possible for a 5 pixel high font.
