### ISSUE TITLE
Suggestion: Replace target of the order without recreating it, and/or copy order's specs.

### ISSUE THREAD

**Issue by RoqueDeicide** [OpenTTD/OpenTTD#8911]
## Motivation
Some orders can be less then trivial, so it can be quite aggravating to put a lot of effort to specify one only to find out that it points to the wrong station. Additionally, it would be easier to create trains that accomplish the same tasks, but on different stations.

## Possible solutions
* **Replace** button - this button could be in the same "category" as the **Delete** button. Clicking on it will have the same effect as clicking on **Go to** button, but instead of creating a new order, it changes the station on the selected order to a new one.
* Creating a new order with a copy of another order's specifications.
  * **Go to** button could have its behavior change when used while an order is selected and **Ctrl** button is held down: a go-to order is created with a copy of specifications from the selected one. Currently holding a **Ctrl** button creates a new order with **Full load any cargo** spec. This may a require an option in the settings to select preferred behavior.
  * **Go to with selected specs** button: a new button that requires an order to be selected, creates a new one with the same specifications.

**Comment by 2TallTyler** [comment]
It sounds like you aren't aware of the ability to insert orders. 🙂 Click on an order to select it (in white), and then any orders added will appear above this.

![insert_order](https://user-images.githubusercontent.com/55058389/112867890-6d15da00-9089-11eb-9799-b5c3deb54d81.png)

**Comment by RoqueDeicide** [comment]
I'm not talking about positioning of the order, but its "specification", like "transfer and leave empty" or "Unload and take cargo with refit to wood".

**Comment by LC-Zorg** [comment]
I understand this problem, although it doesn't seem particularly big to me. One question that comes to mind... @RoqueDeicide: Are you using [shared orders](https://wiki.openttd.org/en/Manual/Orders#shared-orders)?
Even so, I don't think it would be a bad thing to add a replace destination function while keeping the specs of the previous target. This function could be listed under "Go To" when the player mark an order in advance.
![Replace destination](https://user-images.githubusercontent.com/67662046/112885468-192ee380-90d1-11eb-83c6-e5910e4754f7.png)

**Comment by RoqueDeicide** [comment]
"Shared orders" feature is irrelevant here, as I'm suggesting ways to expedite editing of the orders list, "shared orders" simply propagate the edits.

**Comment by TrueBrain** [comment]
Although I understand what you are asking, our issue tracker sadly enough is not the right place for such feature request. Best is to create a topic on https://tt-forums.net to collect if others agree and what a good approach would be. From there someone might pick it up to program this in the game :)

Personally, I like what you suggest; just no clue what the best UX approach is for it .. something to think about :)
