### ISSUE TITLE
Tunnel crash when placing bridge on top going same direction

### ISSUE THREAD

**Issue by matthew57778** [OpenTTD/OpenTTD#8915]
## Version of OpenTTD
1.10.3
## Expected result
Game should not crash when placing a bridge the same direction from end to end of tunnel but should error with "Can't place bridge here."
## Actual result
The game literally crash's with not responding.
## Steps to reproduce
Place a tunnel then place bridge from tile above tunnel entrence and drag and release at tile above tile exit and select bridge type.

**Comment by matthew57778** [comment]
![bug1](https://user-images.githubusercontent.com/18154949/113052423-f564af80-915b-11eb-88c8-7891538bf51e.png)
![bug2](https://user-images.githubusercontent.com/18154949/113052426-f5fd4600-915b-11eb-8c5a-6034ce29da90.png)
Here is the 2 screenshots of both instance's in second picture "bug2" is where i clicked the bridge i wanted.

**Comment by James103** [comment]
This likely has been fixed in a newer version, since it does not crash for me on Windows 10 and OpenTTD f9d24ff. Can you try this again using 1.11.0-RC1?

**Comment by frosch123** [comment]
Official 1.10.3 works fine.
You are using some 3rd-party modified client. (the rail toolbar gives it away).
Please report the bug there.

**Comment by ldpl** [comment]
FWIW this is a bug in polyrail patch introduced in version 11a. Here's the fix: https://github.com/citymania-org/cmclient/commit/68bb40976f4907f0475e501248c7ede670600732
