### ISSUE TITLE
NOT_REACHED() crash when selling shared vehicles

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#8922]
## Version of OpenTTD

1.11.0-RC1

## Expected result

Selling vehicles with shared orders does not crash the game.

## Actual result

![crash_reproduction](https://user-images.githubusercontent.com/55058389/113299642-17c90b00-92cb-11eb-9da3-d44b47ca9640.png)

`NOT_REACHED triggered at line 1719 of ..\src\vehicle_gui.cpp`

## Steps to reproduce

This is a tricky one to reproduce. 

1. In the attached savegame `autosave14` (not the emergency save), open the New Mills Airport station (just north of the starting location in the savegame) and look at the list of trains with that station in its orders.
2. Group the list by shared orders
3. Train 289 is in the list, currently lost and near a depot. Click on it and send it to the depot
4. In the depot, drag the last vehicle (an EMU) off the train onto a new line
5. Click the Sell All button
6. A NOT_REACHED error should trigger

[crash_stuff.zip](https://github.com/OpenTTD/OpenTTD/files/6243812/crash_stuff.zip)

**Comment by James103** [comment]
Can't reproduce the error in jgrpp-0.40.5 (perhaps one of @JGRennison's commits fixed it), but can reproduce in 088964a (2021-03-31 nightly) and 1.11.0 stable.
