### ISSUE TITLE
Windows IME can cause duplicate text input

### ISSUE THREAD

**Issue by nielsmh** [OpenTTD/OpenTTD#8930]
## Version of OpenTTD
799eb31ff1 and probably many earlier. Possibly only on Win32 video driver, possibly depends on standard library/compiler used.

## Expected result
One press of a letter key results in one letter input.

## Actual result
Some input is duplicated, and the duplicate keypresses appear as capital letters despite not touching Shift or Caps Lock keys.

![image](https://user-images.githubusercontent.com/1062071/113451041-6c6ea200-9401-11eb-89d2-00aaa149b537.png)
![image](https://user-images.githubusercontent.com/1062071/113451049-71335600-9401-11eb-9c4b-ff2639d3915e.png)

## Steps to reproduce
Appears to be related to slow framerates. Recommend opening console and filling it with many lines, and opening a text file viewer window, and running an unoptimised build with checks/asserts enabled.
Then type quickly. Mashing keys on home row works well.

Windows 10 (version 2004)
Video driver: win32-opengl (NVIDIA Corporation - GeForce RTX 2060/PCIe/SSE2 (3.2.0 NVIDIA 456.71))
Blitter: 40bpp-anim
Windowed mode: 2560x1600 at 60 Hz
Interface and Font size both at 2x scale

**Comment by James103** [comment]
Can you reproduce this inside the text input windows that correspond to renaming vehicles/stations/depots/companies/etc?

**Comment by nielsmh** [comment]
Yes I can reproduce this also in other text inputs, and it appears I can even under high framerates, if I mash keys fast enough.

**Comment by LordAro** [comment]
I think if you could bisect this to work out where the problem first occurs (there have been a lot of changes to video drivers recently, after all), that would be super helpful in working out what is actually causing it

**Comment by nielsmh** [comment]
Okay I've reproduced this even in the release build of 1.11.0.

**Comment by nielsmh** [comment]
Turns out it has to do with the Japanese IME being the active input/keyboard layout. Even if the text conversion isn't active and it's in direct ASCII input mode, it causes this behaviour. Switching to a different keyboard layout makes the input behave normally.
I don't have this kind of misinput in any other programs, so it seems to have something to do with how OpenTTD handles input from IMEs.
