### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by gassmark** [OpenTTD/OpenTTD#8933]
## Version
1.11.0

## Actual result
game freezes and freezes entire computer system after exactly when started. Usually when the first fog horn sounds.

## Details
Launch game through Steam

[crash.log](https://github.com/OpenTTD/OpenTTD/files/6251408/crash.log)
[crash.log](https://github.com/OpenTTD/OpenTTD/files/6251410/crash.log)

**Comment by LordAro** [comment]
There should be a crash.dmp file in the same place as the crash.log, can you upload that as well? (you'll need to zip it)

**Comment by TrueBrain** [comment]
As we cannot analyze this crash without the `crash.dmp`, I am going to close this ticket for now. Feel free to reopen it if you can either reproduce it or still have the original `crash.dmp`. Tnx!
