### ISSUE TITLE
Crash on save on macOS

### ISSUE THREAD

**Issue by smsm1** [OpenTTD/OpenTTD#8935]
## Version of OpenTTD
1.11.0
zip download

## Expected result
When saving the game, the game should continue.

## Actual result
The game might be saved properly, the application crashes with the error:

```
Application Specific Information:
BUG IN CLIENT OF LIBDISPATCH: Assertion failed: Block was expected to execute on queue [com.apple.main-thread]
```

[otp_crash.log](https://github.com/OpenTTD/OpenTTD/files/6252112/otp_crash.log)

## Steps to reproduce
1. Start or load a saved game
2. Play the game for a bit
3. Save the game
4. On clicking the save button when choosing the file name the game save file is created and then there is the crash.

I can reproduce this on both a Mac Mini 2018 Intel and MacBook Pro M1.

Previous versions (1.10.3) didn't have this issue.

<img width="1112" alt="Screenshot 2021-04-03 at 08 20 07" src="https://user-images.githubusercontent.com/82719/113471612-699d9c80-9455-11eb-9426-72a697f3b6d5.png">

**Comment by andythenorth** [comment]
Confirmed with 1.11.0.  Haven't bisected, but a quick test of 1.11.0 Beta 2 didn't trigger this issue.

**Comment by smsm1** [comment]
e56d2c63c306dd087de26088729d09233b1122c2 has the crash. 
The commit parent of the above one i.e. 3a4a15cc93015ce5bed4f7720d4f0f05178c09e9 does not have the crash when compiling locally with `cmake ..; make -j 8`.

**Comment by michicc** [comment]
I'm currently unable to test this myself, but https://gist.github.com/michicc/1c6f8f0b5322c2cb8f0acc908d6b755a might possibly fix this issue.

**Comment by amf0336** [comment]
When a crash occurs during a save operation, the file can not be used to load a game.

Overwriting an existing save file always works.

**Comment by smsm1** [comment]
@michicc on master branch with your patch I have been unable to reproduce the crash and it is now working as expected. Without the patch the crash occurs.

@amf0336 I can confirm the behaviour that you are seeing too. With the above patch the issue goes away, as I've been able to load any of the files I've saved.

**Comment by michicc** [comment]
@smsm1 If it's not too much a bother, could you try the patch with both `waitUntilDone:NO` and `waitUntilDone:YES`? Principally, `YES` would be more correct, but I'm worried about it causing a thread stall.

I'm going to prepare a pull request tomorrow for this.

**Comment by smsm1** [comment]
<img width="1792" alt="Screenshot 2021-04-04 at 08 17 12" src="https://user-images.githubusercontent.com/82719/113501606-56a2cf00-951e-11eb-9899-02aa0410ba17.png">

When I use `waitUntilDone:YES`, when clicking save I get a beachball and openttd is completely unresponsive.

**Comment by michicc** [comment]
Thanks, then `NO` it is.

**Comment by rafalkrupinski** [comment]
I'm experiencing this bug, latest version, same message, but ONLY if I save by hitting enter in the save dialog

**Comment by TrueBrain** [comment]
Can you please create a new bug-report, with the crash log attached? It is possible, although the issues look alike, that they aren't. With a fresh bug-report and crash log we can look into that :)

Thank you!

**Comment by rafalkrupinski** [comment]
> Can you please create a new bug-report

#9856
