### ISSUE TITLE
Background music doesn't play

### ISSUE THREAD

**Issue by giordy** [OpenTTD/OpenTTD#8940]
## Version of OpenTTD
1.11.0 - from Steam
## Expected result
I should be able to hear music and sound effects
## Actual result
I installed all possible music package but none works.
I'm using MacOS Siri 11.2.3
The sound effects do work, though.
I even tried to remove the configuration folder and have it recreated, no change.

**Comment by andythenorth** [comment]
I get music with 1.11.0 on macOS with the Steam install.  I'm using original sound set.

Sorry, doesn't help fix, but it's a data point.

**Comment by giordy** [comment]
I'm not sure what happened, perhaps I had an instance of OpenTTD stuck in background or so, however now it started working again.
Sorry for opening the issue, apparently there is no bug. Thanks for the feedback!
