### ISSUE TITLE
Can't build 1.11.0

### ISSUE THREAD

**Issue by esselfe** [OpenTTD/OpenTTD#8954]
## Version of OpenTTD
1.11.0

## Expected result
cmake configuration to succeed.

## Actual result
cmake configuration fails.

## Steps to reproduce
wget https://github.com/OpenTTD/OpenTTD/archive/refs/tags/1.11.0.tar.gz -O openttd-1.11.0-source.tar.gz
tar xf openttd\*gz
cd openttd\*0
mkdir build
cd build
cmake ..

## Output
```
13:58:09root@L0:/build/openttd-1.11.0/build# cmake ..
CMake Error at CMakeLists.txt:10 (message):
  In-source builds not allowed.  Please run "cmake .." from the bin directory


-- Configuring incomplete, errors occurred!
See also "/build/openttd-1.11.0/CMakeFiles/CMakeOutput.log".
```

**Comment by esselfe** [comment]
Commenting lines 9 to 11 of openttd-1.11.0/CMakeLists.txt fixes this but the resulting Makefile is in the source dir, not in build/.

**Comment by glx22** [comment]
Using the exact same steps it works fine for me.
I think we need more info about at least your CMake version.

**Comment by esselfe** [comment]
I have cmake 3.20.0

**Comment by glx22** [comment]
Hmm ok, should not be an issue.
Adding 
```
message(STATUS "Source: ${CMAKE_SOURCE_DIR}")
message(STATUS "Binary: ${CMAKE_BINARY_DIR}")
```
before line 9 will tell what CMake detected.

**Comment by esselfe** [comment]
I 'cd build; cmake ..'
```
-- Source: /build/openttd-1.11.0
-- Binary: /build/openttd-1.11.0
CMake Error at CMakeLists.txt:12 (message):
  In-source builds not allowed.  Please run "cmake .." from the bin directory


-- Configuring incomplete, errors occurred!
See also "/build/openttd-1.11.0/CMakeFiles/CMakeOutput.log".
See also "/build/openttd-1.11.0/CMakeFiles/CMakeError.log".
```

**Comment by LordAro** [comment]
Error very much suggests that the `cd build` command is not working for some reason or another. Run `pwd` after doing so?

**Comment by esselfe** [comment]
pwd:
/build/openttd-1.11.0/build

**Comment by glx22** [comment]
Oh maybe there's a leftover `CMakeCache.txt` in `/build/openttd-1.11.0`.

**Comment by esselfe** [comment]
yes it was that! I deleted the file and it works! Thank you so much!
