### ISSUE TITLE
Disasters: wrong location shown in factory/refinery destroyed message

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#8956]
## Version of OpenTTD
1.11.0
## Expected result
The message shows the correct location of the incident
## Actual result
The shown location of the incident is incorrect - it always shows the top left edge of the map.
![Wrong localisation of disaster 1](https://user-images.githubusercontent.com/67662046/113629170-4c8be800-9666-11eb-8fe6-b8e6b9b2d9b6.png)

## Steps to reproduce
The bug always appears, just start the game with disasters.

**Comment by 2TallTyler** [comment]
Sounds like #8810.

**Comment by James103** [comment]
From some of my own testing (and looking at the code), it appears that the news message is likely using the industry's ID as the tile ID to display in the news message, and not the actual location of the (northernmost) corner of the industry itself. See the following code segments for a likely backtrace:
https://github.com/OpenTTD/OpenTTD/blob/825867f2c50ce508fac442e6113da9cebbfccf75/src/disaster_vehicle.cpp#L459
https://github.com/OpenTTD/OpenTTD/blob/825867f2c50ce508fac442e6113da9cebbfccf75/src/disaster_vehicle.cpp#L471-L472
https://github.com/OpenTTD/OpenTTD/blob/825867f2c50ce508fac442e6113da9cebbfccf75/src/industry_map.h#L63-L67
https://github.com/OpenTTD/OpenTTD/blob/825867f2c50ce508fac442e6113da9cebbfccf75/src/industry_map.h#L278-L282
