### ISSUE TITLE
Build error on armhf architecture

### ISSUE THREAD

**Issue by zoltantamasvajda** [OpenTTD/OpenTTD#8962]
Hello there lovely people of OpenTTD contributors!

I'm the maintainer of the [openttd-server snap package](https://github.com/zoltantamasvajda/openttd-server) which I've created for my own purposes but seems to be gaining a bit of popularity, which is nice.

What is not nice is that I seem to be having an issue with building the package for version 1.11.0 on armhf architecture.

Apparently there are at least 5 people out there who'd like to run a dedicated openttd server using snaps on armhf (Raspberry Pi?) and I'd hate to let them down.

I've attached the full cmake logs from the build pipelines but the relevant part seems to be this:

```
`GenerateIndustries()':
<artificial>:(.text+0x9fc8): undefined reference to `Pool<Industry, unsigned short, 64u, 64000u, (PoolType)1, false, true>::MAX_SIZE'
/usr/bin/ld: /tmp/openttd.LStJUE.ltrans19.ltrans.o: in function `GenerateTowns(TownLayout)':
<artificial>:(.text+0x8d7c): undefined reference to `Pool<Town, unsigned short, 64u, 64000u, (PoolType)1, false, true>::MAX_SIZE'
```

Any help would be appreciated. Thanks!

[cmake.log](https://github.com/OpenTTD/OpenTTD/files/6263963/cmake.log)

**Comment by LordAro** [comment]
Already fixed in #8924

**Comment by TrueBrain** [comment]
Good news! We fixed this issue in master :)

https://github.com/OpenTTD/OpenTTD/commit/4d501655adfa0b9e44bd365ba396580461d40a48

It will be in our next release. Till that time, please patch the code yourself if you can. A new release won't be long btw.

**Comment by zoltantamasvajda** [comment]
Lovely! Thanks you!
