### ISSUE TITLE
Black Bars during gameplay

### ISSUE THREAD

**Issue by adamcirillo** [OpenTTD/OpenTTD#8963]
## Version of OpenTTD
1.11 Steam
CPU 9900K
Nvidia 3080 GTX Driver 465.89
Windows 10 20H2

## Expected result
Black Bars should not appear
## Actual result
Black Bars randomly Appear
## Steps to reproduce
Just play the game and it will happen
It did not show up in the screen shoot not sure why

![image](https://user-images.githubusercontent.com/13363284/113765489-ae7c4880-975f-11eb-9820-677c6aa6f904.png)

**Comment by LordAro** [comment]
That fact that this does not show up in screenshots suggests to me that this is some sort of video output issue, either with the video card, the cable, or even the monitor itself

**Comment by adamcirillo** [comment]
I haven't seen this happen with any other game but i will take a picture with my phone next time i see it

**Comment by adamcirillo** [comment]
Here is what happens

![PXL_20210406_195132241 MP](https://user-images.githubusercontent.com/13363284/113770535-93143c00-9765-11eb-8547-027a1c05d84b.jpg)

**Comment by James103** [comment]
What happens if you run `openttd -d driver4`? If you are on Windows, you can also run `dxdiag` and attach the (graphical, or text via "Save All Information") output here.

**Comment by nielsmh** [comment]
Also, can you try turning off Hardware Acceleration in Game Options, to see if that makes a difference?
(You need to quit and restart OpenTTD after toggling the option.)

**Comment by adamcirillo** [comment]
I've run with the driver4 and it happened but it was smaller. I also turned off Hardware Acceleration and the issue disappeared.

[DxDiag.txt](https://github.com/OpenTTD/OpenTTD/files/6270518/DxDiag.txt)

**Comment by adamcirillo** [comment]
So I've done some further setting setting the Vsync setting to on in the Nvidia Control Panel causes this to happen if i turn it off it doesn't happen as well. I turn in on there since i couldn't find a setting in the game as i was getting screen tearing like in https://github.com/OpenTTD/OpenTTD/issues/8968 and have my refresh rate set to 60hz as my monitor won't do higher

**Comment by TrueBrain** [comment]
Can you start the game with vsync enabled (currently not a setting, but we might add that for these cases):

Open either Powershell or Command Prompt and navigate to the folder you installed OpenTTD. Next, run:

`openttd.exe -vwin32-opengl:vsync`

Does that resolve the issue for you?

**Comment by adamcirillo** [comment]
I have tried the setting i still get the black bars but they are very thin line now and they only show up for a 1 or 2 seconds and then disappear

**Comment by TrueBrain** [comment]
What happens if you set the `Vertical sync` setting in the NVIDIA Control Panel to `Use the 3D application setting` ? Does that resolve the issue? (I ask this as you mention you tried on and off, but by default is uses what-ever the application sets it to. Makes me wonder if that makes a difference).

**Comment by adamcirillo** [comment]
i have it set to that right now when i was testing it.

**Comment by adamcirillo** [comment]
Have tried with openttd 1.11.1 and Nvidia driver 466.11 now i get black boxes without scrolling ingame with vsync turned on having it off fixes it right away

**Comment by LordAro** [comment]
@adamcirillo There have been a few changes since 1.11.1 - can you try 1.11.2 or a recent nightly build to see if they fix the issue?

It is a bit strange that no one else at all has reported this issue...

**Comment by Milek7** [comment]
I had some glitches too, likely related: https://milek7.pl/.stuff/ottdglitch.mp4
Seems to happen only on fullscreen with vsync.
(Nvidia graphics)

**Comment by Milek7** [comment]
I have glitching issue that might be related https://milek7.pl/.stuff/ottdglitch.mp4
Seems to happen only on fullscreen with vsync enabled, but I'm not 100% sure.
(Nvidia graphics)

**Comment by TrueBrain** [comment]
Almost three years later, but we haven't received any further reports about this anymore from other people. Are you still experiencing this issue? Otherwise I would like to close this issue, as we are not really equipped to debug issues between OpenGL and videodrivers :)
