### ISSUE TITLE
Arrow key camera panning not consistent with framerate

### ISSUE THREAD

**Issue by jasperfirecai2** [OpenTTD/OpenTTD#8968]
## Version of OpenTTD
1.11.0
## Expected result
Screen scrolling with the arrow keys is smooth on all framerates
## Actual result
Screen scrolling is a fixed rate independent of framerate, causing screen tearing on higher framerate settings, and inconsistency between right mouse panning and arrow key panning.
I'm afraid I don't have a good way to show this with an image or video
## Steps to reproduce
1. Load up the game
2. Change the framerate to something higher than the default, in my case: 144Hz
3. Use the arrow keys to pan the camera
4. Compare with right mouse button panning

**Comment by TrueBrain** [comment]
I think this is not so much related to the refresh-rate, even on 60Hz it feels terrible.

Enabling `smooth viewport scrolling` resolves the issue mostly, which means it is most likely caused that arrow key movements are not per pixels, but by a bunch of pixels at once. There are more places in OpenTTD that have similar issues, like news popping up.

Will need to look further into how arrow key movement works to see if this can be easily fixed, but possibly a simple fix is always applying smooth viewport scrolling for arrow key movement.

**Comment by TrueBrain** [comment]
After looking into this in more detail, indeed, the best fix is to enable smooth-scrolling. I am currently applying some fixes to make smooth-scrolling a bit more smooth, but that is really the solution to this ticket. If you use arrow-keys, enable smooth-scrolling.

Initially I wanted to force enable it when using arrow-keys, but decided that would be weird; some people might not want it. So instead, I have made a suggested change to make smooth-scrolling the default.

PS: did you know that when you press SHIFT the arrow movement goes 5 times as fast? Easier to get to places :)
