### ISSUE TITLE
Wrong language loaded on first game start

### ISSUE THREAD

**Issue by WimLeflere** [OpenTTD/OpenTTD#8973]
## Version of OpenTTD
Own Windows build of master 130a052

## Expected result
My Windows display language and keyboard are configured as 'English (United States)'.
I was expecting that the game would start in English.

## Actual result
The game started in Dutch.
Maybe because my 'Regional format' (date & time format) is configured as 'Dutch (Belgium)'.

Also tested with 'French (Belgium)' and the game starts in French.

## Steps to reproduce
1. delete the value for language in `openttd.cfg`
2. change 'Regional format' in Windows settings
3. start the game

**Comment by WimLeflere** [comment]
I'm working on a fix which uses [GetUserDefaultUILanguage()](https://docs.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getuserdefaultuilanguage) to determine the Windows display language.

**Comment by TrueBrain** [comment]
Fixed by #8973 (was missing "Fixes .. " tag)
