### ISSUE TITLE
Editbox losing focus triggers Editbox's OnEditboxChanged

### ISSUE THREAD

**Issue by perezdidac** [OpenTTD/OpenTTD#8983]
## Version of OpenTTD

Building at HEAD, 1.11+ I guess.

## Expected result

* Losing focus should not trigger OnEditboxChanged

Is this working as expected?!

## Actual result

Losing focus triggers OnEditboxChanged

![image](https://user-images.githubusercontent.com/2025406/114251587-65421980-9956-11eb-942d-63636f48ff26.png)

## Steps to reproduce

1. Enter text in a textbox
2. Add a breakpoint to that window's OnEditboxChanged callback.
3. Click somewhere else.
4. Observe OnEditboxChanged  is called

**Comment by LordAro** [comment]
Should it not be triggered? The editbox has been changed - it is no longer focused! At the very least it needs to redraw the window without the cursor.

**Comment by michicc** [comment]
Also, when using an IME for text input, the edit box string can also change as we discard any non-commited IME input.

**Comment by TrueBrain** [comment]
So running the `OnEditboxChanged` is intended. But I do wonder what you mean with `It ends up triggering window invalidation again and again.` ? It should only do it once for losing focus, so is there something we are not seeing there?

Tnx :)

**Comment by perezdidac** [comment]
> So running the `OnEditboxChanged` is intended. But I do wonder what you mean with `It ends up triggering window invalidation again and again.` ? It should only do it once for losing focus, so is there something we are not seeing there?
> 
> Tnx :)

Nope, that was a mistake observation I made, it actually only triggers *once*. I will change the description to make it clear.

**Comment by perezdidac** [comment]
Thanks for the responses. I guess this makes sense. I wonder if a OnEditboxContentsChanged callback would make sense, though probably not as I don't think there are even that many usages of OnEditboxChanged. Anyhow, I am closing this as it seems to be working fine and doesn't cause any trouble. It was nice to get some discussion on this.
