### ISSUE TITLE
Installer have not option to import original Transport Tycoon Deluxe files / Original Transport Tycoon Deluxe files not detected

### ISSUE THREAD

**Issue by Limyx826** [OpenTTD/OpenTTD#8995]
## Version of OpenTTD
1.11.0

## Expected result
When starting installer, there should be a page shown to import base sets from the original TTD disc or floppy (does it do this before?)

## Actual result
There are no page for this, it just straight installation. 

Also I updated my prior installation with the installer and my old files for Windows TTD and DOS TTD are still in the directory yet they can't be found in the options menu in game. 
![image](https://user-images.githubusercontent.com/38696851/114269289-d528d080-9a38-11eb-83a7-fc6c55323608.png)

**Comment by nielsmh** [comment]
This isn't something most people do anymore, I think, but how to do it is still described in the Readme file.
The files you see in your baseset folder there are the set description files, not the actual data.

**Comment by TrueBrain** [comment]
As people owning the original CD is less and less likely (the game is 27 years old), we stopped suggesting it in the installer. It hasn't been possible for years to legally get a copy of the game anymore.

The README does mention how to set this up. But, ingame you currently can't read the README. There is a Pull Request already to fix that, so hopefully that further addresses this issue.

The instruction online can be found here: https://github.com/OpenTTD/OpenTTD#142-original-transport-tycoon-deluxe-graphics-and-sound-files

Hopefully that also helps you out getting it to work again :) Let us know if you have any further questions!

**Comment by Limyx826** [comment]
Thanks for clarification

**Comment by Limyx826** [comment]
@TrueBrain 
Sorry to tag you but I follow the instructions while both graphics and sound show up but the music didn't. Any way to solve this? 

EDIT: Never mind this, I found the solution just move it out to the base directory.
