### ISSUE TITLE
Coverage not updated directly when expanding

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/OpenTTD#9020]
## Version of OpenTTD
1.11.0

## Expected result
Coverage to update immediately when expanding.

## Actual result
New coverage is not marked dirty, so slow appears when you move your mouse around.

## Steps to reproduce
- Build station.
- Disable `Coverage area highlight` on build window.
- Click station, click coverage.
- Extend station with new station (CTRL+build).
- Tiles of new coverage not marked dirty, looks odd.

![image](https://user-images.githubusercontent.com/1663690/114314736-3a91c580-9afc-11eb-81ab-29433a8b7480.png)

After moving around:
![image](https://user-images.githubusercontent.com/1663690/114314745-41b8d380-9afc-11eb-9c0d-1e775d86f8cb.png)

**Comment by LordAro** [comment]
See also #7980
