### ISSUE TITLE
Error on starting OpenTTD

### ISSUE THREAD

**Issue by SkippyCoo9** [OpenTTD/OpenTTD#9026]
## Steps to reproduce downloaded new update 2x get 
Capture.png
images.githubusercontent.com/58266760/114429883-132e0d80-9b7b-11eb-803b-18d89538dc8e.PNG)
same error.
images.githubusercontent.com/58266760/114429413-9ac74c80-9b7a-11eb-86d7-73b877f652fd.PNG)

**Comment by James103** [comment]
From the image: `Assertion failed at line 988 of ..\src\video\win32_v.cpp: _screen.dst_ptr != nullptr`
Same assertion as https://github.com/OpenTTD/OpenTTD/issues/8967#issuecomment-817179741
(Assume that the version given is "1.11.0", not "1.110")

![image](https://user-images.githubusercontent.com/58266760/114429883-132e0d80-9b7b-11eb-803b-18d89538dc8e.PNG)
![image](https://user-images.githubusercontent.com/58266760/114429413-9ac74c80-9b7a-11eb-86d7-73b877f652fd.PNG)

**Comment by SkippyCoo9** [comment]
I found the problem. It was my mistake. I had downloaded the nightly update instead of the new release of the main file. I downloaded the new file 1.11.0 and installed it. The game started like normal. No errors. I thank you for your time and consideration. Please close the ticket.
SkippyC009
