### ISSUE TITLE
Global story book opens on top of company story book

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/OpenTTD#9030]
## Version of OpenTTD
1.11.0

## Expected result
Not open two near-identical windows on top of each other. Be more like goal-window, I would say.

## Actual result
Two windows of identical size open on top of each other, with only minor difference in colouring. Very confusing.

## Steps to reproduce
- Open company story book
- Open global story book
- Be: huh? Did I open global?
- Close global
- Notice company is below that
- Be: huh?

No other window I know off opens on top of another. Seems like a simple boo-boo somehwere.

Additionally, Goal Window has a nice "Global" and "Company" button, but Story Book doesn't. This feels inconsistent. Maybe both can be tackled at the same time. But the overlapping windows was by far the more frustrating part :)

**Comment by LordAro** [comment]
Window is centred due to `WDP_CENTER` in the window desc. Having multiple centred windows hasn't mattered in the past because they've been different sizes or different designs.

Could make them "unique" ? i.e. only open one storybook at a time? Would that be desirable? Otherwise will require some loops to check open (storybook) windows for centred positioning.

**Comment by TrueBrain** [comment]
Honestly, I think the issue is that it opens in the center.

If this happens for popups, of all various of types, I totally get that. Those windows also have a very distinct background (either red or blue-ish), you notice them, they are often relative small, they require your attention / interaction .. opening those in the center: sure.

But this window has none of that. So I am not really sure why it would want to open centered, and not be like any other window? Mainly as it is, as far as I can tell, the only window to behave like this (that isn't a popup).

**Comment by LordAro** [comment]
It's a storybook, so it opens centred - mostly as part of a "Welcome to this game type" message from a GS. Makes perfect sense that it would be centred, IMO (though perhaps the GS could centre it itself? Can GSes do that?)

**Comment by TrueBrain** [comment]
Or maybe we can only make it centered if the GS opens it, and otherwise make it act like a normal window?

**Comment by LC-Zorg** [comment]
Is there any script where is any sense to open more than one window? I don't know but so far, I haven't seen a single one. Everywhere, the content of these windows is identical, regardless of whether the A, B company window or the global window is opened. I don't even know if it is possible to put variable data in this window. Maybe this function to open multiple windows is unnecessary at all? The only use I can see of being able to this is to be able to open several pages of that window on the screen to take a screenshot, but... that is a weak argument I think. :)
