### ISSUE TITLE
Rivers going uphill are nearly impossible to distinguish from flat river

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/OpenTTD#9031]
## Version of OpenTTD
1.11.0
OpenGFX

(I have no clue if this is OpenTTD graphics of OpenGFX graphics; feel free to move it to OpenGFX if it isn't OpenTTD).

## Expected result
To see when my ship won't be able to get to the dock, because it had to go uphill, and I forgot to build a lock.

Ideally, rivers have a better animation which direction they flow. Now they just move a bit, looking like pixel-noise. But it doesn't show me a direction. I have no clue if this is possible at all, just saying what would have helped me out :)
Locks do have animation in the direction they are in btw, maybe helps for inspiration.

## Actual result
Be totally confused for 30 minutes why my ship doesn't go to the dock.

Mainly, as ships don't have the greatest feedback they can't find a route: they will go towards the dock, but when it cannot go further, it turns around, drifts for a bit of time, then decides to go to the next order. If you are not closely watching your ship, you totally fail to see what is going on. Especially fun when you are building a big route :D

## Steps to reproduce

Well, images say more:
![image](https://user-images.githubusercontent.com/1663690/114450448-4ea9f580-9bd6-11eb-966d-02a8245dd8f5.png)

![image](https://user-images.githubusercontent.com/1663690/114450502-61242f00-9bd6-11eb-8dd7-7427494db62f.png)
Yes, this really goes uphill. Did you spot it?

Here it is without the trees:
![image](https://user-images.githubusercontent.com/1663690/114450540-6e411e00-9bd6-11eb-8a9f-52d7cb1e979b.png)

This one got me the most. I have mad respect for people who draw tiles, but this one is just evil :)

**Comment by nielsmh** [comment]
That's OpenGFX graphics... I think. The "original" graphics looks like this. (Transport Tycoon Deluxe did not have rivers. They and canals are a TTDPatch feature adopted by OpenTTD, so the river graphics is new art drawn in Simon Foster's style.)

![image](https://user-images.githubusercontent.com/1062071/114451432-849ba980-9bd7-11eb-98e7-09012b40839d.png)

**Comment by TrueBrain** [comment]
Yeah, that is not a lot better, it seems. Also little indication of direction and that they are uphill.

I was also thinking, adding a path-indicator ships are going would also resolve the issue. I can then spot it cannot reach the dock. Like trains, but for boats :)

**Comment by PeterN** [comment]
Yeah, I was playing TTD graphics and it's better than OpenGFX, but not a lot.

**Comment by glx22** [comment]
I confirm, original graphics a little better, but some are still very hard to spot
![Capture d’écran 2021-04-12 222931](https://user-images.githubusercontent.com/2952192/114457980-f0cddb80-9bde-11eb-9ef8-6d4e68a1ee51.png)
![Capture d’écran 2021-04-12 223034](https://user-images.githubusercontent.com/2952192/114458101-10650400-9bdf-11eb-950a-760648c435d1.png)
![Capture d’écran 2021-04-12 223128](https://user-images.githubusercontent.com/2952192/114458126-15c24e80-9bdf-11eb-9285-a2baa49eac36.png)

**Comment by James103** [comment]
Maybe make it so that on the river tile graphics, there are (very clearly visible and distinguishable) rocks on the river tile if **and only if** the river tile is sloped? That would entail removing any rocks (or what could look like rocks) from the not sloped portions of river graphics (if any), while adding and/or enlarging rocks present on the sloped river tile graphics.

**Comment by andythenorth** [comment]
I can draw new, more visible rocks, and more white (turbulent) water.  I don't know when, but it can be done.

**Comment by Eddi-z** [comment]
I think the main issue here is that there's no shading for the water, like there is for the grass

**Comment by auge8472** [comment]
For comparision the solution of michael blunck in his rivers NewGRF. The cataracts clearly marks the downhill sections.

![mb-rivers](https://user-images.githubusercontent.com/1734660/114570432-1ce86b80-9c76-11eb-95e9-a1f36174ec6d.png)

**Comment by tendersoft-mjb** [comment]
I propose the simplest solution, make the water darker - in the particular examples below it's 14% darker.

> I confirm, original graphics a little better, but some are still very hard to spot
> ![Capture d’écran 2021-04-12 222931](https://user-images.githubusercontent.com/2952192/114457980-f0cddb80-9bde-11eb-9ef8-6d4e68a1ee51.png)
![openttd-darker-shade-of-sloped-water-01](https://user-images.githubusercontent.com/7294417/115458311-dc649100-a225-11eb-9784-11346fe5ba2d.png)

> ![Capture d’écran 2021-04-12 223034](https://user-images.githubusercontent.com/2952192/114458101-10650400-9bdf-11eb-950a-760648c435d1.png)
![openttd-darker-shade-of-sloped-water-02](https://user-images.githubusercontent.com/7294417/115458309-dbcbfa80-a225-11eb-8748-ee4723145d62.png)

> ![Capture d’écran 2021-04-12 223128](https://user-images.githubusercontent.com/2952192/114458126-15c24e80-9bdf-11eb-9285-a2baa49eac36.png)
![openttd-darker-shade-of-sloped-water-03](https://user-images.githubusercontent.com/7294417/115458306-db336400-a225-11eb-81a4-45ba3a1d0394.png)

**Comment by FLHerne** [comment]
> I propose the simplest solution, make the water darker - in the particular examples below it's 14% darker.

Unfortunately this doesn't work straightforwardly with palette animation -- [the TTD palettes](https://newgrf-specs.tt-wiki.net/wiki/PalettesAndCoordinates) only contain one water cycle each, which doesn't leave much scope to change the colour while keeping animation. Non-animated slope tiles would look odd when all other water tiles are animated.

**Comment by rel1c** [comment]
> I propose the simplest solution, make the water darker - in the particular examples below it's 14% darker.

The water should be lighter in your first example, as the grass is as well when facing northeast.

**Comment by andythenorth** [comment]
Request for accuracy: rivers don't go uphill.

Missed you 😸

**Comment by andythenorth** [comment]
These are photoshop mockups showing we need to match land tile shading for various slope angles.  Other graphical tricks (rocks etc) aren't sufficient to work around this, OpenTTD land relies on shading to show slope.

To do this, we need more animated blue ranges.  The current 'darker' water cycle has 5 steps.  We need 'even darker water' and 'light water'.  Or some tricks to approximate that using 32bpp with a restricted set of pre-defined extra colours, maybe with some pre-processing step where the actual sprite could use DOS palette and then request the blue is shaded / tinted ~40%.

![image](https://user-images.githubusercontent.com/1780327/205512217-b8fcb34c-5455-46f5-8700-258e65766b12.png)
![image](https://user-images.githubusercontent.com/1780327/205512223-0220ffd1-99d0-44cc-8c26-817b601bced8.png)

I did try both adding more rocks, and using OpenGFX lock water slope, which has directional 'flow' animation downhill.  Neither were sufficient.

**Comment by zephyris** [comment]
I'm pretty sure theres's a solution using 32bpp and a mask image: You can use animated palette entries in the mask image, overlaid on shades of gray to brighten and darken them. The mask sprite can be the existing 8bpp water slope sprites. The 32bpp sprite needs to be a single shade of gray - 128,128,128 for flat tiles (unchanged brightness), say 90,90,90 for the darker slopes and say 170,170,170 for the lighter slopes.

I haven't tested this, but I'm pretty sure it'll work. I'll try to bash together a demo newgrf.

**Comment by zephyris** [comment]
The result (and yes, it is animated):
![screenie](https://github.com/OpenTTD/OpenTTD/assets/2762690/4fa7daba-71d3-4baa-8a50-f13dc4c66da0)

The implementation:
```
//Template: water slopes
template template_waterslopes(x, y) {
	//Flat tile
	[ 322+x, 1+y, 64, 32-1, -31,  0 ]
	//Sloped tiles
	[  81+x, 1+y, 64, 24-1, -31,  0 ]
	[ 241+x, 1+y, 64, 40-1, -31, -8 ]
	[   1+x, 1+y, 64, 24-1, -31,  0 ]
	[ 161+x, 1+y, 64, 40-1, -31, -8 ]
}

spriteset (waterfeature_waterslopes, "watertiles_8bpp.png") { template_waterslopes(80, 0) }
alternative_sprites(waterfeature_waterslopes, ZOOM_LEVEL_NORMAL, BIT_DEPTH_32BPP, "watertiles_true32bpp.png", "watertiles_8bpp.png") { template_waterslopes(80, 0) }

item(FEAT_CANALS, waterfeature_canal_slopes, WF_WATERCLIFFS) {
	property { graphic_flags: bitmask(WATERFEATURE_ALTERNATIVE_SPRITES); }
	graphics { default: waterfeature_waterslopes; }
}

item(FEAT_CANALS, waterfeature_river_slopes, WF_RIVER_SLOPE) {
	property { graphic_flags: bitmask(WATERFEATURE_ALTERNATIVE_SPRITES); }
	graphics { default: waterfeature_waterslopes; }
}
```

watertiles_8bpp.png
![watertiles_8bpp](https://github.com/OpenTTD/OpenTTD/assets/2762690/baee9004-3be6-4a2a-b944-533c0f701324)

watertiles_true32bpp.png
![watertiles_true32bpp](https://github.com/OpenTTD/OpenTTD/assets/2762690/34b90f51-7efe-426e-972b-1bfa751967fa)

**Comment by zephyris** [comment]
![opengfx2_rockriver](https://github.com/OpenTTD/OpenTTD/assets/2762690/e146fd41-feb1-4a4e-b63b-34b34cfb04ca)
My suggestion, with shaded water, rocks and white water on the cascades. Multiple strong indications of impassability for ships, for maximum new user-friendliness. This is what I've put into my OpenGFX2.

**Comment by George-VB** [comment]
I'd suggest to provide other solution. It would be much better if sloped river tiles would not require locks, but allow ships to go up and down the hills like trains do. That would not only solve the routing issue of the topicstarter, but provide a new strategy for the beginning of the game with the cheap ship routes (because you build only dock and ship, and the route already exists)

**Comment by George-VB** [comment]
I'd suggest to provide other solution. It would be much better if sloped river tiles would not require locks, but allow ships to go up and down the hills like trains do. That would not only solve the routing issue of the topicstarter, but provide a new strategy for the beginning of the game with the cheap ship routes (because you build only dock and ship, and the route already exists)

**Comment by zephyris** [comment]
![slopeshadig](https://github.com/OpenTTD/OpenTTD/assets/2762690/ec09e9c4-453d-4706-9f0a-efb3135c80b7)
IMO this fixes this issue sufficiently for original graphics: https://github.com/OpenTTD/OpenTTD/pull/11491
