### ISSUE TITLE
No obvious way to change player name during multiplayer session

### ISSUE THREAD

**Issue by PeterN** [OpenTTD/OpenTTD#9035]
## Version of OpenTTD

1.11.0

## Expected result

A button somewhere (client list perhaps?) that opens a query window to change your player name after joining a multiplayer session.

## Actual result

Changing your name requires bringing up the console and using the "name" command.

## Steps to reproduce

1. You have to find out how to bring up the console.
2. Type `help` to bring up the help list
3. Type `list_cmds` to list all the console commands.
4. Hopefully you read the help text all the way and remembered that you need to press shift+pgup to scroll the list.
5. You see there is the command `clientname` but typing that says it's only available to a network server.
6. So you then hunt around and find that the unlisted command is `name`,
7. Type `name` which tells you what your `client_name` is (but client_name is also a network server-only command).
8. Type `name <name>`  to actually change your name.
9. It's actually a shortcut for `setting network.client_name <name>` but...

**Comment by notchloeno** [comment]
This isn't really an issue; a player's name has almost zero bearing in a session, and a quick google can tell you how to use the name command

**Comment by telk5093** [comment]
Nevertheless, a button to change client's name (such as, on the company information window) will help newbies to change their names. I have operated own multiplayer server long time and I've seen that many player have tried to change their name by quitting server, rename and re-joining.

**Comment by nielsmh** [comment]
In general, as part of a new during-game network UI, it would be an obvious candidate for feature.
