### ISSUE TITLE
Game Crashed

### ISSUE THREAD

**Issue by unbeatable-101** [OpenTTD/OpenTTD#9055]
## Version of OpenTTD
1.11.0

The game crashed

## Steps to reproduce
[crash.log](https://github.com/OpenTTD/OpenTTD/files/6332095/crash.log)
![crash](https://user-images.githubusercontent.com/58151048/115159048-3830ed80-a05f-11eb-84f8-d9c0b0068daa.png)

[crash.sav.zip](https://github.com/OpenTTD/OpenTTD/files/6332097/crash.sav.zip)

**Comment by LordAro** [comment]
Were you doing anything at the time of the crash? (Clicking a button, etc?)

**Comment by unbeatable-101** [comment]
I had opened the finance window a few seconds before, but I wasn't doing anything at the time of the crash

**Comment by LordAro** [comment]
Hmm, tricky one, as crash.log isn't particularly useful in this case. If you reload crash.sav, does it crash again?

**Comment by unbeatable-101** [comment]
No

**Comment by michicc** [comment]
It might not have anything to do with it, but from the crashlog I can see you've enabled hardware acceleration in the game options. For OSX specifically using hardware acceleration isn't really the preferred option.

**Comment by LordAro** [comment]
We've talked it over, and we *think* that this is a duplicate of #8977, which is fixed in the soon-to-be-released 1.11.1 - the nature of the crash might mean that it doesn't break immediately, but at some random point later on. Is this setting ("Highest resolution sprites to use") something you changed at some point earlier?

**Comment by unbeatable-101** [comment]
My zoom in level is 4x, and my zoom out level is 8x

"Highest resolution sprites to use" is set to 4x

**Comment by unbeatable-101** [comment]
> It might not have anything to do with it, but from the crashlog I can see you've enabled hardware acceleration in the game options. For OSX specifically using hardware acceleration isn't really the preferred option.

I disabled that and it hasn't happened since.
