### ISSUE TITLE
Clear land tool clears areas that are already cleared (bare land)

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#9061]
## Version of OpenTTD
1.11.1

## Expected result
When clearing an area of tiles, the clear action should ignore any tiles that are already cleared (bare land, appearing as brown dirt). Any tiles that are not fully bare land (such as any stage of grass, snow or desert) still get cleared as normal.

## Actual result
When clearing an area of tiles, the clear action will clear tiles that are already cleared (bare land), which, when combined with very low landscaping limits, means that you have to select lots of very small areas, increasing the complexity and number of unique clicks you have to do to clear a large area. By contrast, planting trees and terraforming can be performed gradually just be selecting the same large area over and over again, even on very low landscaping limits.

## Steps to reproduce
1. Start a new game (at least 256x256).
2. Open the cheats window and increment your money several times (so that you have a couple hundred million GBP or equivalent).
3. Open viewports at the top (first tile) and bottom (last tile) of the map.
4. Drag the clear area tool from the top of the map to the bottom of the map several times.
5. Notice that after the first clear, the land area that is cleared will not increase with subsequent clears.
6. Drag the level land tool from the top of the map to the bottom of the map several times.
7. Notice that after the first level land iteration, the land area that is flattened will increase with subsequent iterations.

**Comment by PeterN** [comment]
Intended behaviour I feel. You can bulldoze bulldozed land.

Your counter-example of tree is kind of wrong, as you can plant more trees on top of existing trees (up to 3), and it does cost money.

Landscaping that doesn't alter the land height doesn't get included because it doesn't do anything.

**Comment by nielsmh** [comment]
Additionally, clearing empty land (grassland) is in fact an action, and it is done internally as part of building most things, like building rails on a tile actually clears the tile first, then places the rail. You will see a difference in cost of building rail on a "grass" tile versus a "dirt" tile, since the "dirt" tile is already clear.

**Comment by TrueBrain** [comment]
I think the verdict is that this is not a bug. Sorry :(

We consider the bulldozing an action, no matter if the land was just bulldozed. As mentioned above, there are reasons for that, but bulldozed land is also very quickly not fully bare anymore.

Basically, the action is to ask bulldozers to run over the land, no matter how it looks. Which costs money / terraform costs. And indeed, if you play with very low terraform limits, that does mean that if you want to bulldoze a large area, you will have to make a lot of smaller clicks. But I am afraid that is what the game is.

**Comment by ldpl** [comment]
smth like #7497 would probably work well for this usecase
