### ISSUE TITLE
"File version" is incorrect for Windows OpenTTD executable

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#9062]
## Version of OpenTTD
`OpenTTD 1.11.1` from the build artifacts for `openttd-1.11.1-windows-win64` or `openttd-1.11.1-windows-win32`

## Expected result
The "File version" that is part of the `openttd.exe` metadata should say `1.11.1.25330` (next: `1.11.2.25330`).

## Actual result
The "File version" that is part of the `openttd.exe` metadata says `1.11.0.25330`. Reinstalling the game from the installer still leaves the value `1.11.0.25330` for the file version, and so does installing the game from the zip archive.

## Steps to reproduce
1. Download `openttd-1.11.1-windows-win64` or `openttd-1.11.1-windows-win32` (zip archive or installer) onto a Windows 10 device.
2. Using Windows 10's File Explorer, look at the `File version` in the tooltip that comes up when you hover over `openttd.exe`.
3. Notice that it says `1.11.0.25330` and not the expected `1.11.1.25330` (next: `1.11.2.25330`).

**Comment by PeterN** [comment]
This is something that should be borne in mind for the future. It is obviously not possible to fix this for 1.11.1...

**Comment by glx22** [comment]
Quickly checked source, master also shows 1.11.0.xxxx

**Comment by LordAro** [comment]
Curious.

https://github.com/OpenTTD/OpenTTD/blob/f757d07bb3884b55854ccd3035c3321c97d993dc/CPackProperties.cmake.in#L2

But `REV_VERSION` is definitely correct: https://github.com/OpenTTD/OpenTTD/runs/2375987432?check_suite_focus=true#step:12:115

CPACK_PACKAGE_VERSION is an internal cpack variable, perhaps it's getting confused/reused somehow?

**Comment by glx22** [comment]
`ottdres.rc` uses hard coded value, I'll see what I can do to fix that automatically.

**Comment by PeterN** [comment]
`make_installer.cmd` for os2 and `osx_stdafx.h` for OS X are also hardcoded.

**Comment by glx22** [comment]
`osx_stdafx.h` doesn't contain openttd version, and for os2 every versions are hard coded, but I guess it should be possible to auto generate `make_installer.cmd` with correct openttd version.

**Comment by orudge** [comment]
The OS/2 installer stuff there is somewhat redundant; "modern" OS/2 appears to use RPM for package distribution. At some point I intend to update the OS/2 stuff, I'd just ignore it for now.
