### ISSUE TITLE
Train cannot get a path to continue while there is no other train

### ISSUE THREAD

**Issue by RailwAI** [OpenTTD/OpenTTD#9065]
## Version of OpenTTD
1.11.1

## Expected result
In this savegame, the blue AI company (Rocky Shuttle d.d.) has only one train. I would expect that this train can continue.

## Actual result
The only train of the blue AI company is waiting for a free path to continue.
![image](https://user-images.githubusercontent.com/42977884/115253773-fcfcf000-a12c-11eb-8aa6-fbeedcdce7de.png)

## Steps to reproduce
Open the attached savegame.

[Unnamed, 2051-01-18.zip](https://github.com/OpenTTD/OpenTTD/files/6336853/Unnamed.2051-01-18.zip)

**Comment by LordAro** [comment]
There is a one-way signal pointing the wrong way (though hidden behind the slope)

![image](https://user-images.githubusercontent.com/4007992/115254356-29ad0980-a125-11eb-816b-f738e45152e0.png)

**Comment by RailwAI** [comment]
You're quick and well spotted! I didn't see it, but then I can close this issue.
