### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Rawstylez** [OpenTTD/OpenTTD#9132]
[crash.zip](https://github.com/OpenTTD/OpenTTD/files/6394121/crash.zip)

## Version of OpenTTD

open ttd 1. 11. 1, win7 64
## Steps to reproduce

launch crash

**Comment by James103** [comment]
1. Have you tried reproducing this using the latest nightly? Either download from https://www.openttd.org/downloads/openttd-nightlies/latest.html or switch to the beta channel in Steam.
2. Have you tried setting `video_hw_accel = false` in `%UserProfile%\Documents\OpenTTD\openttd.cfg`?

**Comment by Rawstylez** [comment]
> 1. Have you tried reproducing this using the latest nightly? Either download from https://www.openttd.org/downloads/openttd-nightlies/latest.html or switch to the beta channel in Steam.
> 2. Have you tried setting `video_hw_accel = false` in `%UserProfile%\Documents\OpenTTD\openttd.cfg`?

Okey. Nightly work.
openttd.cfg was not generated.

But after running nightly version, everything worked. Thanks!

**Comment by glx22** [comment]
Duplicate of #8967
