### ISSUE TITLE
Fatal application failure

### ISSUE THREAD

**Issue by BlackHawk05** [OpenTTD/OpenTTD#9136]
Fatal application failure
[Crash dump](http://dl.csserv.ru/1619669972.rar)

**Comment by nielsmh** [comment]
Please upload the attachments to GitHub instead of using an external hosting service.

**Comment by glx22** [comment]
Duplicate of #8967, according to #9132 nightlies should work.

**Comment by LordAro** [comment]
Duplicate of #8967. Should be fixed in 1.11.2, released now!
