### ISSUE TITLE
Some wagons dissappeard after few years

### ISSUE THREAD

**Issue by cgrim-cz** [OpenTTD/OpenTTD#9145]
## Version of OpenTTD
OpenTTD: 1.11.1 (official Fedora rpm package)
OS: Linux - Fedora 33

## Expected result
All types of wagons are still available.

## Actual result
My daughter started new game in toys land in 1979 and in she 1992 she realized that some wagon types are not available anymore. These are missing:

- Suger Truck
- Candyfloss Hopper
- Bubble Van
- Toy Van

When we loaded saved game from 1990, then only Toy Van is missing there.
When we let the game continue then in 1995 only 4 wagons were available and in 1999 no wagon and game is unplayable.

When we start completely new game in 1993 then all wagons are there.

## Steps to reproduce

See screenshots:
1989
![1989](https://user-images.githubusercontent.com/39614988/116724541-15002980-a9e1-11eb-8d79-f90e3c13ab26.png)
1992
![1992](https://user-images.githubusercontent.com/39614988/116724563-1c273780-a9e1-11eb-8382-a469202c05e7.png)
1995
![1995](https://user-images.githubusercontent.com/39614988/116724565-1c273780-a9e1-11eb-9420-da14750ae218.png)
1999
![1999](https://user-images.githubusercontent.com/39614988/116724993-a40d4180-a9e1-11eb-8a84-cc3896bb4313.png)

And here is the saved game:
[saved-game.zip](https://github.com/OpenTTD/OpenTTD/files/6406804/saved-game.zip)

**Comment by James103** [comment]
If you want to get expired vehicles and engines back, you should do the following;
1. Turn the "Vehicles never expire" setting on.
2. Pull down the console (with the tilde/grave accent key) and run the command `resetengines`.

**Comment by cgrim-cz** [comment]
Thank you very much! I didn't know about this functionality. I've never encountered it before in previous plays. So I'm sorry for the stupid bug report, I should have asked about that in a forum first.

**Comment by LordAro** [comment]
No no, it's not a stupid thing, i wouldn't expect wagons to expire like that - they don't in the other climates. I'm going to reopen it, just to confirm it's expected behaviour (inherited from TTD) rather than any other issue

**Comment by FLHerne** [comment]
After rail wagons expire, monorail and maglev vehicles will be available. The last maglev vehicles never expire regardless of that setting, so the game should be playable for any length of time.

**Comment by odisseus** [comment]
I think there should always be at least one wagon for every type of cargo and every rail type. For what it's worth, this is the case with the default vehicle set in other three climates. 

However, it seems that your vehicles come from an add-on, because the default engine set for Toyland [is different](https://wiki.openttd.org/en/Manual/Trains). A typo in one of the names ("suger" instead of sugar) also suggests this.

Perhaps the problem lies not in the core game, but within that add-on. In that case, you should report this problem to its developers.

**Comment by cgrim-cz** [comment]
@odisseus You are right, we had _Toyland to Mars Conversion_. When I disable it and start a new game in Toyland then the bug is not there. It really seems like it must be in that extension or the extension is not compatible wit the latest OpenTTD version.
Thanks for your time.

**Comment by TrueBrain** [comment]
Given this new insight, I think it is safe to say this ticket can now be closed again :) The base game is doing the right thing .. the NewGRF, in my opinion, less so :) But that is a bug for the NewGRF, not for us.

Tnx for the extra information @cgrim-cz , much appreciated :)
