### ISSUE TITLE
Linkgraphs don't show direction of each link

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#9167]
## Version of OpenTTD
1.11.1 and earlier

## Expected result
Linkgraphs like the Cargo Flow Legend overlay or the smallmap linkgraph, clearly indicate the direction of each link, perhaps with an arrow of some type.

## Actual result
![rhd](https://user-images.githubusercontent.com/55058389/116788591-7e7f4700-aa78-11eb-94fc-259bc03475e6.png)

Which colour is passengers from Treninghall to Martston, and which colour is the return trip?

(Answer: it matches the side road vehicles drive on, but this isn't indicated anywhere.)

This problem exists for both the overlay and smallmap linkgraphs.

## Steps to reproduce

1. Start a game with cargo distribution enabled for passengers (symmetric is fine). 
2. Connect two towns with a bus route.
3. Open the Cargo Flow Legend from the map icon in the main toolbar, and enable Passengers for your company.

**Comment by glx22** [comment]
I tried something, but I'm not sure it's a good idea.
![Ninfingley Transport, 24 Jun 1960](https://user-images.githubusercontent.com/2952192/116790198-5bbe5400-aab3-11eb-87ac-f8e90c1c9a96.png)

**Comment by 2TallTyler** [comment]
I like where you're going, but it's still somewhat ambiguous — could be pointed either direction as an arrowhead or a comet tail.

**Comment by glx22** [comment]
Another try.
![Ninfingley Transport, 16 Avr 1960](https://user-images.githubusercontent.com/2952192/116790695-02a3ef80-aab6-11eb-8a08-38fe1c89c93e.png)

**Comment by 2TallTyler** [comment]
Better, but it's very subtle. Perhaps the arrows could be shorter, maybe even a fixed length instead of half the link distance?

**Comment by glx22** [comment]
Fixed length is complicated, in this one the arrow length is 1/6th of link distance with an empty head.
Anyway not being able to zoom in the minimap doesn't really help to see the arrow, same goes for the green on green.
![Ninfingley Transport, 1er Déc 1960](https://user-images.githubusercontent.com/2952192/116797606-b2de1c00-aae7-11eb-9946-ef0f2ecb6081.png)

**Comment by James103** [comment]
> Anyway not being able to zoom in the minimap doesn't really help to see the arrow, same goes for the green on green.

Ignore the reference above, the actual issue that this is referring to is #8998.

**Comment by 2TallTyler** [comment]
The empty arrow head is very easy to see on the overlay. It's a bit problematic on the smallmap. Absent a PR to increase zoom, perhaps leaving the arrow off the smallmap would be possible? I can't imagine using the smallmap linkgraph anyway in its current max zoom...

**Comment by glx22** [comment]
![image](https://user-images.githubusercontent.com/2952192/127564115-86b5913d-2a2a-4932-b46a-f15853010231.png)
I finally did some math, and now the arrow heads are fixed size and isosceles right triangles (10px in smallmap, 30px in viewport).
Size also doesn't depend on zoom level.

**Comment by 2TallTyler** [comment]
Closed by #9760
