### ISSUE TITLE
Station drawing glitch?

### ISSUE THREAD

**Issue by Milek7** [OpenTTD/OpenTTD#9186]
## Version of OpenTTD
1.11.2 win64

## Expected result
No glitching.

## Actual result
Glitching.

## Steps to reproduce
- Load titlegame
- Pay attention to this fragment of station roof:
![obraz](https://user-images.githubusercontent.com/7935014/116933457-dd54e400-ac63-11eb-858a-87e8e29d9ae4.png)
- Observe that it flickers when train departs

**Comment by JGRennison** [comment]
This sort of issue is a fundamental property of the sprite sorting algorithm, which is inherited from the original TTD.
Unfortunately the existing set of GRFs effectively depends on and have grown around the quirks of the sprite sorting algorithm, so changing it to have different/better behaviour is highly problematic.
