### ISSUE TITLE
empty window Check Online Content

### ISSUE THREAD

**Issue by nirasa1957** [OpenTTD/OpenTTD#9198]
XUbuntu 18.04.
OpenTTD 1.11.2.
OpenTTD JGR 0.41.0.

When I want to download a newgrf from Check Online Content, the window is empty in both versions. This has been happening to me for the last 3 days. The download does not work even for a completely new configuration folder.
Each version has its own configuration folder.
Kamnet advised me:  Typically it fixes itself if you exit the content download screen and immediately go back into it. But... 
The window is still empty.

**Comment by James103** [comment]
Have you tried the following tests from #8582?
* If you are behind a proxy/VPN, try disabling said proxy first.
* Check that https://www.openttd.org/ shows OpenTTD's frontpage
* Check that https://content.openttd.org/ shows a full blank page (no error)
* Make sure that the firewall allows 3978 outbound
* Open Multiplayer, then click "Search internet" and make sure that it returns various servers.
* See if you can connect to a multiplayer server.
* **Try disabling IPv6 and reconnecting** (that worked for @Matias-Barrios in #8582)
* Try the latest nightly version from https://www.openttd.org/downloads/openttd-nightlies/latest.html.

**Comment by LordAro** [comment]
There will likely be some error notice output to the terminal. Run OpenTTD via that and see what you get

**Comment by nirasa1957** [comment]
Thank you so much for all the advice, but only one works in part...
I don't have a proxy and I don't have a firewall.
Multiplayer is ok.
Everything in the game works, but component download does not work.
I have banned IPv6 for a long time.
The terminal did not show any error.

The nightly build of the game works, but only according to Kamnet's advice. It works for me to close and reopen the Component Downloads window.

**Comment by TrueBrain** [comment]
Can you try two more things for me:

1) with the nightly, open the Online Content and wait for 3 seconds. Does anything show up then?
2) Start the game with `-dnet=4` and try the trick that works for you. What does the console report back to you?

Tnx!

**Comment by nirasa1957** [comment]
1. Yes, TrueBrain, at night the list will appear after 3 seconds.
2. In these cases, the sheet does not appear:
Version JGR 0.41.0 linux:
```
 irenas@irenas-xubuntu:~/openttd-jgrpp-41$ ./openttd -dnet=4
dbg: [net] [core] starting network...
dbg: [net] [udp] initializing listeners
dbg: [net] [core] network online, multiplayer available
dbg: [net] Detected broadcast addresses:
dbg: [net] 0) 192.168.100.255
dbg: [net] 1) 25.255.255.255
dbg: [net] Connecting to [content.openttd.org]:3978 (IPv6)
dbg: [net] [udp] closed listeners
dbg: [net] [udp] initializing listeners
dbg: [net] [udp] closed listeners
dbg: [net] [core] shutting down network
```

Version 1.11.2. for Windows via the "wine":
```
 wine openttd.exe -dnet=4
wine: Call from 0x7bc5b50c to unimplemented function ntdll.dll.__wine_dbg_header, aborting
wine: Call from 0x7bc5b50c to unimplemented function ntdll.dll.__wine_dbg_header, aborting
000f:err:module:attach_dlls "ucrtbase.dll" failed to initialize, aborting
000f:err:module:attach_dlls Initializing dlls for L"C:\\windows\\system32\\services.exe" failed, status 80000100
000b:err:wineboot:start_services_process Unexpected termination of services.exe - exit code -2147483392
wine: Call from 0x7bc5b50c to unimplemented function ntdll.dll.__wine_dbg_header, aborting
wine: Call from 0x7bc5b50c to unimplemented function ntdll.dll.__wine_dbg_header, aborting
000d:err:module:attach_dlls "ucrtbase.dll" failed to initialize, aborting
000d:err:module:attach_dlls Initializing dlls for L"C:\\windows\\system32\\winemenubuilder.exe" failed, status 80000100
wine: Call from 0x7bc5b50c to unimplemented function ntdll.dll.__wine_dbg_header, aborting
wine: Call from 0x7bc5b50c to unimplemented function ntdll.dll.__wine_dbg_header, aborting
0017:err:module:attach_dlls "ucrtbase.dll" failed to initialize, aborting
0017:err:module:attach_dlls Initializing dlls for L"C:\\windows\\system32\\services.exe" failed, status 80000100
0013:err:wineboot:start_services_process Unexpected termination of services.exe - exit code -2147483392
wine: Call from 0x7bc5b50c to unimplemented function ntdll.dll.__wine_dbg_header, aborting
wine: Call from 0x7bc5b50c to unimplemented function ntdll.dll.__wine_dbg_header, aborting
0015:err:module:attach_dlls "ucrtbase.dll" failed to initialize, aborting
0015:err:module:attach_dlls Initializing dlls for L"C:\\windows\\system32\\winemenubuilder.exe" failed, status 80000100
dbg: [net] [core] starting network...
dbg: [net] [core] loading windows socket library
dbg: [net] [udp] initializing listeners
dbg: [net] [core] network online, multiplayer available
dbg: [net] Detected broadcast addresses:
dbg: [net] 0) 192.168.100.255
dbg: [net] 1) 25.255.255.255
dbg: [net] Connecting to [content.openttd.org]:3978 (IPv6)
dbg: [net] [udp] closed listeners
dbg: [net] [udp] initializing listeners
dbg: [net] [udp] closed listeners
dbg: [net] [core] shutting down network
AL lib: (EE) ReleaseThreadCtx: Context 0x7c756830 current for thread being destroyed, possible leak!
irenas@irenas-xubuntu:~/openttd-1-11-win$ 
```

**Comment by TrueBrain** [comment]
Sadly enough, the problem is your local connection, and specifically, IPv6.

OpenTTD always prefers IPv6 over IPv4 if available. Your DNS resolves IPv6 for `content.openttd.org`, but fails to setup a connection to it (which an be seen in the logs here: `dbg: [net] Connecting to [content.openttd.org]:3978 (IPv6)`).

In 1.11.2, it will wait the default timeout .. which is something like 20 seconds or more (depending on OS, mostly).
In the nightly we recently changed this into 3 seconds.
And this is what you are seeing.

So after the timeout, it falls back to IPv4, which does create a valid connection for you, and the list is shown.

Sadly, this is not something we can fix. Your system resolves a domain to an IPv6 address, while it cannot connect to that IPv6 address. This is something you have to fix locally.


PS: did you know we have a linux build of OpenTTD? No need for all this `wine` stuff :)

**Comment by nirasa1957** [comment]
Thank you, TrueBrain. 
What can I do with IPv6, please? It is disabled on my computer.

Yes, you knew I had linux. I say everywhere that I have linux and I don't have windows. It is written in the first report above ;-)

**Comment by TrueBrain** [comment]
I know you have Linux. I am also letting you know we have a Linux build :) No need to use the Windows build ;)

For your IPv6 issue, this is something out of our scope. Your OS is resolving `content.openttd.org` to a valid IPv6 address (and doesn't fail instantly when sending an IPv6 packet), which it should never do if there is no IPv6 support. You mentioned it was working a few days ago but stopped working; so my best guess would be that something changed on your local machine. But for what that is .. sadly .. I cannot help with :( Sorry.

**Comment by nirasa1957** [comment]
Ok. So I don't know anything. Thank you. :-(

**Comment by LordAro** [comment]
If it helps, you can *probably* just wait for IPv6 to timeout with the default 20s with 1.11.2/JGR and the content window will load, as per details in #9112

Honestly, there's a decent chance that if you just undo whatever you did to disable IPv6, it will just work :)

**Comment by nirasa1957** [comment]
Sorry, TrueBrain, I don't speak English and I don't understand you. I'm a retiree and I just wanted your help.

**Comment by nirasa1957** [comment]
Ok, LordAro, I will try it. Thanks a lot
