### ISSUE TITLE
The victory screen newspaper slows the game down considerably

### ISSUE THREAD

**Issue by unbeatable-101** [OpenTTD/OpenTTD#9209]
## Version of OpenTTD

OpenTTD Version 1.11.2 (1.11.2), macOS 11.3.1 (20E241)
## Expected result

The game doesn't grind to a halt displaying it
## Actual result

The game grinds to a halt displaying it
## Steps to reproduce

Play until the victory date (In my case 2051-01-01)
[Punfingwell City Transport, 2050-12-19.sav.zip](https://github.com/OpenTTD/OpenTTD/files/6444726/Punfingwell.City.Transport.2050-12-19.sav.zip)

https://user-images.githubusercontent.com/58151048/117517599-7dfc1a00-af6a-11eb-9672-a512ec9687db.mp4

**Comment by PeterN** [comment]
This is also reproducible from the Highscore table accessible from the main intro menu.
