### ISSUE TITLE
Charts do not repect font size increases

### ISSUE THREAD

**Issue by unbeatable-101** [OpenTTD/OpenTTD#9218]
## Version of OpenTTD

OpenTTD Version 1.11.2 (1.11.2), macOS 11.3.1 (20E241)
## Expected result

The legends and labels of the charts increase their font size in accordance with the setting
## Actual result

They stay at normal font size
## Steps to reproduce

1. Set your font size to double or quad
2. Open one of the charts ingame

## Examples
![Screen Shot 2021-05-08 at 10 44 00](https://user-images.githubusercontent.com/58151048/117543337-606e9500-afea-11eb-8b91-869e2e655040.png)
![Screen Shot 2021-05-08 at 10 44 21](https://user-images.githubusercontent.com/58151048/117543339-63698580-afea-11eb-802a-876ffb213068.png)

**Comment by PeterN** [comment]
Which bit is not scaling? I don't see anything obviously wrong from just the pictures.

**Comment by unbeatable-101** [comment]
The labels and legend, or maybe they are scaling and their default size is way smaller than I remember it being.

**Comment by rubidium42** [comment]
I think you might have selected "Double size" for "Interface size" and "Normal" for "Font size". At least for me the information bar at the bottom looks exactly the same with those settings. With those settings the font size does not get changed, so I suggest changing the "Font size" to "Double size".
