### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by giantkin** [OpenTTD/OpenTTD#9224]
## Version of OpenTTD

Win10 20H2 19042.928

[crash.log](https://github.com/OpenTTD/OpenTTD/files/6447701/crash.log)

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/6447703/crash.zip)
 
Ottd unknown, never starts. 

## Steps to reproduce

at start up (steam version)  Just updated, and tried again, this is result of latest steam version.

**Comment by James103** [comment]
```
Decoded stack trace:
[00] ???                  0x0000000000000000
[01] atio6axx             0x00007FFE96B9C6CA DrvSwapBuffers + 18202
[02] atio6axx             0x00007FFE96BA362E DrvSwapBuffers + 46718
[03] atio6axx             0x00007FFE96B9804B DrvSwapBuffers + 155
[04] atio6axx             0x00007FFE96B9396C getEGLInterface + 91052
[05] atio6axx             0x00007FFE96B96E79 DrvValidateVersion + 185
[06] OPENGL32             0x00007FFEA0771185 wglSwapMultipleBuffers + 10821
[07] OPENGL32             0x00007FFEA07715E4 wglSwapMultipleBuffers + 11940
[08] OPENGL32             0x00007FFEA0773C7C wglCopyContext + 3628
[09] OPENGL32             0x00007FFEA078FC90 wglGetPixelFormat + 128
[10] OPENGL32             0x00007FFEA0790CB1 wglDescribePixelFormat + 241
[11] OPENGL32             0x00007FFEA07900B3 wglChoosePixelFormat + 99
[12] gdi32full            0x00007FFEDCAB2449 ChoosePixelFormat + 57
...
```
Crashes in OpenGL (more specifically `atio6axx.dll`), may be related to #8967
1. Have you tried reproducing this using the latest nightly? Either download from https://www.openttd.org/downloads/openttd-nightlies/latest.html or switch to the nightly beta channel in Steam.
2. Have you tried setting `video_hw_accel = false` in `%UserProfile%\Documents\OpenTTD\openttd.cfg`?

**Comment by giantkin** [comment]
Havent tried anything. (i added on release to steam) has crashed every time since. (2 systems)
    I'll try the vid setting now.   .openttd.cfg is not in that directory.

However, im now thinking that the steam version and my local version are conflicting.   i still have cfg from 2015 on this system.
     I guess i have to try to uninstall.  (ive never uninstalled ottd, only Installed upon new systems!) lol.

**Comment by giantkin** [comment]
same error:  (I uninstalled in steam, uninstalled from Portableapps) and Reinstalled from steam. following crash)

*** OpenTTD Crash Report ***

Crash at: Sun May  9 15:08:37 2021
In game date: 0-01-01 (0)

Crash reason:
 Exception: C0000005
 Location:  0000000000000000
 Message:   <none>

OpenTTD version:
 Version:    1.11.2 (0)
 NewGRF ver: 1b286d64
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: May  3 2021 18:47:06

Registers:
 RAX: 000001FF4C064C50 RBX: FFFFFFFFFFFFFFFF RCX: 00000093EE0D9260 RDX: 00000093EE0D9274
 RSI: 0000000000000000 RDI: 0000000000000001 RBP: 00000093EE0D9330 RSP: 00000093EE0D9228
 R8:  00000093EE0D9284 R9:  0000000000000001 R10: 0000000000008000 R11: 00000093EE0D9210
 R12: 00000093EE0D9740 R13: 0000000000000000 R14: 000001FF4C095250 R15: 000001FF4C095250
 RIP: 0000000000000000 EFLAGS: 00010246

 Bytes at instruction pointer:
 ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??

Stack trace:
 96B9C6CA 00007FFE FFFFFFFF FFFFFFFF 98065A18 00007FFE 00000000 00000000
 00000020 00000000 00000001 00000000 00000101 00007FFE 00000000 00000093
 00000000 00000093 4C0641D0 00000000 00000000 00000000 00000040 00000000
 00000180 000001FF 00000000 00000000 00000000 00000000 00000000 00000000
 98CA48F0 00007FFE 4C04B920 000001FF 00000000 00000000 00000000 00000000
 00000000 00000000 4C0641D0 000001FF 00000017 00000000 00000016 00000000
 00000001 000001FF 00000002 00000000 97EAA129 00007FFE EE0D9410 00000093
 00000040 00000000 EE0D9410 00000093 00000040 00000000 00000040 0000D736
 00000180 00007FFE 00000001 00000000 DCD63C5D 00007FFE 00000001 00000002
 DF015BA1 00007FFE 4C05F0A0 000001FF 97EAA8A5 00007FFE 00000000 00000000
 97EA360D 00007FFE 00000FA0 00000000 4C058F90 000001FF 4C0648F0 000001FF
 0000006A 00000000 4C05F0A0 000001FF 4C065840 000001FF 98062FD4 00007FFE
 00000040 00000000 492F0000 000001FF EE0D95B0 00000093 00000180 00000093
 97E9DE4D 00007FFE 00000000 00000001 00000001 00000000 00000060 00000000
 00000000 00000000 00000006 00000000 4C05C8E0 000001FF 4C0665E0 000001FF
 DF0147B1 00007FFE 00000000 00000000 493E0000 000001FF EE0D95B0 00000093
 00000000 00000000 00000000 00000000 97E581E5 00007FFE 00000002 00000000
 97E9FA4C 00007FFE 4C0665E0 000001FF EE0D9740 00000093 FFFFFFFE FFFFFFFF
 96BA3EAA 00007FFE 4C0665E0 000001FF 97E58073 00007FFE EE0D95B0 00000093
 00000000 00000000 004C0047 006E0045 00620061 0065006C EE0D9900 00000093
 96BA7597 00007FFE EE0D9920 00000093 EE0D95B0 00000093 EE0D9740 00000093
 00000053 00000000 00000000 00000000 00000000 00000000 00000000 00000000
 0000000F 00000000 00000000 00000000 00000000 00000000 98963248 00007FFE
 00000000 00000000 98014968 00007FFE 00000000 00000000 00000000 00000000

Operating system:
 Name:     Windows
 Release:  10.0.19042 ()
 Compiler: MSVC 1928

Configuration:
 Blitter:      32bpp-anim
 Graphics set: OpenGFX (7761)
 Language:     C:\Program Files (x86)\Steam\steamapps\common\OpenTTD\lang\english_US.lng
 Music driver: none
 Music set:    none (4294967295)
 Network:      no
 Sound driver: none
 Sound set:    none (4294967295)
 Video driver: win32-opengl

Fonts:
 Small:  sprite
 Medium: sprite
 Large:  sprite
 Mono:   sprite

AI Configuration (local: 0) (current: 0):

Libraries:
 LZMA:       5.2.5
 LZO:        2.10
 PNG:        1.6.37
 Zlib:       1.2.11

Module information:
 C:\Program Files (x86)\Steam\steamapps\common\OpenTTD\openttd.exe handle: 00007FF687610000 size: 8557056 crc: 7352D10F date: 2021-05-09 15:08:28
 C:\WINDOWS\SYSTEM32\ntdll.dll handle: 00007FFEDEFF0000 size: 2024728 crc: 4399D735 date: 2021-04-20 14:01:15
 C:\WINDOWS\System32\KERNEL32.DLL handle: 00007FFEDD890000 size: 764976 crc: 3A191151 date: 2021-04-20 14:01:06
 C:\WINDOWS\System32\KERNELBASE.dll handle: 00007FFEDCD00000 size: 2919288 crc: EAF99E19 date: 2021-04-20 14:01:16
 C:\WINDOWS\System32\WS2_32.dll handle: 00007FFEDD540000 size: 427200 crc: 6E37A637 date: 2021-03-13 23:13:10
 C:\WINDOWS\System32\RPCRT4.dll handle: 00007FFEDD410000 size: 1220520 crc: BB501898 date: 2021-04-20 14:01:16
 C:\WINDOWS\System32\IMM32.dll handle: 00007FFEDD0F0000 size: 185448 crc: 36F61BF6 date: 2021-03-13 23:13:12
 C:\WINDOWS\System32\USER32.dll handle: 00007FFEDD6E0000 size: 1702416 crc: 73C75F75 date: 2021-04-20 14:01:10
 C:\WINDOWS\System32\win32u.dll handle: 00007FFEDCA20000 size: 132760 crc: 167E1EAD date: 2021-04-20 14:01:10
 C:\WINDOWS\System32\GDI32.dll handle: 00007FFEDE5B0000 size: 161680 crc: 2A141BAA date: 2021-03-13 23:12:47
 C:\WINDOWS\SYSTEM32\OPENGL32.dll handle: 00007FFEA1C10000 size: 1064448 crc: A63281AE date: 2021-04-20 14:01:29
 C:\WINDOWS\System32\gdi32full.dll handle: 00007FFEDCA50000 size: 1075880 crc: 6C19849E date: 2021-04-20 14:01:18
 C:\WINDOWS\System32\msvcrt.dll handle: 00007FFEDD120000 size: 637360 crc: 072737D9 date: 2021-03-13 23:13:09
 C:\WINDOWS\System32\msvcp_win.dll handle: 00007FFEDCC60000 size: 634760 crc: E6732639 date: 2021-03-13 23:13:06
 C:\WINDOWS\System32\ADVAPI32.dll handle: 00007FFEDD220000 size: 689024 crc: 355A9B19 date: 2021-03-13 23:12:26
 C:\WINDOWS\SYSTEM32\WINMM.dll handle: 00007FFED4CD0000 size: 147200 crc: 18D40339 date: 2021-03-13 23:12:20
 C:\WINDOWS\System32\ucrtbase.dll handle: 00007FFEDCB60000 size: 1044888 crc: D3CA62A3 date: 2021-03-13 23:13:06
 C:\WINDOWS\System32\sechost.dll handle: 00007FFEDD050000 size: 625496 crc: E09B47D4 date: 2021-04-20 14:01:16
 C:\WINDOWS\System32\combase.dll handle: 00007FFEDE230000 size: 3506992 crc: C1B1E60F date: 2021-04-20 14:01:14
 C:\WINDOWS\System32\SHELL32.dll handle: 00007FFEDE670000 size: 7637008 crc: 57C77621 date: 2021-04-20 14:01:20
 C:\WINDOWS\System32\ole32.dll handle: 00007FFEDD5B0000 size: 1212232 crc: 0FD6B05F date: 2021-03-13 23:13:05
 C:\WINDOWS\SYSTEM32\GLU32.dll handle: 00007FFEB5B90000 size: 164352 crc: DA0CBD61 date: 2021-03-13 23:14:09
 C:\WINDOWS\SYSTEM32\USP10.dll handle: 00007FFED3090000 size: 79360 crc: 9A7F7CC2 date: 2021-03-13 23:13:12
 C:\Program Files (x86)\Steam\gameoverlayrenderer64.dll handle: 00007FFE9EF70000 size: 1809640 crc: 8A9EFDDF date: 2021-04-12 20:03:30
 C:\WINDOWS\System32\PSAPI.DLL handle: 00007FFEDD880000 size: 19144 crc: 6E06CEEB date: 2021-03-13 23:13:05
 C:\WINDOWS\SYSTEM32\windows.storage.dll handle: 00007FFEDA890000 size: 7968600 crc: A4E92974 date: 2021-04-20 14:01:10
 C:\WINDOWS\SYSTEM32\Wldp.dll handle: 00007FFEDC1A0000 size: 173016 crc: C5218D0B date: 2021-03-13 23:13:06
 C:\WINDOWS\System32\SHCORE.dll handle: 00007FFEDEF00000 size: 704008 crc: 0812F61E date: 2021-03-13 23:12:54
 C:\WINDOWS\System32\shlwapi.dll handle: 00007FFEDDFE0000 size: 342440 crc: 5693748E date: 2021-03-13 23:13:25
 C:\WINDOWS\system32\uxtheme.dll handle: 00007FFEDA130000 size: 627712 crc: A05B5F55 date: 2021-03-13 23:13:19
 C:\WINDOWS\System32\MSCTF.dll handle: 00007FFEDE040000 size: 1128008 crc: 3E23452A date: 2021-04-20 14:01:18
 C:\WINDOWS\System32\OLEAUT32.dll handle: 00007FFEDE160000 size: 831024 crc: 8304FB12 date: 2021-03-13 23:13:09
 C:\WINDOWS\SYSTEM32\kernel.appcore.dll handle: 00007FFEDA690000 size: 60464 crc: 7039ACC9 date: 2021-03-13 23:12:51
 C:\WINDOWS\System32\bcryptPrimitives.dll handle: 000001FF4C5F0000 size: 523200 crc: 1A4DFB8D date: 2021-03-13 23:13:10
 C:\WINDOWS\System32\clbcatq.dll handle: 00007FFEDEDC0000 size: 672976 crc: AD4CB4A3 date: 2021-03-13 23:13:05
 C:\WINDOWS\System32\DriverStore\FileRepository\c0365057.inf_amd64_a0f5f3f63c5dcefa\B364966\atig6pxx.dll handle: 00007FFEB3280000 size: 173904 crc: F2CCBB3A date: 2021-03-24 14:13:08
 C:\WINDOWS\System32\DriverStore\FileRepository\c0365057.inf_amd64_a0f5f3f63c5dcefa\B364966\atio6axx.dll handle: 00007FFE96300000 size: 47231288 crc: 61D23D35 date: 2021-03-24 14:13:09
 C:\WINDOWS\System32\SETUPAPI.dll handle: 00007FFEDD950000 size: 4650576 crc: F65AC9E1 date: 2021-03-13 23:13:22
 C:\WINDOWS\System32\cfgmgr32.dll handle: 00007FFEDC9D0000 size: 305272 crc: DE2280BE date: 2021-03-13 23:13:09
 C:\WINDOWS\System32\bcrypt.dll handle: 00007FFEDC840000 size: 146240 crc: 50F3C5E2 date: 2021-03-13 23:13:06
 C:\WINDOWS\SYSTEM32\VERSION.dll handle: 00007FFED4D00000 size: 31496 crc: 546E295F date: 2021-03-13 23:13:25
 C:\WINDOWS\SYSTEM32\dxva2.dll handle: 00007FFED0A90000 size: 133296 crc: 93B92C38 date: 2019-12-07 09:08:27
 C:\WINDOWS\SYSTEM32\dwmapi.dll handle: 00007FFEDA4B0000 size: 168408 crc: BE283206 date: 2021-03-13 23:13:05
 C:\WINDOWS\System32\DriverStore\FileRepository\c0365057.inf_amd64_a0f5f3f63c5dcefa\B364966\atig6txx.dll handle: 00007FFEB02F0000 size: 245072 crc: 8EE21983 date: 2021-03-24 14:13:08

---- gamelog start ----
---- gamelog end ----

Recent news messages:

*** End of OpenTTD Crash Report ***

Decoded stack trace:
[00] ???                  0x0000000000000000
[01] atio6axx             0x00007FFE96B9C6CA DrvSwapBuffers + 18202
[02] atio6axx             0x00007FFE96BA362E DrvSwapBuffers + 46718
[03] atio6axx             0x00007FFE96B9804B DrvSwapBuffers + 155
[04] atio6axx             0x00007FFE96B9396C getEGLInterface + 91052
[05] atio6axx             0x00007FFE96B96E79 DrvValidateVersion + 185
[06] OPENGL32             0x00007FFEA1C31185 wglSwapMultipleBuffers + 10821
[07] OPENGL32             0x00007FFEA1C315E4 wglSwapMultipleBuffers + 11940
[08] OPENGL32             0x00007FFEA1C33C7C wglCopyContext + 3628
[09] OPENGL32             0x00007FFEA1C4FC90 wglGetPixelFormat + 128
[10] OPENGL32             0x00007FFEA1C50CB1 wglDescribePixelFormat + 241
[11] OPENGL32             0x00007FFEA1C500B3 wglChoosePixelFormat + 99
[12] gdi32full            0x00007FFEDCAB2449 ChoosePixelFormat + 57
[13] openttd              0x00007FF687898459
[14] openttd              0x00007FF687898509
[15] openttd              0x00007FF687898649
[16] openttd              0x00007FF6878EA111
[17] openttd              0x00007FF6878E9F64
[18] openttd              0x00007FF6879D9115
[19] openttd              0x00007FF6878111C8
[20] openttd              0x00007FF687B77F02
[21] KERNEL32             0x00007FFEDD8A7034 BaseThreadInitThunk + 20
[22] ntdll                0x00007FFEDF042651 RtlUserThreadStart + 33

*** End of additional info ***

**Comment by glx22** [comment]
```
>	0000000000000000()	Inconnu
 	atio6axx.dll!00007ffe96b9c6ca()	Inconnu
 	atio6axx.dll!00007ffe96ba362e()	Inconnu
 	atio6axx.dll!00007ffe96b9804b()	Inconnu
 	atio6axx.dll!00007ffe96b9396c()	Inconnu
 	atio6axx.dll!00007ffe96b96e79()	Inconnu
 	opengl32.dll!pgldrvLoadAndAllocDriverInfo()	Inconnu
 	opengl32.dll!LoadAvailableDrivers()	Inconnu
 	opengl32.dll!__DescribePrimaryPixelFormat()	Inconnu
 	opengl32.dll!wglNumHardwareFormats()	Inconnu
 	opengl32.dll!wglDescribePixelFormat()	Inconnu
 	opengl32.dll!wglChoosePixelFormat()	Inconnu
 	gdi32full.dll!ChoosePixelFormat()	Inconnu
 	openttd.exe!SelectPixelFormat(HDC__ * dc, bool) Ligne 1239	C++
 	openttd.exe!LoadWGLExtensions() Ligne 1257	C++
 	openttd.exe!VideoDriver_Win32OpenGL::Start(const std::vector<std::string,std::allocator<std::string>> & param) Ligne 1296	C++
 	openttd.exe!DriverFactoryBase::SelectDriverImpl(const std::string & name, Driver::Type type) Ligne 122	C++
 	openttd.exe!DriverFactoryBase::SelectDriver(const std::string & name, Driver::Type type) Ligne 87	C++
 	openttd.exe!openttd_main(int argc, char * * argv) Ligne 769	C++
 	openttd.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Ligne 437	C++
 	[Code externe]	
```
The crash happens inside AMD video driver.

**Comment by giantkin** [comment]
[OpenTTDcrash.zip](https://github.com/OpenTTD/OpenTTD/files/6447786/OpenTTDcrash.zip)

dang you guys respond fast! :)  (whats the fix?)

    still no .cfg in the default folder.

**Comment by glx22** [comment]
You can add "-v win32" as extra start argument

**Comment by giantkin** [comment]
i add that, tried again failed.  Uninstalled, reinstalled, failed.   uninstalled, DELETED doc folder this time. (noticed that steam uninstall didnt remove the crash log)    this time (with the -v option) it worked.  thanks!
     (altho it autoupdated thru portableapps every now and then, on steam it should be ALOT faster!) thanks for that.  maybe someday it'll save on cloud too ;)  (assuming it doesnt now)
