### ISSUE TITLE
Online content not working cross-domain in Emscripten

### ISSUE THREAD

**Issue by embeddedt** [OpenTTD/OpenTTD#9233]
## Version of OpenTTD

Emscripten, 176d65b47240be9be0fece2c56019f66cf4b8692

## Expected result

I expected to successfully open the "Check Online Content" window and see the list from BaNaNaS.

## Actual result

![image](https://user-images.githubusercontent.com/42941056/117680545-431eff80-b17f-11eb-8c2c-5e458aac238c.png)

In Chrome DevTools, the message shown is that "WebSocket is closed before the connection is established."

## Steps to reproduce

1. Compile an Emscripten version of OpenTTD locally.
2. Serve it using any basic HTTP server on `127.0.0.1`.
3. Browse to `127.0.0.1`.
4. Click "Check Online Content".

I'm guessing that this is caused by the recent networking revamp. Interestingly, the compiled previews of recent PRs like #9043 seem to not have this issue.

I don't think this is caused by a lack of HTTPS, as [my fork with JGRPP applied](https://embeddedt.github.io/OpenTTD-modded/) uses HTTPS and has the same issue.

**Comment by TrueBrain** [comment]
Sad news: it does work fine for me. Tested with latest `master` (8f4a612a7c8ceb966d1cd538e9e53fd70336259d), on both FireFox and Chrome.

As you tried a commit from 6 days ago, and there have been many commits since then in `master`, would you mind trying the latest? Who knows we might have fixed it along the way.

**Comment by embeddedt** [comment]
I've retried with `master` and it does work properly there. I'll close this since it's not really a bug.

I noticed that with JGRPP, there has not been a full upstream merge since the networking changes were introduced (instead, all upstream commits seem to be cherry-picked now). The issue there will probably be resolved once a full merge is done.

**Comment by TrueBrain** [comment]
Yeah, we talked it over with JGR, and we suggested he doesn't merge the new networking stuff till we are done. It is pretty likely we break it a few more times before we got all the kinks worked out :D

Let me know if you find any other issues!
