### ISSUE TITLE
Vehicles do not pass stopped/broken down vehicles

### ISSUE THREAD

**Issue by unbeatable-101** [OpenTTD/OpenTTD#9236]
## Version of OpenTTD

OpenTTD Version 1.11.2 (1.11.2), macOS 11.3.1 (20E241)
## Expected result

As with slow vehicles, broken down ones get passed as well
## Actual result

The vehicle blocks traffic
## Steps to reproduce

Wait for a vehicle to break down with more vehicles behind it

https://user-images.githubusercontent.com/58151048/117745154-f87da180-b1d7-11eb-811a-220d1cdde4e0.mp4

**Comment by unbeatable-101** [comment]
![Screen Shot 2021-05-11 at 14 12 12](https://user-images.githubusercontent.com/58151048/117864673-10e6ce00-b263-11eb-9fed-af730bce39dd.png)

**Comment by TrueBrain** [comment]
This annoys me so much. The overtaking feels to random sometimes ... but a stopped vehicle .. why the game doesn't overtake it, I dunno .. feels like a bug to me :) But it is as old as the game itself ;)

**Comment by TrueBrain** [comment]
Duplicate of #10028 (strictly seen, yours is older, but #10028 contains a bit more details.)
