### ISSUE TITLE
Some tree brushes do not mark tiles as a rainforest

### ISSUE THREAD

**Issue by vituscze** [OpenTTD/OpenTTD#9241]
## Version of OpenTTD
1.11.2, Windows 10

## Expected result
Planting rainforest trees in the scenario editor should create rainforest tiles.

## Actual result
Only the "normal" brush creates rainforest tiles, "grove" and "forest" brushes do not.

**Comment by vituscze** [comment]
Left: normal brush, right: grove brush

![image](https://user-images.githubusercontent.com/4149104/118038010-dc603880-b36e-11eb-8629-825f290d7aed.png)

Minimap after demolishing the area:

![image](https://user-images.githubusercontent.com/4149104/118038063-ec781800-b36e-11eb-8208-476f3f39df47.png)

The same area after some time:

![image](https://user-images.githubusercontent.com/4149104/118038128-0580c900-b36f-11eb-9c2f-de189d78680a.png)

**Comment by 2TallTyler** [comment]
Did a bit of digging regarding this. The normal brush uses [CmdPlantTree()](https://github.com/OpenTTD/OpenTTD/blob/master/src/tree_cmd.cpp#L381) (which properly sets the rainforest tile), while the grove and forest brushes use [PlaceTreeGroupAroundTile()](https://github.com/OpenTTD/OpenTTD/blob/master/src/tree_cmd.cpp#L306) (which does not). I'm not sure why PlaceTreeGroupAroundTile() plants trees in a totally different way than simply calling CmdPlaceTree(), but I assume there's a good reason.
