### ISSUE TITLE
Tropical Lumber Mill doesn't work properly on large maps

### ISSUE THREAD

**Issue by vituscze** [OpenTTD/OpenTTD#9242]
## Version of OpenTTD
1.11.2, Windows 10

## Expected result
The production of a tropical lumber mill should be independent of the map size.

## Actual result
A 40x40 section of a rainforest on a 64x64 map can support up to about 80 lumber mills. The same area cannot support even one lumber mill on a 4096x4096 map (the lumber mill eventually runs out of trees to chop down).

In other words, the random tree growth does not scale with map size.

**Comment by PeterN** [comment]
Yes, tree growth is not scaled by map size at all, so the baseline should be the growth rate of a 256x256 map. 64x64 should be reduced.

**Comment by James103** [comment]
In other words, the "Expected result" should be that a 40x40 section of a rainforest on a 256x256 map should be able to support up to 4 or 5 lumber mills at full production and default tree growth rates, regardless of the map size.
