### ISSUE TITLE
Sound effects still play through speakers when I have bluetooth headphones on

### ISSUE THREAD

**Issue by unbeatable-101** [OpenTTD/OpenTTD#9253]
## Version of OpenTTD

OpenTTD Version 20210511-master-g1dfc148613 (20210511-master-g1dfc148613), macOS 11.3.1 (20E241)
## Expected result

The sound effects play through the headphones
## Actual result

The sound effect play through the speakers
## Steps to reproduce

1. Connect Bluetooth headphones (AirPods Pro in my case)
2. Open OpenTTD
3. Open a save

I'll have a video of it happening in a few minutes

**Comment by unbeatable-101** [comment]
Seems to be sporadic with when it happens, here is a bad recording with it happening as it started working properly again after.

https://user-images.githubusercontent.com/58151048/117994500-98d5e200-b30e-11eb-9474-14485028fdb8.mp4

It is clearest at 0:41

**Comment by PeterN** [comment]
I have no idea what we're listening for in the video, there's just background noise.

But there's no code in OpenTTD to switch audio device, so if it is happening then that is the OS's responsibility to get right.
