### ISSUE TITLE
Trains doesn't give income

### ISSUE THREAD

**Issue by JustAFriendV** [OpenTTD/OpenTTD#9262]
## Version of OpenTTD
1.11.2 - Windows 7 Max 64 bit

## Expected result
Recieve money for delivering stuff by train.

## Actual result
Even if it shows that money were made, i don't get them on my balance, also it doesn't show in yearly financial report...

## Steps to reproduce
???
I tried to update for new (1.11.1 -> 1.11.2) version and clear config files.
Still nothing

**Comment by embeddedt** [comment]
Please provide a savegame, or at the very least, a screenshot.

**Comment by JustAFriendV** [comment]
Hello,

i basically just start new game or load, doesn't matter.
Screenshot:
![image](https://user-images.githubusercontent.com/84155792/118191991-c07b9600-b445-11eb-9c8d-c170bc12c762.png)

**Comment by embeddedt** [comment]
What orders are you giving the train? There's not enough information.

**Comment by JustAFriendV** [comment]
the orders are: get fully loaded by coal -> move to power plant, eject all coal

**Comment by JustAFriendV** [comment]
Here is the save.
[test-1.11.2.sav.zip](https://github.com/OpenTTD/OpenTTD/files/6475271/test-1.11.2.sav.zip)

**Comment by embeddedt** [comment]
You're using a transfer order. I don't think that lets the industry pick it up; try using an unload order instead.

**Comment by JustAFriendV** [comment]
Thank you very much, now i get it. You are right, it was because of the orders. It was just leaving stuff at station.

**Comment by LordAro** [comment]
You may find this wiki page (and others) helpful https://wiki.openttd.org/en/Manual/Orders

Though the order window is definitely one of the more complicated things to get your head round, you wouldn't find many people defending its UI :)
