### ISSUE TITLE
Fast forward is bound to SHIFT not TAB in latest Fedora release

### ISSUE THREAD

**Issue by rel1c** [OpenTTD/OpenTTD#9286]
## Version of OpenTTD

1.11.2 using package openttd-1.11.2-1.fc34
Fedora Workstation 34 on Linux 5.11

## Expected result
Pressing TAB fast forwards the game, while SHIFT gives cost estimate of construction below mouse.

## Actual result
TAB does not seem to be bound to anything. Holding SHIFT still enables cost estimation, but the game fast forwards at the same time.

## Steps to reproduce

Run Fedora Workstation 34 and install openttd using dnf or Software application. Press SHIFT. I have confirmed this is the case on two different machines. The bug is not present when downgrading to openttd 1.10.3.

**Comment by LordAro** [comment]
Yup, this is an issue with the Fedora packages

https://src.fedoraproject.org/rpms/openttd/blob/rawhide/f/openttd.spec#_57 - doesn't set a BUILD_TYPE, which defaults to debug mode (which uses shift as FFWD)

Should file a bug there

**Comment by rel1c** [comment]
I made a bug report for the Fedora package. Fwiw I got things working via flatpack using the latest openttd. Thanks for the help.
