### ISSUE TITLE
Autoreplace protection doesn't apply to sub-groups

### ISSUE THREAD

**Issue by Ben79487** [OpenTTD/OpenTTD#9287]
## Version of OpenTTD
I am using Linux (Ubuntu 20.10) and am using OpenTTD 1.10.3.

## Expected result
Autoreplace protection (in the vehicles list) protects a group as well as all of its sub-groups.

## Actual result
While it protects the vehicles in the immediate group, it does *not* protect its sub-groups.

For example, if I have group B in group A, and I start autoreplacing and protect group A, vehicles in group B will still get autoreplaced.

## Steps to reproduce
1. Unzip and load the savegame attached.
2. Check the road vehicles window. Notice that I have set all MPS Regal Buses to be replaced by Foster Buses. Also look at the two groups, "Gufingfield" and "Betbourne". "Gufingfield" has been split into two groups, "Crosstown" and "East", with MPS Regal Buses within, while "Betbourne" only has a lone MPS Regal Bus. Both "Gufingfield" and "Betbourne" have been protected from autoreplacement.
3. Send all vehicles for maintenance to speed up autoreplace, and watch as the buses in the group "Gufingfield" get autoreplaced into Foster Buses, while the lone vehicle in "Betbourne" remains a MPS Regal Bus.

## Further thoughts
While this could be considered proper behavior, if it is, it would be unintuitive, as one would expect making changes to a group would also make changes to its descendants, like setting the color livery, which also sets the defaults for the sub-groups.

[Autoreplace cancel failure.zip](https://github.com/OpenTTD/OpenTTD/files/6525474/Autoreplace.cancel.failure.zip)

**Comment by glx22** [comment]
Propagation to sub-groups depends on Ctrl being pressed or not.

**Comment by glx22** [comment]
Same applies to wagon removal in nightlies. We should probably update tooltips.

**Comment by Ben79487** [comment]
Tooltips updated with PR 9292. Closing this issue, as it seems to be fixed. Thanks!
