### ISSUE TITLE
Music Audio is not normalized/leveled correctly

### ISSUE THREAD

**Issue by suit** [OpenTTD/OpenTTD#9295]
## Version of OpenTTD
1.11.2 Steam, Windows

## Expected result
Music should have a nice level according to game settings

## Actual result
Audio levels are not consistent, on some music sets the difference is very high (eardrum ripping high)

## Steps to reproduce
1) Install the the "Doom I Soundtrack" Version 1.2 from the library
2) reduce global music level to a low setting (for example 20 %) and start listening
3) change the track to 09 Hiding the Secrets or 26 Hiding the Secrets (those play at full volume, no matter the music level you have set)
4) go to content_downloads directory and search for midi-Files: open them in your prefered media player e1m9.mid and e3m9.mid play at the same volume as all the other files

**Comment by nielsmh** [comment]
Cannot reproduce.
Tested with `dmusic` driver playing to the Microsoft GM soft-synth using the default DLS instruments, as well as with the `win32` driver playing to two different hardware MIDI (GM) synths. The volume control is correct in all cases, with track 9, 26, and any other tested from the Doom music set.
Of course, 1.11.2 Windows version from Steam.

**Comment by James103** [comment]
Can you please try the following:
1. Locate the `openttd.cfg` file in your Documents folder and post it here if possible.
2. Run the executable located at `C:\Windows\System32\dxdiag.exe`, then wait for the progress bar to finish.
3. Click "Save All Information", then upload the resulting file here.

**Comment by suit** [comment]
I have tried it with the stock config and just downloaded the Doom I Soundtrack, still reproduceable.

[DxDiag.txt](https://github.com/OpenTTD/OpenTTD/files/6556148/DxDiag.txt)

**Comment by Limyx826** [comment]
#9565 
Might be related.

**Comment by Limyx826** [comment]
> Are you still able to reproduce this in 12.2 or the latest nightly? If not, this issue can be closed.
Not the OP but tried to reproduce his steps in 12.2 and able to confirm still an issue. 
Not sure it is because I used VMS, but when switch to track no 9 from other tracks, the channel 1 is full volume and the rest is normal. However if you adjust the global music volume then it will back to normal. 
I didn't test track 26 yet.

**Comment by James103** [comment]
Can reproduce in 4052feef1f. Also occurs with tracks 0 and 1 when using the Modern Motion music set.

**Comment by Limyx826** [comment]
openttd-20240130-master-g96651b5ada-windows-win64
From my listening, seem fixed right now. I can't how I check the volume of each channel again but from my listening seems good now.
