### ISSUE TITLE
Very large cities can build bridges of unlimited length

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#9316]
## Version
1.11.2 (from #8439 / 1.11.0)

## Expected result
The maximum length of a city bridge according to PR #8439 should be 4 + 1 for every 1000 inhabitants of the city.

## The current result
A city with a population of 50,000 can build a bridges with lenght of 56.
A city with a population of 100,000 can build a bridges with lenght of 106.
A city with a population of 200,000 can build a bridges with lenght of 206.
Cities with a population greater than approximately 252,000 can build bridges of unlimited length, even over 4,000
![Too long bridges](https://user-images.githubusercontent.com/67662046/120103920-3d02ba00-c152-11eb-9de0-d534e92b9754.png)

## Comment
Perhaps there should be a length limit for city bridges. 30 for bridges are usually already very long. A limit of 100 or more seems to be useful in very few cases. Most of these long bridges, often leading nowhere, look quite strange.

**Comment by James103** [comment]
What is the value of the "Max bridge length" setting in your game?

**Comment by LC-Zorg** [comment]
Always the maximum possible.
