### ISSUE TITLE
Bridges built over diagonal waterways can block them

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#9319]
## Version
1.11.0 (from always)

## The current result
By building a flat bridge over an diagonal waterway, it covers the water fields, so on a narrow canal it closes the waterway, prevents the movement of ships and simply looks bad.
![canal vs  bridges](https://user-images.githubusercontent.com/67662046/120104550-3aee2a80-c155-11eb-896d-73078d4ab202.png)

## Expected result
You can build a flat bridge over a narrow diagonal canal without blocking it.

## Possible solution
If the bridge begins or ends at a tiles of half water, the bridge will have no bridgehead or it will have a separate bridgehead type. In the latter case, the NewGRF bridges, if they did not have the appropriate graphics, the game would use its own.
![Unintrusive bridges](https://user-images.githubusercontent.com/67662046/120104554-3fb2de80-c155-11eb-95dc-f6d7f70c4833.png)

The solution to this problem may be part of the solution for #9317

**Comment by 2TallTyler** [comment]
Not a bug. This is just how bridges work in TTD/OpenTTD. 😉 

Of course, PRs for flat bridges would be lovely.

**Comment by nsfluca** [comment]
can i have the newgrf for the bridge?
