### ISSUE TITLE
Crash related to #9309 and DoCommandPInternal

### ISSUE THREAD

**Issue by J0anJosep** [OpenTTD/OpenTTD#9320]
## OpenTTD version
OpenTTD master 2021-05-30 (May 30 2021) on KDE Neon.

## Description
After the changes in #9309, the execution of DoCommandPInternal in:

order_backup.cpp:
DoCommandPInternal(ob->tile, 0, user, CMD_CLEAR_ORDER_BACKUP, nullptr, **nullptr**, true, false);

... can cause a crash.

## Steps to reproduce
Buy a bus in a depot window. Sell it and close the depot window. It causes a crash.

A possible solution is to change the nullptr in bold with "{}", but I am not sure about it.

**Comment by J0anJosep** [comment]
@rubidium42
I got this problem today. Maybe it is related to #9309 . Not sure about it.

**Comment by James103** [comment]
Did you mean to reproduce this bug in OpenTTD nightly 2021-**05**-30 (**May** 30 2021)?

**Comment by rubidium42** [comment]
For order backup it should indeed be a {}.
I'm not seeing why GetDoCommandCallback() must be non-`nullptr` as the `command_text` after it is the `std::string` that is passed as text parameter.

**Comment by J0anJosep** [comment]
> For order backup it should indeed be a {}.
> I'm not seeing why GetDoCommandCallback() must be non-`nullptr` as the `command_text` after it is the `std::string` that is passed as text parameter.

Yes. I missed it.

**Comment by J0anJosep** [comment]
> Did you mean to reproduce this bug in OpenTTD nightly 2021-**05**-30 (**May** 30 2021)?

Sorry. I built it myself today, using master, not nightly. Nightly for 2021-05-30 isn't built yet.
For the date format, ok. Next time I will use this one.
