### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by MaXenaeL** [OpenTTD/OpenTTD#9326]
## Version of OpenTTD

Long time version, macOS client. 

## Issue

Toy world. One headquarter's tile is empty in all HQ upgrades.
<img width="334" alt="Снимок экрана 2021-06-01 в 13 20 58" src="https://user-images.githubusercontent.com/85165050/120307933-3607b300-c2dc-11eb-945a-c54099640994.png">

**Comment by James103** [comment]
What is the actual OpenTTD version you were using? Also, I presume this is zBase or another 32bpp graphics set. Have you tried reproducing this with the default OpenGFX base set?

**Comment by MaXenaeL** [comment]
> What is the actual OpenTTD version you were using? Also, I presume this is zBase or another 32bpp graphics set. Have you tried reproducing this with the default OpenGFX base set?

It's fine with OpenGFX, but aBase, zBase fail

**Comment by PeterN** [comment]
Closing this as aBase/zBase are not OpenTTD. As far as I know both those projects are abandoned by their author(s) too.
