### ISSUE TITLE
No rule to make target 'generated/ottdres.rc' when Cross-compiling with CMake + MINGW

### ISSUE THREAD

**Issue by Roboron3042** [OpenTTD/OpenTTD#9329]
I'm unable to cross-compile OpenTTD (master) inside a MINGW environment using CMake due to the aforementioned error.

Things I did:
 * Follow the steps mentioned in: https://github.com/OpenTTD/OpenTTD/pull/8350
 * `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=~/toolchain-mingw32.cmake -DHOST_BINARY_DIR=native/ ..`
* `cmake --build . --target openttd`

In the toolchain file I've everything set up correctly, as I used it before to build other projects. Either there is something I didn't do previously (probably, since openttd cross-compilation with cmake is not well documented), or there is something missing in CMake files.

**Comment by James103** [comment]
What version of OpenTTD did you try to build?

**Comment by Roboron3042** [comment]
> What version of OpenTTD did you try to build?

The current master (I already said it).

**Comment by glx22** [comment]
Cross-compilation is tested with every nightly build, so it should work.
Please provide all the exact steps you followed, including the tool build steps.

Edit: hmm 'generated/ottdres.rc' doesn't depend on openttd native tools, it should be generated by version detection script during build

**Comment by glx22** [comment]
I think the issue is https://github.com/OpenTTD/OpenTTD/blob/48ecc481ee3b38702eb58f3cfef009d2ee5a9693/cmake/scripts/FindVersion.cmake#L141-L145
I'm not sure `WIN32` is set properly for `cmake` calls in `add_custom_target` like https://github.com/OpenTTD/OpenTTD/blob/48ecc481ee3b38702eb58f3cfef009d2ee5a9693/CMakeLists.txt#L73-L83
But I can't really test it myself.

**Comment by Roboron3042** [comment]
> I think the issue is
> 
> https://github.com/OpenTTD/OpenTTD/blob/48ecc481ee3b38702eb58f3cfef009d2ee5a9693/cmake/scripts/FindVersion.cmake#L141-L145

Yes it is. I removed the IF condition and compilation continued (but didn't succeed due to an unrelated error), so you are right.

**Comment by glx22** [comment]
Ok https://github.com/OpenTTD/OpenTTD/compare/master...glx22:fix_9329 should fix it, but I only tested native builds.

**Comment by Roboron3042** [comment]
I've applied the patch to my local copy and I can confirm it fixed the issue. I have now other issues preventing me from compiling, but I'll report them on another issue since they don't seem to be related.
