### ISSUE TITLE
Crash Report of AI

### ISSUE THREAD

**Issue by Rsmid** [OpenTTD/OpenTTD#9357]
## Version of OpenTTD

Nightly 20210611

![obrazek](https://user-images.githubusercontent.com/46579823/121786096-1155ea00-cbbe-11eb-92da-abea6014bab6.png)

**Comment by TrueBrain** [comment]
All AIs are created by our community, and this one is no exception. This means we cannot help you any further with this AI crash; we only deal with crashes of the game itself.

Please report this problem to the author of DictatorAI, and hopefully they can help you out.

Tnx!
