### ISSUE TITLE
Bug Report - tar loader ignores empty files. An AI that requires such file fails to start

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#9358]
## Version of OpenTTD

OpenTTD 1.11.2 and Windows 10
## Expected result

.tar loader shouldn't ignore empty files.
## Actual result

.tar loader ignores an empty file which is required file for the AI to start without erroring out.
## Steps to reproduce

The AI named Mungo, version 5 has an empty file, but it's required for the AI to start.
See conversation https://webster.openttdcoop.org/index.php?channel=openttd&date=1623369600#1623423363

**Comment by glx22** [comment]
Based on fileio.cpp history I think https://github.com/OpenTTD/OpenTTD/blob/7d791800408b6fc41f716f116e88135f02e18270/src/fileio.cpp#L545 can be removed. This check was used to detect folders or special stuff before we actually check entry type.
