### ISSUE TITLE
Include copyright notice

### ISSUE THREAD

**Issue by panosalevropoulos** [OpenTTD/OpenTTD#9384]
In [COPYING](https://github.com/OpenTTD/OpenTTD/blob/master/COPYING.md), it is good practice to include a copyright notice as per the [GPL guide](https://www.gnu.org/licenses/gpl-howto.en.html) for proper licensing.

Thanks for this great game.

**Comment by rubidium42** [comment]
The third line (first line after the title) contains a copyright notice (or line 7-9 of the raw document), or am I mistaken?

**Comment by TrueBrain** [comment]
As mentioned on the GPL guide as linked, the `copyright notice` is not about the `COPYING` file, but about the header in each source file. To quote:

`This involves adding two elements to each source file of your program: a copyright notice (..)`

The following `The copyright notice` chapter is about this part, not about `COPYING`. The `The license files` chapter is about `COPYING`. This file is copyrighted, but to GNU, not to us. After all, we didn't write it ;)

I am not sure if @panosalevropoulos has any source that disagrees with this conclusion, but this how I read that guide. Additionally, to me it would also be weird to add a copyright notice to a file that we didn't write. But IANAL, so who knows :)

Going to close this ticket for now; if you have any additional information, please do let us know! Tnx!

**Comment by panosalevropoulos** [comment]
@TrueBrain I agree that my original post was incorrect. The copyright notice should not be included in the COPYING file. But the issue remains. At minimum there should be a copyright notice in the README or CREDITS file. Optimally, there would be a copyright notice in every code file header.

Currently, there is no copyright notice to be found on the project's page.
