### ISSUE TITLE
Passenger subsidies don't check if houses actually accept Passengers

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#9385]
## Version of OpenTTD
1.11.2

## Expected result
If my house set doesn't accept Passengers, the game will not offer subsidies to deliver Passengers from one town to another.

## Actual result
I'm developing an experimental industry NewGRF where passengers ("Workers") are delivered to industries for production, and are not accepted by my NewGRF houses. The game offers subsidies for bringing Workers from one town to another, even though houses in that town do not accept Workers.

Note that I am using both the original cargo ID and label PASS for Workers, for compatibility with other NewGRFs including old house sets and vehicles with cargo subtype refits for liveries.

## Steps to reproduce
1. Load the two NewGRFs in the .zip file below - Improved Town Layouts 1.4.0 beta 3 and Industries of the Caribbean 0.0.0, or just load the save (all other NewGRFs are on Bananas). 
2. Ensure that CargoDist is in Manual mode for Passengers.
3. Wait for subsidies to be offered.

[Subsidy_Demo.zip](https://github.com/OpenTTD/OpenTTD/files/6680626/Subsidy_Demo.zip)

**Comment by James103** [comment]
Does the same apply for Mail as well? In other words, if no town will ever accept Mail, but some towns do produce Mail, then there should be no subsidies between towns for Mail.

**Comment by 2TallTyler** [comment]
I suspect so, but have not tested this.

**Comment by 2TallTyler** [comment]
I'm no longer doing (these specific) stupid things with NewGRFs, and don't expect anyone else to encounter this issue. Fixing it would probably be TMWFTLB.
