### ISSUE TITLE
AIVehicle.GetBuildWithRefitCapacity returns -1 when at the max num of vehicles

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#9392]
## Version of OpenTTD

20210620-master-g6a05839d8d
## Expected result

When an AI is at the max num of vehicles, AIVehicle.GetBuildWithRefitCapacity returns the actual capacity
## Actual result

When an AI is at the max num of vehicles, AIVehicle.GetBuildWithRefitCapacity returns -1
## Steps to reproduce

My AI builds aircraft and reaches the limit. It still continues its aircraft management checking if there are newer engine models available from time to time. I noticed a weird behaviour when Bakewell Luckett LB-9 became available. Normally, the AI would start replacing the old model of choice, the Coleman Count to this new model.
It failed to do so because it was simulating the new income using a capacity of -1 for passengers when using AIVehicle.GetBuildWithRefitCapacity function.

After investigating openttd code, I found that the issue is due to GetFreeUnitNumber not allowing a new vehicle to be temporarily purchased for requesting the refited capacity amount.

https://github.com/OpenTTD/OpenTTD/blob/6a05839d8d26eaaaae5b5df2948b77f5f0993499/src/vehicle_cmd.cpp#L127

**Comment by glx22** [comment]
https://github.com/OpenTTD/OpenTTD/compare/master...glx22:refit should partially fix the issue (at least when refitting to non default cargo)
