### ISSUE TITLE
[Crash]: Founding a town

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#9402]
### Version of OpenTTD

20210626-master-gda7621cc55, Windows 10

### Steps to reproduce

1. Start new game
2. Open 'Found town' window
3. Place it.
Crash!

### Upload crash files

I don't have them atm.

**Comment by SamuXarick** [comment]
>	[Inline Frame] openttd.exe!std::_Narrow_char_traits<char,int>::length(const char * const) Line 409	C++
 	[Inline Frame] openttd.exe!std::string::assign(const char * const) Line 3264	C++
 	[Inline Frame] openttd.exe!std::string::{ctor}(const char * const) Line 2521	C++
 	openttd.exe!FoundTownWindow::ExecuteFoundTownCommand(unsigned int tile, bool random, unsigned int errstr, void(*)(const CommandCost &, unsigned int, unsigned int, unsigned int, unsigned int) cc) Line 1165	C++
 	openttd.exe!FoundTownWindow::OnPlaceObject(Point pt, unsigned int tile) Line 1220	C++
 	openttd.exe!HandleViewportClicked(const Viewport * vp, int x, int y) Line 2359	C++
 	openttd.exe!MouseLoop(MouseClick click, int mousewheel) Line 2846	C++
 	openttd.exe!HandleMouseEvents() Line 2977	C++
 	openttd.exe!WndProcGdi(HWND__ * hwnd, unsigned int msg, unsigned __int64 wParam, __int64 lParam) Line 432	C++
 	[External Code]	
 	openttd.exe!VideoDriver_Win32Base::PollEvent() Line 857	C++
 	openttd.exe!VideoDriver::Tick() Line 133	C++
 	openttd.exe!VideoDriver_Win32Base::MainLoop() Line 868	C++
 	openttd.exe!openttd_main(int argc, char * * argv) Line 802	C++
 	openttd.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 413	C++
 	[External Code]

**Comment by James103** [comment]
> 20210626-master-gda7621cc55, Windows 10

I don't have access to that nightly via cdn.openttd.org because of #9386. Where did you get that nightly from (more specifically commit da7621cc55)?

**Comment by glx22** [comment]
Manual build is the only way.
