### ISSUE TITLE
[Bug]: Duplicate client

### ISSUE THREAD

**Issue by scorpio1441** [OpenTTD/OpenTTD#9439]
### Version of OpenTTD

1.11.2, FreeBSD

### Expected result

Duplicate clients appear in GUI, but not in console.

![image](https://user-images.githubusercontent.com/1091494/125247598-1c855e00-e2c1-11eb-8af2-ebdae6e976fb.png)

![image](https://user-images.githubusercontent.com/1091494/125247540-0e374200-e2c1-11eb-8ac8-3fb4b6eaa0db.png)

### Actual result

Single client

### Steps to reproduce

Here is a log file for `onion` client:
```
‎*** onion has joined the game (Client #950)
Client #950 is dropped because the client did not respond for more than 501 ticks                                                                                  dbg: [net] 'onion' made an error and has been disconnected. Reason: 'general timeout'                                                                              
‎*** onion has left the game (general timeout)‎*** onion has joined the game (Client #982)
‎*** onion has joined the game (Client #984)
dbg: [net] 'onion' made an error and has been disconnected. Reason: 'general timeout'
‎*** onion has left the game (general timeout)
‎*** onion has joined the game (Client #1026)
‎*** onion has left the game (general timeout)
‎*** onion has joined the game (Client #1034)

```

**Comment by LordAro** [comment]
Thanks for the report, this has already been found and fixed independently in #9238
