### ISSUE TITLE
[Bug]: Inflation breaks negative cargo payments

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#9440]
### Version of OpenTTD

OpenTTD 1.11.2, Windows 10

### Expected result

My NewGRF industry set, Industries of the Caribbean, uses negative cargo rates set in the NML properties (not the profit callback, [where a known issue exists](https://github.com/OpenTTD/nml/pull/212)).

When Inflation is disabled, this works as intended. A cargo delivery like that in the savegame attached below costs the company about -£50.

### Actual result

When Inflation is enabled, that -£50 cargo delivery instead gives £205 million.

### Steps to reproduce

A user provided this savegame illustrating the issue.
[IOTC_inflation_bug.zip](https://github.com/OpenTTD/OpenTTD/files/6809096/IOTC_inflation_bug.zip)

When a new map is started with Inflation disabled and the same set of NewGRFs, the profit works as intended.

**Comment by James103** [comment]
Can you please check the cargo payment rates graph as well pre- and post-inflation and post your findings?

**Comment by 2TallTyler** [comment]
As intended, without inflation:
![no_inflation](https://user-images.githubusercontent.com/55058389/125464085-c5391778-1952-45e7-8bec-afb30a1e5b30.png)

With inflation:
![inflation](https://user-images.githubusercontent.com/55058389/125464110-fa17fad8-d049-449f-b0d5-1b1892aa2135.PNG)

**Comment by James103** [comment]
I can tell that the erratic cargo payment rate is highly dependent on the least significant bits (i.e. fractional part) of the inflation income factor. If the inflation income factor is an integer, normal behavior is exhibited, but if the inflation income factor is not an integer, that very easily leads to the erratic behavior shown. For example, there is an overflow in the cargo payment rates for imported cargoes that is triggered when the inflation income factor is greater than 0.5 (modulo 1.0):

For comparison, cargo payment rates where the inflation income factor is set to exactly 1.00000:
![image](https://user-images.githubusercontent.com/37945304/125467836-12c549ec-515b-4a3c-baca-b90b5525edf2.png)

Cargo payment rates where the inflation income factor is set to exactly 1.00003:
![image](https://user-images.githubusercontent.com/37945304/125468001-c7131387-42a9-456c-a6d4-9047a02ab9d2.png)

Cargo payment rates where the inflation income factor is set to exactly 1.50000:
![image](https://user-images.githubusercontent.com/37945304/125467018-fa950b4e-888e-4a15-9051-e357df98b28d.png)

Cargo payment rates where the inflation income factor is set to exactly 1.50003:
![image](https://user-images.githubusercontent.com/37945304/125467117-ec048fcf-2cfb-4427-af01-988f4ca47b76.png)

Cargo payment rates where the inflation income factor is set to exactly 1.99999:
![image](https://user-images.githubusercontent.com/37945304/125468102-30153e66-37bc-49ec-a053-11752f71cfe5.png)

Cargo payment rates where the inflation income factor is set to exactly 2.00000 is the same as with 1.00000, just the magnitudes are doubled.

...

Cargo payment rates where the inflation income factor is set to exactly 10,000.501:
![image](https://user-images.githubusercontent.com/37945304/125467469-1709f192-6f12-4b44-a2b6-1d86ae1f7900.png)
(notice that the absolute value of the highest / lowest paying cargo is within 0.1% of the other extreme-case graphs)
