### ISSUE TITLE
[Crash]: Game crashes on start up.

### ISSUE THREAD

**Issue by monotomt** [OpenTTD/OpenTTD#9463]
### Version of OpenTTD

1.11.2 Windows 10

### Steps to reproduce

Game crashes on start up. I've tried all the available betas (1.11.0-1.11.2 and nightly)

### Upload crash files

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/6940343/crash.zip)

**Comment by monotomt** [comment]
I've also tried to turn off hardware acceleretion.

**Comment by glx22** [comment]
Does it start when using "-s null" or "-s win32"  in launch options (properties) ?

**Comment by LordAro** [comment]
To give more details - it looks the crash is happening inside components from Nahimic GameOverlay - that's not something we can do anything about. Try disabling it/updating it/yeeting it out of a window and see if that helps?

**Comment by monotomt** [comment]
> Does it start when using "-s null" or "-s win32" in launch options (properties) ?

-s null did the trick! Thanks!

**Comment by glx22** [comment]
You won't have any sound effect with "-s null", so also try "-s win32" (if it works you'll have sound)

**Comment by monotomt** [comment]
> You won't have any sound effect with "-s null", so also try "-s win32" (if it works you'll have sound)

Worked! Thanks!

**Comment by glx22** [comment]
BTW after some search on google, it seems the culprit would be sonic studio 3 or nahimic service. It seems many games are affected by this.

**Comment by LordAro** [comment]
Closing issue, as workaround has been found and it's not our bug anyway.

**Comment by glx22** [comment]
Hello @monotomt, would be nice if you could try nightly branch on steam (20210911 version or more recent), with clean launch options.
We implemented a possible automatic work around, but can't test it as we are not affected by the issue.

**Comment by monotomt** [comment]
Hey! I've unfortunately uninstalled sonic studio 3 since it interferd with other games and programs.
