### ISSUE TITLE
[Crash]: On startup

### ISSUE THREAD

**Issue by QuazyHG** [OpenTTD/OpenTTD#9470]
### Version of OpenTTD

1.11.2 - Windows 10

### Steps to reproduce

open the game, and game crashes. cannot start game.

### Upload crash files

[OpenTTD.zip](https://github.com/OpenTTD/OpenTTD/files/6975944/OpenTTD.zip)

**Comment by LordAro** [comment]
Duplicate of #9463 

An issue with the Nahimic GameOverlay is causing crashes in the audio driver (nothing we can do about this). Either disable/uninstall this overlay, or run with `-s win32` options.
