### ISSUE TITLE
[Bug]: music distorted on Raspberry Pi

### ISSUE THREAD

**Issue by AustrianLinuxMemer** [OpenTTD/OpenTTD#9483]
### Version of OpenTTD

1.10.3 Ubuntu Raspberry-Pi Exclusive

### Expected result

I expected that the music is starting normally when i open the game

### Actual result

the music gets distorted if i open the game
the higher the resolution, the more distorted the music is

### Steps to reproduce

1. Just open OpenTTD
2. The error comes up instantly.

**Comment by TrueBrain** [comment]
We would have to triage, but can you check how your CPU is doing while playing? It sounds like something is not keeping up, especially as it is influenced by resolution.

**Comment by AustrianLinuxMemer** [comment]
the quad-core cpu (clocked at 2000 Mhz) is on half capacity on all four cores

**Comment by AustrianLinuxMemer** [comment]
i want to say that it is a Raspberry Pi 4

**Comment by TrueBrain** [comment]
So two cores are fully in use, basically. OpenTTD is for most part a single-threaded game, so if I am reading this right, I think it simply cannot keep up to send enough music information to the driver. Not sure if that is fixable for us ..

You could try updating to 1.11 (or better: 12.0-beta1) and see if the OpenGL driver wants to kick in. That should help for the CPU usage.

**Comment by AustrianLinuxMemer** [comment]
i've set the gpu-clock to 700 Mhz and the graphics-memory to 512 MB

**Comment by AustrianLinuxMemer** [comment]
it could also be timidity++ that is not keeping up. sound effects are not affected at all.
They run fine even the game is on a higher resolution than 640x480

**Comment by glx22** [comment]
OpenTTD doesn't use gpu acceleration at all in pre 1.11 versions. You really should try a more recent one.

**Comment by AustrianLinuxMemer** [comment]
okay

**Comment by AustrianLinuxMemer** [comment]
i tried the standalone timidity++ with the .midi files and it run perfectly

**Comment by AustrianLinuxMemer** [comment]
who makes the binary packages for the various linux distros?

**Comment by TrueBrain** [comment]
I know it has been a while, but we never heard back from you if trying 12.0 address this issue? By now it might be better to test a recent nightly, as many changes have been made that would improve a situation like yours.

Mind testing https://www.openttd.org/downloads/openttd-nightlies/latest and see if that resolves the issue? Cheers!
