### ISSUE TITLE
OpenGFX update required before full 12.0 release - "Base graphics set missing 5 tiles"

### ISSUE THREAD

**Issue by dgealow** [OpenTTD/OpenTTD#9486]
### Version of OpenTTD

12.0 beta-1, macOS 11.4

### Expected result

No error messages when using default OpenGFX base graphics set

### Actual result

Main menu has the message:
"The currently selected base graphics set is missing 5 sprites. Please check for updates for the baseset."

### Steps to reproduce

Open the beta 12.0 game with the default OpenGFX base graphics set selected.

**Comment by LordAro** [comment]
Not really a bug, more of a missing OpenGFX release

However, I'll leave this open and milestone it for 12.0 so it doesn't get forgotten

**Comment by andythenorth** [comment]
See https://github.com/OpenTTD/OpenGFX/pull/69

**Comment by glx22** [comment]
OpenGFX is now updated (but not released yet).
