### ISSUE TITLE
[Bug]: Refreshing a full server gives an error

### ISSUE THREAD

**Issue by ldpl** [OpenTTD/OpenTTD#9490]
### Version of OpenTTD

12.0-beta1

### Expected result

Update server info. I'd like to know if some clients happen to disconnect ;)

### Actual result

Shows "server is full" error message and closes network lobby.

### Steps to reproduce

0. Open multiplayer lobby
1. Find a full server (maxed out on clients) and click on it
2. Click "Refresh server"

**Comment by TrueBrain** [comment]
During `accept()` it is validated if there is still room on the server. This obviously is the wrong place, and it should be done a bit later, always allowing for a `refresh` to happen.
