### ISSUE TITLE
[Bug]: "Use relay?" prompt can timeout with a weird error

### ISSUE THREAD

**Issue by ldpl** [OpenTTD/OpenTTD#9491]
### Version of OpenTTD

12.0-beta1

### Expected result

Have all the time I need to read the message and make a decision. Or, at least, get a meaningful error.

### Actual result

After some time (which I bet depends on server settings) client gets thrown out to the main menu with "The server didn't answer the request" message.

### Steps to reproduce

1. Connect to a server that requires TURN to be used.
2. Wait some time when "Use relay?" dialog pops up.

**Comment by TrueBrain** [comment]
No, has nothing to do with any server-setting. There is a maximum amount of time the Game Coordinator allows for a connection to be established, after which he says: both sides, give up.

Some triage:

The GC doesn't know the client had a popup asking for permission to connect to the TURN server. And the "give up" results in the error you are getting.
Silly enough, the client callback handling the "give up" also doesn't know he was waiting for permission of the user.
