### ISSUE TITLE
[Bug]: "Use relay?" prompt pops out for no apparent reason.

### ISSUE THREAD

**Issue by ldpl** [OpenTTD/OpenTTD#9492]
### Version of OpenTTD

12.0-beta1

### Expected result

Don't show the prompt until I'm actually trying to connect to some server.

### Actual result

Prompt pops up few seconds after opening the multiplayer window. And a few seconds later it disappears without any message or error. 
![Screenshot from 2021-08-17 21-23-01](https://user-images.githubusercontent.com/413570/129781702-1da6ac0e-2279-4e9d-981a-f27fcd65fe95.png)

If I click "yes": 
![Screenshot from 2021-08-17 21-30-43](https://user-images.githubusercontent.com/413570/129781327-66b62952-c3ac-41d7-afd0-ff5299b5eb17.png)

If I clilck "no":
![Screenshot from 2021-08-17 21-31-40](https://user-images.githubusercontent.com/413570/129781348-a05b672c-dbac-4506-a732-f9d50d6c6d30.png)

### Steps to reproduce

0. Start the game
1. Click "multiplayer"
2. Wait a few seconds.

Only happens on the first time mp window is opened (after starting the game).

Now, I'm not 100% sure that's what causing it but it seems to be trying to refresh the server that I joined last time.
So likely prior steps to repro this are:
01. Join the server with TURN
02. Exit the game

**Comment by James103** [comment]
Can the "Use relay?" prompt raised due to this issue time out, thereby reproducing #9491? If so, what happens when the prompt times out?

**Comment by ldpl** [comment]
Yes, it can timeout but nothing happens (same as clicking no).

**Comment by TrueBrain** [comment]
When the Multiplayer window is opened, all the servers in the list (including the last-server joined) are being refreshed. This could be by IP or by invite-code, but it is like you click on all of them and hit the refresh. This creates a TCP connection to each of them. If any needs a relayed connection, it will ask you for this.

Possibly the best way to fix this, is to add to the TURN message to which server it tried to connect. As that would mean users connect the dots.

As a side note:
The "Expected result" here is unreachable; as that would be similar to saying that the "Refresh" button shouldn't show this message. But as it is fetching live data, it needs to connect to the server. And if that needs a relay to work, it has to show this message.

**Comment by ldpl** [comment]
Well, it doesn't popup big red questions for connecting to coordinator.openttd.org which is also a relay for server info of sorts. Neither it does for stun.openttd.org. So why should it for turn.openttd.org? When actually connecting to the server it's useful to know that connection is relayed but just for getting few bytes of server info it seems pointless.
