### ISSUE TITLE
[Bug]: set signals from another railroad system

### ISSUE THREAD

**Issue by HelmiMUC** [OpenTTD/OpenTTD#9509]
### Version of OpenTTD

1.12.0-beta2

### Expected result

To set signals only for the selected railroad track system.

For example:
to set signals for Maglev railroad system on Maglev railroad tracks.

### Actual result

At the moment it is possible to set signals from each system to any railroad tracks.
It doesn´t depend on the railroad system.

### Steps to reproduce

For expample:
1. set tracks from monorail railroad (or other railroad system)
2. activate the Maglev constraction window (or other railroad system but not the same of `#1`)
3. activate the signal build button
4. set signal on the track

**Comment by TrueBrain** [comment]
Just thinking out loud: is this really a bug, or a feature? (honest question, to be clear)

**Comment by HelmiMUC** [comment]
It also the same with "waypoints".

So it seems, only constructions which contains a track have to be from the same railroad system (e. g. bridges, depot,...).
But constructions which will be added on the tracks (signals, waypoints) can be added from another railroad system.

**Comment by embeddedt** [comment]
I'd rather consider this a feature. It would be annoying to have to switch between types just to add/remove a signal.

**Comment by TrueBrain** [comment]
After some toying with this, and for the fact this has been this way for 17 years now, I think I am going to rule this "working as intended".

I can understand it might feel strange that you can put "maglev signals" on monorail, but making signals bind to their track-type, makes for very frustrating gameplay too. And I do not think there is anything inherently wrong by allowing it, other than surprising a few people from time to time.

So in the larger picture, I think it is better to allow this, and consider it a feature, than anything else. Sorry, but tnx for the report, it is much appreciated!
