### ISSUE TITLE
[Bug]: Wrong unreservation behaviour when reversing a train inside a depot when an incoming reservation exists

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#9520]
### Version of OpenTTD

master (aa83488f)

### Expected result

Pressing the reverse button when a train is waiting inside a depot does not cause any PBS reservation issues.
Any incoming reservations should be unaffected.

### Actual result

When there is an incoming reservation into a depot, pressing the reverse button on a train inside the depot removes the entire incoming reservation, including from underneath the incoming train.
The depot tile is then left reserved. This can result in the depot being permanently blocked without user intervention if the incoming train does not then continue into the depot.

### Steps to reproduce

1. Load: [JGR Rail Testing Ltd., 1980-02-25.sav.zip](https://github.com/OpenTTD/OpenTTD/files/7071475/JGR.Rail.Testing.Ltd.1980-02-25.sav.zip).
2. Press reverse button on Train 2.
3. Note that Train 1's reservation has been removed, and the depot tile has been left reserved.

**Comment by TrueBrain** [comment]
Beautiful savegame to test this bug with. Tnx a lot for that @JGRennison , this is much appreciated!
