### ISSUE TITLE
[Bug]: "ship is lost" is only reported via news

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/OpenTTD#9523]
### Version of OpenTTD

12.0-beta2

### Expected result

See somewhere on the vehicle or wherever, that the ship is lost.

### Actual result

If a ship cannot reach its destination, it shows news about that once. This is true for all vehicles, but for ships even more annoying as they tend to drift towards the destination.

If you think you fixed the route, it doesn't update you with "route found!", so you are in the false sense you fixed the issue, and it never shows "ship is lost" again. This makes using ships a very frustrating experience.

### Steps to reproduce

1. Build a dock upstream
2. Don't build a lock
3. Build a depot downstream
4. Build a ship
5. Make it go to the dock
6. Observe the news message about it being lost
7. Try to find back whether it is still lost after that

What makes this extra annoying: 
8. Build a lock, but the ship still cannot reach the dock
9. You will NOT receive any notification it still cannot reach the destination

**Comment by TrueBrain** [comment]
The biggest "well that is a shame" part, is that there is a flag to indicate the ship is lost in the vehicle flags (`VF_PATHFINDER_LOST`). It is just not used anywhere in the GUI.

It seems this is a pretty easy thing to address, we just need to find a clean way to present it to the user. Maybe in the status bar of the vehicle? `Couldn't find a route to ...` instead of `Heading to ...`?

**Comment by James103** [comment]
There could also be an alert symbol `⚠` displayed in front of the vehicle's consist in the GUI. For example, if the `VF_PATHFINDER_LOST` flag is set, the alert symbol is shown, in order to further inform players in the vehicle listings.
