### ISSUE TITLE
[Crash]: cannot play multiplayer running two instances on same computer

### ISSUE THREAD

**Issue by pnpBrumi** [OpenTTD/OpenTTD#9530]
### Version of OpenTTD

12.0-beta2, Windows 10 (21H1)

### Steps to reproduce

1. Start OpenTTD, create a new multiplayer server with local visibility.
2. Start another instance of OpenTTD, and click Search LAN.
3. The game crashes.

_Note:_ When creating the server for the first time, I got a Windows notification asking to allow OpenTTD to receive incoming traffic, and I did **not** give the permission. This might complicate things, I may try this on another computer where I do give OpenTTD the permission to access the network.

### Upload crash files

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/7090557/crash.zip)

**Comment by James103** [comment]
```
Crash reason:
  Message: Assertion failed at line 146 of D:\a\OpenTTD\OpenTTD\src\network\network_client.cpp: ClientNetworkGameSocketHandler::my_client == nullptr
```
Same issue as #9501?

**Comment by pnpBrumi** [comment]
Quite possible. The crash does not occur in the latest nightly (20210831) with the same reproduction steps.
