### ISSUE TITLE
[Crash]: Switching between monitors in fullscreen

### ISSUE THREAD

**Issue by simply-peachy** [OpenTTD/OpenTTD#9531]
### Version of OpenTTD

OpenTTD 20210831-master-g2c05412d72 Kubuntu 20.04.2

### Steps to reproduce

Also affects v1.11.2. Using a nightly in its own directory via `./openttd -c openttd.conf -d` with a blank config file; no settings or NewGRFs are loaded. The following steps may seem odd until one considers playing on a laptop, then plugging in an external screen and switching to the external screen.

1. On a system with multiple monitors of differing resolutions, have OpenTTD open in fullscreen mode, with the other monitor unplugged/disabled. 
2. Plug in the other monitor, switch to it (primary/exclusive).
3. Observe OpenTTD window in fullscreen mode, but still set to the previous monitor's resolution.
4. Open Game Options, uncheck fullscreen mode.
5. Crashes with:

```
X Error of failed request:  BadRRCrtc (invalid Crtc parameter)
Major opcode of failed request:  140 (RANDR)
Minor opcode of failed request:  20 (RRGetCrtcInfo)
Crtc id in failed request: 0x0
Serial number of failed request:  2901
Current serial number in output stream:  2901
```

None of crash.log, crash.dmp or crash.sav are being generated, so I had to add a dummy to permit filing the issue.

### Upload crash files

[crash.log](https://github.com/OpenTTD/OpenTTD/files/7094992/crash.log)

**Comment by LordAro** [comment]
This looks like a crash/failure within SDL2 or X11, rather than within OTTD. As such, it's quite likely there's nothing we can do about it. Happy to be proved wrong, however. Perhaps running via `gdb` could reveal some more information?

**Comment by TrueBrain** [comment]
As talked about on IRC, this really looks like an SDL issue. Do you mind if we close this ticket for now? There is current little action we can take :(

Feel free to reopen it if you either have more information (like a backtrace will confirm for us if we can do anything about this) or if you feel like we can prevent the crash. Don't take this "closing" as "we don't care", but really as a "this doesn't seem actionable for us" :)
