### ISSUE TITLE
 No coal

### ISSUE THREAD

**Issue by Budgie2021** [OpenTTD/OpenTTD#9537]
### Version of OpenTTD

1.11.2.win 10

### Expected result

new game generated expect coal mines

### Actual result

no coal mines on map
no coal mines can be built as
[coalfail1.zip](https://github.com/OpenTTD/OpenTTD/files/7109077/coalfail1.zip)
[coalfail2.zip](https://github.com/OpenTTD/OpenTTD/files/7109078/coalfail2.zip)
 not on list

### Steps to reproduce

 play the game

**Comment by Budgie2021** [comment]
Disregard - my bad - issue was ECS vector basic started before town vector

 NOTE NO error message for this error on  GRF settings screen in 1.11.2 but error warnings  do show up in 1.10.3
 (not tested nor verified)

**Comment by glx22** [comment]
Indeed I can see 2 `(undefined string)` cargo type, which is usually the result of a conflict (load order or whatever) with newgrfs.
NewGRF window shows the error for me:
![image](https://user-images.githubusercontent.com/2952192/132080311-91366a6a-64eb-48cb-a4b5-55b07c048577.png)
BTW there is coal being produced by `Tar Kiln`

~~(I didn't check in 1.11.2)~~ Checked 1.11.2, error is visible in the window.
![image](https://user-images.githubusercontent.com/2952192/132080542-5ed86727-c4fc-42c6-9916-e9ef89f2b552.png)
