### ISSUE TITLE
[Crash]: Game crashed on switching windows with Alt-Tab

### ISSUE THREAD

**Issue by randstring** [OpenTTD/OpenTTD#9561]
### Version of OpenTTD

1.11.2, Windows 10 Home 21H1

### Steps to reproduce

1. OpenTTD was running in background (with the game in pause), while I was doing other stuff with my computer.
2. I decided to continue playing and switched to it using Alt-Tab
3. The screen froze for a second or two with partial image in the upper part of the screen
4. The game crashed and I got a dialog message, suggesting to send a crash report.

OpenTTD is quite stable for me and this is the first time this happened on this computer and only after a days long session. It's no big deal and I'm sending this report only because it might be useful for improving the game.
Also, this was a random crash and I can't reproduce it. Feel free to close and ignore if it would get in the way of higher priority work.

Thank you for all your work on the game.

### Upload crash files

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/7190062/crash.zip)

**Comment by glx22** [comment]
Crash happens inside intel video driver, and I can't extract the call stack from dmp (don't want to start a dll hunt)

**Comment by randstring** [comment]
This crash never repeated and as commented, happened inside the video driver, so I think I should close this.
