### ISSUE TITLE
[Bug]: Lost ship after leaving station if it docked in a perpendicular manner and doesn't reverse

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#9566]
### Version of OpenTTD

20210919-master-g45edd9f326

### Expected result

When the ship reaches Sentown Docks and leaves it, it should be able to reverse on the spot and go towards northwest, where it will find its way to next destination.

### Actual result

When the ship reaches Sentown Docks and leaves it, it follows the path towards southeast of it and ends up lost, unable to make a turn around until it reaches open sea.

### Steps to reproduce

[Ship can't reverse at Sentown Docks.zip](https://github.com/OpenTTD/OpenTTD/files/7204799/Ship.can.t.reverse.at.Sentown.Docks.zip)
![ship becomes lost after leaving dock](https://user-images.githubusercontent.com/43006711/134211740-b2defcea-a442-41b9-82b9-0fc861394e5c.png)
t.

- Load savegame, watch ship become lost

This is probably not a bug, but more of a feature request, to ask the pathfinder whether it's better to reverse after leaving the docks.

I found this situation to be the main reason I have why some of my AI ships move so further out of place that gets them lost, even when using buoys - they enter some canal route leading to open sea and unable to return back to the right track.

**Comment by glx22** [comment]
Since #9576 ship can find a path, but it still needs to follow the canal before turning around.
