### ISSUE TITLE
[Bug]: No music or sound on Linux Debian

### ISSUE THREAD

**Issue by PepsiDoggo** [OpenTTD/OpenTTD#9571]
### Version of OpenTTD

1.11.2, Linux Debian

### Expected result

When I installed and booted up the game, I expected the usual vanilla sounds and music to be playing on the title screen.

### Actual result

The game was silent, and for some reason OpenSFX wasn't installed. Even after installing OpenSFX and having music and sound files selected, there was nothing coming from the game.

### Steps to reproduce

It isn't really an issue I think could be reproduced on other computers, as I am using a Chromebook that has Linux Debian support.

**Comment by nielsmh** [comment]
Can you start the game with driver debugging output on?

Run from a terminal:
`openttd -ddriver=1`

It should print a bunch of messages about which audio devices and output drivers are chosen.

**Comment by PepsiDoggo** [comment]
> Can you start the game with driver debugging output on?
> 
> Run from a terminal:
> `openttd -ddriver=1`
> 
> It should print a bunch of messages about which audio devices and output drivers are chosen.

I did this and it says at the end "Could not set volume"
Is this the potential root of my issues?

**Comment by nielsmh** [comment]
Right now the most likely cause would be that SDL chooses the wrong output.

You can try setting the `SDL_AUDIODRIVER` environment to force a different output, but it depends on what your system is configured for and whether OpenTTD is built for SDL 1.2 or SDL 2.0. (See [SDL FAQ](http://wiki.libsdl.org/FAQUsingSDL).)

**Comment by LordAro** [comment]
(Unless you've built OTTD yourself to explicitly use SDL1.2, it will be using 2.0)

**Comment by Enyuma00** [comment]
All i can say is get the music and sound packs if you havent, select them at basic settings menu and make sure the volume slider is not on 0
