### ISSUE TITLE
[Bug]: Path signals are the only available signals to build

### ISSUE THREAD

**Issue by Castle4079King6023** [OpenTTD/OpenTTD#9580]
### Version of OpenTTD

12.0-RC1

### Expected result

I click 'build signals' and get the full list of signals to construct

### Actual result

I click 'build signals' and the only available signals are Path signals

### Steps to reproduce

1. load any game
2. click 'build signals'

**Comment by nielsmh** [comment]
![image](https://user-images.githubusercontent.com/1062071/134818438-ae56c2f1-3ab1-4578-8fd9-9183156e34c2.png)

https://cdn.openttd.org/openttd-releases/12.0-RC1/changelog.txt
```
12.0-RC1 (2021-09-25)
------------------------------------------------------------------------
Feature: Hide block signals in GUI by default (#8688)
```

**Comment by nielsmh** [comment]
In other words, not a bug. See PR #8688 for reasoning and so on.
