### ISSUE TITLE
[Crash]: Switching from fullscreen

### ISSUE THREAD

**Issue by simply-peachy** [OpenTTD/OpenTTD#9582]
### Version of OpenTTD

1.11.2 (0), Kubuntu 20.04

### Steps to reproduce

Game was in fullscreen mode, paused. Toggled fullscreen off, game crashed. This does not happen each time.

### Upload crash files

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/7232178/crash.zip)

**Comment by glx22** [comment]
Can you try 12.0-RC1 or a nightly ?
Probably won't prevent the crash but may give some hints.

**Comment by TrueBrain** [comment]
The user never got back to us.

Given we made a lot of changes to our video-driver and how we handle fullscreen, I am going to assume this problem has been resolved in any recent nightly and the upcoming 14.0.

If not, feel free to reopen with a crash-log from any of those versions. That will give us more information :)

**Comment by simply-peachy** [comment]
Apologies for not replying sooner. I can't reproduce this in 13.0 so presume it's been resolved.

**Comment by TrueBrain** [comment]
Cool! Glad to hear, and tnx for letting us know :)
