### ISSUE TITLE
[Bug]: Incorrect sorting of vehicles by capacity

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#9584]
### Version of OpenTTD

1.11.2 (also earlier)

### Expected result

The game correctly sorts vehicles by capacity for the selected cargo (or all cargoes), starting with the vehicle with the highest maximum payload available, and ending with the vehicle with the lowest payload (or inversely) - the game takes into account all vehicle versions.

### Actual result

When sorting by load capacity, the game probably takes into account the load capacity for the first version of the vehicle, which in the case of more complex sets results in an inappropriate, looking random order on the list.

The problem is clearly visible with the new Shark 1.0 ship set
![sorting problem - shark 1 0](https://user-images.githubusercontent.com/67662046/134831255-bd61fab6-8eb6-42da-a29d-85b6b3e91fb4.png)

It is similar in the other sets from the FISH series

Another example is in the Polroad set, which generally has some balance issues and may seem overly complex, but the list order is not correct anyway. It's hard to see the sorting logic here.
![sorting problem - polroad 50](https://user-images.githubusercontent.com/67662046/134831168-b51efddf-e552-4a95-a80b-054fc771f7a4.png)

### Steps to reproduce

Description above

**Comment by LordAro** [comment]
In a way, this is actually just a misunderstanding - the sorting the vehicle list by cargo only sorts by the default cargo. The cargo filter is separate, and only meant for filtering the list, not affecting sort order.

It's definitely confusing though

**Comment by LordAro** [comment]
And of course, the existing sorter functions have no access to the selected cargo type at all, which would make fixing this "painful" to say the least.

**Comment by andythenorth** [comment]
Low likelihood of fix, would require something like
- running cb36 for all available vehicles
- running cb12 for all available vehicles
- making a decision about whether to try and guess / handle cargo subtypes for all available vehicles
- going through these flow controls to find all the edge cases https://newgrf-specs.tt-wiki.net/wiki/VehicleRefitting

Not _likely_ to happen, closing, thanks for report.

**Comment by LC-Zorg** [comment]
I understand the arguments, but would like to point out that the problem has not been resolved and will continue to apply. I think it would be worthwhile to mark this and similar reports in some other way.
