### ISSUE TITLE
[Bug]: cant join a server on the same network

### ISSUE THREAD

**Issue by pyro9287** [OpenTTD/OpenTTD#9585]
### Version of OpenTTD

1.15

### Expected result

i dont know if this is a bug or not but i cant join a server my brother made.

### Actual result

my brother made a open ttd server and i cant serch for it i tried the ip thing too but never succeded. 
we are on the same network and i tried another not work but it didnt work

### Steps to reproduce

go to multiplayer and serch lan och search internet and you just dont find the server

**Comment by LordAro** [comment]
Can you confirm which version you're using? "1.15" is not an OpenTTD version.

You might like to try 12.0-RC1, which has just been released and significantly improves the multiplayer experience - https://www.openttd.org/news/2021/09/26/new-multiplayer-experience.html

**Comment by pyro9287** [comment]
Thx alot. The game version was 1.11.2. But now everthing works with the new
version.

**Comment by TrueBrain** [comment]
Closing ad 12.0 seems to fix the issue! Let us know if there any other problems :)
