### ISSUE TITLE
[Bug]: Localized plural strings required in certain instances

### ISSUE THREAD

**Issue by kneekoo** [OpenTTD/OpenTTD#9595]
### Version of OpenTTD

12.0-rc1, Linux Mint 20.2 Cinnamon (based on Ubuntu 20.04), using openttd-12.0-RC1-linux-ubuntu-focal-amd64.deb

### Expected result

In the Romanian locale, the STR_NEWS_SERVICE_SUBSIDY_OFFERED and STR_NEWS_SERVICE_SUBSIDY_AWARDED_* need to use plural form for: passengers and mail.

Specifically: STR_CARGO_PLURAL_PASSENGERS and STR_CARGO_PLURAL_MAIL

### Actual result

Currently, STR_CARGO_SINGULAR_PASSENGER and STR_CARGO_SINGULAR_MAIL are used - and they're incorrect in Romanian.

The screenshot below shows both wrong cases on 01-04-1967 and 01-03-1967:
![wrong locale](https://i.imgur.com/4VDuM7X.jpg)

### Steps to reproduce

Use the Romanian locale and wait for subsidy news, then do the required action to get the subsidy award. Both will be displayed in singular form.

**Comment by telk5093** [comment]
I think it is solvable by translation, such as [Cases](https://wiki.openttd.org/en/Archive/Source/OpenTTDDevBlackBook/Format%20of%20langfiles#cases), not by modification of game's code itself.

**Comment by kneekoo** [comment]
> I think it is solvable by translation, such as [Cases](https://wiki.openttd.org/en/Archive/Source/OpenTTDDevBlackBook/Format%20of%20langfiles#cases), not by modification of game's code itself.

I don't understand [the cases example](https://wiki.openttd.org/en/Archive/Source/OpenTTDDevBlackBook/Format%20of%20langfiles#cases) and there's no way to test it "live". The "quickest" way to test translations is, unfortunately, by using nightly builds, but a 24-hour wait is unpractical for experimentation.

I hope the wiki will get some more examples. That would probably be faster than [allowing translation previews](https://github.com/OpenTTD/OpenTTD/issues/9590) with WebTranslator.
