### ISSUE TITLE
[Bug]: Buggy locale in a Romanian string involving bags

### ISSUE THREAD

**Issue by kneekoo** [OpenTTD/OpenTTD#9596]
### Version of OpenTTD

12.0-rc1, Linux Mint 20.2 Cinnamon (based on Ubuntu 20.04), using openttd-12.0-RC1-linux-ubuntu-focal-amd64.deb

### Expected result

Between parentheses we should see `(22 de saci)` instead of that.

![wrong locale](https://i.imgur.com/4ab97Ib.jpg)

### Actual result

Inside the parentheses, the current locale shows the singular form + the second plural form, which is wrong.

### Steps to reproduce

Set your locale to Romanian and hover over a truck in the vehicle depot list.

**Comment by glx22** [comment]
```
STR_BAGS                                                        :{COMMA}{NBSP}sac{P "" "" "de "}sac{P "" i i}
```
 is wrong, you can fix it in WT.

**Comment by kneekoo** [comment]
Thanks a lot! :) Fixed.
