### ISSUE TITLE
[Crash]: An AI fills up the maximum memory allocation almost exactly (just a few bytes left) and crashes the game.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#9599]
### Version of OpenTTD

20211102-master-ga2cf81e722 and jgrpp-0.43.0 on Windows 10

### Steps to reproduce

1. Set the value of `Maximum memory usage per script` to 1,024 MiB.
2. Load the AI attached in the below section.
3. Start up the AI.
4. Notice that the game crashes.

A. If you get "Maximum memory allocation exceeded" instead, increase the value of the constant `53214` by the value of ceil(`N`/16) in `Maximum memory allocation exceeded by N bytes while allocating M bytes`.

B. If the AI starts up normally and doesn't crash, decrease the value of the constant `53214` until either the game crashes or condition A holds true.

### Upload crash files

`20211102-master-ga2cf81e722` crashes, but does not produce any crash logs on my system.
The following crash files are from reproducing on `jgrpp-0.43.0`.
[crash-20211003T080806Z.zip](https://github.com/OpenTTD/OpenTTD/files/7272934/crash-20211003T080806Z.zip)

The crashing AI script: [_TestAI.zip](https://github.com/OpenTTD/OpenTTD/files/7272935/_TestAI.zip)

**Comment by glx22** [comment]
Fixed with #9592.
