### ISSUE TITLE
[Crash]: Assertion failed - An AI's `info.nut` fills up the maximum memory allocation almost exactly.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#9601]
### Version of OpenTTD

20211002-master-ga2cf81e722 (Steam only) on Windows 10

### Steps to reproduce

1. Set the value of Maximum memory usage per script to 1,024 MiB.
2. Close the game.
3. Extract the contents of the attached AI script zip file into your OpenTTD working directory's `ai` directory.
4. Start up the game.
5. The game asserts here. The assertion is introduced in #9589.
https://github.com/OpenTTD/OpenTTD/blob/2144cd98a34efd7b47156d6f43ee5de7d6216d86/src/script/squirrel.cpp#L771

If the game does not crash during reproduction, you may need to change the constant `3778` in the AI's `info.nut` so that it does crash.

### Upload crash files

Crash files: [crash.zip](https://github.com/OpenTTD/OpenTTD/files/7273010/crash.zip)

Crashing AI: [_TestAI.zip](https://github.com/OpenTTD/OpenTTD/files/7273012/_TestAI.zip)

**Comment by glx22** [comment]
Fixed with #9592.
