### ISSUE TITLE
[Bug]: Some gamescripts appear to be broken after loading 1.11.2 saves

### ISSUE THREAD

**Issue by ldpl** [OpenTTD/OpenTTD#9626]
### Version of OpenTTD

12.0

### Expected result

Scripts continue to work the way they did in 1.11.2

### Actual result

Scripts don't function in the way they were supposed to after loading saves made in 1.11.2 version. The same scripts work fine for games started in 12.0 version. Namely in City Controller towns that weren't growing in 1.11.2 can't be made to grow even if required cargo is supplied:
![Screenshot from 2021-10-18 15-22-27](https://user-images.githubusercontent.com/413570/137960864-31711b80-a612-4ae3-8f32-490a7abe23f2.png)

I've only verified it for City Controller but there is a similar report for Simpleton CB as well (first comment):
https://steamcommunity.com/app/1536610/eventcomments/5358712989068088189/

### Steps to reproduce

1. Load 
[city-controller-12-0-test.zip](https://github.com/OpenTTD/OpenTTD/files/7375504/city-controller-12-0-test.zip)
2. Compare how Radingham and Ladingstone Bay grow in 1.11.2 and 12.0 

Resaving in 12.0 doesn't help

**Comment by nielsmh** [comment]
Could this be some cargo monitors that don't get restored properly?

**Comment by glx22** [comment]
Really weird, just checking script debug window is interesting.
In 12.0-beta2 or 12.0 it continuously prints some message.
In 1.11.2 it prints startup messages, and nothing more until unpaused.
In nightly (steam or local debug build), it's the same as 12.0.
In nightly (local debug build), it's like 1.11.2 in script debug, but script crashes on december 2nd.
