### ISSUE TITLE
[Bug]: The previously selected signal is not saved between games

### ISSUE THREAD

**Issue by Rau117** [OpenTTD/OpenTTD#9631]
### Version of OpenTTD

12.0 Windows

###

Not sure if this is intended as part of hiding advanced™ signals.
In previous versions last used signal (block/path/one-way path) was saved through games as different parameter.

It is was very convenient to have a two-way (PBS without red plate) path signal by default and select the rest via ctrl+click. 

### Expected result

On the new game will be choosen previously used signal

### Actual result

One-way path signal is choosed by default after game loaded/reconnected to server
It does not matter if block signals are hidden or not.

### Steps to reproduce

1. Load the game and pick signal building tool
2. Choose any signal except one-way PBS
3. Once again load the game and pick signal tool
4. You will get one-way PBS choosed by default and cannot change it in any way
![2021-10-20 07-38-36](https://user-images.githubusercontent.com/47086324/138029456-e079da97-e17f-43b2-8dba-6fe0e64a7847.gif)

**Comment by iTKerry** [comment]
Thats annoying. Please, fix that.

**Comment by 2TallTyler** [comment]
Prior to #8688, there was a setting for choosing the default signal type when starting a new game, after which the GUI keeps the last-used signal selected. It did not remember the last-used signal between games.

This setting was removed in #8688 as part of a general simplification of signal-related settings, and now it defaults to one-way PBS when starting a game, then remembers the last-used signal as before.

**Comment by Rau117** [comment]
And how does that simplify the game? What was the point in that? There was a useful setting, but you need to kill it because some noobs do not understand it. Just brilliant.

These are not even hidden signals that can be shown. Yes, you remove this from settings, but leave the option to select the default signal in openttd.cfg. It is terribly inconvenient to constantly switch to the block signal, due to the fact that it is hardcoded.

It does not remember, I search thorugh the code. You just removed the setting that does it. In _some_ pa
rameter there, instead of  **"look in config and choose signal"** it makes **"select one-way PBS"**

![изображение](https://user-images.githubusercontent.com/47086324/138122521-072d95fd-487f-4fd0-953e-2882437a2041.png)

**Comment by Rau117** [comment]
It does not remember, It cannot remember. I searched thorugh the code. You just removed the setting that does it. 
In _some_ function instead of "look in config and choose signal" it makes "always select one-way PBS".

![изображение](https://user-images.githubusercontent.com/47086324/138122719-8e03d046-41e0-44c4-95dc-08a09236305d.png)

**Comment by same-f** [comment]
I As an admin server on which both advanced players and new players play, I can say that after the update, everything (including new ones) is in misunderstanding of the changes, and in search of signals. So far, I have seen the exact opposite of simplifying the game for beginners, as I see these beginners looking for help to turn on. And I don't understand why a handful of clever people solves what most people need by covering up their desires and whims with beginners.

**Comment by LEB0VSKI** [comment]
i need a developer. no one can explain it to me. i hope you'll explain it to me. why does the train don't want to go to the depo?
![Screenshot_2021-10-20-18-39-44-393_com miui gallery](https://user-images.githubusercontent.com/92875611/138126009-742acd3b-7283-42b3-ba43-8c2d8f8cac9e.jpg)

**Comment by LordAro** [comment]
@LEB0VSKI Difficult to say for sure without a savegame, but my guess is that the train has previously selected the left-hand depot to use (either through orders or when it decides it needs to go for a service), so has to wait - it's not clever enough to know that there's a free one right next to it

Technically, #9577 might help with that...

**Comment by LEB0VSKI** [comment]
there's a station there. just behind the station are these depots. by what principle do trains choose a depot in this case? (they are given the task to go to the nearest depot)

**Comment by LordAro** [comment]
Impossible to say without a savegame. I can't even see a station in your screenshot and have no idea what those trains are doing just from the picture - these sort of questions should go on the forum - https://www.tt-forums.net/viewforum.php?f=31

**Comment by Eddi-z** [comment]
aside of this question not belonging here, you could try the following: place a waypoint right before the two depots, and use a "go via \<waypoint\>" with a "if need servicing" conditional order, instead of a "service at depot" order.

**Comment by TrueBrain** [comment]
> 
> 
> It does not remember, It cannot remember. I searched thorugh the code. You just removed the setting that does it. In _some_ function instead of "look in config and choose signal" it makes "always select one-way PBS".
> 
> ![изображение](https://user-images.githubusercontent.com/47086324/138122719-8e03d046-41e0-44c4-95dc-08a09236305d.png)

If you read the diff carefully, you see that `_default_signal_type` is a "read-only" settings. That is to say: it is only read by the code, and never set (with the exception of the settings menu). In yet other words: it doesn't remember your last signal type used, but you can set what the default is when opening it.
Sounds you experience Mandela Effect :) If you don't believe me, try it out yourself in 1.11 or something. You will see you always start with the same signal type, no matter how you left it behind.

That said, I guess we could read the bug report as: "I want a way to set my default signal to either one-way or two-way". That was possible pre-12.0, and is no longer. I currently have no opinion on that :)

**Comment by Rau117** [comment]
Okay, I made a mistake about choosing a signal between games from signal menu. But now the setting that is responsible for the default signal is gone? I would very much like to return it, because the one-way PBS by default is very inconvenient in "our" style of play. 

Perhaps I had some old version of the setting in openttd.cfg that worked, but now it is gone and saving signals does not work now in any form. Even on 1.11.x

Okay, okay, everything is quite simple there, but the changes will not be accepted, most likely

**Comment by LC-Zorg** [comment]
It's not the same bug, but it seems the root of the problem is the same, so I'm writing here.
Removing the setting also means that when running different versions of the game, each time the selected signaling setting changes. Sometimes both settings. If someone uses different versions for some reason (e.g. playing on different servers), each time before or during the game has to correct these settings. This is discouraging... :/
![Nightmare](https://user-images.githubusercontent.com/67662046/138601454-9ddc6afc-2929-4d2b-bb84-b063a367095f.png)
