### ISSUE TITLE
[Bug]: Turning the music volume slider to 0 then back results only playing MIDI sounds at default volume

### ISSUE THREAD

**Issue by Enyuma00** [OpenTTD/OpenTTD#9640]
### Version of OpenTTD

12.0 Windows 10

### Expected result

Turning music volume slider to 0 then back should just play the music with no change

### Actual result

The MIDI sounds get played on default volume for some reason

### Steps to reproduce

Go to basic settings menu or jazz musicbox, go to music volume slider, turn it to 0 then turn it back

**Comment by Enyuma00** [comment]
Also i use 64bit to be very specific

**Comment by Stratdan0** [comment]
yep, i tried it works i don't know why tho

**Comment by LordAro** [comment]
I'm not quite sure what you mean by "with no change" here. Do you mean you're expecting the music to be paused if the volume is set to zero?

I can't hear any strangeness the actual volume output when sliding volume to zero and back, but I am on a different platform

**Comment by nielsmh** [comment]
Music playback continues regardless of what the volume setting is. It continues playing even if the volume is zero.
The volume adjustment is done by multiplying the per-channel volume (GM controller 8) from the song data with the volume setting, and immediately sending a new controller change event on every channel when the volume setting is changed.
If you change the volume setting to zero then all sound is going to get silent instantly. If you change the volume setting to 8, then all sound is going to get barely-audible instantly. If you change the volume setting to 127 (max) then all sound is going to get full volume instantly.
This behaviour should be exactly the same on both the Win32 and the DirectMusic drivers.

You need to be more specific with what exactly you do and what exactly you expect, ideally including a screen capture video including a capture of your audio output that demonstrates the error.

**Comment by 2TallTyler** [comment]
The information in this report isn't enough to understand what problem is being reported, and the author of this issue hasn't provided any more info. If anyone is still experiencing this bug, please open a new issue (with more info).
