### ISSUE TITLE
[Bug]: Screenshots are no longer saved as PNG

### ISSUE THREAD

**Issue by lcd047** [OpenTTD/OpenTTD#9643]
### Version of OpenTTD

12.0, Linux

### Expected result

Screenshots should be saved as PNG when OpenTTD is linked against libpng.

### Actual result

Screenshots are always saved as BMP.

### Steps to reproduce

1. Start a game
2. Press Shift-S, or click "Normal screenshot" from the menu.

`openttd` 12.0 is linked against `libpng`.  Version 1.11.2 still saves screenshots as PNG, so there is nothing wrong with either detection or functioning of `libpng`.

**Comment by glx22** [comment]
Oh indeed I can confirm that, I have `screenshot_format = png` in openttd.cfg, but it saves as BMP.
~~It used to work less than a month ago.~~

**Comment by James103** [comment]
Did you try downgrading `libpng` to a version released no later than mid-September 2021 (if that's even possible)? There may have been some changes since then that has caused OpenTTD to no longer use the library correctly.

**Comment by glx22** [comment]
I've not updated libs since July.

**Comment by lcd047** [comment]
Same here, I'm using `libpng-1.6.37` which is pretty old.

**Comment by glx22** [comment]
Oh my last png screenshots where in May (I though it was more recent), so something broke between then and now (libs or source code)

**Comment by lcd047** [comment]
Indeed this fixes the  problem, thank you!
