### ISSUE TITLE
[Bug]: Gold Mines no Banks

### ISSUE THREAD

**Issue by Budgie2021** [OpenTTD/OpenTTD#9654]
### Version of OpenTTD

12

### Expected result

Have gold mines but there are no banks created and a bank cannot be funded - tagged as future use

### Actual result

ditto

### Steps to reproduce

 ditto

**Comment by glx22** [comment]
Maybe attach a savegame at least.

**Comment by James103** [comment]
Will you please attach a screenshot of your NewGRF Settings window in the affected game?

**Comment by Budgie2021** [comment]
Will do

**Comment by Budgie2021** [comment]
screenshot
![Screenshot (2)](https://user-images.githubusercontent.com/81542598/138615520-ad67ef31-39a9-4f46-8f67-c6511e35bf53.png)

**Comment by Budgie2021** [comment]
Seems github no 7zip  - 7z or rar  darn

**Comment by James103** [comment]
Are you on Windows? If so, to create a ZIP file of the save,
1. Open Explorer and navigate to the directory where the save is located.
2. Right click, then click "New" -> "Compressed (zipped) folder".
3. Drag the `.sav` file for the affected save into the newly created ZIP file.
4. Attach the ZIP file here.

**Comment by Budgie2021** [comment]
James have been trying for an hour now. 
My newly installed evaluation Winzip  copy creates a winzip file no prob.
However github refuses to reconoze it as a legit file.
I think my preferred zip files rar and 7z are overriding the winzip format.
Your instructions do not seem to work with a Winzip eval copy.
and I am tired of trying

sry

**Comment by AtjonTV** [comment]
@Budgie2021 you can also try to make a ZIP without using Winzip .. go into the folder of the save file, right click it and then "send to" -> "(Zip) Compressed file". This should put the zipped file either in current folder or on desktop (should be desktop)

As far as I know those ZIPs can be uploaded to Github :wink: 

(This is a Windows feature that exists since Windows XP)

**Comment by Budgie2021** [comment]
Dear fellow OpenTTD lovers ..., I'm old , learned computers on a VIC20 - spec and build my own now.

Owned the original TTD and have been playing OpenTTD for decades. 

This was my first reporting of an issue.

I use Winrar and 7zip as preferred. Unzippers. 

However in 40 years of heavy computer usage I have never had to archive and send a zip file.

Creation of a valid "winzip" file (archived then restored by the winzip program - and note I downloaded  and installed a eval copy of Winzip and tested it.)

That  is not the issue here. 

Github refuses to recognize the file as a "zip" file.

Specifically in the location where you drag the file it states in RED "is not included in the list"

So folks anyone can set up and run a copy of my script settings in much less time than we are wasting here to see/duplicate the "savegame issue" issue.

Keep up up excellent work team.

This issue is reported and in your ballpark to solve or ignore at your pleasure.

I have games to play.

**Comment by Budgie2021** [comment]
Loic - re: gold mines but  no buildable banks,. which just may be a
programmer desired.
 Senningville Transport, May 19th, 1983.sav
<https://drive.google.com/file/d/1i8pcompAIueJYbTdTrZj7Y5Hjv3jvuBU/view?usp=drive_web>

**Comment by Budgie2021** [comment]
Tested for this error using a  new game with no GRF settings.

Banks can be built just fine,  so the error muat be related to a created mod in my game GRF settings and not Openttd 12.

Issue closed.

Thanks again team.

**Comment by Budgie2021** [comment]
I'll check and make sure any errors are not mode related next time.
