### ISSUE TITLE
[Bug]: Install target for emscripten is incorrect

### ISSUE THREAD

**Issue by kaomoneus** [OpenTTD/OpenTTD#9655]
### Version of OpenTTD

12.0-RC1

### Expected result

As an installaction result I expect to see 4 files gather in same directory:
* *openttd.html*
* *openttd.data*
* *openttd.js*
* *openttd.wasm*

### Actual result

Only *openttd.html* appears in final installation directory (`install/games` dir).

Also *share* directory is created as if would install it on Linux.

### Steps to reproduce

1. Initialize build directory with cmake. Use custom installation path by means of `-DCMAKE_INSTALL_PREFIX=<>`
2. Build openttd.
3. Install it.
4. Observe installation directory.

**Comment by kaomoneus** [comment]
I believe we need something like this:
https://github.com/kaomoneus/OpenTTD/commit/ef03a56de83e7765aba43c3d80afbebd13052e39

### My concerns (about my fix)
1. .js, .wasm and .data perhaps should be classified as a data files. But there is no such component. So I just heaped everything in `Runtime`.
2. I hardcoded paths like `${CMAKE_BINARY_DIR}/openttd.js` but perhaps, there is some variable I'm not aware of. Smth like `OPENTTD_JS_PATH`
3. Perhaps it's good to redefine default `CMAKE_INSTALL_DATADIR` and `CMAKE_INSTALL_BINDIR` values. For emscripten it is better just to keep structure flat, all in same directory.

**Comment by TrueBrain** [comment]
You should have made a PR out of it! It went under the radar now :D

1) that is fine.
2) that is fine, and pretty common.
3) nah; this is fine :)

I did make a change to your commit, as not installing COPYING etc isn't right :) But other than that, tnx for the commit!
