### ISSUE TITLE
[Crash]: OpenTTD crashes about 30 seconds after launch.

### ISSUE THREAD

**Issue by swetr77** [OpenTTD/OpenTTD#9660]
### Version of OpenTTD

OpenTTD version 12.0, Windows 10 21H1

### Steps to reproduce

Started OpenTTD, did nothing, just idle on main screen, but just after 20-30 seconds OpenTTD completly crashed. I tried multiple times and even after reinstall it keeps happening.

### Upload crash files

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/7425543/crash.zip)

**Comment by LordAro** [comment]
Duplicate of #9622 

Try setting zoom_min to 0 or 1 in [gui] section of openttd.cfg.
