### ISSUE TITLE
[Crash]: Crashed on startup in both Steam and standalone versions

### ISSUE THREAD

**Issue by TowkeyMeriam** [OpenTTD/OpenTTD#9661]
### Version of OpenTTD

12, Windows 10

### Steps to reproduce

1. Launch game
2. Closed a few dialogs about missing grf (OpenGFX, and OpenSound were not installed)
3. Crashed at the welcome screen around 10 seconds later

### Upload crash files

[OpenTTD_crash.zip](https://github.com/OpenTTD/OpenTTD/files/7426347/OpenTTD_crash.zip)

**Comment by James103** [comment]
From @LordAro:
> Try setting zoom_min to 0 or 1 in [gui] section of openttd.cfg.

**Comment by LordAro** [comment]
Likely duplicate of #9622
