### ISSUE TITLE
[Bug]: Two-ways path signals affect signals behind them

### ISSUE THREAD

**Issue by lcd047** [OpenTTD/OpenTTD#9662]
### Version of OpenTTD

12.0, Linux

### Expected result

The exit signal 2 in the picture below should be red.  The backwards path signal 1 should have no effect on what happens behind it other than a path penalty.

### Actual result

The exit signal 2 in the picture below is green.

### Steps to reproduce

<img width="740" alt="2021-10-29_14-46" src="https://user-images.githubusercontent.com/1281736/139429778-9ad36682-a1e3-4a81-9eba-c59ed26b83be.png">

In this picture 1 is a two-ways path signal placed backwards, and 2 is an exit signal (the point of signal 1 being to encourage trains to pick one of the other choices, since they have access to two platforms rather than one).  Sadly the path signal 1 seems to affect the functioning of the exit signal 2.

**Comment by PeterN** [comment]
All signals mark the end of a signal block, regardless of their direction.

There isn't really a need to use block and pre-signals this way on a terminus station.

**Comment by lcd047** [comment]
> All signals mark the end of a signal block, regardless of their direction.

Is this a recent change?  I believe the above used to work in the past.

**Comment by lcd047** [comment]
Right, what I'm saying doesn't make sense.  Sorry for the noise.
