### ISSUE TITLE
[Crash]: Game crashes when launching game after update to 12.0

### ISSUE THREAD

**Issue by wlbrsmth** [OpenTTD/OpenTTD#9663]
### Version of OpenTTD

12.0 Windows 10 Pro 64-bit

### Steps to reproduce

1. Start game
2. Wait 10 sec
3. crash and error report

### Upload crash files

[OpenTTD.zip](https://github.com/OpenTTD/OpenTTD/files/7442824/OpenTTD.zip)

**Comment by James103** [comment]
Possible workaround from @LordAro:

> Try setting zoom_min to 0 or 1 in [gui] section of openttd.cfg.

**Comment by wlbrsmth** [comment]
I tried this fix:
https://github.com/OpenTTD/OpenTTD/issues/9622
and it worked
