### ISSUE TITLE
[Crash]: Whenever I idle on the main menu for too long the game gives a fatal error

### ISSUE THREAD

**Issue by FemboyFan21** [OpenTTD/OpenTTD#9664]
### Version of OpenTTD

12.0 windows 10 steam edition

### Steps to reproduce

1. open the game
2. wait on the main menu for about 15-30 seconds (works fine if I load a save)

### Upload crash files

[the deets.zip](https://github.com/OpenTTD/OpenTTD/files/7445770/the.deets.zip)

**Comment by James103** [comment]
Possible workaround from @LordAro in #9622:

> Try setting zoom_min to 0 or 1 in [gui] section of openttd.cfg.

**Comment by Siob21** [comment]
Hi!

Got the same issue, the fix worked for me. Thx!
