### ISSUE TITLE
[Bug]: No nightly builds are published after October 25.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#9668]
### Version of OpenTTD

Any/all versions after 4487ad1a5e for Windows, Mac, Linux, or Steam

### Expected result

There are at least 6 commits made since October 25, including 1 bug fix and some translation updates.
These commits should have been included in the latest nightly release, which should be released tonight.

### Actual result

The above commits are not included in the latest nightly release, which is released on October 25 (instead of sometime in November). Since no release is made on cdn.openttd.org, that means no precompiled builds exist for these versions for Windows, Mac, Linux, or Steam.

### Steps to reproduce

1. Check Steam for updates.
2. Notice that the latest update is released on October 25.
3. Check https://cdn.openttd.org/openttd-nightlies/2021/ for updates.
4. Notice that the latest build is released on October 25.

**Comment by TrueBrain** [comment]
For an easier overview of how the nightly is doing, see https://github.com/OpenTTD/OpenTTD/actions/workflows/release.yml :)

**Comment by glx22** [comment]
We know it :)
It's a bug in github actions virtual environment.
We hope it will be fixed tomorrow.

**Comment by James103** [comment]
The latest build was successful. Steam updated the game (nightly version 20211103), and cdn.openttd.org shows the same latest nightly version. I'm closing this issue for now.
