### ISSUE TITLE
[Bug]: Two way rail signals

### ISSUE THREAD

**Issue by killory** [OpenTTD/OpenTTD#9670]
### Version of OpenTTD

1.12.0 win 10 pro

### Expected result

I was playing the game and started to make some railways .I got to the point wher i wanted to make some 2 way signals.so iwasd expecting 2 way signals on first deployment.

### Actual result

I don't know if it's a bug but I can't Place two-way signals anywhere on my train lines.Is that a bug?

### Steps to reproduce

[Killy Transport National, 1977-12-11.zip](https://github.com/OpenTTD/OpenTTD/files/7474520/Killy.Transport.National.1977-12-11.zip)
step 1. Load game
step 2. Try place pace rail signals. It will place a 1 way signal clicking multiple times will only  allow direction change on signal and does not allow a two way signal to be installed.

**Comment by PeterN** [comment]
It's not a bug, in the changelog for 12.0:

Feature: Hide block signals in GUI by default (#8688)

**Comment by killory** [comment]
i must be blind i dont see it
![settingcapture](https://user-images.githubusercontent.com/10958451/140346467-fe439a01-c173-4dd7-bba8-699e08e98633.png)
t

**Comment by ldpl** [comment]
@killory 
![Screenshot from 2021-11-04 18-20-09](https://user-images.githubusercontent.com/413570/140348519-b23a5cdc-e955-4ba9-a838-20cf9b507eef.png)

**Comment by killory** [comment]
thanks and sorry for anny incoviniance
