### ISSUE TITLE
[Bug]: Grammatically incorrect comment in overflowsafe_type.hpp

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#9681]
### Version of OpenTTD

0ad40ee868a4e2ced9cb34bdbb5cddec84cb26fe

### Expected result

The message should read:
```c++
/** 
 * Overflow safe template for integers, i.e. integers that will never overflow 
 * when you multiply the maximum value with 2, or add 2, or subtract something 
 * from the minimum value, etc. 
 * @param T     the type these integers are stored with. 
 */ 
```

In other words, add `when` between `integers that will never overflow` and `you multiply the maximum value with 2`, and update the line wrap accordingly.

### Actual result

The message actually reads:
https://github.com/OpenTTD/OpenTTD/blob/0ad40ee868a4e2ced9cb34bdbb5cddec84cb26fe/src/core/overflowsafe_type.hpp#L23-L28

### Steps to reproduce

Check lines 23-28 of the file `src/core/overflowsafe_type.hpp` and notice the incorrect message.

**Comment by TrueBrain** [comment]
It really is about time you learn how to make your own PRs @James103 ;) You can even do it from the GitHub interface if you so would like :)
