### ISSUE TITLE
[Steam] 12.1 release only available through "testing" beta

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#9682]
### Version of OpenTTD

12.0

### Expected result

Steam automatically updates my 12.0 version to 12.1 when it is released, without me having to do anything.

### Actual result

Steam keeps using 12.0. In order to use 12.1, I have to select the "testing" beta.

### Steps to reproduce

1. Run OpenTTD via Steam and see that it is still 12.0.
2. Right-click on the game in your Steam library and select Properties.
2. In the Betas tab, choose the "testing" branch from the dropdown.
3. See that the game updates to 12.1.

**Comment by TrueBrain** [comment]
And you only complaint about Steam? But how about GOG?! :(

Will be fixed later tonight .. moving releases to stable is a manual action not everyone can perform, so it is always slightly delayed :) (for all platforms btw, Steam, GOG, MSStore, ..)
