### ISSUE TITLE
[Suggestion]: Change behaviour of the «expand signal menu» button

### ISSUE THREAD

**Issue by Rau117** [OpenTTD/OpenTTD#9686]
### Version of OpenTTD

13.0? 12.2? Idk.

### Expected result

I didn't notice this the first time, but now I can clearly see that new signals button is **completely useless** and will be pressed not more than 5-6 times.

If the player knows about the existence of block signals and want to use it, he will permanently turn on the old menu and completely forget about this button.
If the player does not know about block signals, he… will **not** turn on the old menu and will also forget about this button forever.

I suggest to show message when the signal menu opens for the first time after (next?) update
Something like «Do you want to show advanced signals menu?»: Yes, No, Not now.

If the player clicks YES, show the signals menu, which contains all the signals.
By the new button one row of the signals will be hided, you can change light to the semaphore, and vice-versa. by pressing «change signal type» button. Ctrl+click will hold this button and it will acts as normal.
![изображение](https://user-images.githubusercontent.com/47086324/141015183-cde9164e-351c-4fa0-be68-a9d542449796.png)

If the player clicks NO, the signal menu will be turned off completely. The semaphore / traffic light is selected according to the setting and current year (build old style signals before [year]), the default signal is one-way PBS, changing the signal by ctrl+click on curren signal. 
ctrl+click on the signall menu on the rail toolbar will open the simplified signal menu in its current form, where you can change signal by default, signal type for this game by default and distance between signals. Make distance = 5 by default for the new players.
![изображение](https://user-images.githubusercontent.com/47086324/141016155-25080458-d630-406e-bf31-aea0ed352a6c.png)

### Actual result

Just a suggestion. 

### Steps to reproduce

1
2
3

**Comment by LordAro** [comment]
Nah.

Issue tracker not the place for suggestions anyway

**Comment by iTKerry** [comment]
@LordAro then where should suggestions be posted? Why can't you create label 'suggestion' or smth like that? How do you manage GH Issues in that case???

At least leave link to the place where suggestions can be left. 

Don't ignore a big part of your community. It's a bad practice.

**Comment by TrueBrain** [comment]
Dear @iTKerry, before you go off on a member of our community, can I please ask you to do the bare minimum first and check what we have in place? If you click "new issues" there is a button "suggestions". That is the place for suggestions :)

We don't ignore suggestions; issue trackers just aren't the place for it :D

**Comment by Rau117** [comment]
> We don't ignore suggestions; issue trackers just aren't the place for it :D

Oh sure. Why suggest something here, if you can go to the forgotten and useless forum?
How often do you visit the forum to check new suggestions?

I hope his will not be removed from the discussions. Or at least it will be noticed.

**Comment by TrueBrain** [comment]
Just because you don't agree with processes we have in place, doesn't mean you can just ignore them and stamp over them.

If you disagree with a process you can start a constructive conversation about it. This is not that :)
