### ISSUE TITLE
[Crash]: Crash on startup / 12.1 / MacOs

### ISSUE THREAD

**Issue by cbeyer** [OpenTTD/OpenTTD#9688]
### Version of OpenTTD

12.1, MacOs Sierra 10.12.6

### Steps to reproduce

1. Lauch the game
2. Crash!

### Upload crash files

Process:               openttd [98278]
Path:                  /Applications/OpenTTD 1.12.1.app/Contents/MacOS/openttd
Identifier:            org.openttd.openttd
Version:               12.1 (12.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           openttd [98278]
User ID:               501

Date/Time:             2021-11-11 10:48:22.302 +0100
OS Version:            Mac OS X 10.12.6 (16G2136)
Report Version:        12
Anonymous UUID:        CAA4237B-B4DA-7B34-AC33-23B14C5D146C

Sleep/Wake UUID:       D3EB6F46-FDDE-4463-A368-87B0E581E933

Time Awake Since Boot: 620000 seconds
Time Since Wake:       3600 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Symbol not found: __ZTISt18bad_variant_access
  Referenced from: /Applications/OpenTTD 1.12.1.app/Contents/MacOS/openttd
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/OpenTTD 1.12.1.app/Contents/MacOS/openttd

Binary Images:
(...)

**Comment by LordAro** [comment]
Is this a new crash (since 12.1)? Or does it happen with older versions as well? Is it consistent?

Separate issue: why does macOS think the version is 1.12.1 ?

**Comment by orudge** [comment]
> Separate issue: why does macOS think the version is 1.12.1 ?

It doesn't, the user may have just renamed the app. (See ```Version: 12.1 (12.1)``` in the crash report.)

**Comment by glx22** [comment]
MacOS before 10.14 is missing a symbol, so that's the minimum supported version.

**Comment by cbeyer** [comment]
Sorry for the version, 12.1 of course :) (first post edited)

Versions up to 11.2 were OK.

**Comment by TrueBrain** [comment]
Fixed by #9689
