### ISSUE TITLE
[Bug]: Linking Error on Raspbian OS Buster with OpenTTD 12.1

### ISSUE THREAD

**Issue by wg25** [OpenTTD/OpenTTD#9690]
### Version of OpenTTD

12.1 Linux, Raspbian Buster

### Expected result

Fully build of the 12.1 on Raspbian
On the same raspberry pi 3 compiling of 12.0 works with no problems

### Actual result

[ 44%] Linking CXX executable openttd
collect2: fatal error: ld terminated with signal 9 [Getötet]
compilation terminated.
make[2]: *** [CMakeFiles/openttd.dir/build.make:6306: openttd] Fehler 1
make[2]: *** Datei „openttd“ wird gelöscht
make[1]: *** [CMakeFiles/Makefile2:1241: CMakeFiles/openttd.dir/all] Fehler 2
make: *** [Makefile:163: all] Fehler 2
root@gamma:~/openttd-12.1/build#

### Steps to reproduce

1. Raspbian Buster on Raspberry Pi 3
2. cmake .. in build of OpenTTD 12.1
3. make

**Comment by nielsmh** [comment]
Killed with signal 9? You should check your kernel log, my first suspicion is some kind of Out Of Memory (OOM) error.
Try adding more swap to the system, if you can.

**Comment by wg25** [comment]
Yes, you are absolutly right. My fault. It's working now.
