### ISSUE TITLE
[Crash]: OpenTTD crashes right after I launch it

### ISSUE THREAD

**Issue by DonaldDuck313** [OpenTTD/OpenTTD#9695]
### Version of OpenTTD

12.0, Windows 11

### Steps to reproduce

No idea, I just launched OpenTTD.

### Upload crash files

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/7533719/crash.zip)

**Comment by nielsmh** [comment]
There are some bugs fixed in version 12.1, please try upgrading first.

**Comment by LordAro** [comment]
Almost certainly duplicate of #9622

**Comment by glx22** [comment]
Yup duplicate, I checked the callstack.
