### ISSUE TITLE
[Bug]: Most or all of the message display settings are not working properly

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#9698]
### Version of OpenTTD

12.1 Win10

### Expected result

The settings work properly, the selected player settings remain unchanged for the next version of the game.

### Actual result

The production change and company shutdown news settings are tied to the news setting for opening new companies - changing this setting affects the others.

![News settings bug  1](https://user-images.githubusercontent.com/67662046/141700700-d815877c-3c22-441d-895f-a3505914026c.png)

![News settings bug 2](https://user-images.githubusercontent.com/67662046/141700708-fb29f669-1d71-4a06-a4ef-51aecd60178b.png)

Currently, it is impossible to set summary messages for opening enterprises and exclude messages about production changes and closing enterprises. To disable the latter, you must select either disable or full messages for enterprises opening.

### Steps to reproduce

1. Start the game with a default industry and high density.
2. Disable messages about closing enterprises and production changes, while those about opening are enabled - it doesn't work.
3. Change the enterprises open message setting to Full or Off - it works.
4. I haven't checked all the possibilities, so maybe there is a bug somewhere else.

**Comment by glx22** [comment]
Works for me, and nothing changed in this area between 12.0 and 12.1

**Comment by LC-Zorg** [comment]
Well, so it's even more interesting. :) Indeed, I started the game and everything was fine. But...
1. When I changed the last of the settings, I started to see the summary news about subsidies that I had turned off.
2. When I then turned on the summary information about the closings of enterprises, information about changes in production also appeared.
![News settings bug  3](https://user-images.githubusercontent.com/67662046/141706429-d3abe04a-1fda-4db7-a6d1-9befed2af23b.png)

3. The next time I started the game, I changed the setting about opening enterprises and this time information about... subsidies appeared, but they should not.
![News settings bug  4](https://user-images.githubusercontent.com/67662046/141706436-6288e36d-1e1c-4785-b1ae-ea18b8e2ac27.png)

It looks as nothing has to do with anything. Maybe the problem is related to #9653, though I don't see this setting.

**Comment by glx22** [comment]
#9653 will be in 13.0, it's not in 12.1

**Comment by LC-Zorg** [comment]
Ok, I started the game again and this time there were messages regarding either aging vehicles and the arrival of the first vehicle at the station. I've had these messages off for a hundred years...

I admit that the problem with the news appeared some time ago. Maybe in 1.10.0 or even earlier. At the time, I wanted to turn on lost vehicle warns, but that didn't work and the messages weren't popping up. I wrote about it in one of the [topics](https://www.tt-forums.net/viewtopic.php?p=1236379#p1236379).  Now it is much worse, because nothing works as it should.

**Comment by 2TallTyler** [comment]
@LC-Zorg Are you still experiencing this problem? If not, I'd like to close this issue, as it seems like an isolated problem that nobody else has encountered (or at least reported).

**Comment by LC-Zorg** [comment]
I checked and I don't see the problem persisting. If anything comes up again, I'll let you know. I think it can be closed as solved, though I don't know how and when. :)

**Comment by 2TallTyler** [comment]
Glad to hear it. Thanks.
