### ISSUE TITLE
[Bug]: No indication that server is full within the game

### ISSUE THREAD

**Issue by ldpl** [OpenTTD/OpenTTD#9703]
### Version of OpenTTD

12.1

### Expected result

Online players window shows some clear indication that server is full and new company can't be created.

### Actual result

(New company) line just disappears and players, especially newbies, get confused trying to find it.
![Screenshot from 2021-11-17 03-21-21](https://user-images.githubusercontent.com/413570/142086987-13ca91c6-6e01-40b0-af00-5c2d6fc9c7ff.png)

![Screenshot from 2021-11-17 03-14-53](https://user-images.githubusercontent.com/413570/142086375-0496fb1d-f48b-41d0-ac18-452ef7b81bd0.png)

### Steps to reproduce

1. Join a full server
2. ???

**Comment by 2TallTyler** [comment]
Closed by #10523.
