### ISSUE TITLE
[Bug]: Cities still build too many, too long, bridges that spoil the game map

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#9712]
### Version of OpenTTD

since 1.11.0, Win10, Probably caused by #8439

### Expected result

The number of bridges visible on the game map is not overwhelming.

![Zrzut ekranu 2021-09-30 234007](https://user-images.githubusercontent.com/67662046/142782635-5844dc53-8182-4b94-8d21-e83b0444aada.png)

![Zrzut ekranu 2021-10-05 000646](https://user-images.githubusercontent.com/67662046/142782653-2c47c77b-7db4-4db9-a088-d09228f314ac.png)
The longest visible bridge on this maps has 19 tiles, all the longer ones have been removed

**Comments from PR #8439: Feature: Make town bridge max length a function of its population**
[perezdidac (author)](https://github.com/OpenTTD/OpenTTD/pull/8439#issuecomment-751410446): _I tried different town sizes and bridge lengths and 20 seems too much regardless of the city size._
[2TallTyler](https://github.com/OpenTTD/OpenTTD/pull/8439#pullrequestreview-558899338): _I think 20 tiles is a bit excessive and would lead to large cities building ridiculous bridges. What about keeping the current 11 tile length?_
**Comment from the discussion preceding the above PR (#8388: Maximum town bridge length)**
[2TallTyler](https://github.com/OpenTTD/OpenTTD/discussions/8388#discussion-71510): I generated a map with lots of bridges (high number of towns and medium sea level) and did a quick survey of bridge lengths (again, not counting bridge ends). In general, those with a length <= 4 nearly always look appropriate, bridges length == 5 are about evenly split between silly and appropriate, and bridges> 5 tiles are mostly silly.

### Actual result

After the change in version 1.11.0, cities can build very long bridges. As a result, after a while, there are tons of ridiculous bridges going nowhere around the cities located by the water. The effect seems to be inconsistent even with what Perezdidac, author of this change wanted to achieve.

![Zrzut ekranu 2021-09-30 231532](https://user-images.githubusercontent.com/67662046/142782935-4279fc88-b1ba-403a-b12b-788918f2b433.png)
![Zrzut ekranu 2021-10-04 235747](https://user-images.githubusercontent.com/67662046/142782945-98433052-0e88-4ec1-9c8f-35020c685405.png)
The entire body of water near cities is covered with bridges. It just looks wrong. Much worse than before the change.

Now, whenever I launch a new game, after a while, a lot of ridiculous bridges are built up each time. This happens even when I open some old save.
![Zrzut ekranu 2021-10-04 231114](https://user-images.githubusercontent.com/67662046/142783019-b1342ac9-8288-44e9-9d93-5980291e4bfd.png)
![Zrzut ekranu 2021-10-30 195431](https://user-images.githubusercontent.com/67662046/142783038-f54af993-9d37-4df2-9f57-365f63e095dd.png)
![Zrzut ekranu 2021-11-21 231454](https://user-images.githubusercontent.com/67662046/142783044-dab078d2-32fc-4b06-aa64-6a9676805b79.png)

### Steps to reproduce

The problem is most noticeable / nuisance on maps with a lot of water.

**Comment by LC-Zorg** [comment]
I'm reporting this problem again because I suppose it may take a lot of time before there is someone to fix the problem and come up with a more advanced solution or it may even never be solved. Meanwhile, to significantly reduce this annoying problem, it would now be enough to restore the maximum length limit. In my opinion the limit not should be higher than 20 - with this value it often looks bad, but sometimes it still makes sense. Previously, it was 12. There was also a proposal to limit this length to 5, which I consider too restrictive.
Another posibility is also undo this change in its entirety until the proper conditioning of bridge construction is introduced, or ... add a setting for the length of city bridges and tunnels.

**Comment by 2TallTyler** [comment]
Related, with some discussion of possible solutions: #9299

**Comment by pleasejustgo** [comment]
wow, you guys are almost as bad as the OpenRA devs.
