### ISSUE TITLE
[FIX] Unwanted feature - Company passwords are not saved in the savegames.

### ISSUE THREAD

**Issue by Shituation** [OpenTTD/OpenTTD#9713]
### Version of OpenTTD

12.1 / Windows 10

### Expected result

My unknown guests (open online server) keep losing their companies after a server reboot.
Recently some asshole connected after a reboot and cleaned all companies leaving a "heh heh heh" in the chat.

Fix the company password issue. Encrypt them if needed, or change the method. Be creative.

Right now the problem that you fear so much is happening anyway. 
1 out of 1000 people are going to take the time to hack a network game savefile to steal passwords. 

What's the paranoia? it happens anyway...

PD: server is on windows 10 pc, has updates an all kind of stuff so it as to be rebooted from time to time. That obliterates players every time. I'm the only one standing since I know when the server reboots, cause I'm the admin.

### Actual result

- Have people connecting to unprotected companies after a reboot and destroying the game.
- Have other players erased since the server deletes unprotected companies after a while.

### Steps to reproduce

Play the game online.

**Comment by telk5093** [comment]
See https://github.com/OpenTTD/OpenTTD/discussions/8420

**Comment by TrueBrain** [comment]
Although we understand the frustration this might give to you, the alternative isn't much better. In your balance, it is worth the risk. In our balance, we stray on the side of caution, and it is not worth the risk. As such, by pure policy, we do not store passwords of users anywhere. It is simply the safer thing to do.

That said, we have for years been looking into solving "private" companies in other ways, like the discussion linked. Sadly, as of yet, nobody brought forward an implementation that was accepted into our codebase. Until that time, I am afraid we have to disappoint you here.

On that note, I am going to close this issue, as we do not consider this a bug, but intended behaviour. And again, I understand your use-case and that it can be frustrating. But in the balance of two evils, one has to win.

**Comment by danfe** [comment]
> My unknown guests (open online server) keep losing their companies after a server reboot.

Ten years ago someone sent me a [patch](https://cgit.freebsd.org/ports/tree/games/openttd/files/extra-patch-save-passwords) which allows to save companies' passwords between OpenTTD server restarts.  I've kept it with the game's FreeBSD port, hoping that its original author would upstream it one day, but it never happened, either because he didn't bother or perhaps due to the project's policy to never store clear-text passwords.  Maybe you'll find it useful.

**Comment by danfe** [comment]
Apparently this all had been obsoleted with commits 5706801 and ca4bef1 if anyone was still paying attention.

**Comment by Shituation** [comment]
Maybe... I don't know. But I've stopped playing this game and shot down my server at least 2 years ago.
