### ISSUE TITLE
[Bug]: Town GUI shows amount of Mail produced and transported, even when no Mail cargo type exists in GRF

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#9714]
### Version of OpenTTD

12.1

### Expected result

When using a NewGRF industry set which does not define a [Mail cargotype](https://newgrf-specs.tt-wiki.net/wiki/Action0/Cargos#Substitute_type_and_multiplier_for_town_growth_.2818.2C_19.29) (Action0, Property 18 = 02) or have a cargo in the typical mail cargo ID of 2, the Town GUI does not list the amount of Mail produced and transported last month.

### Actual result

The GUI displays an amount of "Nothing" produced and transported last month. 

(Note: It appears that the game is still calculating mail generation based on the mail multiplier house property, which displays as `<invalid cargo>` when I use the tile inspector on a house. I'll create a separate issue for this).

![mail](https://user-images.githubusercontent.com/55058389/143154721-280e81e9-f2f8-4d94-9626-e079cf5a1652.png)

### Steps to reproduce

1. Use an industry set which doesn't define a Mail cargo, like [Minimalist Industries](https://github.com/2TallTyler/minimalist_industries), attached: [minimalist_industries.zip](https://github.com/OpenTTD/OpenTTD/files/7592015/minimalist_industries.zip).
2. Open the Town GUI for any town.

**Comment by nielsmh** [comment]
As I also commented in the other issue, in my opinion it's the NewGRF that's faulty when it undefines one of the core cargo types the game is built around.

**Comment by TrueBrain** [comment]
Similar to #9715, closing this issue :)
