### ISSUE TITLE
[Bug]: Undetected GPU

### ISSUE THREAD

**Issue by dimaspaf14** [OpenTTD/OpenTTD#9723]
### Version of OpenTTD

12.1

### Expected result

i was opening openttd on my win 7 x86, but it wont detect my gpu & error just pop-up:
"Error with video settings...
... no compatible GPU found. Hardware acceleration disabled"
![op](https://user-images.githubusercontent.com/71385492/143829353-b03b2f11-a953-4b71-bd98-f461b0491398.png)

my GPU is:
SIS Mirage 3

Is my gpu too bad?

### Actual result

run with gpu acc

### Steps to reproduce

1. just open the game
2. then error pop-up

**Comment by nielsmh** [comment]
It looks like your graphics chipset does not support the OpenGL driver version that OpenTTD requires. A quick search points to it only supporting OpenGL 2.0, which is too old.

The game will still play with full graphics quality, the only limitation is that it might not be able to run as fast in fast-forward mode.

**Comment by dimaspaf14** [comment]
Ok thanks, my opengl was 1.1
