### ISSUE TITLE
[Bug]: Multiplayer window doubles when exiting password entering is cancelled

### ISSUE THREAD

**Issue by Azusa257** [OpenTTD/OpenTTD#9736]
### Version of OpenTTD

Version: 12.1 OS: Windows 10

### Expected result

expectation: 
![image](https://user-images.githubusercontent.com/76620903/144865959-f284f8ca-ebf3-4730-b5b9-ee10b6163c52.png)
clicking the cancel button in the password entering phase closes the password entering window and brings you back to the multiplayer server list that you were previously were on.

### Actual result

![image](https://user-images.githubusercontent.com/76620903/144866506-158e02b9-5070-425b-b9b7-354ed27194e8.png)
Clicking Cancel yields another multiplayer server list window, now two of the same window is generated.

### Steps to reproduce

1. Open Multiplayer Menu
2. Join any passworded server
3. When requested for password, click cancel

**Comment by TrueBrain** [comment]
Wait, you don't appreciate double the window? :D In fact, it is even worse:

![image](https://user-images.githubusercontent.com/1663690/144870247-4cab5f7a-551b-4d6f-bd69-9ab90c07f4c3.png)

That is one nice bug you found there! Very cool :) Tnx for reporting!
