### ISSUE TITLE
[Issue]: The visibility of the invitation code in the GAME INFO section is redundant and confusing.

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#9747]
### Version of OpenTTD

since 12.0, Win10

### Expected result

This information is invisible and the window shows only those that are relevant to the player.

### Actual result

Information about the invitation code is visible, although it has no (I don't see) any practical use for it in the case of public servers. For players less familiar with the game, this is another unknown that affects the perception of the game as overly complicated. Theoretically, these codes could be used to find a server, but it seems to be a much worse solution than simply typing in even a fragment of the server name, which is much easier to remember.

### Steps to reproduce

n/a

**Comment by nielsmh** [comment]
I assume you mean in this window:

![image](https://user-images.githubusercontent.com/1062071/145845140-6a9620e8-5992-4f16-80aa-22227a40543e.png)

It's present so you can tell a friend who you want to play with exactly which server you are on. It's necessary on invite-only, since those aren't listed in the public list. It's more direct for public servers since you don't need to search for a possibly long name which could have multiple very similar names in the list.

**Comment by 2TallTyler** [comment]
And it's particularly useful for telling your friends how to join your game using communication methods outside of OpenTTD (text, email, Discord, etc) because it's a much shorter string than many server names. Typing it in directly is easier than scrolling through a long list of servers.

**Comment by LC-Zorg** [comment]
> I assume you mean in this window

No. From what I understood, that button will be in this window, and this information should stay. I thought about information in the server list window.

![Invite code in server list window](https://user-images.githubusercontent.com/67662046/145850295-f1ef8b8b-91a2-4750-af6f-4b331b31bef8.png)
I don't see any use for this info at the moment, so I find it unnecessary and can be intimidating to some players.

> Typing it in directly is easier than scrolling through a long list of servers.

This is precisely related to the second problem I mentioned. :) The function or name of the "Add server" button is very confusing. I never thought I had to paste the code there to find the server.

**Comment by 2TallTyler** [comment]
If I were finding a server with friends, I might still send them the invite code from the server list so they don't have to scroll through the list. I think it is perfectly appropriate to be shown in both the server list and in-game game info GUI.

Your confusion seems to stem from not understanding how to use the invite codes, which I think is better handled in #9746. I vote for "this is not a bug".

**Comment by LordAro** [comment]
Agreed
