### ISSUE TITLE
[Bug]: Nightly stuck at 20211128-master-g802ca4e722

### ISSUE THREAD

**Issue by Limyx826** [OpenTTD/OpenTTD#9752]
Latest master release in openttd is 20211128-master-g802ca4e722, released on 2021-11-28 19:03 UTC. 

This is the version currently listed on the openttd.org site. Obviously it haven't been updated for some time.

**Comment by James103** [comment]
I just checked, and the issue affects Windows, Mac, Linux, and Steam.
After checking https://github.com/OpenTTD/OpenTTD/actions/workflows/release.yml,
it looks like it's not even running the workflow anymore. Why is that and can it be fixed?

**Comment by glx22** [comment]
Fixed, some workflows were auto disabled.
Thanks for the notification :)
