### ISSUE TITLE
[Bug]: Multiplayer Level Ground Tool - Assertion Failed Line 336, network command.cpp

### ISSUE THREAD

**Issue by FilmBoy84** [OpenTTD/OpenTTD#9756]
### Version of OpenTTD

Nightlies 20211216 through 20211219 inclusive

### Expected result

Using the level ground tool in multiplayer should not cause a crash

### Actual result

Using the level ground tool in multiplayer crashes as follows
![image](https://user-images.githubusercontent.com/33913088/146774215-3aaf4282-71ce-4585-b220-cab22b85a83b.png)

### Steps to reproduce

1. Using the 20211216 through 20211219 nightlies, start a new, locally hosted, MP server. I did this on the artic climate
2. Go to the lanscaping tool and attempt to lower or level land with the LEVELLING tool - i did this above the snowline on multiple runs as well as transitional snow tiles but it also seems to occur on none-snow tiles too
3. OpenTTD will immediately crash on release of the mouse button with the above screenshotted error

**Comment by FilmBoy84** [comment]
[openttd.zip](https://github.com/OpenTTD/OpenTTD/files/7745629/openttd.zip)
OpenTTD Config File in use

The GRF list is that of the "North American Set 1830" list in that configuration file but i have replicated with NO NewGRFs loaded also

**Comment by FilmBoy84** [comment]
[OpenTTD.zip](https://github.com/OpenTTD/OpenTTD/files/7745661/OpenTTD.zip)
Crash Files

**Comment by glx22** [comment]
```
 	[Code externe]	
>	openttd.exe!raise(int signum) Ligne 547	C++
 	openttd.exe!abort() Ligne 71	C++
 	openttd.exe!error(const char * s, ...) Ligne 148	C++
 	openttd.exe!NetworkExecuteLocalCommandQueue() Ligne 336	C++
 	openttd.exe!NetworkGameLoop() Ligne 1178	C++
 	openttd.exe!GameLoop() Ligne 1462	C++
 	openttd.exe!VideoDriver::GameLoop() Ligne 37	C++
 	openttd.exe!VideoDriver::GameThread() Ligne 46	C++
 	openttd.exe!StartNewThread::__l3::<lambda>(const char * name, void(*)(VideoDriver *) && F, VideoDriver * && <A_0>) Ligne 65	C++
 	[Code externe]	
 	openttd.exe!thread_start<unsigned int (__cdecl*)(void *),1>(void * const parameter) Ligne 97	C++
 	[Code externe]	
```

**Comment by glx22** [comment]
I can also trigger the assert when building a vehicle.
