### ISSUE TITLE
[Crash]: OpenTTD crashed when using keyboard shortcut for terrain leveling (Q,W,E) while laying tracks

### ISSUE THREAD

**Issue by feix303** [OpenTTD/OpenTTD#9777]
### Version of OpenTTD

12.1, Windows 10

### Steps to reproduce

1. Build stations
2. Lay tracks
3. Have at least one train running and leave train window open
3. Use keyboard shortcut to level terrain (Q,W,E)

### Upload crash files

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/7796514/crash.zip)

**Comment by glx22** [comment]
Not the official 12.1 version so crash dump is useless.

**Comment by James103** [comment]
@feix303 Are you able to reproduce this issue in the **official** 12.1 version of OpenTTD? If so, can you please post the resulting crash files?

**Comment by feix303** [comment]
It does not happen in the official 12.1 version. Thx

**Comment by James103** [comment]
Therefore, this issue can be closed as invalid.
