### ISSUE TITLE
[Bug]: Dedicated server requires useless client_name

### ISSUE THREAD

**Issue by Berbe** [OpenTTD/OpenTTD#9782]
### Version of OpenTTD

12.1

### Expected result

No error message

### Actual result

```
dbg: [net] No "client_name" has been set, using "Unnamed Client" instead. Please set this now using the "name <new name>" command
```

### Steps to reproduce

Start a dedicated server on GNU/Linux (Devuan - Debian-derived - here)

**Comment by ldpl** [comment]
The name itself isn't useless as a dedicated server still creates a client for itself that is shown in the client list to players.
The usefulness of having a client is debatable though.

**Comment by TrueBrain** [comment]
As mentioned, `client_name` isn't optional, not even for servers, how ever weird that sounds :D Going to close this issue :)
