### ISSUE TITLE
The GUI for changing company color scheme is confusing

### ISSUE THREAD

**Issue by TinCanTech** [OpenTTD/OpenTTD#9784]
### Version of OpenTTD

12.1 .deb from official TTD site + Linux Ubuntu 20.04

### Expected result

I want to change company colour scheme during the game.

### Actual result

It is possible to select a colour sceme before starting a game via settings.
Once the game is started it is not possible to change colour scheme.

### Steps to reproduce

Start a new game in v12.1 and try to change company colour scheme.

**Comment by James103** [comment]
Click on the little 'face' in the toolbar to open the company info window.
In the company info window, click "Colour Scheme".
Try changing the Standard Livery from there. Does it update? (It does for me)

The setting you were most likely trying to change in game is "Starting company color", but that only affects new games and when you start a new (human) company in an existing game.

**Comment by TinCanTech** [comment]
Hi, I have tested all sorts of things from single player to LAN game.  Once the game starts it is not possible to select any other colour scheme.  It's like they do not exist in the save game or something.

**Comment by TinCanTech** [comment]
Even starting a brand new game, once the game has started I can no longer change scheme.

**Comment by LordAro** [comment]
As James says, it's not clear what you've tried and what isn't working. See the tutorial for how you change your company colour in-game:

https://wiki.openttd.org/en/Manual/Transport%20company + https://wiki.openttd.org/en/Archive/Manual/Company%20Colours

**Comment by TinCanTech** [comment]
I have done the following:
1. Installed OpenTTD from official`.deb` version 12.1 for Ubuntu 20.04
2. I start a new single player game with no NewGFX loaded.
3. Once the game starts it is not possible to change colour scheme.

Although, I tried lots of other settings, to determine if I had done something wrong, with these 3 basic steps above, it is possible to reproduce the problem.

In the past, I used different colour schemes to label and rank different groups of vehicles.  For example, all my passenger vehicles were white scheme, while my Oil vehicles were Purple.

**Comment by LordAro** [comment]
It is still not clear what you are doing. Which buttons are you pressing, what is not happening? Are you able to select different colour schemes but the vehicles aren't actually changing? Are you not able to select anything at all?

Vehicle groups can have their liveries changed via the group gui ( https://wiki.openttd.org/en/Manual/Vehicle%20groups#using-groups ) but I believe you need a NewGRF that supports that loaded before it is available (this is unchanged)

**Comment by TinCanTech** [comment]
When I open the Company Window and select Colour scheme, the only scheme listed is the one selected at the start of the game, or random.  But no other schemes are listed, there is no drop down list available.

**Comment by nielsmh** [comment]
![image](https://user-images.githubusercontent.com/1062071/148698444-7a84c77a-e306-4c00-89e5-b2d4d01857f0.png)
It does not look like this? How does it look then?

**Comment by TinCanTech** [comment]
![ttdcs](https://user-images.githubusercontent.com/25598447/148698576-ad8e2e6d-407d-4f08-853d-4c38f0c70a70.png)

I cannot select the drop down list because it does not appear.<br>
When I click where it says "Green" nothing happens.

**Comment by nielsmh** [comment]
Which of them? This one is the right one:

![image](https://user-images.githubusercontent.com/1062071/148698662-8e0210c5-23bc-4e1c-904e-3444f129d4c0.png)

**Comment by TinCanTech** [comment]
Oh .. Well, now don't I feel sheepish!

Sorry, yes, now the drop down list appears.

**Comment by nielsmh** [comment]
No keep this open, bad UX is also a bug.

**Comment by TinCanTech** [comment]
I was drawn to the **`bright colours`**.

Summary:
- `heading` selectable-low-light 
- `setting` **un**selectable-HIGH-light

Is _in-human_. I was beyond _confused_, I was _confounded_ ! :smile:

**Comment by andythenorth** [comment]
There are many words that could be applied to company colour UI.  

 'Exists' might be my favourite.

We have no mockups or similar for anything better though, and certain behaviours are now ingrained and expected, so https://xkcd.com/1172/ will apply as usual.

**Comment by 2TallTyler** [comment]
Resolved by #11617. 🙂
