### ISSUE TITLE
[Bug]: v12.1 All off-shore oil railway tracks and station deleted

### ISSUE THREAD

**Issue by TinCanTech** [OpenTTD/OpenTTD#9785]
### Version of OpenTTD

v12.1 + Linux ubuntu 20.04

### Expected result

Load complete game.

### Actual result

All off-shore oil railway track and stations deleted.<br>
**Edit**: All oil railway track and stations deleted, off-shore or not.<br>
All Refineries have been placed in different locations.

### Steps to reproduce

Load a game with oil from a previous version (eg. 10.3), the oil tracks and stations will be deleted.

**Comment by TinCanTech** [comment]
In fact, I find all sorts of parts of my network have mysteriously vanished.

**Comment by LordAro** [comment]
Please provide a savegame that can be tested

**Comment by TinCanTech** [comment]
I realised, I was loading the wrong file.
