### ISSUE TITLE
[Bug]: city name bug

### ISSUE THREAD

**Issue by predo2810** [OpenTTD/OpenTTD#9796]
### Version of OpenTTD

12.1 windows 10

### Expected result

huh, i don't know if this is a bug but it's a wrong name, the Latino-American name Barcelona is not a name from the continent...
![image](https://user-images.githubusercontent.com/93801931/150439887-344c4e02-83e0-4a0f-9c1d-e062f03a26b4.png)

### Actual result

Barcelona is on Spain not on Latino-America
![image](https://user-images.githubusercontent.com/93801931/150439971-035643b9-7044-4485-ab62-0014f4cdf2cc.png)

sorry if this is not a bug

(and sorry for my english if there's some errors (i'm from brazil))

### Steps to reproduce

[city bug.zip](https://github.com/OpenTTD/OpenTTD/files/7909185/city.bug.zip)

**Comment by stormcone** [comment]
Looks like there are more than one Barcelona, for example:
https://www.openstreetmap.org/node/333655403
https://www.openstreetmap.org/relation/301130

**Comment by predo2810** [comment]
> Looks like there are more than one Barcelona, for example: https://www.openstreetmap.org/node/333655403 https://www.openstreetmap.org/relation/301130

oh man, sorry, i didin't see it :/

next time i'll try to search more...

thanks for the answer! :)
