### ISSUE TITLE
[Bug]: "Highest Resolution Sprites to use" feature causes failure to load any visible graphics

### ISSUE THREAD

**Issue by PikkaBird** [OpenTTD/OpenTTD#9804]
### Version of OpenTTD

12.1

### Expected result

This feature should downscale 32bpp extra zoom sprites to match the desired zoom level, instead of displaying the 8bpp normal zoom fallback sprite.

### Actual result

As per today's discussion on Discord, using the feature "allow limiting zoom level of NewGRF-provided sprites #8604" with 32bpp extra zoom NewGRFs active frequently results in no visible sprites at all being shown, as it displays the 8bpp normal zoom fallback sprite, which in most cases is a blank or otherwise unsuitable placeholder.

My understanding is that the reason 32bpp sets don't normally show the placeholder sprites at normal zoom is that 32bpp sprites are always preferred if available. So the simple solution is to extend that logic to the zoom level limitation feature - prefer 32bpp sprites if they are provided, even if they are higher zoom level than the limited level requested.

A more thorough solution, which would produce the result most players would expect, would be to downscale/pixellate any 32bpp extra zoom sprites to the limited zoom level requested, if no explicit lower zoom 32bpp sprites are provided by the NewGRF.

### Steps to reproduce

- Start a game with a 32bpp extra zoom NewGRF loaded (original report was with CZTR Ground set, which is particularly dramatic).
- In the game settings, set "Highest Resolution Sprites to use" to 1x.
- Witness the game break.

**Comment by PikkaBird** [comment]
![Untitled1](https://user-images.githubusercontent.com/39507755/151762531-ae660bf8-ac16-410f-99a5-d053e59c5018.png)

**Comment by TrueBrain** [comment]
Why does that look like a Bob Ross picture?

<sub>(sorry, there is no actual content to this reply, besides this pure artistic observation :D)

**Comment by JGRennison** [comment]
I had a go at resolving this in https://github.com/JGRennison/OpenTTD-patches/commit/309f1b47d29a377e24dd75071848d67d5c0c23f0

Zoom levels are only removed in the case where one or more suitable zoom levels using the same colour mode remain available.
This appears to resolve the issue with extra-zoom GRFs, whilst still allowing the intended fallback functionality for those GRFs which define multiple zoom levels.

**Comment by LordAro** [comment]
Seems like a reasonable fix, care to PR it? Wonder if it might also resolve #9876 ?

**Comment by JGRennison** [comment]
I'll see what I can do on that.

It won't do anything about #9876 though. That is an unrelated issue.
