### ISSUE TITLE
[Bug]: Error message when trying to order articulated vehicles to non-drive-thru stop is unclear

### ISSUE THREAD

**Issue by spyderr7** [OpenTTD/OpenTTD#9807]
### Version of OpenTTD

12.1

### Expected result

I should be able to send a bus using GO TO to a station, instead...

### Actual result

When sending a bus to a station that is attached to another station (like train station) I get the message: Can't insert new order ... vehicle can't go to that station. 
It happend few times already. 

![image](https://user-images.githubusercontent.com/4007992/162501993-268bff8a-36a2-4e0d-932a-88ee14e4fd8b.png)

Any tips on how to get around the error? 

### Steps to reproduce

[SAVE](https://drive.google.com/file/d/1vRI8pLWzYLLOQHdfElc5TLVc7Sy384nz/view?usp=sharing)

1. Try sending bus number 58 to a station Strzebielin Wiekszy Woods. 
2. You'll gen an error message.

**Comment by James103** [comment]
The bus is likely articulated. Can you please build a drive-through road stop, connect it to the road network and the rest of the station, then order the bus to stop there?

**Comment by LordAro** [comment]
If James' assumption is correct, we could still improve the error message in this scenario

**Comment by James103** [comment]
I would suggest the following messages (subject to change):

When attempting to order an articulated vehicle to a bay stop:
```
Can't insert new order
Vehicle can only stop at drive-through stops
```

When attempting to order a bus to a truck stop:
```
Can't insert new order
Vehicle can only stop at bus stops
```

When attempting to order a truck to a bus stop:
```
Can't insert new order
Vehicle can only stop at truck stops
```

**Comment by LordAro** [comment]
I would suggest "articulated vehicles can only use drive-through stops", to save adding lots of strings :)

**Comment by spyderr7** [comment]
Yes, non artuculated bus works! I wouldn't think of this in a million years. Thank you!

**Comment by James103** [comment]
JGRPP fixes this issue in this commit: https://github.com/JGRennison/OpenTTD-patches/commit/d3efa2afe043fab82eadb21548fb50fbd65e4c61
