### ISSUE TITLE
[Bug]: 'Rebuilding' a through road stop costs money.

### ISSUE THREAD

**Issue by zephyris** [OpenTTD/OpenTTD#9810]
### Version of OpenTTD

12.1 Windows 10

### Expected result

"Rebuilding" a through road stop should not cost money, ie. clicking with the through stop build tool on an existing through road stop should not have any effect. This is the existing behaviour for any other build tool, if the object is already built re-clicking with the build tool has no effect.

### Actual result

"Rebuilding" a through road stop costs the standard build cost for building on an existing road tile. This behaviour happens when building a bus or lorry road stop.

### Steps to reproduce

Replicate by building a through road station, then click again on the same tile and it charges the road station cost.

**Comment by PikkaBird** [comment]
Overbuilding railway stations and standard road stops also costs money. Overbuilding docks and airports doesn't work.

Should overbuilding railway stations also be free? Probably, yes.

**Comment by zephyris** [comment]
I thought it'd be useful to summarise the behaviour of different tools. Overall the behaviour of different build tools on overbuilding is somewhat inconsistent, with somewhat inconsistent error messages when it fails:

canal, aqueduct: Fails "... already built"
lock, ship depot: Fails "Building must be demolished first"
dock: Fails "Must demolish dock first"

airports: Fails "Must demolish airport first"

purchase land: Fails "... you already own it!"
tree: Fails, once tile full "... tree already here."
sign: Allowed [Leading to multiple signs on one tile. NB. Cancel does not cancel placement of sign, just adjustment from default text.]
level land: Fails "... already flat."
demolish: Allowed [No cost if already clear]

road: Fails "... already built"
road depot: Fails "Building must be demolished first"
bus/lorry stop: Allowed [Additional cost on rebuild. NB. Unlike rail stations, overbuilding a through stop in the other orientation is not allowed, "...road facing in the wrong direction"]
bridge: Allowed [Triggers type reselection, no direct cost. NB. No explicit indication that this is an upgrade, nor a cancel button, just default "X".]
tunnel: Fails "Must demolish tunnel first"
upgrade: Fails "No suitable road"

rail: Fails "...already built"
rail depot: Fails "Building must be demolished first"
station: Allowed [Additional cost on rebuild. NB. Unlike road stops, overbuilding in the other orientation changes the underlying rail]
waypoints: Allowed [Additional cost on rebuild. NB. Unlike through road stops or stations, doesn't come with rail & define direction]
signals: N/A [Changes direction of one-way signals, no cost]
upgrade: Fails [No suitable railway track]
