### ISSUE TITLE
[Bug]: Selling NewGRF ships requires me to drag them to the wrong place

### ISSUE THREAD

**Issue by DonaldDuck313** [OpenTTD/OpenTTD#9811]
### Version of OpenTTD

12.1, Windows 11

### Expected result

To sell a ship, I should be able to just drag it to the sell button in the depot window, no matter if it's an original ship or a NewGRF ship.

### Actual result

When I try to drag a NewGRF ship to the sell button, nothing happens. To sell it, I need to drag it to a random place in the depot window, see attached video.

https://user-images.githubusercontent.com/40611243/152973239-5ad58593-0c82-45bf-ae5f-0cd9c56e86a6.mp4

### Steps to reproduce

1. Download the "Sailing Ships" NewGRF
2. Start a game with the "Sailing Ships" NewGRF enabled, preferably around 1900 so that the ships are available.
3. Buy a sailing ship.
4. Try selling it by dragging it and you will notice the bug.

**Comment by glx22** [comment]
Could be a bug in the newgrf itself, like incorrect value in some property (but I didn't check).

**Comment by frosch123** [comment]
The issue is visible in the first split second of the video:
On mouse-down the ship sprite is attached to the cursor. You can see how far away the sprite is from the actual mouse position.

The position of the "action point" in the sprite is defined by the NewGRF in the sprite offset.

So, this is a bug in the NewGRF.

**Comment by LordAro** [comment]
In particular, notice where the ship is when the button is depressed:
![image](https://user-images.githubusercontent.com/4007992/153043060-0946ca2d-6480-4c98-b4aa-950c50cc9129.png)

**Comment by frosch123** [comment]
Looks like 9156d7bf346b77c broke this for ships and aircraft.

**Comment by frosch123** [comment]
#9812 fixes this for FISH and other sets.
But "Sailing ships" has indeed broken offsets in the NewGRF.
