### ISSUE TITLE
[Bug]: Scroll down main settings window issue on smaller resolutions

### ISSUE THREAD

**Issue by danilka7** [OpenTTD/OpenTTD#9815]
### Version of OpenTTD

12.1 Windows 10

### Expected result

I should see whole popup with main settings. But I can see just part which can be placed inside window (no scrolling ability)

### Actual result

![main_settings_scroll_down_issue](https://user-images.githubusercontent.com/19391572/153661973-c76bb8d4-d4f5-45cf-9ce5-4b5b44c4c1f8.png)

### Steps to reproduce

1. Start game
2. Open "Settings"

**Comment by 2TallTyler** [comment]
Expanded with details about new variable interface scaling in #10170. Still needs to be fixed.
