### ISSUE TITLE
[Bug]: Destroying road when local authority doesn't allow it gives the wrong error message

### ISSUE THREAD

**Issue by DonaldDuck313** [OpenTTD/OpenTTD#9820]
### Version of OpenTTD

12.1, Windows 11

### Expected result

When I try to delete a road but the local authority doesn't allow it, I should get an error message saying "Local authority doesn't allow this", no matter what button I use.

### Actual result

When I try to delete a road using the  ![](https://user-images.githubusercontent.com/40611243/154799590-e1dfc2df-0832-4b65-9cfe-ff5b8b2f41c4.png) button but the local authority doesn't allow it, I get an error message saying "there is no road". If I use the ![](https://user-images.githubusercontent.com/40611243/154799844-f0c04fb6-6b61-466e-b283-90620432b9d7.png) button instead, it gives the correct error message.

### Steps to reproduce

1. Make the local authority of a town mad at you by destroying buildings, trees, etc.
2. Try to destroy a road owned by that town by using the ![](https://user-images.githubusercontent.com/40611243/154799590-e1dfc2df-0832-4b65-9cfe-ff5b8b2f41c4.png) button.
3. You will get an error message saying "there is no road", see video below.

https://user-images.githubusercontent.com/40611243/154799894-1b63124a-1fbb-4a2f-99c5-b745d9988032.mp4

**Comment by glx22** [comment]
I think it shows "there is no road" because there is no road on the last tile of your selection.

**Comment by 2TallTyler** [comment]
> I think it shows "there is no road" because there is no road on the last tile of your selection.

I can confirm this. I get the proper error when I only try to remove road tiles.

![OpenTTD 12 1 3_10_2022 2_31_18 PM](https://user-images.githubusercontent.com/55058389/157758520-4951c2d9-bbae-4e1c-aca9-b9c9a881c470.png)

**Comment by 2TallTyler** [comment]
Related: #9034

**Comment by TrueBrain** [comment]
Been throwing coins all day what to do with this ticket.

Basically, in the use-case presented there are two errors over the full stretch:

- No road to remove
- Not allowed to remove the road

So the toss-up becomes: which of these two errors should be presented to the user. Currently it is what-ever the most northern tile throws. Very tempted to always make "not allowed" win from any other error .. which is already the case for ownership.
