### ISSUE TITLE
[Bug]: terraforming away a river does not include cost of removal of river

### ISSUE THREAD

**Issue by whydoievenneedthis** [OpenTTD/OpenTTD#9822]
### Version of OpenTTD

nightly from 2022.02.10, windows 10

### Expected result

When a terraformation action results in a river segment to be deleted, the cost should reflect the deletion of the river as well.

### Actual result

The cost only considers the terraformation action, not the river removal. This was working fine in the 12.1 stable release.

### Steps to reproduce

1. Find a river segment.
2. Raise a corner of land right next to it.

![image](https://user-images.githubusercontent.com/87586203/155065931-b7ec641d-2217-4c0e-84b6-cd8217575408.png)
![image](https://user-images.githubusercontent.com/87586203/155065943-67d34671-41bd-4d63-a176-8e3169c2b8eb.png)
![image](https://user-images.githubusercontent.com/87586203/155065952-5e74ce6c-115f-401a-b91f-e62dba11592b.png)

3. For bonus points, find another river segment and shift-click to only calculate the price of the action. Spoiler: the to-be-affected river segments are removed :)

![image](https://user-images.githubusercontent.com/87586203/155137767-6499f675-bb78-446d-9dee-434962fe13b4.png)
![image](https://user-images.githubusercontent.com/87586203/155137784-3a617640-5d11-46f9-96ad-295a78bc63cc.png)

**Comment by James103** [comment]
This may cause desyncs in multiplayer, but I can't test that at the moment.

**Comment by nielsmh** [comment]
https://github.com/OpenTTD/OpenTTD/commit/e740c24eb7a90bc771f5976d64d80639ee7576e5#diff-2435a884057fcf692871728ce3d0726330c4120b00d7b07514eaa0ec310b0fd5R1385-R1387

This commit accidentally replaces the flags for terraform commands on water tiles with just DC_EXEC.
