### ISSUE TITLE
[Bug]: Can't start a local server and connect to it on the same machine

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#9823]
### Version of OpenTTD

Nightly 20220210 and 20211127 and JGRPP 0.46.x

### Expected result

One should be able to start a local server for a game such as OpenTTD and connect to it on the same machine.
For example, on a machine with IPv6, when using old versions of OpenTTD (i.e. 1.11.x and earlier), starting a server with `openttd -D ::1` and connecting a client to it with `connect ::1` worked properly.

What should I do so that I can continue to connect a local client to a server that's on the same computer (not just network) as the client?

### Actual result

When running the console commands listed below, "Connection to the server timed out and was refused" is logged on the client. For `connect ::1`, "Failed to resolve DNS for ::1" is also logged, while the others merely log "Timeout while connecting to ..."

As for the server logs,
When started with `openttd -D ::1` (which is what used to work):
```
...
dbg: [net] No "server_name" has been set, using "Unnamed Server" instead. Please set this now using the "server_name <new name>" command
dbg: [net] Initializing UDP listeners
dbg: [net] Initializing UDP listeners
dbg: [net] getaddrinfo for hostname ":", port 1, address family either IPv4 or IPv6 and socket type tcp failed: No such host is known.
dbg: [net] Could not start network: could not create listening socket
dbg: [net] Generating map, please wait...
...
```

When started with `openttd -D` (without `::1`)
```
...
dbg: [net] No "server_name" has been set, using "Unnamed Server" instead. Please set this now using the "server_name <new name>" command
dbg: [net] Initializing UDP listeners
dbg: [net] Initializing UDP listeners
dbg: [net] Listening on [::]:1 (IPv6)
dbg: [net] Listening on 0.0.0.0:1 (IPv4)
dbg: [net] Listening on [::]:1 (IPv6)
dbg: [net] Listening on 0.0.0.0:1 (IPv4)
dbg: [net] Network revision name: 20211127-master-g6953df7b5e
dbg: [net] Generating map, please wait...
...
```

As client trying to connect to both servers, all of the following console commands fail to connect properly, while the first one used to work in older versions:
```mcfunction
connect ::1
connect ::1:3979
connect 192.168.0.1
connect 192.168.0.0
connect 127.0.0.1
connect localhost
```

### Steps to reproduce

1. From a command line, start two OpenTTD servers with
```
openttd -D ::1
openttd -D
```
2. Observe the log in the console windows of both servers.
3. Start an OpenTTD client with the same version as both servers above.
4. As client, run the following commands described above.

**Comment by glx22** [comment]
Try with `openttd -D [::1]`

**Comment by James103** [comment]
> Try with `openttd -D [::1]`.

That does not work for me.

Server log:
```
...
dbg: [net] No "server_name" has been set, using "Unnamed Server" instead. Please set this now using the "server_name <new name>" command
dbg: [net] Initializing UDP listeners
dbg: [net] Initializing UDP listeners
dbg: [net] Listening on [::1]:1 (IPv6)
dbg: [net] Listening on [::1]:1 (IPv6)
dbg: [net] Network revision name: 20220210-master-g41c40f130b
dbg: [net] Generating map, please wait...
...
```

Client console log:
```
...
> connect [::1]
Connection to the server timed out or was refused
dbg: [net] Timeout while connecting to [::1]:3979
> connect localhost
Connection to the server timed out or was refused
dbg: [net] Timeout while connecting to localhost:3979
> connect ::1
Connection to the server timed out or was refused
dbg: [net] Failed to resolve DNS for ::1
...
```

**Comment by glx22** [comment]
For me `openttd -D [::1]` works fine and listen on `[::1]:3979`, so somehow you have `network.server_port` set to 1

**Comment by James103** [comment]
> For me `openttd -D [::1]` works fine and listen on `[::1]:3979`, so somehow you have `network.server_port` set to 1

Resetting `network.server_port` fixed that part of the issue.

**Comment by glx22** [comment]
Format for IPv6 always been `[xxxx::...::xxxx]:<port>`. Pre <12.0 it seems it also accepted `xxxx::...::xxxx` but would not parse `::xxxx::...::xxxx:<port>` correctly

(See https://github.com/OpenTTD/OpenTTD/commit/3d91eee919de2ecec11102b4ba1f4caafa4d7a83#diff-a9f60d67639dc3c6cc2a43b2e6cc5e74402f3dd461f35b6d70ce0b80e72e7333L462)

**Comment by LordAro** [comment]
Working as intended. Previous behaviour was unexpected

**Comment by James103** [comment]
For anyone that runs into this in the future, after starting the server with `openttd -D [::1]`, the client must also connect with `connect [::1]`, not `connect ::1`.
