### ISSUE TITLE
[Bug]: Latest nightly is 2 commits (9 days) behind latest commit to master.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#9824]
### Version of OpenTTD

Latest nightly: 41c40f130b907e73475f41706510a54a519b78e4

### Expected result

The text quoted in 'Actual Result' should say:
"Latest master release in openttd is 20220219-master-g36bee83864, released on 2022-02-19 XX:XX UTC."
where XX:XX is a placeholder time parameter.

### Actual result

From https://www.openttd.org/downloads/openttd-nightlies/latest:
"Latest master release in openttd is 20220210-master-g41c40f130b, released on 2022-02-11 19:13 UTC."
As of the time of writing, this is 2 commits (9 days) behind the latest commit to master.

### Steps to reproduce

1. Check `openttd.org` and `cdn.openttd.org` for updates.
2. Notice that the latest version is nightly 2022-02-10.
3. Check that the latest commit to master is 2022-02-19 as of the time of writing.
4. Check that https://github.com/OpenTTD/OpenTTD/actions/workflows/release.yml does not have any workflow results since 2022-02-11 as of the time of writing.

**Comment by glx22** [comment]
Should be fixed for tonight, thanks for the report.
