### ISSUE TITLE
[Feature]: Disable terraforming until X years passed for a company.

### ISSUE THREAD

**Issue by Shituation** [OpenTTD/OpenTTD#9847]
### Version of OpenTTD

12.1 / Windows 10

### Expected result

Delaying terraforming for new companies should stop random and free trolling on multiplayer games.
Make a config rule (like auto clean companies) that limit terraforming tools until X years have passed for that company, effectively stopping random trolling.
A reasonable time could be 3 in game years.

### Actual result

Trolls join a game and use the initial money + loans to make chaos on other players (mostly water based operations), then disconnect.

### Steps to reproduce

play on multiplayer.

**Comment by same-f** [comment]
Can't this issue resolve changes in terraforming prices?

**Comment by James103** [comment]
> Can't this issue resolve changes in terraforming prices?

Prices for terraforming (and most of everything else) can be changed using the BaseCosts NewGRF and the following steps:
1. Download and install the NewGRF "BaseCosts 5.0".
2. In NewGRF Settings, activate that NewGRF and configure the parameters to your liking. For example, to make terraforming cost £3,000 per unit before inflation, set the "raise/lower land" parameter to 16x. To make clearing water cost £240K per tile before inflation, set the "clear water" parameter to 32x. The more it costs to do landscaping, the less landscaping a griefer will be able to do.
3. Start a new game.

To increase base costs in a running game (note that this is technically unsupported but works for me so far):
1. Execute the console command: `set newgrf_developer_tools true`
2. Download and install the NewGRF "BaseCosts 5.0".
3. In NewGRF Settings, activate the NewGRF and configure the parameters to your liking. For this scenario, I would recommend increasing the cost to terraform and clear water to levels that would still be reasonable for an established company with several years' tenure, but not for a new company.
4. Click "Apply Changes".
5. Read and accept the warning.
6. The new base costs should now be in effect.

**Comment by same-f** [comment]
> > Can't this issue resolve changes in terraforming prices?
> 
> 
> 
> Prices for terraforming (and most of everything else) can be changed using the BaseCosts NewGRF and the following steps:
> 
> 1. Download and install the NewGRF "BaseCosts 5.0".
> 
> 2. In NewGRF Settings, activate that NewGRF and configure the parameters to your liking. For example, to make terraforming cost £3,000 per unit before inflation, set the "raise/lower land" parameter to 16x. To make clearing water cost £240K per tile before inflation, set the "clear water" parameter to 32x. The more it costs to do landscaping, the less landscaping a griefer will be able to do.
> 
> 3. Start a new game.
> 
> 
> 
> To increase base costs in a running game (note that this is technically unsupported but works for me so far):
> 
> 1. Execute the console command: `set newgrf_developer_tools true`
> 
> 2. Download and install the NewGRF "BaseCosts 5.0".
> 
> 3. In NewGRF Settings, activate the NewGRF and configure the parameters to your liking. For this scenario, I would recommend increasing the cost to terraform and clear water to levels that would still be reasonable for an established company with several years' tenure, but not for a new company.
> 
> 4. Click "Apply Changes".
> 
> 5. Read and accept the warning.
> 
> 6. The new base costs should now be in effect.

I know how to do it. I just clarified, isn't it possible to solve the problem put forward by the author by simpler methods than changing the code

**Comment by masterofobzene** [comment]
+1 to this. 
I'm tired of kids.

**Comment by LordAro** [comment]
Nice idea, but to keep our issue tracker more readable we avoid suggestions here - PRs accepted!

**Comment by Shituation** [comment]
Ok, thank you for nothing.
