### ISSUE TITLE
[Bug]: Transparency only partially working on diamond and gold mines

### ISSUE THREAD

**Issue by Fabian272** [OpenTTD/OpenTTD#9851]
### Version of OpenTTD

1.12.2, Windows 10

### Expected result

The mines should turn transparent / invisible like any other industry building when enabling the options for it.

### Actual result

Only specific parts of the mines get turned transparent when enabling transparency for industries. They only turn partly invisible when enabling the option for it as well.
![diamondmine](https://user-images.githubusercontent.com/92162379/163049914-1b00640c-c857-4673-a865-7c47b840e58b.png)
![goldmine](https://user-images.githubusercontent.com/92162379/163050686-f69fcf30-5e83-4768-b8d2-2dbf261f17b0.png)

### Steps to reproduce

1. Start or load a game in a sub-tropic or sub-arctic
2. Locate a gold or diamond mine
3. Enable transparency / transparency + invisibility for Industries
4. Only parts of them go transparent / invisible

**Comment by PikkaBird** [comment]
Those particular industry tiles are coded as ground tiles only, rather than a building on a ground tile. This is an inconsistency which goes back to the original Transport Tycoon Deluxe.

**Comment by LordAro** [comment]
Yeah, working as intended, if strange - just part of how the baseset works
