### ISSUE TITLE
[Crash]: Crash on save on macOS

### ISSUE THREAD

**Issue by rafalkrupinski** [OpenTTD/OpenTTD#9856]
### Version of OpenTTD

12.1, macos, brew

### Steps to reproduce

1. open save dialog
2. hit [enter] (only crashes when hitting [enter])

### Upload crash files

[report.zip](https://github.com/OpenTTD/OpenTTD/files/8498086/report.zip)

**Comment by Bouke** [comment]
Are you able to reproduce this issue? Brew doesn't allow me to install previous versions. I just tried installing 12.2 using brew and the steps to reproduce don't cause a crash. By [enter], do you mean the key labeled [return] or are you using some special keyboard that could be interfering?

**Comment by rafalkrupinski** [comment]
II had two version installed - 12.2 from brew and 11.1 not sure from where :)
brew was reporting 12.2 but the welcome screen 11.1.
I also removed the openttd formula and installed the cask and it's working now.
Thank you!
