### ISSUE TITLE
[Bug]: Aircraft with Full load ANY cargo waits till full load of ALL cargo

### ISSUE THREAD

**Issue by andrew-chiz-muzychuk** [OpenTTD/OpenTTD#9859]
### Version of OpenTTD

12.2 MacOS

### Expected result

With setting `Full load ANY cargo` I expect an aircraft to load 10 mails with 10 mails as max capacity (while not all passangers are loaded) and aircraft flying to a next point.

### Actual result

With setting `Full load ANY cargo` an aircraft waits for ALL (passangers and mail) cargos to be loaded.

### Steps to reproduce

1. Have 2 airports
2. Have an aircraft with two destinations
3. Set `Full load any cargo` as for loading behavior
4. Make aircraft load on the destination with this setting

Video - https://youtu.be/94DJZ-CND1U

**Comment by James103** [comment]
Caused by this if-block:
https://github.com/OpenTTD/OpenTTD/blob/bcf26f8ec050a951ea81622f6feca0d6f8ba21d1/src/economy.cpp#L1850-L1859

In other words: if the aircraft can carry Passengers, "full load any cargo" and "full load any cargo" are effectively one and the same.

**Comment by andrew-chiz-muzychuk** [comment]
Is it intended bahavior? Why just not remove the `Full load ANY cargo` menu item for aircrafts? It is misleading.

**Comment by frosch123** [comment]
The code piece quoted by James answers the question:
https://github.com/OpenTTD/OpenTTD/blob/bcf26f8ec050a951ea81622f6feca0d6f8ba21d1/src/economy.cpp#L1851-L1852

* Yes, the behavior is intended.
* No, "full load all" and "full load any" do not do the same.

The assumption is that noone would ever want a plane to only load mail and no passengers.
So "full load all" waits for both passengers and mail, and "full load any" only waits for passenger.

**Comment by andrew-chiz-muzychuk** [comment]
Thanks!
I guess this one can be closed as "Not a bug".
