### ISSUE TITLE
Autosave on server reset/disconnection

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#986]
**_bilbo_ opened the ticket and wrote:**

> I think it may be worthy to have option for autosave to be done when there is server disconnection (server crashes, connection losed, desync ... it may be used to finish playing the game offline later or maybe investigate reasons of disconnecting)
> 
> Also, option for autosave on server reset (with the state "just before the reset") would be useful too (if you want to save your company "for archival purposes").
> 
> This way you could turn off the monthly/yearly autosave and you will still have the "last moment" save when something went bad with server or network connection (though this will not save you from client crash, but thats what periodical autosaves are good for ...)

**Reported version**: _0.5.2_
**Operating system**: _All_

---

**Comment by nielsmh** [comment]
Fixed by #6796
