### ISSUE TITLE
[Bug]: Translation Error

### ISSUE THREAD

**Issue by laitingsheng** [OpenTTD/OpenTTD#9864]
### Version of OpenTTD

12.2 Windows 11

### Expected result

In this line

https://github.com/OpenTTD/OpenTTD/blame/master/src/lang/simplified_chinese.txt#L929

The current translated text really means "Australian Shilling" but not "Austrian Shilling". I don't know why this line is correct, though:

https://github.com/OpenTTD/OpenTTD/blob/master/src/lang/traditional_chinese.txt#L917

### Actual result

"Austrian Shilling" should be translated into "奥地利先令" in Simplified Chinese.

### Steps to reproduce

No step is required. It's just a translation error.

**Comment by nielsmh** [comment]
Translations are handled on the web translator.
(See https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#using-the-issue-tracker=)
You can either sign up as translator yourself to directly help improving the translations, or contact one of the existing translators.

**Comment by WenSimEHRP** [comment]
@laitingsheng Good news, that line was fixed several months ago :-)
