### ISSUE TITLE
[Bug]: Audio/music continues to play after the game crashes

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#9894]
### Version of OpenTTD

20220515-master-gfd1aa154f4 on WIndows 10

### Expected result

Audio/music should stop playing when the game crashes.

### Actual result

Audio/music continues playing when the game crashes.

### Steps to reproduce

1. Start playing music.
2. Crash the game (e.g. by following the reproduction steps in #9545).
3. Music continues to play (through the end of the current song).

**Comment by 2TallTyler** [comment]
How do you crash the game?

**Comment by James103** [comment]
The specific crash that I triggered was first reported in #9545.

**Comment by nielsmh** [comment]
Can we just call this one an unplanned feature instead?

**Comment by LordAro** [comment]
As far as I'm aware, this is pretty much entirely dependent on the audio driver, which we obviously can't do anything about. Very much doubt, in the case of crashing, we have any real control over the audio subsystem anyway
