### ISSUE TITLE
[Feature]: Demo of browser version on openttd.org

### ISSUE THREAD

**Issue by diekmann** [OpenTTD/OpenTTD#9896]
### Version of OpenTTD

12

### Expected result

Why is https://www.openttd.org/ not providing a browser version?

I know that the browser version is somewhat incomplete, but we could flag this as an unstable demo on openttd.org.

### Actual result

The browser version is not mentioned on openttd.org and finding out more about the browser version of OpenTTD is hard for users who don't look at sources on GitHub.

### Steps to reproduce

I just learned that OpenTTD runs in the browser and can be published to GitHub Pages via GitHub workflows automatically. I also learned that this process is already (mostly) documented. I created a demo repo which pulls the OpenTTD sources, compiles them to the browser, and publishes them to GitHub pages. Everything happens on a normal push via GitHub actions: https://github.com/diekmann/openttd-web-publishing

Can we have a link to such a browser-based build (but via the official openttd repo) on openttd.org?

**Comment by TrueBrain** [comment]
Currently the browser-version (which is not a demo, it is the full-version :P ) is not ready for the general public. It is lacking networking, saves could be lost when a browser decides to purge the files, and it is still rough around the edges in regards to gameplay.

This is why we currently only use it for previewing PRs, and don't put it on our main website :) If someone (hint hint) would put in the time to actually polish it, and make it ready for the general public, we for sure will put a "Play Now" button on the main website :D

You up for it? :)

**Comment by diekmann** [comment]
Hey Patric, thanks for the quick reply. My apologies for calling it a demo. It's exactly those cases you describe which made me mentally label this build as a demo. With those warnings you mentioned, would the current version we have be good enough as a "web demo" for the main website?

I don't think I have the capacity currently to improve the browser version. Yet, the project does sound very interesting.

While the browser version is not good enough for the general public, would you accept a GitHub workflow which automatically publishes a build to GitHub pages, not advertised on openttd.org?
If you like this idea, there is one sample workflow on https://github.com/diekmann/openttd-web-publishing ;-) Since debugging GitHub workflows can be super hard for folks who don't own the repo, it would be very convenient if some owner of the OpenTTD repo decides to pull that in ;-)

**Comment by TrueBrain** [comment]
It was worth a shot ;)

You are always free to publish it on your own GitHub Pages ofc; you are not the first doing this :) But we cannot link to it, as we would get many support questions we are not ready to deal with yet :) Even if we nick it "demo" :P So I am sorry, we cannot pull that in just yet. But who knows some day soon :D

Either way, I do appreciate the interest. Going to close this issue now, as we tend not to keep feature requests in our bug-tracker. If you ever find some free time on your hands, you know where to find us :D
