### ISSUE TITLE
[Crash]: order backup

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#9908]
### Version of OpenTTD

20220531-master-g9fca8af586, windows 10

### Steps to reproduce

1. start openttd
2. click multiplayer
3. click start server
4. click new game
5. build a depot
6. build a vehicle in that depot (this is vehicle 1)
7. give it orders
8. clone vehicle 1 (vehicle 2 is created)
9. sell vehicle 2
10. important: leave the depot window open
11. on the online players window, join spectators
12. delete the company where you built the vehicles

crash!

### Upload crash files

[crash20220601104256.zip](https://github.com/OpenTTD/OpenTTD/files/8813369/crash20220601104256.zip)

**Comment by glx22** [comment]
Similar assert happens in 12.2 (custom build with asserts enabled).
