### ISSUE TITLE
[Bug]: error message not being displayed

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#9909]
### Version of OpenTTD

20220531-master-g9fca8af586, windows 10

### Expected result

Error message being displayed telling I'm short on cash.

Screenshot as of OpenTTD 12.2:
![Unnamed, 1935-01-11](https://user-images.githubusercontent.com/43006711/171391809-f0b76f70-d7a0-475f-a5eb-48781cbd1bed.png)

### Actual result

Nothing happens, no error message is displayed

### Steps to reproduce

[purchase 25% shares on admiralai.zip](https://github.com/OpenTTD/OpenTTD/files/8813545/purchase.25.shares.on.admiralai.zip)
1. load savegame
2. open AdmiralAI company information
3. try to buy 25% shares

**Comment by glx22** [comment]
Ok, found the issue.
`Post()` on https://github.com/OpenTTD/OpenTTD/blob/master/src/company_gui.cpp#L2642 is translated to https://github.com/OpenTTD/OpenTTD/blob/master/src/command_func.h#L195 while it should use https://github.com/OpenTTD/OpenTTD/blob/master/src/command_func.h#L183.
