### ISSUE TITLE
[Bug]: Industries are closed without any warning

### ISSUE THREAD

**Issue by LC-Zorg** [OpenTTD/OpenTTD#9919]
### Version of OpenTTD

12.2 (old bug)

### Expected result

A few months before the closure of the enterprise, information about the threat of closure appears in the enterprise window. Delivery of any cargo at this time is secures the enterprise.
Thanks to this, player knows what to expect. If he has made the decision to serve this enterprise and started building the line, he knows he should hurry up. However, if he is looking for the right enterprise, he can avoid a wrong choice.

![Window of industry at risk of closure v1 4](https://user-images.githubusercontent.com/67662046/172730455-27c9d242-9500-4778-91d7-706b6f79fad5.png)

Alternative: Building a station next to the enterprise resets the time to closure - the game, before deciding to close, checks if there are stations nearby and what are their construction dates.

### Actual result

Processing enterprises are closed without any warnings. The information that appears is about a fait accompli which player cannot do anything about. Moreover, when there are many other messages, information about a planned closure appears with a long delay or not at all.

The closure of an enterprise very often takes place after player has built a route to that enterprise. It is not uncommon for a enterprise to close just before the arrival of the first delivery. This can be very annoying, especially when a player has spent a lot of time building the line, there is no way to fund a new enterprise and has to start all over again.
![Annoying closing](https://user-images.githubusercontent.com/67662046/172730299-703648ff-8ba7-4b8e-b261-5d69d71e4122.png)

In the case of mining enterprises, the situation is clear and although there is some risk, player is able to assess its level and take it consciously.

This issue was reported on tt-forums 2.5 years ago ([here](https://www.tt-forums.net/viewtopic.php?p=1226845#p1226845)). The above graphics are from that topic.
I'm writing this because of another enterprise closure bug report #9918.

### Steps to reproduce

1. Open the included save 
[Closing Industries Show LTD, 1955-11-16.zip](https://github.com/OpenTTD/OpenTTD/files/8865497/Closing.Industries.Show.LTD.1955-11-16.zip)

2. Do nothing, just watch (use fast forward).
3. Imagine that you have built a connection between the iron ore mine (X) and the steel mill (A)
4. You let the first train from the station
5. Steel mill (A) announces closure while train is on its way (January 1956)
6. So you decide to rebuild the connection to another nearby steel mill (B)
7. During the reconstruction, second steel mill (B) announces its closure (March 1956)
8. You have little money so you decide to remove all the railroad tracks to get some of the funds back and start building up to the third steel mill (C)
9. The third steel mill (C) also closes before the arrival of the train. (October 1956)

Such a scenario never happened to me, but as save shows, it is possible! The three steel mills closest to the player's station have been closed one after the other. Of course, without any warning and no possibility to do anything.

**Reproducing this scenario is not entirely possible because building any station resets the order of enterprises closings.**

![from the nightmare](https://user-images.githubusercontent.com/67662046/172735060-c7776635-743f-4532-af59-5d60ace3c278.png)

**Comment by nielsmh** [comment]
This is just asking for changing the game rules. Processing industries don't _plan_ their closure, they just have a risk every production change (which might happen at month change) to close, if they don't produce anything for 5 years.

Changing them to announce risk of closure and give a grace period will be problematic with NewGRF industries, because those can control their closure or not in the production change callback. They will then still be closing with no warning, and you'd instead be complaining that things are inconsistent between built-in and _some_ NewGRF industries. Because NewGRF industries that don't use the production change callback still use the default rules.
If you instead changed NewGRF industries that do use the production change callback to request closure, then they would suddenly potentially have their internal constraints violated. If the industry requests to close, and then does not, it might suddenly be moving into undefined behaviour, and then you'd be filing bugs with the NewGRF author that are not their fault, but because you changed the carpet they were walking on.

**Comment by LC-Zorg** [comment]
Changing the game rules? Technically, probably yes, but from a gameplay point of view, for players it would not be a change of rules (enterprises would also be randomly shut down after at least 5 years of out of service), but merely the removal of the annoying point of the game, which is closing without any warning.

I understand adding a warning could be problematic...

Then maybe some other solution would be possible? Maybe the construction of a station next to the enterprise could be read similarly to the delivery of cargo?

**Comment by nielsmh** [comment]
> Then maybe some other solution would be possible? Maybe the construction of a station next to the enterprise could be read similarly to the delivery of cargo?

You have no guarantee that a NewGRF industry with production callbacks will take the delivery of zero units of cargo to refresh any internal timers. (And giving the industry actual cargo delivered, just by building a station, would be its own problem too.)

I agree this is an annoying behaviour in the game, but I also don't see any way to change it that won't bring its own problems or inconsistencies. I'd be most inclined to close this as "not fixable" but really hope someone else can give a second opinion too.

**Comment by LordAro** [comment]
Ultimately agree with niels here - it's annoying, but there's nothing we can do about it as it's part of the OG game that we cannot change. If you want different behaviour, there are NewGRFs, GameScripts, or the "frozen" economy mode as workarounds
