### ISSUE TITLE
[Bug]: SSE4.1 is mandatory when SSE optimizations are enabled

### ISSUE THREAD

**Issue by trey92r** [OpenTTD/OpenTTD#9935]
### Version of OpenTTD

1.11+/Linux

### Expected result

There are processors which don't support SSE4.1 but could take advantage of SSE2 and SSSE3 optimizations in the codebase. Please consider pushing the build of "viewport_sprite_sorter_sse4.cpp" only when the processor supports SSE4.1 or when SSE4.1 is explicitly enabled at the build time.

### Actual result

Some SSE4.1-only code are built and used when SSE_FOUND and WITH_SSE are true, causing a crash due to illegal instruction on processors without SSE4.1.

### Steps to reproduce

Compile and run OpenTTD (Linux) on a processor that only has support to SSE2/SSSE3.

**Comment by glx22** [comment]
There's a runtime cpu check for this case via `ViewportSortParentSpritesSSE41Checker`, could it be this function triggering illegal instruction ?

**Comment by trey92r** [comment]
Crashlog:
[crash20220627173644.log](https://github.com/OpenTTD/OpenTTD/files/8994552/crash20220627173644.log)

If I remove viewport_sprite_sorter_sse4.cpp from the build system and `ViewportSortParentSpritesSSE41Checker` and `ViewportSortParentSpritesSSE41` in viewport.cpp and viewport_sprite_sorter.h, it works fine.

**Comment by trey92r** [comment]
Maybe something in the build system?

Alpine folks are apparently hitting the same error. They just decided to make FindSSE.cmake fails.

https://gitlab.alpinelinux.org/alpine/aports/-/commit/631059433ebe8b46a288746a64d4ab1699be1558

**Comment by nielsmh** [comment]
Okay yeah this is wrong.
https://github.com/OpenTTD/OpenTTD/blob/ffd3c11ba7d3abd3dc3e387df24c157f281c8d15/cmake/FindSSE.cmake#L7-L9

The test is for "does the compiler have the include files for MMX and SSE intrinsics", but then sets the `-msse4.1` flag which tells the compiler to _use SSE 4.1 instructions in all code_, including code not using any intrinsics. This means it might e.g. translate a loop of naive pairwise additions into something using MMX or SSE instructions.

The `-msse4.1` flag is not required to use the intrinsics, but rather just means the compiler might generate a binary that will never run on anything without SSE4.1 support.

**Comment by trey92r** [comment]
It still fails. Crashlog:
[crash20220628171620.log](https://github.com/OpenTTD/OpenTTD/files/9003348/crash20220628171620.log)

I guess the `ViewportSortParentSpritesSSE41Checker` function should be out of viewport_sprite_sorter_sse4.cpp.

**Comment by glx22** [comment]
`ViewportSortParentSpritesSSE41Checker` is called way before, and seems to return `true`, as it really looks like `ViewportSortParentSpritesSSE41` is called here (at least that's a guess from the call stack).
But that should not be possible if the CPU doesn't support SSE4.1 as `ViewportSortParentSpritesSSE41Checker` should then have return `false`.

**Comment by nielsmh** [comment]
Okay I misunderstood the above. It isn't adding the `-msse4.1` option to every file it compiles. But it still unnecessarily adds it to the files containing SSE4.1 intrinsics code. Those files compile and work perfectly fine without that flag, but can cause code generation to do undesired things.

The other option might be to yes, move the CPU feature flag detection out of the files containing the code getting optimised. For example to `cpu.h` and `cpu.cpp` and just make them generic names so `CanUseSSE41` instead of `ViewportSortParentSpritesSSE41Checker`

**Comment by nielsmh** [comment]
Try removing these lines and see if that fixes things:
https://github.com/OpenTTD/OpenTTD/blob/ffd3c11ba7d3abd3dc3e387df24c157f281c8d15/src/CMakeLists.txt#L28-L36

There might be similar things in the `CMakeLists.txt` files in `blitter/`.

**Comment by JGRennison** [comment]
If you've got gdb installed, you could run openttd through that as that will result in a better stack trace.
`gdb ./openttd` then `run` then `bt`, `disassemble ottd_cpuid` and `disassemble HasCPUIDFlag`.

It's probably also worth checking whether replacing the contents of `ViewportSortParentSpritesSSE41Checker` with `return false` but otherwise leaving everything else the same still causes the issue.

**Comment by trey92r** [comment]
@nielsmh
I already tried that. You do need "-msse4.1" to compile viewport_sprite_sorter_sse4.cpp or the build will fail.

I replaced `return HasCPUIDFlag(1, 2, 19)` in viewport_sprite_sorter_sse4.cpp with `return false`... It doesn't work. Crashlog:
[crash20220628184413.log](https://github.com/OpenTTD/OpenTTD/files/9003872/crash20220628184413.log)

I can give you the gdb info later.

**Comment by JGRennison** [comment]
viewport_sprite_sorter_sse4.cpp does include some non-trivial header files.
In principle, header functions compiled with -msse4.1 could end up referenced by other translation units if the linker de-duplication and/or LTO resulted in the -msse4.1 instances being retained and the others not. I've not actually been able to find any instances of this in binaries I've looked at so far though...

**Comment by nielsmh** [comment]
If it is in fact an ODR thing with some inline functions being compiled with SSE4.1 and then getting chosen for the definition getting linked, perhaps it's worth trying to change the order in CMakeLists.txt so the source files requiring different machine options are listed at the end instead of the beginning.

**Comment by trey92r** [comment]
I was compiling with "-O3" all the time. I'm sorry about that. "-O3" is enough to make OpenTTD crashes.

I did some tests and it works with "-O2" and "-O2 -flto". GCC 11.2.1.
[gdb-O3.txt](https://github.com/OpenTTD/OpenTTD/files/9006789/gdb-O3.txt)
[gdb-O2.txt](https://github.com/OpenTTD/OpenTTD/files/9006792/gdb-O2.txt)
[gdb-O2LTO.txt](https://github.com/OpenTTD/OpenTTD/files/9006793/gdb-O2LTO.txt)

**Comment by glx22** [comment]
I made a quick (and maybe dirty) test on https://github.com/OpenTTD/OpenTTD/compare/master...glx22:OpenTTD:sse

**Comment by trey92r** [comment]
@glx22
That seems to fix it. Worked fine with whatever build flag I used.
Thanks.

**Comment by James103** [comment]
> That seems to fix it. Worked fine with whatever build flag I used.

Which build flag(s) did you use to test? If not `-O3`, does building with `-O3` make the built binary crash?

**Comment by trey92r** [comment]
@James103
I can't reproduce the initial problem with glx22's changes applied to the source code, no matter the flag I use to build the binary.
I did test with "-O3". No errors.

**Comment by nielsmh** [comment]
Were anyone making a PR to fix this?

**Comment by glx22** [comment]
I can PR my test branch.
