### ISSUE TITLE
[Bug]: I don't see wagons with unlimited speed

### ISSUE THREAD

**Issue by milsa** [OpenTTD/OpenTTD#9941]
### Version of OpenTTD

12.2, Windows 10

### Expected result

I don't know what the mistake is. Is it a mistake that I'm seeing wagons with unlimited speed? The electric line allows 265 km/h. So it's probably not a mistake. Apparently it's a mistake that I don't see those unlimited wagons and instead I see wagons for 160. With this error, I can't using the electrified track for speeds higher than 160 for freight trains.

I think it is problem with NeGRFs in my game. But I did not change this list in game during playing.

### Actual result

I have wagons (OpenGFX) with a speed of 160 km/h and unlimited. I have hidden the ones with 160 speed and at this time (1990) I can't buy wagons with unlimited speed. 

### Steps to reproduce

1. Look at the picture.
2. Open save and try to buy wagons with unlimited speed (OpenGFX).

**Comment by milsa** [comment]
I do not see place to add files.

**Comment by milsa** [comment]
![MT, 1992-05-15](https://user-images.githubusercontent.com/1958604/177043973-24f51d14-dec9-449e-a257-a409cb3af3b0.png)
[MT, 1992-05-15.zip](https://github.com/OpenTTD/OpenTTD/files/9034949/MT.1992-05-15.zip)

**Comment by LC-Zorg** [comment]
No, it's not a bug. In the settings you have an option that enables or disables the speed limits of the wagons.
![speed limit of wagons](https://user-images.githubusercontent.com/67662046/177053216-d9a36bb8-83ed-41e7-8eec-fa51cfffa14e.png)

In the case of the default trains, they have no limits, but most, if not all other NewGRF sets with trains have and will be enabled by default. You can turn it off here if you want. :)

**Comment by milsa** [comment]
Ok, thank you.

Then bug is left list with unlimited wagons in picture. Wagons in list is duplicit (speed and unlimited). Correct way is list with speed limit only but not unlimited (in left list on my picture with speed limit on in settings).
