### ISSUE TITLE
[Bug]: Industries created using scenario editor random industries button have their persistent storage cleared

### ISSUE THREAD

**Issue by JGRennison** [OpenTTD/OpenTTD#9951]
### Version of OpenTTD

master

### Expected result

Industry persistent storage values are not cleared after construction.
(Persistent storage values may be set by callbacks such as 15F)

### Actual result

The create random industries button in the scenario editor does not call BasePersistentStorageArray::SwitchMode, therefore persistent storage changes are reverted after construction of the industries.
The other industry construction paths call BasePersistentStorageArray::SwitchMode with the appropriate values.

### Steps to reproduce

1. Add an industry GRF which uses industry persistent storage at construction time such as FIRS 4.4
2. Start scenario editor
3. Click "create random industries" button
4. Use debug button on a primary industry to check persistent storage (compare with an industry created using the build industry command path).

**Comment by andythenorth** [comment]
Known source of FIRS '0 production' bugs.  Adding this comment to help explain those.
