### ISSUE TITLE
[Bug]: AIVehicle::GetBuildWithRefitCapacity() returned  incorrect value when engine was articulated.

### ISSUE THREAD

**Issue by rei-artist** [OpenTTD/OpenTTD#9954]
### Version of OpenTTD

1.12.2, windows 11

### Expected result

AIVehicle::GetBuildWithRefitCapacity() return correct value.
for example Hereford Articulated Hpper Truck (eGRVTS 2.0 NRT) return 60

### Actual result

AIVehicle::GetBuildWithRefitCapacity() returned incorrect value when engine was articulated.
for example Hereford Articulated Hpper Truck (eGRVTS 2.0 NRT)  returned 25

### Steps to reproduce

1. Set NewGRF eGRVTS 2.0 NRT
2. StartGame year 1970
3. Call AIVehicle::GetBuildWithRefitCapacity(engine: Hereford Articulated Hpper Truck cargo:COAL)
Expect 60 but 25 returned

**Comment by glx22** [comment]
Is there a difference if you first build without refitting then use `AIVehicle::GetRefitCapacity()` on the built vehicle ?

**Comment by rei-artist** [comment]
Different from AIVehicle::GetBuildWithRefitCapacity.
AIVehicle::GetRefitCapacity() returned correct value.

**Comment by rei-artist** [comment]
<img width="332" alt="ss 2022-07-19 132240" src="https://user-images.githubusercontent.com/74841537/179664387-9b932e66-14aa-47a7-80ca-ee72f867c9e6.png">

I noticed that the vehicle is also displaying the weight incorrectly.
45 - 20 = 25 (GetBuildWithRefitCapacity returned value) != 60 (GetRefitCapacityreturned value)

**Comment by rei-artist** [comment]
<img width="566" alt="ss 122854" src="https://user-images.githubusercontent.com/74841537/206827644-6f426cc3-801c-475a-a2bb-fe4e1f304326.png">
There is a possible issue regarding Max Tractive Effort, as the only way for AI to get Max T.E. on load is to use this API, so a change in the API could affect AI as well. If this modification is made, we will need a separate API to get the Max T.E. on load and it may need to be displayed in the purchase window as well. Otherwise, it would not be possible to determine if the slope can be climbed before purchase.

Translated with www.DeepL.com/Translator (free version)

**Comment by rei-artist** [comment]
I closed this issue by mistake.
