### ISSUE TITLE
[Crash]: Seg fault 11

### ISSUE THREAD

**Issue by sbibauw** [OpenTTD/OpenTTD#9956]
### Version of OpenTTD

12.2, macOS 12.4 (Intel)

### Steps to reproduce

1. Had installed some modules + started a scenario.
2. Restarted the game.
3. Installed abase.
4. Activated abase in the options.
5. Crash

### Upload crash files

[Archive.zip](https://github.com/OpenTTD/OpenTTD/files/9186685/Archive.zip)

**Comment by glx22** [comment]
Might be a duplicate of #9876

**Comment by LordAro** [comment]
Duplicates #9876
