### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by wazzan** [OpenTTD/OpenTTD#9960]
### Version of OpenTTD

MAC OS X 12.4 (21F79)

### Steps to reproduce

Game crashed upon startup

### Upload crash files

[Archive.zip](https://github.com/OpenTTD/OpenTTD/files/9210054/Archive.zip)

**Comment by glx22** [comment]
Likely duplicate of #9956 (same trace)

**Comment by wazzan** [comment]
This is fresh start of the game, cannot even get to the menu page or start page.

**Comment by LordAro** [comment]
Duplicates #9876
