### ISSUE TITLE
[Bug]: 'server_advertise' is an unknown setting.

### ISSUE THREAD

**Issue by yhorndt** [OpenTTD/OpenTTD#9962]
### Version of OpenTTD

12.2 Debian (10) Linux

### Expected result

I was hoping to hide my server from the public list, by entering 
`setting server_advertise = false`
in the command line.
I also tried to enter it manually into the openttd.cfg file, but that seemed to have no effect.

(I looked at the source and played with the server_game_type settings, but that didn't change much as well..)

### Actual result

I got the message: 
`'server_advertise' is an unknown setting.`

### Steps to reproduce

1. Build from source 
2. `sudo cmake .. -DOPTION_DEDICATED=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo`
3. start openttd as dedicated
4. `setting server_password xyz`
5. `saveconfig`
6. `setting server_advertise`

**Comment by TrueBrain** [comment]
This setting has been renamed in 12 to `server_game_type`, and can contain `local`, `invite-only` or `public` (similar as they are called in the in-game client).

`local` is similar to what `false` was for `server_advertise`, where `public` is similar to `true`. `invite-only` is new, and sits in between: your server is not listed, but friends can join based on the invite-code.

Hope this helps!

**Comment by yhorndt** [comment]
Ah thanks, I got it!
I had set server_game_type to 0, but it still showed in my list.
I have now removed the server from my private.cfg config and can't see it in the list anymore.
