### ISSUE TITLE
[Crash]: Freeze then crash on start

### ISSUE THREAD

**Issue by JakubR01** [OpenTTD/OpenTTD#9964]
### Version of OpenTTD

12.2 Steam on Kde Neon latest with 5.25 Plasma

### Steps to reproduce

1. Run game from Steam
2. Freeze
3. Crash

### Upload crash files

[crash20220812085756..zip](https://github.com/OpenTTD/OpenTTD/files/9329509/crash20220812085756.zip)

**Comment by glx22** [comment]
You could try to add `-v sdl` in launch options (openttd properties in steam)

**Comment by JakubR01** [comment]
It works. Thank you.

**Comment by TrueBrain** [comment]
Given we received no other reports of a similar crash, and it has been over a year, I am going to assume this problem is resolved sufficiently.

Enjoy the game!
