### ISSUE TITLE
[Bug]: Command line option for help (`-h`) prints just the version and no other info.

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#9966]
### Version of OpenTTD

20220809-master-gbe352ce1b6 on Windows 10, 64-bit (via Steam)

### Expected result

`openttd -h` should print the version of OpenTTD, followed by a list of command line options, then a list of graphics, sound, and music sets, music, sound, and video drivers, blitters, and finally a list of AIs and Game Scripts.

### Actual result

`openttd -h` only prints the version of OpenTTD and nothing else.

### Steps to reproduce

1. Run `openttd -h` from the master branch.
2. Notice that the output is truncated and only contains the version name.
3. Run `openttd -h` from a JGRPP 0.48.1 installation.
4. Notice that the output contains the version name, followed by command line options and other info (as expected).

**Comment by TrueBrain** [comment]
Only a problem on Windows; on other OSes it is fine.

I am guessing that this line is in error:
https://github.com/OpenTTD/OpenTTD/blob/be352ce1b6f3d468270f50875151417773d1a7df/src/openttd.cpp#L243

**Comment by James103** [comment]
Looking at the ShowInfo function specifically, it is identical in both master (be352ce1b6) and JGRPP (0.48.1), with the last update touching the function being 2 years ago according to `git blame`.
https://github.com/OpenTTD/OpenTTD/blob/be352ce1b6f3d468270f50875151417773d1a7df/src/os/windows/win32.cpp#L355

**Comment by glx22** [comment]
Just tested.
Debug build opens a console then prints the full help message in it before closing it with the exe.
Release build opens a dialog box to display the full help message, then wait for it to be closed.
Everything seems to work as expected for me.

**Comment by James103** [comment]
Here is the DxDiag file for my system: [DxDiag.txt](https://github.com/OpenTTD/OpenTTD/files/9334189/DxDiag.txt)

Can you please attach the output file from running `dxdiag`, waiting for the progress to finish, then clicking "Save All Information"?

**Comment by glx22** [comment]
Did more tests, and Steam build only shows the version in help dialog, while it shows the full text in console with `-d -h`.

**Comment by NyanGoat** [comment]
Went through and checked the previous nightlies:
openttd-20220210-master-g41c40f130b-windows-win64: Works.
openttd-20220222-master-g22f6502b14-windows-win64: Stopped working.

**Comment by glx22** [comment]
Finally found the issue. It's caused by VS2022 compiler silently converting `*q++ = '\r';` into `q++;` when optimising.
I reported the issue [here](https://developercommunity2.visualstudio.com/t/Optimization-generates-incorrect-code-v/10122149)

**Comment by James103** [comment]
Will you please update your Visual Studio 2022 version to 17.3.1 or later then rebuild/retest?
According to the linked bug report, the issue appears to be fixed in that later version.

**Comment by glx22** [comment]
They suggested a [workaround](https://developercommunity.visualstudio.com/t/Optimization-generates-incorrect-code-v/10122149#T-ND10145010)
