### ISSUE TITLE
[Bug]: vehicle_is_not_powered is incorrect for parts of the articulated vehicle

### ISSUE THREAD

**Issue by George-VB** [OpenTTD/OpenTTD#9970]
### Version of OpenTTD

nb 20220725 on Windows 10

### Expected result

when articulated vehicle (train) runs on wrong rails, I expect vehicle_is_not_powered to be 1 for each part of the articulated vehicle (https://newgrf-specs.tt-wiki.net/wiki/NML:Vehicles)

Used code
switch (FEAT_TRAINS, SELF, vl8_sprites_right_notpowered, vehicle_is_not_powered)  
{ 1: vl8_notpowered_sprites_right_down;  
     vl8_sprites_right2; }

Note:
I've tried 
switch (FEAT_TRAINS, SELF, vl8_sprites_right_notpowered, 
[ STORE_TEMP(-position_in_articulated_veh, 0x10F), vehicle_is_not_powered ])  
{ 1: vl8_notpowered_sprites_right_down;  
     vl8_sprites_right2; }

but it does not work either

### Actual result

Only the first part of he articulated vehicle gets vehicle_is_not_powered = 1. Other parts do not. 
![image](https://user-images.githubusercontent.com/43310520/185682404-da7d4b21-85b7-4608-878b-6581d6f0ebc7.png)

### Steps to reproduce

1) install xUSSRse v0.7RC2  https://github.com/George-VB/xussrset/releases/tag/0.7
2) open attached savegame 
[DC+DS (Mach).zip](https://github.com/OpenTTD/OpenTTD/files/9384563/DC%2BDS.Mach.zip)
3) the second part of VL8 has wrong graphics

**Comment by frosch123** [comment]
Currently articulared parts are not considerer powered or unpowered. So, independent of the tracktype, both `vehicle_is_powered` and `vehicle_is_not_powered` are always false.

To access variables of other vehicles, you have to use variable 61. NML has no simple syntax for this, you have to go the NFO route:
```
[ STORE_TEMP(-position_in_articulated_veh, 0x10F), var[0x61, 6, 1, 0xFE] ])
```
