### ISSUE TITLE
[Bug]: Unused space in frame rate window (where texture doesn't update) in German language

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#9972]
### Version of OpenTTD

88a046a7 on Windows 10, 64-bit (via Steam)

### Expected result

The black part (unused, non-refreshing space) in the lower right corner of the frame rate window should not be there regardless of language.

### Actual result

When the language is set to German and the game is paused, the frame rate window has unused space in the lower right corner that does not redraw properly, creating "hall-of-mirrors" effects.
![image](https://user-images.githubusercontent.com/37945304/185719778-fc670f01-a559-451a-849d-9dfcca45c946.png)

### Steps to reproduce

1. Set language to German.
2. Start a new game or load a saved game.
3. Pause the game.
4. Open the frame rate window.
5. Notice unused, non-refreshing space in the lower right corner.
6. Set language to English.
7. Notice the unused, non-refreshing space is gone.

Discovered while testing #9971

**Comment by nielsmh** [comment]
Just to be precise, pausing the game is not required to reproduce this. It depends on font selection, interface scale, etc. as well. And if any AI or GS are loaded, then the additional memory usage column takes the problem away.

![image](https://user-images.githubusercontent.com/1062071/187041999-310ab476-b12a-4a49-a1c5-f1cdcad01899.png)

Making the UI adjust to correct size is quite annoying.
