### ISSUE TITLE
[Bug]: `getsysdate` returns a blank value (instead of the current date and time)

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#9974]
### Version of OpenTTD

882b8f45d9 on Windows 10, 64-bit (via Steam)

### Expected result

`getsysdate` should return the current date and time.

### Actual result

`getsysdate` returns a blank value, as shown below.

```
getsysdate
System Date: 
```

### Steps to reproduce

1. Run OpenTTD.
2. Run `getsysdate` from the console.
3. Notice it returns a blank value.

Tested on master 882b8f45d9, JGRPP 0.47.2, and JGRPP 0.48.1. All three versions return a blank value when running `getsysdate`.

**Comment by JGRennison** [comment]
The buffer is one byte too small (due to the null terminator).
strftime returns 0 and the contents of the output buffer is undefined in this case.
On Linux I get a result like "2022-08-23 15:00:h" followed by some unprintables.
