### ISSUE TITLE
[Bug]: Missing electric traction railways in some landscapes

### ISSUE THREAD

**Issue by ferenczy** [OpenTTD/OpenTTD#9976]
### Version of OpenTTD

12.2 (MacOs, Android)

### Expected result

Electric railways are available in all landscapes (default game setup).

In the "Temperate" landscape, there are both the regular (steam/diesel) and electric railways are available. When all regular locomotives "expire", I can simply electrify tracks and start using the electric locomotives. I would expect the same in other available landscapes, I don't understand why the electric railways shouldn't be available there.

### Actual result

In all landscapes other than "Temperate", the electric railways are not available at all. If I build a large network of tracks and all regular locomotives "expire", I'm basically stuck and the only option is to rebuild the whole network into a monorail or maglev system (often not realistic on a really complex network).

It should be possible to add the electric railways into other landscapes by installing a NewGRF extension, but I don't want to change the existing electric railways, I just want to have the same electric railways as are available in the "Temperate" landscape also in other landscapes in the default setup of the game. Without it, it's just a dead end when all regular locomotives expire around the year 2020 and existing locomotives get old and have to be exchanged for new ones.

Also, I would consider changing of the expiration date of the regular (diesel) locomotives as it's not realistic for them to disappear around the year 2020.

### Steps to reproduce

1. Start a new game with the following parameters: Sub-tropical landscape, year 2030
2. Build a regular railways train depot
3. Open the depot window a click _New Vehicles_
4. There are no locomotives available to buy and also there are not electric railways available

**Comment by PeterN** [comment]
There literally aren't any electric engines in the default engine list in those climates. The default engine list is climate dependent. You can only add some with NewGRFs.

Not a bug.

**Comment by ferenczy** [comment]
Thank you for your reply, but that's exactly what I have described in my post. I just don't understand what's the reason for that.

I'll explain why I consider it a bug: I have installed and played OpenTTD after several year recently. I always used to play the Sub-tropical scenario because I like it. I have built a large and complex network of regular tracks and everything went went until about the year 2015 when all regular locomotives have expired. I had to abandon the game since there was no way to continue as existing locomotives got old and needed a replace.

I know I can install a NewGRF extension, but I don't know which one, there are literary hundreds of them. I have no idea if there's one that simply adds the electric locomotives from the Temperate landscape to other landscapes without changing them.

I don't think that the game should allow such a dead end in the default setup without requiring to install any additional extensions.

And mainly, I don't understand what's the reason for not having the electric railways in other landscapes. It doesn't reflect the reality. So what's the reason for that?

**Comment by nielsmh** [comment]
The reason is that it's how Transport Tycoon Deluxe (1995) was. The default game data in OpenTTD reflect Transport Tycoon Deluxe.
I believe that you still get access to Monorail and Maglev in the other climates. The game intends you to gradually replace your routes with the futuristic rail types.

If you don't want to use monorail/maglev, you can instead enable the "Vehicles never expire" game setting. If you enable it around 1990 you should keep the vehicles that were available at that time while those that previously expired stay expired.

If you have an existing game you want to re-enable all vehicle types in, you can enable "Vehicles never expire" and then open the game console and type the command ´resetengines´. That will make all vehicle types available again.

This is not a bug, and not a change that will be made, as it goes against the goals for the project.

**Comment by andythenorth** [comment]
Try 'OGFX+ Trains' as a grf.  There is a parameter option that enables wider ranges of the default vehicles.

<img width="718" alt="image" src="https://user-images.githubusercontent.com/1780327/186388144-5a3a28ba-9f33-4c75-9dee-4585a4511d7d.png">

**Comment by ferenczy** [comment]
@andythenorth Thank you for the suggestion, but I wasn't able to find it using the Content Downloading dialog:

![image](https://user-images.githubusercontent.com/1712992/186395546-89aea764-697c-4737-8b02-a8adfbb08850.png)

@nielsmh I don't want to disable the vehicle expiration, I just want to have the electric railways available in the Sub-tropic landscape. Anyway, thank you for the explanation. I don't like it, I think it's bad for the game, but it looks like it will stay like that.

Anyway, I used to play the good ol' TTD quite a lot, like 20 years ago, I always used to play the Sub-tropical landscape, got to the year 2050 and further many times and I don't remember I would ever end up in this state (without available locomotives). That's why I was so surprised when it happened now. Of course, I don't remember details (game settings, etc.).

Also, thanks for the `resetengines` command suggestion, I didn't know about that!

**Comment by nielsmh** [comment]
OGFX+ is abbreviating OpenGFX+, search for that :)

**Comment by ferenczy** [comment]
@nielsmh I see, that's much better ;), thanks!

@andythenorth Installed all OpenGFX+ addons, configured them and finally it works as I would expect in the Sub-tropical landscape. Thank you!
