### ISSUE TITLE
[Bug]: FindAllegro.cmake doesn't find Allegro v5.2.8

### ISSUE THREAD

**Issue by krysclarke** [OpenTTD/OpenTTD#9981]
### Version of OpenTTD

12.0-beta2 Linux

### Expected result

cmake finds /usr/lib/x86_64-linux-gnu/liballegro.so

### Actual result

cmake doesn't find /usr/lib/x86_64-linux-gnu/liballegro.so (from v5.2.8) but does find /usr/lib/x86_64-linux-gnu/liballeg.so (from v4.4.3.1)

### Steps to reproduce

1. Clone OpenTTD master repository within VS Code
2. run cmake to detect everything.
3. apt-get install liballegro5-dev
4. re-run cmake and note that it didn't find /usr/lib/x86_64-linux-gnu/liballegro.so
5. apt-get install liballegro4-dev
6. re-run cmake again, it does find /usr/lib/x86_64-linux-gnu/liballeg.so

**Comment by glx22** [comment]
We explicitly did it (https://github.com/OpenTTD/OpenTTD/commit/9322b40df1bf0987a440404fbb2c72dfb4410ba3) because our code use v4.

**Comment by LordAro** [comment]
Closing as wontfix. PR for Allegro5 support would be accepted!
