### ISSUE TITLE
[Bug]: "Net Profit" shows "-£0" instead of "£0" if that value is zero

### ISSUE THREAD

**Issue by James103** [OpenTTD/OpenTTD#9989]
### Version of OpenTTD

c8399507 on Windows 10, 64-bit (via Steam)

### Expected result

"Net Profit" shows "£0" or "+£0" if that value is zero, such as when a new game just started and is paused on the first tick.
![image](https://user-images.githubusercontent.com/37945304/188036048-784ce665-d78d-42e3-a0bb-16cbe81cbd38.png)

(Note that the image above shows a plain "£0", but "+£0" should be fine as well)

### Actual result

"Net Profit" shows "-£0" as if the value "0" is interpreted as negative (even though it's neither negative or positive).
![image](https://user-images.githubusercontent.com/37945304/188036030-0b916712-eaf0-45d2-bb38-c5ec4d7de80e.png)

### Steps to reproduce

1. Start a new game.
2. Pause the game.
3. Check the company finances window.
4. Notice an item in the "Net Profit" row says "-£0" where it should say "£0".

**Comment by nielsmh** [comment]
Should just be the `<` here that needs to be changed to `<=`.
https://github.com/OpenTTD/OpenTTD/blob/c839950791e3adee28e5e21730b35b100bb95451/src/company_gui.cpp#L206-L223

**Comment by LordAro** [comment]
What I don't understand is how it just displays "£0" for the first tick, when the only possible strings it should be using are "-£0" or "+£0"

**Comment by 2TallTyler** [comment]
@LordAro I think you're confusing the Expected and Actual screenshots. 😉
